In [1]:
# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
fused_df_named_int = pd.read_csv('/content/drive//MyDrive/par-rest.csv')
fused_df_named_int.head()

,feat_0,feat_1,feat_2,feat_3,feat_4,feat_5,feat_6,feat_7,feat_8,feat_9,...,feat_23,feat_24,feat_25,feat_26,feat_27,feat_28,feat_29,feat_30,feat_31,PD_Label_Combined
0,-0.012186,-0.242798,0.211955,-0.160821,-0.349731,0.206071,-0.035737,0.214398,0.037981,-0.006974,...,0.137540,-0.160455,-0.271169,-0.093879,-0.173949,-0.141305,0.172487,0.109752,-0.024355,1
1,0.087441,-0.137109,0.237290,0.187446,-0.029030,-0.078206,0.246426,-0.176444,-0.205465,-0.180480,...,0.127048,-0.128230,0.238130,0.211441,-0.247213,0.162762,0.005994,-0.129804,0.303167,1
2,0.051393,-0.216597,0.221062,-0.168011,-0.326128,0.184495,-0.004922,0.213458,0.099279,0.024897,...,0.057531,-0.161128,-0.235423,-0.075906,-0.206909,-0.124901,0.233371,0.128156,0.019849,0
3,-0.160189,-0.281906,0.161437,0.190605,-0.135677,-0.167509,-0.101194,-0.114843,-0.063206,0.097344,...,0.302572,-0.225723,-0.163523,0.298178,0.242114,-0.049313,-0.204896,0.152081,-0.115680,1
4,0.117965,0.233021,0.214486,-0.008514,-0.086752,0.019917,-0.214910,-0.170774,0.145858,-0.108719,...,0.215618,0.231745,0.029170,0.208857,-0.181698,0.036961,-0.212452,0.130756,-0.122318,1

In [4]:

# ============================================================
# ENSEMBLE CLASSIFICATION WITH 95% CONFIDENCE INTERVALS
# Stratified 10-Fold CV + Independent Test Set
#
# Models:
#   1. CatBoost
#   2. Gradient Boosting
#   3. Bagging
#   4. AdaBoost
#   5. Extra Trees
#
# Metrics with 95% CI:
# Accuracy, Precision, Sensitivity, Specificity, F1, AUC
#
# Additional metrics:
# Balanced Accuracy, MCC
#
# Notes:
#   - 90% training / 10% independent test split
#   - Stratified 10-fold CV on the training set
#   - Median imputation fitted within each training partition
#   - Wilson CIs for Accuracy, Precision, Sensitivity, Specificity
#   - Stratified bootstrap CIs for F1 and AUC
# ============================================================

!pip install -q catboost scikit-learn statsmodels pandas numpy

import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

from sklearn.model_selection import (
    train_test_split,
    StratifiedKFold
)

from sklearn.impute import SimpleImputer
from sklearn.tree import DecisionTreeClassifier

from sklearn.ensemble import (
    GradientBoostingClassifier,
    BaggingClassifier,
    AdaBoostClassifier,
    ExtraTreesClassifier
)

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    balanced_accuracy_score,
    matthews_corrcoef,
    confusion_matrix
)

from statsmodels.stats.proportion import proportion_confint
from catboost import CatBoostClassifier


# ============================================================
# STEP 1: PREPARE DATA
# ============================================================

feature_cols = [f"feat_{i}" for i in range(32)]

X = fused_df_named_int[feature_cols].copy()
y = fused_df_named_int["PD_Label_Combined"].copy()

X = X.apply(pd.to_numeric, errors="coerce")
X = X.replace([np.inf, -np.inf], np.nan)
y = pd.to_numeric(y, errors="coerce")

valid = y.notna()

X = X.loc[valid].reset_index(drop=True)
y = y.loc[valid].astype(int).reset_index(drop=True)

if set(y.unique()) != {0, 1}:
    raise ValueError("Labels must be encoded as 0 and 1.")

if X.shape[1] != 32:
    raise ValueError("Expected exactly 32 embedding features.")

if y.value_counts().min() < 10:
    raise ValueError(
        "Each class needs at least 10 samples for stratified "
        "10-fold cross-validation."
    )

print("X shape:", X.shape)
print("\nClass distribution:")
print(y.value_counts().sort_index())


# ============================================================
# STEP 2: TRAIN-TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.10,
    stratify=y,
    random_state=42
)

print("\nTraining shape:", X_train.shape)
print("Test shape:", X_test.shape)

print("\nTraining class distribution:")
print(y_train.value_counts().sort_index())

print("\nIndependent test class distribution:")
print(y_test.value_counts().sort_index())


# ============================================================
# STEP 3: MODEL FACTORY
# ============================================================

def create_models(y_fit):

    # Class imbalance ratio for CatBoost.
    n_negative = int((y_fit == 0).sum())
    n_positive = int((y_fit == 1).sum())

    scale_pos_weight = n_negative / max(n_positive, 1)

    # --------------------------------------------------------
    # 1. CatBoost
    # --------------------------------------------------------
    catboost = CatBoostClassifier(
        iterations=500,
        depth=5,
        learning_rate=0.03,
        loss_function="Logloss",
        eval_metric="Logloss",
        l2_leaf_reg=5.0,
        scale_pos_weight=scale_pos_weight,
        random_seed=42,
        verbose=False,
        allow_writing_files=False,
        thread_count=-1
    )



    # --------------------------------------------------------
    # 2. Bagging
    # --------------------------------------------------------
    # Use a decision tree as the base estimator.
    # The constructor below supports newer scikit-learn.
    bagging = BaggingClassifier(
        estimator=DecisionTreeClassifier(
            max_depth=None,
            min_samples_split=5,
            min_samples_leaf=2,
            class_weight="balanced",
            random_state=42
        ),
        n_estimators=200,
        max_samples=0.85,
        max_features=0.90,
        bootstrap=True,
        bootstrap_features=False,
        n_jobs=-1,
        random_state=42
    )

    # --------------------------------------------------------
    # 3. AdaBoost
    # --------------------------------------------------------
    adaboost = AdaBoostClassifier(
        estimator=DecisionTreeClassifier(
            max_depth=1,
            min_samples_leaf=3,
            random_state=42
        ),
        n_estimators=200,
        learning_rate=0.03,
        random_state=42
    )

    # --------------------------------------------------------
    # 4. Extra Trees
    # --------------------------------------------------------
    extra_trees = ExtraTreesClassifier(
        n_estimators=500,
        max_depth=None,
        min_samples_split=5,
        min_samples_leaf=2,
        max_features="sqrt",
        class_weight="balanced",
        bootstrap=False,
        n_jobs=-1,
        random_state=42
    )

    return {
        "CatBoost": catboost,
        "Bagging": bagging,
        "AdaBoost": adaboost,
        "Extra Trees": extra_trees
    }


# ============================================================
# STEP 4: METRICS + 95% CONFIDENCE INTERVALS
# ============================================================

def calculate_metrics_with_ci(
    y_true,
    y_pred,
    y_prob,
    n_boot=2000,
    random_state=42
):

    y_true = np.asarray(y_true).astype(int)
    y_pred = np.asarray(y_pred).astype(int)
    y_prob = np.asarray(y_prob, dtype=float)

    tn, fp, fn, tp = confusion_matrix(
        y_true,
        y_pred,
        labels=[0, 1]
    ).ravel()

    n = len(y_true)

    # ---------------- Point estimates ----------------

    accuracy = accuracy_score(y_true, y_pred)

    precision = precision_score(
        y_true, y_pred, zero_division=0
    )

    sensitivity = recall_score(
        y_true, y_pred, zero_division=0
    )

    specificity = (
        tn / (tn + fp) if (tn + fp) > 0 else np.nan
    )

    f1 = f1_score(
        y_true, y_pred, zero_division=0
    )

    auc = roc_auc_score(y_true, y_prob)

    results = {
        "Accuracy": accuracy,
        "Precision": precision,
        "Sensitivity": sensitivity,
        "Specificity": specificity,
        "F1": f1,
        "AUC": auc,
        "Balanced Accuracy": balanced_accuracy_score(
            y_true, y_pred
        ),
        "MCC": matthews_corrcoef(y_true, y_pred),
        "TN": tn,
        "FP": fp,
        "FN": fn,
        "TP": tp
    }

    # ---------------- Wilson 95% CIs ----------------

    proportions = {
        "Accuracy": (tp + tn, n),
        "Precision": (tp, tp + fp),
        "Sensitivity": (tp, tp + fn),
        "Specificity": (tn, tn + fp)
    }

    for metric, (count, denominator) in proportions.items():

        if denominator > 0:
            low, high = proportion_confint(
                count=count,
                nobs=denominator,
                alpha=0.05,
                method="wilson"
            )
        else:
            low, high = np.nan, np.nan

        results[f"{metric} CI Low"] = low
        results[f"{metric} CI High"] = high

    # ---------------- Stratified bootstrap CIs ----------------
    # Resample each class separately, preserving the class counts.
    # Predictions and probabilities remain paired with labels.

    rng = np.random.default_rng(random_state)

    class_indices = [
        np.flatnonzero(y_true == 0),
        np.flatnonzero(y_true == 1)
    ]

    bootstrap_f1 = []
    bootstrap_auc = []

    for _ in range(n_boot):

        sampled_indices = np.concatenate([
            rng.choice(
                indices,
                size=len(indices),
                replace=True
            )
            for indices in class_indices
        ])

        yt = y_true[sampled_indices]
        yp = y_pred[sampled_indices]
        pr = y_prob[sampled_indices]

        bootstrap_f1.append(
            f1_score(yt, yp, zero_division=0)
        )

        bootstrap_auc.append(
            roc_auc_score(yt, pr)
        )

    for metric, values in [
        ("F1", bootstrap_f1),
        ("AUC", bootstrap_auc)
    ]:

        low, high = np.percentile(
            values,
            [2.5, 97.5]
        )

        results[f"{metric} CI Low"] = low
        results[f"{metric} CI High"] = high

    return results


# ============================================================
# STEP 5: PREPROCESSING
# ============================================================

def make_preprocessor():
    return SimpleImputer(strategy="median")


# ============================================================
# STEP 6: STRATIFIED 10-FOLD CROSS-VALIDATION
# ============================================================

skf = StratifiedKFold(
    n_splits=10,
    shuffle=True,
    random_state=42
)

model_names = [
    "CatBoost",
    "Bagging",
    "AdaBoost",
    "Extra Trees"
]

cv_records = []
cv_summary_records = []
test_records = []
confusion_matrices = {}

metrics_to_report = [
    "Accuracy",
    "Precision",
    "Sensitivity",
    "Specificity",
    "F1",
    "AUC"
]


for model_name in model_names:

    print("\n" + "=" * 85)
    print("EVALUATING:", model_name)
    print("=" * 85)

    fold_metrics = []

    for fold, (train_idx, val_idx) in enumerate(
        skf.split(X_train, y_train),
        start=1
    ):

        X_tr = X_train.iloc[train_idx]
        X_val = X_train.iloc[val_idx]

        y_tr = y_train.iloc[train_idx]
        y_val = y_train.iloc[val_idx]

        # Fit imputation only on this fold's training partition.
        imputer = make_preprocessor()

        X_tr_imp = imputer.fit_transform(X_tr)
        X_val_imp = imputer.transform(X_val)

        # Construct a fresh model for each fold.
        models = create_models(y_tr)
        model = models[model_name]

        model.fit(X_tr_imp, y_tr)

        val_pred = np.asarray(
            model.predict(X_val_imp)
        ).reshape(-1).astype(int)

        val_prob = model.predict_proba(X_val_imp)[:, 1]

        metrics = calculate_metrics_with_ci(
            y_val,
            val_pred,
            val_prob,
            n_boot=2000,
            random_state=1000 + fold
        )

        metrics["Model"] = model_name
        metrics["Fold"] = fold

        fold_metrics.append(metrics)
        cv_records.append(metrics.copy())

        # Print metrics and CIs for every fold.
        print(f"\nFold {fold:02d}/10")

        for metric in metrics_to_report:

            print(
                f"{metric:15s}: {metrics[metric]:.4f} "
                f"(95% CI: "
                f"{metrics[metric + ' CI Low']:.4f}-"
                f"{metrics[metric + ' CI High']:.4f})"
            )

    # ========================================================
    # STEP 7: CV MEAN AND STANDARD DEVIATION
    # ========================================================

    fold_df = pd.DataFrame(fold_metrics)

    print(f"\n{model_name} - 10-Fold CV Summary")
    print("-" * 75)

    summary = {"Model": model_name}

    for metric in metrics_to_report:

        mean_val = fold_df[metric].mean()
        std_val = fold_df[metric].std(ddof=1)

        # Descriptive average of the fold CI endpoints.
        # These are NOT a formal pooled 95% CI.
        mean_ci_low = fold_df[
            f"{metric} CI Low"
        ].mean()

        mean_ci_high = fold_df[
            f"{metric} CI High"
        ].mean()

        summary[f"CV {metric} Mean"] = mean_val
        summary[f"CV {metric} SD"] = std_val
        summary[f"Mean Fold {metric} CI Low"] = mean_ci_low
        summary[f"Mean Fold {metric} CI High"] = mean_ci_high

        print(
            f"{metric:15s}: {mean_val:.4f} +/- {std_val:.4f} "
            f"| Mean fold CI: "
            f"{mean_ci_low:.4f}-{mean_ci_high:.4f}"
        )

    for metric in ["Balanced Accuracy", "MCC"]:

        summary[f"CV {metric} Mean"] = fold_df[metric].mean()
        summary[f"CV {metric} SD"] = fold_df[metric].std(ddof=1)

    cv_summary_records.append(summary)

    # ========================================================
    # STEP 8: FINAL MODEL AND INDEPENDENT TEST SET
    # ========================================================

    final_imputer = make_preprocessor()

    X_train_imp = final_imputer.fit_transform(X_train)
    X_test_imp = final_imputer.transform(X_test)

    final_models = create_models(y_train)
    final_model = final_models[model_name]

    final_model.fit(X_train_imp, y_train)

    test_pred = np.asarray(
        final_model.predict(X_test_imp)
    ).reshape(-1).astype(int)

    test_prob = final_model.predict_proba(X_test_imp)[:, 1]

    test_metrics = calculate_metrics_with_ci(
        y_test,
        test_pred,
        test_prob,
        n_boot=5000,
        random_state=2026
    )

    test_metrics["Model"] = model_name
    test_records.append(test_metrics.copy())

    confusion_matrices[model_name] = confusion_matrix(
        y_test,
        test_pred,
        labels=[0, 1]
    )

    print(f"\n{model_name} - Independent Test Set")
    print("-" * 75)

    for metric in metrics_to_report:

        print(
            f"{metric:15s}: {test_metrics[metric]:.4f} "
            f"(95% CI: "
            f"{test_metrics[metric + ' CI Low']:.4f}-"
            f"{test_metrics[metric + ' CI High']:.4f})"
        )

    print(
        f"Balanced Accuracy: "
        f"{test_metrics['Balanced Accuracy']:.4f}"
    )

    print(f"MCC: {test_metrics['MCC']:.4f}")

    print("\nConfusion Matrix (rows=true, columns=predicted):")
    print(confusion_matrices[model_name])


# ============================================================
# STEP 9: INDIVIDUAL FOLD RESULTS WITH 95% CIs
# ============================================================

fold_results_df = pd.DataFrame(cv_records)

fold_columns = [
    "Model", "Fold",
    "Accuracy", "Accuracy CI Low", "Accuracy CI High",
    "Precision", "Precision CI Low", "Precision CI High",
    "Sensitivity", "Sensitivity CI Low", "Sensitivity CI High",
    "Specificity", "Specificity CI Low", "Specificity CI High",
    "F1", "F1 CI Low", "F1 CI High",
    "AUC", "AUC CI Low", "AUC CI High",
    "Balanced Accuracy", "MCC",
    "TN", "FP", "FN", "TP"
]

fold_results_df = fold_results_df[fold_columns]

print("\n" + "=" * 100)
print("ALL MODELS: INDIVIDUAL FOLD RESULTS WITH 95% CIs")
print("=" * 100)

display(
    fold_results_df.sort_values(
        ["Model", "Fold"]
    ).round(4)
)


# ============================================================
# STEP 10: CROSS-VALIDATION SUMMARY
# ============================================================

cv_summary_df = pd.DataFrame(cv_summary_records)

print("\n" + "=" * 100)
print("CROSS-VALIDATION MEAN, SD AND MEAN FOLD CIs")
print("=" * 100)

display(cv_summary_df.round(4))


# ============================================================
# STEP 11: INDEPENDENT TEST RESULTS WITH 95% CIs
# ============================================================

test_results_df = pd.DataFrame(
    test_records
).set_index("Model")

test_columns = [
    "Accuracy", "Accuracy CI Low", "Accuracy CI High",
    "Precision", "Precision CI Low", "Precision CI High",
    "Sensitivity", "Sensitivity CI Low", "Sensitivity CI High",
    "Specificity", "Specificity CI Low", "Specificity CI High",
    "F1", "F1 CI Low", "F1 CI High",
    "AUC", "AUC CI Low", "AUC CI High",
    "Balanced Accuracy", "MCC",
    "TN", "FP", "FN", "TP"
]

test_results_df = test_results_df[test_columns]

print("\n" + "=" * 100)
print("INDEPENDENT TEST SET COMPARISON WITH 95% CIs")
print("=" * 100)

display(
    test_results_df.sort_values(
        by="F1",
        ascending=False
    ).round(4)
)


# ============================================================
# STEP 12: INDIVIDUAL MODEL RESULTS
# ============================================================

print("\n" + "=" * 100)
print("INDIVIDUAL MODEL COMPARISON")
print("=" * 100)

print("\nCross-validation summary:")
display(
    cv_summary_df[
        cv_summary_df["Model"].isin(model_names)
    ].round(4)
)

print("\nIndependent test results:")
display(
    test_results_df.round(4)
)


# ============================================================
# STEP 13: CONFUSION MATRICES FOR ALL MODELS
# ============================================================

print("\n" + "=" * 100)
print("INDEPENDENT TEST CONFUSION MATRICES")
print("=" * 100)

for model_name in model_names:
    print(f"\n{model_name}")
    print("Rows = true labels [HC, PD]")
    print("Columns = predicted labels [HC, PD]")
    print(confusion_matrices[model_name])


# ============================================================
# STEP 14: OPTIONAL SAVE RESULTS AS CSV
# ============================================================

fold_results_df.to_csv(
    "ensemble_fold_results_95CI.csv",
    index=False
)

cv_summary_df.to_csv(
    "ensemble_cv_summary_95CI.csv",
    index=False
)

test_results_df.to_csv(
    "ensemble_independent_test_results_95CI.csv"
)

print("\nSaved result files:")
print("1. ensemble_fold_results_95CI.csv")
print("2. ensemble_cv_summary_95CI.csv")
print("3. ensemble_independent_test_results_95CI.csv")

X shape: (320, 32)

Class distribution:
PD_Label_Combined
0    131
1    189
Name: count, dtype: int64

Training shape: (288, 32)
Test shape: (32, 32)

Training class distribution:
PD_Label_Combined
0    118
1    170
Name: count, dtype: int64

Independent test class distribution:
PD_Label_Combined
0    13
1    19
Name: count, dtype: int64

=====================================================================================
EVALUATING: CatBoost
=====================================================================================

Fold 01/10
Accuracy       : 0.7586 (95% CI: 0.5789-0.8778)
Precision      : 0.7778 (95% CI: 0.5479-0.9100)
Sensitivity    : 0.8235 (95% CI: 0.5897-0.9381)
Specificity    : 0.6667 (95% CI: 0.3906-0.8619)
F1             : 0.8000 (95% CI: 0.6471-0.9143)
AUC            : 0.8627 (95% CI: 0.7059-0.9706)

Fold 02/10
Accuracy       : 0.6897 (95% CI: 0.5077-0.8272)
Precision      : 0.7500 (95% CI: 0.5050-0.8982)
Sensitivity    : 0.7059 (95% CI: 0.4687-0.8672)
Specificity    : 0.6667 (95% CI: 0.3906-0.8619)
F1             : 0.7273 (95% CI: 0.5453-0.8824)
AUC            : 0.7647 (95% CI: 0.5636-0.9364)

Fold 03/10
Accuracy       : 0.7241 (95% CI: 0.5428-0.8530)
Precision      : 0.8000 (95% CI: 0.5481-0.9295)
Sensitivity    : 0.7059 (95% CI: 0.4687-0.8672)
Specificity    : 0.7500 (95% CI: 0.4677-0.9111)
F1             : 0.7500 (95% CI: 0.5598-0.8889)
AUC            : 0.8039 (95% CI: 0.6127-0.9510)

Fold 04/10
Accuracy       : 0.6897 (95% CI: 0.5077-0.8272)
Precision      : 0.7222 (95% CI: 0.4913-0.8750)
Sensitivity    : 0.7647 (95% CI: 0.5274-0.9044)
Specificity    : 0.5833 (95% CI: 0.3195-0.8067)
F1             : 0.7429 (95% CI: 0.5806-0.8824)
AUC            : 0.7647 (95% CI: 0.5735-0.9167)

Fold 05/10
Accuracy       : 0.6897 (95% CI: 0.5077-0.8272)
Precision      : 0.7000 (95% CI: 0.4810-0.8545)
Sensitivity    : 0.8235 (95% CI: 0.5897-0.9381)
Specificity    : 0.5000 (95% CI: 0.2538-0.7462)
F1             : 0.7568 (95% CI: 0.6153-0.8718)
AUC            : 0.7745 (95% CI: 0.5735-0.9216)

Fold 06/10
Accuracy       : 0.6552 (95% CI: 0.4735-0.8006)
Precision      : 0.7059 (95% CI: 0.4687-0.8672)
Sensitivity    : 0.7059 (95% CI: 0.4687-0.8672)
Specificity    : 0.5833 (95% CI: 0.3195-0.8067)
F1             : 0.7059 (95% CI: 0.5333-0.8485)
AUC            : 0.7157 (95% CI: 0.5195-0.8922)

Fold 07/10
Accuracy       : 0.5517 (95% CI: 0.3755-0.7159)
Precision      : 0.6429 (95% CI: 0.3876-0.8366)
Sensitivity    : 0.5294 (95% CI: 0.3096-0.7383)
Specificity    : 0.5833 (95% CI: 0.3195-0.8067)
F1             : 0.5806 (95% CI: 0.3704-0.7586)
AUC            : 0.6275 (95% CI: 0.4167-0.8333)

Fold 08/10
Accuracy       : 0.6207 (95% CI: 0.4400-0.7731)
Precision      : 0.6667 (95% CI: 0.4375-0.8372)
Sensitivity    : 0.7059 (95% CI: 0.4687-0.8672)
Specificity    : 0.5000 (95% CI: 0.2538-0.7462)
F1             : 0.6857 (95% CI: 0.5161-0.8333)
AUC            : 0.6863 (95% CI: 0.4754-0.8775)

Fold 09/10
Accuracy       : 0.6786 (95% CI: 0.4934-0.8207)
Precision      : 0.7222 (95% CI: 0.4913-0.8750)
Sensitivity    : 0.7647 (95% CI: 0.5274-0.9044)
Specificity    : 0.5455 (95% CI: 0.2801-0.7873)
F1             : 0.7429 (95% CI: 0.5882-0.8752)
AUC            : 0.8128 (95% CI: 0.6364-0.9465)

Fold 10/10
Accuracy       : 0.6071 (95% CI: 0.4241-0.7643)
Precision      : 0.6667 (95% CI: 0.4375-0.8372)
Sensitivity    : 0.7059 (95% CI: 0.4687-0.8672)
Specificity    : 0.4545 (95% CI: 0.2127-0.7199)
F1             : 0.6857 (95% CI: 0.5143-0.8333)
AUC            : 0.6738 (95% CI: 0.4385-0.8663)

CatBoost - 10-Fold CV Summary
---------------------------------------------------------------------------
Accuracy       : 0.6665 +/- 0.0601 | Mean fold CI: 0.4851-0.8087
Precision      : 0.7154 +/- 0.0502 | Mean fold CI: 0.4796-0.8720
Sensitivity    : 0.7235 +/- 0.0834 | Mean fold CI: 0.4887-0.8759
Specificity    : 0.5833 +/- 0.0904 | Mean fold CI: 0.3208-0.8055
F1             : 0.7178 +/- 0.0593 | Mean fold CI: 0.5470-0.8589
AUC            : 0.7487 +/- 0.0720 | Mean fold CI: 0.5516-0.9112

CatBoost - Independent Test Set
---------------------------------------------------------------------------
Accuracy       : 0.6875 (95% CI: 0.5143-0.8205)
Precision      : 0.7647 (95% CI: 0.5274-0.9044)
Sensitivity    : 0.6842 (95% CI: 0.4601-0.8464)
Specificity    : 0.6923 (95% CI: 0.4237-0.8732)
F1             : 0.7222 (95% CI: 0.5455-0.8649)
AUC            : 0.6721 (95% CI: 0.4696-0.8623)
Balanced Accuracy: 0.6883
MCC: 0.3706

Confusion Matrix (rows=true, columns=predicted):
[[ 9  4]
 [ 6 13]]

=====================================================================================
EVALUATING: Bagging
=====================================================================================

Fold 01/10
Accuracy       : 0.7241 (95% CI: 0.5428-0.8530)
Precision      : 0.7368 (95% CI: 0.5121-0.8819)
Sensitivity    : 0.8235 (95% CI: 0.5897-0.9381)
Specificity    : 0.5833 (95% CI: 0.3195-0.8067)
F1             : 0.7778 (95% CI: 0.6471-0.8889)
AUC            : 0.8186 (95% CI: 0.6518-0.9510)

Fold 02/10
Accuracy       : 0.6897 (95% CI: 0.5077-0.8272)
Precision      : 0.7500 (95% CI: 0.5050-0.8982)
Sensitivity    : 0.7059 (95% CI: 0.4687-0.8672)
Specificity    : 0.6667 (95% CI: 0.3906-0.8619)
F1             : 0.7273 (95% CI: 0.5455-0.8824)
AUC            : 0.7500 (95% CI: 0.5441-0.9265)

Fold 03/10
Accuracy       : 0.6552 (95% CI: 0.4735-0.8006)
Precision      : 0.7059 (95% CI: 0.4687-0.8672)
Sensitivity    : 0.7059 (95% CI: 0.4687-0.8672)
Specificity    : 0.5833 (95% CI: 0.3195-0.8067)
F1             : 0.7059 (95% CI: 0.5294-0.8485)
AUC            : 0.7745 (95% CI: 0.5783-0.9265)

Fold 04/10
Accuracy       : 0.6897 (95% CI: 0.5077-0.8272)
Precision      : 0.7222 (95% CI: 0.4913-0.8750)
Sensitivity    : 0.7647 (95% CI: 0.5274-0.9044)
Specificity    : 0.5833 (95% CI: 0.3195-0.8067)
F1             : 0.7429 (95% CI: 0.5806-0.8649)
AUC            : 0.7941 (95% CI: 0.5979-0.9314)

Fold 05/10
Accuracy       : 0.6552 (95% CI: 0.4735-0.8006)
Precision      : 0.6842 (95% CI: 0.4601-0.8464)
Sensitivity    : 0.7647 (95% CI: 0.5274-0.9044)
Specificity    : 0.5000 (95% CI: 0.2538-0.7462)
F1             : 0.7222 (95% CI: 0.5714-0.8571)
AUC            : 0.7304 (95% CI: 0.5098-0.9020)

Fold 06/10
Accuracy       : 0.6897 (95% CI: 0.5077-0.8272)
Precision      : 0.7222 (95% CI: 0.4913-0.8750)
Sensitivity    : 0.7647 (95% CI: 0.5274-0.9044)
Specificity    : 0.5833 (95% CI: 0.3195-0.8067)
F1             : 0.7429 (95% CI: 0.5882-0.8650)
AUC            : 0.6961 (95% CI: 0.5049-0.8676)

Fold 07/10
Accuracy       : 0.6552 (95% CI: 0.4735-0.8006)
Precision      : 0.7333 (95% CI: 0.4805-0.8910)
Sensitivity    : 0.6471 (95% CI: 0.4130-0.8269)
Specificity    : 0.6667 (95% CI: 0.3906-0.8619)
F1             : 0.6875 (95% CI: 0.5000-0.8485)
AUC            : 0.6961 (95% CI: 0.4951-0.8873)

Fold 08/10
Accuracy       : 0.6552 (95% CI: 0.4735-0.8006)
Precision      : 0.7059 (95% CI: 0.4687-0.8672)
Sensitivity    : 0.7059 (95% CI: 0.4687-0.8672)
Specificity    : 0.5833 (95% CI: 0.3195-0.8067)
F1             : 0.7059 (95% CI: 0.5333-0.8500)
AUC            : 0.7108 (95% CI: 0.5049-0.8922)

Fold 09/10
Accuracy       : 0.7500 (95% CI: 0.5664-0.8732)
Precision      : 0.7778 (95% CI: 0.5479-0.9100)
Sensitivity    : 0.8235 (95% CI: 0.5897-0.9381)
Specificity    : 0.6364 (95% CI: 0.3538-0.8483)
F1             : 0.8000 (95% CI: 0.6667-0.9189)
AUC            : 0.8396 (95% CI: 0.6791-0.9679)

Fold 10/10
Accuracy       : 0.6429 (95% CI: 0.4583-0.7929)
Precision      : 0.6667 (95% CI: 0.4537-0.8281)
Sensitivity    : 0.8235 (95% CI: 0.5897-0.9381)
Specificity    : 0.3636 (95% CI: 0.1517-0.6462)
F1             : 0.7368 (95% CI: 0.6111-0.8500)
AUC            : 0.6417 (95% CI: 0.4116-0.8610)

Bagging - 10-Fold CV Summary
---------------------------------------------------------------------------
Accuracy       : 0.6807 +/- 0.0349 | Mean fold CI: 0.4984-0.8203
Precision      : 0.7205 +/- 0.0320 | Mean fold CI: 0.4879-0.8740
Sensitivity    : 0.7529 +/- 0.0608 | Mean fold CI: 0.5170-0.8956
Specificity    : 0.5750 +/- 0.0890 | Mean fold CI: 0.3138-0.7998
F1             : 0.7349 +/- 0.0339 | Mean fold CI: 0.5773-0.8674
AUC            : 0.7452 +/- 0.0619 | Mean fold CI: 0.5478-0.9113

Bagging - Independent Test Set
---------------------------------------------------------------------------
Accuracy       : 0.6562 (95% CI: 0.4831-0.7959)
Precision      : 0.7000 (95% CI: 0.4810-0.8545)
Sensitivity    : 0.7368 (95% CI: 0.5121-0.8819)
Specificity    : 0.5385 (95% CI: 0.2914-0.7679)
F1             : 0.7179 (95% CI: 0.5625-0.8500)
AUC            : 0.7004 (95% CI: 0.4980-0.8826)
Balanced Accuracy: 0.6377
MCC: 0.2793

Confusion Matrix (rows=true, columns=predicted):
[[ 7  6]
 [ 5 14]]

=====================================================================================
EVALUATING: AdaBoost
=====================================================================================

Fold 01/10
Accuracy       : 0.6552 (95% CI: 0.4735-0.8006)
Precision      : 0.6522 (95% CI: 0.4489-0.8119)
Sensitivity    : 0.8824 (95% CI: 0.6566-0.9671)
Specificity    : 0.3333 (95% CI: 0.1381-0.6094)
F1             : 0.7500 (95% CI: 0.6486-0.8421)
AUC            : 0.7377 (95% CI: 0.5441-0.8995)

Fold 02/10
Accuracy       : 0.6897 (95% CI: 0.5077-0.8272)
Precision      : 0.6818 (95% CI: 0.4732-0.8364)
Sensitivity    : 0.8824 (95% CI: 0.6566-0.9671)
Specificity    : 0.4167 (95% CI: 0.1933-0.6805)
F1             : 0.7692 (95% CI: 0.6663-0.8650)
AUC            : 0.6250 (95% CI: 0.4044-0.8236)

Fold 03/10
Accuracy       : 0.5172 (95% CI: 0.3443-0.6861)
Precision      : 0.5600 (95% CI: 0.3707-0.7333)
Sensitivity    : 0.8235 (95% CI: 0.5897-0.9381)
Specificity    : 0.0833 (95% CI: 0.0149-0.3539)
F1             : 0.6667 (95% CI: 0.5500-0.7556)
AUC            : 0.5564 (95% CI: 0.3357-0.7598)

Fold 04/10
Accuracy       : 0.6552 (95% CI: 0.4735-0.8006)
Precision      : 0.6522 (95% CI: 0.4489-0.8119)
Sensitivity    : 0.8824 (95% CI: 0.6566-0.9671)
Specificity    : 0.3333 (95% CI: 0.1381-0.6094)
F1             : 0.7500 (95% CI: 0.6486-0.8421)
AUC            : 0.7451 (95% CI: 0.5466-0.8947)

Fold 05/10
Accuracy       : 0.6552 (95% CI: 0.4735-0.8006)
Precision      : 0.6296 (95% CI: 0.4423-0.7847)
Sensitivity    : 1.0000 (95% CI: 0.8157-1.0000)
Specificity    : 0.1667 (95% CI: 0.0470-0.4480)
F1             : 0.7727 (95% CI: 0.7391-0.8293)
AUC            : 0.6275 (95% CI: 0.4117-0.8333)

Fold 06/10
Accuracy       : 0.6552 (95% CI: 0.4735-0.8006)
Precision      : 0.6400 (95% CI: 0.4452-0.7975)
Sensitivity    : 0.9412 (95% CI: 0.7302-0.9895)
Specificity    : 0.2500 (95% CI: 0.0889-0.5323)
F1             : 0.7619 (95% CI: 0.6829-0.8421)
AUC            : 0.6495 (95% CI: 0.4460-0.8309)

Fold 07/10
Accuracy       : 0.6552 (95% CI: 0.4735-0.8006)
Precision      : 0.6522 (95% CI: 0.4489-0.8119)
Sensitivity    : 0.8824 (95% CI: 0.6566-0.9671)
Specificity    : 0.3333 (95% CI: 0.1381-0.6094)
F1             : 0.7500 (95% CI: 0.6341-0.8423)
AUC            : 0.7304 (95% CI: 0.5465-0.9069)

Fold 08/10
Accuracy       : 0.5862 (95% CI: 0.4074-0.7449)
Precision      : 0.5926 (95% CI: 0.4073-0.7549)
Sensitivity    : 0.9412 (95% CI: 0.7302-0.9895)
Specificity    : 0.0833 (95% CI: 0.0149-0.3539)
F1             : 0.7273 (95% CI: 0.6512-0.7907)
AUC            : 0.6838 (95% CI: 0.4657-0.8676)

Fold 09/10
Accuracy       : 0.7143 (95% CI: 0.5294-0.8475)
Precision      : 0.6957 (95% CI: 0.4913-0.8440)
Sensitivity    : 0.9412 (95% CI: 0.7302-0.9895)
Specificity    : 0.3636 (95% CI: 0.1517-0.6462)
F1             : 0.8000 (95% CI: 0.7143-0.8947)
AUC            : 0.7166 (95% CI: 0.5160-0.9011)

Fold 10/10
Accuracy       : 0.7143 (95% CI: 0.5294-0.8475)
Precision      : 0.7143 (95% CI: 0.5004-0.8619)
Sensitivity    : 0.8824 (95% CI: 0.6566-0.9671)
Specificity    : 0.4545 (95% CI: 0.2127-0.7199)
F1             : 0.7895 (95% CI: 0.6842-0.8947)
AUC            : 0.7219 (95% CI: 0.5053-0.9064)

AdaBoost - 10-Fold CV Summary
---------------------------------------------------------------------------
Accuracy       : 0.6498 +/- 0.0593 | Mean fold CI: 0.4685-0.7956
Precision      : 0.6471 +/- 0.0460 | Mean fold CI: 0.4477-0.8048
Sensitivity    : 0.9059 +/- 0.0496 | Mean fold CI: 0.6879-0.9742
Specificity    : 0.2818 +/- 0.1315 | Mean fold CI: 0.1138-0.5563
F1             : 0.7537 +/- 0.0371 | Mean fold CI: 0.6619-0.8399
AUC            : 0.6794 +/- 0.0626 | Mean fold CI: 0.4722-0.8624

AdaBoost - Independent Test Set
---------------------------------------------------------------------------
Accuracy       : 0.5625 (95% CI: 0.3933-0.7183)
Precision      : 0.5806 (95% CI: 0.4077-0.7358)
Sensitivity    : 0.9474 (95% CI: 0.7536-0.9906)
Specificity    : 0.0000 (95% CI: 0.0000-0.2281)
F1             : 0.7200 (95% CI: 0.6667-0.7451)
AUC            : 0.6235 (95% CI: 0.4190-0.8178)
Balanced Accuracy: 0.4737
MCC: -0.1486

Confusion Matrix (rows=true, columns=predicted):
[[ 0 13]
 [ 1 18]]

=====================================================================================
EVALUATING: Extra Trees
=====================================================================================

Fold 01/10
Accuracy       : 0.6552 (95% CI: 0.4735-0.8006)
Precision      : 0.7059 (95% CI: 0.4687-0.8672)
Sensitivity    : 0.7059 (95% CI: 0.4687-0.8672)
Specificity    : 0.5833 (95% CI: 0.3195-0.8067)
F1             : 0.7059 (95% CI: 0.5294-0.8485)
AUC            : 0.8039 (95% CI: 0.6225-0.9412)

Fold 02/10
Accuracy       : 0.6897 (95% CI: 0.5077-0.8272)
Precision      : 0.9000 (95% CI: 0.5958-0.9821)
Sensitivity    : 0.5294 (95% CI: 0.3096-0.7383)
Specificity    : 0.9167 (95% CI: 0.6461-0.9851)
F1             : 0.6667 (95% CI: 0.4348-0.8387)
AUC            : 0.7304 (95% CI: 0.5245-0.9118)

Fold 03/10
Accuracy       : 0.6897 (95% CI: 0.5077-0.8272)
Precision      : 0.7857 (95% CI: 0.5241-0.9243)
Sensitivity    : 0.6471 (95% CI: 0.4130-0.8269)
Specificity    : 0.7500 (95% CI: 0.4677-0.9111)
F1             : 0.7097 (95% CI: 0.5161-0.8649)
AUC            : 0.8284 (95% CI: 0.6373-0.9657)

Fold 04/10
Accuracy       : 0.7241 (95% CI: 0.5428-0.8530)
Precision      : 0.8000 (95% CI: 0.5481-0.9295)
Sensitivity    : 0.7059 (95% CI: 0.4687-0.8672)
Specificity    : 0.7500 (95% CI: 0.4677-0.9111)
F1             : 0.7500 (95% CI: 0.5625-0.8889)
AUC            : 0.7941 (95% CI: 0.5980-0.9314)

Fold 05/10
Accuracy       : 0.6552 (95% CI: 0.4735-0.8006)
Precision      : 0.6842 (95% CI: 0.4601-0.8464)
Sensitivity    : 0.7647 (95% CI: 0.5274-0.9044)
Specificity    : 0.5000 (95% CI: 0.2538-0.7462)
F1             : 0.7222 (95% CI: 0.5714-0.8571)
AUC            : 0.7500 (95% CI: 0.5392-0.9167)

Fold 06/10
Accuracy       : 0.5862 (95% CI: 0.4074-0.7449)
Precision      : 0.6471 (95% CI: 0.4130-0.8269)
Sensitivity    : 0.6471 (95% CI: 0.4130-0.8269)
Specificity    : 0.5000 (95% CI: 0.2538-0.7462)
F1             : 0.6471 (95% CI: 0.4667-0.8000)
AUC            : 0.6569 (95% CI: 0.4559-0.8382)

Fold 07/10
Accuracy       : 0.5862 (95% CI: 0.4074-0.7449)
Precision      : 0.7273 (95% CI: 0.4344-0.9025)
Sensitivity    : 0.4706 (95% CI: 0.2617-0.6904)
Specificity    : 0.7500 (95% CI: 0.4677-0.9111)
F1             : 0.5714 (95% CI: 0.3333-0.7586)
AUC            : 0.6618 (95% CI: 0.4412-0.8629)

Fold 08/10
Accuracy       : 0.6552 (95% CI: 0.4735-0.8006)
Precision      : 0.6842 (95% CI: 0.4601-0.8464)
Sensitivity    : 0.7647 (95% CI: 0.5274-0.9044)
Specificity    : 0.5000 (95% CI: 0.2538-0.7462)
F1             : 0.7222 (95% CI: 0.5714-0.8571)
AUC            : 0.6716 (95% CI: 0.4559-0.8627)

Fold 09/10
Accuracy       : 0.7857 (95% CI: 0.6046-0.8979)
Precision      : 0.7895 (95% CI: 0.5667-0.9149)
Sensitivity    : 0.8824 (95% CI: 0.6566-0.9671)
Specificity    : 0.6364 (95% CI: 0.3538-0.8483)
F1             : 0.8333 (95% CI: 0.7222-0.9412)
AUC            : 0.8610 (95% CI: 0.7112-0.9733)

Fold 10/10
Accuracy       : 0.6429 (95% CI: 0.4583-0.7929)
Precision      : 0.7059 (95% CI: 0.4687-0.8672)
Sensitivity    : 0.7059 (95% CI: 0.4687-0.8672)
Specificity    : 0.5455 (95% CI: 0.2801-0.7873)
F1             : 0.7059 (95% CI: 0.5294-0.8571)
AUC            : 0.6471 (95% CI: 0.4116-0.8610)

Extra Trees - 10-Fold CV Summary
---------------------------------------------------------------------------
Accuracy       : 0.6670 +/- 0.0600 | Mean fold CI: 0.4856-0.8090
Precision      : 0.7430 +/- 0.0753 | Mean fold CI: 0.4940-0.8907
Sensitivity    : 0.6824 +/- 0.1183 | Mean fold CI: 0.4515-0.8460
Specificity    : 0.6432 +/- 0.1429 | Mean fold CI: 0.3764-0.8399
F1             : 0.7034 +/- 0.0681 | Mean fold CI: 0.5237-0.8512
AUC            : 0.7405 +/- 0.0789 | Mean fold CI: 0.5397-0.9065

Extra Trees - Independent Test Set
---------------------------------------------------------------------------
Accuracy       : 0.6875 (95% CI: 0.5143-0.8205)
Precision      : 0.7647 (95% CI: 0.5274-0.9044)
Sensitivity    : 0.6842 (95% CI: 0.4601-0.8464)
Specificity    : 0.6923 (95% CI: 0.4237-0.8732)
F1             : 0.7222 (95% CI: 0.5455-0.8649)
AUC            : 0.6964 (95% CI: 0.4899-0.8826)
Balanced Accuracy: 0.6883
MCC: 0.3706

Confusion Matrix (rows=true, columns=predicted):
[[ 9  4]
 [ 6 13]]

====================================================================================================
ALL MODELS: INDIVIDUAL FOLD RESULTS WITH 95% CIs
====================================================================================================

,Model,Fold,Accuracy,Accuracy CI Low,Accuracy CI High,Precision,Precision CI Low,Precision CI High,Sensitivity,Sensitivity CI Low,...,F1 CI High,AUC,AUC CI Low,AUC CI High,Balanced Accuracy,MCC,TN,FP,FN,TP
20,AdaBoost,1,0.6552,0.4735,0.8006,0.6522,0.4489,0.8119,0.8824,0.6566,...,0.8421,0.7377,0.5441,0.8995,0.6078,0.2622,4,8,2,15
21,AdaBoost,2,0.6897,0.5077,0.8272,0.6818,0.4732,0.8364,0.8824,0.6566,...,0.8650,0.6250,0.4044,0.8236,0.6495,0.3442,5,7,2,15
22,AdaBoost,3,0.5172,0.3443,0.6861,0.5600,0.3707,0.7333,0.8235,0.5897,...,0.7556,0.5564,0.3357,0.7598,0.4534,-0.1330,1,11,3,14
23,AdaBoost,4,0.6552,0.4735,0.8006,0.6522,0.4489,0.8119,0.8824,0.6566,...,0.8421,0.7451,0.5466,0.8947,0.6078,0.2622,4,8,2,15
24,AdaBoost,5,0.6552,0.4735,0.8006,0.6296,0.4423,0.7847,1.0000,0.8157,...,0.8293,0.6275,0.4117,0.8333,0.5833,0.3239,2,10,0,17
25,AdaBoost,6,0.6552,0.4735,0.8006,0.6400,0.4452,0.7975,0.9412,0.7302,...,0.8421,0.6495,0.4460,0.8309,0.5956,0.2731,3,9,1,16
26,AdaBoost,7,0.6552,0.4735,0.8006,0.6522,0.4489,0.8119,0.8824,0.6566,...,0.8423,0.7304,0.5465,0.9069,0.6078,0.2622,4,8,2,15
27,AdaBoost,8,0.5862,0.4074,0.7449,0.5926,0.4073,0.7549,0.9412,0.7302,...,0.7907,0.6838,0.4657,0.8676,0.5123,0.0476,1,11,1,16
28,AdaBoost,9,0.7143,0.5294,0.8475,0.6957,0.4913,0.8440,0.9412,0.7302,...,0.8947,0.7166,0.5160,0.9011,0.6524,0.3887,4,7,1,16
29,AdaBoost,10,0.7143,0.5294,0.8475,0.7143,0.5004,0.8619,0.8824,0.6566,...,0.8947,0.7219,0.5053,0.9064,0.6684,0.3800,5,6,2,15
10,Bagging,1,0.7241,0.5428,0.8530,0.7368,0.5121,0.8819,0.8235,0.5897,...,0.8889,0.8186,0.6518,0.9510,0.7034,0.4216,7,5,3,14
11,Bagging,2,0.6897,0.5077,0.8272,0.7500,0.5050,0.8982,0.7059,0.4687,...,0.8824,0.7500,0.5441,0.9265,0.6863,0.3689,8,4,5,12
12,Bagging,3,0.6552,0.4735,0.8006,0.7059,0.4687,0.8672,0.7059,0.4687,...,0.8485,0.7745,0.5783,0.9265,0.6446,0.2892,7,5,5,12
13,Bagging,4,0.6897,0.5077,0.8272,0.7222,0.4913,0.8750,0.7647,0.5274,...,0.8649,0.7941,0.5979,0.9314,0.6740,0.3533,7,5,4,13
14,Bagging,5,0.6552,0.4735,0.8006,0.6842,0.4601,0.8464,0.7647,0.5274,...,0.8571,0.7304,0.5098,0.9020,0.6324,0.2743,6,6,4,13
15,Bagging,6,0.6897,0.5077,0.8272,0.7222,0.4913,0.8750,0.7647,0.5274,...,0.8650,0.6961,0.5049,0.8676,0.6740,0.3533,7,5,4,13
16,Bagging,7,0.6552,0.4735,0.8006,0.7333,0.4805,0.8910,0.6471,0.4130,...,0.8485,0.6961,0.4951,0.8873,0.6569,0.3092,8,4,6,11
17,Bagging,8,0.6552,0.4735,0.8006,0.7059,0.4687,0.8672,0.7059,0.4687,...,0.8500,0.7108,0.5049,0.8922,0.6446,0.2892,7,5,5,12
18,Bagging,9,0.7500,0.5664,0.8732,0.7778,0.5479,0.9100,0.8235,0.5897,...,0.9189,0.8396,0.6791,0.9679,0.7299,0.4688,7,4,3,14
19,Bagging,10,0.6429,0.4583,0.7929,0.6667,0.4537,0.8281,0.8235,0.5897,...,0.8500,0.6417,0.4116,0.8610,0.5936,0.2111,4,7,3,14
0,CatBoost,1,0.7586,0.5789,0.8778,0.7778,0.5479,0.9100,0.8235,0.5897,...,0.9143,0.8627,0.7059,0.9706,0.7451,0.4976,8,4,3,14
1,CatBoost,2,0.6897,0.5077,0.8272,0.7500,0.5050,0.8982,0.7059,0.4687,...,0.8824,0.7647,0.5636,0.9364,0.6863,0.3689,8,4,5,12
2,CatBoost,3,0.7241,0.5428,0.8530,0.8000,0.5481,0.9295,0.7059,0.4687,...,0.8889,0.8039,0.6127,0.9510,0.7279,0.4493,9,3,5,12
3,CatBoost,4,0.6897,0.5077,0.8272,0.7222,0.4913,0.8750,0.7647,0.5274,...,0.8824,0.7647,0.5735,0.9167,0.6740,0.3533,7,5,4,13
4,CatBoost,5,0.6897,0.5077,0.8272,0.7000,0.4810,0.8545,0.8235,0.5897,...,0.8718,0.7745,0.5735,0.9216,0.6618,0.3444,6,6,3,14
5,CatBoost,6,0.6552,0.4735,0.8006,0.7059,0.4687,0.8672,0.7059,0.4687,...,0.8485,0.7157,0.5195,0.8922,0.6446,0.2892,7,5,5,12
6,CatBoost,7,0.5517,0.3755,0.7159,0.6429,0.3876,0.8366,0.5294,0.3096,...,0.7586,0.6275,0.4167,0.8333,0.5564,0.1111,7,5,8,9
7,CatBoost,8,0.6207,0.4400,0.7731,0.6667,0.4375,0.8372,0.7059,0.4687,...,0.8333,0.6863,0.4754,0.8775,0.6029,0.2090,6,6,5,12
8,CatBoost,9,0.6786,0.4934,0.8207,0.7222,0.4913,0.8750,0.7647,0.5274,...,0.8752,0.8128,0.6364,0.9465,0.6551,0.3161,6,5,4,13
9,CatBoost,10,0.6071,0.4241,0.7643,0.6667,0.4375,0.8372,0.7059,0.4687,...,0.8333,0.6738,0.4385,0.8663,0.5802,0.1635,5,6,5,12
30,Extra Trees,1,0.6552,0.4735,0.8006,0.7059,0.4687,0.8672,0.7059,0.4687,...,0.8485,0.8039,0.6225,0.9412,0.6446,0.2892,7,5,5,12
31,Extra Trees,2,0.6897,0.5077,0.8272,0.9000,0.5958,0.9821,0.5294,0.3096,...,0.8387,0.7304,0.5245,0.9118,0.7230,0.4622,11,1,8,9
32,Extra Trees,3,0.6897,0.5077,0.8272,0.7857,0.5241,0.9243,0.6471,0.4130,...,0.8649,0.8284,0.6373,0.9657,0.6985,0.3913,9,3,6,11
33,Extra Trees,4,0.7241,0.5428,0.8530,0.8000,0.5481,0.9295,0.7059,0.4687,...,0.8889,0.7941,0.5980,0.9314,0.7279,0.4493,9,3,5,12
34,Extra Trees,5,0.6552,0.4735,0.8006,0.6842,0.4601,0.8464,0.7647,0.5274,...,0.8571,0.7500,0.5392,0.9167,0.6324,0.2743,6,6,4,13
35,Extra Trees,6,0.5862,0.4074,0.7449,0.6471,0.4130,0.8269,0.6471,0.4130,...,0.8000,0.6569,0.4559,0.8382,0.5735,0.1471,6,6,6,11
36,Extra Trees,7,0.5862,0.4074,0.7449,0.7273,0.4344,0.9025,0.4706,0.2617,...,0.7586,0.6618,0.4412,0.8629,0.6103,0.2239,9,3,9,8
37,Extra Trees,8,0.6552,0.4735,0.8006,0.6842,0.4601,0.8464,0.7647,0.5274,...,0.8571,0.6716,0.4559,0.8627,0.6324,0.2743,6,6,4,13
38,Extra Trees,9,0.7857,0.6046,0.8979,0.7895,0.5667,0.9149,0.8824,0.6566,...,0.9412,0.8610,0.7112,0.9733,0.7594,0.5424,7,4,2,15
39,Extra Trees,10,0.6429,0.4583,0.7929,0.7059,0.4687,0.8672,0.7059,0.4687,...,0.8571,0.6471,0.4116,0.8610,0.6257,0.2513,6,5,5,12

====================================================================================================
CROSS-VALIDATION MEAN, SD AND MEAN FOLD CIs
====================================================================================================

,Model,CV Accuracy Mean,CV Accuracy SD,Mean Fold Accuracy CI Low,Mean Fold Accuracy CI High,CV Precision Mean,CV Precision SD,Mean Fold Precision CI Low,Mean Fold Precision CI High,CV Sensitivity Mean,...,Mean Fold F1 CI Low,Mean Fold F1 CI High,CV AUC Mean,CV AUC SD,Mean Fold AUC CI Low,Mean Fold AUC CI High,CV Balanced Accuracy Mean,CV Balanced Accuracy SD,CV MCC Mean,CV MCC SD
0,CatBoost,0.6665,0.0601,0.4851,0.8087,0.7154,0.0502,0.4796,0.8720,0.7235,...,0.5470,0.8589,0.7487,0.0720,0.5516,0.9112,0.6534,0.0605,0.3103,0.1215
1,Bagging,0.6807,0.0349,0.4984,0.8203,0.7205,0.0320,0.4879,0.8740,0.7529,...,0.5773,0.8674,0.7452,0.0619,0.5478,0.9113,0.6640,0.0385,0.3339,0.0753
2,AdaBoost,0.6498,0.0593,0.4685,0.7956,0.6471,0.0460,0.4477,0.8048,0.9059,...,0.6619,0.8399,0.6794,0.0626,0.4722,0.8624,0.5939,0.0660,0.2411,0.1627
3,Extra Trees,0.6670,0.0600,0.4856,0.8090,0.7430,0.0753,0.4940,0.8907,0.6824,...,0.5237,0.8512,0.7405,0.0789,0.5397,0.9065,0.6628,0.0603,0.3305,0.1245

====================================================================================================
INDEPENDENT TEST SET COMPARISON WITH 95% CIs
====================================================================================================

,Accuracy,Accuracy CI Low,Accuracy CI High,Precision,Precision CI Low,Precision CI High,Sensitivity,Sensitivity CI Low,Sensitivity CI High,Specificity,...,F1 CI High,AUC,AUC CI Low,AUC CI High,Balanced Accuracy,MCC,TN,FP,FN,TP
Model,,,,,,,,,,,,,,,,,,,,,
CatBoost,0.6875,0.5143,0.8205,0.7647,0.5274,0.9044,0.6842,0.4601,0.8464,0.6923,...,0.8649,0.6721,0.4696,0.8623,0.6883,0.3706,9,4,6,13
Extra Trees,0.6875,0.5143,0.8205,0.7647,0.5274,0.9044,0.6842,0.4601,0.8464,0.6923,...,0.8649,0.6964,0.4899,0.8826,0.6883,0.3706,9,4,6,13
AdaBoost,0.5625,0.3933,0.7183,0.5806,0.4077,0.7358,0.9474,0.7536,0.9906,0.0000,...,0.7451,0.6235,0.4190,0.8178,0.4737,-0.1486,0,13,1,18
Bagging,0.6562,0.4831,0.7959,0.7000,0.4810,0.8545,0.7368,0.5121,0.8819,0.5385,...,0.8500,0.7004,0.4980,0.8826,0.6377,0.2793,7,6,5,14

====================================================================================================
INDIVIDUAL MODEL COMPARISON
====================================================================================================

Cross-validation summary:

,Model,CV Accuracy Mean,CV Accuracy SD,Mean Fold Accuracy CI Low,Mean Fold Accuracy CI High,CV Precision Mean,CV Precision SD,Mean Fold Precision CI Low,Mean Fold Precision CI High,CV Sensitivity Mean,...,Mean Fold F1 CI Low,Mean Fold F1 CI High,CV AUC Mean,CV AUC SD,Mean Fold AUC CI Low,Mean Fold AUC CI High,CV Balanced Accuracy Mean,CV Balanced Accuracy SD,CV MCC Mean,CV MCC SD
0,CatBoost,0.6665,0.0601,0.4851,0.8087,0.7154,0.0502,0.4796,0.8720,0.7235,...,0.5470,0.8589,0.7487,0.0720,0.5516,0.9112,0.6534,0.0605,0.3103,0.1215
1,Bagging,0.6807,0.0349,0.4984,0.8203,0.7205,0.0320,0.4879,0.8740,0.7529,...,0.5773,0.8674,0.7452,0.0619,0.5478,0.9113,0.6640,0.0385,0.3339,0.0753
2,AdaBoost,0.6498,0.0593,0.4685,0.7956,0.6471,0.0460,0.4477,0.8048,0.9059,...,0.6619,0.8399,0.6794,0.0626,0.4722,0.8624,0.5939,0.0660,0.2411,0.1627
3,Extra Trees,0.6670,0.0600,0.4856,0.8090,0.7430,0.0753,0.4940,0.8907,0.6824,...,0.5237,0.8512,0.7405,0.0789,0.5397,0.9065,0.6628,0.0603,0.3305,0.1245

Independent test results:

,Accuracy,Accuracy CI Low,Accuracy CI High,Precision,Precision CI Low,Precision CI High,Sensitivity,Sensitivity CI Low,Sensitivity CI High,Specificity,...,F1 CI High,AUC,AUC CI Low,AUC CI High,Balanced Accuracy,MCC,TN,FP,FN,TP
Model,,,,,,,,,,,,,,,,,,,,,
CatBoost,0.6875,0.5143,0.8205,0.7647,0.5274,0.9044,0.6842,0.4601,0.8464,0.6923,...,0.8649,0.6721,0.4696,0.8623,0.6883,0.3706,9,4,6,13
Bagging,0.6562,0.4831,0.7959,0.7000,0.4810,0.8545,0.7368,0.5121,0.8819,0.5385,...,0.8500,0.7004,0.4980,0.8826,0.6377,0.2793,7,6,5,14
AdaBoost,0.5625,0.3933,0.7183,0.5806,0.4077,0.7358,0.9474,0.7536,0.9906,0.0000,...,0.7451,0.6235,0.4190,0.8178,0.4737,-0.1486,0,13,1,18
Extra Trees,0.6875,0.5143,0.8205,0.7647,0.5274,0.9044,0.6842,0.4601,0.8464,0.6923,...,0.8649,0.6964,0.4899,0.8826,0.6883,0.3706,9,4,6,13

====================================================================================================
INDEPENDENT TEST CONFUSION MATRICES
====================================================================================================

CatBoost
Rows = true labels [HC, PD]
Columns = predicted labels [HC, PD]
[[ 9  4]
 [ 6 13]]

Bagging
Rows = true labels [HC, PD]
Columns = predicted labels [HC, PD]
[[ 7  6]
 [ 5 14]]

AdaBoost
Rows = true labels [HC, PD]
Columns = predicted labels [HC, PD]
[[ 0 13]
 [ 1 18]]

Extra Trees
Rows = true labels [HC, PD]
Columns = predicted labels [HC, PD]
[[ 9  4]
 [ 6 13]]

Saved result files:
1. ensemble_fold_results_95CI.csv
2. ensemble_cv_summary_95CI.csv
3. ensemble_independent_test_results_95CI.csv

In [5]:

# ============================================================
# CLASSIFICATION WITH 95% CONFIDENCE INTERVALS
# Stratified 10-Fold CV + Independent Test Set
#
# Models:
#   1. LightGBM
#   2. Logistic Regression
#   3. Support Vector Machine (SVM)
#   4. Decision Tree
#
# Metrics with 95% CI:
# Accuracy, Precision, Sensitivity, Specificity, F1, AUC
#
# Additional metrics:
# Balanced Accuracy, MCC, TN, FP, FN, TP
# ============================================================

!pip install -q lightgbm scikit-learn statsmodels pandas numpy

import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

from sklearn.model_selection import (
    train_test_split,
    StratifiedKFold
)

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    balanced_accuracy_score,
    matthews_corrcoef,
    confusion_matrix
)

from statsmodels.stats.proportion import proportion_confint
from lightgbm import LGBMClassifier


# ============================================================
# STEP 1: PREPARE DATA
# ============================================================

feature_cols = [f"feat_{i}" for i in range(32)]

X = fused_df_named_int[feature_cols].copy()
y = fused_df_named_int["PD_Label_Combined"].copy()

X = X.apply(pd.to_numeric, errors="coerce")
X = X.replace([np.inf, -np.inf], np.nan)
y = pd.to_numeric(y, errors="coerce")

valid = y.notna()

X = X.loc[valid].reset_index(drop=True)
y = y.loc[valid].astype(int).reset_index(drop=True)

if set(y.unique()) != {0, 1}:
    raise ValueError("Labels must be encoded as 0 and 1.")

if X.shape[1] != 32:
    raise ValueError("Expected exactly 32 embedding features.")

if y.value_counts().min() < 10:
    raise ValueError(
        "Each class needs at least 10 samples for stratified "
        "10-fold cross-validation."
    )

print("X shape:", X.shape)
print("\nClass distribution:")
print(y.value_counts().sort_index())


# ============================================================
# STEP 2: TRAIN-TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.10,
    stratify=y,
    random_state=42
)

print("\nTraining shape:", X_train.shape)
print("Test shape:", X_test.shape)

print("\nTraining class distribution:")
print(y_train.value_counts().sort_index())

print("\nIndependent test class distribution:")
print(y_test.value_counts().sort_index())


# ============================================================
# STEP 3: MODEL FACTORY
# ============================================================

def create_models(y_fit):

    n_negative = int((y_fit == 0).sum())
    n_positive = int((y_fit == 1).sum())

    # Balanced class weights for LightGBM.
    lightgbm = LGBMClassifier(
        objective="binary",
        n_estimators=200,
        learning_rate=0.03,
        num_leaves=15,
        max_depth=4,
        min_child_samples=10,
        subsample=0.85,
        subsample_freq=1,
        colsample_bytree=0.85,
        reg_alpha=0.1,
        reg_lambda=2.0,
        class_weight="balanced",
        random_state=42,
        n_jobs=-1,
        verbosity=-1
    )

    # Logistic Regression: scaling is important.
    logistic_regression = Pipeline([
        ("scaler", StandardScaler()),
        ("classifier", LogisticRegression(
            C=1.0,
            penalty="l2",
            solver="liblinear",
            class_weight="balanced",
            max_iter=1000,
            random_state=42
        ))
    ])

    # SVM: scaling and probability estimates.
    svm = Pipeline([
        ("scaler", StandardScaler()),
        ("classifier", SVC(
            C=1.0,
            kernel="rbf",
            gamma="scale",
            probability=True,
            class_weight="balanced",
            random_state=42
        ))
    ])

    # Decision Tree.
    decision_tree = DecisionTreeClassifier(
        criterion="gini",
        max_depth=5,
        min_samples_split=5,
        min_samples_leaf=3,
        class_weight="balanced",
        random_state=42
    )

    return {
        "LightGBM": lightgbm,
        "Logistic Regression": logistic_regression,
        "SVM": svm,
        "Decision Tree": decision_tree
    }


# ============================================================
# STEP 4: METRICS + 95% CONFIDENCE INTERVALS
# ============================================================

def calculate_metrics_with_ci(
    y_true,
    y_pred,
    y_prob,
    n_boot=2000,
    random_state=42
):

    y_true = np.asarray(y_true).astype(int)
    y_pred = np.asarray(y_pred).astype(int)
    y_prob = np.asarray(y_prob, dtype=float)

    tn, fp, fn, tp = confusion_matrix(
        y_true,
        y_pred,
        labels=[0, 1]
    ).ravel()

    n = len(y_true)

    # ---------------- Point estimates ----------------

    accuracy = accuracy_score(y_true, y_pred)

    precision = precision_score(
        y_true, y_pred, zero_division=0
    )

    sensitivity = recall_score(
        y_true, y_pred, zero_division=0
    )

    specificity = (
        tn / (tn + fp) if (tn + fp) > 0 else np.nan
    )

    f1 = f1_score(
        y_true, y_pred, zero_division=0
    )

    auc = roc_auc_score(y_true, y_prob)

    results = {
        "Accuracy": accuracy,
        "Precision": precision,
        "Sensitivity": sensitivity,
        "Specificity": specificity,
        "F1": f1,
        "AUC": auc,
        "Balanced Accuracy": balanced_accuracy_score(
            y_true, y_pred
        ),
        "MCC": matthews_corrcoef(y_true, y_pred),
        "TN": tn,
        "FP": fp,
        "FN": fn,
        "TP": tp
    }

    # ---------------- Wilson 95% CIs ----------------

    proportions = {
        "Accuracy": (tp + tn, n),
        "Precision": (tp, tp + fp),
        "Sensitivity": (tp, tp + fn),
        "Specificity": (tn, tn + fp)
    }

    for metric, (count, denominator) in proportions.items():

        if denominator > 0:
            low, high = proportion_confint(
                count=count,
                nobs=denominator,
                alpha=0.05,
                method="wilson"
            )
        else:
            low, high = np.nan, np.nan

        results[f"{metric} CI Low"] = low
        results[f"{metric} CI High"] = high

    # ---------------- Stratified bootstrap CIs ----------------
    # Resample within each class, preserving class counts.

    rng = np.random.default_rng(random_state)

    class_indices = [
        np.flatnonzero(y_true == 0),
        np.flatnonzero(y_true == 1)
    ]

    bootstrap_f1 = []
    bootstrap_auc = []

    for _ in range(n_boot):

        sampled_indices = np.concatenate([
            rng.choice(
                indices,
                size=len(indices),
                replace=True
            )
            for indices in class_indices
        ])

        yt = y_true[sampled_indices]
        yp = y_pred[sampled_indices]
        pr = y_prob[sampled_indices]

        bootstrap_f1.append(
            f1_score(yt, yp, zero_division=0)
        )

        bootstrap_auc.append(
            roc_auc_score(yt, pr)
        )

    for metric, values in [
        ("F1", bootstrap_f1),
        ("AUC", bootstrap_auc)
    ]:

        low, high = np.percentile(
            values,
            [2.5, 97.5]
        )

        results[f"{metric} CI Low"] = low
        results[f"{metric} CI High"] = high

    return results


# ============================================================
# STEP 5: PREPROCESSING
# ============================================================

def make_preprocessor():
    return SimpleImputer(strategy="median")


# ============================================================
# STEP 6: STRATIFIED 10-FOLD CROSS-VALIDATION
# ============================================================

skf = StratifiedKFold(
    n_splits=10,
    shuffle=True,
    random_state=42
)

model_names = [
    "LightGBM",
    "Logistic Regression",
    "SVM",
    "Decision Tree"
]

cv_records = []
cv_summary_records = []
test_records = []
confusion_matrices = {}

metrics_to_report = [
    "Accuracy",
    "Precision",
    "Sensitivity",
    "Specificity",
    "F1",
    "AUC"
]


for model_name in model_names:

    print("\n" + "=" * 85)
    print("EVALUATING:", model_name)
    print("=" * 85)

    fold_metrics = []

    for fold, (train_idx, val_idx) in enumerate(
        skf.split(X_train, y_train),
        start=1
    ):

        X_tr = X_train.iloc[train_idx]
        X_val = X_train.iloc[val_idx]

        y_tr = y_train.iloc[train_idx]
        y_val = y_train.iloc[val_idx]

        # Imputation is fitted on training data only.
        imputer = make_preprocessor()

        X_tr_imp = imputer.fit_transform(X_tr)
        X_val_imp = imputer.transform(X_val)

        # Fresh model for each fold.
        model = create_models(y_tr)[model_name]

        model.fit(X_tr_imp, y_tr)

        val_pred = np.asarray(
            model.predict(X_val_imp)
        ).reshape(-1).astype(int)

        val_prob = model.predict_proba(X_val_imp)[:, 1]

        metrics = calculate_metrics_with_ci(
            y_val,
            val_pred,
            val_prob,
            n_boot=2000,
            random_state=1000 + fold
        )

        metrics["Model"] = model_name
        metrics["Fold"] = fold

        fold_metrics.append(metrics)
        cv_records.append(metrics.copy())

        print(f"\nFold {fold:02d}/10")

        for metric in metrics_to_report:

            print(
                f"{metric:15s}: {metrics[metric]:.4f} "
                f"(95% CI: "
                f"{metrics[metric + ' CI Low']:.4f}-"
                f"{metrics[metric + ' CI High']:.4f})"
            )

    # ========================================================
    # STEP 7: CV MEAN AND STANDARD DEVIATION
    # ========================================================

    fold_df = pd.DataFrame(fold_metrics)

    print(f"\n{model_name} - 10-Fold CV Summary")
    print("-" * 75)

    summary = {"Model": model_name}

    for metric in metrics_to_report:

        mean_val = fold_df[metric].mean()
        std_val = fold_df[metric].std(ddof=1)

        # Descriptive averages of fold CI endpoints,
        # not a formal pooled 95% confidence interval.
        mean_ci_low = fold_df[
            f"{metric} CI Low"
        ].mean()

        mean_ci_high = fold_df[
            f"{metric} CI High"
        ].mean()

        summary[f"CV {metric} Mean"] = mean_val
        summary[f"CV {metric} SD"] = std_val
        summary[f"Mean Fold {metric} CI Low"] = mean_ci_low
        summary[f"Mean Fold {metric} CI High"] = mean_ci_high

        print(
            f"{metric:15s}: {mean_val:.4f} +/- {std_val:.4f} "
            f"| Mean fold CI: "
            f"{mean_ci_low:.4f}-{mean_ci_high:.4f}"
        )

    for metric in ["Balanced Accuracy", "MCC"]:

        summary[f"CV {metric} Mean"] = fold_df[metric].mean()
        summary[f"CV {metric} SD"] = fold_df[metric].std(ddof=1)

    cv_summary_records.append(summary)

    # ========================================================
    # STEP 8: FINAL MODEL AND INDEPENDENT TEST SET
    # ========================================================

    final_imputer = make_preprocessor()

    X_train_imp = final_imputer.fit_transform(X_train)
    X_test_imp = final_imputer.transform(X_test)

    final_model = create_models(y_train)[model_name]

    final_model.fit(X_train_imp, y_train)

    test_pred = np.asarray(
        final_model.predict(X_test_imp)
    ).reshape(-1).astype(int)

    test_prob = final_model.predict_proba(X_test_imp)[:, 1]

    test_metrics = calculate_metrics_with_ci(
        y_test,
        test_pred,
        test_prob,
        n_boot=5000,
        random_state=2026
    )

    test_metrics["Model"] = model_name
    test_records.append(test_metrics.copy())

    confusion_matrices[model_name] = confusion_matrix(
        y_test,
        test_pred,
        labels=[0, 1]
    )

    print(f"\n{model_name} - Independent Test Set")
    print("-" * 75)

    for metric in metrics_to_report:

        print(
            f"{metric:15s}: {test_metrics[metric]:.4f} "
            f"(95% CI: "
            f"{test_metrics[metric + ' CI Low']:.4f}-"
            f"{test_metrics[metric + ' CI High']:.4f})"
        )

    print(
        f"Balanced Accuracy: "
        f"{test_metrics['Balanced Accuracy']:.4f}"
    )

    print(f"MCC: {test_metrics['MCC']:.4f}")

    print("\nConfusion Matrix (rows=true, columns=predicted):")
    print(confusion_matrices[model_name])


# ============================================================
# STEP 9: INDIVIDUAL FOLD RESULTS WITH 95% CIs
# ============================================================

fold_results_df = pd.DataFrame(cv_records)

fold_columns = [
    "Model", "Fold",
    "Accuracy", "Accuracy CI Low", "Accuracy CI High",
    "Precision", "Precision CI Low", "Precision CI High",
    "Sensitivity", "Sensitivity CI Low", "Sensitivity CI High",
    "Specificity", "Specificity CI Low", "Specificity CI High",
    "F1", "F1 CI Low", "F1 CI High",
    "AUC", "AUC CI Low", "AUC CI High",
    "Balanced Accuracy", "MCC",
    "TN", "FP", "FN", "TP"
]

fold_results_df = fold_results_df[fold_columns]

print("\n" + "=" * 100)
print("ALL MODELS: INDIVIDUAL FOLD RESULTS WITH 95% CIs")
print("=" * 100)

display(
    fold_results_df.sort_values(
        ["Model", "Fold"]
    ).round(4)
)


# ============================================================
# STEP 10: CROSS-VALIDATION SUMMARY
# ============================================================

cv_summary_df = pd.DataFrame(cv_summary_records)

print("\n" + "=" * 100)
print("CROSS-VALIDATION MEAN, SD AND MEAN FOLD CIs")
print("=" * 100)

display(cv_summary_df.round(4))


# ============================================================
# STEP 11: INDEPENDENT TEST RESULTS WITH 95% CIs
# ============================================================

test_results_df = pd.DataFrame(
    test_records
).set_index("Model")

test_columns = [
    "Accuracy", "Accuracy CI Low", "Accuracy CI High",
    "Precision", "Precision CI Low", "Precision CI High",
    "Sensitivity", "Sensitivity CI Low", "Sensitivity CI High",
    "Specificity", "Specificity CI Low", "Specificity CI High",
    "F1", "F1 CI Low", "F1 CI High",
    "AUC", "AUC CI Low", "AUC CI High",
    "Balanced Accuracy", "MCC",
    "TN", "FP", "FN", "TP"
]

test_results_df = test_results_df[test_columns]

print("\n" + "=" * 100)
print("INDEPENDENT TEST SET COMPARISON WITH 95% CIs")
print("=" * 100)

display(
    test_results_df.sort_values(
        by="F1",
        ascending=False
    ).round(4)
)


# ============================================================
# STEP 12: INDIVIDUAL MODEL COMPARISON
# ============================================================

print("\n" + "=" * 100)
print("MODEL COMPARISON")
print("=" * 100)

print("\nCross-validation summary:")
display(cv_summary_df.round(4))

print("\nIndependent test results:")
display(test_results_df.round(4))


# ============================================================
# STEP 13: CONFUSION MATRICES
# ============================================================

print("\n" + "=" * 100)
print("INDEPENDENT TEST CONFUSION MATRICES")
print("=" * 100)

for model_name in model_names:

    print(f"\n{model_name}")
    print("Rows = true labels [HC, PD]")
    print("Columns = predicted labels [HC, PD]")
    print(confusion_matrices[model_name])


# ============================================================
# STEP 14: SAVE RESULTS AS CSV
# ============================================================

fold_results_df.to_csv(
    "classification_fold_results_95CI.csv",
    index=False
)

cv_summary_df.to_csv(
    "classification_cv_summary_95CI.csv",
    index=False
)

test_results_df.to_csv(
    "classification_independent_test_results_95CI.csv"
)

print("\nSaved result files:")
print("1. classification_fold_results_95CI.csv")
print("2. classification_cv_summary_95CI.csv")
print("3. classification_independent_test_results_95CI.csv")

X shape: (320, 32)

Class distribution:
PD_Label_Combined
0    131
1    189
Name: count, dtype: int64

Training shape: (288, 32)
Test shape: (32, 32)

Training class distribution:
PD_Label_Combined
0    118
1    170
Name: count, dtype: int64

Independent test class distribution:
PD_Label_Combined
0    13
1    19
Name: count, dtype: int64

=====================================================================================
EVALUATING: LightGBM
=====================================================================================

Fold 01/10
Accuracy       : 0.7241 (95% CI: 0.5428-0.8530)
Precision      : 0.7368 (95% CI: 0.5121-0.8819)
Sensitivity    : 0.8235 (95% CI: 0.5897-0.9381)
Specificity    : 0.5833 (95% CI: 0.3195-0.8067)
F1             : 0.7778 (95% CI: 0.6471-0.8889)
AUC            : 0.8186 (95% CI: 0.6422-0.9510)

Fold 02/10
Accuracy       : 0.7241 (95% CI: 0.5428-0.8530)
Precision      : 0.8000 (95% CI: 0.5481-0.9295)
Sensitivity    : 0.7059 (95% CI: 0.4687-0.8672)
Specificity    : 0.7500 (95% CI: 0.4677-0.9111)
F1             : 0.7500 (95% CI: 0.5712-0.8889)
AUC            : 0.7304 (95% CI: 0.5293-0.9119)

Fold 03/10
Accuracy       : 0.7241 (95% CI: 0.5428-0.8530)
Precision      : 0.7368 (95% CI: 0.5121-0.8819)
Sensitivity    : 0.8235 (95% CI: 0.5897-0.9381)
Specificity    : 0.5833 (95% CI: 0.3195-0.8067)
F1             : 0.7778 (95% CI: 0.6286-0.8889)
AUC            : 0.7451 (95% CI: 0.5392-0.9118)

Fold 04/10
Accuracy       : 0.7241 (95% CI: 0.5428-0.8530)
Precision      : 0.8000 (95% CI: 0.5481-0.9295)
Sensitivity    : 0.7059 (95% CI: 0.4687-0.8672)
Specificity    : 0.7500 (95% CI: 0.4677-0.9111)
F1             : 0.7500 (95% CI: 0.5625-0.8890)
AUC            : 0.8039 (95% CI: 0.6176-0.9363)

Fold 05/10
Accuracy       : 0.6552 (95% CI: 0.4735-0.8006)
Precision      : 0.6842 (95% CI: 0.4601-0.8464)
Sensitivity    : 0.7647 (95% CI: 0.5274-0.9044)
Specificity    : 0.5000 (95% CI: 0.2538-0.7462)
F1             : 0.7222 (95% CI: 0.5625-0.8571)
AUC            : 0.7255 (95% CI: 0.5097-0.9069)

Fold 06/10
Accuracy       : 0.6552 (95% CI: 0.4735-0.8006)
Precision      : 0.7692 (95% CI: 0.4974-0.9182)
Sensitivity    : 0.5882 (95% CI: 0.3601-0.7839)
Specificity    : 0.7500 (95% CI: 0.4677-0.9111)
F1             : 0.6667 (95% CI: 0.4615-0.8387)
AUC            : 0.7108 (95% CI: 0.5049-0.8824)

Fold 07/10
Accuracy       : 0.6897 (95% CI: 0.5077-0.8272)
Precision      : 0.7857 (95% CI: 0.5241-0.9243)
Sensitivity    : 0.6471 (95% CI: 0.4130-0.8269)
Specificity    : 0.7500 (95% CI: 0.4677-0.9111)
F1             : 0.7097 (95% CI: 0.5185-0.8750)
AUC            : 0.6471 (95% CI: 0.4363-0.8578)

Fold 08/10
Accuracy       : 0.7241 (95% CI: 0.5428-0.8530)
Precision      : 0.7647 (95% CI: 0.5274-0.9044)
Sensitivity    : 0.7647 (95% CI: 0.5274-0.9044)
Specificity    : 0.6667 (95% CI: 0.3906-0.8619)
F1             : 0.7647 (95% CI: 0.6111-0.8889)
AUC            : 0.7157 (95% CI: 0.5098-0.9020)

Fold 09/10
Accuracy       : 0.7857 (95% CI: 0.6046-0.8979)
Precision      : 0.8235 (95% CI: 0.5897-0.9381)
Sensitivity    : 0.8235 (95% CI: 0.5897-0.9381)
Specificity    : 0.7273 (95% CI: 0.4344-0.9025)
F1             : 0.8235 (95% CI: 0.6875-0.9412)
AUC            : 0.8182 (95% CI: 0.6471-0.9572)

Fold 10/10
Accuracy       : 0.6429 (95% CI: 0.4583-0.7929)
Precision      : 0.7059 (95% CI: 0.4687-0.8672)
Sensitivity    : 0.7059 (95% CI: 0.4687-0.8672)
Specificity    : 0.5455 (95% CI: 0.2801-0.7873)
F1             : 0.7059 (95% CI: 0.5294-0.8571)
AUC            : 0.6952 (95% CI: 0.4759-0.8930)

LightGBM - 10-Fold CV Summary
---------------------------------------------------------------------------
Accuracy       : 0.7049 +/- 0.0440 | Mean fold CI: 0.5232-0.8384
Precision      : 0.7607 +/- 0.0444 | Mean fold CI: 0.5188-0.9022
Sensitivity    : 0.7353 +/- 0.0796 | Mean fold CI: 0.5003-0.8836
Specificity    : 0.6606 +/- 0.0986 | Mean fold CI: 0.3869-0.8556
F1             : 0.7448 +/- 0.0450 | Mean fold CI: 0.5780-0.8814
AUC            : 0.7410 +/- 0.0566 | Mean fold CI: 0.5412-0.9110

LightGBM - Independent Test Set
---------------------------------------------------------------------------
Accuracy       : 0.6562 (95% CI: 0.4831-0.7959)
Precision      : 0.7857 (95% CI: 0.5241-0.9243)
Sensitivity    : 0.5789 (95% CI: 0.3628-0.7686)
Specificity    : 0.7692 (95% CI: 0.4974-0.9182)
F1             : 0.6667 (95% CI: 0.4667-0.8333)
AUC            : 0.6761 (95% CI: 0.4615-0.8704)
Balanced Accuracy: 0.6741
MCC: 0.3447

Confusion Matrix (rows=true, columns=predicted):
[[10  3]
 [ 8 11]]

=====================================================================================
EVALUATING: Logistic Regression
=====================================================================================

Fold 01/10
Accuracy       : 0.7241 (95% CI: 0.5428-0.8530)
Precision      : 0.8000 (95% CI: 0.5481-0.9295)
Sensitivity    : 0.7059 (95% CI: 0.4687-0.8672)
Specificity    : 0.7500 (95% CI: 0.4677-0.9111)
F1             : 0.7500 (95% CI: 0.5714-0.9032)
AUC            : 0.8137 (95% CI: 0.6275-0.9559)

Fold 02/10
Accuracy       : 0.6207 (95% CI: 0.4400-0.7731)
Precision      : 0.6875 (95% CI: 0.4440-0.8584)
Sensitivity    : 0.6471 (95% CI: 0.4130-0.8269)
Specificity    : 0.5833 (95% CI: 0.3195-0.8067)
F1             : 0.6667 (95% CI: 0.4798-0.8235)
AUC            : 0.7010 (95% CI: 0.4852-0.8725)

Fold 03/10
Accuracy       : 0.6207 (95% CI: 0.4400-0.7731)
Precision      : 0.6875 (95% CI: 0.4440-0.8584)
Sensitivity    : 0.6471 (95% CI: 0.4130-0.8269)
Specificity    : 0.5833 (95% CI: 0.3195-0.8067)
F1             : 0.6667 (95% CI: 0.4667-0.8235)
AUC            : 0.6961 (95% CI: 0.4853-0.8776)

Fold 04/10
Accuracy       : 0.5517 (95% CI: 0.3755-0.7159)
Precision      : 0.6250 (95% CI: 0.3864-0.8152)
Sensitivity    : 0.5882 (95% CI: 0.3601-0.7839)
Specificity    : 0.5000 (95% CI: 0.2538-0.7462)
F1             : 0.6061 (95% CI: 0.4000-0.7568)
AUC            : 0.6912 (95% CI: 0.4853-0.8627)

Fold 05/10
Accuracy       : 0.6552 (95% CI: 0.4735-0.8006)
Precision      : 0.6842 (95% CI: 0.4601-0.8464)
Sensitivity    : 0.7647 (95% CI: 0.5274-0.9044)
Specificity    : 0.5000 (95% CI: 0.2538-0.7462)
F1             : 0.7222 (95% CI: 0.5625-0.8571)
AUC            : 0.5833 (95% CI: 0.3480-0.8137)

Fold 06/10
Accuracy       : 0.5862 (95% CI: 0.4074-0.7449)
Precision      : 0.6471 (95% CI: 0.4130-0.8269)
Sensitivity    : 0.6471 (95% CI: 0.4130-0.8269)
Specificity    : 0.5000 (95% CI: 0.2538-0.7462)
F1             : 0.6471 (95% CI: 0.4614-0.8000)
AUC            : 0.6275 (95% CI: 0.4020-0.8284)

Fold 07/10
Accuracy       : 0.6552 (95% CI: 0.4735-0.8006)
Precision      : 0.7692 (95% CI: 0.4974-0.9182)
Sensitivity    : 0.5882 (95% CI: 0.3601-0.7839)
Specificity    : 0.7500 (95% CI: 0.4677-0.9111)
F1             : 0.6667 (95% CI: 0.4665-0.8387)
AUC            : 0.6471 (95% CI: 0.4314-0.8480)

Fold 08/10
Accuracy       : 0.5862 (95% CI: 0.4074-0.7449)
Precision      : 0.6923 (95% CI: 0.4237-0.8732)
Sensitivity    : 0.5294 (95% CI: 0.3096-0.7383)
Specificity    : 0.6667 (95% CI: 0.3906-0.8619)
F1             : 0.6000 (95% CI: 0.3704-0.7742)
AUC            : 0.6176 (95% CI: 0.3971-0.8186)

Fold 09/10
Accuracy       : 0.7143 (95% CI: 0.5294-0.8475)
Precision      : 0.7647 (95% CI: 0.5274-0.9044)
Sensitivity    : 0.7647 (95% CI: 0.5274-0.9044)
Specificity    : 0.6364 (95% CI: 0.3538-0.8483)
F1             : 0.7647 (95% CI: 0.6061-0.8947)
AUC            : 0.7914 (95% CI: 0.5881-0.9519)

Fold 10/10
Accuracy       : 0.5714 (95% CI: 0.3907-0.7349)
Precision      : 0.6923 (95% CI: 0.4237-0.8732)
Sensitivity    : 0.5294 (95% CI: 0.3096-0.7383)
Specificity    : 0.6364 (95% CI: 0.3538-0.8483)
F1             : 0.6000 (95% CI: 0.3704-0.7879)
AUC            : 0.5936 (95% CI: 0.3690-0.8021)

Logistic Regression - 10-Fold CV Summary
---------------------------------------------------------------------------
Accuracy       : 0.6286 +/- 0.0585 | Mean fold CI: 0.4480-0.7788
Precision      : 0.7050 +/- 0.0556 | Mean fold CI: 0.4568-0.8704
Sensitivity    : 0.6412 +/- 0.0852 | Mean fold CI: 0.4102-0.8201
Specificity    : 0.6106 +/- 0.0952 | Mean fold CI: 0.3434-0.8233
F1             : 0.6690 +/- 0.0601 | Mean fold CI: 0.4755-0.8260
AUC            : 0.6762 +/- 0.0786 | Mean fold CI: 0.4619-0.8632

Logistic Regression - Independent Test Set
---------------------------------------------------------------------------
Accuracy       : 0.5625 (95% CI: 0.3933-0.7183)
Precision      : 0.6316 (95% CI: 0.4104-0.8085)
Sensitivity    : 0.6316 (95% CI: 0.4104-0.8085)
Specificity    : 0.4615 (95% CI: 0.2321-0.7086)
F1             : 0.6316 (95% CI: 0.4570-0.7778)
AUC            : 0.5992 (95% CI: 0.3846-0.8057)
Balanced Accuracy: 0.5466
MCC: 0.0931

Confusion Matrix (rows=true, columns=predicted):
[[ 6  7]
 [ 7 12]]

=====================================================================================
EVALUATING: SVM
=====================================================================================

Fold 01/10
Accuracy       : 0.7586 (95% CI: 0.5789-0.8778)
Precision      : 0.9167 (95% CI: 0.6461-0.9851)
Sensitivity    : 0.6471 (95% CI: 0.4130-0.8269)
Specificity    : 0.9167 (95% CI: 0.6461-0.9851)
F1             : 0.7586 (95% CI: 0.5600-0.9091)
AUC            : 0.8162 (95% CI: 0.6225-0.9657)

Fold 02/10
Accuracy       : 0.7241 (95% CI: 0.5428-0.8530)
Precision      : 0.8000 (95% CI: 0.5481-0.9295)
Sensitivity    : 0.7059 (95% CI: 0.4687-0.8672)
Specificity    : 0.7500 (95% CI: 0.4677-0.9111)
F1             : 0.7500 (95% CI: 0.5714-0.9032)
AUC            : 0.7696 (95% CI: 0.5784-0.9216)

Fold 03/10
Accuracy       : 0.5517 (95% CI: 0.3755-0.7159)
Precision      : 0.6429 (95% CI: 0.3876-0.8366)
Sensitivity    : 0.5294 (95% CI: 0.3096-0.7383)
Specificity    : 0.5833 (95% CI: 0.3195-0.8067)
F1             : 0.5806 (95% CI: 0.3571-0.7502)
AUC            : 0.6961 (95% CI: 0.4804-0.8676)

Fold 04/10
Accuracy       : 0.7241 (95% CI: 0.5428-0.8530)
Precision      : 0.8000 (95% CI: 0.5481-0.9295)
Sensitivity    : 0.7059 (95% CI: 0.4687-0.8672)
Specificity    : 0.7500 (95% CI: 0.4677-0.9111)
F1             : 0.7500 (95% CI: 0.5712-0.8889)
AUC            : 0.8088 (95% CI: 0.6225-0.9559)

Fold 05/10
Accuracy       : 0.6897 (95% CI: 0.5077-0.8272)
Precision      : 0.6818 (95% CI: 0.4732-0.8364)
Sensitivity    : 0.8824 (95% CI: 0.6566-0.9671)
Specificity    : 0.4167 (95% CI: 0.1933-0.6805)
F1             : 0.7692 (95% CI: 0.6500-0.8718)
AUC            : 0.6667 (95% CI: 0.4559-0.8578)

Fold 06/10
Accuracy       : 0.6552 (95% CI: 0.4735-0.8006)
Precision      : 0.7333 (95% CI: 0.4805-0.8910)
Sensitivity    : 0.6471 (95% CI: 0.4130-0.8269)
Specificity    : 0.6667 (95% CI: 0.3906-0.8619)
F1             : 0.6875 (95% CI: 0.5000-0.8485)
AUC            : 0.6814 (95% CI: 0.4608-0.8580)

Fold 07/10
Accuracy       : 0.6552 (95% CI: 0.4735-0.8006)
Precision      : 0.8182 (95% CI: 0.5230-0.9486)
Sensitivity    : 0.5294 (95% CI: 0.3096-0.7383)
Specificity    : 0.8333 (95% CI: 0.5520-0.9530)
F1             : 0.6429 (95% CI: 0.4167-0.8387)
AUC            : 0.6863 (95% CI: 0.4853-0.8725)

Fold 08/10
Accuracy       : 0.6207 (95% CI: 0.4400-0.7731)
Precision      : 0.7500 (95% CI: 0.4677-0.9111)
Sensitivity    : 0.5294 (95% CI: 0.3096-0.7383)
Specificity    : 0.7500 (95% CI: 0.4677-0.9111)
F1             : 0.6207 (95% CI: 0.3846-0.8000)
AUC            : 0.6961 (95% CI: 0.4803-0.8678)

Fold 09/10
Accuracy       : 0.7500 (95% CI: 0.5664-0.8732)
Precision      : 0.8125 (95% CI: 0.5699-0.9341)
Sensitivity    : 0.7647 (95% CI: 0.5274-0.9044)
Specificity    : 0.7273 (95% CI: 0.4344-0.9025)
F1             : 0.7879 (95% CI: 0.6249-0.9143)
AUC            : 0.8663 (95% CI: 0.7059-0.9786)

Fold 10/10
Accuracy       : 0.5357 (95% CI: 0.3581-0.7047)
Precision      : 0.6429 (95% CI: 0.3876-0.8366)
Sensitivity    : 0.5294 (95% CI: 0.3096-0.7383)
Specificity    : 0.5455 (95% CI: 0.2801-0.7873)
F1             : 0.5806 (95% CI: 0.3704-0.7647)
AUC            : 0.5615 (95% CI: 0.3209-0.7861)

SVM - 10-Fold CV Summary
---------------------------------------------------------------------------
Accuracy       : 0.6665 +/- 0.0784 | Mean fold CI: 0.4859-0.8079
Precision      : 0.7598 +/- 0.0871 | Mean fold CI: 0.5032-0.9038
Sensitivity    : 0.6471 +/- 0.1209 | Mean fold CI: 0.4186-0.8213
Specificity    : 0.6939 +/- 0.1459 | Mean fold CI: 0.4219-0.8710
F1             : 0.6928 +/- 0.0807 | Mean fold CI: 0.5006-0.8489
AUC            : 0.7249 +/- 0.0898 | Mean fold CI: 0.5213-0.8932

SVM - Independent Test Set
---------------------------------------------------------------------------
Accuracy       : 0.6562 (95% CI: 0.4831-0.7959)
Precision      : 0.7500 (95% CI: 0.5050-0.8982)
Sensitivity    : 0.6316 (95% CI: 0.4104-0.8085)
Specificity    : 0.6923 (95% CI: 0.4237-0.8732)
F1             : 0.6857 (95% CI: 0.5000-0.8421)
AUC            : 0.6397 (95% CI: 0.4413-0.8340)
Balanced Accuracy: 0.6619
MCC: 0.3181

Confusion Matrix (rows=true, columns=predicted):
[[ 9  4]
 [ 7 12]]

=====================================================================================
EVALUATING: Decision Tree
=====================================================================================

Fold 01/10
Accuracy       : 0.6552 (95% CI: 0.4735-0.8006)
Precision      : 0.8182 (95% CI: 0.5230-0.9486)
Sensitivity    : 0.5294 (95% CI: 0.3096-0.7383)
Specificity    : 0.8333 (95% CI: 0.5520-0.9530)
F1             : 0.6429 (95% CI: 0.4167-0.8276)
AUC            : 0.7500 (95% CI: 0.5466-0.9020)

Fold 02/10
Accuracy       : 0.5517 (95% CI: 0.3755-0.7159)
Precision      : 0.7500 (95% CI: 0.4093-0.9285)
Sensitivity    : 0.3529 (95% CI: 0.1731-0.5870)
Specificity    : 0.8333 (95% CI: 0.5520-0.9530)
F1             : 0.4800 (95% CI: 0.2000-0.6897)
AUC            : 0.7132 (95% CI: 0.5074-0.8848)

Fold 03/10
Accuracy       : 0.5517 (95% CI: 0.3755-0.7159)
Precision      : 0.6250 (95% CI: 0.3864-0.8152)
Sensitivity    : 0.5882 (95% CI: 0.3601-0.7839)
Specificity    : 0.5000 (95% CI: 0.2538-0.7462)
F1             : 0.6061 (95% CI: 0.4000-0.7647)
AUC            : 0.6887 (95% CI: 0.4828-0.8653)

Fold 04/10
Accuracy       : 0.7241 (95% CI: 0.5428-0.8530)
Precision      : 0.9091 (95% CI: 0.6226-0.9838)
Sensitivity    : 0.5882 (95% CI: 0.3601-0.7839)
Specificity    : 0.9167 (95% CI: 0.6461-0.9851)
F1             : 0.7143 (95% CI: 0.5000-0.8752)
AUC            : 0.6936 (95% CI: 0.4853-0.8824)

Fold 05/10
Accuracy       : 0.5862 (95% CI: 0.4074-0.7449)
Precision      : 0.6316 (95% CI: 0.4104-0.8085)
Sensitivity    : 0.7059 (95% CI: 0.4687-0.8672)
Specificity    : 0.4167 (95% CI: 0.1933-0.6805)
F1             : 0.6667 (95% CI: 0.5000-0.8108)
AUC            : 0.6152 (95% CI: 0.3995-0.8088)

Fold 06/10
Accuracy       : 0.6552 (95% CI: 0.4735-0.8006)
Precision      : 0.7059 (95% CI: 0.4687-0.8672)
Sensitivity    : 0.7059 (95% CI: 0.4687-0.8672)
Specificity    : 0.5833 (95% CI: 0.3195-0.8067)
F1             : 0.7059 (95% CI: 0.5333-0.8571)
AUC            : 0.6618 (95% CI: 0.4583-0.8431)

Fold 07/10
Accuracy       : 0.5172 (95% CI: 0.3443-0.6861)
Precision      : 0.6667 (95% CI: 0.3542-0.8794)
Sensitivity    : 0.3529 (95% CI: 0.1731-0.5870)
Specificity    : 0.7500 (95% CI: 0.4677-0.9111)
F1             : 0.4615 (95% CI: 0.2219-0.6667)
AUC            : 0.5858 (95% CI: 0.3774-0.7868)

Fold 08/10
Accuracy       : 0.5862 (95% CI: 0.4074-0.7449)
Precision      : 0.6667 (95% CI: 0.4171-0.8482)
Sensitivity    : 0.5882 (95% CI: 0.3601-0.7839)
Specificity    : 0.5833 (95% CI: 0.3195-0.8067)
F1             : 0.6250 (95% CI: 0.4138-0.7879)
AUC            : 0.6005 (95% CI: 0.3922-0.7917)

Fold 09/10
Accuracy       : 0.6071 (95% CI: 0.4241-0.7643)
Precision      : 0.7500 (95% CI: 0.4677-0.9111)
Sensitivity    : 0.5294 (95% CI: 0.3096-0.7383)
Specificity    : 0.7273 (95% CI: 0.4344-0.9025)
F1             : 0.6207 (95% CI: 0.3846-0.8000)
AUC            : 0.5882 (95% CI: 0.3717-0.8075)

Fold 10/10
Accuracy       : 0.5000 (95% CI: 0.3263-0.6737)
Precision      : 0.5789 (95% CI: 0.3628-0.7686)
Sensitivity    : 0.6471 (95% CI: 0.4130-0.8269)
Specificity    : 0.2727 (95% CI: 0.0975-0.5656)
F1             : 0.6111 (95% CI: 0.4375-0.7502)
AUC            : 0.5936 (95% CI: 0.3769-0.7968)

Decision Tree - 10-Fold CV Summary
---------------------------------------------------------------------------
Accuracy       : 0.5935 +/- 0.0691 | Mean fold CI: 0.4150-0.7500
Precision      : 0.7102 +/- 0.0994 | Mean fold CI: 0.4422-0.8759
Sensitivity    : 0.5588 +/- 0.1248 | Mean fold CI: 0.3396-0.7564
Specificity    : 0.6417 +/- 0.2060 | Mean fold CI: 0.3836-0.8311
F1             : 0.6134 +/- 0.0840 | Mean fold CI: 0.4008-0.7830
AUC            : 0.6491 +/- 0.0599 | Mean fold CI: 0.4398-0.8369

Decision Tree - Independent Test Set
---------------------------------------------------------------------------
Accuracy       : 0.5938 (95% CI: 0.4226-0.7448)
Precision      : 0.6667 (95% CI: 0.4375-0.8372)
Sensitivity    : 0.6316 (95% CI: 0.4104-0.8085)
Specificity    : 0.5385 (95% CI: 0.2914-0.7679)
F1             : 0.6486 (95% CI: 0.4706-0.7909)
AUC            : 0.5931 (95% CI: 0.3927-0.7814)
Balanced Accuracy: 0.5850
MCC: 0.1683

Confusion Matrix (rows=true, columns=predicted):
[[ 7  6]
 [ 7 12]]

====================================================================================================
ALL MODELS: INDIVIDUAL FOLD RESULTS WITH 95% CIs
====================================================================================================

,Model,Fold,Accuracy,Accuracy CI Low,Accuracy CI High,Precision,Precision CI Low,Precision CI High,Sensitivity,Sensitivity CI Low,...,F1 CI High,AUC,AUC CI Low,AUC CI High,Balanced Accuracy,MCC,TN,FP,FN,TP
30,Decision Tree,1,0.6552,0.4735,0.8006,0.8182,0.5230,0.9486,0.5294,0.3096,...,0.8276,0.7500,0.5466,0.9020,0.6814,0.3682,10,2,8,9
31,Decision Tree,2,0.5517,0.3755,0.7159,0.7500,0.4093,0.9285,0.3529,0.1731,...,0.6897,0.7132,0.5074,0.8848,0.5931,0.2053,10,2,11,6
32,Decision Tree,3,0.5517,0.3755,0.7159,0.6250,0.3864,0.8152,0.5882,0.3601,...,0.7647,0.6887,0.4828,0.8653,0.5441,0.0874,6,6,7,10
33,Decision Tree,4,0.7241,0.5428,0.8530,0.9091,0.6226,0.9838,0.5882,0.3601,...,0.8752,0.6936,0.4853,0.8824,0.7525,0.5125,11,1,7,10
34,Decision Tree,5,0.5862,0.4074,0.7449,0.6316,0.4104,0.8085,0.7059,0.4687,...,0.8108,0.6152,0.3995,0.8088,0.5613,0.1270,5,7,5,12
35,Decision Tree,6,0.6552,0.4735,0.8006,0.7059,0.4687,0.8672,0.7059,0.4687,...,0.8571,0.6618,0.4583,0.8431,0.6446,0.2892,7,5,5,12
36,Decision Tree,7,0.5172,0.3443,0.6861,0.6667,0.3542,0.8794,0.3529,0.1731,...,0.6667,0.5858,0.3774,0.7868,0.5515,0.1096,9,3,11,6
37,Decision Tree,8,0.5862,0.4074,0.7449,0.6667,0.4171,0.8482,0.5882,0.3601,...,0.7879,0.6005,0.3922,0.7917,0.5858,0.1691,7,5,7,10
38,Decision Tree,9,0.6071,0.4241,0.7643,0.7500,0.4677,0.9111,0.5294,0.3096,...,0.8000,0.5882,0.3717,0.8075,0.6283,0.2533,8,3,8,9
39,Decision Tree,10,0.5000,0.3263,0.6737,0.5789,0.3628,0.7686,0.6471,0.4130,...,0.7502,0.5936,0.3769,0.7968,0.4599,-0.0839,3,8,6,11
0,LightGBM,1,0.7241,0.5428,0.8530,0.7368,0.5121,0.8819,0.8235,0.5897,...,0.8889,0.8186,0.6422,0.9510,0.7034,0.4216,7,5,3,14
1,LightGBM,2,0.7241,0.5428,0.8530,0.8000,0.5481,0.9295,0.7059,0.4687,...,0.8889,0.7304,0.5293,0.9119,0.7279,0.4493,9,3,5,12
2,LightGBM,3,0.7241,0.5428,0.8530,0.7368,0.5121,0.8819,0.8235,0.5897,...,0.8889,0.7451,0.5392,0.9118,0.7034,0.4216,7,5,3,14
3,LightGBM,4,0.7241,0.5428,0.8530,0.8000,0.5481,0.9295,0.7059,0.4687,...,0.8890,0.8039,0.6176,0.9363,0.7279,0.4493,9,3,5,12
4,LightGBM,5,0.6552,0.4735,0.8006,0.6842,0.4601,0.8464,0.7647,0.5274,...,0.8571,0.7255,0.5097,0.9069,0.6324,0.2743,6,6,4,13
5,LightGBM,6,0.6552,0.4735,0.8006,0.7692,0.4974,0.9182,0.5882,0.3601,...,0.8387,0.7108,0.5049,0.8824,0.6691,0.3350,9,3,7,10
6,LightGBM,7,0.6897,0.5077,0.8272,0.7857,0.5241,0.9243,0.6471,0.4130,...,0.8750,0.6471,0.4363,0.8578,0.6985,0.3913,9,3,6,11
7,LightGBM,8,0.7241,0.5428,0.8530,0.7647,0.5274,0.9044,0.7647,0.5274,...,0.8889,0.7157,0.5098,0.9020,0.7157,0.4314,8,4,4,13
8,LightGBM,9,0.7857,0.6046,0.8979,0.8235,0.5897,0.9381,0.8235,0.5897,...,0.9412,0.8182,0.6471,0.9572,0.7754,0.5508,8,3,3,14
9,LightGBM,10,0.6429,0.4583,0.7929,0.7059,0.4687,0.8672,0.7059,0.4687,...,0.8571,0.6952,0.4759,0.8930,0.6257,0.2513,6,5,5,12
10,Logistic Regression,1,0.7241,0.5428,0.8530,0.8000,0.5481,0.9295,0.7059,0.4687,...,0.9032,0.8137,0.6275,0.9559,0.7279,0.4493,9,3,5,12
11,Logistic Regression,2,0.6207,0.4400,0.7731,0.6875,0.4440,0.8584,0.6471,0.4130,...,0.8235,0.7010,0.4852,0.8725,0.6152,0.2282,7,5,6,11
12,Logistic Regression,3,0.6207,0.4400,0.7731,0.6875,0.4440,0.8584,0.6471,0.4130,...,0.8235,0.6961,0.4853,0.8776,0.6152,0.2282,7,5,6,11
13,Logistic Regression,4,0.5517,0.3755,0.7159,0.6250,0.3864,0.8152,0.5882,0.3601,...,0.7568,0.6912,0.4853,0.8627,0.5441,0.0874,6,6,7,10
14,Logistic Regression,5,0.6552,0.4735,0.8006,0.6842,0.4601,0.8464,0.7647,0.5274,...,0.8571,0.5833,0.3480,0.8137,0.6324,0.2743,6,6,4,13
15,Logistic Regression,6,0.5862,0.4074,0.7449,0.6471,0.4130,0.8269,0.6471,0.4130,...,0.8000,0.6275,0.4020,0.8284,0.5735,0.1471,6,6,6,11
16,Logistic Regression,7,0.6552,0.4735,0.8006,0.7692,0.4974,0.9182,0.5882,0.3601,...,0.8387,0.6471,0.4314,0.8480,0.6691,0.3350,9,3,7,10
17,Logistic Regression,8,0.5862,0.4074,0.7449,0.6923,0.4237,0.8732,0.5294,0.3096,...,0.7742,0.6176,0.3971,0.8186,0.5980,0.1942,8,4,8,9
18,Logistic Regression,9,0.7143,0.5294,0.8475,0.7647,0.5274,0.9044,0.7647,0.5274,...,0.8947,0.7914,0.5881,0.9519,0.7005,0.4011,7,4,4,13
19,Logistic Regression,10,0.5714,0.3907,0.7349,0.6923,0.4237,0.8732,0.5294,0.3096,...,0.7879,0.5936,0.3690,0.8021,0.5829,0.1623,7,4,8,9
20,SVM,1,0.7586,0.5789,0.8778,0.9167,0.6461,0.9851,0.6471,0.4130,...,0.9091,0.8162,0.6225,0.9657,0.7819,0.5637,11,1,6,11
21,SVM,2,0.7241,0.5428,0.8530,0.8000,0.5481,0.9295,0.7059,0.4687,...,0.9032,0.7696,0.5784,0.9216,0.7279,0.4493,9,3,5,12
22,SVM,3,0.5517,0.3755,0.7159,0.6429,0.3876,0.8366,0.5294,0.3096,...,0.7502,0.6961,0.4804,0.8676,0.5564,0.1111,7,5,8,9
23,SVM,4,0.7241,0.5428,0.8530,0.8000,0.5481,0.9295,0.7059,0.4687,...,0.8889,0.8088,0.6225,0.9559,0.7279,0.4493,9,3,5,12
24,SVM,5,0.6897,0.5077,0.8272,0.6818,0.4732,0.8364,0.8824,0.6566,...,0.8718,0.6667,0.4559,0.8578,0.6495,0.3442,5,7,2,15
25,SVM,6,0.6552,0.4735,0.8006,0.7333,0.4805,0.8910,0.6471,0.4130,...,0.8485,0.6814,0.4608,0.8580,0.6569,0.3092,8,4,6,11
26,SVM,7,0.6552,0.4735,0.8006,0.8182,0.5230,0.9486,0.5294,0.3096,...,0.8387,0.6863,0.4853,0.8725,0.6814,0.3682,10,2,8,9
27,SVM,8,0.6207,0.4400,0.7731,0.7500,0.4677,0.9111,0.5294,0.3096,...,0.8000,0.6961,0.4803,0.8678,0.6397,0.2794,9,3,8,9
28,SVM,9,0.7500,0.5664,0.8732,0.8125,0.5699,0.9341,0.7647,0.5274,...,0.9143,0.8663,0.7059,0.9786,0.7460,0.4855,8,3,4,13
29,SVM,10,0.5357,0.3581,0.7047,0.6429,0.3876,0.8366,0.5294,0.3096,...,0.7647,0.5615,0.3209,0.7861,0.5374,0.0731,6,5,8,9

====================================================================================================
CROSS-VALIDATION MEAN, SD AND MEAN FOLD CIs
====================================================================================================

,Model,CV Accuracy Mean,CV Accuracy SD,Mean Fold Accuracy CI Low,Mean Fold Accuracy CI High,CV Precision Mean,CV Precision SD,Mean Fold Precision CI Low,Mean Fold Precision CI High,CV Sensitivity Mean,...,Mean Fold F1 CI Low,Mean Fold F1 CI High,CV AUC Mean,CV AUC SD,Mean Fold AUC CI Low,Mean Fold AUC CI High,CV Balanced Accuracy Mean,CV Balanced Accuracy SD,CV MCC Mean,CV MCC SD
0,LightGBM,0.7049,0.0440,0.5232,0.8384,0.7607,0.0444,0.5188,0.9022,0.7353,...,0.5780,0.8814,0.7410,0.0566,0.5412,0.9110,0.6980,0.0454,0.3976,0.0892
1,Logistic Regression,0.6286,0.0585,0.4480,0.7788,0.7050,0.0556,0.4568,0.8704,0.6412,...,0.4755,0.8260,0.6762,0.0786,0.4619,0.8632,0.6259,0.0579,0.2507,0.1151
2,SVM,0.6665,0.0784,0.4859,0.8079,0.7598,0.0871,0.5032,0.9038,0.6471,...,0.5006,0.8489,0.7249,0.0898,0.5213,0.8932,0.6705,0.0797,0.3433,0.1578
3,Decision Tree,0.5935,0.0691,0.4150,0.7500,0.7102,0.0994,0.4422,0.8759,0.5588,...,0.4008,0.7830,0.6491,0.0599,0.4398,0.8369,0.6002,0.0813,0.2038,0.1648

====================================================================================================
INDEPENDENT TEST SET COMPARISON WITH 95% CIs
====================================================================================================

,Accuracy,Accuracy CI Low,Accuracy CI High,Precision,Precision CI Low,Precision CI High,Sensitivity,Sensitivity CI Low,Sensitivity CI High,Specificity,...,F1 CI High,AUC,AUC CI Low,AUC CI High,Balanced Accuracy,MCC,TN,FP,FN,TP
Model,,,,,,,,,,,,,,,,,,,,,
SVM,0.6562,0.4831,0.7959,0.7500,0.5050,0.8982,0.6316,0.4104,0.8085,0.6923,...,0.8421,0.6397,0.4413,0.8340,0.6619,0.3181,9,4,7,12
LightGBM,0.6562,0.4831,0.7959,0.7857,0.5241,0.9243,0.5789,0.3628,0.7686,0.7692,...,0.8333,0.6761,0.4615,0.8704,0.6741,0.3447,10,3,8,11
Decision Tree,0.5938,0.4226,0.7448,0.6667,0.4375,0.8372,0.6316,0.4104,0.8085,0.5385,...,0.7909,0.5931,0.3927,0.7814,0.5850,0.1683,7,6,7,12
Logistic Regression,0.5625,0.3933,0.7183,0.6316,0.4104,0.8085,0.6316,0.4104,0.8085,0.4615,...,0.7778,0.5992,0.3846,0.8057,0.5466,0.0931,6,7,7,12

====================================================================================================
MODEL COMPARISON
====================================================================================================

Cross-validation summary:

,Model,CV Accuracy Mean,CV Accuracy SD,Mean Fold Accuracy CI Low,Mean Fold Accuracy CI High,CV Precision Mean,CV Precision SD,Mean Fold Precision CI Low,Mean Fold Precision CI High,CV Sensitivity Mean,...,Mean Fold F1 CI Low,Mean Fold F1 CI High,CV AUC Mean,CV AUC SD,Mean Fold AUC CI Low,Mean Fold AUC CI High,CV Balanced Accuracy Mean,CV Balanced Accuracy SD,CV MCC Mean,CV MCC SD
0,LightGBM,0.7049,0.0440,0.5232,0.8384,0.7607,0.0444,0.5188,0.9022,0.7353,...,0.5780,0.8814,0.7410,0.0566,0.5412,0.9110,0.6980,0.0454,0.3976,0.0892
1,Logistic Regression,0.6286,0.0585,0.4480,0.7788,0.7050,0.0556,0.4568,0.8704,0.6412,...,0.4755,0.8260,0.6762,0.0786,0.4619,0.8632,0.6259,0.0579,0.2507,0.1151
2,SVM,0.6665,0.0784,0.4859,0.8079,0.7598,0.0871,0.5032,0.9038,0.6471,...,0.5006,0.8489,0.7249,0.0898,0.5213,0.8932,0.6705,0.0797,0.3433,0.1578
3,Decision Tree,0.5935,0.0691,0.4150,0.7500,0.7102,0.0994,0.4422,0.8759,0.5588,...,0.4008,0.7830,0.6491,0.0599,0.4398,0.8369,0.6002,0.0813,0.2038,0.1648

Independent test results:

,Accuracy,Accuracy CI Low,Accuracy CI High,Precision,Precision CI Low,Precision CI High,Sensitivity,Sensitivity CI Low,Sensitivity CI High,Specificity,...,F1 CI High,AUC,AUC CI Low,AUC CI High,Balanced Accuracy,MCC,TN,FP,FN,TP
Model,,,,,,,,,,,,,,,,,,,,,
LightGBM,0.6562,0.4831,0.7959,0.7857,0.5241,0.9243,0.5789,0.3628,0.7686,0.7692,...,0.8333,0.6761,0.4615,0.8704,0.6741,0.3447,10,3,8,11
Logistic Regression,0.5625,0.3933,0.7183,0.6316,0.4104,0.8085,0.6316,0.4104,0.8085,0.4615,...,0.7778,0.5992,0.3846,0.8057,0.5466,0.0931,6,7,7,12
SVM,0.6562,0.4831,0.7959,0.7500,0.5050,0.8982,0.6316,0.4104,0.8085,0.6923,...,0.8421,0.6397,0.4413,0.8340,0.6619,0.3181,9,4,7,12
Decision Tree,0.5938,0.4226,0.7448,0.6667,0.4375,0.8372,0.6316,0.4104,0.8085,0.5385,...,0.7909,0.5931,0.3927,0.7814,0.5850,0.1683,7,6,7,12

====================================================================================================
INDEPENDENT TEST CONFUSION MATRICES
====================================================================================================

LightGBM
Rows = true labels [HC, PD]
Columns = predicted labels [HC, PD]
[[10  3]
 [ 8 11]]

Logistic Regression
Rows = true labels [HC, PD]
Columns = predicted labels [HC, PD]
[[ 6  7]
 [ 7 12]]

SVM
Rows = true labels [HC, PD]
Columns = predicted labels [HC, PD]
[[ 9  4]
 [ 7 12]]

Decision Tree
Rows = true labels [HC, PD]
Columns = predicted labels [HC, PD]
[[ 7  6]
 [ 7 12]]

Saved result files:
1. classification_fold_results_95CI.csv
2. classification_cv_summary_95CI.csv
3. classification_independent_test_results_95CI.csv

In [6]:
# ============================================================
# CLASSIFICATION WITH 95% CONFIDENCE INTERVALS
# Stratified 10-Fold CV + Independent Test Set
#
# Models:
#   1. LightGBM
#   2. Logistic Regression
#   3. Support Vector Machine (SVM)
#   4. Decision Tree
#   5. Gaussian Naive Bayes
#   6. Linear Discriminant Analysis (LDA)
#
# Metrics with 95% CI:
# Accuracy, Precision, Sensitivity, Specificity, F1, AUC
#
# Additional metrics:
# Balanced Accuracy, MCC, TN, FP, FN, TP
# ============================================================

!pip install -q lightgbm scikit-learn statsmodels pandas numpy

import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

from sklearn.model_selection import (
    train_test_split,
    StratifiedKFold
)

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    balanced_accuracy_score,
    matthews_corrcoef,
    confusion_matrix
)

from statsmodels.stats.proportion import proportion_confint
from lightgbm import LGBMClassifier


# ============================================================
# STEP 1: PREPARE DATA
# ============================================================

feature_cols = [f"feat_{i}" for i in range(32)]

X = fused_df_named_int[feature_cols].copy()
y = fused_df_named_int["PD_Label_Combined"].copy()

X = X.apply(pd.to_numeric, errors="coerce")
X = X.replace([np.inf, -np.inf], np.nan)
y = pd.to_numeric(y, errors="coerce")

valid = y.notna()

X = X.loc[valid].reset_index(drop=True)
y = y.loc[valid].astype(int).reset_index(drop=True)

if set(y.unique()) != {0, 1}:
    raise ValueError("Labels must be encoded as 0 and 1.")

if X.shape[1] != 32:
    raise ValueError("Expected exactly 32 embedding features.")

if y.value_counts().min() < 10:
    raise ValueError(
        "Each class needs at least 10 samples for stratified "
        "10-fold cross-validation."
    )

print("X shape:", X.shape)
print("\nClass distribution:")
print(y.value_counts().sort_index())


# ============================================================
# STEP 2: TRAIN-TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.10,
    stratify=y,
    random_state=42
)

print("\nTraining shape:", X_train.shape)
print("Test shape:", X_test.shape)

print("\nTraining class distribution:")
print(y_train.value_counts().sort_index())

print("\nIndependent test class distribution:")
print(y_test.value_counts().sort_index())


# ============================================================
# STEP 3: MODEL FACTORY
# ============================================================

def create_models(y_fit):

    # --------------------------------------------------------
    # 1. LightGBM
    # --------------------------------------------------------

    lightgbm = LGBMClassifier(
        objective="binary",
        n_estimators=200,
        learning_rate=0.03,
        num_leaves=15,
        max_depth=4,
        min_child_samples=10,
        subsample=0.85,
        subsample_freq=1,
        colsample_bytree=0.85,
        reg_alpha=0.1,
        reg_lambda=2.0,
        class_weight="balanced",
        random_state=42,
        n_jobs=-1,
        verbosity=-1
    )

    # --------------------------------------------------------
    # 2. Logistic Regression
    # Scaling is performed inside each fold.
    # --------------------------------------------------------

    logistic_regression = Pipeline([
        ("scaler", StandardScaler()),
        ("classifier", LogisticRegression(
            C=1.0,
            penalty="l2",
            solver="liblinear",
            class_weight="balanced",
            max_iter=1000,
            random_state=42
        ))
    ])

    # --------------------------------------------------------
    # 3. Support Vector Machine (RBF kernel)
    # Scaling and probability estimates are included.
    # --------------------------------------------------------

    svm = Pipeline([
        ("scaler", StandardScaler()),
        ("classifier", SVC(
            C=1.0,
            kernel="rbf",
            gamma="scale",
            probability=True,
            class_weight="balanced",
            random_state=42
        ))
    ])

    # --------------------------------------------------------
    # 4. Decision Tree
    # --------------------------------------------------------

    decision_tree = DecisionTreeClassifier(
        criterion="gini",
        max_depth=5,
        min_samples_split=5,
        min_samples_leaf=3,
        class_weight="balanced",
        random_state=42
    )

    # --------------------------------------------------------
    # 5. Gaussian Naive Bayes
    # Models each feature using a Gaussian distribution
    # conditional on the class.
    # --------------------------------------------------------

    gaussian_nb = GaussianNB()

    # --------------------------------------------------------
    # 6. Linear Discriminant Analysis (LDA)
    # Shrinkage helps stabilize covariance estimation when
    # features are correlated or the sample size is limited.
    # --------------------------------------------------------

    lda = LinearDiscriminantAnalysis(
        solver="lsqr",
        shrinkage="auto"
    )

    return {
        "LightGBM": lightgbm,
        "Logistic Regression": logistic_regression,
        "SVM": svm,
        "Decision Tree": decision_tree,
        "Gaussian Naive Bayes": gaussian_nb,
        "LDA": lda
    }


# ============================================================
# STEP 4: METRICS + 95% CONFIDENCE INTERVALS
# ============================================================

def calculate_metrics_with_ci(
    y_true,
    y_pred,
    y_prob,
    n_boot=2000,
    random_state=42
):

    y_true = np.asarray(y_true).astype(int)
    y_pred = np.asarray(y_pred).astype(int)
    y_prob = np.asarray(y_prob, dtype=float)

    tn, fp, fn, tp = confusion_matrix(
        y_true,
        y_pred,
        labels=[0, 1]
    ).ravel()

    n = len(y_true)

    # ---------------- Point estimates ----------------

    accuracy = accuracy_score(y_true, y_pred)

    precision = precision_score(
        y_true, y_pred, zero_division=0
    )

    sensitivity = recall_score(
        y_true, y_pred, zero_division=0
    )

    specificity = (
        tn / (tn + fp) if (tn + fp) > 0 else np.nan
    )

    f1 = f1_score(
        y_true, y_pred, zero_division=0
    )

    auc = roc_auc_score(y_true, y_prob)

    results = {
        "Accuracy": accuracy,
        "Precision": precision,
        "Sensitivity": sensitivity,
        "Specificity": specificity,
        "F1": f1,
        "AUC": auc,
        "Balanced Accuracy": balanced_accuracy_score(
            y_true, y_pred
        ),
        "MCC": matthews_corrcoef(y_true, y_pred),
        "TN": tn,
        "FP": fp,
        "FN": fn,
        "TP": tp
    }

    # ---------------- Wilson 95% CIs ----------------

    proportions = {
        "Accuracy": (tp + tn, n),
        "Precision": (tp, tp + fp),
        "Sensitivity": (tp, tp + fn),
        "Specificity": (tn, tn + fp)
    }

    for metric, (count, denominator) in proportions.items():

        if denominator > 0:
            low, high = proportion_confint(
                count=count,
                nobs=denominator,
                alpha=0.05,
                method="wilson"
            )
        else:
            low, high = np.nan, np.nan

        results[f"{metric} CI Low"] = low
        results[f"{metric} CI High"] = high

    # ---------------- Stratified bootstrap CIs ----------------
    # Resample within each class, preserving class counts.

    rng = np.random.default_rng(random_state)

    class_indices = [
        np.flatnonzero(y_true == 0),
        np.flatnonzero(y_true == 1)
    ]

    bootstrap_f1 = []
    bootstrap_auc = []

    for _ in range(n_boot):

        sampled_indices = np.concatenate([
            rng.choice(
                indices,
                size=len(indices),
                replace=True
            )
            for indices in class_indices
        ])

        yt = y_true[sampled_indices]
        yp = y_pred[sampled_indices]
        pr = y_prob[sampled_indices]

        bootstrap_f1.append(
            f1_score(yt, yp, zero_division=0)
        )

        bootstrap_auc.append(
            roc_auc_score(yt, pr)
        )

    for metric, values in [
        ("F1", bootstrap_f1),
        ("AUC", bootstrap_auc)
    ]:

        low, high = np.percentile(
            values,
            [2.5, 97.5]
        )

        results[f"{metric} CI Low"] = low
        results[f"{metric} CI High"] = high

    return results


# ============================================================
# STEP 5: PREPROCESSING
# ============================================================

def make_preprocessor():
    return SimpleImputer(strategy="median")


# ============================================================
# STEP 6: STRATIFIED 10-FOLD CROSS-VALIDATION
# ============================================================

skf = StratifiedKFold(
    n_splits=10,
    shuffle=True,
    random_state=42
)

model_names = [
    "LightGBM",
    "Logistic Regression",
    "SVM",
    "Decision Tree",
    "Gaussian Naive Bayes",
    "LDA"
]

cv_records = []
cv_summary_records = []
test_records = []
confusion_matrices = {}

metrics_to_report = [
    "Accuracy",
    "Precision",
    "Sensitivity",
    "Specificity",
    "F1",
    "AUC"
]


for model_name in model_names:

    print("\n" + "=" * 85)
    print("EVALUATING:", model_name)
    print("=" * 85)

    fold_metrics = []

    for fold, (train_idx, val_idx) in enumerate(
        skf.split(X_train, y_train),
        start=1
    ):

        X_tr = X_train.iloc[train_idx]
        X_val = X_train.iloc[val_idx]

        y_tr = y_train.iloc[train_idx]
        y_val = y_train.iloc[val_idx]

        # Imputation is fitted on training data only.
        imputer = make_preprocessor()

        X_tr_imp = imputer.fit_transform(X_tr)
        X_val_imp = imputer.transform(X_val)

        # Create a fresh model for every fold.
        model = create_models(y_tr)[model_name]

        model.fit(X_tr_imp, y_tr)

        val_pred = np.asarray(
            model.predict(X_val_imp)
        ).reshape(-1).astype(int)

        val_prob = model.predict_proba(X_val_imp)[:, 1]

        metrics = calculate_metrics_with_ci(
            y_val,
            val_pred,
            val_prob,
            n_boot=2000,
            random_state=1000 + fold
        )

        metrics["Model"] = model_name
        metrics["Fold"] = fold

        fold_metrics.append(metrics)
        cv_records.append(metrics.copy())

        print(f"\nFold {fold:02d}/10")

        for metric in metrics_to_report:

            print(
                f"{metric:15s}: {metrics[metric]:.4f} "
                f"(95% CI: "
                f"{metrics[metric + ' CI Low']:.4f}-"
                f"{metrics[metric + ' CI High']:.4f})"
            )

    # ========================================================
    # STEP 7: CV MEAN AND STANDARD DEVIATION
    # ========================================================

    fold_df = pd.DataFrame(fold_metrics)

    print(f"\n{model_name} - 10-Fold CV Summary")
    print("-" * 75)

    summary = {"Model": model_name}

    for metric in metrics_to_report:

        mean_val = fold_df[metric].mean()
        std_val = fold_df[metric].std(ddof=1)

        # Descriptive averages of fold CI endpoints.
        # These are not formal pooled 95% confidence intervals.
        mean_ci_low = fold_df[
            f"{metric} CI Low"
        ].mean()

        mean_ci_high = fold_df[
            f"{metric} CI High"
        ].mean()

        summary[f"CV {metric} Mean"] = mean_val
        summary[f"CV {metric} SD"] = std_val
        summary[f"Mean Fold {metric} CI Low"] = mean_ci_low
        summary[f"Mean Fold {metric} CI High"] = mean_ci_high

        print(
            f"{metric:15s}: {mean_val:.4f} +/- {std_val:.4f} "
            f"| Mean fold CI: "
            f"{mean_ci_low:.4f}-{mean_ci_high:.4f}"
        )

    for metric in ["Balanced Accuracy", "MCC"]:

        summary[f"CV {metric} Mean"] = fold_df[metric].mean()
        summary[f"CV {metric} SD"] = fold_df[metric].std(ddof=1)

    cv_summary_records.append(summary)

    # ========================================================
    # STEP 8: FINAL MODEL AND INDEPENDENT TEST SET
    # ========================================================

    final_imputer = make_preprocessor()

    X_train_imp = final_imputer.fit_transform(X_train)
    X_test_imp = final_imputer.transform(X_test)

    final_model = create_models(y_train)[model_name]

    final_model.fit(X_train_imp, y_train)

    test_pred = np.asarray(
        final_model.predict(X_test_imp)
    ).reshape(-1).astype(int)

    test_prob = final_model.predict_proba(X_test_imp)[:, 1]

    test_metrics = calculate_metrics_with_ci(
        y_test,
        test_pred,
        test_prob,
        n_boot=5000,
        random_state=2026
    )

    test_metrics["Model"] = model_name
    test_records.append(test_metrics.copy())

    confusion_matrices[model_name] = confusion_matrix(
        y_test,
        test_pred,
        labels=[0, 1]
    )

    print(f"\n{model_name} - Independent Test Set")
    print("-" * 75)

    for metric in metrics_to_report:

        print(
            f"{metric:15s}: {test_metrics[metric]:.4f} "
            f"(95% CI: "
            f"{test_metrics[metric + ' CI Low']:.4f}-"
            f"{test_metrics[metric + ' CI High']:.4f})"
        )

    print(
        f"Balanced Accuracy: "
        f"{test_metrics['Balanced Accuracy']:.4f}"
    )

    print(f"MCC: {test_metrics['MCC']:.4f}")

    print("\nConfusion Matrix (rows=true, columns=predicted):")
    print(confusion_matrices[model_name])


# ============================================================
# STEP 9: INDIVIDUAL FOLD RESULTS WITH 95% CIs
# ============================================================

fold_results_df = pd.DataFrame(cv_records)

fold_columns = [
    "Model", "Fold",
    "Accuracy", "Accuracy CI Low", "Accuracy CI High",
    "Precision", "Precision CI Low", "Precision CI High",
    "Sensitivity", "Sensitivity CI Low", "Sensitivity CI High",
    "Specificity", "Specificity CI Low", "Specificity CI High",
    "F1", "F1 CI Low", "F1 CI High",
    "AUC", "AUC CI Low", "AUC CI High",
    "Balanced Accuracy", "MCC",
    "TN", "FP", "FN", "TP"
]

fold_results_df = fold_results_df[fold_columns]

print("\n" + "=" * 100)
print("ALL MODELS: INDIVIDUAL FOLD RESULTS WITH 95% CIs")
print("=" * 100)

display(
    fold_results_df.sort_values(
        ["Model", "Fold"]
    ).round(4)
)


# ============================================================
# STEP 10: CROSS-VALIDATION SUMMARY
# ============================================================

cv_summary_df = pd.DataFrame(cv_summary_records)

print("\n" + "=" * 100)
print("CROSS-VALIDATION MEAN, SD AND MEAN FOLD CIs")
print("=" * 100)

display(cv_summary_df.round(4))


# ============================================================
# STEP 11: INDEPENDENT TEST RESULTS WITH 95% CIs
# ============================================================

test_results_df = pd.DataFrame(
    test_records
).set_index("Model")

test_columns = [
    "Accuracy", "Accuracy CI Low", "Accuracy CI High",
    "Precision", "Precision CI Low", "Precision CI High",
    "Sensitivity", "Sensitivity CI Low", "Sensitivity CI High",
    "Specificity", "Specificity CI Low", "Specificity CI High",
    "F1", "F1 CI Low", "F1 CI High",
    "AUC", "AUC CI Low", "AUC CI High",
    "Balanced Accuracy", "MCC",
    "TN", "FP", "FN", "TP"
]

test_results_df = test_results_df[test_columns]

print("\n" + "=" * 100)
print("INDEPENDENT TEST SET COMPARISON WITH 95% CIs")
print("=" * 100)

display(
    test_results_df.sort_values(
        by="F1",
        ascending=False
    ).round(4)
)


# ============================================================
# STEP 12: INDIVIDUAL MODEL COMPARISON
# ============================================================

print("\n" + "=" * 100)
print("MODEL COMPARISON")
print("=" * 100)

print("\nCross-validation summary:")
display(cv_summary_df.round(4))

print("\nIndependent test results:")
display(test_results_df.round(4))


# ============================================================
# STEP 13: CONFUSION MATRICES
# ============================================================

print("\n" + "=" * 100)
print("INDEPENDENT TEST CONFUSION MATRICES")
print("=" * 100)

for model_name in model_names:

    print(f"\n{model_name}")
    print("Rows = true labels [HC, PD]")
    print("Columns = predicted labels [HC, PD]")
    print(confusion_matrices[model_name])


# ============================================================
# STEP 14: SAVE RESULTS AS CSV
# ============================================================

fold_results_df.to_csv(
    "classification_fold_results_95CI.csv",
    index=False
)

cv_summary_df.to_csv(
    "classification_cv_summary_95CI.csv",
    index=False
)

test_results_df.to_csv(
    "classification_independent_test_results_95CI.csv"
)

print("\nSaved result files:")
print("1. classification_fold_results_95CI.csv")
print("2. classification_cv_summary_95CI.csv")
print("3. classification_independent_test_results_95CI.csv")

X shape: (320, 32)

Class distribution:
PD_Label_Combined
0    131
1    189
Name: count, dtype: int64

Training shape: (288, 32)
Test shape: (32, 32)

Training class distribution:
PD_Label_Combined
0    118
1    170
Name: count, dtype: int64

Independent test class distribution:
PD_Label_Combined
0    13
1    19
Name: count, dtype: int64

=====================================================================================
EVALUATING: LightGBM
=====================================================================================

Fold 01/10
Accuracy       : 0.7241 (95% CI: 0.5428-0.8530)
Precision      : 0.7368 (95% CI: 0.5121-0.8819)
Sensitivity    : 0.8235 (95% CI: 0.5897-0.9381)
Specificity    : 0.5833 (95% CI: 0.3195-0.8067)
F1             : 0.7778 (95% CI: 0.6471-0.8889)
AUC            : 0.8186 (95% CI: 0.6422-0.9510)

Fold 02/10
Accuracy       : 0.7241 (95% CI: 0.5428-0.8530)
Precision      : 0.8000 (95% CI: 0.5481-0.9295)
Sensitivity    : 0.7059 (95% CI: 0.4687-0.8672)
Specificity    : 0.7500 (95% CI: 0.4677-0.9111)
F1             : 0.7500 (95% CI: 0.5712-0.8889)
AUC            : 0.7304 (95% CI: 0.5293-0.9119)

Fold 03/10
Accuracy       : 0.7241 (95% CI: 0.5428-0.8530)
Precision      : 0.7368 (95% CI: 0.5121-0.8819)
Sensitivity    : 0.8235 (95% CI: 0.5897-0.9381)
Specificity    : 0.5833 (95% CI: 0.3195-0.8067)
F1             : 0.7778 (95% CI: 0.6286-0.8889)
AUC            : 0.7451 (95% CI: 0.5392-0.9118)

Fold 04/10
Accuracy       : 0.7241 (95% CI: 0.5428-0.8530)
Precision      : 0.8000 (95% CI: 0.5481-0.9295)
Sensitivity    : 0.7059 (95% CI: 0.4687-0.8672)
Specificity    : 0.7500 (95% CI: 0.4677-0.9111)
F1             : 0.7500 (95% CI: 0.5625-0.8890)
AUC            : 0.8039 (95% CI: 0.6176-0.9363)

Fold 05/10
Accuracy       : 0.6552 (95% CI: 0.4735-0.8006)
Precision      : 0.6842 (95% CI: 0.4601-0.8464)
Sensitivity    : 0.7647 (95% CI: 0.5274-0.9044)
Specificity    : 0.5000 (95% CI: 0.2538-0.7462)
F1             : 0.7222 (95% CI: 0.5625-0.8571)
AUC            : 0.7255 (95% CI: 0.5097-0.9069)

Fold 06/10
Accuracy       : 0.6552 (95% CI: 0.4735-0.8006)
Precision      : 0.7692 (95% CI: 0.4974-0.9182)
Sensitivity    : 0.5882 (95% CI: 0.3601-0.7839)
Specificity    : 0.7500 (95% CI: 0.4677-0.9111)
F1             : 0.6667 (95% CI: 0.4615-0.8387)
AUC            : 0.7108 (95% CI: 0.5049-0.8824)

Fold 07/10
Accuracy       : 0.6897 (95% CI: 0.5077-0.8272)
Precision      : 0.7857 (95% CI: 0.5241-0.9243)
Sensitivity    : 0.6471 (95% CI: 0.4130-0.8269)
Specificity    : 0.7500 (95% CI: 0.4677-0.9111)
F1             : 0.7097 (95% CI: 0.5185-0.8750)
AUC            : 0.6471 (95% CI: 0.4363-0.8578)

Fold 08/10
Accuracy       : 0.7241 (95% CI: 0.5428-0.8530)
Precision      : 0.7647 (95% CI: 0.5274-0.9044)
Sensitivity    : 0.7647 (95% CI: 0.5274-0.9044)
Specificity    : 0.6667 (95% CI: 0.3906-0.8619)
F1             : 0.7647 (95% CI: 0.6111-0.8889)
AUC            : 0.7157 (95% CI: 0.5098-0.9020)

Fold 09/10
Accuracy       : 0.7857 (95% CI: 0.6046-0.8979)
Precision      : 0.8235 (95% CI: 0.5897-0.9381)
Sensitivity    : 0.8235 (95% CI: 0.5897-0.9381)
Specificity    : 0.7273 (95% CI: 0.4344-0.9025)
F1             : 0.8235 (95% CI: 0.6875-0.9412)
AUC            : 0.8182 (95% CI: 0.6471-0.9572)

Fold 10/10
Accuracy       : 0.6429 (95% CI: 0.4583-0.7929)
Precision      : 0.7059 (95% CI: 0.4687-0.8672)
Sensitivity    : 0.7059 (95% CI: 0.4687-0.8672)
Specificity    : 0.5455 (95% CI: 0.2801-0.7873)
F1             : 0.7059 (95% CI: 0.5294-0.8571)
AUC            : 0.6952 (95% CI: 0.4759-0.8930)

LightGBM - 10-Fold CV Summary
---------------------------------------------------------------------------
Accuracy       : 0.7049 +/- 0.0440 | Mean fold CI: 0.5232-0.8384
Precision      : 0.7607 +/- 0.0444 | Mean fold CI: 0.5188-0.9022
Sensitivity    : 0.7353 +/- 0.0796 | Mean fold CI: 0.5003-0.8836
Specificity    : 0.6606 +/- 0.0986 | Mean fold CI: 0.3869-0.8556
F1             : 0.7448 +/- 0.0450 | Mean fold CI: 0.5780-0.8814
AUC            : 0.7410 +/- 0.0566 | Mean fold CI: 0.5412-0.9110

LightGBM - Independent Test Set
---------------------------------------------------------------------------
Accuracy       : 0.6562 (95% CI: 0.4831-0.7959)
Precision      : 0.7857 (95% CI: 0.5241-0.9243)
Sensitivity    : 0.5789 (95% CI: 0.3628-0.7686)
Specificity    : 0.7692 (95% CI: 0.4974-0.9182)
F1             : 0.6667 (95% CI: 0.4667-0.8333)
AUC            : 0.6761 (95% CI: 0.4615-0.8704)
Balanced Accuracy: 0.6741
MCC: 0.3447

Confusion Matrix (rows=true, columns=predicted):
[[10  3]
 [ 8 11]]

=====================================================================================
EVALUATING: Logistic Regression
=====================================================================================

Fold 01/10
Accuracy       : 0.7241 (95% CI: 0.5428-0.8530)
Precision      : 0.8000 (95% CI: 0.5481-0.9295)
Sensitivity    : 0.7059 (95% CI: 0.4687-0.8672)
Specificity    : 0.7500 (95% CI: 0.4677-0.9111)
F1             : 0.7500 (95% CI: 0.5714-0.9032)
AUC            : 0.8137 (95% CI: 0.6275-0.9559)

Fold 02/10
Accuracy       : 0.6207 (95% CI: 0.4400-0.7731)
Precision      : 0.6875 (95% CI: 0.4440-0.8584)
Sensitivity    : 0.6471 (95% CI: 0.4130-0.8269)
Specificity    : 0.5833 (95% CI: 0.3195-0.8067)
F1             : 0.6667 (95% CI: 0.4798-0.8235)
AUC            : 0.7010 (95% CI: 0.4852-0.8725)

Fold 03/10
Accuracy       : 0.6207 (95% CI: 0.4400-0.7731)
Precision      : 0.6875 (95% CI: 0.4440-0.8584)
Sensitivity    : 0.6471 (95% CI: 0.4130-0.8269)
Specificity    : 0.5833 (95% CI: 0.3195-0.8067)
F1             : 0.6667 (95% CI: 0.4667-0.8235)
AUC            : 0.6961 (95% CI: 0.4853-0.8776)

Fold 04/10
Accuracy       : 0.5517 (95% CI: 0.3755-0.7159)
Precision      : 0.6250 (95% CI: 0.3864-0.8152)
Sensitivity    : 0.5882 (95% CI: 0.3601-0.7839)
Specificity    : 0.5000 (95% CI: 0.2538-0.7462)
F1             : 0.6061 (95% CI: 0.4000-0.7568)
AUC            : 0.6912 (95% CI: 0.4853-0.8627)

Fold 05/10
Accuracy       : 0.6552 (95% CI: 0.4735-0.8006)
Precision      : 0.6842 (95% CI: 0.4601-0.8464)
Sensitivity    : 0.7647 (95% CI: 0.5274-0.9044)
Specificity    : 0.5000 (95% CI: 0.2538-0.7462)
F1             : 0.7222 (95% CI: 0.5625-0.8571)
AUC            : 0.5833 (95% CI: 0.3480-0.8137)

Fold 06/10
Accuracy       : 0.5862 (95% CI: 0.4074-0.7449)
Precision      : 0.6471 (95% CI: 0.4130-0.8269)
Sensitivity    : 0.6471 (95% CI: 0.4130-0.8269)
Specificity    : 0.5000 (95% CI: 0.2538-0.7462)
F1             : 0.6471 (95% CI: 0.4614-0.8000)
AUC            : 0.6275 (95% CI: 0.4020-0.8284)

Fold 07/10
Accuracy       : 0.6552 (95% CI: 0.4735-0.8006)
Precision      : 0.7692 (95% CI: 0.4974-0.9182)
Sensitivity    : 0.5882 (95% CI: 0.3601-0.7839)
Specificity    : 0.7500 (95% CI: 0.4677-0.9111)
F1             : 0.6667 (95% CI: 0.4665-0.8387)
AUC            : 0.6471 (95% CI: 0.4314-0.8480)

Fold 08/10
Accuracy       : 0.5862 (95% CI: 0.4074-0.7449)
Precision      : 0.6923 (95% CI: 0.4237-0.8732)
Sensitivity    : 0.5294 (95% CI: 0.3096-0.7383)
Specificity    : 0.6667 (95% CI: 0.3906-0.8619)
F1             : 0.6000 (95% CI: 0.3704-0.7742)
AUC            : 0.6176 (95% CI: 0.3971-0.8186)

Fold 09/10
Accuracy       : 0.7143 (95% CI: 0.5294-0.8475)
Precision      : 0.7647 (95% CI: 0.5274-0.9044)
Sensitivity    : 0.7647 (95% CI: 0.5274-0.9044)
Specificity    : 0.6364 (95% CI: 0.3538-0.8483)
F1             : 0.7647 (95% CI: 0.6061-0.8947)
AUC            : 0.7914 (95% CI: 0.5881-0.9519)

Fold 10/10
Accuracy       : 0.5714 (95% CI: 0.3907-0.7349)
Precision      : 0.6923 (95% CI: 0.4237-0.8732)
Sensitivity    : 0.5294 (95% CI: 0.3096-0.7383)
Specificity    : 0.6364 (95% CI: 0.3538-0.8483)
F1             : 0.6000 (95% CI: 0.3704-0.7879)
AUC            : 0.5936 (95% CI: 0.3690-0.8021)

Logistic Regression - 10-Fold CV Summary
---------------------------------------------------------------------------
Accuracy       : 0.6286 +/- 0.0585 | Mean fold CI: 0.4480-0.7788
Precision      : 0.7050 +/- 0.0556 | Mean fold CI: 0.4568-0.8704
Sensitivity    : 0.6412 +/- 0.0852 | Mean fold CI: 0.4102-0.8201
Specificity    : 0.6106 +/- 0.0952 | Mean fold CI: 0.3434-0.8233
F1             : 0.6690 +/- 0.0601 | Mean fold CI: 0.4755-0.8260
AUC            : 0.6762 +/- 0.0786 | Mean fold CI: 0.4619-0.8632

Logistic Regression - Independent Test Set
---------------------------------------------------------------------------
Accuracy       : 0.5625 (95% CI: 0.3933-0.7183)
Precision      : 0.6316 (95% CI: 0.4104-0.8085)
Sensitivity    : 0.6316 (95% CI: 0.4104-0.8085)
Specificity    : 0.4615 (95% CI: 0.2321-0.7086)
F1             : 0.6316 (95% CI: 0.4570-0.7778)
AUC            : 0.5992 (95% CI: 0.3846-0.8057)
Balanced Accuracy: 0.5466
MCC: 0.0931

Confusion Matrix (rows=true, columns=predicted):
[[ 6  7]
 [ 7 12]]

=====================================================================================
EVALUATING: SVM
=====================================================================================

Fold 01/10
Accuracy       : 0.7586 (95% CI: 0.5789-0.8778)
Precision      : 0.9167 (95% CI: 0.6461-0.9851)
Sensitivity    : 0.6471 (95% CI: 0.4130-0.8269)
Specificity    : 0.9167 (95% CI: 0.6461-0.9851)
F1             : 0.7586 (95% CI: 0.5600-0.9091)
AUC            : 0.8162 (95% CI: 0.6225-0.9657)

Fold 02/10
Accuracy       : 0.7241 (95% CI: 0.5428-0.8530)
Precision      : 0.8000 (95% CI: 0.5481-0.9295)
Sensitivity    : 0.7059 (95% CI: 0.4687-0.8672)
Specificity    : 0.7500 (95% CI: 0.4677-0.9111)
F1             : 0.7500 (95% CI: 0.5714-0.9032)
AUC            : 0.7696 (95% CI: 0.5784-0.9216)

Fold 03/10
Accuracy       : 0.5517 (95% CI: 0.3755-0.7159)
Precision      : 0.6429 (95% CI: 0.3876-0.8366)
Sensitivity    : 0.5294 (95% CI: 0.3096-0.7383)
Specificity    : 0.5833 (95% CI: 0.3195-0.8067)
F1             : 0.5806 (95% CI: 0.3571-0.7502)
AUC            : 0.6961 (95% CI: 0.4804-0.8676)

Fold 04/10
Accuracy       : 0.7241 (95% CI: 0.5428-0.8530)
Precision      : 0.8000 (95% CI: 0.5481-0.9295)
Sensitivity    : 0.7059 (95% CI: 0.4687-0.8672)
Specificity    : 0.7500 (95% CI: 0.4677-0.9111)
F1             : 0.7500 (95% CI: 0.5712-0.8889)
AUC            : 0.8088 (95% CI: 0.6225-0.9559)

Fold 05/10
Accuracy       : 0.6897 (95% CI: 0.5077-0.8272)
Precision      : 0.6818 (95% CI: 0.4732-0.8364)
Sensitivity    : 0.8824 (95% CI: 0.6566-0.9671)
Specificity    : 0.4167 (95% CI: 0.1933-0.6805)
F1             : 0.7692 (95% CI: 0.6500-0.8718)
AUC            : 0.6667 (95% CI: 0.4559-0.8578)

Fold 06/10
Accuracy       : 0.6552 (95% CI: 0.4735-0.8006)
Precision      : 0.7333 (95% CI: 0.4805-0.8910)
Sensitivity    : 0.6471 (95% CI: 0.4130-0.8269)
Specificity    : 0.6667 (95% CI: 0.3906-0.8619)
F1             : 0.6875 (95% CI: 0.5000-0.8485)
AUC            : 0.6814 (95% CI: 0.4608-0.8580)

Fold 07/10
Accuracy       : 0.6552 (95% CI: 0.4735-0.8006)
Precision      : 0.8182 (95% CI: 0.5230-0.9486)
Sensitivity    : 0.5294 (95% CI: 0.3096-0.7383)
Specificity    : 0.8333 (95% CI: 0.5520-0.9530)
F1             : 0.6429 (95% CI: 0.4167-0.8387)
AUC            : 0.6863 (95% CI: 0.4853-0.8725)

Fold 08/10
Accuracy       : 0.6207 (95% CI: 0.4400-0.7731)
Precision      : 0.7500 (95% CI: 0.4677-0.9111)
Sensitivity    : 0.5294 (95% CI: 0.3096-0.7383)
Specificity    : 0.7500 (95% CI: 0.4677-0.9111)
F1             : 0.6207 (95% CI: 0.3846-0.8000)
AUC            : 0.6961 (95% CI: 0.4803-0.8678)

Fold 09/10
Accuracy       : 0.7500 (95% CI: 0.5664-0.8732)
Precision      : 0.8125 (95% CI: 0.5699-0.9341)
Sensitivity    : 0.7647 (95% CI: 0.5274-0.9044)
Specificity    : 0.7273 (95% CI: 0.4344-0.9025)
F1             : 0.7879 (95% CI: 0.6249-0.9143)
AUC            : 0.8663 (95% CI: 0.7059-0.9786)

Fold 10/10
Accuracy       : 0.5357 (95% CI: 0.3581-0.7047)
Precision      : 0.6429 (95% CI: 0.3876-0.8366)
Sensitivity    : 0.5294 (95% CI: 0.3096-0.7383)
Specificity    : 0.5455 (95% CI: 0.2801-0.7873)
F1             : 0.5806 (95% CI: 0.3704-0.7647)
AUC            : 0.5615 (95% CI: 0.3209-0.7861)

SVM - 10-Fold CV Summary
---------------------------------------------------------------------------
Accuracy       : 0.6665 +/- 0.0784 | Mean fold CI: 0.4859-0.8079
Precision      : 0.7598 +/- 0.0871 | Mean fold CI: 0.5032-0.9038
Sensitivity    : 0.6471 +/- 0.1209 | Mean fold CI: 0.4186-0.8213
Specificity    : 0.6939 +/- 0.1459 | Mean fold CI: 0.4219-0.8710
F1             : 0.6928 +/- 0.0807 | Mean fold CI: 0.5006-0.8489
AUC            : 0.7249 +/- 0.0898 | Mean fold CI: 0.5213-0.8932

SVM - Independent Test Set
---------------------------------------------------------------------------
Accuracy       : 0.6562 (95% CI: 0.4831-0.7959)
Precision      : 0.7500 (95% CI: 0.5050-0.8982)
Sensitivity    : 0.6316 (95% CI: 0.4104-0.8085)
Specificity    : 0.6923 (95% CI: 0.4237-0.8732)
F1             : 0.6857 (95% CI: 0.5000-0.8421)
AUC            : 0.6397 (95% CI: 0.4413-0.8340)
Balanced Accuracy: 0.6619
MCC: 0.3181

Confusion Matrix (rows=true, columns=predicted):
[[ 9  4]
 [ 7 12]]

=====================================================================================
EVALUATING: Decision Tree
=====================================================================================

Fold 01/10
Accuracy       : 0.6552 (95% CI: 0.4735-0.8006)
Precision      : 0.8182 (95% CI: 0.5230-0.9486)
Sensitivity    : 0.5294 (95% CI: 0.3096-0.7383)
Specificity    : 0.8333 (95% CI: 0.5520-0.9530)
F1             : 0.6429 (95% CI: 0.4167-0.8276)
AUC            : 0.7500 (95% CI: 0.5466-0.9020)

Fold 02/10
Accuracy       : 0.5517 (95% CI: 0.3755-0.7159)
Precision      : 0.7500 (95% CI: 0.4093-0.9285)
Sensitivity    : 0.3529 (95% CI: 0.1731-0.5870)
Specificity    : 0.8333 (95% CI: 0.5520-0.9530)
F1             : 0.4800 (95% CI: 0.2000-0.6897)
AUC            : 0.7132 (95% CI: 0.5074-0.8848)

Fold 03/10
Accuracy       : 0.5517 (95% CI: 0.3755-0.7159)
Precision      : 0.6250 (95% CI: 0.3864-0.8152)
Sensitivity    : 0.5882 (95% CI: 0.3601-0.7839)
Specificity    : 0.5000 (95% CI: 0.2538-0.7462)
F1             : 0.6061 (95% CI: 0.4000-0.7647)
AUC            : 0.6887 (95% CI: 0.4828-0.8653)

Fold 04/10
Accuracy       : 0.7241 (95% CI: 0.5428-0.8530)
Precision      : 0.9091 (95% CI: 0.6226-0.9838)
Sensitivity    : 0.5882 (95% CI: 0.3601-0.7839)
Specificity    : 0.9167 (95% CI: 0.6461-0.9851)
F1             : 0.7143 (95% CI: 0.5000-0.8752)
AUC            : 0.6936 (95% CI: 0.4853-0.8824)

Fold 05/10
Accuracy       : 0.5862 (95% CI: 0.4074-0.7449)
Precision      : 0.6316 (95% CI: 0.4104-0.8085)
Sensitivity    : 0.7059 (95% CI: 0.4687-0.8672)
Specificity    : 0.4167 (95% CI: 0.1933-0.6805)
F1             : 0.6667 (95% CI: 0.5000-0.8108)
AUC            : 0.6152 (95% CI: 0.3995-0.8088)

Fold 06/10
Accuracy       : 0.6552 (95% CI: 0.4735-0.8006)
Precision      : 0.7059 (95% CI: 0.4687-0.8672)
Sensitivity    : 0.7059 (95% CI: 0.4687-0.8672)
Specificity    : 0.5833 (95% CI: 0.3195-0.8067)
F1             : 0.7059 (95% CI: 0.5333-0.8571)
AUC            : 0.6618 (95% CI: 0.4583-0.8431)

Fold 07/10
Accuracy       : 0.5172 (95% CI: 0.3443-0.6861)
Precision      : 0.6667 (95% CI: 0.3542-0.8794)
Sensitivity    : 0.3529 (95% CI: 0.1731-0.5870)
Specificity    : 0.7500 (95% CI: 0.4677-0.9111)
F1             : 0.4615 (95% CI: 0.2219-0.6667)
AUC            : 0.5858 (95% CI: 0.3774-0.7868)

Fold 08/10
Accuracy       : 0.5862 (95% CI: 0.4074-0.7449)
Precision      : 0.6667 (95% CI: 0.4171-0.8482)
Sensitivity    : 0.5882 (95% CI: 0.3601-0.7839)
Specificity    : 0.5833 (95% CI: 0.3195-0.8067)
F1             : 0.6250 (95% CI: 0.4138-0.7879)
AUC            : 0.6005 (95% CI: 0.3922-0.7917)

Fold 09/10
Accuracy       : 0.6071 (95% CI: 0.4241-0.7643)
Precision      : 0.7500 (95% CI: 0.4677-0.9111)
Sensitivity    : 0.5294 (95% CI: 0.3096-0.7383)
Specificity    : 0.7273 (95% CI: 0.4344-0.9025)
F1             : 0.6207 (95% CI: 0.3846-0.8000)
AUC            : 0.5882 (95% CI: 0.3717-0.8075)

Fold 10/10
Accuracy       : 0.5000 (95% CI: 0.3263-0.6737)
Precision      : 0.5789 (95% CI: 0.3628-0.7686)
Sensitivity    : 0.6471 (95% CI: 0.4130-0.8269)
Specificity    : 0.2727 (95% CI: 0.0975-0.5656)
F1             : 0.6111 (95% CI: 0.4375-0.7502)
AUC            : 0.5936 (95% CI: 0.3769-0.7968)

Decision Tree - 10-Fold CV Summary
---------------------------------------------------------------------------
Accuracy       : 0.5935 +/- 0.0691 | Mean fold CI: 0.4150-0.7500
Precision      : 0.7102 +/- 0.0994 | Mean fold CI: 0.4422-0.8759
Sensitivity    : 0.5588 +/- 0.1248 | Mean fold CI: 0.3396-0.7564
Specificity    : 0.6417 +/- 0.2060 | Mean fold CI: 0.3836-0.8311
F1             : 0.6134 +/- 0.0840 | Mean fold CI: 0.4008-0.7830
AUC            : 0.6491 +/- 0.0599 | Mean fold CI: 0.4398-0.8369

Decision Tree - Independent Test Set
---------------------------------------------------------------------------
Accuracy       : 0.5938 (95% CI: 0.4226-0.7448)
Precision      : 0.6667 (95% CI: 0.4375-0.8372)
Sensitivity    : 0.6316 (95% CI: 0.4104-0.8085)
Specificity    : 0.5385 (95% CI: 0.2914-0.7679)
F1             : 0.6486 (95% CI: 0.4706-0.7909)
AUC            : 0.5931 (95% CI: 0.3927-0.7814)
Balanced Accuracy: 0.5850
MCC: 0.1683

Confusion Matrix (rows=true, columns=predicted):
[[ 7  6]
 [ 7 12]]

=====================================================================================
EVALUATING: Gaussian Naive Bayes
=====================================================================================

Fold 01/10
Accuracy       : 0.6552 (95% CI: 0.4735-0.8006)
Precision      : 0.7692 (95% CI: 0.4974-0.9182)
Sensitivity    : 0.5882 (95% CI: 0.3601-0.7839)
Specificity    : 0.7500 (95% CI: 0.4677-0.9111)
F1             : 0.6667 (95% CI: 0.4516-0.8387)
AUC            : 0.7549 (95% CI: 0.5637-0.9167)

Fold 02/10
Accuracy       : 0.7241 (95% CI: 0.5428-0.8530)
Precision      : 0.8000 (95% CI: 0.5481-0.9295)
Sensitivity    : 0.7059 (95% CI: 0.4687-0.8672)
Specificity    : 0.7500 (95% CI: 0.4677-0.9111)
F1             : 0.7500 (95% CI: 0.5625-0.8889)
AUC            : 0.7059 (95% CI: 0.4950-0.8922)

Fold 03/10
Accuracy       : 0.5517 (95% CI: 0.3755-0.7159)
Precision      : 0.6250 (95% CI: 0.3864-0.8152)
Sensitivity    : 0.5882 (95% CI: 0.3601-0.7839)
Specificity    : 0.5000 (95% CI: 0.2538-0.7462)
F1             : 0.6061 (95% CI: 0.4118-0.7647)
AUC            : 0.5980 (95% CI: 0.3775-0.7892)

Fold 04/10
Accuracy       : 0.6207 (95% CI: 0.4400-0.7731)
Precision      : 0.7143 (95% CI: 0.4535-0.8828)
Sensitivity    : 0.5882 (95% CI: 0.3601-0.7839)
Specificity    : 0.6667 (95% CI: 0.3906-0.8619)
F1             : 0.6452 (95% CI: 0.4444-0.8125)
AUC            : 0.6765 (95% CI: 0.4558-0.8627)

Fold 05/10
Accuracy       : 0.5517 (95% CI: 0.3755-0.7159)
Precision      : 0.6000 (95% CI: 0.3866-0.7812)
Sensitivity    : 0.7059 (95% CI: 0.4687-0.8672)
Specificity    : 0.3333 (95% CI: 0.1381-0.6094)
F1             : 0.6486 (95% CI: 0.4864-0.7895)
AUC            : 0.5245 (95% CI: 0.2941-0.7500)

Fold 06/10
Accuracy       : 0.6552 (95% CI: 0.4735-0.8006)
Precision      : 0.6842 (95% CI: 0.4601-0.8464)
Sensitivity    : 0.7647 (95% CI: 0.5274-0.9044)
Specificity    : 0.5000 (95% CI: 0.2538-0.7462)
F1             : 0.7222 (95% CI: 0.5712-0.8500)
AUC            : 0.6225 (95% CI: 0.3971-0.8137)

Fold 07/10
Accuracy       : 0.5862 (95% CI: 0.4074-0.7449)
Precision      : 0.6471 (95% CI: 0.4130-0.8269)
Sensitivity    : 0.6471 (95% CI: 0.4130-0.8269)
Specificity    : 0.5000 (95% CI: 0.2538-0.7462)
F1             : 0.6471 (95% CI: 0.4667-0.8000)
AUC            : 0.6324 (95% CI: 0.4167-0.8431)

Fold 08/10
Accuracy       : 0.6207 (95% CI: 0.4400-0.7731)
Precision      : 0.7500 (95% CI: 0.4677-0.9111)
Sensitivity    : 0.5294 (95% CI: 0.3096-0.7383)
Specificity    : 0.7500 (95% CI: 0.4677-0.9111)
F1             : 0.6207 (95% CI: 0.3846-0.8000)
AUC            : 0.5637 (95% CI: 0.3382-0.7696)

Fold 09/10
Accuracy       : 0.7500 (95% CI: 0.5664-0.8732)
Precision      : 0.8125 (95% CI: 0.5699-0.9341)
Sensitivity    : 0.7647 (95% CI: 0.5274-0.9044)
Specificity    : 0.7273 (95% CI: 0.4344-0.9025)

,Model,Fold,Accuracy,Accuracy CI Low,Accuracy CI High,Precision,Precision CI Low,Precision CI High,Sensitivity,Sensitivity CI Low,...,F1 CI High,AUC,AUC CI Low,AUC CI High,Balanced Accuracy,MCC,TN,FP,FN,TP
30,Decision Tree,1,0.6552,0.4735,0.8006,0.8182,0.5230,0.9486,0.5294,0.3096,...,0.8276,0.7500,0.5466,0.9020,0.6814,0.3682,10,2,8,9
31,Decision Tree,2,0.5517,0.3755,0.7159,0.7500,0.4093,0.9285,0.3529,0.1731,...,0.6897,0.7132,0.5074,0.8848,0.5931,0.2053,10,2,11,6
32,Decision Tree,3,0.5517,0.3755,0.7159,0.6250,0.3864,0.8152,0.5882,0.3601,...,0.7647,0.6887,0.4828,0.8653,0.5441,0.0874,6,6,7,10
33,Decision Tree,4,0.7241,0.5428,0.8530,0.9091,0.6226,0.9838,0.5882,0.3601,...,0.8752,0.6936,0.4853,0.8824,0.7525,0.5125,11,1,7,10
34,Decision Tree,5,0.5862,0.4074,0.7449,0.6316,0.4104,0.8085,0.7059,0.4687,...,0.8108,0.6152,0.3995,0.8088,0.5613,0.1270,5,7,5,12
35,Decision Tree,6,0.6552,0.4735,0.8006,0.7059,0.4687,0.8672,0.7059,0.4687,...,0.8571,0.6618,0.4583,0.8431,0.6446,0.2892,7,5,5,12
36,Decision Tree,7,0.5172,0.3443,0.6861,0.6667,0.3542,0.8794,0.3529,0.1731,...,0.6667,0.5858,0.3774,0.7868,0.5515,0.1096,9,3,11,6
37,Decision Tree,8,0.5862,0.4074,0.7449,0.6667,0.4171,0.8482,0.5882,0.3601,...,0.7879,0.6005,0.3922,0.7917,0.5858,0.1691,7,5,7,10
38,Decision Tree,9,0.6071,0.4241,0.7643,0.7500,0.4677,0.9111,0.5294,0.3096,...,0.8000,0.5882,0.3717,0.8075,0.6283,0.2533,8,3,8,9
39,Decision Tree,10,0.5000,0.3263,0.6737,0.5789,0.3628,0.7686,0.6471,0.4130,...,0.7502,0.5936,0.3769,0.7968,0.4599,-0.0839,3,8,6,11
40,Gaussian Naive Bayes,1,0.6552,0.4735,0.8006,0.7692,0.4974,0.9182,0.5882,0.3601,...,0.8387,0.7549,0.5637,0.9167,0.6691,0.3350,9,3,7,10
41,Gaussian Naive Bayes,2,0.7241,0.5428,0.8530,0.8000,0.5481,0.9295,0.7059,0.4687,...,0.8889,0.7059,0.4950,0.8922,0.7279,0.4493,9,3,5,12
42,Gaussian Naive Bayes,3,0.5517,0.3755,0.7159,0.6250,0.3864,0.8152,0.5882,0.3601,...,0.7647,0.5980,0.3775,0.7892,0.5441,0.0874,6,6,7,10
43,Gaussian Naive Bayes,4,0.6207,0.4400,0.7731,0.7143,0.4535,0.8828,0.5882,0.3601,...,0.8125,0.6765,0.4558,0.8627,0.6275,0.2512,8,4,7,10
44,Gaussian Naive Bayes,5,0.5517,0.3755,0.7159,0.6000,0.3866,0.7812,0.7059,0.4687,...,0.7895,0.5245,0.2941,0.7500,0.5196,0.0417,4,8,5,12
45,Gaussian Naive Bayes,6,0.6552,0.4735,0.8006,0.6842,0.4601,0.8464,0.7647,0.5274,...,0.8500,0.6225,0.3971,0.8137,0.6324,0.2743,6,6,4,13
46,Gaussian Naive Bayes,7,0.5862,0.4074,0.7449,0.6471,0.4130,0.8269,0.6471,0.4130,...,0.8000,0.6324,0.4167,0.8431,0.5735,0.1471,6,6,6,11
47,Gaussian Naive Bayes,8,0.6207,0.4400,0.7731,0.7500,0.4677,0.9111,0.5294,0.3096,...,0.8000,0.5637,0.3382,0.7696,0.6397,0.2794,9,3,8,9
48,Gaussian Naive Bayes,9,0.7500,0.5664,0.8732,0.8125,0.5699,0.9341,0.7647,0.5274,...,0.9189,0.7754,0.5722,0.9465,0.7460,0.4855,8,3,4,13
49,Gaussian Naive Bayes,10,0.4643,0.2953,0.6419,0.5625,0.3318,0.7690,0.5294,0.3096,...,0.7222,0.4973,0.2727,0.7219,0.4465,-0.1056,4,7,8,9
50,LDA,1,0.7241,0.5428,0.8530,0.7647,0.5274,0.9044,0.7647,0.5274,...,0.8947,0.8480,0.6912,0.9608,0.7157,0.4314,8,4,4,13
51,LDA,2,0.6207,0.4400,0.7731,0.6500,0.4329,0.8188,0.7647,0.5274,...,0.8293,0.7157,0.5049,0.8824,0.5907,0.1931,5,7,4,13
52,LDA,3,0.6897,0.5077,0.8272,0.7000,0.4810,0.8545,0.8235,0.5897,...,0.8824,0.7157,0.5098,0.8873,0.6618,0.3444,6,6,3,14
53,LDA,4,0.6207,0.4400,0.7731,0.6667,0.4375,0.8372,0.7059,0.4687,...,0.8235,0.7010,0.4902,0.8725,0.6029,0.2090,6,6,5,12
54,LDA,5,0.7586,0.5789,0.8778,0.7273,0.5185,0.8685,0.9412,0.7302,...,0.9189,0.6127,0.3824,0.8335,0.7206,0.5078,6,6,1,16
55,LDA,6,0.5517,0.3755,0.7159,0.5909,0.3873,0.7674,0.7647,0.5274,...,0.7895,0.6520,0.4314,0.8431,0.5074,0.0169,3,9,4,13
56,LDA,7,0.5517,0.3755,0.7159,0.6111,0.3862,0.7969,0.6471,0.4130,...,0.7778,0.6373,0.4265,0.8333,0.5319,0.0647,5,7,6,11
57,LDA,8,0.5517,0.3755,0.7159,0.6111,0.3862,0.7969,0.6471,0.4130,...,0.7692,0.6078,0.3971,0.8137,0.5319,0.0647,5,7,6,11
58,LDA,9,0.7857,0.6046,0.8979,0.7895,0.5667,0.9149,0.8824,0.6566,...,0.9413,0.7754,0.5721,0.9519,0.7594,0.5424,7,4,2,15
59,LDA,10,0.5357,0.3581,0.7047,0.6429,0.3876,0.8366,0.5294,0.3096,...,0.7647,0.5936,0.3636,0.8021,0.5374,0.0731,6,5,8,9
0,LightGBM,1,0.7241,0.5428,0.8530,0.7368,0.5121,0.8819,0.8235,0.5897,...,0.8889,0.8186,0.6422,0.9510,0.7034,0.4216,7,5,3,14
1,LightGBM,2,0.7241,0.5428,0.8530,0.8000,0.5481,0.9295,0.7059,0.4687,...,0.8889,0.7304,0.5293,0.9119,0.7279,0.4493,9,3,5,12
2,LightGBM,3,0.7241,0.5428,0.8530,0.7368,0.5121,0.8819,0.8235,0.5897,...,0.8889,0.7451,0.5392,0.9118,0.7034,0.4216,7,5,3,14
3,LightGBM,4,0.7241,0.5428,0.8530,0.8000,0.5481,0.9295,0.7059,0.4687,...,0.8890,0.8039,0.6176,0.9363,0.7279,0.4493,9,3,5,12
4,LightGBM,5,0.6552,0.4735,0.8006,0.6842,0.4601,0.8464,0.7647,0.5274,...,0.8571,0.7255,0.5097,0.9069,0.6324,0.2743,6,6,4,13
5,LightGBM,6,0.6552,0.4735,0.8006,0.7692,0.4974,0.9182,0.5882,0.3601,...,0.8387,0.7108,0.5049,0.8824,0.6691,0.3350,9,3,7,10
6,LightGBM,7,0.6897,0.5077,0.8272,0.7857,0.5241,0.9243,0.6471,0.4130,...,0.8750,0.6471,0.4363,0.8578,0.6985,0.3913,9,3,6,11
7,LightGBM,8,0.7241,0.5428,0.8530,0.7647,0.5274,0.9044,0.7647,0.5274,...,0.8889,0.7157,0.5098,0.9020,0.7157,0.4314,8,4,4,13
8,LightGBM,9,0.7857,0.6046,0.8979,0.8235,0.5897,0.9381,0.8235,0.5897,...,0.9412,0.8182,0.6471,0.9572,0.7754,0.5508,8,3,3,14
9,LightGBM,10,0.6429,0.4583,0.7929,0.7059,0.4687,0.8672,0.7059,0.4687,...,0.8571,0.6952,0.4759,0.8930,0.6257,0.2513,6,5,5,12
10,Logistic Regression,1,0.7241,0.5428,0.8530,0.8000,0.5481,0.9295,0.7059,0.4687,...,0.9032,0.8137,0.6275,0.9559,0.7279,0.4493,9,3,5,12
11,Logistic Regression,2,0.6207,0.4400,0.7731,0.6875,0.4440,0.8584,0.6471,0.4130,...,0.8235,0.7010,0.4852,0.8725,0.6152,0.2282,7,5,6,11
12,Logistic Regression,3,0.6207,0.4400,0.7731,0.6875,0.4440,0.8584,0.6471,0.4130,...,0.8235,0.6961,0.4853,0.8776,0.6152,0.2282,7,5,6,11
13,Logistic Regression,4,0.5517,0.3755,0.7159,0.6250,0.3864,0.8152,0.5882,0.3601,...,0.7568,0.6912,0.4853,0.8627,0.5441,0.0874,6,6,7,10
14,Logistic Regression,5,0.6552,0.4735,0.8006,0.6842,0.4601,0.8464,0.7647,0.5274,...,0.8571,0.5833,0.3480,0.8137,0.6324,0.2743,6,6,4,13
15,Logistic Regression,6,0.5862,0.4074,0.7449,0.6471,0.4130,0.8269,0.6471,0.4130,...,0.8000,0.6275,0.4020,0.8284,0.5735,0.1471,6,6,6,11
16,Logistic Regression,7,0.6552,0.4735,0.8006,0.7692,0.4974,0.9182,0.5882,0.3601,...,0.8387,0.6471,0.4314,0.8480,0.6691,0.3350,9,3,7,10
17,Logistic Regression,8,0.5862,0.4074,0.7449,0.6923,0.4237,0.8732,0.5294,0.3096,...,0.7742,0.6176,0.3971,0.8186,0.5980,0.1942,8,4,8,9
18,Logistic Regression,9,0.7143,0.5294,0.8475,0.7647,0.5274,0.9044,0.7647,0.5274,...,0.8947,0.7914,0.5881,0.9519,0.7005,0.4011,7,4,4,13
19,Logistic Regression,10,0.5714,0.3907,0.7349,0.6923,0.4237,0.8732,0.5294,0.3096,...,0.7879,0.5936,0.3690,0.8021,0.5829,0.1623,7,4,8,9
20,SVM,1,0.7586,0.5789,0.8778,0.9167,0.6461,0.9851,0.6471,0.4130,...,0.9091,0.8162,0.6225,0.9657,0.7819,0.5637,11,1,6,11
21,SVM,2,0.7241,0.5428,0.8530,0.8000,0.5481,0.9295,0.7059,0.4687,...,0.9032,0.7696,0.5784,0.9216,0.7279,0.4493,9,3,5,12
22,SVM,3,0.5517,0.3755,0.7159,0.6429,0.3876,0.8366,0.5294,0.3096,...,0.7502,0.6961,0.4804,0.8676,0.5564,0.1111,7,5,8,9
23,SVM,4,0.7241,0.5428,0.8530,0.8000,0.5481,0.9295,0.7059,0.4687,...,0.8889,0.8088,0.6225,0.9559,0.7279,0.4493,9,3,5,12
24,SVM,5,0.6897,0.5077,0.8272,0.6818,0.4732,0.8364,0.8824,0.6566,...,0.8718,0.6667,0.4559,0.8578,0.6495,0.3442,5,7,2,15
25,SVM,6,0.6552,0.4735,0.8006,0.7333,0.4805,0.8910,0.6471,0.4130,...,0.8485,0.6814,0.4608,0.8580,0.6569,0.3092,8,4,6,11
26,SVM,7,0.6552,0.4735,0.8006,0.8182,0.5230,0.9486,0.5294,0.3096,...,0.8387,0.6863,0.4853,0.8725,0.6814,0.3682,10,2,8,9
27,SVM,8,0.6207,0.4400,0.7731,0.7500,0.4677,0.9111,0.5294,0.3096,...,0.8000,0.6961,0.4803,0.8678,0.6397,0.2794,9,3,8,9
28,SVM,9,0.7500,0.5664,0.8732,0.8125,0.5699,0.9341,0.7647,0.5274,...,0.9143,0.8663,0.7059,0.9786,0.7460,0.4855,8,3,4,13
29,SVM,10,0.5357,0.3581,0.7047,0.6429,0.3876,0.8366,0.5294,0.3096,...,0.7647,0.5615,0.3209,0.7861,0.5374,0.0731,6,5,8,9

====================================================================================================
CROSS-VALIDATION MEAN, SD AND MEAN FOLD CIs
====================================================================================================

,Model,CV Accuracy Mean,CV Accuracy SD,Mean Fold Accuracy CI Low,Mean Fold Accuracy CI High,CV Precision Mean,CV Precision SD,Mean Fold Precision CI Low,Mean Fold Precision CI High,CV Sensitivity Mean,...,Mean Fold F1 CI Low,Mean Fold F1 CI High,CV AUC Mean,CV AUC SD,Mean Fold AUC CI Low,Mean Fold AUC CI High,CV Balanced Accuracy Mean,CV Balanced Accuracy SD,CV MCC Mean,CV MCC SD
0,LightGBM,0.7049,0.0440,0.5232,0.8384,0.7607,0.0444,0.5188,0.9022,0.7353,...,0.5780,0.8814,0.7410,0.0566,0.5412,0.9110,0.6980,0.0454,0.3976,0.0892
1,Logistic Regression,0.6286,0.0585,0.4480,0.7788,0.7050,0.0556,0.4568,0.8704,0.6412,...,0.4755,0.8260,0.6762,0.0786,0.4619,0.8632,0.6259,0.0579,0.2507,0.1151
2,SVM,0.6665,0.0784,0.4859,0.8079,0.7598,0.0871,0.5032,0.9038,0.6471,...,0.5006,0.8489,0.7249,0.0898,0.5213,0.8932,0.6705,0.0797,0.3433,0.1578
3,Decision Tree,0.5935,0.0691,0.4150,0.7500,0.7102,0.0994,0.4422,0.8759,0.5588,...,0.4008,0.7830,0.6491,0.0599,0.4398,0.8369,0.6002,0.0813,0.2038,0.1648
4,Gaussian Naive Bayes,0.6180,0.0849,0.4390,0.7692,0.6965,0.0867,0.4515,0.8614,0.6412,...,0.4733,0.8185,0.6351,0.0935,0.4183,0.8306,0.6126,0.0931,0.2245,0.1839
5,LDA,0.6390,0.0942,0.4599,0.7854,0.6754,0.0679,0.4511,0.8396,0.7471,...,0.5482,0.8391,0.6859,0.0815,0.4769,0.8681,0.6160,0.0922,0.2447,0.1980

====================================================================================================
INDEPENDENT TEST SET COMPARISON WITH 95% CIs
====================================================================================================

,Accuracy,Accuracy CI Low,Accuracy CI High,Precision,Precision CI Low,Precision CI High,Sensitivity,Sensitivity CI Low,Sensitivity CI High,Specificity,...,F1 CI High,AUC,AUC CI Low,AUC CI High,Balanced Accuracy,MCC,TN,FP,FN,TP
Model,,,,,,,,,,,,,,,,,,,,,
Gaussian Naive Bayes,0.6875,0.5143,0.8205,0.8000,0.5481,0.9295,0.6316,0.4104,0.8085,0.7692,...,0.8571,0.7490,0.5628,0.9028,0.7004,0.3945,10,3,7,12
SVM,0.6562,0.4831,0.7959,0.7500,0.5050,0.8982,0.6316,0.4104,0.8085,0.6923,...,0.8421,0.6397,0.4413,0.8340,0.6619,0.3181,9,4,7,12
LightGBM,0.6562,0.4831,0.7959,0.7857,0.5241,0.9243,0.5789,0.3628,0.7686,0.7692,...,0.8333,0.6761,0.4615,0.8704,0.6741,0.3447,10,3,8,11
Decision Tree,0.5938,0.4226,0.7448,0.6667,0.4375,0.8372,0.6316,0.4104,0.8085,0.5385,...,0.7909,0.5931,0.3927,0.7814,0.5850,0.1683,7,6,7,12
Logistic Regression,0.5625,0.3933,0.7183,0.6316,0.4104,0.8085,0.6316,0.4104,0.8085,0.4615,...,0.7778,0.5992,0.3846,0.8057,0.5466,0.0931,6,7,7,12
LDA,0.5625,0.3933,0.7183,0.6316,0.4104,0.8085,0.6316,0.4104,0.8085,0.4615,...,0.7778,0.6032,0.3887,0.8058,0.5466,0.0931,6,7,7,12

====================================================================================================
MODEL COMPARISON
====================================================================================================

Cross-validation summary:

,Model,CV Accuracy Mean,CV Accuracy SD,Mean Fold Accuracy CI Low,Mean Fold Accuracy CI High,CV Precision Mean,CV Precision SD,Mean Fold Precision CI Low,Mean Fold Precision CI High,CV Sensitivity Mean,...,Mean Fold F1 CI Low,Mean Fold F1 CI High,CV AUC Mean,CV AUC SD,Mean Fold AUC CI Low,Mean Fold AUC CI High,CV Balanced Accuracy Mean,CV Balanced Accuracy SD,CV MCC Mean,CV MCC SD
0,LightGBM,0.7049,0.0440,0.5232,0.8384,0.7607,0.0444,0.5188,0.9022,0.7353,...,0.5780,0.8814,0.7410,0.0566,0.5412,0.9110,0.6980,0.0454,0.3976,0.0892
1,Logistic Regression,0.6286,0.0585,0.4480,0.7788,0.7050,0.0556,0.4568,0.8704,0.6412,...,0.4755,0.8260,0.6762,0.0786,0.4619,0.8632,0.6259,0.0579,0.2507,0.1151
2,SVM,0.6665,0.0784,0.4859,0.8079,0.7598,0.0871,0.5032,0.9038,0.6471,...,0.5006,0.8489,0.7249,0.0898,0.5213,0.8932,0.6705,0.0797,0.3433,0.1578
3,Decision Tree,0.5935,0.0691,0.4150,0.7500,0.7102,0.0994,0.4422,0.8759,0.5588,...,0.4008,0.7830,0.6491,0.0599,0.4398,0.8369,0.6002,0.0813,0.2038,0.1648
4,Gaussian Naive Bayes,0.6180,0.0849,0.4390,0.7692,0.6965,0.0867,0.4515,0.8614,0.6412,...,0.4733,0.8185,0.6351,0.0935,0.4183,0.8306,0.6126,0.0931,0.2245,0.1839
5,LDA,0.6390,0.0942,0.4599,0.7854,0.6754,0.0679,0.4511,0.8396,0.7471,...,0.5482,0.8391,0.6859,0.0815,0.4769,0.8681,0.6160,0.0922,0.2447,0.1980

Independent test results:

,Accuracy,Accuracy CI Low,Accuracy CI High,Precision,Precision CI Low,Precision CI High,Sensitivity,Sensitivity CI Low,Sensitivity CI High,Specificity,...,F1 CI High,AUC,AUC CI Low,AUC CI High,Balanced Accuracy,MCC,TN,FP,FN,TP
Model,,,,,,,,,,,,,,,,,,,,,
LightGBM,0.6562,0.4831,0.7959,0.7857,0.5241,0.9243,0.5789,0.3628,0.7686,0.7692,...,0.8333,0.6761,0.4615,0.8704,0.6741,0.3447,10,3,8,11
Logistic Regression,0.5625,0.3933,0.7183,0.6316,0.4104,0.8085,0.6316,0.4104,0.8085,0.4615,...,0.7778,0.5992,0.3846,0.8057,0.5466,0.0931,6,7,7,12
SVM,0.6562,0.4831,0.7959,0.7500,0.5050,0.8982,0.6316,0.4104,0.8085,0.6923,...,0.8421,0.6397,0.4413,0.8340,0.6619,0.3181,9,4,7,12
Decision Tree,0.5938,0.4226,0.7448,0.6667,0.4375,0.8372,0.6316,0.4104,0.8085,0.5385,...,0.7909,0.5931,0.3927,0.7814,0.5850,0.1683,7,6,7,12
Gaussian Naive Bayes,0.6875,0.5143,0.8205,0.8000,0.5481,0.9295,0.6316,0.4104,0.8085,0.7692,...,0.8571,0.7490,0.5628,0.9028,0.7004,0.3945,10,3,7,12
LDA,0.5625,0.3933,0.7183,0.6316,0.4104,0.8085,0.6316,0.4104,0.8085,0.4615,...,0.7778,0.6032,0.3887,0.8058,0.5466,0.0931,6,7,7,12

====================================================================================================
INDEPENDENT TEST CONFUSION MATRICES
====================================================================================================

LightGBM
Rows = true labels [HC, PD]
Columns = predicted labels [HC, PD]
[[10  3]
 [ 8 11]]

Logistic Regression
Rows = true labels [HC, PD]
Columns = predicted labels [HC, PD]
[[ 6  7]
 [ 7 12]]

SVM
Rows = true labels [HC, PD]
Columns = predicted labels [HC, PD]
[[ 9  4]
 [ 7 12]]

Decision Tree
Rows = true labels [HC, PD]
Columns = predicted labels [HC, PD]
[[ 7  6]
 [ 7 12]]

Gaussian Naive Bayes
Rows = true labels [HC, PD]
Columns = predicted labels [HC, PD]
[[10  3]
 [ 7 12]]

LDA
Rows = true labels [HC, PD]
Columns = predicted labels [HC, PD]
[[ 6  7]
 [ 7 12]]

Saved result files:
1. classification_fold_results_95CI.csv
2. classification_cv_summary_95CI.csv
3. classification_independent_test_results_95CI.csv