***MIRA-Net***

In [1]:
# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

df_acoustic_top7 = pd.read_csv('/content/drive/MyDrive/Acoustic-subject-level-dataset_top7.csv')
df_acoustic_top7 = df_acoustic_top7.drop(columns=['Participant_ID'])
print(df_acoustic_top7.shape)
print(df_acoustic_top7.head())

(193, 8)
       RPDE  Degree-voice breaks  Delta2  Delta3  Delta11  MFCC5   spread1  \
0  0.428488                  0.0     0.0     0.0      0.0    0.0 -4.239926
1  0.542488                  0.0     0.0     0.0      0.0    0.0 -4.519291
2  0.332247                  0.0     0.0     0.0      0.0    0.0 -7.226125
3  0.498593                  0.0     0.0     0.0      0.0    0.0 -5.632290
4  0.470775                  0.0     0.0     0.0      0.0    0.0 -5.523149

   Status
0       1
1       1
2       0
3       1
4       1

In [3]:
import pandas as pd

final_meg_df = pd.read_csv('/content/drive/MyDrive/final_meg-rest(par)_top7_rfc+shap_10-fold_analysis_last_column.csv')

print("Loaded data shape:", final_meg_df.shape)
print(final_meg_df.head())

Loaded data shape: (127, 8)
   ibi_cv_asym  ibi_cv_L_std  mean_burst_duration_R_std  \
0     0.002893      0.048081                   0.002407
1    -0.018062      0.085531                   0.005160
2    -0.002573      0.032173                   0.001270
3     0.001531      0.044880                   0.003106
4     0.023834      0.142267                   0.004734

   mean_burst_duration_asym  burst_dur_cv_R_std  burst_dur_cv_L_std  \
0                  0.009156            0.040693            0.055777
1                 -0.005581            0.048648            0.052883
2                  0.007325            0.030995            0.046488
3                  0.005372            0.042429            0.049082
4                  0.014897            0.044595            0.053040

   ibi_cv_R_std  PD_Label_Combined
0      0.043907                  0
1      0.086747                  0
2      0.032718                  0
3      0.044973                  1
4      0.113787                  1

Advance EDANN+SCL with cross modality & cross participant solution

In [4]:
# ============================================================
#     SIMPLE + STABLE DANN + SCL + MLP CLASSIFIER
#     CROSS-MODAL + CROSS-PARTICIPANT ANALYSIS
# ============================================================

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from torch.autograd import Function
import torch.nn.functional as F

import numpy as np

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# ============================================================
# LOAD DATA
# ============================================================

# First 7 columns -> Features
# Last column     -> PD / HC labels

X_acoustic = df_acoustic_top7.iloc[:, :-1].values.astype(np.float32)
y_acoustic = df_acoustic_top7.iloc[:, -1].values.astype(np.int64)

X_meg = final_meg_df.iloc[:, :-1].values.astype(np.float32)
y_meg = final_meg_df.iloc[:, -1].values.astype(np.int64)

# ============================================================
# STANDARDIZATION
# ============================================================

scaler_acoustic = StandardScaler()
scaler_meg = StandardScaler()

X_acoustic = scaler_acoustic.fit_transform(X_acoustic)
X_meg = scaler_meg.fit_transform(X_meg)

# ============================================================
# DOMAIN LABELS
# ============================================================

# 0 -> Acoustic
# 1 -> MEG

domain_acoustic = np.zeros(len(X_acoustic))
domain_meg = np.ones(len(X_meg))

# ============================================================
# COMBINE
# ============================================================

X_all = np.vstack([
    X_acoustic,
    X_meg
]).astype(np.float32)

task_labels = np.hstack([
    y_acoustic,
    y_meg
]).astype(np.int64)

domain_labels = np.hstack([
    domain_acoustic,
    domain_meg
]).astype(np.int64)

# ============================================================
# TENSORS
# ============================================================

X_all_tensor = torch.tensor(
    X_all
).float().to(device)

task_labels_tensor = torch.tensor(
    task_labels
).long().to(device)

domain_labels_tensor = torch.tensor(
    domain_labels
).long().to(device)

# ============================================================
# GRADIENT REVERSAL
# ============================================================

class GradReverse(Function):

    @staticmethod
    def forward(ctx, x, lambd):

        ctx.lambd = lambd

        return x.view_as(x)

    @staticmethod
    def backward(ctx, grad_output):

        return -ctx.lambd * grad_output, None

def grad_reverse(x, lambd):

    return GradReverse.apply(x, lambd)

# ============================================================
# SIMPLE RESIDUAL BLOCK
# ============================================================

class ResidualBlock(nn.Module):

    def __init__(self, dim):

        super().__init__()

        self.block = nn.Sequential(

            nn.Linear(dim, dim),
            nn.ReLU(),

            nn.Linear(dim, dim)
        )

    def forward(self, x):

        return F.relu(
            self.block(x) + x
        )

# ============================================================
# DANN + SCL MODEL
# ============================================================

class DANNContrastive(nn.Module):

    def __init__(self, input_dim, latent_dim=32):

        super().__init__()

        # ====================================================
        # SIMPLE ENCODER
        # ====================================================

        self.encoder = nn.Sequential(

            nn.Linear(input_dim, 128),
            nn.ReLU(),

            ResidualBlock(128),

            nn.Linear(128, 64),
            nn.ReLU(),

            nn.Dropout(0.1),

            nn.Linear(64, latent_dim)
        )

        # ====================================================
        # TASK HEAD
        # ====================================================

        self.task_head = nn.Sequential(

            nn.Linear(latent_dim, 32),
            nn.ReLU(),

            nn.Dropout(0.2),

            nn.Linear(32, 2)
        )

        # ====================================================
        # DOMAIN HEAD
        # ====================================================

        self.domain_head = nn.Sequential(

            nn.Linear(latent_dim, 16),
            nn.ReLU(),

            nn.Linear(16, 2)
        )

    def forward(self, x, lambd=1.0):

        z = self.encoder(x)

        # L2 NORMALIZATION

        z_norm = F.normalize(
            z,
            p=2,
            dim=1
        )

        # DANN

        rev_z = grad_reverse(
            z_norm,
            lambd
        )

        task_out = self.task_head(z_norm)

        domain_out = self.domain_head(rev_z)

        return task_out, domain_out, z_norm

# ============================================================
# SUPERVISED CONTRASTIVE LOSS
# ============================================================

class SupConLoss(nn.Module):

    def __init__(self, temperature=0.07):

        super().__init__()

        self.temperature = temperature

    def forward(self, features, labels):

        device = features.device

        labels = labels.contiguous().view(-1, 1)

        mask = torch.eq(
            labels,
            labels.T
        ).float().to(device)

        similarity = torch.matmul(
            features,
            features.T
        ) / self.temperature

        logits_max, _ = torch.max(
            similarity,
            dim=1,
            keepdim=True
        )

        logits = similarity - logits_max.detach()

        logits_mask = torch.ones_like(mask) - torch.eye(
            mask.shape[0]
        ).to(device)

        mask = mask * logits_mask

        exp_logits = torch.exp(logits) * logits_mask

        log_prob = logits - torch.log(
            exp_logits.sum(1, keepdim=True) + 1e-8
        )

        mean_log_prob_pos = (
            mask * log_prob
        ).sum(1) / (mask.sum(1) + 1e-8)

        loss = -mean_log_prob_pos.mean()

        return loss

# ============================================================
# DATA LOADER
# ============================================================

dataset = TensorDataset(
    X_all_tensor,
    task_labels_tensor,
    domain_labels_tensor
)

loader = DataLoader(
    dataset,
    batch_size=128,
    shuffle=True
)

# ============================================================
# MODEL
# ============================================================

model = DANNContrastive(
    input_dim=X_all.shape[1],
    latent_dim=32
).to(device)

# ============================================================
# OPTIMIZER
# ============================================================

optimizer = optim.Adam(
    model.parameters(),
    lr=1e-3,
    weight_decay=1e-4
)

# ============================================================
# LOSSES
# ============================================================

task_loss_fn = nn.CrossEntropyLoss()

domain_loss_fn = nn.CrossEntropyLoss()

contrastive_loss_fn = SupConLoss(
    temperature=0.07
)

epochs = 120

print("\nTraining Started...\n")

# ============================================================
# TRAINING
# ============================================================

for epoch in range(epochs):

    model.train()

    total_correct = 0
    total_samples = 0

    # ========================================================
    # WEAKER DANN
    # ========================================================

    p = min(epoch / 50.0, 1.0)

    lambd = 0.25 * (
        2 / (1 + np.exp(-10 * p)) - 1
    )

    for xb, y_task, y_dom in loader:

        optimizer.zero_grad()

        task_out, dom_out, z = model(
            xb,
            lambd
        )

        # ====================================================
        # LOSSES
        # ====================================================

        loss_task = task_loss_fn(
            task_out,
            y_task
        )

        loss_domain = domain_loss_fn(
            dom_out,
            y_dom
        )

        loss_contrastive = contrastive_loss_fn(
            z,
            y_task
        )

        # ====================================================
        # FINAL LOSS
        # ====================================================

        loss = (
            3.0 * loss_task +
            0.25 * loss_domain +
            0.55 * loss_contrastive
        )

        loss.backward()

        optimizer.step()

        preds = task_out.argmax(1)

        total_correct += (
            preds == y_task
        ).sum().item()

        total_samples += len(y_task)

    acc = total_correct / total_samples

    print(
        f"Epoch {epoch+1}/{epochs} "
        f"| λ={lambd:.3f} "
        f"| Acc={acc:.4f}"
    )

# ============================================================
# EXTRACT LATENT FEATURES
# ============================================================

model.eval()

with torch.no_grad():

    fused_acoustic_32D = model(
        torch.tensor(X_acoustic).float().to(device),
        0
    )[2].cpu().numpy()

    fused_meg_32D = model(
        torch.tensor(X_meg).float().to(device),
        0
    )[2].cpu().numpy()

# ============================================================
# COMBINE LATENTS
# ============================================================

X_fused = np.vstack([
    fused_acoustic_32D,
    fused_meg_32D
])

y_fused = np.hstack([
    y_acoustic,
    y_meg
])

# ============================================================
# SIMPLE MLP CLASSIFIER
# ============================================================

class FinalMLP(nn.Module):

    def __init__(self, input_dim=32):

        super().__init__()

        self.net = nn.Sequential(

            nn.Linear(input_dim, 64),
            nn.ReLU(),

            nn.Dropout(0.2),

            nn.Linear(64, 32),
            nn.ReLU(),

            nn.Linear(32, 2)
        )

    def forward(self, x):

        return self.net(x)

# ============================================================
# CROSS PARTICIPANT EVALUATION
# ============================================================

print("\n======================================")
print(" CROSS PARTICIPANT ANALYSIS")
print("======================================\n")

skf = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

accs = []
precs = []
recs = []
f1s = []
aucs = []

fold = 1

for train_idx, test_idx in skf.split(X_fused, y_fused):

    X_train = torch.tensor(
        X_fused[train_idx]
    ).float().to(device)

    X_test = torch.tensor(
        X_fused[test_idx]
    ).float().to(device)

    y_train = torch.tensor(
        y_fused[train_idx]
    ).long().to(device)

    y_test = y_fused[test_idx]

    clf = FinalMLP().to(device)

    optimizer_clf = optim.Adam(
        clf.parameters(),
        lr=1e-3
    )

    criterion = nn.CrossEntropyLoss()

    # ========================================================
    # TRAIN MLP
    # ========================================================

    clf.train()

    for epoch in range(80):

        optimizer_clf.zero_grad()

        outputs = clf(X_train)

        loss = criterion(
            outputs,
            y_train
        )

        loss.backward()

        optimizer_clf.step()

    # ========================================================
    # TEST
    # ========================================================

    clf.eval()

    with torch.no_grad():

        outputs = clf(X_test)

        probs = F.softmax(
            outputs,
            dim=1
        )[:, 1].cpu().numpy()

        preds = outputs.argmax(1).cpu().numpy()

    acc = accuracy_score(y_test, preds)

    prec = precision_score(y_test, preds)

    rec = recall_score(y_test, preds)

    f1 = f1_score(y_test, preds)

    auc = roc_auc_score(y_test, probs)

    accs.append(acc)
    precs.append(prec)
    recs.append(rec)
    f1s.append(f1)
    aucs.append(auc)

    print(f"Fold {fold}")

    print(f"Accuracy  : {acc:.4f}")
    print(f"Precision : {prec:.4f}")
    print(f"Recall    : {rec:.4f}")
    print(f"F1-Score  : {f1:.4f}")
    print(f"AUC       : {auc:.4f}")

    print()

    fold += 1

# ============================================================
# FINAL RESULTS
# ============================================================

print("\n======================================")
print(" FINAL RESULTS")
print("======================================\n")

print(f"Mean Accuracy  : {np.mean(accs)*100:.2f}%")
print(f"Mean Precision : {np.mean(precs)*100:.2f}%")
print(f"Mean Recall    : {np.mean(recs)*100:.2f}%")
print(f"Mean F1-Score  : {np.mean(f1s)*100:.2f}%")
print(f"Mean AUC       : {np.mean(aucs)*100:.2f}%")

print("\n======================================")
print(" LATENT SHAPES")
print("======================================\n")

print("Acoustic :", fused_acoustic_32D.shape)
print("MEG      :", fused_meg_32D.shape)

Training Started...

Epoch 1/120 | λ=0.000 | Acc=0.4094
Epoch 2/120 | λ=0.025 | Acc=0.4094
Epoch 3/120 | λ=0.049 | Acc=0.4094
Epoch 4/120 | λ=0.073 | Acc=0.4125
Epoch 5/120 | λ=0.095 | Acc=0.5062
Epoch 6/120 | λ=0.116 | Acc=0.5875
Epoch 7/120 | λ=0.134 | Acc=0.5813
Epoch 8/120 | λ=0.151 | Acc=0.5938
Epoch 9/120 | λ=0.166 | Acc=0.5875
Epoch 10/120 | λ=0.179 | Acc=0.5938
Epoch 11/120 | λ=0.190 | Acc=0.5906
Epoch 12/120 | λ=0.200 | Acc=0.5906
Epoch 13/120 | λ=0.208 | Acc=0.5906
Epoch 14/120 | λ=0.215 | Acc=0.5906
Epoch 15/120 | λ=0.221 | Acc=0.5906
Epoch 16/120 | λ=0.226 | Acc=0.5906
Epoch 17/120 | λ=0.230 | Acc=0.5906
Epoch 18/120 | λ=0.234 | Acc=0.5906
Epoch 19/120 | λ=0.237 | Acc=0.5906
Epoch 20/120 | λ=0.239 | Acc=0.5906
Epoch 21/120 | λ=0.241 | Acc=0.5938
Epoch 22/120 | λ=0.243 | Acc=0.5938
Epoch 23/120 | λ=0.244 | Acc=0.6000
Epoch 24/120 | λ=0.245 | Acc=0.6094
Epoch 25/120 | λ=0.246 | Acc=0.6062
Epoch 26/120 | λ=0.247 | Acc=0.6469
Epoch 27/120 | λ=0.247 | Acc=0.6562
Epoch 28/120 | λ=0.248 | Acc=0.6937
Epoch 29/120 | λ=0.248 | Acc=0.6719
Epoch 30/120 | λ=0.248 | Acc=0.6594
Epoch 31/120 | λ=0.249 | Acc=0.7281
Epoch 32/120 | λ=0.249 | Acc=0.6844
Epoch 33/120 | λ=0.249 | Acc=0.7438
Epoch 34/120 | λ=0.249 | Acc=0.7719
Epoch 35/120 | λ=0.249 | Acc=0.7250
Epoch 36/120 | λ=0.250 | Acc=0.7719
Epoch 37/120 | λ=0.250 | Acc=0.7656
Epoch 38/120 | λ=0.250 | Acc=0.7875
Epoch 39/120 | λ=0.250 | Acc=0.7562
Epoch 40/120 | λ=0.250 | Acc=0.8063
Epoch 41/120 | λ=0.250 | Acc=0.7688
Epoch 42/120 | λ=0.250 | Acc=0.7906
Epoch 43/120 | λ=0.250 | Acc=0.7719
Epoch 44/120 | λ=0.250 | Acc=0.7937
Epoch 45/120 | λ=0.250 | Acc=0.7812
Epoch 46/120 | λ=0.250 | Acc=0.7688
Epoch 47/120 | λ=0.250 | Acc=0.7937
Epoch 48/120 | λ=0.250 | Acc=0.7969
Epoch 49/120 | λ=0.250 | Acc=0.7812
Epoch 50/120 | λ=0.250 | Acc=0.7969
Epoch 51/120 | λ=0.250 | Acc=0.8063
Epoch 52/120 | λ=0.250 | Acc=0.8063
Epoch 53/120 | λ=0.250 | Acc=0.8031
Epoch 54/120 | λ=0.250 | Acc=0.8156
Epoch 55/120 | λ=0.250 | Acc=0.7906
Epoch 56/120 | λ=0.250 | Acc=0.8156
Epoch 57/120 | λ=0.250 | Acc=0.7875
Epoch 58/120 | λ=0.250 | Acc=0.8094
Epoch 59/120 | λ=0.250 | Acc=0.8250
Epoch 60/120 | λ=0.250 | Acc=0.8000
Epoch 61/120 | λ=0.250 | Acc=0.8313
Epoch 62/120 | λ=0.250 | Acc=0.8219
Epoch 63/120 | λ=0.250 | Acc=0.8219
Epoch 64/120 | λ=0.250 | Acc=0.8094
Epoch 65/120 | λ=0.250 | Acc=0.8094
Epoch 66/120 | λ=0.250 | Acc=0.8031
Epoch 67/120 | λ=0.250 | Acc=0.8313
Epoch 68/120 | λ=0.250 | Acc=0.8375
Epoch 69/120 | λ=0.250 | Acc=0.8250
Epoch 70/120 | λ=0.250 | Acc=0.8219
Epoch 71/120 | λ=0.250 | Acc=0.8250
Epoch 72/120 | λ=0.250 | Acc=0.8187
Epoch 73/120 | λ=0.250 | Acc=0.8344
Epoch 74/120 | λ=0.250 | Acc=0.8469
Epoch 75/120 | λ=0.250 | Acc=0.8531
Epoch 76/120 | λ=0.250 | Acc=0.8469
Epoch 77/120 | λ=0.250 | Acc=0.8469
Epoch 78/120 | λ=0.250 | Acc=0.8500
Epoch 79/120 | λ=0.250 | Acc=0.8344
Epoch 80/120 | λ=0.250 | Acc=0.8250
Epoch 81/120 | λ=0.250 | Acc=0.8344
Epoch 82/120 | λ=0.250 | Acc=0.8562
Epoch 83/120 | λ=0.250 | Acc=0.8031
Epoch 84/120 | λ=0.250 | Acc=0.8375
Epoch 85/120 | λ=0.250 | Acc=0.8500
Epoch 86/120 | λ=0.250 | Acc=0.8406
Epoch 87/120 | λ=0.250 | Acc=0.8531
Epoch 88/120 | λ=0.250 | Acc=0.8500
Epoch 89/120 | λ=0.250 | Acc=0.8250
Epoch 90/120 | λ=0.250 | Acc=0.8344
Epoch 91/120 | λ=0.250 | Acc=0.8344
Epoch 92/120 | λ=0.250 | Acc=0.8750
Epoch 93/120 | λ=0.250 | Acc=0.8375
Epoch 94/120 | λ=0.250 | Acc=0.8562
Epoch 95/120 | λ=0.250 | Acc=0.8688
Epoch 96/120 | λ=0.250 | Acc=0.8438
Epoch 97/120 | λ=0.250 | Acc=0.8375
Epoch 98/120 | λ=0.250 | Acc=0.8406
Epoch 99/120 | λ=0.250 | Acc=0.8531
Epoch 100/120 | λ=0.250 | Acc=0.8500
Epoch 101/120 | λ=0.250 | Acc=0.8625
Epoch 102/120 | λ=0.250 | Acc=0.8531
Epoch 103/120 | λ=0.250 | Acc=0.8562
Epoch 104/120 | λ=0.250 | Acc=0.8594
Epoch 105/120 | λ=0.250 | Acc=0.8656
Epoch 106/120 | λ=0.250 | Acc=0.8500
Epoch 107/120 | λ=0.250 | Acc=0.8500
Epoch 108/120 | λ=0.250 | Acc=0.8656
Epoch 109/120 | λ=0.250 | Acc=0.8500
Epoch 110/120 | λ=0.250 | Acc=0.8344
Epoch 111/120 | λ=0.250 | Acc=0.8750
Epoch 112/120 | λ=0.250 | Acc=0.8781
Epoch 113/120 | λ=0.250 | Acc=0.8594
Epoch 114/120 | λ=0.250 | Acc=0.8500
Epoch 115/120 | λ=0.250 | Acc=0.8781
Epoch 116/120 | λ=0.250 | Acc=0.8719
Epoch 117/120 | λ=0.250 | Acc=0.8594
Epoch 118/120 | λ=0.250 | Acc=0.8656
Epoch 119/120 | λ=0.250 | Acc=0.8812
Epoch 120/120 | λ=0.250 | Acc=0.8781

======================================
 CROSS PARTICIPANT ANALYSIS
======================================

Fold 1
Accuracy  : 0.8594
Precision : 0.8919
Recall    : 0.8684
F1-Score  : 0.8800
AUC       : 0.9190

Fold 2
Accuracy  : 0.8594
Precision : 0.8537
Recall    : 0.9211
F1-Score  : 0.8861
AUC       : 0.9615

Fold 3
Accuracy  : 0.9062
Precision : 0.9211
Recall    : 0.9211
F1-Score  : 0.9211
AUC       : 0.9651

Fold 4
Accuracy  : 0.8906
Precision : 0.9189
Recall    : 0.8947
F1-Score  : 0.9067
AUC       : 0.9787

Fold 5
Accuracy  : 0.9062
Precision : 0.9189
Recall    : 0.9189
F1-Score  : 0.9189
AUC       : 0.9640


======================================
 FINAL RESULTS
======================================

Mean Accuracy  : 88.44%
Mean Precision : 90.09%
Mean Recall    : 90.48%
Mean F1-Score  : 90.25%
Mean AUC       : 95.77%

======================================
 LATENT SHAPES
======================================

Acoustic : (193, 32)
MEG      : (127, 32)

Concatenating acoustic and meg

In [5]:
import torch

# Assuming fused_acoustic_32D and fused_meg_32D are numpy arrays of shape (7350, 32)

# Step 1: Convert numpy arrays to torch tensors (float32)
fused_acoustic_tensor = torch.from_numpy(fused_acoustic_32D).float()
fused_meg_tensor = torch.from_numpy(fused_meg_32D).float()

# Step 2: Concatenate row-wise (along dim=0)
fused_output_tensor = torch.cat([fused_acoustic_tensor, fused_meg_tensor], dim=0)  # Shape: (14700, 32)

# Step 3: Print shape and dtype
print(fused_output_tensor.shape)  # torch.Size([14700, 32])
print(fused_output_tensor.dtype)  # torch.float32

torch.Size([320, 32])
torch.float32

Adding target columns of acoustic & meg

In [6]:
import torch
import numpy as np

# ------------------------
# Step 1: Extract targets correctly
# ------------------------

# Acoustic target from df_acoustic_top7 (last column)
y_acoustic = df_acoustic_top7.iloc[:, -1].values.astype(np.int32)   # (7350,)

# MEG target from final_meg_df (last column)
y_meg = final_meg_df.iloc[:, -1].values.astype(np.int32)           # (7350,)

# Convert to tensors (reshape to column)
acoustic_target_tensor = torch.tensor(y_acoustic).long().reshape(-1, 1)   # (7350, 1)
meg_target_tensor      = torch.tensor(y_meg).long().reshape(-1, 1)        # (7350, 1)

# ------------------------
# Step 2: Convert 32D latent features to tensors
# ------------------------

fused_acoustic_tensor = torch.from_numpy(fused_acoustic_32D).float()  # (7350, 32)
fused_meg_tensor      = torch.from_numpy(fused_meg_32D).float()       # (7350, 32)

# ------------------------
# Step 3: Attach target columns
# ------------------------

# Concatenate latent features with target
acoustic_full = torch.cat([fused_acoustic_tensor, acoustic_target_tensor.float()], dim=1)  # (7350, 65)
meg_full      = torch.cat([fused_meg_tensor,      meg_target_tensor.float()],      dim=1)  # (7350, 65)

# ------------------------
# Step 4: Concatenate both datasets
# ------------------------

fused_df = torch.cat([acoustic_full, meg_full], dim=0)  # (14700, 65)

# ------------------------
# Step 5: Separate features and labels for PyTorch
# ------------------------

X = fused_df[:, :-1].float()   # Features (32D) -> float32
y = fused_df[:, -1].long()     # Target -> int32

# ------------------------
# Step 6: Print shapes and dtypes
# ------------------------

print(f"Features shape: {X.shape}, dtype: {X.dtype}")  # (14700, 32), float32
print(f"Labels shape: {y.shape}, dtype: {y.dtype}")    # (14700,), int32

Features shape: torch.Size([320, 32]), dtype: torch.float32
Labels shape: torch.Size([320]), dtype: torch.int64

In [7]:
import torch
import pandas as pd

# fused_df shape = (14700, 33)

# Step 6: Convert fused tensor to numpy
fused_df_np = fused_df.numpy()

# Step 7: Create correct column names for 32 latent features + 1 label
feature_names = [f"feat_{i}" for i in range(32)]
feature_names.append("PD_Label_Combined")

# Step 8: Convert to DataFrame
fused_df_named = pd.DataFrame(fused_df_np, columns=feature_names)

# Step 9: Verify
print(fused_df_named.shape)
print(fused_df_named.head())
print(fused_df_named.tail())

(320, 33)
     feat_0    feat_1    feat_2    feat_3    feat_4    feat_5    feat_6  \
0 -0.167408  0.247791  0.108752  0.145678  0.128758  0.139512 -0.388908
1 -0.180029  0.247106  0.100994  0.151763  0.123837  0.135823 -0.402635
2 -0.001097  0.241502  0.040228 -0.006898 -0.064571  0.300266 -0.410168
3 -0.176504  0.251508  0.101407  0.158764  0.116113  0.131070 -0.395935
4 -0.173168  0.251137  0.105332  0.155920  0.118184  0.132368 -0.391873

     feat_7    feat_8    feat_9  ...   feat_23   feat_24   feat_25   feat_26  \
0  0.054051  0.095272  0.254308  ...  0.108517 -0.281111  0.177043  0.142417
1  0.052673  0.077987  0.259495  ...  0.100198 -0.276510  0.187728  0.125000
2 -0.137268 -0.039887  0.266537  ...  0.046432 -0.352390  0.039223  0.215824
3  0.038676  0.080782  0.265491  ...  0.101161 -0.292017  0.183169  0.119719
4  0.043918  0.086204  0.263430  ...  0.104799 -0.291758  0.184798  0.124395

    feat_27   feat_28   feat_29   feat_30   feat_31  PD_Label_Combined
0  0.167025 -0.078603  0.080411  0.143566 -0.061701                1.0
1  0.170609 -0.067088  0.090003  0.144013 -0.061494                1.0
2  0.131209 -0.130985 -0.058039  0.051696 -0.153072                0.0
3  0.178148 -0.062601  0.082337  0.140690 -0.052108                1.0
4  0.174616 -0.067344  0.082248  0.141177 -0.051903                1.0

[5 rows x 33 columns]
       feat_0    feat_1    feat_2    feat_3    feat_4    feat_5    feat_6  \
315 -0.120494  0.222308  0.051255  0.110616  0.088675  0.249190 -0.389066
316 -0.111501  0.201342  0.084623  0.150340  0.119532  0.165589 -0.322789
317 -0.000726  0.220240  0.029568 -0.010912 -0.066983  0.324351 -0.414913
318 -0.075490  0.227554  0.061746  0.078284  0.003309  0.296805 -0.394502
319 -0.117272  0.246315  0.050150  0.168366  0.137220  0.178903 -0.397066

       feat_7    feat_8    feat_9  ...   feat_23   feat_24   feat_25  \
315 -0.100743 -0.005789  0.292479  ...  0.068717 -0.338708  0.068657
316 -0.055082  0.054647  0.292251  ...  0.004845 -0.312237  0.217194
317 -0.165653 -0.114927  0.236822  ...  0.113643 -0.350189  0.071393
318 -0.126118 -0.063019  0.288609  ...  0.072854 -0.361191  0.092873
319 -0.078382  0.021282  0.275629  ...  0.052600 -0.300884  0.129632

      feat_26   feat_27   feat_28   feat_29   feat_30   feat_31  \
315  0.215861  0.141846 -0.107299 -0.045929  0.096667 -0.121763
316  0.141954  0.154216 -0.006091 -0.000985  0.189160 -0.045804
317  0.269450  0.088896 -0.130458 -0.071817  0.014122 -0.186085
318  0.239526  0.132472 -0.114987 -0.081330  0.071849 -0.133440
319  0.177024  0.167951 -0.073407  0.018561  0.114748 -0.080984

     PD_Label_Combined
315                0.0
316                1.0
317                0.0
318                0.0
319                1.0

[5 rows x 33 columns]

In [8]:
# Make a copy to be safe (optional)
fused_df_named_int = fused_df_named.copy()

# Convert only the last column to int
fused_df_named_int['PD_Label_Combined'] = fused_df_named_int['PD_Label_Combined'].astype(int)

# Verify
print(fused_df_named_int.dtypes)
print(fused_df_named_int.head())

feat_0               float32
feat_1               float32
feat_2               float32
feat_3               float32
feat_4               float32
feat_5               float32
feat_6               float32
feat_7               float32
feat_8               float32
feat_9               float32
feat_10              float32
feat_11              float32
feat_12              float32
feat_13              float32
feat_14              float32
feat_15              float32
feat_16              float32
feat_17              float32
feat_18              float32
feat_19              float32
feat_20              float32
feat_21              float32
feat_22              float32
feat_23              float32
feat_24              float32
feat_25              float32
feat_26              float32
feat_27              float32
feat_28              float32
feat_29              float32
feat_30              float32
feat_31              float32
PD_Label_Combined      int64
dtype: object
     feat_0    feat_1    feat_2    feat_3    feat_4    feat_5    feat_6  \
0 -0.167408  0.247791  0.108752  0.145678  0.128758  0.139512 -0.388908
1 -0.180029  0.247106  0.100994  0.151763  0.123837  0.135823 -0.402635
2 -0.001097  0.241502  0.040228 -0.006898 -0.064571  0.300266 -0.410168
3 -0.176504  0.251508  0.101407  0.158764  0.116113  0.131070 -0.395935
4 -0.173168  0.251137  0.105332  0.155920  0.118184  0.132368 -0.391873

     feat_7    feat_8    feat_9  ...   feat_23   feat_24   feat_25   feat_26  \
0  0.054051  0.095272  0.254308  ...  0.108517 -0.281111  0.177043  0.142417
1  0.052673  0.077987  0.259495  ...  0.100198 -0.276510  0.187728  0.125000
2 -0.137268 -0.039887  0.266537  ...  0.046432 -0.352390  0.039223  0.215824
3  0.038676  0.080782  0.265491  ...  0.101161 -0.292017  0.183169  0.119719
4  0.043918  0.086204  0.263430  ...  0.104799 -0.291758  0.184798  0.124395

    feat_27   feat_28   feat_29   feat_30   feat_31  PD_Label_Combined
0  0.167025 -0.078603  0.080411  0.143566 -0.061701                  1
1  0.170609 -0.067088  0.090003  0.144013 -0.061494                  1
2  0.131209 -0.130985 -0.058039  0.051696 -0.153072                  0
3  0.178148 -0.062601  0.082337  0.140690 -0.052108                  1
4  0.174616 -0.067344  0.082248  0.141177 -0.051903                  1

[5 rows x 33 columns]

Saving the data

In [9]:
# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [10]:
import pandas as pd

fused_df_named_int.to_csv('/content/drive//MyDrive/Subject-level-fused_frest_(with_120_epoches)_MIRA-Net_data.csv', index=False)

In [1]:
# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
fused_df_named_int = pd.read_csv('/content/drive//MyDrive/Subject-level-fused_frest_(with_120_epoches)_MIRA-Net_data.csv')
fused_df_named_int.head()

,feat_0,feat_1,feat_2,feat_3,feat_4,feat_5,feat_6,feat_7,feat_8,feat_9,...,feat_23,feat_24,feat_25,feat_26,feat_27,feat_28,feat_29,feat_30,feat_31,PD_Label_Combined
0,-0.167408,0.247791,0.108752,0.145678,0.128758,0.139512,-0.388908,0.054051,0.095272,0.254308,...,0.108517,-0.281111,0.177043,0.142417,0.167025,-0.078603,0.080411,0.143566,-0.061701,1
1,-0.180029,0.247106,0.100994,0.151763,0.123837,0.135823,-0.402635,0.052673,0.077987,0.259495,...,0.100198,-0.276510,0.187728,0.125000,0.170609,-0.067088,0.090003,0.144013,-0.061494,1
2,-0.001097,0.241502,0.040228,-0.006898,-0.064571,0.300266,-0.410168,-0.137268,-0.039887,0.266537,...,0.046432,-0.352390,0.039223,0.215824,0.131209,-0.130986,-0.058039,0.051696,-0.153072,0
3,-0.176504,0.251508,0.101407,0.158764,0.116113,0.131070,-0.395935,0.038676,0.080782,0.265491,...,0.101161,-0.292017,0.183169,0.119719,0.178148,-0.062601,0.082337,0.140690,-0.052108,1
4,-0.173168,0.251137,0.105332,0.155920,0.118184,0.132368,-0.391873,0.043918,0.086204,0.263430,...,0.104799,-0.291758,0.184798,0.124395,0.174616,-0.067344,0.082248,0.141177,-0.051903,1

Evaluation

In [3]:
# ============================================================
# ###8)###
# ENSEMBLE CLASSIFICATION WITH STRATIFIED 10-FOLD CV
# ============================================================

# ------------------ Install Required Packages ------------------

!pip install xgboost lightgbm catboost scikit-learn statsmodels matplotlib seaborn --quiet


# ------------------ Imports ------------------

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.utils.class_weight import compute_class_weight

from sklearn.model_selection import (
    train_test_split,
    StratifiedKFold
)

from sklearn.preprocessing import StandardScaler

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    balanced_accuracy_score,
    matthews_corrcoef,
    confusion_matrix
)

from sklearn.ensemble import (
    VotingClassifier,
    StackingClassifier,
    RandomForestClassifier,
    HistGradientBoostingClassifier
)

from sklearn.linear_model import LogisticRegression

from xgboost import XGBClassifier

from statsmodels.stats.proportion import proportion_confint


# ============================================================
# STEP 1: PREPARE DATA
# ============================================================

X = fused_df_named_int[
    [f'feat_{i}' for i in range(32)]
].copy()

y = fused_df_named_int[
    "PD_Label_Combined"
].copy()


# ------------------ Convert X to numeric ------------------

X = X.apply(
    pd.to_numeric,
    errors='coerce'
)

X.fillna(
    0,
    inplace=True
)


# ============================================================
# STEP 2: CLASS WEIGHTS
# ============================================================

classes = np.unique(y)

class_weights = compute_class_weight(
    class_weight='balanced',
    classes=classes,
    y=y
)

class_weights_dict = {
    int(classes[0]): float(class_weights[0]),
    int(classes[1]): float(class_weights[1])
}

print("\nClass Weights:")
print(class_weights_dict)


# ============================================================
# STEP 3: TRAIN-TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=42
)


print("\nTrain Shape :", X_train.shape)
print("Test Shape  :", X_test.shape)

print("\nTraining Class Distribution:")
print(y_train.value_counts())

print("\nTesting Class Distribution:")
print(y_test.value_counts())


# ============================================================
# STEP 4: HANDLE CLASS IMBALANCE
# ============================================================

cw = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_train),
    y=y_train
)

cw_dict = dict(
    zip(
        np.unique(y_train),
        cw
    )
)

scale_pos_weight = (
    cw[1] / cw[0]
)

print("\nTraining Class Weights:")
print(cw_dict)

print(
    "\nXGBoost scale_pos_weight:",
    scale_pos_weight
)


# ============================================================
# STEP 5: BASE MODEL CREATION FUNCTION
# ============================================================

def create_models():

    # ---------------- XGBoost ----------------

    xgb = XGBClassifier(
        n_estimators=200,
        max_depth=4,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,

        scale_pos_weight=scale_pos_weight,

        eval_metric='logloss',

        random_state=42,
        n_jobs=-1
    )


    # ---------------- Random Forest ----------------

    rf = RandomForestClassifier(
        n_estimators=200,

        class_weight='balanced',

        random_state=42,
        n_jobs=-1
    )


    # ---------------- HistGradientBoosting ----------------

    hgb = HistGradientBoostingClassifier(
        max_iter=200,
        learning_rate=0.05,
        max_leaf_nodes=31,

        class_weight='balanced',

        random_state=42
    )


    return xgb, rf, hgb


# ============================================================
# STEP 6: STRATIFIED 10-FOLD CV
# ============================================================

skf = StratifiedKFold(
    n_splits=10,
    shuffle=True,
    random_state=42
)


# ============================================================
# STEP 7: EVALUATION FUNCTION
# ============================================================

def evaluate_model(model_name):

    # ========================================================
    # CV METRIC STORAGE
    # ========================================================

    cv_accuracy = []
    cv_precision = []
    cv_sensitivity = []
    cv_f1 = []
    cv_auc = []
    cv_balanced_accuracy = []


    # ========================================================
    # 10-FOLD STRATIFIED CROSS-VALIDATION
    # ========================================================

    for fold, (train_idx, val_idx) in enumerate(
        skf.split(X_train, y_train),
        start=1
    ):

        print(
            f"\n{model_name} | Fold {fold}/10"
        )


        # ----------------------------------------------------
        # Split fold
        # ----------------------------------------------------

        X_tr = X_train.iloc[
            train_idx
        ]

        X_val = X_train.iloc[
            val_idx
        ]

        y_tr = y_train.iloc[
            train_idx
        ]

        y_val = y_train.iloc[
            val_idx
        ]


        # ----------------------------------------------------
        # Scaling INSIDE EACH FOLD
        # ----------------------------------------------------

        scaler = StandardScaler()

        X_tr_scaled = scaler.fit_transform(
            X_tr
        )

        X_val_scaled = scaler.transform(
            X_val
        )


        # ----------------------------------------------------
        # Create FRESH models for every fold
        # ----------------------------------------------------

        xgb, rf, hgb = create_models()


        # ----------------------------------------------------
        # Select requested model
        # ----------------------------------------------------

        if model_name == "XGBoost":

            model = xgb


        elif model_name == "Random Forest":

            model = rf


        elif model_name == "HistGradientBoosting":

            model = hgb


        elif model_name == "Voting Fusion":

            model = VotingClassifier(
                estimators=[
                    ('xgb', xgb),
                    ('rf', rf),
                    ('hgb', hgb)
                ],
                voting='soft'
            )


        elif model_name == "Stacking Fusion":

            model = StackingClassifier(
                estimators=[
                    ('xgb', xgb),
                    ('rf', rf),
                    ('hgb', hgb)
                ],

                final_estimator=LogisticRegression(
                    max_iter=1000,
                    class_weight='balanced'
                ),

                passthrough=True,

                cv=5
            )


        else:

            raise ValueError(
                f"Unknown model: {model_name}"
            )


        # ----------------------------------------------------
        # Train fold
        # ----------------------------------------------------

        model.fit(
            X_tr_scaled,
            y_tr
        )


        # ----------------------------------------------------
        # Validation predictions
        # ----------------------------------------------------

        val_preds = model.predict(
            X_val_scaled
        )

        val_probs = model.predict_proba(
            X_val_scaled
        )[:, 1]


        # ----------------------------------------------------
        # Fold metrics
        # ----------------------------------------------------

        fold_accuracy = accuracy_score(
            y_val,
            val_preds
        )

        fold_precision = precision_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_sensitivity = recall_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_f1 = f1_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_auc = roc_auc_score(
            y_val,
            val_probs
        )

        fold_balanced_accuracy = balanced_accuracy_score(
            y_val,
            val_preds
        )


        # ----------------------------------------------------
        # Store fold metrics
        # ----------------------------------------------------

        cv_accuracy.append(
            fold_accuracy
        )

        cv_precision.append(
            fold_precision
        )

        cv_sensitivity.append(
            fold_sensitivity
        )

        cv_f1.append(
            fold_f1
        )

        cv_auc.append(
            fold_auc
        )

        cv_balanced_accuracy.append(
            fold_balanced_accuracy
        )


        # ----------------------------------------------------
        # Print fold result
        # ----------------------------------------------------

        print(
            f"Accuracy            : {fold_accuracy:.4f}"
        )

        print(
            f"Precision           : {fold_precision:.4f}"
        )

        print(
            f"Sensitivity         : {fold_sensitivity:.4f}"
        )

        print(
            f"F1 Score            : {fold_f1:.4f}"
        )

        print(
            f"ROC-AUC             : {fold_auc:.4f}"
        )

        print(
            f"Balanced Accuracy   : "
            f"{fold_balanced_accuracy:.4f}"
        )


    # ========================================================
    # CV MEAN RESULTS
    # ========================================================

    cv_accuracy_mean = np.mean(
        cv_accuracy
    )

    cv_precision_mean = np.mean(
        cv_precision
    )

    cv_sensitivity_mean = np.mean(
        cv_sensitivity
    )

    cv_f1_mean = np.mean(
        cv_f1
    )

    cv_auc_mean = np.mean(
        cv_auc
    )

    cv_balanced_accuracy_mean = np.mean(
        cv_balanced_accuracy
    )


    # ========================================================
    # CROSS-VALIDATION RESULTS
    # ========================================================

    print(
        "\n================================================"
    )

    print(
        f"{model_name} - Cross-Validation (10-fold)"
    )

    print(
        "================================================"
    )

    print(
        f"Accuracy            : "
        f"{cv_accuracy_mean:.4f}"
    )

    print(
        f"Precision           : "
        f"{cv_precision_mean:.4f}"
    )

    print(
        f"Recall/Sensitivity  : "
        f"{cv_sensitivity_mean:.4f}"
    )

    print(
        f"F1 Score            : "
        f"{cv_f1_mean:.4f}"
    )

    print(
        f"ROC-AUC             : "
        f"{cv_auc_mean:.4f}"
    )

    print(
        f"Balanced Accuracy   : "
        f"{cv_balanced_accuracy_mean:.4f}"
    )


    # ========================================================
    # TRAIN FINAL MODEL ON COMPLETE TRAINING SET
    # ========================================================

    final_scaler = StandardScaler()

    X_train_final_scaled = final_scaler.fit_transform(
        X_train
    )

    X_test_final_scaled = final_scaler.transform(
        X_test
    )


    # --------------------------------------------------------
    # Create fresh final models
    # --------------------------------------------------------

    xgb, rf, hgb = create_models()


    if model_name == "XGBoost":

        final_model = xgb


    elif model_name == "Random Forest":

        final_model = rf


    elif model_name == "HistGradientBoosting":

        final_model = hgb


    elif model_name == "Voting Fusion":

        final_model = VotingClassifier(
            estimators=[
                ('xgb', xgb),
                ('rf', rf),
                ('hgb', hgb)
            ],
            voting='soft'
        )


    elif model_name == "Stacking Fusion":

        final_model = StackingClassifier(
            estimators=[
                ('xgb', xgb),
                ('rf', rf),
                ('hgb', hgb)
            ],

            final_estimator=LogisticRegression(
                max_iter=1000,
                class_weight='balanced'
            ),

            passthrough=True,

            cv=5
        )


    # ========================================================
    # FINAL TRAINING
    # ========================================================

    final_model.fit(
        X_train_final_scaled,
        y_train
    )


    # ========================================================
    # TEST PREDICTIONS
    # ========================================================

    test_preds = final_model.predict(
        X_test_final_scaled
    )

    test_probs = final_model.predict_proba(
        X_test_final_scaled
    )[:, 1]


    # ========================================================
    # TEST METRICS
    # ========================================================

    accuracy = accuracy_score(
        y_test,
        test_preds
    )

    precision = precision_score(
        y_test,
        test_preds,
        zero_division=0
    )

    sensitivity = recall_score(
        y_test,
        test_preds,
        zero_division=0
    )

    f1 = f1_score(
        y_test,
        test_preds,
        zero_division=0
    )

    roc_auc = roc_auc_score(
        y_test,
        test_probs
    )

    balanced_accuracy = balanced_accuracy_score(
        y_test,
        test_preds
    )

    mcc = matthews_corrcoef(
        y_test,
        test_preds
    )


    # ========================================================
    # CONFUSION MATRIX
    # ========================================================

    cm = confusion_matrix(
        y_test,
        test_preds,
        labels=[0, 1]
    )

    tn, fp, fn, tp = cm.ravel()


    # ========================================================
    # SENSITIVITY / SPECIFICITY
    # ========================================================

    sensitivity = (
        tp / (tp + fn)
        if (tp + fn) > 0
        else 0
    )

    specificity = (
        tn / (tn + fp)
        if (tn + fp) > 0
        else 0
    )


    # ========================================================
    # 95% CONFIDENCE INTERVALS
    # ========================================================

    # ---------------- Accuracy CI ----------------

    acc_low, acc_high = proportion_confint(
        count=int(round(accuracy * len(y_test))),
        nobs=len(y_test),
        alpha=0.05,
        method='wilson'
    )


    # ---------------- Precision CI ----------------

    precision_low, precision_high = proportion_confint(
        count=tp,
        nobs=(tp + fp),
        alpha=0.05,
        method='wilson'
    ) if (tp + fp) > 0 else (0.0, 0.0)


    # ---------------- Sensitivity CI ----------------

    sensitivity_low, sensitivity_high = proportion_confint(
        count=tp,
        nobs=(tp + fn),
        alpha=0.05,
        method='wilson'
    ) if (tp + fn) > 0 else (0.0, 0.0)


    # ---------------- Specificity CI ----------------

    specificity_low, specificity_high = proportion_confint(
        count=tn,
        nobs=(tn + fp),
        alpha=0.05,
        method='wilson'
    ) if (tn + fp) > 0 else (0.0, 0.0)


    # ========================================================
    # TEST SET PERFORMANCE
    # ========================================================

    print(
        "\n================================================"
    )

    print(
        f"{model_name} - Test Set Performance"
    )

    print(
        "================================================"
    )

    print(
        f"Accuracy            : {accuracy:.4f} "
        f"(95% CI: "
        f"{acc_low:.4f}-{acc_high:.4f})"
    )

    print(
        f"Precision           : {precision:.4f} "
        f"(95% CI: "
        f"{precision_low:.4f}-{precision_high:.4f})"
    )

    print(
        f"Sensitivity         : {sensitivity:.4f} "
        f"(95% CI: "
        f"{sensitivity_low:.4f}-{sensitivity_high:.4f})"
    )

    print(
        f"Specificity         : {specificity:.4f} "
        f"(95% CI: "
        f"{specificity_low:.4f}-{specificity_high:.4f})"
    )

    print(
        f"F1 Score            : {f1:.4f}"
    )

    print(
        f"ROC-AUC             : {roc_auc:.4f}"
    )

    print(
        f"Balanced Accuracy   : "
        f"{balanced_accuracy:.4f}"
    )

    print(
        f"MCC                 : {mcc:.4f}"
    )


    # ========================================================
    # CONFUSION MATRIX
    # ========================================================

    print(
        "\nConfusion Matrix:"
    )

    print(cm)

    print(
        "\nTN :", tn
    )

    print(
        "FP :", fp
    )

    print(
        "FN :", fn
    )

    print(
        "TP :", tp
    )


    # ========================================================
    # STORE RESULTS
    # ========================================================

    result = {

        # ---------------- CV ----------------

        "CV Accuracy":
            cv_accuracy_mean,

        "CV Precision":
            cv_precision_mean,

        "CV Sensitivity":
            cv_sensitivity_mean,

        "CV F1":
            cv_f1_mean,

        "CV ROC-AUC":
            cv_auc_mean,

        "CV Balanced Accuracy":
            cv_balanced_accuracy_mean,


        # ---------------- Test ----------------

        "Accuracy":
            accuracy,

        "Accuracy CI Low":
            acc_low,

        "Accuracy CI High":
            acc_high,


        "Precision":
            precision,

        "Precision CI Low":
            precision_low,

        "Precision CI High":
            precision_high,


        "Sensitivity":
            sensitivity,

        "Sensitivity CI Low":
            sensitivity_low,

        "Sensitivity CI High":
            sensitivity_high,


        "Specificity":
            specificity,

        "Specificity CI Low":
            specificity_low,

        "Specificity CI High":
            specificity_high,


        "F1":
            f1,

        "ROC-AUC":
            roc_auc,

        "Balanced Accuracy":
            balanced_accuracy,

        "MCC":
            mcc,


        # ---------------- Confusion Matrix ----------------

        "TN":
            tn,

        "FP":
            fp,

        "FN":
            fn,

        "TP":
            tp
    }


    return result


# ============================================================
# STEP 8: EVALUATE ALL MODELS
# ============================================================

model_names = [
    "XGBoost",
    "Random Forest",
    "HistGradientBoosting",
    "Voting Fusion",
    "Stacking Fusion"
]


results = {}

for name in model_names:

    print(
        "\n\n################################################"
    )

    print(
        f"Evaluating: {name}"
    )

    print(
        "################################################"
    )

    results[name] = evaluate_model(
        name
    )


# ============================================================
# STEP 9: FINAL RESULTS DATAFRAME
# ============================================================

results_df = pd.DataFrame(
    results
).T


# ============================================================
# STEP 10: ORDER RESULTS
# ============================================================

results_df = results_df[
    [

        # ---------------- CV ----------------

        "CV Accuracy",
        "CV Precision",
        "CV Sensitivity",
        "CV F1",
        "CV ROC-AUC",
        "CV Balanced Accuracy",


        # ---------------- Test ----------------

        "Accuracy",
        "Accuracy CI Low",
        "Accuracy CI High",

        "Precision",
        "Precision CI Low",
        "Precision CI High",

        "Sensitivity",
        "Sensitivity CI Low",
        "Sensitivity CI High",

        "Specificity",
        "Specificity CI Low",
        "Specificity CI High",

        "F1",
        "ROC-AUC",
        "Balanced Accuracy",
        "MCC",

        # ---------------- Confusion Matrix ----------------

        "TN",
        "FP",
        "FN",
        "TP"
    ]
]


# ============================================================
# STEP 11: DISPLAY FINAL RESULTS
# ============================================================

print(
    "\n================================================"
)

print(
    "FINAL MODEL COMPARISON"
)

print(
    "================================================\n"
)


display(
    results_df.sort_values(
        by="F1",
        ascending=False
    )
)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 8.0 MB/s eta 0:00:00

Class Weights:
{0: 1.2213740458015268, 1: 0.8465608465608465}

Train Shape : (256, 32)
Test Shape  : (64, 32)

Training Class Distribution:
PD_Label_Combined
1    151
0    105
Name: count, dtype: int64

Testing Class Distribution:
PD_Label_Combined
1    38
0    26
Name: count, dtype: int64

Training Class Weights:
{np.int64(0): np.float64(1.2190476190476192), np.int64(1): np.float64(0.847682119205298)}

XGBoost scale_pos_weight: 0.6953642384105959


################################################
Evaluating: XGBoost
################################################

XGBoost | Fold 1/10
Accuracy            : 0.7308
Precision           : 0.7647
Sensitivity         : 0.8125
F1 Score            : 0.7879
ROC-AUC             : 0.9000
Balanced Accuracy   : 0.7063

XGBoost | Fold 2/10
Accuracy            : 0.6154
Precision           : 0.6667
Sensitivity         : 0.6667
F1 Score            : 0.6667
ROC-AUC             : 0.7970
Balanced Accuracy   : 0.6061

XGBoost | Fold 3/10
Accuracy            : 0.9231
Precision           : 0.8824
Sensitivity         : 1.0000
F1 Score            : 0.9375
ROC-AUC             : 0.9758
Balanced Accuracy   : 0.9091

XGBoost | Fold 4/10
Accuracy            : 0.8077
Precision           : 0.8125
Sensitivity         : 0.8667
F1 Score            : 0.8387
ROC-AUC             : 0.9394
Balanced Accuracy   : 0.7970

XGBoost | Fold 5/10
Accuracy            : 0.8462
Precision           : 0.8235
Sensitivity         : 0.9333
F1 Score            : 0.8750
ROC-AUC             : 0.9636
Balanced Accuracy   : 0.8303

XGBoost | Fold 6/10
Accuracy            : 0.8462
Precision           : 0.9231
Sensitivity         : 0.8000
F1 Score            : 0.8571
ROC-AUC             : 0.9333
Balanced Accuracy   : 0.8545

XGBoost | Fold 7/10
Accuracy            : 0.8800
Precision           : 0.9286
Sensitivity         : 0.8667
F1 Score            : 0.8966
ROC-AUC             : 0.9033
Balanced Accuracy   : 0.8833

XGBoost | Fold 8/10
Accuracy            : 0.8800
Precision           : 0.9286
Sensitivity         : 0.8667
F1 Score            : 0.8966
ROC-AUC             : 0.9467
Balanced Accuracy   : 0.8833

XGBoost | Fold 9/10
Accuracy            : 0.9600
Precision           : 1.0000
Sensitivity         : 0.9333
F1 Score            : 0.9655
ROC-AUC             : 1.0000
Balanced Accuracy   : 0.9667

XGBoost | Fold 10/10
Accuracy            : 0.8800
Precision           : 1.0000
Sensitivity         : 0.8000
F1 Score            : 0.8889
ROC-AUC             : 0.9933
Balanced Accuracy   : 0.9000

================================================
XGBoost - Cross-Validation (10-fold)
================================================
Accuracy            : 0.8369
Precision           : 0.8730
Recall/Sensitivity  : 0.8546
F1 Score            : 0.8610
ROC-AUC             : 0.9352
Balanced Accuracy   : 0.8337

================================================
XGBoost - Test Set Performance
================================================
Accuracy            : 0.8125 (95% CI: 0.7003-0.8894)
Precision           : 0.8421 (95% CI: 0.6958-0.9256)
Sensitivity         : 0.8421 (95% CI: 0.6958-0.9256)
Specificity         : 0.7692 (95% CI: 0.5795-0.8897)
F1 Score            : 0.8421
ROC-AUC             : 0.9251
Balanced Accuracy   : 0.8057
MCC                 : 0.6113

Confusion Matrix:
[[20  6]
 [ 6 32]]

TN : 20
FP : 6
FN : 6
TP : 32


################################################
Evaluating: Random Forest
################################################

Random Forest | Fold 1/10
Accuracy            : 0.7692
Precision           : 0.7778
Sensitivity         : 0.8750
F1 Score            : 0.8235
ROC-AUC             : 0.8969
Balanced Accuracy   : 0.7375

Random Forest | Fold 2/10
Accuracy            : 0.6923
Precision           : 0.7059
Sensitivity         : 0.8000
F1 Score            : 0.7500
ROC-AUC             : 0.8061
Balanced Accuracy   : 0.6727

Random Forest | Fold 3/10
Accuracy            : 0.9231
Precision           : 0.8824
Sensitivity         : 1.0000
F1 Score            : 0.9375
ROC-AUC             : 0.9818
Balanced Accuracy   : 0.9091

Random Forest | Fold 4/10
Accuracy            : 0.8077
Precision           : 0.8125
Sensitivity         : 0.8667
F1 Score            : 0.8387
ROC-AUC             : 0.9212
Balanced Accuracy   : 0.7970

Random Forest | Fold 5/10
Accuracy            : 0.8462
Precision           : 0.8235
Sensitivity         : 0.9333
F1 Score            : 0.8750
ROC-AUC             : 0.9697
Balanced Accuracy   : 0.8303

Random Forest | Fold 6/10
Accuracy            : 0.8462
Precision           : 0.9231
Sensitivity         : 0.8000
F1 Score            : 0.8571
ROC-AUC             : 0.9515
Balanced Accuracy   : 0.8545

Random Forest | Fold 7/10
Accuracy            : 0.8400
Precision           : 0.8667
Sensitivity         : 0.8667
F1 Score            : 0.8667
ROC-AUC             : 0.8967
Balanced Accuracy   : 0.8333

Random Forest | Fold 8/10
Accuracy            : 0.8800
Precision           : 0.9286
Sensitivity         : 0.8667
F1 Score            : 0.8966
ROC-AUC             : 0.9600
Balanced Accuracy   : 0.8833

Random Forest | Fold 9/10
Accuracy            : 0.9600
Precision           : 1.0000
Sensitivity         : 0.9333
F1 Score            : 0.9655
ROC-AUC             : 1.0000
Balanced Accuracy   : 0.9667

Random Forest | Fold 10/10
Accuracy            : 0.8800
Precision           : 1.0000
Sensitivity         : 0.8000
F1 Score            : 0.8889
ROC-AUC             : 0.9933
Balanced Accuracy   : 0.9000

================================================
Random Forest - Cross-Validation (10-fold)
================================================
Accuracy            : 0.8445
Precision           : 0.8720
Recall/Sensitivity  : 0.8742
F1 Score            : 0.8700
ROC-AUC             : 0.9377
Balanced Accuracy   : 0.8384

================================================
Random Forest - Test Set Performance
================================================
Accuracy            : 0.8281 (95% CI: 0.7179-0.9012)
Precision           : 0.8462 (95% CI: 0.7027-0.9275)
Sensitivity         : 0.8684 (95% CI: 0.7267-0.9425)
Specificity         : 0.7692 (95% CI: 0.5795-0.8897)
F1 Score            : 0.8571
ROC-AUC             : 0.8968
Balanced Accuracy   : 0.8188
MCC                 : 0.6419

Confusion Matrix:
[[20  6]
 [ 5 33]]

TN : 20
FP : 6
FN : 5
TP : 33


################################################
Evaluating: HistGradientBoosting
################################################

HistGradientBoosting | Fold 1/10
Accuracy            : 0.7308
Precision           : 0.7647
Sensitivity         : 0.8125
F1 Score            : 0.7879
ROC-AUC             : 0.9062
Balanced Accuracy   : 0.7063

HistGradientBoosting | Fold 2/10
Accuracy            : 0.6154
Precision           : 0.6667
Sensitivity         : 0.6667
F1 Score            : 0.6667
ROC-AUC             : 0.7303
Balanced Accuracy   : 0.6061

HistGradientBoosting | Fold 3/10
Accuracy            : 0.8846
Precision           : 0.8750
Sensitivity         : 0.9333
F1 Score            : 0.9032
ROC-AUC             : 0.9636
Balanced Accuracy   : 0.8758

HistGradientBoosting | Fold 4/10
Accuracy            : 0.8846
Precision           : 0.8750
Sensitivity         : 0.9333
F1 Score            : 0.9032
ROC-AUC             : 0.9394
Balanced Accuracy   : 0.8758

HistGradientBoosting | Fold 5/10
Accuracy            : 0.8077
Precision           : 0.7778
Sensitivity         : 0.9333
F1 Score            : 0.8485
ROC-AUC             : 0.9455
Balanced Accuracy   : 0.7848

HistGradientBoosting | Fold 6/10
Accuracy            : 0.8846
Precision           : 1.0000
Sensitivity         : 0.8000
F1 Score            : 0.8889
ROC-AUC             : 0.9273
Balanced Accuracy   : 0.9000

HistGradientBoosting | Fold 7/10
Accuracy            : 0.8400
Precision           : 0.9231
Sensitivity         : 0.8000
F1 Score            : 0.8571
ROC-AUC             : 0.9100
Balanced Accuracy   : 0.8500

HistGradientBoosting | Fold 8/10
Accuracy            : 0.9200
Precision           : 0.9333
Sensitivity         : 0.9333
F1 Score            : 0.9333
ROC-AUC             : 0.9333
Balanced Accuracy   : 0.9167

HistGradientBoosting | Fold 9/10
Accuracy            : 0.9600
Precision           : 1.0000
Sensitivity         : 0.9333
F1 Score            : 0.9655
ROC-AUC             : 0.9933
Balanced Accuracy   : 0.9667

HistGradientBoosting | Fold 10/10
Accuracy            : 0.8800
Precision           : 1.0000
Sensitivity         : 0.8000
F1 Score            : 0.8889
ROC-AUC             : 0.9867
Balanced Accuracy   : 0.9000

================================================
HistGradientBoosting - Cross-Validation (10-fold)
================================================
Accuracy            : 0.8408
Precision           : 0.8816
Recall/Sensitivity  : 0.8546
F1 Score            : 0.8643
ROC-AUC             : 0.9236
Balanced Accuracy   : 0.8382

================================================
HistGradientBoosting - Test Set Performance
================================================
Accuracy            : 0.7812 (95% CI: 0.6657-0.8650)
Precision           : 0.8158 (95% CI: 0.6658-0.9078)
Sensitivity         : 0.8158 (95% CI: 0.6658-0.9078)
Specificity         : 0.7308 (95% CI: 0.5392-0.8630)
F1 Score            : 0.8158
ROC-AUC             : 0.9221
Balanced Accuracy   : 0.7733
MCC                 : 0.5466

Confusion Matrix:
[[19  7]
 [ 7 31]]

TN : 19
FP : 7
FN : 7
TP : 31


################################################
Evaluating: Voting Fusion
################################################

Voting Fusion | Fold 1/10
Accuracy            : 0.7308
Precision           : 0.7647
Sensitivity         : 0.8125
F1 Score            : 0.7879
ROC-AUC             : 0.9000
Balanced Accuracy   : 0.7063

Voting Fusion | Fold 2/10
Accuracy            : 0.6923
Precision           : 0.7333
Sensitivity         : 0.7333
F1 Score            : 0.7333
ROC-AUC             : 0.7697
Balanced Accuracy   : 0.6848

Voting Fusion | Fold 3/10
Accuracy            : 0.8846
Precision           : 0.8750
Sensitivity         : 0.9333
F1 Score            : 0.9032
ROC-AUC             : 0.9758
Balanced Accuracy   : 0.8758

Voting Fusion | Fold 4/10
Accuracy            : 0.8462
Precision           : 0.8235
Sensitivity         : 0.9333
F1 Score            : 0.8750
ROC-AUC             : 0.9394
Balanced Accuracy   : 0.8303

Voting Fusion | Fold 5/10
Accuracy            : 0.8462
Precision           : 0.8235
Sensitivity         : 0.9333
F1 Score            : 0.8750
ROC-AUC             : 0.9576
Balanced Accuracy   : 0.8303

Voting Fusion | Fold 6/10
Accuracy            : 0.8462
Precision           : 0.9231
Sensitivity         : 0.8000
F1 Score            : 0.8571
ROC-AUC             : 0.9394
Balanced Accuracy   : 0.8545

Voting Fusion | Fold 7/10
Accuracy            : 0.8800
Precision           : 0.9286
Sensitivity         : 0.8667
F1 Score            : 0.8966
ROC-AUC             : 0.8967
Balanced Accuracy   : 0.8833

Voting Fusion | Fold 8/10
Accuracy            : 0.8800
Precision           : 0.9286
Sensitivity         : 0.8667
F1 Score            : 0.8966
ROC-AUC             : 0.9667
Balanced Accuracy   : 0.8833

Voting Fusion | Fold 9/10
Accuracy            : 0.9600
Precision           : 1.0000
Sensitivity         : 0.9333
F1 Score            : 0.9655
ROC-AUC             : 1.0000
Balanced Accuracy   : 0.9667

Voting Fusion | Fold 10/10
Accuracy            : 0.8800
Precision           : 1.0000
Sensitivity         : 0.8000
F1 Score            : 0.8889
ROC-AUC             : 0.9933
Balanced Accuracy   : 0.9000

================================================
Voting Fusion - Cross-Validation (10-fold)
================================================
Accuracy            : 0.8446
Precision           : 0.8800
Recall/Sensitivity  : 0.8613
F1 Score            : 0.8679
ROC-AUC             : 0.9338
Balanced Accuracy   : 0.8415

================================================
Voting Fusion - Test Set Performance
================================================
Accuracy            : 0.7969 (95% CI: 0.6829-0.8773)
Precision           : 0.8378 (95% CI: 0.6886-0.9235)
Sensitivity         : 0.8158 (95% CI: 0.6658-0.9078)
Specificity         : 0.7692 (95% CI: 0.5795-0.8897)
F1 Score            : 0.8267
ROC-AUC             : 0.9089
Balanced Accuracy   : 0.7925
MCC                 : 0.5818

Confusion Matrix:
[[20  6]
 [ 7 31]]

TN : 20
FP : 6
FN : 7
TP : 31


################################################
Evaluating: Stacking Fusion
################################################

Stacking Fusion | Fold 1/10
Accuracy            : 0.8077
Precision           : 0.8667
Sensitivity         : 0.8125
F1 Score            : 0.8387
ROC-AUC             : 0.8938
Balanced Accuracy   : 0.8063

Stacking Fusion | Fold 2/10
Accuracy            : 0.7308
Precision           : 0.7857
Sensitivity         : 0.7333
F1 Score            : 0.7586
ROC-AUC             : 0.8424
Balanced Accuracy   : 0.7303

Stacking Fusion | Fold 3/10
Accuracy            : 0.9615
Precision           : 0.9375
Sensitivity         : 1.0000
F1 Score            : 0.9677
ROC-AUC             : 1.0000
Balanced Accuracy   : 0.9545

Stacking Fusion | Fold 4/10
Accuracy            : 0.8462
Precision           : 0.8667
Sensitivity         : 0.8667
F1 Score            : 0.8667
ROC-AUC             : 0.9455
Balanced Accuracy   : 0.8424

Stacking Fusion | Fold 5/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Stacking Fusion | Fold 6/10
Accuracy            : 0.8462
Precision           : 0.9231
Sensitivity         : 0.8000
F1 Score            : 0.8571
ROC-AUC             : 0.9394
Balanced Accuracy   : 0.8545

Stacking Fusion | Fold 7/10
Accuracy            : 0.8800
Precision           : 1.0000
Sensitivity         : 0.8000
F1 Score            : 0.8889
ROC-AUC             : 0.9300
Balanced Accuracy   : 0.9000

Stacking Fusion | Fold 8/10
Accuracy            : 0.8800
Precision           : 0.9286
Sensitivity         : 0.8667
F1 Score            : 0.8966
ROC-AUC             : 0.9667
Balanced Accuracy   : 0.8833

Stacking Fusion | Fold 9/10
Accuracy            : 0.9200
Precision           : 1.0000
Sensitivity         : 0.8667
F1 Score            : 0.9286
ROC-AUC             : 1.0000
Balanced Accuracy   : 0.9333

Stacking Fusion | Fold 10/10
Accuracy            : 0.9200
Precision           : 1.0000
Sensitivity         : 0.8667
F1 Score            : 0.9286
ROC-AUC             : 0.9667
Balanced Accuracy   : 0.9333

================================================
Stacking Fusion - Cross-Validation (10-fold)
================================================
Accuracy            : 0.8792
Precision           : 0.9308
Recall/Sensitivity  : 0.8613
F1 Score            : 0.8931
ROC-AUC             : 0.9484
Balanced Accuracy   : 0.8838

================================================
Stacking Fusion - Test Set Performance
================================================
Accuracy            : 0.8906 (95% CI: 0.7910-0.9460)
Precision           : 0.9189 (95% CI: 0.7870-0.9720)
Sensitivity         : 0.8947 (95% CI: 0.7587-0.9583)
Specificity         : 0.8846 (95% CI: 0.7102-0.9600)
F1 Score            : 0.9067
ROC-AUC             : 0.9636
Balanced Accuracy   : 0.8897
MCC                 : 0.7750

Confusion Matrix:
[[23  3]
 [ 4 34]]

TN : 23
FP : 3
FN : 4
TP : 34

================================================
FINAL MODEL COMPARISON
================================================

,CV Accuracy,CV Precision,CV Sensitivity,CV F1,CV ROC-AUC,CV Balanced Accuracy,Accuracy,Accuracy CI Low,Accuracy CI High,Precision,...,Specificity CI Low,Specificity CI High,F1,ROC-AUC,Balanced Accuracy,MCC,TN,FP,FN,TP
Stacking Fusion,0.879231,0.930820,0.861250,0.893147,0.948436,0.883807,0.890625,0.791014,0.945999,0.918919,...,0.710241,0.959968,0.906667,0.963563,0.889676,0.775050,23.0,3.0,4.0,34.0
Random Forest,0.844462,0.872036,0.874167,0.869951,0.937718,0.838447,0.828125,0.717868,0.901223,0.846154,...,0.579484,0.889662,0.857143,0.896761,0.818826,0.641889,20.0,6.0,5.0,33.0
XGBoost,0.836923,0.872997,0.854583,0.861041,0.935242,0.833655,0.812500,0.700256,0.889354,0.842105,...,0.579484,0.889662,0.842105,0.925101,0.805668,0.611336,20.0,6.0,6.0,32.0
Voting Fusion,0.844615,0.880032,0.861250,0.867909,0.933848,0.841534,0.796875,0.682864,0.877266,0.837838,...,0.579484,0.889662,0.826667,0.908907,0.792510,0.581790,20.0,6.0,7.0,31.0
HistGradientBoosting,0.840769,0.881556,0.854583,0.864325,0.923564,0.838201,0.781250,0.665672,0.864977,0.815789,...,0.539170,0.862956,0.815789,0.922065,0.773279,0.546559,19.0,7.0,7.0,31.0

**Early Fusion**

In [1]:
# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

df_acoustic_top7 = pd.read_csv('/content/drive/MyDrive/Acoustic-subject-level-dataset_top7.csv')
df_acoustic_top7 = df_acoustic_top7.drop(columns=['Participant_ID'])
print(df_acoustic_top7.shape)
print(df_acoustic_top7.head())

(193, 8)
       RPDE  Degree-voice breaks  Delta2  Delta3  Delta11  MFCC5   spread1  \
0  0.428488                  0.0     0.0     0.0      0.0    0.0 -4.239926
1  0.542488                  0.0     0.0     0.0      0.0    0.0 -4.519291
2  0.332247                  0.0     0.0     0.0      0.0    0.0 -7.226125
3  0.498593                  0.0     0.0     0.0      0.0    0.0 -5.632290
4  0.470775                  0.0     0.0     0.0      0.0    0.0 -5.523149

   Status
0       1
1       1
2       0
3       1
4       1

In [3]:
import pandas as pd

final_meg_df = pd.read_csv('/content/drive/MyDrive/final_meg-rest(par)_top7_rfc+shap_10-fold_analysis_last_column.csv')

print("Loaded data shape:", final_meg_df.shape)
print(final_meg_df.head())

Loaded data shape: (127, 8)
   ibi_cv_asym  ibi_cv_L_std  mean_burst_duration_R_std  \
0     0.002893      0.048081                   0.002407
1    -0.018062      0.085531                   0.005160
2    -0.002573      0.032173                   0.001270
3     0.001531      0.044880                   0.003106
4     0.023834      0.142267                   0.004734

   mean_burst_duration_asym  burst_dur_cv_R_std  burst_dur_cv_L_std  \
0                  0.009156            0.040693            0.055777
1                 -0.005581            0.048648            0.052883
2                  0.007325            0.030995            0.046488
3                  0.005372            0.042429            0.049082
4                  0.014897            0.044595            0.053040

   ibi_cv_R_std  PD_Label_Combined
0      0.043907                  0
1      0.086747                  0
2      0.032718                  0
3      0.044973                  1
4      0.113787                  1

In [4]:
# ============================================================
#        EARLY FUSION BASELINE (BALANCED + 32D)
#               + 5-FOLD CROSS VALIDATION
# ============================================================

import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

from imblearn.over_sampling import SMOTE

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# ============================================================
# STEP 1 — LOAD FEATURES + LABELS
# ============================================================

# Acoustic
X_acoustic = df_acoustic_top7.iloc[:, :-1].values.astype(np.float32)
y_acoustic = df_acoustic_top7.iloc[:, -1].values.astype(np.int64)

# MEG
X_meg = final_meg_df.iloc[:, :-1].values.astype(np.float32)
y_meg = final_meg_df.iloc[:, -1].values.astype(np.int64)

print("Acoustic Shape:", X_acoustic.shape)
print("MEG Shape:", X_meg.shape)

# ============================================================
# STEP 2 — NORMALIZATION
# ============================================================

scaler_acoustic = StandardScaler()
scaler_meg = StandardScaler()

X_acoustic = scaler_acoustic.fit_transform(X_acoustic)
X_meg = scaler_meg.fit_transform(X_meg)

# ============================================================
# STEP 3 — COMBINE MODALITIES
# ============================================================

X_early = np.vstack([X_acoustic, X_meg]).astype(np.float32)

y_early = np.hstack([
    y_acoustic,
    y_meg
]).astype(np.int64)

print("\nCombined Shape:", X_early.shape)
print("Combined Labels:", y_early.shape)

# ============================================================
# STEP 4 — EARLY FUSION MLP (32D LATENT)
# ============================================================

class EarlyFusionMLP(nn.Module):

    def __init__(self, input_dim):

        super().__init__()

        self.feature_extractor = nn.Sequential(

            nn.Linear(input_dim, 64),
            nn.ReLU(),
            nn.BatchNorm1d(64),
            nn.Dropout(0.3),

            nn.Linear(64, 32),
            nn.ReLU(),
            nn.BatchNorm1d(32)
        )

        self.classifier = nn.Sequential(

            nn.Dropout(0.2),

            nn.Linear(32, 2)
        )

    def forward(self, x):

        latent = self.feature_extractor(x)

        out = self.classifier(latent)

        return out, latent

# ============================================================
# STEP 5 — CROSS VALIDATION
# ============================================================

print("\n======================================")
print(" 5-FOLD CROSS VALIDATION")
print("======================================\n")

skf = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

accs = []
precs = []
recs = []
f1s = []
aucs = []

fold = 1

# ============================================================
# STEP 6 — FOLD LOOP
# ============================================================

for train_idx, test_idx in skf.split(X_early, y_early):

    X_train = X_early[train_idx]
    X_test = X_early[test_idx]

    y_train = y_early[train_idx]
    y_test = y_early[test_idx]

    # ========================================================
    # SMOTE
    # ========================================================

    smote = SMOTE(random_state=42)

    X_train, y_train = smote.fit_resample(
        X_train,
        y_train
    )

    # ========================================================
    # TENSORS
    # ========================================================

    X_train = torch.tensor(X_train).float().to(device)
    X_test = torch.tensor(X_test).float().to(device)

    y_train = torch.tensor(y_train).long().to(device)

    # ========================================================
    # MODEL
    # ========================================================

    model = EarlyFusionMLP(
        input_dim=X_early.shape[1]
    ).to(device)

    optimizer = optim.Adam(
        model.parameters(),
        lr=1e-3,
        weight_decay=1e-4
    )

    criterion = nn.CrossEntropyLoss()

    # ========================================================
    # TRAINING
    # ========================================================

    epochs = 120

    for epoch in range(epochs):

        model.train()

        optimizer.zero_grad()

        outputs, latent = model(X_train)

        loss = criterion(outputs, y_train)

        loss.backward()

        optimizer.step()

    # ========================================================
    # EVALUATION
    # ========================================================

    model.eval()

    with torch.no_grad():

        outputs, latent_test = model(X_test)

        probs = torch.softmax(
            outputs,
            dim=1
        )[:, 1].cpu().numpy()

        preds = outputs.argmax(1).cpu().numpy()

    # ========================================================
    # METRICS
    # ========================================================

    acc = accuracy_score(
        y_test,
        preds
    )

    precision = precision_score(
        y_test,
        preds
    )

    recall = recall_score(
        y_test,
        preds
    )

    f1 = f1_score(
        y_test,
        preds
    )

    auc = roc_auc_score(
        y_test,
        probs
    )

    accs.append(acc)
    precs.append(precision)
    recs.append(recall)
    f1s.append(f1)
    aucs.append(auc)

    # ========================================================
    # PRINT FOLD RESULTS
    # ========================================================

    print(f"Fold {fold}")

    print(f"Accuracy  : {acc:.4f}")
    print(f"Precision : {precision:.4f}")
    print(f"Recall    : {recall:.4f}")
    print(f"F1-Score  : {f1:.4f}")
    print(f"AUC       : {auc:.4f}")

    print()

    fold += 1

# ============================================================
# FINAL RESULTS
# ============================================================

print("\n======================================")
print(" FINAL RESULTS")
print("======================================\n")

print(f"Mean Accuracy  : {np.mean(accs)*100:.2f}%")
print(f"Mean Precision : {np.mean(precs)*100:.2f}%")
print(f"Mean Recall    : {np.mean(recs)*100:.2f}%")
print(f"Mean F1-Score  : {np.mean(f1s)*100:.2f}%")
print(f"Mean AUC       : {np.mean(aucs)*100:.2f}%")

# ============================================================
# EXTRACT 32D FEATURES
# ============================================================

with torch.no_grad():

    acoustic_tensor = torch.tensor(
        X_acoustic
    ).float().to(device)

    meg_tensor = torch.tensor(
        X_meg
    ).float().to(device)

    _, acoustic_32D = model(acoustic_tensor)

    _, meg_32D = model(meg_tensor)

acoustic_32D = acoustic_32D.cpu().numpy()
meg_32D = meg_32D.cpu().numpy()

print("\n======================================")
print(" LATENT SHAPES")
print("======================================\n")

print("Acoustic 32D Shape :", acoustic_32D.shape)
print("MEG 32D Shape      :", meg_32D.shape)

Acoustic Shape: (193, 7)
MEG Shape: (127, 7)

Combined Shape: (320, 7)
Combined Labels: (320,)

======================================
 5-FOLD CROSS VALIDATION
======================================

Fold 1
Accuracy  : 0.5938
Precision : 0.7000
Recall    : 0.5526
F1-Score  : 0.6176
AUC       : 0.7065

Fold 2
Accuracy  : 0.7031
Precision : 0.7714
Recall    : 0.7105
F1-Score  : 0.7397
AUC       : 0.8087

Fold 3
Accuracy  : 0.7031
Precision : 0.7714
Recall    : 0.7105
F1-Score  : 0.7397
AUC       : 0.8112

Fold 4
Accuracy  : 0.7969
Precision : 0.8788
Recall    : 0.7632
F1-Score  : 0.8169
AUC       : 0.8644

Fold 5
Accuracy  : 0.7812
Precision : 0.9600
Recall    : 0.6486
F1-Score  : 0.7742
AUC       : 0.8529


======================================
 FINAL RESULTS
======================================

Mean Accuracy  : 71.56%
Mean Precision : 81.63%
Mean Recall    : 67.71%
Mean F1-Score  : 73.76%
Mean AUC       : 80.87%

======================================
 LATENT SHAPES
======================================

Acoustic 32D Shape : (193, 32)
MEG 32D Shape      : (127, 32)

In [5]:
import torch

# Assuming fused_acoustic_32D and fused_meg_32D are numpy arrays of shape (7350, 32)

# Step 1: Convert numpy arrays to torch tensors (float32)
fused_acoustic_tensor = torch.from_numpy(acoustic_32D).float()
fused_meg_tensor = torch.from_numpy(meg_32D).float()

# Step 2: Concatenate row-wise (along dim=0)
fused_output_tensor = torch.cat([fused_acoustic_tensor, fused_meg_tensor], dim=0)  # Shape: (14700, 32)

# Step 3: Print shape and dtype
print(fused_output_tensor.shape)  # torch.Size([14700, 32])
print(fused_output_tensor.dtype)  # torch.float32

torch.Size([320, 32])
torch.float32

In [6]:
import torch
import numpy as np

# ------------------------
# Step 1: Extract targets correctly
# ------------------------

# Acoustic target from df_acoustic_top7 (last column)
y_acoustic = df_acoustic_top7.iloc[:, -1].values.astype(np.int32)   # (7350,)

# MEG target from final_meg_df (last column)
y_meg = final_meg_df.iloc[:, -1].values.astype(np.int32)           # (7350,)

# Convert to tensors (reshape to column)
acoustic_target_tensor = torch.tensor(y_acoustic).long().reshape(-1, 1)   # (7350, 1)
meg_target_tensor      = torch.tensor(y_meg).long().reshape(-1, 1)        # (7350, 1)

# ------------------------
# Step 2: Convert 32D latent features to tensors
# ------------------------

fused_acoustic_tensor = torch.from_numpy(acoustic_32D).float()  # (7350, 32)
fused_meg_tensor      = torch.from_numpy(meg_32D).float()       # (7350, 32)

# ------------------------
# Step 3: Attach target columns
# ------------------------

# Concatenate latent features with target
acoustic_full = torch.cat([fused_acoustic_tensor, acoustic_target_tensor.float()], dim=1)  # (7350, 65)
meg_full      = torch.cat([fused_meg_tensor,      meg_target_tensor.float()],      dim=1)  # (7350, 65)

# ------------------------
# Step 4: Concatenate both datasets
# ------------------------

fused_df = torch.cat([acoustic_full, meg_full], dim=0)  # (14700, 65)

# ------------------------
# Step 5: Separate features and labels for PyTorch
# ------------------------

X = fused_df[:, :-1].float()   # Features (32D) -> float32
y = fused_df[:, -1].long()     # Target -> int32

# ------------------------
# Step 6: Print shapes and dtypes
# ------------------------

print(f"Features shape: {X.shape}, dtype: {X.dtype}")  # (14700, 32), float32
print(f"Labels shape: {y.shape}, dtype: {y.dtype}")    # (14700,), int32

Features shape: torch.Size([320, 32]), dtype: torch.float32
Labels shape: torch.Size([320]), dtype: torch.int64

In [7]:
import torch
import pandas as pd

# fused_df shape = (14700, 33)

# Step 6: Convert fused tensor to numpy
fused_df_np = fused_df.numpy()

# Step 7: Create correct column names for 32 latent features + 1 label
feature_names = [f"feat_{i}" for i in range(32)]
feature_names.append("PD_Label_Combined")

# Step 8: Convert to DataFrame
fused_df_named = pd.DataFrame(fused_df_np, columns=feature_names)

# Step 9: Verify
print(fused_df_named.shape)
print(fused_df_named.head())
print(fused_df_named.tail())

(320, 33)
     feat_0    feat_1    feat_2    feat_3    feat_4    feat_5    feat_6  \
0  0.787601 -0.218651 -0.630598  0.982720  0.756916 -0.358014  2.059087
1  1.117629 -0.263253 -0.630598  1.351278  1.160880 -0.358014  2.726168
2  0.394909  1.164572 -0.630598  0.706102  0.963496 -0.358014  1.102115
3  1.022828  0.309351 -0.630598  1.190836  0.878951 -0.358014  2.483664
4  0.986499  0.315469 -0.630598  1.042747  0.845622 -0.358014  2.318614

     feat_7    feat_8    feat_9  ...   feat_23   feat_24   feat_25   feat_26  \
0 -0.535866 -0.442754  1.013063  ... -0.148631 -0.457484 -0.627050 -0.588157
1 -0.535866 -0.442754  1.532030  ...  0.361794 -0.457484 -0.627050 -0.873537
2  0.804543 -0.263878  0.993354  ... -0.706309  0.765729  2.269803  1.839361
3 -0.236054 -0.442754  1.510995  ... -0.485251 -0.457484 -0.246851 -0.873537
4 -0.306775 -0.442754  1.429110  ... -0.437006 -0.457484 -0.394638 -0.873537

    feat_27   feat_28   feat_29   feat_30   feat_31  PD_Label_Combined
0 -0.429518 -0.559085  0.804747 -0.018031 -0.758336                1.0
1 -0.429518 -0.559085  1.486662  0.167920 -0.758336                1.0
2 -0.429518 -0.559085 -0.269810 -0.318409 -0.758336                0.0
3 -0.429518 -0.559085  1.036788  0.221199 -0.758336                1.0
4 -0.429518 -0.559085  0.851997  0.089698 -0.758336                1.0

[5 rows x 33 columns]
       feat_0    feat_1    feat_2    feat_3    feat_4    feat_5    feat_6  \
315 -0.432143 -0.085280 -0.630598 -0.363044 -0.504779 -0.251244 -0.541923
316 -0.566386 -0.036995 -0.630598 -0.158174 -0.504779  0.066578 -0.541923
317 -0.566386 -0.123195 -0.271117 -0.118074 -0.504779 -0.358014  0.121336
318 -0.566386 -0.311333 -0.630598 -0.628395 -0.504779 -0.358014 -0.453903
319 -0.505180 -0.009076 -0.630598  0.022837 -0.222367  0.848502 -0.541923

       feat_7    feat_8    feat_9  ...   feat_23   feat_24   feat_25  \
315 -0.535866 -0.442754 -0.328052  ... -0.406801 -0.370824 -0.627050
316 -0.535866 -0.442754 -0.398892  ... -0.422086 -0.457484 -0.627050
317 -0.535866 -0.442754 -0.424937  ... -0.706309 -0.457484 -0.547748
318 -0.535866 -0.389444 -0.424937  ...  0.059111 -0.457484 -0.627050
319 -0.535866 -0.442754 -0.424937  ... -0.706309 -0.457484 -0.627050

      feat_26   feat_27   feat_28   feat_29   feat_30   feat_31  \
315  1.556989 -0.429518 -0.559085 -0.466054 -0.480276  0.947867
316  0.246402 -0.429518 -0.559085 -0.466054 -0.480276  0.842823
317 -0.394786 -0.429518 -0.559085  0.076969  0.391177  0.090667
318  1.021890 -0.429518 -0.559085 -0.466054 -0.480276  1.146409
319  0.928801 -0.429518 -0.559085 -0.466054 -0.480276 -0.251629

     PD_Label_Combined
315                0.0
316                1.0
317                0.0
318                0.0
319                1.0

[5 rows x 33 columns]

In [8]:
# Make a copy to be safe (optional)
fused_df_named_int = fused_df_named.copy()

# Convert only the last column to int
fused_df_named_int['PD_Label_Combined'] = fused_df_named_int['PD_Label_Combined'].astype(int)

# Verify
print(fused_df_named_int.dtypes)
print(fused_df_named_int.head())

feat_0               float32
feat_1               float32
feat_2               float32
feat_3               float32
feat_4               float32
feat_5               float32
feat_6               float32
feat_7               float32
feat_8               float32
feat_9               float32
feat_10              float32
feat_11              float32
feat_12              float32
feat_13              float32
feat_14              float32
feat_15              float32
feat_16              float32
feat_17              float32
feat_18              float32
feat_19              float32
feat_20              float32
feat_21              float32
feat_22              float32
feat_23              float32
feat_24              float32
feat_25              float32
feat_26              float32
feat_27              float32
feat_28              float32
feat_29              float32
feat_30              float32
feat_31              float32
PD_Label_Combined      int64
dtype: object
     feat_0    feat_1    feat_2    feat_3    feat_4    feat_5    feat_6  \
0  0.787601 -0.218651 -0.630598  0.982720  0.756916 -0.358014  2.059087
1  1.117629 -0.263253 -0.630598  1.351278  1.160880 -0.358014  2.726168
2  0.394909  1.164572 -0.630598  0.706102  0.963496 -0.358014  1.102115
3  1.022828  0.309351 -0.630598  1.190836  0.878951 -0.358014  2.483664
4  0.986499  0.315469 -0.630598  1.042747  0.845622 -0.358014  2.318614

     feat_7    feat_8    feat_9  ...   feat_23   feat_24   feat_25   feat_26  \
0 -0.535866 -0.442754  1.013063  ... -0.148631 -0.457484 -0.627050 -0.588157
1 -0.535866 -0.442754  1.532030  ...  0.361794 -0.457484 -0.627050 -0.873537
2  0.804543 -0.263878  0.993354  ... -0.706309  0.765729  2.269803  1.839361
3 -0.236054 -0.442754  1.510995  ... -0.485251 -0.457484 -0.246851 -0.873537
4 -0.306775 -0.442754  1.429110  ... -0.437006 -0.457484 -0.394638 -0.873537

    feat_27   feat_28   feat_29   feat_30   feat_31  PD_Label_Combined
0 -0.429518 -0.559085  0.804747 -0.018031 -0.758336                  1
1 -0.429518 -0.559085  1.486662  0.167920 -0.758336                  1
2 -0.429518 -0.559085 -0.269810 -0.318409 -0.758336                  0
3 -0.429518 -0.559085  1.036788  0.221199 -0.758336                  1
4 -0.429518 -0.559085  0.851997  0.089698 -0.758336                  1

[5 rows x 33 columns]

In [9]:
# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [10]:
import pandas as pd

fused_df_named_int.to_csv('/content/drive//MyDrive/Subject-level-fused-Early_fusion_MLP_frest(1)_data_5-fold_cross_validation_2.csv', index=False)

In [2]:
# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd

fused_df_named_int = pd.read_csv('/content/drive//MyDrive/Subject-level-fused-Early_fusion_MLP_frest(1)_data_5-fold_cross_validation_2.csv')
fused_df_named_int.head()

,feat_0,feat_1,feat_2,feat_3,feat_4,feat_5,feat_6,feat_7,feat_8,feat_9,...,feat_23,feat_24,feat_25,feat_26,feat_27,feat_28,feat_29,feat_30,feat_31,PD_Label_Combined
0,0.787601,-0.218651,-0.630598,0.982720,0.756916,-0.358014,2.059087,-0.535866,-0.442754,1.013063,...,-0.148631,-0.457484,-0.627050,-0.588157,-0.429519,-0.559085,0.804747,-0.018031,-0.758336,1
1,1.117629,-0.263253,-0.630598,1.351278,1.160880,-0.358014,2.726168,-0.535866,-0.442754,1.532030,...,0.361794,-0.457484,-0.627050,-0.873537,-0.429519,-0.559085,1.486662,0.167920,-0.758336,1
2,0.394909,1.164572,-0.630598,0.706102,0.963496,-0.358014,1.102115,0.804543,-0.263878,0.993354,...,-0.706310,0.765729,2.269803,1.839361,-0.429519,-0.559085,-0.269810,-0.318409,-0.758336,0
3,1.022828,0.309351,-0.630598,1.190836,0.878951,-0.358014,2.483664,-0.236054,-0.442754,1.510995,...,-0.485251,-0.457484,-0.246851,-0.873537,-0.429519,-0.559085,1.036788,0.221199,-0.758336,1
4,0.986499,0.315469,-0.630598,1.042747,0.845622,-0.358014,2.318614,-0.306775,-0.442754,1.429110,...,-0.437006,-0.457484,-0.394638,-0.873537,-0.429519,-0.559085,0.851997,0.089698,-0.758336,1

Evaluation

In [4]:
# ============================================================
# ###8)###
# ENSEMBLE CLASSIFICATION WITH STRATIFIED 10-FOLD CV
# ============================================================

# ------------------ Install Required Packages ------------------

!pip install xgboost lightgbm catboost scikit-learn statsmodels matplotlib seaborn --quiet


# ------------------ Imports ------------------

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.utils.class_weight import compute_class_weight

from sklearn.model_selection import (
    train_test_split,
    StratifiedKFold
)

from sklearn.preprocessing import StandardScaler

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    balanced_accuracy_score,
    matthews_corrcoef,
    confusion_matrix
)

from sklearn.ensemble import (
    VotingClassifier,
    StackingClassifier,
    RandomForestClassifier,
    HistGradientBoostingClassifier
)

from sklearn.linear_model import LogisticRegression

from xgboost import XGBClassifier

from statsmodels.stats.proportion import proportion_confint


# ============================================================
# STEP 1: PREPARE DATA
# ============================================================

X = fused_df_named_int[
    [f'feat_{i}' for i in range(32)]
].copy()

y = fused_df_named_int[
    "PD_Label_Combined"
].copy()


# ------------------ Convert X to numeric ------------------

X = X.apply(
    pd.to_numeric,
    errors='coerce'
)

X.fillna(
    0,
    inplace=True
)


# ============================================================
# STEP 2: CLASS WEIGHTS
# ============================================================

classes = np.unique(y)

class_weights = compute_class_weight(
    class_weight='balanced',
    classes=classes,
    y=y
)

class_weights_dict = {
    int(classes[0]): float(class_weights[0]),
    int(classes[1]): float(class_weights[1])
}

print("\nClass Weights:")
print(class_weights_dict)


# ============================================================
# STEP 3: TRAIN-TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=42
)


print("\nTrain Shape :", X_train.shape)
print("Test Shape  :", X_test.shape)

print("\nTraining Class Distribution:")
print(y_train.value_counts())

print("\nTesting Class Distribution:")
print(y_test.value_counts())


# ============================================================
# STEP 4: HANDLE CLASS IMBALANCE
# ============================================================

cw = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_train),
    y=y_train
)

cw_dict = dict(
    zip(
        np.unique(y_train),
        cw
    )
)

scale_pos_weight = (
    cw[1] / cw[0]
)

print("\nTraining Class Weights:")
print(cw_dict)

print(
    "\nXGBoost scale_pos_weight:",
    scale_pos_weight
)


# ============================================================
# STEP 5: BASE MODEL CREATION FUNCTION
# ============================================================

def create_models():

    # ---------------- XGBoost ----------------

    xgb = XGBClassifier(
        n_estimators=200,
        max_depth=4,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,

        scale_pos_weight=scale_pos_weight,

        eval_metric='logloss',

        random_state=42,
        n_jobs=-1
    )


    # ---------------- Random Forest ----------------

    rf = RandomForestClassifier(
        n_estimators=200,

        class_weight='balanced',

        random_state=42,
        n_jobs=-1
    )


    # ---------------- HistGradientBoosting ----------------

    hgb = HistGradientBoostingClassifier(
        max_iter=200,
        learning_rate=0.05,
        max_leaf_nodes=31,

        class_weight='balanced',

        random_state=42
    )


    return xgb, rf, hgb


# ============================================================
# STEP 6: STRATIFIED 10-FOLD CV
# ============================================================

skf = StratifiedKFold(
    n_splits=10,
    shuffle=True,
    random_state=42
)


# ============================================================
# STEP 7: EVALUATION FUNCTION
# ============================================================

def evaluate_model(model_name):

    # ========================================================
    # CV METRIC STORAGE
    # ========================================================

    cv_accuracy = []
    cv_precision = []
    cv_sensitivity = []
    cv_f1 = []
    cv_auc = []
    cv_balanced_accuracy = []


    # ========================================================
    # 10-FOLD STRATIFIED CROSS-VALIDATION
    # ========================================================

    for fold, (train_idx, val_idx) in enumerate(
        skf.split(X_train, y_train),
        start=1
    ):

        print(
            f"\n{model_name} | Fold {fold}/10"
        )


        # ----------------------------------------------------
        # Split fold
        # ----------------------------------------------------

        X_tr = X_train.iloc[
            train_idx
        ]

        X_val = X_train.iloc[
            val_idx
        ]

        y_tr = y_train.iloc[
            train_idx
        ]

        y_val = y_train.iloc[
            val_idx
        ]


        # ----------------------------------------------------
        # Scaling INSIDE EACH FOLD
        # ----------------------------------------------------

        scaler = StandardScaler()

        X_tr_scaled = scaler.fit_transform(
            X_tr
        )

        X_val_scaled = scaler.transform(
            X_val
        )


        # ----------------------------------------------------
        # Create FRESH models for every fold
        # ----------------------------------------------------

        xgb, rf, hgb = create_models()


        # ----------------------------------------------------
        # Select requested model
        # ----------------------------------------------------

        if model_name == "XGBoost":

            model = xgb


        elif model_name == "Random Forest":

            model = rf


        elif model_name == "HistGradientBoosting":

            model = hgb


        elif model_name == "Voting Fusion":

            model = VotingClassifier(
                estimators=[
                    ('xgb', xgb),
                    ('rf', rf),
                    ('hgb', hgb)
                ],
                voting='soft'
            )


        elif model_name == "Stacking Fusion":

            model = StackingClassifier(
                estimators=[
                    ('xgb', xgb),
                    ('rf', rf),
                    ('hgb', hgb)
                ],

                final_estimator=LogisticRegression(
                    max_iter=1000,
                    class_weight='balanced'
                ),

                passthrough=True,

                cv=5
            )


        else:

            raise ValueError(
                f"Unknown model: {model_name}"
            )


        # ----------------------------------------------------
        # Train fold
        # ----------------------------------------------------

        model.fit(
            X_tr_scaled,
            y_tr
        )


        # ----------------------------------------------------
        # Validation predictions
        # ----------------------------------------------------

        val_preds = model.predict(
            X_val_scaled
        )

        val_probs = model.predict_proba(
            X_val_scaled
        )[:, 1]


        # ----------------------------------------------------
        # Fold metrics
        # ----------------------------------------------------

        fold_accuracy = accuracy_score(
            y_val,
            val_preds
        )

        fold_precision = precision_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_sensitivity = recall_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_f1 = f1_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_auc = roc_auc_score(
            y_val,
            val_probs
        )

        fold_balanced_accuracy = balanced_accuracy_score(
            y_val,
            val_preds
        )


        # ----------------------------------------------------
        # Store fold metrics
        # ----------------------------------------------------

        cv_accuracy.append(
            fold_accuracy
        )

        cv_precision.append(
            fold_precision
        )

        cv_sensitivity.append(
            fold_sensitivity
        )

        cv_f1.append(
            fold_f1
        )

        cv_auc.append(
            fold_auc
        )

        cv_balanced_accuracy.append(
            fold_balanced_accuracy
        )


        # ----------------------------------------------------
        # Print fold result
        # ----------------------------------------------------

        print(
            f"Accuracy            : {fold_accuracy:.4f}"
        )

        print(
            f"Precision           : {fold_precision:.4f}"
        )

        print(
            f"Sensitivity         : {fold_sensitivity:.4f}"
        )

        print(
            f"F1 Score            : {fold_f1:.4f}"
        )

        print(
            f"ROC-AUC             : {fold_auc:.4f}"
        )

        print(
            f"Balanced Accuracy   : "
            f"{fold_balanced_accuracy:.4f}"
        )


    # ========================================================
    # CV MEAN RESULTS
    # ========================================================

    cv_accuracy_mean = np.mean(
        cv_accuracy
    )

    cv_precision_mean = np.mean(
        cv_precision
    )

    cv_sensitivity_mean = np.mean(
        cv_sensitivity
    )

    cv_f1_mean = np.mean(
        cv_f1
    )

    cv_auc_mean = np.mean(
        cv_auc
    )

    cv_balanced_accuracy_mean = np.mean(
        cv_balanced_accuracy
    )


    # ========================================================
    # CROSS-VALIDATION RESULTS
    # ========================================================

    print(
        "\n================================================"
    )

    print(
        f"{model_name} - Cross-Validation (10-fold)"
    )

    print(
        "================================================"
    )

    print(
        f"Accuracy            : "
        f"{cv_accuracy_mean:.4f}"
    )

    print(
        f"Precision           : "
        f"{cv_precision_mean:.4f}"
    )

    print(
        f"Recall/Sensitivity  : "
        f"{cv_sensitivity_mean:.4f}"
    )

    print(
        f"F1 Score            : "
        f"{cv_f1_mean:.4f}"
    )

    print(
        f"ROC-AUC             : "
        f"{cv_auc_mean:.4f}"
    )

    print(
        f"Balanced Accuracy   : "
        f"{cv_balanced_accuracy_mean:.4f}"
    )


    # ========================================================
    # TRAIN FINAL MODEL ON COMPLETE TRAINING SET
    # ========================================================

    final_scaler = StandardScaler()

    X_train_final_scaled = final_scaler.fit_transform(
        X_train
    )

    X_test_final_scaled = final_scaler.transform(
        X_test
    )


    # --------------------------------------------------------
    # Create fresh final models
    # --------------------------------------------------------

    xgb, rf, hgb = create_models()


    if model_name == "XGBoost":

        final_model = xgb


    elif model_name == "Random Forest":

        final_model = rf


    elif model_name == "HistGradientBoosting":

        final_model = hgb


    elif model_name == "Voting Fusion":

        final_model = VotingClassifier(
            estimators=[
                ('xgb', xgb),
                ('rf', rf),
                ('hgb', hgb)
            ],
            voting='soft'
        )


    elif model_name == "Stacking Fusion":

        final_model = StackingClassifier(
            estimators=[
                ('xgb', xgb),
                ('rf', rf),
                ('hgb', hgb)
            ],

            final_estimator=LogisticRegression(
                max_iter=1000,
                class_weight='balanced'
            ),

            passthrough=True,

            cv=5
        )


    # ========================================================
    # FINAL TRAINING
    # ========================================================

    final_model.fit(
        X_train_final_scaled,
        y_train
    )


    # ========================================================
    # TEST PREDICTIONS
    # ========================================================

    test_preds = final_model.predict(
        X_test_final_scaled
    )

    test_probs = final_model.predict_proba(
        X_test_final_scaled
    )[:, 1]


    # ========================================================
    # TEST METRICS
    # ========================================================

    accuracy = accuracy_score(
        y_test,
        test_preds
    )

    precision = precision_score(
        y_test,
        test_preds,
        zero_division=0
    )

    sensitivity = recall_score(
        y_test,
        test_preds,
        zero_division=0
    )

    f1 = f1_score(
        y_test,
        test_preds,
        zero_division=0
    )

    roc_auc = roc_auc_score(
        y_test,
        test_probs
    )

    balanced_accuracy = balanced_accuracy_score(
        y_test,
        test_preds
    )

    mcc = matthews_corrcoef(
        y_test,
        test_preds
    )


    # ========================================================
    # CONFUSION MATRIX
    # ========================================================

    cm = confusion_matrix(
        y_test,
        test_preds,
        labels=[0, 1]
    )

    tn, fp, fn, tp = cm.ravel()


    # ========================================================
    # SENSITIVITY / SPECIFICITY
    # ========================================================

    sensitivity = (
        tp / (tp + fn)
        if (tp + fn) > 0
        else 0
    )

    specificity = (
        tn / (tn + fp)
        if (tn + fp) > 0
        else 0
    )


    # ========================================================
    # 95% CONFIDENCE INTERVALS
    # ========================================================

    # ---------------- Accuracy CI ----------------

    acc_low, acc_high = proportion_confint(
        count=int(round(accuracy * len(y_test))),
        nobs=len(y_test),
        alpha=0.05,
        method='wilson'
    )


    # ---------------- Precision CI ----------------

    precision_low, precision_high = proportion_confint(
        count=tp,
        nobs=(tp + fp),
        alpha=0.05,
        method='wilson'
    ) if (tp + fp) > 0 else (0.0, 0.0)


    # ---------------- Sensitivity CI ----------------

    sensitivity_low, sensitivity_high = proportion_confint(
        count=tp,
        nobs=(tp + fn),
        alpha=0.05,
        method='wilson'
    ) if (tp + fn) > 0 else (0.0, 0.0)


    # ---------------- Specificity CI ----------------

    specificity_low, specificity_high = proportion_confint(
        count=tn,
        nobs=(tn + fp),
        alpha=0.05,
        method='wilson'
    ) if (tn + fp) > 0 else (0.0, 0.0)


    # ========================================================
    # TEST SET PERFORMANCE
    # ========================================================

    print(
        "\n================================================"
    )

    print(
        f"{model_name} - Test Set Performance"
    )

    print(
        "================================================"
    )

    print(
        f"Accuracy            : {accuracy:.4f} "
        f"(95% CI: "
        f"{acc_low:.4f}-{acc_high:.4f})"
    )

    print(
        f"Precision           : {precision:.4f} "
        f"(95% CI: "
        f"{precision_low:.4f}-{precision_high:.4f})"
    )

    print(
        f"Sensitivity         : {sensitivity:.4f} "
        f"(95% CI: "
        f"{sensitivity_low:.4f}-{sensitivity_high:.4f})"
    )

    print(
        f"Specificity         : {specificity:.4f} "
        f"(95% CI: "
        f"{specificity_low:.4f}-{specificity_high:.4f})"
    )

    print(
        f"F1 Score            : {f1:.4f}"
    )

    print(
        f"ROC-AUC             : {roc_auc:.4f}"
    )

    print(
        f"Balanced Accuracy   : "
        f"{balanced_accuracy:.4f}"
    )

    print(
        f"MCC                 : {mcc:.4f}"
    )


    # ========================================================
    # CONFUSION MATRIX
    # ========================================================

    print(
        "\nConfusion Matrix:"
    )

    print(cm)

    print(
        "\nTN :", tn
    )

    print(
        "FP :", fp
    )

    print(
        "FN :", fn
    )

    print(
        "TP :", tp
    )


    # ========================================================
    # STORE RESULTS
    # ========================================================

    result = {

        # ---------------- CV ----------------

        "CV Accuracy":
            cv_accuracy_mean,

        "CV Precision":
            cv_precision_mean,

        "CV Sensitivity":
            cv_sensitivity_mean,

        "CV F1":
            cv_f1_mean,

        "CV ROC-AUC":
            cv_auc_mean,

        "CV Balanced Accuracy":
            cv_balanced_accuracy_mean,


        # ---------------- Test ----------------

        "Accuracy":
            accuracy,

        "Accuracy CI Low":
            acc_low,

        "Accuracy CI High":
            acc_high,


        "Precision":
            precision,

        "Precision CI Low":
            precision_low,

        "Precision CI High":
            precision_high,


        "Sensitivity":
            sensitivity,

        "Sensitivity CI Low":
            sensitivity_low,

        "Sensitivity CI High":
            sensitivity_high,


        "Specificity":
            specificity,

        "Specificity CI Low":
            specificity_low,

        "Specificity CI High":
            specificity_high,


        "F1":
            f1,

        "ROC-AUC":
            roc_auc,

        "Balanced Accuracy":
            balanced_accuracy,

        "MCC":
            mcc,


        # ---------------- Confusion Matrix ----------------

        "TN":
            tn,

        "FP":
            fp,

        "FN":
            fn,

        "TP":
            tp
    }


    return result


# ============================================================
# STEP 8: EVALUATE ALL MODELS
# ============================================================

model_names = [
    "XGBoost",
    "Random Forest",
    "HistGradientBoosting",
    "Voting Fusion",
    "Stacking Fusion"
]


results = {}

for name in model_names:

    print(
        "\n\n################################################"
    )

    print(
        f"Evaluating: {name}"
    )

    print(
        "################################################"
    )

    results[name] = evaluate_model(
        name
    )


# ============================================================
# STEP 9: FINAL RESULTS DATAFRAME
# ============================================================

results_df = pd.DataFrame(
    results
).T


# ============================================================
# STEP 10: ORDER RESULTS
# ============================================================

results_df = results_df[
    [

        # ---------------- CV ----------------

        "CV Accuracy",
        "CV Precision",
        "CV Sensitivity",
        "CV F1",
        "CV ROC-AUC",
        "CV Balanced Accuracy",


        # ---------------- Test ----------------

        "Accuracy",
        "Accuracy CI Low",
        "Accuracy CI High",

        "Precision",
        "Precision CI Low",
        "Precision CI High",

        "Sensitivity",
        "Sensitivity CI Low",
        "Sensitivity CI High",

        "Specificity",
        "Specificity CI Low",
        "Specificity CI High",

        "F1",
        "ROC-AUC",
        "Balanced Accuracy",
        "MCC",

        # ---------------- Confusion Matrix ----------------

        "TN",
        "FP",
        "FN",
        "TP"
    ]
]


# ============================================================
# STEP 11: DISPLAY FINAL RESULTS
# ============================================================

print(
    "\n================================================"
)

print(
    "FINAL MODEL COMPARISON"
)

print(
    "================================================\n"
)


display(
    results_df.sort_values(
        by="F1",
        ascending=False
    )
)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 8.6 MB/s eta 0:00:00

Class Weights:
{0: 1.2213740458015268, 1: 0.8465608465608465}

Train Shape : (256, 32)
Test Shape  : (64, 32)

Training Class Distribution:
PD_Label_Combined
1    151
0    105
Name: count, dtype: int64

Testing Class Distribution:
PD_Label_Combined
1    38
0    26
Name: count, dtype: int64

Training Class Weights:
{np.int64(0): np.float64(1.2190476190476192), np.int64(1): np.float64(0.847682119205298)}

XGBoost scale_pos_weight: 0.6953642384105959


################################################
Evaluating: XGBoost
################################################

XGBoost | Fold 1/10
Accuracy            : 0.6538
Precision           : 0.6842
Sensitivity         : 0.8125
F1 Score            : 0.7429
ROC-AUC             : 0.8438
Balanced Accuracy   : 0.6062

XGBoost | Fold 2/10
Accuracy            : 0.6923
Precision           : 0.8182
Sensitivity         : 0.6000
F1 Score            : 0.6923
ROC-AUC             : 0.6970
Balanced Accuracy   : 0.7091

XGBoost | Fold 3/10
Accuracy            : 0.8077
Precision           : 0.8125
Sensitivity         : 0.8667
F1 Score            : 0.8387
ROC-AUC             : 0.8485
Balanced Accuracy   : 0.7970

XGBoost | Fold 4/10
Accuracy            : 0.6538
Precision           : 0.7500
Sensitivity         : 0.6000
F1 Score            : 0.6667
ROC-AUC             : 0.7879
Balanced Accuracy   : 0.6636

XGBoost | Fold 5/10
Accuracy            : 0.8846
Precision           : 0.9286
Sensitivity         : 0.8667
F1 Score            : 0.8966
ROC-AUC             : 0.8970
Balanced Accuracy   : 0.8879

XGBoost | Fold 6/10
Accuracy            : 0.6923
Precision           : 0.7692
Sensitivity         : 0.6667
F1 Score            : 0.7143
ROC-AUC             : 0.7515
Balanced Accuracy   : 0.6970

XGBoost | Fold 7/10
Accuracy            : 0.7600
Precision           : 0.8462
Sensitivity         : 0.7333
F1 Score            : 0.7857
ROC-AUC             : 0.8700
Balanced Accuracy   : 0.7667

XGBoost | Fold 8/10
Accuracy            : 0.7600
Precision           : 0.7368
Sensitivity         : 0.9333
F1 Score            : 0.8235
ROC-AUC             : 0.8867
Balanced Accuracy   : 0.7167

XGBoost | Fold 9/10
Accuracy            : 0.8000
Precision           : 0.9167
Sensitivity         : 0.7333
F1 Score            : 0.8148
ROC-AUC             : 0.8600
Balanced Accuracy   : 0.8167

XGBoost | Fold 10/10
Accuracy            : 0.8800
Precision           : 1.0000
Sensitivity         : 0.8000
F1 Score            : 0.8889
ROC-AUC             : 0.9467
Balanced Accuracy   : 0.9000

================================================
XGBoost - Cross-Validation (10-fold)
================================================
Accuracy            : 0.7585
Precision           : 0.8262
Recall/Sensitivity  : 0.7612
F1 Score            : 0.7864
ROC-AUC             : 0.8389
Balanced Accuracy   : 0.7561

================================================
XGBoost - Test Set Performance
================================================
Accuracy            : 0.7812 (95% CI: 0.6657-0.8650)
Precision           : 0.8000 (95% CI: 0.6524-0.8950)
Sensitivity         : 0.8421 (95% CI: 0.6958-0.9256)
Specificity         : 0.6923 (95% CI: 0.5001-0.8350)
F1 Score            : 0.8205
ROC-AUC             : 0.7915
Balanced Accuracy   : 0.7672
MCC                 : 0.5422

Confusion Matrix:
[[18  8]
 [ 6 32]]

TN : 18
FP : 8
FN : 6
TP : 32


################################################
Evaluating: Random Forest
################################################

Random Forest | Fold 1/10
Accuracy            : 0.6923
Precision           : 0.7000
Sensitivity         : 0.8750
F1 Score            : 0.7778
ROC-AUC             : 0.8188
Balanced Accuracy   : 0.6375

Random Forest | Fold 2/10
Accuracy            : 0.5769
Precision           : 0.6250
Sensitivity         : 0.6667
F1 Score            : 0.6452
ROC-AUC             : 0.6970
Balanced Accuracy   : 0.5606

Random Forest | Fold 3/10
Accuracy            : 0.8077
Precision           : 0.8125
Sensitivity         : 0.8667
F1 Score            : 0.8387
ROC-AUC             : 0.9394
Balanced Accuracy   : 0.7970

Random Forest | Fold 4/10
Accuracy            : 0.7308
Precision           : 0.9000
Sensitivity         : 0.6000
F1 Score            : 0.7200
ROC-AUC             : 0.8545
Balanced Accuracy   : 0.7545

Random Forest | Fold 5/10
Accuracy            : 0.8846
Precision           : 0.9286
Sensitivity         : 0.8667
F1 Score            : 0.8966
ROC-AUC             : 0.8727
Balanced Accuracy   : 0.8879

Random Forest | Fold 6/10
Accuracy            : 0.6923
Precision           : 0.7692
Sensitivity         : 0.6667
F1 Score            : 0.7143
ROC-AUC             : 0.7970
Balanced Accuracy   : 0.6970

Random Forest | Fold 7/10
Accuracy            : 0.7200
Precision           : 0.7857
Sensitivity         : 0.7333
F1 Score            : 0.7586
ROC-AUC             : 0.8300
Balanced Accuracy   : 0.7167

Random Forest | Fold 8/10
Accuracy            : 0.7200
Precision           : 0.7222
Sensitivity         : 0.8667
F1 Score            : 0.7879
ROC-AUC             : 0.8600
Balanced Accuracy   : 0.6833

Random Forest | Fold 9/10
Accuracy            : 0.8000
Precision           : 0.9167
Sensitivity         : 0.7333
F1 Score            : 0.8148
ROC-AUC             : 0.8533
Balanced Accuracy   : 0.8167

Random Forest | Fold 10/10
Accuracy            : 0.8400
Precision           : 0.9231
Sensitivity         : 0.8000
F1 Score            : 0.8571
ROC-AUC             : 0.9333
Balanced Accuracy   : 0.8500

================================================
Random Forest - Cross-Validation (10-fold)
================================================
Accuracy            : 0.7465
Precision           : 0.8083
Recall/Sensitivity  : 0.7675
F1 Score            : 0.7811
ROC-AUC             : 0.8456
Balanced Accuracy   : 0.7401

================================================
Random Forest - Test Set Performance
================================================
Accuracy            : 0.7188 (95% CI: 0.5987-0.8141)
Precision           : 0.7273 (95% CI: 0.5815-0.8365)
Sensitivity         : 0.8421 (95% CI: 0.6958-0.9256)
Specificity         : 0.5385 (95% CI: 0.3546-0.7124)
F1 Score            : 0.7805
ROC-AUC             : 0.7697
Balanced Accuracy   : 0.6903
MCC                 : 0.4032

Confusion Matrix:
[[14 12]
 [ 6 32]]

TN : 14
FP : 12
FN : 6
TP : 32


################################################
Evaluating: HistGradientBoosting
################################################

HistGradientBoosting | Fold 1/10
Accuracy            : 0.6923
Precision           : 0.7000
Sensitivity         : 0.8750
F1 Score            : 0.7778
ROC-AUC             : 0.8438
Balanced Accuracy   : 0.6375

HistGradientBoosting | Fold 2/10
Accuracy            : 0.6154
Precision           : 0.6667
Sensitivity         : 0.6667
F1 Score            : 0.6667
ROC-AUC             : 0.6818
Balanced Accuracy   : 0.6061

HistGradientBoosting | Fold 3/10
Accuracy            : 0.7308
Precision           : 0.7857
Sensitivity         : 0.7333
F1 Score            : 0.7586
ROC-AUC             : 0.8485
Balanced Accuracy   : 0.7303

HistGradientBoosting | Fold 4/10
Accuracy            : 0.7692
Precision           : 0.9091
Sensitivity         : 0.6667
F1 Score            : 0.7692
ROC-AUC             : 0.8424
Balanced Accuracy   : 0.7879

HistGradientBoosting | Fold 5/10
Accuracy            : 0.8077
Precision           : 0.8125
Sensitivity         : 0.8667
F1 Score            : 0.8387
ROC-AUC             : 0.8606
Balanced Accuracy   : 0.7970

HistGradientBoosting | Fold 6/10
Accuracy            : 0.6538
Precision           : 0.7143
Sensitivity         : 0.6667
F1 Score            : 0.6897
ROC-AUC             : 0.7818
Balanced Accuracy   : 0.6515

HistGradientBoosting | Fold 7/10
Accuracy            : 0.8400
Precision           : 0.8667
Sensitivity         : 0.8667
F1 Score            : 0.8667
ROC-AUC             : 0.8900
Balanced Accuracy   : 0.8333

HistGradientBoosting | Fold 8/10
Accuracy            : 0.7600
Precision           : 0.7368
Sensitivity         : 0.9333
F1 Score            : 0.8235
ROC-AUC             : 0.8867
Balanced Accuracy   : 0.7167

HistGradientBoosting | Fold 9/10
Accuracy            : 0.7600
Precision           : 0.9091
Sensitivity         : 0.6667
F1 Score            : 0.7692
ROC-AUC             : 0.8200
Balanced Accuracy   : 0.7833

HistGradientBoosting | Fold 10/10
Accuracy            : 0.8400
Precision           : 1.0000
Sensitivity         : 0.7333
F1 Score            : 0.8462
ROC-AUC             : 0.9467
Balanced Accuracy   : 0.8667

================================================
HistGradientBoosting - Cross-Validation (10-fold)
================================================
Accuracy            : 0.7469
Precision           : 0.8101
Recall/Sensitivity  : 0.7675
F1 Score            : 0.7806
ROC-AUC             : 0.8402
Balanced Accuracy   : 0.7410

================================================
HistGradientBoosting - Test Set Performance
================================================
Accuracy            : 0.7344 (95% CI: 0.6152-0.8270)
Precision           : 0.7442 (95% CI: 0.5976-0.8507)
Sensitivity         : 0.8421 (95% CI: 0.6958-0.9256)
Specificity         : 0.5769 (95% CI: 0.3895-0.7446)
F1 Score            : 0.7901
ROC-AUC             : 0.7702
Balanced Accuracy   : 0.7095
MCC                 : 0.4383

Confusion Matrix:
[[15 11]
 [ 6 32]]

TN : 15
FP : 11
FN : 6
TP : 32


################################################
Evaluating: Voting Fusion
################################################

Voting Fusion | Fold 1/10
Accuracy            : 0.6923
Precision           : 0.7000
Sensitivity         : 0.8750
F1 Score            : 0.7778
ROC-AUC             : 0.8375
Balanced Accuracy   : 0.6375

Voting Fusion | Fold 2/10
Accuracy            : 0.6538
Precision           : 0.7500
Sensitivity         : 0.6000
F1 Score            : 0.6667
ROC-AUC             : 0.7000
Balanced Accuracy   : 0.6636

Voting Fusion | Fold 3/10
Accuracy            : 0.8077
Precision           : 0.8125
Sensitivity         : 0.8667
F1 Score            : 0.8387
ROC-AUC             : 0.8424
Balanced Accuracy   : 0.7970

Voting Fusion | Fold 4/10
Accuracy            : 0.6538
Precision           : 0.8000
Sensitivity         : 0.5333
F1 Score            : 0.6400
ROC-AUC             : 0.8424
Balanced Accuracy   : 0.6758

Voting Fusion | Fold 5/10
Accuracy            : 0.8846
Precision           : 0.9286
Sensitivity         : 0.8667
F1 Score            : 0.8966
ROC-AUC             : 0.8788
Balanced Accuracy   : 0.8879

Voting Fusion | Fold 6/10
Accuracy            : 0.6538
Precision           : 0.7143
Sensitivity         : 0.6667
F1 Score            : 0.6897
ROC-AUC             : 0.7758
Balanced Accuracy   : 0.6515

Voting Fusion | Fold 7/10
Accuracy            : 0.7600
Precision           : 0.8000
Sensitivity         : 0.8000
F1 Score            : 0.8000
ROC-AUC             : 0.8567
Balanced Accuracy   : 0.7500

Voting Fusion | Fold 8/10
Accuracy            : 0.7600
Precision           : 0.7368
Sensitivity         : 0.9333
F1 Score            : 0.8235
ROC-AUC             : 0.8667
Balanced Accuracy   : 0.7167

Voting Fusion | Fold 9/10
Accuracy            : 0.8000
Precision           : 0.9167
Sensitivity         : 0.7333
F1 Score            : 0.8148
ROC-AUC             : 0.8600
Balanced Accuracy   : 0.8167

Voting Fusion | Fold 10/10
Accuracy            : 0.8800
Precision           : 1.0000
Sensitivity         : 0.8000
F1 Score            : 0.8889
ROC-AUC             : 0.9400
Balanced Accuracy   : 0.9000

================================================
Voting Fusion - Cross-Validation (10-fold)
================================================
Accuracy            : 0.7546
Precision           : 0.8159
Recall/Sensitivity  : 0.7675
F1 Score            : 0.7837
ROC-AUC             : 0.8400
Balanced Accuracy   : 0.7497

================================================
Voting Fusion - Test Set Performance
================================================
Accuracy            : 0.7344 (95% CI: 0.6152-0.8270)
Precision           : 0.7442 (95% CI: 0.5976-0.8507)
Sensitivity         : 0.8421 (95% CI: 0.6958-0.9256)
Specificity         : 0.5769 (95% CI: 0.3895-0.7446)
F1 Score            : 0.7901
ROC-AUC             : 0.7915
Balanced Accuracy   : 0.7095
MCC                 : 0.4383

Confusion Matrix:
[[15 11]
 [ 6 32]]

TN : 15
FP : 11
FN : 6
TP : 32


################################################
Evaluating: Stacking Fusion
################################################

Stacking Fusion | Fold 1/10
Accuracy            : 0.6538
Precision           : 0.7059
Sensitivity         : 0.7500
F1 Score            : 0.7273
ROC-AUC             : 0.8125
Balanced Accuracy   : 0.6250

Stacking Fusion | Fold 2/10
Accuracy            : 0.7308
Precision           : 0.7500
Sensitivity         : 0.8000
F1 Score            : 0.7742
ROC-AUC             : 0.7455
Balanced Accuracy   : 0.7182

Stacking Fusion | Fold 3/10
Accuracy            : 0.8846
Precision           : 1.0000
Sensitivity         : 0.8000
F1 Score            : 0.8889
ROC-AUC             : 0.9394
Balanced Accuracy   : 0.9000

Stacking Fusion | Fold 4/10
Accuracy            : 0.6923
Precision           : 0.8889
Sensitivity         : 0.5333
F1 Score            : 0.6667
ROC-AUC             : 0.7758
Balanced Accuracy   : 0.7212

Stacking Fusion | Fold 5/10
Accuracy            : 0.8462
Precision           : 0.9231
Sensitivity         : 0.8000
F1 Score            : 0.8571
ROC-AUC             : 0.9273
Balanced Accuracy   : 0.8545

Stacking Fusion | Fold 6/10
Accuracy            : 0.6923
Precision           : 0.8889
Sensitivity         : 0.5333
F1 Score            : 0.6667
ROC-AUC             : 0.8000
Balanced Accuracy   : 0.7212

Stacking Fusion | Fold 7/10
Accuracy            : 0.7600
Precision           : 0.9091
Sensitivity         : 0.6667
F1 Score            : 0.7692
ROC-AUC             : 0.8300
Balanced Accuracy   : 0.7833

Stacking Fusion | Fold 8/10
Accuracy            : 0.7600
Precision           : 0.8000
Sensitivity         : 0.8000
F1 Score            : 0.8000
ROC-AUC             : 0.8733
Balanced Accuracy   : 0.7500

Stacking Fusion | Fold 9/10
Accuracy            : 0.8400
Precision           : 1.0000
Sensitivity         : 0.7333
F1 Score            : 0.8462
ROC-AUC             : 1.0000
Balanced Accuracy   : 0.8667

Stacking Fusion | Fold 10/10
Accuracy            : 0.8000
Precision           : 0.9167
Sensitivity         : 0.7333
F1 Score            : 0.8148
ROC-AUC             : 0.9267
Balanced Accuracy   : 0.8167

================================================
Stacking Fusion - Cross-Validation (10-fold)
================================================
Accuracy            : 0.7660
Precision           : 0.8782
Recall/Sensitivity  : 0.7150
F1 Score            : 0.7811
ROC-AUC             : 0.8630
Balanced Accuracy   : 0.7757

================================================
Stacking Fusion - Test Set Performance
================================================
Accuracy            : 0.7656 (95% CI: 0.6487-0.8525)
Precision           : 0.8108 (95% CI: 0.6580-0.9052)
Sensitivity         : 0.7895 (95% CI: 0.6365-0.8893)
Specificity         : 0.7308 (95% CI: 0.5392-0.8630)
F1 Score            : 0.8000
ROC-AUC             : 0.8128
Balanced Accuracy   : 0.7601
MCC                 : 0.5174

Confusion Matrix:
[[19  7]
 [ 8 30]]

TN : 19
FP : 7
FN : 8
TP : 30

================================================
FINAL MODEL COMPARISON
================================================

,CV Accuracy,CV Precision,CV Sensitivity,CV F1,CV ROC-AUC,CV Balanced Accuracy,Accuracy,Accuracy CI Low,Accuracy CI High,Precision,...,Specificity CI Low,Specificity CI High,F1,ROC-AUC,Balanced Accuracy,MCC,TN,FP,FN,TP
XGBoost,0.758462,0.826236,0.76125,0.786433,0.838890,0.756080,0.781250,0.665672,0.864977,0.800000,...,0.500117,0.834987,0.820513,0.791498,0.767206,0.542150,18.0,8.0,6.0,32.0
Stacking Fusion,0.766000,0.878249,0.71500,0.781103,0.863038,0.775682,0.765625,0.648667,0.852501,0.810811,...,0.539170,0.862956,0.800000,0.812753,0.760121,0.517371,19.0,7.0,8.0,30.0
HistGradientBoosting,0.746923,0.810086,0.76750,0.780624,0.840223,0.741023,0.734375,0.615171,0.827036,0.744186,...,0.389486,0.744556,0.790123,0.770243,0.709514,0.438307,15.0,11.0,6.0,32.0
Voting Fusion,0.754615,0.815887,0.76750,0.783659,0.840023,0.749659,0.734375,0.615171,0.827036,0.744186,...,0.389486,0.744556,0.790123,0.791498,0.709514,0.438307,15.0,11.0,6.0,32.0
Random Forest,0.746462,0.808298,0.76750,0.781094,0.845602,0.740114,0.718750,0.598661,0.814066,0.727273,...,0.354579,0.712441,0.780488,0.769737,0.690283,0.403244,14.0,12.0,6.0,32.0

Vanilla DANN

In [1]:
# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

df_acoustic_top7 = pd.read_csv('/content/drive/MyDrive/Acoustic-subject-level-dataset_top7.csv')
df_acoustic_top7 = df_acoustic_top7.drop(columns=['Participant_ID'])
print(df_acoustic_top7.shape)
print(df_acoustic_top7.head())

(193, 8)
       RPDE  Degree-voice breaks  Delta2  Delta3  Delta11  MFCC5   spread1  \
0  0.428488                  0.0     0.0     0.0      0.0    0.0 -4.239926
1  0.542488                  0.0     0.0     0.0      0.0    0.0 -4.519291
2  0.332247                  0.0     0.0     0.0      0.0    0.0 -7.226125
3  0.498593                  0.0     0.0     0.0      0.0    0.0 -5.632290
4  0.470775                  0.0     0.0     0.0      0.0    0.0 -5.523149

   Status
0       1
1       1
2       0
3       1
4       1

In [3]:
import pandas as pd

final_meg_df = pd.read_csv('/content/drive/MyDrive/final_meg-rest(par)_top7_rfc+shap_10-fold_analysis_last_column.csv')

print("Loaded data shape:", final_meg_df.shape)
print(final_meg_df.head())

Loaded data shape: (127, 8)
   ibi_cv_asym  ibi_cv_L_std  mean_burst_duration_R_std  \
0     0.002893      0.048081                   0.002407
1    -0.018062      0.085531                   0.005160
2    -0.002573      0.032173                   0.001270
3     0.001531      0.044880                   0.003106
4     0.023834      0.142267                   0.004734

   mean_burst_duration_asym  burst_dur_cv_R_std  burst_dur_cv_L_std  \
0                  0.009156            0.040693            0.055777
1                 -0.005581            0.048648            0.052883
2                  0.007325            0.030995            0.046488
3                  0.005372            0.042429            0.049082
4                  0.014897            0.044595            0.053040

   ibi_cv_R_std  PD_Label_Combined
0      0.043907                  0
1      0.086747                  0
2      0.032718                  0
3      0.044973                  1
4      0.113787                  1

In [4]:
# ============================================================
#                VANILLA DANN BASELINE
#     DOMAIN + TASK ADVERSARIAL LEARNING
#          + 5-FOLD CROSS VALIDATION
# ============================================================

# ============================================================
# IMPORTS
# ============================================================

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from torch.autograd import Function

import torch.nn.functional as F

import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

# ============================================================
# LOAD DATA
# ============================================================

X_acoustic = df_acoustic_top7.iloc[:, :-1].values.astype(np.float32)
y_acoustic = df_acoustic_top7.iloc[:, -1].values.astype(np.int32)

X_meg = final_meg_df.iloc[:, :-1].values.astype(np.float32)
y_meg = final_meg_df.iloc[:, -1].values.astype(np.int32)

# ============================================================
# STANDARDIZATION
# ============================================================

scaler_acoustic = StandardScaler()
scaler_meg = StandardScaler()

X_acoustic = scaler_acoustic.fit_transform(X_acoustic)
X_meg = scaler_meg.fit_transform(X_meg)

# ============================================================
# DOMAIN LABELS
# ============================================================

domain_acoustic = np.zeros(len(X_acoustic))
domain_meg = np.ones(len(X_meg))

# ============================================================
# COMBINE DATA
# ============================================================

X_all = np.vstack([
    X_acoustic,
    X_meg
]).astype(np.float32)

task_labels = np.hstack([
    y_acoustic,
    y_meg
]).astype(np.int32)

domain_labels = np.hstack([
    domain_acoustic,
    domain_meg
]).astype(np.int32)

# ============================================================
# TENSORS
# ============================================================

X_all_tensor = torch.tensor(
    X_all
).float().to(device)

task_labels_tensor = torch.tensor(
    task_labels
).long().to(device)

domain_labels_tensor = torch.tensor(
    domain_labels
).long().to(device)

# ============================================================
# DATA LOADER
# ============================================================

dataset = TensorDataset(
    X_all_tensor,
    task_labels_tensor,
    domain_labels_tensor
)

loader = DataLoader(
    dataset,
    batch_size=128,
    shuffle=True
)

# ============================================================
# GRADIENT REVERSAL LAYER
# ============================================================

class GradReverse(Function):

    @staticmethod
    def forward(ctx, x, lambd=1.0):

        ctx.lambd = lambd

        return x.view_as(x)

    @staticmethod
    def backward(ctx, grad_output):

        return -ctx.lambd * grad_output, None

def grad_reverse(x, lambd=1.0):

    return GradReverse.apply(x, lambd)

# ============================================================
# VANILLA DANN MODEL
# ============================================================

class VanillaDANN(nn.Module):

    def __init__(
        self,
        input_dim=7,
        hidden_dim=32,
        task_classes=2,
        domain_classes=2
    ):

        super(VanillaDANN, self).__init__()

        self.feature_extractor = nn.Sequential(

            nn.Linear(input_dim, 32),
            nn.ReLU(),

            nn.Linear(32, hidden_dim),
            nn.ReLU()
        )

        self.task_classifier = nn.Sequential(

            nn.Linear(hidden_dim, 32),
            nn.ReLU(),

            nn.Linear(32, task_classes)
        )

        self.domain_classifier = nn.Sequential(

            nn.Linear(hidden_dim, 32),
            nn.ReLU(),

            nn.Linear(32, domain_classes)
        )

    def forward(self, x, lambd=1.0):

        features = self.feature_extractor(x)

        task_out = self.task_classifier(features)

        reversed_feat = grad_reverse(
            features,
            lambd
        )

        domain_out = self.domain_classifier(
            reversed_feat
        )

        return task_out, domain_out, features

# ============================================================
# MODEL
# ============================================================

model = VanillaDANN().to(device)

# ============================================================
# OPTIMIZER
# ============================================================

optimizer = optim.Adam(
    model.parameters(),
    lr=0.001
)

# ============================================================
# LOSSES
# ============================================================

task_loss_fn = nn.CrossEntropyLoss()

domain_loss_fn = nn.CrossEntropyLoss()

# ============================================================
# TRAINING
# ============================================================

epochs = 120

print("\nTraining Vanilla DANN...\n")

for epoch in range(epochs):

    model.train()

    total_loss = 0
    total_correct = 0
    total_samples = 0

    p = min(epoch / 50.0, 1.0)

    lambd = 2 / (1 + np.exp(-10 * p)) - 1

    for x_batch, y_batch, d_batch in loader:

        optimizer.zero_grad()

        task_out, domain_out, _ = model(
            x_batch,
            lambd
        )

        loss_task = task_loss_fn(
            task_out,
            y_batch
        )

        loss_domain = domain_loss_fn(
            domain_out,
            d_batch
        )

        loss = (
            loss_task +
            0.5 * loss_domain
        )

        loss.backward()

        optimizer.step()

        total_loss += loss.item()

        preds = task_out.argmax(1)

        total_correct += (
            preds == y_batch
        ).sum().item()

        total_samples += len(y_batch)

    acc = total_correct / total_samples

    print(
        f"Epoch {epoch+1}/{epochs} "
        f"| λ={lambd:.3f} "
        f"| Loss={total_loss:.4f} "
        f"| Task Acc={acc:.4f}"
    )

# ============================================================
# EXTRACT LATENT FEATURES
# ============================================================

model.eval()

with torch.no_grad():

    _, _, acoustic_latent = model(
        torch.tensor(X_acoustic).float().to(device),
        0
    )

    _, _, meg_latent = model(
        torch.tensor(X_meg).float().to(device),
        0
    )

# ============================================================
# CONVERT TO NUMPY
# ============================================================

fused_acoustic_32D = acoustic_latent.cpu().numpy()

fused_meg_32D = meg_latent.cpu().numpy()

# ============================================================
# COMBINE LATENT FEATURES
# ============================================================

X_fused = np.vstack([
    fused_acoustic_32D,
    fused_meg_32D
])

y_fused = np.hstack([
    y_acoustic,
    y_meg
])

# ============================================================
# FINAL MLP CLASSIFIER
# ============================================================

class FinalMLP(nn.Module):

    def __init__(self, input_dim=32):

        super().__init__()

        self.net = nn.Sequential(

            nn.Linear(input_dim, 64),
            nn.ReLU(),

            nn.Dropout(0.2),

            nn.Linear(64, 32),
            nn.ReLU(),

            nn.Linear(32, 2)
        )

    def forward(self, x):

        return self.net(x)

# ============================================================
# 5-FOLD CROSS VALIDATION
# ============================================================

print("\n======================================")
print(" CROSS VALIDATION RESULTS")
print("======================================\n")

skf = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

accs = []
precs = []
recs = []
f1s = []
aucs = []

fold = 1

for train_idx, test_idx in skf.split(X_fused, y_fused):

    X_train = torch.tensor(
        X_fused[train_idx]
    ).float().to(device)

    X_test = torch.tensor(
        X_fused[test_idx]
    ).float().to(device)

    y_train = torch.tensor(
        y_fused[train_idx]
    ).long().to(device)

    y_test = y_fused[test_idx]

    clf = FinalMLP().to(device)

    optimizer_clf = optim.Adam(
        clf.parameters(),
        lr=1e-3
    )

    criterion = nn.CrossEntropyLoss()

    # ========================================================
    # TRAIN CLASSIFIER
    # ========================================================

    clf.train()

    for epoch in range(80):

        optimizer_clf.zero_grad()

        outputs = clf(X_train)

        loss = criterion(
            outputs,
            y_train
        )

        loss.backward()

        optimizer_clf.step()

    # ========================================================
    # TEST
    # ========================================================

    clf.eval()

    with torch.no_grad():

        outputs = clf(X_test)

        probs = F.softmax(
            outputs,
            dim=1
        )[:, 1].cpu().numpy()

        preds = outputs.argmax(1).cpu().numpy()

    acc = accuracy_score(y_test, preds)

    prec = precision_score(y_test, preds)

    rec = recall_score(y_test, preds)

    f1 = f1_score(y_test, preds)

    auc = roc_auc_score(y_test, probs)

    accs.append(acc)
    precs.append(prec)
    recs.append(rec)
    f1s.append(f1)
    aucs.append(auc)

    print(f"Fold {fold}")

    print(f"Accuracy  : {acc:.4f}")
    print(f"Precision : {prec:.4f}")
    print(f"Recall    : {rec:.4f}")
    print(f"F1-Score  : {f1:.4f}")
    print(f"AUC       : {auc:.4f}")

    print()

    fold += 1

# ============================================================
# FINAL RESULTS
# ============================================================

print("\n======================================")
print(" FINAL RESULTS")
print("======================================\n")

print(f"Mean Accuracy  : {np.mean(accs)*100:.2f}%")
print(f"Mean Precision : {np.mean(precs)*100:.2f}%")
print(f"Mean Recall    : {np.mean(recs)*100:.2f}%")
print(f"Mean F1-Score  : {np.mean(f1s)*100:.2f}%")
print(f"Mean AUC       : {np.mean(aucs)*100:.2f}%")

# ============================================================
# LATENT SHAPES
# ============================================================

print("\n===================================")
print(" LATENT FEATURE SHAPES")
print("===================================\n")

print(
    f"Acoustic Latent Shape: "
    f"{fused_acoustic_32D.shape}"
)

print(
    f"MEG Latent Shape: "
    f"{fused_meg_32D.shape}"
)

Training Vanilla DANN...

Epoch 1/120 | λ=0.000 | Loss=3.0778 | Task Acc=0.5875
Epoch 2/120 | λ=0.100 | Loss=3.0387 | Task Acc=0.6125
Epoch 3/120 | λ=0.197 | Loss=3.0022 | Task Acc=0.5750
Epoch 4/120 | λ=0.291 | Loss=2.9768 | Task Acc=0.5906
Epoch 5/120 | λ=0.380 | Loss=2.9328 | Task Acc=0.5906
Epoch 6/120 | λ=0.462 | Loss=2.9103 | Task Acc=0.5906
Epoch 7/120 | λ=0.537 | Loss=2.8751 | Task Acc=0.5906
Epoch 8/120 | λ=0.604 | Loss=2.8561 | Task Acc=0.5906
Epoch 9/120 | λ=0.664 | Loss=2.8343 | Task Acc=0.5938
Epoch 10/120 | λ=0.716 | Loss=2.8236 | Task Acc=0.5938
Epoch 11/120 | λ=0.762 | Loss=2.7775 | Task Acc=0.5938
Epoch 12/120 | λ=0.800 | Loss=2.8033 | Task Acc=0.6062
Epoch 13/120 | λ=0.834 | Loss=2.7719 | Task Acc=0.6406
Epoch 14/120 | λ=0.862 | Loss=2.7788 | Task Acc=0.6438
Epoch 15/120 | λ=0.885 | Loss=2.7339 | Task Acc=0.6312
Epoch 16/120 | λ=0.905 | Loss=2.7203 | Task Acc=0.6375
Epoch 17/120 | λ=0.922 | Loss=2.7108 | Task Acc=0.6188
Epoch 18/120 | λ=0.935 | Loss=2.7214 | Task Acc=0.6281
Epoch 19/120 | λ=0.947 | Loss=2.7026 | Task Acc=0.6250
Epoch 20/120 | λ=0.956 | Loss=2.6951 | Task Acc=0.6281
Epoch 21/120 | λ=0.964 | Loss=2.6597 | Task Acc=0.6312
Epoch 22/120 | λ=0.970 | Loss=2.6710 | Task Acc=0.6375
Epoch 23/120 | λ=0.976 | Loss=2.6568 | Task Acc=0.6312
Epoch 24/120 | λ=0.980 | Loss=2.6352 | Task Acc=0.6344
Epoch 25/120 | λ=0.984 | Loss=2.6664 | Task Acc=0.6406
Epoch 26/120 | λ=0.987 | Loss=2.6315 | Task Acc=0.6406
Epoch 27/120 | λ=0.989 | Loss=2.6935 | Task Acc=0.6406
Epoch 28/120 | λ=0.991 | Loss=2.6579 | Task Acc=0.6500
Epoch 29/120 | λ=0.993 | Loss=2.6379 | Task Acc=0.6562
Epoch 30/120 | λ=0.994 | Loss=2.7050 | Task Acc=0.6687
Epoch 31/120 | λ=0.995 | Loss=2.6798 | Task Acc=0.6906
Epoch 32/120 | λ=0.996 | Loss=2.6644 | Task Acc=0.6937
Epoch 33/120 | λ=0.997 | Loss=2.6746 | Task Acc=0.7031
Epoch 34/120 | λ=0.997 | Loss=2.6850 | Task Acc=0.7000
Epoch 35/120 | λ=0.998 | Loss=2.6401 | Task Acc=0.6969
Epoch 36/120 | λ=0.998 | Loss=2.6665 | Task Acc=0.6969
Epoch 37/120 | λ=0.999 | Loss=2.6247 | Task Acc=0.6937
Epoch 38/120 | λ=0.999 | Loss=2.6384 | Task Acc=0.6969
Epoch 39/120 | λ=0.999 | Loss=2.6235 | Task Acc=0.6906
Epoch 40/120 | λ=0.999 | Loss=2.5920 | Task Acc=0.6906
Epoch 41/120 | λ=0.999 | Loss=2.5497 | Task Acc=0.6875
Epoch 42/120 | λ=0.999 | Loss=2.5472 | Task Acc=0.6875
Epoch 43/120 | λ=1.000 | Loss=2.5726 | Task Acc=0.7000
Epoch 44/120 | λ=1.000 | Loss=2.5377 | Task Acc=0.7031
Epoch 45/120 | λ=1.000 | Loss=2.5227 | Task Acc=0.7125
Epoch 46/120 | λ=1.000 | Loss=2.5031 | Task Acc=0.7156
Epoch 47/120 | λ=1.000 | Loss=2.5714 | Task Acc=0.7094
Epoch 48/120 | λ=1.000 | Loss=2.5218 | Task Acc=0.7188
Epoch 49/120 | λ=1.000 | Loss=2.4629 | Task Acc=0.7156
Epoch 50/120 | λ=1.000 | Loss=2.4931 | Task Acc=0.7188
Epoch 51/120 | λ=1.000 | Loss=2.4943 | Task Acc=0.7219
Epoch 52/120 | λ=1.000 | Loss=2.4407 | Task Acc=0.7344
Epoch 53/120 | λ=1.000 | Loss=2.4134 | Task Acc=0.7406
Epoch 54/120 | λ=1.000 | Loss=2.3947 | Task Acc=0.7594
Epoch 55/120 | λ=1.000 | Loss=2.4545 | Task Acc=0.7469
Epoch 56/120 | λ=1.000 | Loss=2.4158 | Task Acc=0.7312
Epoch 57/120 | λ=1.000 | Loss=2.3671 | Task Acc=0.7250
Epoch 58/120 | λ=1.000 | Loss=2.4065 | Task Acc=0.7281
Epoch 59/120 | λ=1.000 | Loss=2.4280 | Task Acc=0.7312
Epoch 60/120 | λ=1.000 | Loss=2.3914 | Task Acc=0.7438
Epoch 61/120 | λ=1.000 | Loss=2.4282 | Task Acc=0.7594
Epoch 62/120 | λ=1.000 | Loss=2.4014 | Task Acc=0.7562
Epoch 63/120 | λ=1.000 | Loss=2.3979 | Task Acc=0.7594
Epoch 64/120 | λ=1.000 | Loss=2.3829 | Task Acc=0.7500
Epoch 65/120 | λ=1.000 | Loss=2.4004 | Task Acc=0.7625
Epoch 66/120 | λ=1.000 | Loss=2.3523 | Task Acc=0.7656
Epoch 67/120 | λ=1.000 | Loss=2.3554 | Task Acc=0.7656
Epoch 68/120 | λ=1.000 | Loss=2.3573 | Task Acc=0.7562
Epoch 69/120 | λ=1.000 | Loss=2.4351 | Task Acc=0.7594
Epoch 70/120 | λ=1.000 | Loss=2.3859 | Task Acc=0.7688
Epoch 71/120 | λ=1.000 | Loss=2.3614 | Task Acc=0.7719
Epoch 72/120 | λ=1.000 | Loss=2.3338 | Task Acc=0.7719
Epoch 73/120 | λ=1.000 | Loss=2.3679 | Task Acc=0.7688
Epoch 74/120 | λ=1.000 | Loss=2.3364 | Task Acc=0.7656
Epoch 75/120 | λ=1.000 | Loss=2.3122 | Task Acc=0.7688
Epoch 76/120 | λ=1.000 | Loss=2.3468 | Task Acc=0.7719
Epoch 77/120 | λ=1.000 | Loss=2.3359 | Task Acc=0.7750
Epoch 78/120 | λ=1.000 | Loss=2.2894 | Task Acc=0.7719
Epoch 79/120 | λ=1.000 | Loss=2.2939 | Task Acc=0.7781
Epoch 80/120 | λ=1.000 | Loss=2.3069 | Task Acc=0.7781
Epoch 81/120 | λ=1.000 | Loss=2.3681 | Task Acc=0.7688
Epoch 82/120 | λ=1.000 | Loss=2.3253 | Task Acc=0.7625
Epoch 83/120 | λ=1.000 | Loss=2.2508 | Task Acc=0.7750
Epoch 84/120 | λ=1.000 | Loss=2.2816 | Task Acc=0.7844
Epoch 85/120 | λ=1.000 | Loss=2.3170 | Task Acc=0.7844
Epoch 86/120 | λ=1.000 | Loss=2.2701 | Task Acc=0.8000
Epoch 87/120 | λ=1.000 | Loss=2.2686 | Task Acc=0.7906
Epoch 88/120 | λ=1.000 | Loss=2.2760 | Task Acc=0.7781
Epoch 89/120 | λ=1.000 | Loss=2.2845 | Task Acc=0.7844
Epoch 90/120 | λ=1.000 | Loss=2.2321 | Task Acc=0.7844
Epoch 91/120 | λ=1.000 | Loss=2.2696 | Task Acc=0.7875
Epoch 92/120 | λ=1.000 | Loss=2.2707 | Task Acc=0.7969
Epoch 93/120 | λ=1.000 | Loss=2.2743 | Task Acc=0.7906
Epoch 94/120 | λ=1.000 | Loss=2.2341 | Task Acc=0.7906
Epoch 95/120 | λ=1.000 | Loss=2.2351 | Task Acc=0.7875
Epoch 96/120 | λ=1.000 | Loss=2.2643 | Task Acc=0.7844
Epoch 97/120 | λ=1.000 | Loss=2.1654 | Task Acc=0.7906
Epoch 98/120 | λ=1.000 | Loss=2.1809 | Task Acc=0.7969
Epoch 99/120 | λ=1.000 | Loss=2.1989 | Task Acc=0.7812
Epoch 100/120 | λ=1.000 | Loss=2.1543 | Task Acc=0.7875
Epoch 101/120 | λ=1.000 | Loss=2.2504 | Task Acc=0.7844
Epoch 102/120 | λ=1.000 | Loss=2.1712 | Task Acc=0.7875
Epoch 103/120 | λ=1.000 | Loss=2.1841 | Task Acc=0.7875
Epoch 104/120 | λ=1.000 | Loss=2.2120 | Task Acc=0.7812
Epoch 105/120 | λ=1.000 | Loss=2.2167 | Task Acc=0.8031
Epoch 106/120 | λ=1.000 | Loss=2.2264 | Task Acc=0.7906
Epoch 107/120 | λ=1.000 | Loss=2.1856 | Task Acc=0.7812
Epoch 108/120 | λ=1.000 | Loss=2.1871 | Task Acc=0.7875
Epoch 109/120 | λ=1.000 | Loss=2.1923 | Task Acc=0.7937
Epoch 110/120 | λ=1.000 | Loss=2.2090 | Task Acc=0.7906
Epoch 111/120 | λ=1.000 | Loss=2.1747 | Task Acc=0.8063
Epoch 112/120 | λ=1.000 | Loss=2.1788 | Task Acc=0.8031
Epoch 113/120 | λ=1.000 | Loss=2.2002 | Task Acc=0.7937
Epoch 114/120 | λ=1.000 | Loss=2.2086 | Task Acc=0.7906
Epoch 115/120 | λ=1.000 | Loss=2.2167 | Task Acc=0.8031
Epoch 116/120 | λ=1.000 | Loss=2.1614 | Task Acc=0.7906
Epoch 117/120 | λ=1.000 | Loss=2.1148 | Task Acc=0.7812
Epoch 118/120 | λ=1.000 | Loss=2.1394 | Task Acc=0.7937
Epoch 119/120 | λ=1.000 | Loss=2.0826 | Task Acc=0.7844
Epoch 120/120 | λ=1.000 | Loss=2.1041 | Task Acc=0.7906

======================================
 CROSS VALIDATION RESULTS
======================================

Fold 1
Accuracy  : 0.7344
Precision : 0.8000
Recall    : 0.7368
F1-Score  : 0.7671
AUC       : 0.7672

Fold 2
Accuracy  : 0.7500
Precision : 0.7619
Recall    : 0.8421
F1-Score  : 0.8000
AUC       : 0.8451

Fold 3
Accuracy  : 0.7656
Precision : 0.7805
Recall    : 0.8421
F1-Score  : 0.8101
AUC       : 0.8740

Fold 4
Accuracy  : 0.8281
Precision : 0.8649
Recall    : 0.8421
F1-Score  : 0.8533
AUC       : 0.8826

Fold 5
Accuracy  : 0.8594
Precision : 0.9667
Recall    : 0.7838
F1-Score  : 0.8657
AUC       : 0.8829


======================================
 FINAL RESULTS
======================================

Mean Accuracy  : 78.75%
Mean Precision : 83.48%
Mean Recall    : 80.94%
Mean F1-Score  : 81.93%
Mean AUC       : 85.04%

===================================
 LATENT FEATURE SHAPES
===================================

Acoustic Latent Shape: (193, 32)
MEG Latent Shape: (127, 32)

In [5]:
import torch

# Assuming fused_acoustic_32D and fused_meg_32D are numpy arrays of shape (7350, 32)

# Step 1: Convert numpy arrays to torch tensors (float32)
fused_acoustic_tensor = torch.from_numpy(fused_acoustic_32D).float()
fused_meg_tensor = torch.from_numpy(fused_meg_32D).float()

# Step 2: Concatenate row-wise (along dim=0)
fused_output_tensor = torch.cat([fused_acoustic_tensor, fused_meg_tensor], dim=0)  # Shape: (14700, 32)

# Step 3: Print shape and dtype
print(fused_output_tensor.shape)  # torch.Size([14700, 32])
print(fused_output_tensor.dtype)  # torch.float32

torch.Size([320, 32])
torch.float32

In [6]:
import torch
import numpy as np

# ------------------------
# Step 1: Extract targets correctly
# ------------------------

# Acoustic target from df_acoustic_top7 (last column)
y_acoustic = df_acoustic_top7.iloc[:, -1].values.astype(np.int32)   # (7350,)

# MEG target from final_meg_df (last column)
y_meg = final_meg_df.iloc[:, -1].values.astype(np.int32)           # (7350,)

# Convert to tensors (reshape to column)
acoustic_target_tensor = torch.tensor(y_acoustic).long().reshape(-1, 1)   # (7350, 1)
meg_target_tensor      = torch.tensor(y_meg).long().reshape(-1, 1)        # (7350, 1)

# ------------------------
# Step 2: Convert 32D latent features to tensors
# ------------------------

fused_acoustic_tensor = torch.from_numpy(fused_acoustic_32D).float()  # (7350, 32)
fused_meg_tensor      = torch.from_numpy(fused_meg_32D).float()       # (7350, 32)

# ------------------------
# Step 3: Attach target columns
# ------------------------

# Concatenate latent features with target
acoustic_full = torch.cat([fused_acoustic_tensor, acoustic_target_tensor.float()], dim=1)  # (7350, 65)
meg_full      = torch.cat([fused_meg_tensor,      meg_target_tensor.float()],      dim=1)  # (7350, 65)

# ------------------------
# Step 4: Concatenate both datasets
# ------------------------

fused_df = torch.cat([acoustic_full, meg_full], dim=0)  # (14700, 65)

# ------------------------
# Step 5: Separate features and labels for PyTorch
# ------------------------

X = fused_df[:, :-1].float()   # Features (32D) -> float32
y = fused_df[:, -1].long()     # Target -> int32

# ------------------------
# Step 6: Print shapes and dtypes
# ------------------------

print(f"Features shape: {X.shape}, dtype: {X.dtype}")  # (14700, 32), float32
print(f"Labels shape: {y.shape}, dtype: {y.dtype}")    # (14700,), int32

Features shape: torch.Size([320, 32]), dtype: torch.float32
Labels shape: torch.Size([320]), dtype: torch.int64

In [7]:
import torch
import pandas as pd

# fused_df shape = (14700, 33)

# Step 6: Convert fused tensor to numpy
fused_df_np = fused_df.numpy()

# Step 7: Create correct column names for 32 latent features + 1 label
feature_names = [f"feat_{i}" for i in range(32)]
feature_names.append("PD_Label_Combined")

# Step 8: Convert to DataFrame
fused_df_named = pd.DataFrame(fused_df_np, columns=feature_names)

# Step 9: Verify
print(fused_df_named.shape)
print(fused_df_named.head())
print(fused_df_named.tail())

(320, 33)
     feat_0    feat_1  feat_2  feat_3  feat_4  feat_5    feat_6    feat_7  \
0  0.435749  0.065489     0.0     0.0     0.0     0.0  0.000000  0.706785
1  0.535737  0.173545     0.0     0.0     0.0     0.0  0.033903  0.820567
2  0.135576  0.000000     0.0     0.0     0.0     0.0  0.105527  0.698564
3  0.406749  0.000000     0.0     0.0     0.0     0.0  0.056985  0.781687
4  0.387907  0.000000     0.0     0.0     0.0     0.0  0.026205  0.750198

   feat_8  feat_9  ...   feat_23   feat_24   feat_25  feat_26   feat_27  \
0     0.0     0.0  ...  0.000000  0.020852  0.000000      0.0  0.545818
1     0.0     0.0  ...  0.163953  0.276760  0.019176      0.0  0.642769
2     0.0     0.0  ...  0.000000  0.000000  0.000000      0.0  0.871915
3     0.0     0.0  ...  0.054859  0.021825  0.000000      0.0  0.732781
4     0.0     0.0  ...  0.008782  0.000000  0.000000      0.0  0.698132

    feat_28   feat_29   feat_30   feat_31  PD_Label_Combined
0  0.247931  0.830861  0.913916  0.073765                1.0
1  0.306917  0.964458  0.941762  0.000000                1.0
2  0.104835  0.714571  0.944696  0.218468                0.0
3  0.215230  0.892646  0.932902  0.090508                1.0
4  0.208451  0.859715  0.933993  0.102556                1.0

[5 rows x 33 columns]
       feat_0    feat_1  feat_2    feat_3  feat_4  feat_5    feat_6    feat_7  \
315  0.209188  0.000000     0.0  0.000000     0.0     0.0  0.000000  0.231208
316  0.250661  0.000000     0.0  0.000000     0.0     0.0  0.000000  0.499981
317  0.364395  0.488394     0.0  0.172896     0.0     0.0  0.061090  0.482965
318  0.230231  0.220282     0.0  0.099551     0.0     0.0  0.040482  0.271249
319  0.227305  0.000000     0.0  0.000000     0.0     0.0  0.000000  0.418599

     feat_8  feat_9  ...   feat_23   feat_24   feat_25   feat_26   feat_27  \
315     0.0     0.0  ...  0.000000  0.000000  0.000000  0.019401  0.233257
316     0.0     0.0  ...  0.000000  0.000000  0.000000  0.001941  0.066927
317     0.0     0.0  ...  0.294386  0.338036  0.101236  0.000000  0.586610
318     0.0     0.0  ...  0.030157  0.084437  0.000000  0.000000  0.402332
319     0.0     0.0  ...  0.000000  0.000000  0.000000  0.000000  0.079804

      feat_28   feat_29   feat_30   feat_31  PD_Label_Combined
315  0.144183  0.322131  0.374925  0.339206                0.0
316  0.015383  0.398571  0.431218  0.237465                1.0
317  0.326991  0.666251  0.472662  0.030119                0.0
318  0.218805  0.378191  0.329325  0.249352                0.0
319  0.051366  0.400243  0.490303  0.266024                1.0

[5 rows x 33 columns]

In [8]:
# Make a copy to be safe (optional)
fused_df_named_int = fused_df_named.copy()

# Convert only the last column to int
fused_df_named_int['PD_Label_Combined'] = fused_df_named_int['PD_Label_Combined'].astype(int)

# Verify
print(fused_df_named_int.dtypes)
print(fused_df_named_int.head())

feat_0               float32
feat_1               float32
feat_2               float32
feat_3               float32
feat_4               float32
feat_5               float32
feat_6               float32
feat_7               float32
feat_8               float32
feat_9               float32
feat_10              float32
feat_11              float32
feat_12              float32
feat_13              float32
feat_14              float32
feat_15              float32
feat_16              float32
feat_17              float32
feat_18              float32
feat_19              float32
feat_20              float32
feat_21              float32
feat_22              float32
feat_23              float32
feat_24              float32
feat_25              float32
feat_26              float32
feat_27              float32
feat_28              float32
feat_29              float32
feat_30              float32
feat_31              float32
PD_Label_Combined      int64
dtype: object
     feat_0    feat_1  feat_2  feat_3  feat_4  feat_5    feat_6    feat_7  \
0  0.435749  0.065489     0.0     0.0     0.0     0.0  0.000000  0.706785
1  0.535737  0.173545     0.0     0.0     0.0     0.0  0.033903  0.820567
2  0.135576  0.000000     0.0     0.0     0.0     0.0  0.105527  0.698564
3  0.406749  0.000000     0.0     0.0     0.0     0.0  0.056985  0.781687
4  0.387907  0.000000     0.0     0.0     0.0     0.0  0.026205  0.750198

   feat_8  feat_9  ...   feat_23   feat_24   feat_25  feat_26   feat_27  \
0     0.0     0.0  ...  0.000000  0.020852  0.000000      0.0  0.545818
1     0.0     0.0  ...  0.163953  0.276760  0.019176      0.0  0.642769
2     0.0     0.0  ...  0.000000  0.000000  0.000000      0.0  0.871915
3     0.0     0.0  ...  0.054859  0.021825  0.000000      0.0  0.732781
4     0.0     0.0  ...  0.008782  0.000000  0.000000      0.0  0.698132

    feat_28   feat_29   feat_30   feat_31  PD_Label_Combined
0  0.247931  0.830861  0.913916  0.073765                  1
1  0.306917  0.964458  0.941762  0.000000                  1
2  0.104835  0.714571  0.944696  0.218468                  0
3  0.215230  0.892646  0.932902  0.090508                  1
4  0.208451  0.859715  0.933993  0.102556                  1

[5 rows x 33 columns]

In [9]:
# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [10]:
import pandas as pd

fused_df_named_int.to_csv('/content/drive//MyDrive/Subject-level-fused_df_Vanilla_DANN_frest_data_5-fold_cross_validation.csv', index=False)

In [1]:
# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

fused_df_named_int = pd.read_csv('/content/drive//MyDrive/Subject-level-fused_df_Vanilla_DANN_frest_data_5-fold_cross_validation.csv')
fused_df_named_int.head()

,feat_0,feat_1,feat_2,feat_3,feat_4,feat_5,feat_6,feat_7,feat_8,feat_9,...,feat_23,feat_24,feat_25,feat_26,feat_27,feat_28,feat_29,feat_30,feat_31,PD_Label_Combined
0,0.435749,0.065489,0.0,0.0,0.0,0.0,0.000000,0.706785,0.0,0.0,...,0.000000,0.020852,0.000000,0.0,0.545818,0.247931,0.830861,0.913915,0.073765,1
1,0.535737,0.173545,0.0,0.0,0.0,0.0,0.033903,0.820567,0.0,0.0,...,0.163953,0.276759,0.019176,0.0,0.642769,0.306917,0.964458,0.941762,0.000000,1
2,0.135576,0.000000,0.0,0.0,0.0,0.0,0.105527,0.698564,0.0,0.0,...,0.000000,0.000000,0.000000,0.0,0.871915,0.104835,0.714571,0.944696,0.218468,0
3,0.406749,0.000000,0.0,0.0,0.0,0.0,0.056985,0.781687,0.0,0.0,...,0.054859,0.021825,0.000000,0.0,0.732781,0.215230,0.892646,0.932902,0.090508,1
4,0.387907,0.000000,0.0,0.0,0.0,0.0,0.026205,0.750198,0.0,0.0,...,0.008782,0.000000,0.000000,0.0,0.698132,0.208451,0.859715,0.933993,0.102556,1

Evaluation

In [3]:
# ============================================================
# ###8)###
# ENSEMBLE CLASSIFICATION WITH STRATIFIED 10-FOLD CV
# ============================================================

# ------------------ Install Required Packages ------------------

!pip install xgboost lightgbm catboost scikit-learn statsmodels matplotlib seaborn --quiet


# ------------------ Imports ------------------

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.utils.class_weight import compute_class_weight

from sklearn.model_selection import (
    train_test_split,
    StratifiedKFold
)

from sklearn.preprocessing import StandardScaler

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    balanced_accuracy_score,
    matthews_corrcoef,
    confusion_matrix
)

from sklearn.ensemble import (
    VotingClassifier,
    StackingClassifier,
    RandomForestClassifier,
    HistGradientBoostingClassifier
)

from sklearn.linear_model import LogisticRegression

from xgboost import XGBClassifier

from statsmodels.stats.proportion import proportion_confint


# ============================================================
# STEP 1: PREPARE DATA
# ============================================================

X = fused_df_named_int[
    [f'feat_{i}' for i in range(32)]
].copy()

y = fused_df_named_int[
    "PD_Label_Combined"
].copy()


# ------------------ Convert X to numeric ------------------

X = X.apply(
    pd.to_numeric,
    errors='coerce'
)

X.fillna(
    0,
    inplace=True
)


# ============================================================
# STEP 2: CLASS WEIGHTS
# ============================================================

classes = np.unique(y)

class_weights = compute_class_weight(
    class_weight='balanced',
    classes=classes,
    y=y
)

class_weights_dict = {
    int(classes[0]): float(class_weights[0]),
    int(classes[1]): float(class_weights[1])
}

print("\nClass Weights:")
print(class_weights_dict)


# ============================================================
# STEP 3: TRAIN-TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=42
)


print("\nTrain Shape :", X_train.shape)
print("Test Shape  :", X_test.shape)

print("\nTraining Class Distribution:")
print(y_train.value_counts())

print("\nTesting Class Distribution:")
print(y_test.value_counts())


# ============================================================
# STEP 4: HANDLE CLASS IMBALANCE
# ============================================================

cw = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_train),
    y=y_train
)

cw_dict = dict(
    zip(
        np.unique(y_train),
        cw
    )
)

scale_pos_weight = (
    cw[1] / cw[0]
)

print("\nTraining Class Weights:")
print(cw_dict)

print(
    "\nXGBoost scale_pos_weight:",
    scale_pos_weight
)


# ============================================================
# STEP 5: BASE MODEL CREATION FUNCTION
# ============================================================

def create_models():

    # ---------------- XGBoost ----------------

    xgb = XGBClassifier(
        n_estimators=200,
        max_depth=4,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,

        scale_pos_weight=scale_pos_weight,

        eval_metric='logloss',

        random_state=42,
        n_jobs=-1
    )


    # ---------------- Random Forest ----------------

    rf = RandomForestClassifier(
        n_estimators=200,

        class_weight='balanced',

        random_state=42,
        n_jobs=-1
    )


    # ---------------- HistGradientBoosting ----------------

    hgb = HistGradientBoostingClassifier(
        max_iter=200,
        learning_rate=0.05,
        max_leaf_nodes=31,

        class_weight='balanced',

        random_state=42
    )


    return xgb, rf, hgb


# ============================================================
# STEP 6: STRATIFIED 10-FOLD CV
# ============================================================

skf = StratifiedKFold(
    n_splits=10,
    shuffle=True,
    random_state=42
)


# ============================================================
# STEP 7: EVALUATION FUNCTION
# ============================================================

def evaluate_model(model_name):

    # ========================================================
    # CV METRIC STORAGE
    # ========================================================

    cv_accuracy = []
    cv_precision = []
    cv_sensitivity = []
    cv_f1 = []
    cv_auc = []
    cv_balanced_accuracy = []


    # ========================================================
    # 10-FOLD STRATIFIED CROSS-VALIDATION
    # ========================================================

    for fold, (train_idx, val_idx) in enumerate(
        skf.split(X_train, y_train),
        start=1
    ):

        print(
            f"\n{model_name} | Fold {fold}/10"
        )


        # ----------------------------------------------------
        # Split fold
        # ----------------------------------------------------

        X_tr = X_train.iloc[
            train_idx
        ]

        X_val = X_train.iloc[
            val_idx
        ]

        y_tr = y_train.iloc[
            train_idx
        ]

        y_val = y_train.iloc[
            val_idx
        ]


        # ----------------------------------------------------
        # Scaling INSIDE EACH FOLD
        # ----------------------------------------------------

        scaler = StandardScaler()

        X_tr_scaled = scaler.fit_transform(
            X_tr
        )

        X_val_scaled = scaler.transform(
            X_val
        )


        # ----------------------------------------------------
        # Create FRESH models for every fold
        # ----------------------------------------------------

        xgb, rf, hgb = create_models()


        # ----------------------------------------------------
        # Select requested model
        # ----------------------------------------------------

        if model_name == "XGBoost":

            model = xgb


        elif model_name == "Random Forest":

            model = rf


        elif model_name == "HistGradientBoosting":

            model = hgb


        elif model_name == "Voting Fusion":

            model = VotingClassifier(
                estimators=[
                    ('xgb', xgb),
                    ('rf', rf),
                    ('hgb', hgb)
                ],
                voting='soft'
            )


        elif model_name == "Stacking Fusion":

            model = StackingClassifier(
                estimators=[
                    ('xgb', xgb),
                    ('rf', rf),
                    ('hgb', hgb)
                ],

                final_estimator=LogisticRegression(
                    max_iter=1000,
                    class_weight='balanced'
                ),

                passthrough=True,

                cv=5
            )


        else:

            raise ValueError(
                f"Unknown model: {model_name}"
            )


        # ----------------------------------------------------
        # Train fold
        # ----------------------------------------------------

        model.fit(
            X_tr_scaled,
            y_tr
        )


        # ----------------------------------------------------
        # Validation predictions
        # ----------------------------------------------------

        val_preds = model.predict(
            X_val_scaled
        )

        val_probs = model.predict_proba(
            X_val_scaled
        )[:, 1]


        # ----------------------------------------------------
        # Fold metrics
        # ----------------------------------------------------

        fold_accuracy = accuracy_score(
            y_val,
            val_preds
        )

        fold_precision = precision_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_sensitivity = recall_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_f1 = f1_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_auc = roc_auc_score(
            y_val,
            val_probs
        )

        fold_balanced_accuracy = balanced_accuracy_score(
            y_val,
            val_preds
        )


        # ----------------------------------------------------
        # Store fold metrics
        # ----------------------------------------------------

        cv_accuracy.append(
            fold_accuracy
        )

        cv_precision.append(
            fold_precision
        )

        cv_sensitivity.append(
            fold_sensitivity
        )

        cv_f1.append(
            fold_f1
        )

        cv_auc.append(
            fold_auc
        )

        cv_balanced_accuracy.append(
            fold_balanced_accuracy
        )


        # ----------------------------------------------------
        # Print fold result
        # ----------------------------------------------------

        print(
            f"Accuracy            : {fold_accuracy:.4f}"
        )

        print(
            f"Precision           : {fold_precision:.4f}"
        )

        print(
            f"Sensitivity         : {fold_sensitivity:.4f}"
        )

        print(
            f"F1 Score            : {fold_f1:.4f}"
        )

        print(
            f"ROC-AUC             : {fold_auc:.4f}"
        )

        print(
            f"Balanced Accuracy   : "
            f"{fold_balanced_accuracy:.4f}"
        )


    # ========================================================
    # CV MEAN RESULTS
    # ========================================================

    cv_accuracy_mean = np.mean(
        cv_accuracy
    )

    cv_precision_mean = np.mean(
        cv_precision
    )

    cv_sensitivity_mean = np.mean(
        cv_sensitivity
    )

    cv_f1_mean = np.mean(
        cv_f1
    )

    cv_auc_mean = np.mean(
        cv_auc
    )

    cv_balanced_accuracy_mean = np.mean(
        cv_balanced_accuracy
    )


    # ========================================================
    # CROSS-VALIDATION RESULTS
    # ========================================================

    print(
        "\n================================================"
    )

    print(
        f"{model_name} - Cross-Validation (10-fold)"
    )

    print(
        "================================================"
    )

    print(
        f"Accuracy            : "
        f"{cv_accuracy_mean:.4f}"
    )

    print(
        f"Precision           : "
        f"{cv_precision_mean:.4f}"
    )

    print(
        f"Recall/Sensitivity  : "
        f"{cv_sensitivity_mean:.4f}"
    )

    print(
        f"F1 Score            : "
        f"{cv_f1_mean:.4f}"
    )

    print(
        f"ROC-AUC             : "
        f"{cv_auc_mean:.4f}"
    )

    print(
        f"Balanced Accuracy   : "
        f"{cv_balanced_accuracy_mean:.4f}"
    )


    # ========================================================
    # TRAIN FINAL MODEL ON COMPLETE TRAINING SET
    # ========================================================

    final_scaler = StandardScaler()

    X_train_final_scaled = final_scaler.fit_transform(
        X_train
    )

    X_test_final_scaled = final_scaler.transform(
        X_test
    )


    # --------------------------------------------------------
    # Create fresh final models
    # --------------------------------------------------------

    xgb, rf, hgb = create_models()


    if model_name == "XGBoost":

        final_model = xgb


    elif model_name == "Random Forest":

        final_model = rf


    elif model_name == "HistGradientBoosting":

        final_model = hgb


    elif model_name == "Voting Fusion":

        final_model = VotingClassifier(
            estimators=[
                ('xgb', xgb),
                ('rf', rf),
                ('hgb', hgb)
            ],
            voting='soft'
        )


    elif model_name == "Stacking Fusion":

        final_model = StackingClassifier(
            estimators=[
                ('xgb', xgb),
                ('rf', rf),
                ('hgb', hgb)
            ],

            final_estimator=LogisticRegression(
                max_iter=1000,
                class_weight='balanced'
            ),

            passthrough=True,

            cv=5
        )


    # ========================================================
    # FINAL TRAINING
    # ========================================================

    final_model.fit(
        X_train_final_scaled,
        y_train
    )


    # ========================================================
    # TEST PREDICTIONS
    # ========================================================

    test_preds = final_model.predict(
        X_test_final_scaled
    )

    test_probs = final_model.predict_proba(
        X_test_final_scaled
    )[:, 1]


    # ========================================================
    # TEST METRICS
    # ========================================================

    accuracy = accuracy_score(
        y_test,
        test_preds
    )

    precision = precision_score(
        y_test,
        test_preds,
        zero_division=0
    )

    sensitivity = recall_score(
        y_test,
        test_preds,
        zero_division=0
    )

    f1 = f1_score(
        y_test,
        test_preds,
        zero_division=0
    )

    roc_auc = roc_auc_score(
        y_test,
        test_probs
    )

    balanced_accuracy = balanced_accuracy_score(
        y_test,
        test_preds
    )

    mcc = matthews_corrcoef(
        y_test,
        test_preds
    )


    # ========================================================
    # CONFUSION MATRIX
    # ========================================================

    cm = confusion_matrix(
        y_test,
        test_preds,
        labels=[0, 1]
    )

    tn, fp, fn, tp = cm.ravel()


    # ========================================================
    # SENSITIVITY / SPECIFICITY
    # ========================================================

    sensitivity = (
        tp / (tp + fn)
        if (tp + fn) > 0
        else 0
    )

    specificity = (
        tn / (tn + fp)
        if (tn + fp) > 0
        else 0
    )


    # ========================================================
    # 95% CONFIDENCE INTERVALS
    # ========================================================

    # ---------------- Accuracy CI ----------------

    acc_low, acc_high = proportion_confint(
        count=int(round(accuracy * len(y_test))),
        nobs=len(y_test),
        alpha=0.05,
        method='wilson'
    )


    # ---------------- Precision CI ----------------

    precision_low, precision_high = proportion_confint(
        count=tp,
        nobs=(tp + fp),
        alpha=0.05,
        method='wilson'
    ) if (tp + fp) > 0 else (0.0, 0.0)


    # ---------------- Sensitivity CI ----------------

    sensitivity_low, sensitivity_high = proportion_confint(
        count=tp,
        nobs=(tp + fn),
        alpha=0.05,
        method='wilson'
    ) if (tp + fn) > 0 else (0.0, 0.0)


    # ---------------- Specificity CI ----------------

    specificity_low, specificity_high = proportion_confint(
        count=tn,
        nobs=(tn + fp),
        alpha=0.05,
        method='wilson'
    ) if (tn + fp) > 0 else (0.0, 0.0)


    # ========================================================
    # TEST SET PERFORMANCE
    # ========================================================

    print(
        "\n================================================"
    )

    print(
        f"{model_name} - Test Set Performance"
    )

    print(
        "================================================"
    )

    print(
        f"Accuracy            : {accuracy:.4f} "
        f"(95% CI: "
        f"{acc_low:.4f}-{acc_high:.4f})"
    )

    print(
        f"Precision           : {precision:.4f} "
        f"(95% CI: "
        f"{precision_low:.4f}-{precision_high:.4f})"
    )

    print(
        f"Sensitivity         : {sensitivity:.4f} "
        f"(95% CI: "
        f"{sensitivity_low:.4f}-{sensitivity_high:.4f})"
    )

    print(
        f"Specificity         : {specificity:.4f} "
        f"(95% CI: "
        f"{specificity_low:.4f}-{specificity_high:.4f})"
    )

    print(
        f"F1 Score            : {f1:.4f}"
    )

    print(
        f"ROC-AUC             : {roc_auc:.4f}"
    )

    print(
        f"Balanced Accuracy   : "
        f"{balanced_accuracy:.4f}"
    )

    print(
        f"MCC                 : {mcc:.4f}"
    )


    # ========================================================
    # CONFUSION MATRIX
    # ========================================================

    print(
        "\nConfusion Matrix:"
    )

    print(cm)

    print(
        "\nTN :", tn
    )

    print(
        "FP :", fp
    )

    print(
        "FN :", fn
    )

    print(
        "TP :", tp
    )


    # ========================================================
    # STORE RESULTS
    # ========================================================

    result = {

        # ---------------- CV ----------------

        "CV Accuracy":
            cv_accuracy_mean,

        "CV Precision":
            cv_precision_mean,

        "CV Sensitivity":
            cv_sensitivity_mean,

        "CV F1":
            cv_f1_mean,

        "CV ROC-AUC":
            cv_auc_mean,

        "CV Balanced Accuracy":
            cv_balanced_accuracy_mean,


        # ---------------- Test ----------------

        "Accuracy":
            accuracy,

        "Accuracy CI Low":
            acc_low,

        "Accuracy CI High":
            acc_high,


        "Precision":
            precision,

        "Precision CI Low":
            precision_low,

        "Precision CI High":
            precision_high,


        "Sensitivity":
            sensitivity,

        "Sensitivity CI Low":
            sensitivity_low,

        "Sensitivity CI High":
            sensitivity_high,


        "Specificity":
            specificity,

        "Specificity CI Low":
            specificity_low,

        "Specificity CI High":
            specificity_high,


        "F1":
            f1,

        "ROC-AUC":
            roc_auc,

        "Balanced Accuracy":
            balanced_accuracy,

        "MCC":
            mcc,


        # ---------------- Confusion Matrix ----------------

        "TN":
            tn,

        "FP":
            fp,

        "FN":
            fn,

        "TP":
            tp
    }


    return result


# ============================================================
# STEP 8: EVALUATE ALL MODELS
# ============================================================

model_names = [
    "XGBoost",
    "Random Forest",
    "HistGradientBoosting",
    "Voting Fusion",
    "Stacking Fusion"
]


results = {}

for name in model_names:

    print(
        "\n\n################################################"
    )

    print(
        f"Evaluating: {name}"
    )

    print(
        "################################################"
    )

    results[name] = evaluate_model(
        name
    )


# ============================================================
# STEP 9: FINAL RESULTS DATAFRAME
# ============================================================

results_df = pd.DataFrame(
    results
).T


# ============================================================
# STEP 10: ORDER RESULTS
# ============================================================

results_df = results_df[
    [

        # ---------------- CV ----------------

        "CV Accuracy",
        "CV Precision",
        "CV Sensitivity",
        "CV F1",
        "CV ROC-AUC",
        "CV Balanced Accuracy",


        # ---------------- Test ----------------

        "Accuracy",
        "Accuracy CI Low",
        "Accuracy CI High",

        "Precision",
        "Precision CI Low",
        "Precision CI High",

        "Sensitivity",
        "Sensitivity CI Low",
        "Sensitivity CI High",

        "Specificity",
        "Specificity CI Low",
        "Specificity CI High",

        "F1",
        "ROC-AUC",
        "Balanced Accuracy",
        "MCC",

        # ---------------- Confusion Matrix ----------------

        "TN",
        "FP",
        "FN",
        "TP"
    ]
]


# ============================================================
# STEP 11: DISPLAY FINAL RESULTS
# ============================================================

print(
    "\n================================================"
)

print(
    "FINAL MODEL COMPARISON"
)

print(
    "================================================\n"
)


display(
    results_df.sort_values(
        by="F1",
        ascending=False
    )
)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 8.4 MB/s eta 0:00:00

Class Weights:
{0: 1.2213740458015268, 1: 0.8465608465608465}

Train Shape : (256, 32)
Test Shape  : (64, 32)

Training Class Distribution:
PD_Label_Combined
1    151
0    105
Name: count, dtype: int64

Testing Class Distribution:
PD_Label_Combined
1    38
0    26
Name: count, dtype: int64

Training Class Weights:
{np.int64(0): np.float64(1.2190476190476192), np.int64(1): np.float64(0.847682119205298)}

XGBoost scale_pos_weight: 0.6953642384105959


################################################
Evaluating: XGBoost
################################################

XGBoost | Fold 1/10
Accuracy            : 0.6538
Precision           : 0.6842
Sensitivity         : 0.8125
F1 Score            : 0.7429
ROC-AUC             : 0.8313
Balanced Accuracy   : 0.6062

XGBoost | Fold 2/10
Accuracy            : 0.5769
Precision           : 0.6429
Sensitivity         : 0.6000
F1 Score            : 0.6207
ROC-AUC             : 0.7091
Balanced Accuracy   : 0.5727

XGBoost | Fold 3/10
Accuracy            : 0.8846
Precision           : 0.8750
Sensitivity         : 0.9333
F1 Score            : 0.9032
ROC-AUC             : 0.9212
Balanced Accuracy   : 0.8758

XGBoost | Fold 4/10
Accuracy            : 0.6923
Precision           : 0.7692
Sensitivity         : 0.6667
F1 Score            : 0.7143
ROC-AUC             : 0.8061
Balanced Accuracy   : 0.6970

XGBoost | Fold 5/10
Accuracy            : 0.7308
Precision           : 0.7500
Sensitivity         : 0.8000
F1 Score            : 0.7742
ROC-AUC             : 0.8424
Balanced Accuracy   : 0.7182

XGBoost | Fold 6/10
Accuracy            : 0.7308
Precision           : 0.7857
Sensitivity         : 0.7333
F1 Score            : 0.7586
ROC-AUC             : 0.8727
Balanced Accuracy   : 0.7303

XGBoost | Fold 7/10
Accuracy            : 0.7200
Precision           : 0.8333
Sensitivity         : 0.6667
F1 Score            : 0.7407
ROC-AUC             : 0.8300
Balanced Accuracy   : 0.7333

XGBoost | Fold 8/10
Accuracy            : 0.7600
Precision           : 0.7647
Sensitivity         : 0.8667
F1 Score            : 0.8125
ROC-AUC             : 0.8667
Balanced Accuracy   : 0.7333

XGBoost | Fold 9/10
Accuracy            : 0.8400
Precision           : 0.9231
Sensitivity         : 0.8000
F1 Score            : 0.8571
ROC-AUC             : 0.9533
Balanced Accuracy   : 0.8500

XGBoost | Fold 10/10
Accuracy            : 0.8000
Precision           : 0.9167
Sensitivity         : 0.7333
F1 Score            : 0.8148
ROC-AUC             : 0.8933
Balanced Accuracy   : 0.8167

================================================
XGBoost - Cross-Validation (10-fold)
================================================
Accuracy            : 0.7389
Precision           : 0.7945
Recall/Sensitivity  : 0.7612
F1 Score            : 0.7739
ROC-AUC             : 0.8526
Balanced Accuracy   : 0.7334

================================================
XGBoost - Test Set Performance
================================================
Accuracy            : 0.7344 (95% CI: 0.6152-0.8270)
Precision           : 0.7692 (95% CI: 0.6166-0.8735)
Sensitivity         : 0.7895 (95% CI: 0.6365-0.8893)
Specificity         : 0.6538 (95% CI: 0.4622-0.8059)
F1 Score            : 0.7792
ROC-AUC             : 0.7753
Balanced Accuracy   : 0.7217
MCC                 : 0.4463

Confusion Matrix:
[[17  9]
 [ 8 30]]

TN : 17
FP : 9
FN : 8
TP : 30


################################################
Evaluating: Random Forest
################################################

Random Forest | Fold 1/10
Accuracy            : 0.6538
Precision           : 0.6842
Sensitivity         : 0.8125
F1 Score            : 0.7429
ROC-AUC             : 0.7875
Balanced Accuracy   : 0.6062

Random Forest | Fold 2/10
Accuracy            : 0.5769
Precision           : 0.6250
Sensitivity         : 0.6667
F1 Score            : 0.6452
ROC-AUC             : 0.7394
Balanced Accuracy   : 0.5606

Random Forest | Fold 3/10
Accuracy            : 0.8462
Precision           : 0.9231
Sensitivity         : 0.8000
F1 Score            : 0.8571
ROC-AUC             : 0.9606
Balanced Accuracy   : 0.8545

Random Forest | Fold 4/10
Accuracy            : 0.6923
Precision           : 0.7692
Sensitivity         : 0.6667
F1 Score            : 0.7143
ROC-AUC             : 0.8121
Balanced Accuracy   : 0.6970

Random Forest | Fold 5/10
Accuracy            : 0.6923
Precision           : 0.7059
Sensitivity         : 0.8000
F1 Score            : 0.7500
ROC-AUC             : 0.8364
Balanced Accuracy   : 0.6727

Random Forest | Fold 6/10
Accuracy            : 0.6923
Precision           : 0.7333
Sensitivity         : 0.7333
F1 Score            : 0.7333
ROC-AUC             : 0.8545
Balanced Accuracy   : 0.6848

Random Forest | Fold 7/10
Accuracy            : 0.7600
Precision           : 0.8462
Sensitivity         : 0.7333
F1 Score            : 0.7857
ROC-AUC             : 0.8300
Balanced Accuracy   : 0.7667

Random Forest | Fold 8/10
Accuracy            : 0.7600
Precision           : 0.7647
Sensitivity         : 0.8667
F1 Score            : 0.8125
ROC-AUC             : 0.8033
Balanced Accuracy   : 0.7333

Random Forest | Fold 9/10
Accuracy            : 0.8800
Precision           : 0.9286
Sensitivity         : 0.8667
F1 Score            : 0.8966
ROC-AUC             : 0.9533
Balanced Accuracy   : 0.8833

Random Forest | Fold 10/10
Accuracy            : 0.8000
Precision           : 0.8571
Sensitivity         : 0.8000
F1 Score            : 0.8276
ROC-AUC             : 0.9400
Balanced Accuracy   : 0.8000

================================================
Random Forest - Cross-Validation (10-fold)
================================================
Accuracy            : 0.7354
Precision           : 0.7837
Recall/Sensitivity  : 0.7746
F1 Score            : 0.7765
ROC-AUC             : 0.8517
Balanced Accuracy   : 0.7259

================================================
Random Forest - Test Set Performance
================================================
Accuracy            : 0.6562 (95% CI: 0.5340-0.7608)
Precision           : 0.7000 (95% CI: 0.5457-0.8193)
Sensitivity         : 0.7368 (95% CI: 0.5799-0.8503)
Specificity         : 0.5385 (95% CI: 0.3546-0.7124)
F1 Score            : 0.7179
ROC-AUC             : 0.7257
Balanced Accuracy   : 0.6377
MCC                 : 0.2793

Confusion Matrix:
[[14 12]
 [10 28]]

TN : 14
FP : 12
FN : 10
TP : 28


################################################
Evaluating: HistGradientBoosting
################################################

HistGradientBoosting | Fold 1/10
Accuracy            : 0.6923
Precision           : 0.7222
Sensitivity         : 0.8125
F1 Score            : 0.7647
ROC-AUC             : 0.8187
Balanced Accuracy   : 0.6562

HistGradientBoosting | Fold 2/10
Accuracy            : 0.6154
Precision           : 0.6667
Sensitivity         : 0.6667
F1 Score            : 0.6667
ROC-AUC             : 0.7152
Balanced Accuracy   : 0.6061

HistGradientBoosting | Fold 3/10
Accuracy            : 0.7692
Precision           : 0.8000
Sensitivity         : 0.8000
F1 Score            : 0.8000
ROC-AUC             : 0.9212
Balanced Accuracy   : 0.7636

HistGradientBoosting | Fold 4/10
Accuracy            : 0.6923
Precision           : 0.8182
Sensitivity         : 0.6000
F1 Score            : 0.6923
ROC-AUC             : 0.8182
Balanced Accuracy   : 0.7091

HistGradientBoosting | Fold 5/10
Accuracy            : 0.7308
Precision           : 0.7857
Sensitivity         : 0.7333
F1 Score            : 0.7586
ROC-AUC             : 0.8667
Balanced Accuracy   : 0.7303

HistGradientBoosting | Fold 6/10
Accuracy            : 0.8077
Precision           : 0.8571
Sensitivity         : 0.8000
F1 Score            : 0.8276
ROC-AUC             : 0.8545
Balanced Accuracy   : 0.8091

HistGradientBoosting | Fold 7/10
Accuracy            : 0.7600
Precision           : 0.8462
Sensitivity         : 0.7333
F1 Score            : 0.7857
ROC-AUC             : 0.8500
Balanced Accuracy   : 0.7667

HistGradientBoosting | Fold 8/10
Accuracy            : 0.8400
Precision           : 0.8235
Sensitivity         : 0.9333
F1 Score            : 0.8750
ROC-AUC             : 0.8867
Balanced Accuracy   : 0.8167

HistGradientBoosting | Fold 9/10
Accuracy            : 0.8800
Precision           : 1.0000
Sensitivity         : 0.8000
F1 Score            : 0.8889
ROC-AUC             : 0.9267
Balanced Accuracy   : 0.9000

HistGradientBoosting | Fold 10/10
Accuracy            : 0.8400
Precision           : 1.0000
Sensitivity         : 0.7333
F1 Score            : 0.8462
ROC-AUC             : 0.9467
Balanced Accuracy   : 0.8667

================================================
HistGradientBoosting - Cross-Validation (10-fold)
================================================
Accuracy            : 0.7628
Precision           : 0.8320
Recall/Sensitivity  : 0.7612
F1 Score            : 0.7906
ROC-AUC             : 0.8605
Balanced Accuracy   : 0.7624

================================================
HistGradientBoosting - Test Set Performance
================================================
Accuracy            : 0.7031 (95% CI: 0.5823-0.8009)
Precision           : 0.7436 (95% CI: 0.5892-0.8543)
Sensitivity         : 0.7632 (95% CI: 0.6079-0.8701)
Specificity         : 0.6154 (95% CI: 0.4253-0.7757)
F1 Score            : 0.7532
ROC-AUC             : 0.7490
Balanced Accuracy   : 0.6893
MCC                 : 0.3811

Confusion Matrix:
[[16 10]
 [ 9 29]]

TN : 16
FP : 10
FN : 9
TP : 29


################################################
Evaluating: Voting Fusion
################################################

Voting Fusion | Fold 1/10
Accuracy            : 0.6538
Precision           : 0.6842
Sensitivity         : 0.8125
F1 Score            : 0.7429
ROC-AUC             : 0.8125
Balanced Accuracy   : 0.6062

Voting Fusion | Fold 2/10
Accuracy            : 0.6154
Precision           : 0.6667
Sensitivity         : 0.6667
F1 Score            : 0.6667
ROC-AUC             : 0.7333
Balanced Accuracy   : 0.6061

Voting Fusion | Fold 3/10
Accuracy            : 0.8462
Precision           : 0.8667
Sensitivity         : 0.8667
F1 Score            : 0.8667
ROC-AUC             : 0.9515
Balanced Accuracy   : 0.8424

Voting Fusion | Fold 4/10
Accuracy            : 0.7308
Precision           : 0.8333
Sensitivity         : 0.6667
F1 Score            : 0.7407
ROC-AUC             : 0.8061
Balanced Accuracy   : 0.7424

Voting Fusion | Fold 5/10
Accuracy            : 0.6923
Precision           : 0.7333
Sensitivity         : 0.7333
F1 Score            : 0.7333
ROC-AUC             : 0.8485
Balanced Accuracy   : 0.6848

Voting Fusion | Fold 6/10
Accuracy            : 0.8077
Precision           : 0.8571
Sensitivity         : 0.8000
F1 Score            : 0.8276
ROC-AUC             : 0.8727
Balanced Accuracy   : 0.8091

Voting Fusion | Fold 7/10
Accuracy            : 0.7600
Precision           : 0.8462
Sensitivity         : 0.7333
F1 Score            : 0.7857
ROC-AUC             : 0.8300
Balanced Accuracy   : 0.7667

Voting Fusion | Fold 8/10
Accuracy            : 0.8000
Precision           : 0.8125
Sensitivity         : 0.8667
F1 Score            : 0.8387
ROC-AUC             : 0.8467
Balanced Accuracy   : 0.7833

Voting Fusion | Fold 9/10
Accuracy            : 0.8400
Precision           : 1.0000
Sensitivity         : 0.7333
F1 Score            : 0.8462
ROC-AUC             : 0.9467
Balanced Accuracy   : 0.8667

Voting Fusion | Fold 10/10
Accuracy            : 0.8400
Precision           : 0.9231
Sensitivity         : 0.8000
F1 Score            : 0.8571
ROC-AUC             : 0.9467
Balanced Accuracy   : 0.8500

================================================
Voting Fusion - Cross-Validation (10-fold)
================================================
Accuracy            : 0.7586
Precision           : 0.8223
Recall/Sensitivity  : 0.7679
F1 Score            : 0.7906
ROC-AUC             : 0.8595
Balanced Accuracy   : 0.7558

================================================
Voting Fusion - Test Set Performance
================================================
Accuracy            : 0.6875 (95% CI: 0.5661-0.7877)
Precision           : 0.7250 (95% CI: 0.5717-0.8389)
Sensitivity         : 0.7632 (95% CI: 0.6079-0.8701)
Specificity         : 0.5769 (95% CI: 0.3895-0.7446)
F1 Score            : 0.7436
ROC-AUC             : 0.7571
Balanced Accuracy   : 0.6700
MCC                 : 0.3450

Confusion Matrix:
[[15 11]
 [ 9 29]]

TN : 15
FP : 11
FN : 9
TP : 29


################################################
Evaluating: Stacking Fusion
################################################

Stacking Fusion | Fold 1/10
Accuracy            : 0.6538
Precision           : 0.7059
Sensitivity         : 0.7500
F1 Score            : 0.7273
ROC-AUC             : 0.7812
Balanced Accuracy   : 0.6250

Stacking Fusion | Fold 2/10
Accuracy            : 0.6538
Precision           : 0.7500
Sensitivity         : 0.6000
F1 Score            : 0.6667
ROC-AUC             : 0.7636
Balanced Accuracy   : 0.6636

Stacking Fusion | Fold 3/10
Accuracy            : 0.8462
Precision           : 1.0000
Sensitivity         : 0.7333
F1 Score            : 0.8462
ROC-AUC             : 0.8667
Balanced Accuracy   : 0.8667

Stacking Fusion | Fold 4/10
Accuracy            : 0.8077
Precision           : 0.9167
Sensitivity         : 0.7333
F1 Score            : 0.8148
ROC-AUC             : 0.8545
Balanced Accuracy   : 0.8212

Stacking Fusion | Fold 5/10
Accuracy            : 0.8462
Precision           : 0.9231
Sensitivity         : 0.8000
F1 Score            : 0.8571
ROC-AUC             : 0.9333
Balanced Accuracy   : 0.8545

Stacking Fusion | Fold 6/10
Accuracy            : 0.6538
Precision           : 0.7500
Sensitivity         : 0.6000
F1 Score            : 0.6667
ROC-AUC             : 0.8121
Balanced Accuracy   : 0.6636

Stacking Fusion | Fold 7/10
Accuracy            : 0.8000
Precision           : 0.9167
Sensitivity         : 0.7333
F1 Score            : 0.8148
ROC-AUC             : 0.8567
Balanced Accuracy   : 0.8167

Stacking Fusion | Fold 8/10
Accuracy            : 0.8000
Precision           : 0.8125
Sensitivity         : 0.8667
F1 Score            : 0.8387
ROC-AUC             : 0.8733
Balanced Accuracy   : 0.7833

Stacking Fusion | Fold 9/10
Accuracy            : 0.8400
Precision           : 1.0000
Sensitivity         : 0.7333
F1 Score            : 0.8462
ROC-AUC             : 0.9733
Balanced Accuracy   : 0.8667

Stacking Fusion | Fold 10/10
Accuracy            : 0.8000
Precision           : 0.8571
Sensitivity         : 0.8000
F1 Score            : 0.8276
ROC-AUC             : 0.9600
Balanced Accuracy   : 0.8000

================================================
Stacking Fusion - Cross-Validation (10-fold)
================================================
Accuracy            : 0.7702
Precision           : 0.8632
Recall/Sensitivity  : 0.7350
F1 Score            : 0.7906
ROC-AUC             : 0.8675
Balanced Accuracy   : 0.7761

================================================
Stacking Fusion - Test Set Performance
================================================
Accuracy            : 0.7500 (95% CI: 0.6318-0.8399)
Precision           : 0.7895 (95% CI: 0.6365-0.8893)
Sensitivity         : 0.7895 (95% CI: 0.6365-0.8893)
Specificity         : 0.6923 (95% CI: 0.5001-0.8350)
F1 Score            : 0.7895
ROC-AUC             : 0.8077
Balanced Accuracy   : 0.7409
MCC                 : 0.4818

Confusion Matrix:
[[18  8]
 [ 8 30]]

TN : 18
FP : 8
FN : 8
TP : 30

================================================
FINAL MODEL COMPARISON
================================================

,CV Accuracy,CV Precision,CV Sensitivity,CV F1,CV ROC-AUC,CV Balanced Accuracy,Accuracy,Accuracy CI Low,Accuracy CI High,Precision,...,Specificity CI Low,Specificity CI High,F1,ROC-AUC,Balanced Accuracy,MCC,TN,FP,FN,TP
Stacking Fusion,0.770154,0.863194,0.735000,0.790598,0.867489,0.776136,0.750000,0.631837,0.839851,0.789474,...,0.500117,0.834987,0.789474,0.807692,0.740891,0.481781,18.0,8.0,8.0,30.0
XGBoost,0.738923,0.794480,0.761250,0.773907,0.852610,0.733352,0.734375,0.615171,0.827036,0.769231,...,0.462206,0.805878,0.779221,0.775304,0.721660,0.446266,17.0,9.0,8.0,30.0
HistGradientBoosting,0.762769,0.831961,0.761250,0.790564,0.860451,0.762443,0.703125,0.582298,0.800948,0.743590,...,0.425349,0.775714,0.753247,0.748988,0.689271,0.381058,16.0,10.0,9.0,29.0
Voting Fusion,0.758615,0.822308,0.767917,0.790557,0.859462,0.755777,0.687500,0.566077,0.787689,0.725000,...,0.389486,0.744556,0.743590,0.757085,0.670040,0.345005,15.0,11.0,9.0,29.0
Random Forest,0.735385,0.783731,0.774583,0.776513,0.851720,0.725928,0.656250,0.534036,0.760769,0.700000,...,0.354579,0.712441,0.717949,0.725709,0.637652,0.279290,14.0,12.0,10.0,28.0

Baseline SCL

In [1]:
# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

df_acoustic_top7 = pd.read_csv('/content/drive/MyDrive/Acoustic-subject-level-dataset_top7.csv')
df_acoustic_top7 = df_acoustic_top7.drop(columns=['Participant_ID'])
print(df_acoustic_top7.shape)
print(df_acoustic_top7.head())

(193, 8)
       RPDE  Degree-voice breaks  Delta2  Delta3  Delta11  MFCC5   spread1  \
0  0.428488                  0.0     0.0     0.0      0.0    0.0 -4.239926
1  0.542488                  0.0     0.0     0.0      0.0    0.0 -4.519291
2  0.332247                  0.0     0.0     0.0      0.0    0.0 -7.226125
3  0.498593                  0.0     0.0     0.0      0.0    0.0 -5.632290
4  0.470775                  0.0     0.0     0.0      0.0    0.0 -5.523149

   Status
0       1
1       1
2       0
3       1
4       1

In [3]:
import pandas as pd

final_meg_df = pd.read_csv('/content/drive/MyDrive/final_meg-rest(par)_top7_rfc+shap_10-fold_analysis_last_column.csv')

print("Loaded data shape:", final_meg_df.shape)
print(final_meg_df.head())

Loaded data shape: (127, 8)
   ibi_cv_asym  ibi_cv_L_std  mean_burst_duration_R_std  \
0     0.002893      0.048081                   0.002407
1    -0.018062      0.085531                   0.005160
2    -0.002573      0.032173                   0.001270
3     0.001531      0.044880                   0.003106
4     0.023834      0.142267                   0.004734

   mean_burst_duration_asym  burst_dur_cv_R_std  burst_dur_cv_L_std  \
0                  0.009156            0.040693            0.055777
1                 -0.005581            0.048648            0.052883
2                  0.007325            0.030995            0.046488
3                  0.005372            0.042429            0.049082
4                  0.014897            0.044595            0.053040

   ibi_cv_R_std  PD_Label_Combined
0      0.043907                  0
1      0.086747                  0
2      0.032718                  0
3      0.044973                  1
4      0.113787                  1

In [4]:
# ============================================================
#           BASELINE SUPERVISED CONTRASTIVE LEARNING
#        (BASIC SCL BASELINE + 5-FOLD CROSS VALIDATION)
# ============================================================

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

import torch.nn.functional as F
import numpy as np

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# ============================================================
# LOAD DATA
# ============================================================

sc = StandardScaler()

# Acoustic
X_acoustic = sc.fit_transform(
    df_acoustic_top7.iloc[:, :-1]
).astype(np.float32)

# MEG
X_meg = sc.fit_transform(
    final_meg_df.iloc[:, :-1]
).astype(np.float32)

# LABELS

acoustic_labels = df_acoustic_top7.iloc[:, -1].values.astype(np.int64)

meg_labels = final_meg_df.iloc[:, -1].values.astype(np.int64)

# ============================================================
# COMBINE MODALITIES
# ============================================================

X_all = np.vstack([
    X_acoustic,
    X_meg
]).astype(np.float32)

task_labels = np.hstack([
    acoustic_labels,
    meg_labels
]).astype(np.int64)

# ============================================================
# TENSORS
# ============================================================

X_all_tensor = torch.tensor(
    X_all
).float().to(device)

task_labels_tensor = torch.tensor(
    task_labels
).long().to(device)

# ============================================================
# SIMPLE SCL MODEL
# ============================================================

class BasicSCLModel(nn.Module):

    def __init__(self, input_dim, latent_dim=32):

        super().__init__()

        # SIMPLE ENCODER

        self.encoder = nn.Sequential(

            nn.Linear(input_dim, 64),
            nn.ReLU(),

            nn.Linear(64, latent_dim)
        )

        # SIMPLE TASK HEAD

        self.task_head = nn.Sequential(

            nn.Linear(latent_dim, 16),
            nn.ReLU(),

            nn.Linear(16, 2)
        )

    def forward(self, x):

        # LATENT FEATURES

        z = self.encoder(x)

        # NORMALIZATION

        z_norm = F.normalize(
            z,
            p=2,
            dim=1
        )

        # CLASSIFICATION

        task_out = self.task_head(z_norm)

        return task_out, z_norm

# ============================================================
# BASIC SUPERVISED CONTRASTIVE LOSS
# ============================================================

class SupConLoss(nn.Module):

    def __init__(self, temperature=0.1):

        super().__init__()

        self.temperature = temperature

    def forward(self, features, labels):

        device = features.device

        labels = labels.contiguous().view(-1, 1)

        mask = torch.eq(
            labels,
            labels.T
        ).float().to(device)

        similarity = torch.matmul(
            features,
            features.T
        ) / self.temperature

        logits_mask = torch.ones_like(mask) - torch.eye(
            mask.shape[0]
        ).to(device)

        mask = mask * logits_mask

        exp_sim = torch.exp(similarity) * logits_mask

        log_prob = similarity - torch.log(
            exp_sim.sum(1, keepdim=True) + 1e-8
        )

        mean_log_prob_pos = (
            mask * log_prob
        ).sum(1) / (mask.sum(1) + 1e-8)

        loss = -mean_log_prob_pos.mean()

        return loss

# ============================================================
# DATA LOADER
# ============================================================

dataset = TensorDataset(
    X_all_tensor,
    task_labels_tensor
)

loader = DataLoader(
    dataset,
    batch_size=128,
    shuffle=True
)

# ============================================================
# MODEL
# ============================================================

model = BasicSCLModel(
    input_dim=X_all.shape[1],
    latent_dim=32
).to(device)

# ============================================================
# OPTIMIZER
# ============================================================

optimizer = optim.Adam(
    model.parameters(),
    lr=1e-3
)

# ============================================================
# LOSSES
# ============================================================

task_loss_fn = nn.CrossEntropyLoss()

contrastive_loss_fn = SupConLoss(
    temperature=0.1
)

epochs = 120

print("\nTraining Started...\n")

# ============================================================
# TRAINING
# ============================================================

for epoch in range(epochs):

    model.train()

    total_correct = 0
    total_samples = 0

    for xb, y_task in loader:

        optimizer.zero_grad()

        # FORWARD

        task_out, z = model(xb)

        # TASK LOSS

        loss_task = task_loss_fn(
            task_out,
            y_task
        )

        # CONTRASTIVE LOSS

        loss_contrastive = contrastive_loss_fn(
            z,
            y_task
        )

        # FINAL LOSS

        loss = (
            1.0 * loss_task +
            0.3 * loss_contrastive
        )

        loss.backward()

        optimizer.step()

        # ACCURACY

        preds = task_out.argmax(1)

        total_correct += (
            preds == y_task
        ).sum().item()

        total_samples += len(y_task)

    acc = total_correct / total_samples

    print(
        f"Epoch {epoch+1}/{epochs} "
        f"| Accuracy={acc:.4f}"
    )

# ============================================================
# EXTRACT 32D LATENT FEATURES
# ============================================================

model.eval()

with torch.no_grad():

    fused_acoustic_32D = model(
        torch.tensor(X_acoustic).float().to(device)
    )[1].cpu().numpy()

    fused_meg_32D = model(
        torch.tensor(X_meg).float().to(device)
    )[1].cpu().numpy()

# ============================================================
# COMBINE LATENT FEATURES
# ============================================================

combined_32D = np.vstack([
    fused_acoustic_32D,
    fused_meg_32D
]).astype(np.float32)

combined_labels = np.hstack([
    acoustic_labels,
    meg_labels
]).astype(np.int64)

# ============================================================
# FINAL MLP CLASSIFIER
# ============================================================

class FinalMLP(nn.Module):

    def __init__(self, input_dim=32):

        super().__init__()

        self.net = nn.Sequential(

            nn.Linear(input_dim, 64),
            nn.ReLU(),

            nn.Dropout(0.2),

            nn.Linear(64, 32),
            nn.ReLU(),

            nn.Linear(32, 2)
        )

    def forward(self, x):

        return self.net(x)

# ============================================================
# 5-FOLD CROSS VALIDATION
# ============================================================

print("\n======================================")
print(" CROSS VALIDATION RESULTS")
print("======================================\n")

skf = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

accs = []
precs = []
recs = []
f1s = []
aucs = []

fold = 1

for train_idx, test_idx in skf.split(combined_32D, combined_labels):

    X_train = torch.tensor(
        combined_32D[train_idx]
    ).float().to(device)

    X_test = torch.tensor(
        combined_32D[test_idx]
    ).float().to(device)

    y_train = torch.tensor(
        combined_labels[train_idx]
    ).long().to(device)

    y_test = combined_labels[test_idx]

    clf = FinalMLP().to(device)

    optimizer_clf = optim.Adam(
        clf.parameters(),
        lr=1e-3
    )

    criterion = nn.CrossEntropyLoss()

    # ========================================================
    # TRAIN CLASSIFIER
    # ========================================================

    clf.train()

    for epoch in range(80):

        optimizer_clf.zero_grad()

        outputs = clf(X_train)

        loss = criterion(
            outputs,
            y_train
        )

        loss.backward()

        optimizer_clf.step()

    # ========================================================
    # TEST
    # ========================================================

    clf.eval()

    with torch.no_grad():

        outputs = clf(X_test)

        probs = F.softmax(
            outputs,
            dim=1
        )[:, 1].cpu().numpy()

        preds = outputs.argmax(1).cpu().numpy()

    acc = accuracy_score(y_test, preds)

    prec = precision_score(y_test, preds)

    rec = recall_score(y_test, preds)

    f1 = f1_score(y_test, preds)

    auc = roc_auc_score(y_test, probs)

    accs.append(acc)
    precs.append(prec)
    recs.append(rec)
    f1s.append(f1)
    aucs.append(auc)

    print(f"Fold {fold}")

    print(f"Accuracy  : {acc:.4f}")
    print(f"Precision : {prec:.4f}")
    print(f"Recall    : {rec:.4f}")
    print(f"F1-Score  : {f1:.4f}")
    print(f"AUC       : {auc:.4f}")

    print()

    fold += 1

# ============================================================
# FINAL RESULTS
# ============================================================

print("\n======================================")
print(" FINAL RESULTS")
print("======================================\n")

print(f"Mean Accuracy  : {np.mean(accs)*100:.2f}%")
print(f"Mean Precision : {np.mean(precs)*100:.2f}%")
print(f"Mean Recall    : {np.mean(recs)*100:.2f}%")
print(f"Mean F1-Score  : {np.mean(f1s)*100:.2f}%")
print(f"Mean AUC       : {np.mean(aucs)*100:.2f}%")

# ============================================================
# FINAL RESULTS
# ============================================================

print("\n========== LATENT FEATURE SHAPES ==========\n")

print("Acoustic 32D :", fused_acoustic_32D.shape)

print("MEG 32D      :", fused_meg_32D.shape)

print("Combined 32D :", combined_32D.shape)

print("Labels Shape :", combined_labels.shape)

Training Started...

Epoch 1/120 | Accuracy=0.5906
Epoch 2/120 | Accuracy=0.5906
Epoch 3/120 | Accuracy=0.5906
Epoch 4/120 | Accuracy=0.5906
Epoch 5/120 | Accuracy=0.5906
Epoch 6/120 | Accuracy=0.5906
Epoch 7/120 | Accuracy=0.5906
Epoch 8/120 | Accuracy=0.5906
Epoch 9/120 | Accuracy=0.5906
Epoch 10/120 | Accuracy=0.5906
Epoch 11/120 | Accuracy=0.5906
Epoch 12/120 | Accuracy=0.5906
Epoch 13/120 | Accuracy=0.5906
Epoch 14/120 | Accuracy=0.5906
Epoch 15/120 | Accuracy=0.5906
Epoch 16/120 | Accuracy=0.5906
Epoch 17/120 | Accuracy=0.5906
Epoch 18/120 | Accuracy=0.5906
Epoch 19/120 | Accuracy=0.5906
Epoch 20/120 | Accuracy=0.5906
Epoch 21/120 | Accuracy=0.5906
Epoch 22/120 | Accuracy=0.5906
Epoch 23/120 | Accuracy=0.5906
Epoch 24/120 | Accuracy=0.5906
Epoch 25/120 | Accuracy=0.5906
Epoch 26/120 | Accuracy=0.5906
Epoch 27/120 | Accuracy=0.5906
Epoch 28/120 | Accuracy=0.5906
Epoch 29/120 | Accuracy=0.5906
Epoch 30/120 | Accuracy=0.5906
Epoch 31/120 | Accuracy=0.5906
Epoch 32/120 | Accuracy=0.5906
Epoch 33/120 | Accuracy=0.5906
Epoch 34/120 | Accuracy=0.5906
Epoch 35/120 | Accuracy=0.5906
Epoch 36/120 | Accuracy=0.5938
Epoch 37/120 | Accuracy=0.5938
Epoch 38/120 | Accuracy=0.5938
Epoch 39/120 | Accuracy=0.5938
Epoch 40/120 | Accuracy=0.5969
Epoch 41/120 | Accuracy=0.6031
Epoch 42/120 | Accuracy=0.6125
Epoch 43/120 | Accuracy=0.6250
Epoch 44/120 | Accuracy=0.6438
Epoch 45/120 | Accuracy=0.6656
Epoch 46/120 | Accuracy=0.6687
Epoch 47/120 | Accuracy=0.6719
Epoch 48/120 | Accuracy=0.6875
Epoch 49/120 | Accuracy=0.6969
Epoch 50/120 | Accuracy=0.7219
Epoch 51/120 | Accuracy=0.7312
Epoch 52/120 | Accuracy=0.7562
Epoch 53/120 | Accuracy=0.7531
Epoch 54/120 | Accuracy=0.7281
Epoch 55/120 | Accuracy=0.7094
Epoch 56/120 | Accuracy=0.7156
Epoch 57/120 | Accuracy=0.7312
Epoch 58/120 | Accuracy=0.7344
Epoch 59/120 | Accuracy=0.7344
Epoch 60/120 | Accuracy=0.7438
Epoch 61/120 | Accuracy=0.7688
Epoch 62/120 | Accuracy=0.7719
Epoch 63/120 | Accuracy=0.7750
Epoch 64/120 | Accuracy=0.7750
Epoch 65/120 | Accuracy=0.7781
Epoch 66/120 | Accuracy=0.7844
Epoch 67/120 | Accuracy=0.7875
Epoch 68/120 | Accuracy=0.7906
Epoch 69/120 | Accuracy=0.7844
Epoch 70/120 | Accuracy=0.7875
Epoch 71/120 | Accuracy=0.7750
Epoch 72/120 | Accuracy=0.7875
Epoch 73/120 | Accuracy=0.7937
Epoch 74/120 | Accuracy=0.7875
Epoch 75/120 | Accuracy=0.7906
Epoch 76/120 | Accuracy=0.7812
Epoch 77/120 | Accuracy=0.7969
Epoch 78/120 | Accuracy=0.7875
Epoch 79/120 | Accuracy=0.7969
Epoch 80/120 | Accuracy=0.7969
Epoch 81/120 | Accuracy=0.7937
Epoch 82/120 | Accuracy=0.7937
Epoch 83/120 | Accuracy=0.7906
Epoch 84/120 | Accuracy=0.7937
Epoch 85/120 | Accuracy=0.7969
Epoch 86/120 | Accuracy=0.7875
Epoch 87/120 | Accuracy=0.8000
Epoch 88/120 | Accuracy=0.7969
Epoch 89/120 | Accuracy=0.8063
Epoch 90/120 | Accuracy=0.8000
Epoch 91/120 | Accuracy=0.8000
Epoch 92/120 | Accuracy=0.7969
Epoch 93/120 | Accuracy=0.8063
Epoch 94/120 | Accuracy=0.8063
Epoch 95/120 | Accuracy=0.8000
Epoch 96/120 | Accuracy=0.7969
Epoch 97/120 | Accuracy=0.8031
Epoch 98/120 | Accuracy=0.8031
Epoch 99/120 | Accuracy=0.8000
Epoch 100/120 | Accuracy=0.8094
Epoch 101/120 | Accuracy=0.8063
Epoch 102/120 | Accuracy=0.7937
Epoch 103/120 | Accuracy=0.8156
Epoch 104/120 | Accuracy=0.8063
Epoch 105/120 | Accuracy=0.8094
Epoch 106/120 | Accuracy=0.8031
Epoch 107/120 | Accuracy=0.7969
Epoch 108/120 | Accuracy=0.8125
Epoch 109/120 | Accuracy=0.8000
Epoch 110/120 | Accuracy=0.8000
Epoch 111/120 | Accuracy=0.8031
Epoch 112/120 | Accuracy=0.8187
Epoch 113/120 | Accuracy=0.8000
Epoch 114/120 | Accuracy=0.7937
Epoch 115/120 | Accuracy=0.8125
Epoch 116/120 | Accuracy=0.8094
Epoch 117/120 | Accuracy=0.8031
Epoch 118/120 | Accuracy=0.8063
Epoch 119/120 | Accuracy=0.8000
Epoch 120/120 | Accuracy=0.7937

======================================
 CROSS VALIDATION RESULTS
======================================

Fold 1
Accuracy  : 0.7344
Precision : 0.8000
Recall    : 0.7368
F1-Score  : 0.7671
AUC       : 0.8057

Fold 2
Accuracy  : 0.7812
Precision : 0.8000
Recall    : 0.8421
F1-Score  : 0.8205
AUC       : 0.8826

Fold 3
Accuracy  : 0.8281
Precision : 0.8462
Recall    : 0.8684
F1-Score  : 0.8571
AUC       : 0.9297

Fold 4
Accuracy  : 0.8750
Precision : 0.9167
Recall    : 0.8684
F1-Score  : 0.8919
AUC       : 0.9291

Fold 5
Accuracy  : 0.8438
Precision : 0.9655
Recall    : 0.7568
F1-Score  : 0.8485
AUC       : 0.9199


======================================
 FINAL RESULTS
======================================

Mean Accuracy  : 81.25%
Mean Precision : 86.57%
Mean Recall    : 81.45%
Mean F1-Score  : 83.70%
Mean AUC       : 89.34%

========== LATENT FEATURE SHAPES ==========

Acoustic 32D : (193, 32)
MEG 32D      : (127, 32)
Combined 32D : (320, 32)
Labels Shape : (320,)

In [5]:
import torch

# Assuming fused_acoustic_32D and fused_meg_32D are numpy arrays of shape (7350, 32)

# Step 1: Convert numpy arrays to torch tensors (float32)
fused_acoustic_tensor = torch.from_numpy(fused_acoustic_32D).float()
fused_meg_tensor = torch.from_numpy(fused_meg_32D).float()

# Step 2: Concatenate row-wise (along dim=0)
fused_output_tensor = torch.cat([fused_acoustic_tensor, fused_meg_tensor], dim=0)  # Shape: (14700, 32)

# Step 3: Print shape and dtype
print(fused_output_tensor.shape)  # torch.Size([14700, 32])
print(fused_output_tensor.dtype)  # torch.float32

torch.Size([320, 32])
torch.float32

In [6]:
import torch
import numpy as np

# ------------------------
# Step 1: Extract targets correctly
# ------------------------

# Acoustic target from df_acoustic_top7 (last column)
y_acoustic = df_acoustic_top7.iloc[:, -1].values.astype(np.int32)   # (7350,)

# MEG target from final_meg_df (last column)
y_meg = final_meg_df.iloc[:, -1].values.astype(np.int32)           # (7350,)

# Convert to tensors (reshape to column)
acoustic_target_tensor = torch.tensor(y_acoustic).long().reshape(-1, 1)   # (7350, 1)
meg_target_tensor      = torch.tensor(y_meg).long().reshape(-1, 1)        # (7350, 1)

# ------------------------
# Step 2: Convert 32D latent features to tensors
# ------------------------

fused_acoustic_tensor = torch.from_numpy(fused_acoustic_32D).float()  # (7350, 32)
fused_meg_tensor      = torch.from_numpy(fused_meg_32D).float()       # (7350, 32)

# ------------------------
# Step 3: Attach target columns
# ------------------------

# Concatenate latent features with target
acoustic_full = torch.cat([fused_acoustic_tensor, acoustic_target_tensor.float()], dim=1)  # (7350, 65)
meg_full      = torch.cat([fused_meg_tensor,      meg_target_tensor.float()],      dim=1)  # (7350, 65)

# ------------------------
# Step 4: Concatenate both datasets
# ------------------------

fused_df = torch.cat([acoustic_full, meg_full], dim=0)  # (14700, 65)

# ------------------------
# Step 5: Separate features and labels for PyTorch
# ------------------------

X = fused_df[:, :-1].float()   # Features (32D) -> float32
y = fused_df[:, -1].long()     # Target -> int32

# ------------------------
# Step 6: Print shapes and dtypes
# ------------------------

print(f"Features shape: {X.shape}, dtype: {X.dtype}")  # (14700, 32), float32
print(f"Labels shape: {y.shape}, dtype: {y.dtype}")    # (14700,), int32

Features shape: torch.Size([320, 32]), dtype: torch.float32
Labels shape: torch.Size([320]), dtype: torch.int64

In [7]:
import torch
import pandas as pd

# fused_df shape = (14700, 33)

# Step 6: Convert fused tensor to numpy
fused_df_np = fused_df.numpy()

# Step 7: Create correct column names for 32 latent features + 1 label
feature_names = [f"feat_{i}" for i in range(32)]
feature_names.append("PD_Label_Combined")

# Step 8: Convert to DataFrame
fused_df_named = pd.DataFrame(fused_df_np, columns=feature_names)

# Step 9: Verify
print(fused_df_named.shape)
print(fused_df_named.head())
print(fused_df_named.tail())

(320, 33)
     feat_0    feat_1    feat_2    feat_3    feat_4    feat_5    feat_6  \
0 -0.090532 -0.299824  0.162386 -0.197490  0.124908 -0.170494 -0.033195
1 -0.073853 -0.313330  0.185814 -0.212945  0.160580 -0.160358 -0.013756
2 -0.193478 -0.251246 -0.036881 -0.116005 -0.128935 -0.051564 -0.276141
3 -0.111925 -0.333076  0.158121 -0.207150  0.119648 -0.148717 -0.078786
4 -0.110957 -0.326688  0.154037 -0.204938  0.107521 -0.152203 -0.081005

     feat_7    feat_8    feat_9  ...   feat_23   feat_24   feat_25   feat_26  \
0 -0.031910 -0.016706 -0.020094  ...  0.001866 -0.083015 -0.238879  0.288587
1 -0.039369 -0.041299 -0.045408  ... -0.022062 -0.084012 -0.258180  0.283961
2 -0.006460 -0.029725 -0.151767  ...  0.238209 -0.338960 -0.093122  0.122698
3 -0.030877 -0.028395 -0.063987  ...  0.044652 -0.134609 -0.255564  0.279587
4 -0.030716 -0.017285 -0.057762  ...  0.047257 -0.134722 -0.245655  0.280771

    feat_27   feat_28   feat_29   feat_30   feat_31  PD_Label_Combined
0  0.030100 -0.165922 -0.126996 -0.045287  0.119898                1.0
1  0.050136 -0.149453 -0.093379 -0.067003  0.123643                1.0
2 -0.219179 -0.059170 -0.237814  0.107825  0.164711                0.0
3  0.020171 -0.127921 -0.113286 -0.039158  0.138688                1.0
4  0.008701 -0.138115 -0.125035 -0.032635  0.139875                1.0

[5 rows x 33 columns]
       feat_0    feat_1    feat_2    feat_3    feat_4    feat_5    feat_6  \
315 -0.194939 -0.310531  0.044625 -0.177371 -0.006899 -0.049486 -0.161243
316 -0.177222 -0.165664  0.169291 -0.265381  0.075992 -0.136585 -0.219230
317 -0.235808 -0.300868  0.029165 -0.160141  0.020594 -0.094110 -0.148251
318 -0.251440 -0.304226  0.069079 -0.157896  0.018405 -0.062438 -0.178305
319 -0.153560 -0.283591  0.055179 -0.219570 -0.015760 -0.094311 -0.156425

       feat_7    feat_8    feat_9  ...   feat_23   feat_24   feat_25  \
315 -0.036856 -0.161389 -0.167679  ...  0.153687 -0.282625 -0.160439
316 -0.059929 -0.156218 -0.104975  ... -0.048616 -0.105584 -0.314289
317 -0.002809 -0.121865 -0.129139  ...  0.028494 -0.128619 -0.199108
318 -0.007634 -0.167179 -0.167412  ...  0.162970 -0.227537 -0.210729
319 -0.066939 -0.118262 -0.162674  ...  0.108072 -0.206402 -0.183711

      feat_26   feat_27   feat_28   feat_29   feat_30   feat_31  \
315  0.193837 -0.117699 -0.093492 -0.215604  0.066064  0.167212
316  0.264744 -0.047622  0.015402 -0.048774 -0.039498  0.129536
317  0.133960 -0.083980 -0.088645 -0.176633 -0.034053  0.128382
318  0.156673 -0.139502 -0.035874 -0.211264  0.012815  0.143879
319  0.225317 -0.077283 -0.094471 -0.168016  0.079864  0.182930

     PD_Label_Combined
315                0.0
316                1.0
317                0.0
318                0.0
319                1.0

[5 rows x 33 columns]

In [8]:
# Make a copy to be safe (optional)
fused_df_named_int = fused_df_named.copy()

# Convert only the last column to int
fused_df_named_int['PD_Label_Combined'] = fused_df_named_int['PD_Label_Combined'].astype(int)

# Verify
print(fused_df_named_int.dtypes)
print(fused_df_named_int.head())

feat_0               float32
feat_1               float32
feat_2               float32
feat_3               float32
feat_4               float32
feat_5               float32
feat_6               float32
feat_7               float32
feat_8               float32
feat_9               float32
feat_10              float32
feat_11              float32
feat_12              float32
feat_13              float32
feat_14              float32
feat_15              float32
feat_16              float32
feat_17              float32
feat_18              float32
feat_19              float32
feat_20              float32
feat_21              float32
feat_22              float32
feat_23              float32
feat_24              float32
feat_25              float32
feat_26              float32
feat_27              float32
feat_28              float32
feat_29              float32
feat_30              float32
feat_31              float32
PD_Label_Combined      int64
dtype: object
     feat_0    feat_1    feat_2    feat_3    feat_4    feat_5    feat_6  \
0 -0.090532 -0.299824  0.162386 -0.197490  0.124908 -0.170494 -0.033195
1 -0.073853 -0.313330  0.185814 -0.212945  0.160580 -0.160358 -0.013756
2 -0.193478 -0.251246 -0.036881 -0.116005 -0.128935 -0.051564 -0.276141
3 -0.111925 -0.333076  0.158121 -0.207150  0.119648 -0.148717 -0.078786
4 -0.110957 -0.326688  0.154037 -0.204938  0.107521 -0.152203 -0.081005

     feat_7    feat_8    feat_9  ...   feat_23   feat_24   feat_25   feat_26  \
0 -0.031910 -0.016706 -0.020094  ...  0.001866 -0.083015 -0.238879  0.288587
1 -0.039369 -0.041299 -0.045408  ... -0.022062 -0.084012 -0.258180  0.283961
2 -0.006460 -0.029725 -0.151767  ...  0.238209 -0.338960 -0.093122  0.122698
3 -0.030877 -0.028395 -0.063987  ...  0.044652 -0.134609 -0.255564  0.279587
4 -0.030716 -0.017285 -0.057762  ...  0.047257 -0.134722 -0.245655  0.280771

    feat_27   feat_28   feat_29   feat_30   feat_31  PD_Label_Combined
0  0.030100 -0.165922 -0.126996 -0.045287  0.119898                  1
1  0.050136 -0.149453 -0.093379 -0.067003  0.123643                  1
2 -0.219179 -0.059170 -0.237814  0.107825  0.164711                  0
3  0.020171 -0.127921 -0.113286 -0.039158  0.138688                  1
4  0.008701 -0.138115 -0.125035 -0.032635  0.139875                  1

[5 rows x 33 columns]

In [9]:
# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [10]:
import pandas as pd

fused_df_named_int.to_csv('/content/drive//MyDrive/Subject-level-fused_df_Baseline_SCL_frest_data_5-fold_cross_validation.csv', index=False)

In [1]:
# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

fused_df_named_int = pd.read_csv('/content/drive//MyDrive/Subject-level-fused_df_Baseline_SCL_frest_data_5-fold_cross_validation.csv')
fused_df_named_int.head()

,feat_0,feat_1,feat_2,feat_3,feat_4,feat_5,feat_6,feat_7,feat_8,feat_9,...,feat_23,feat_24,feat_25,feat_26,feat_27,feat_28,feat_29,feat_30,feat_31,PD_Label_Combined
0,-0.090532,-0.299824,0.162386,-0.197490,0.124908,-0.170494,-0.033195,-0.031910,-0.016706,-0.020094,...,0.001866,-0.083015,-0.238879,0.288587,0.030100,-0.165922,-0.126996,-0.045287,0.119898,1
1,-0.073853,-0.313330,0.185814,-0.212945,0.160580,-0.160358,-0.013756,-0.039369,-0.041299,-0.045408,...,-0.022062,-0.084012,-0.258180,0.283961,0.050136,-0.149453,-0.093379,-0.067003,0.123643,1
2,-0.193478,-0.251246,-0.036881,-0.116005,-0.128935,-0.051564,-0.276141,-0.006460,-0.029725,-0.151767,...,0.238209,-0.338960,-0.093122,0.122698,-0.219179,-0.059170,-0.237814,0.107825,0.164711,0
3,-0.111925,-0.333076,0.158121,-0.207150,0.119648,-0.148717,-0.078786,-0.030877,-0.028395,-0.063987,...,0.044652,-0.134609,-0.255564,0.279587,0.020171,-0.127921,-0.113286,-0.039158,0.138688,1
4,-0.110957,-0.326688,0.154037,-0.204938,0.107521,-0.152203,-0.081005,-0.030716,-0.017285,-0.057762,...,0.047257,-0.134722,-0.245655,0.280772,0.008701,-0.138115,-0.125035,-0.032635,0.139875,1

Evaluation

In [3]:
# ============================================================
# ###8)###
# ENSEMBLE CLASSIFICATION WITH STRATIFIED 10-FOLD CV
# ============================================================

# ------------------ Install Required Packages ------------------

!pip install xgboost lightgbm catboost scikit-learn statsmodels matplotlib seaborn --quiet


# ------------------ Imports ------------------

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.utils.class_weight import compute_class_weight

from sklearn.model_selection import (
    train_test_split,
    StratifiedKFold
)

from sklearn.preprocessing import StandardScaler

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    balanced_accuracy_score,
    matthews_corrcoef,
    confusion_matrix
)

from sklearn.ensemble import (
    VotingClassifier,
    StackingClassifier,
    RandomForestClassifier,
    HistGradientBoostingClassifier
)

from sklearn.linear_model import LogisticRegression

from xgboost import XGBClassifier

from statsmodels.stats.proportion import proportion_confint


# ============================================================
# STEP 1: PREPARE DATA
# ============================================================

X = fused_df_named_int[
    [f'feat_{i}' for i in range(32)]
].copy()

y = fused_df_named_int[
    "PD_Label_Combined"
].copy()


# ------------------ Convert X to numeric ------------------

X = X.apply(
    pd.to_numeric,
    errors='coerce'
)

X.fillna(
    0,
    inplace=True
)


# ============================================================
# STEP 2: CLASS WEIGHTS
# ============================================================

classes = np.unique(y)

class_weights = compute_class_weight(
    class_weight='balanced',
    classes=classes,
    y=y
)

class_weights_dict = {
    int(classes[0]): float(class_weights[0]),
    int(classes[1]): float(class_weights[1])
}

print("\nClass Weights:")
print(class_weights_dict)


# ============================================================
# STEP 3: TRAIN-TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=42
)


print("\nTrain Shape :", X_train.shape)
print("Test Shape  :", X_test.shape)

print("\nTraining Class Distribution:")
print(y_train.value_counts())

print("\nTesting Class Distribution:")
print(y_test.value_counts())


# ============================================================
# STEP 4: HANDLE CLASS IMBALANCE
# ============================================================

cw = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_train),
    y=y_train
)

cw_dict = dict(
    zip(
        np.unique(y_train),
        cw
    )
)

scale_pos_weight = (
    cw[1] / cw[0]
)

print("\nTraining Class Weights:")
print(cw_dict)

print(
    "\nXGBoost scale_pos_weight:",
    scale_pos_weight
)


# ============================================================
# STEP 5: BASE MODEL CREATION FUNCTION
# ============================================================

def create_models():

    # ---------------- XGBoost ----------------

    xgb = XGBClassifier(
        n_estimators=200,
        max_depth=4,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,

        scale_pos_weight=scale_pos_weight,

        eval_metric='logloss',

        random_state=42,
        n_jobs=-1
    )


    # ---------------- Random Forest ----------------

    rf = RandomForestClassifier(
        n_estimators=200,

        class_weight='balanced',

        random_state=42,
        n_jobs=-1
    )


    # ---------------- HistGradientBoosting ----------------

    hgb = HistGradientBoostingClassifier(
        max_iter=200,
        learning_rate=0.05,
        max_leaf_nodes=31,

        class_weight='balanced',

        random_state=42
    )


    return xgb, rf, hgb


# ============================================================
# STEP 6: STRATIFIED 10-FOLD CV
# ============================================================

skf = StratifiedKFold(
    n_splits=10,
    shuffle=True,
    random_state=42
)


# ============================================================
# STEP 7: EVALUATION FUNCTION
# ============================================================

def evaluate_model(model_name):

    # ========================================================
    # CV METRIC STORAGE
    # ========================================================

    cv_accuracy = []
    cv_precision = []
    cv_sensitivity = []
    cv_f1 = []
    cv_auc = []
    cv_balanced_accuracy = []


    # ========================================================
    # 10-FOLD STRATIFIED CROSS-VALIDATION
    # ========================================================

    for fold, (train_idx, val_idx) in enumerate(
        skf.split(X_train, y_train),
        start=1
    ):

        print(
            f"\n{model_name} | Fold {fold}/10"
        )


        # ----------------------------------------------------
        # Split fold
        # ----------------------------------------------------

        X_tr = X_train.iloc[
            train_idx
        ]

        X_val = X_train.iloc[
            val_idx
        ]

        y_tr = y_train.iloc[
            train_idx
        ]

        y_val = y_train.iloc[
            val_idx
        ]


        # ----------------------------------------------------
        # Scaling INSIDE EACH FOLD
        # ----------------------------------------------------

        scaler = StandardScaler()

        X_tr_scaled = scaler.fit_transform(
            X_tr
        )

        X_val_scaled = scaler.transform(
            X_val
        )


        # ----------------------------------------------------
        # Create FRESH models for every fold
        # ----------------------------------------------------

        xgb, rf, hgb = create_models()


        # ----------------------------------------------------
        # Select requested model
        # ----------------------------------------------------

        if model_name == "XGBoost":

            model = xgb


        elif model_name == "Random Forest":

            model = rf


        elif model_name == "HistGradientBoosting":

            model = hgb


        elif model_name == "Voting Fusion":

            model = VotingClassifier(
                estimators=[
                    ('xgb', xgb),
                    ('rf', rf),
                    ('hgb', hgb)
                ],
                voting='soft'
            )


        elif model_name == "Stacking Fusion":

            model = StackingClassifier(
                estimators=[
                    ('xgb', xgb),
                    ('rf', rf),
                    ('hgb', hgb)
                ],

                final_estimator=LogisticRegression(
                    max_iter=1000,
                    class_weight='balanced'
                ),

                passthrough=True,

                cv=5
            )


        else:

            raise ValueError(
                f"Unknown model: {model_name}"
            )


        # ----------------------------------------------------
        # Train fold
        # ----------------------------------------------------

        model.fit(
            X_tr_scaled,
            y_tr
        )


        # ----------------------------------------------------
        # Validation predictions
        # ----------------------------------------------------

        val_preds = model.predict(
            X_val_scaled
        )

        val_probs = model.predict_proba(
            X_val_scaled
        )[:, 1]


        # ----------------------------------------------------
        # Fold metrics
        # ----------------------------------------------------

        fold_accuracy = accuracy_score(
            y_val,
            val_preds
        )

        fold_precision = precision_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_sensitivity = recall_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_f1 = f1_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_auc = roc_auc_score(
            y_val,
            val_probs
        )

        fold_balanced_accuracy = balanced_accuracy_score(
            y_val,
            val_preds
        )


        # ----------------------------------------------------
        # Store fold metrics
        # ----------------------------------------------------

        cv_accuracy.append(
            fold_accuracy
        )

        cv_precision.append(
            fold_precision
        )

        cv_sensitivity.append(
            fold_sensitivity
        )

        cv_f1.append(
            fold_f1
        )

        cv_auc.append(
            fold_auc
        )

        cv_balanced_accuracy.append(
            fold_balanced_accuracy
        )


        # ----------------------------------------------------
        # Print fold result
        # ----------------------------------------------------

        print(
            f"Accuracy            : {fold_accuracy:.4f}"
        )

        print(
            f"Precision           : {fold_precision:.4f}"
        )

        print(
            f"Sensitivity         : {fold_sensitivity:.4f}"
        )

        print(
            f"F1 Score            : {fold_f1:.4f}"
        )

        print(
            f"ROC-AUC             : {fold_auc:.4f}"
        )

        print(
            f"Balanced Accuracy   : "
            f"{fold_balanced_accuracy:.4f}"
        )


    # ========================================================
    # CV MEAN RESULTS
    # ========================================================

    cv_accuracy_mean = np.mean(
        cv_accuracy
    )

    cv_precision_mean = np.mean(
        cv_precision
    )

    cv_sensitivity_mean = np.mean(
        cv_sensitivity
    )

    cv_f1_mean = np.mean(
        cv_f1
    )

    cv_auc_mean = np.mean(
        cv_auc
    )

    cv_balanced_accuracy_mean = np.mean(
        cv_balanced_accuracy
    )


    # ========================================================
    # CROSS-VALIDATION RESULTS
    # ========================================================

    print(
        "\n================================================"
    )

    print(
        f"{model_name} - Cross-Validation (10-fold)"
    )

    print(
        "================================================"
    )

    print(
        f"Accuracy            : "
        f"{cv_accuracy_mean:.4f}"
    )

    print(
        f"Precision           : "
        f"{cv_precision_mean:.4f}"
    )

    print(
        f"Recall/Sensitivity  : "
        f"{cv_sensitivity_mean:.4f}"
    )

    print(
        f"F1 Score            : "
        f"{cv_f1_mean:.4f}"
    )

    print(
        f"ROC-AUC             : "
        f"{cv_auc_mean:.4f}"
    )

    print(
        f"Balanced Accuracy   : "
        f"{cv_balanced_accuracy_mean:.4f}"
    )


    # ========================================================
    # TRAIN FINAL MODEL ON COMPLETE TRAINING SET
    # ========================================================

    final_scaler = StandardScaler()

    X_train_final_scaled = final_scaler.fit_transform(
        X_train
    )

    X_test_final_scaled = final_scaler.transform(
        X_test
    )


    # --------------------------------------------------------
    # Create fresh final models
    # --------------------------------------------------------

    xgb, rf, hgb = create_models()


    if model_name == "XGBoost":

        final_model = xgb


    elif model_name == "Random Forest":

        final_model = rf


    elif model_name == "HistGradientBoosting":

        final_model = hgb


    elif model_name == "Voting Fusion":

        final_model = VotingClassifier(
            estimators=[
                ('xgb', xgb),
                ('rf', rf),
                ('hgb', hgb)
            ],
            voting='soft'
        )


    elif model_name == "Stacking Fusion":

        final_model = StackingClassifier(
            estimators=[
                ('xgb', xgb),
                ('rf', rf),
                ('hgb', hgb)
            ],

            final_estimator=LogisticRegression(
                max_iter=1000,
                class_weight='balanced'
            ),

            passthrough=True,

            cv=5
        )


    # ========================================================
    # FINAL TRAINING
    # ========================================================

    final_model.fit(
        X_train_final_scaled,
        y_train
    )


    # ========================================================
    # TEST PREDICTIONS
    # ========================================================

    test_preds = final_model.predict(
        X_test_final_scaled
    )

    test_probs = final_model.predict_proba(
        X_test_final_scaled
    )[:, 1]


    # ========================================================
    # TEST METRICS
    # ========================================================

    accuracy = accuracy_score(
        y_test,
        test_preds
    )

    precision = precision_score(
        y_test,
        test_preds,
        zero_division=0
    )

    sensitivity = recall_score(
        y_test,
        test_preds,
        zero_division=0
    )

    f1 = f1_score(
        y_test,
        test_preds,
        zero_division=0
    )

    roc_auc = roc_auc_score(
        y_test,
        test_probs
    )

    balanced_accuracy = balanced_accuracy_score(
        y_test,
        test_preds
    )

    mcc = matthews_corrcoef(
        y_test,
        test_preds
    )


    # ========================================================
    # CONFUSION MATRIX
    # ========================================================

    cm = confusion_matrix(
        y_test,
        test_preds,
        labels=[0, 1]
    )

    tn, fp, fn, tp = cm.ravel()


    # ========================================================
    # SENSITIVITY / SPECIFICITY
    # ========================================================

    sensitivity = (
        tp / (tp + fn)
        if (tp + fn) > 0
        else 0
    )

    specificity = (
        tn / (tn + fp)
        if (tn + fp) > 0
        else 0
    )


    # ========================================================
    # 95% CONFIDENCE INTERVALS
    # ========================================================

    # ---------------- Accuracy CI ----------------

    acc_low, acc_high = proportion_confint(
        count=int(round(accuracy * len(y_test))),
        nobs=len(y_test),
        alpha=0.05,
        method='wilson'
    )


    # ---------------- Precision CI ----------------

    precision_low, precision_high = proportion_confint(
        count=tp,
        nobs=(tp + fp),
        alpha=0.05,
        method='wilson'
    ) if (tp + fp) > 0 else (0.0, 0.0)


    # ---------------- Sensitivity CI ----------------

    sensitivity_low, sensitivity_high = proportion_confint(
        count=tp,
        nobs=(tp + fn),
        alpha=0.05,
        method='wilson'
    ) if (tp + fn) > 0 else (0.0, 0.0)


    # ---------------- Specificity CI ----------------

    specificity_low, specificity_high = proportion_confint(
        count=tn,
        nobs=(tn + fp),
        alpha=0.05,
        method='wilson'
    ) if (tn + fp) > 0 else (0.0, 0.0)


    # ========================================================
    # TEST SET PERFORMANCE
    # ========================================================

    print(
        "\n================================================"
    )

    print(
        f"{model_name} - Test Set Performance"
    )

    print(
        "================================================"
    )

    print(
        f"Accuracy            : {accuracy:.4f} "
        f"(95% CI: "
        f"{acc_low:.4f}-{acc_high:.4f})"
    )

    print(
        f"Precision           : {precision:.4f} "
        f"(95% CI: "
        f"{precision_low:.4f}-{precision_high:.4f})"
    )

    print(
        f"Sensitivity         : {sensitivity:.4f} "
        f"(95% CI: "
        f"{sensitivity_low:.4f}-{sensitivity_high:.4f})"
    )

    print(
        f"Specificity         : {specificity:.4f} "
        f"(95% CI: "
        f"{specificity_low:.4f}-{specificity_high:.4f})"
    )

    print(
        f"F1 Score            : {f1:.4f}"
    )

    print(
        f"ROC-AUC             : {roc_auc:.4f}"
    )

    print(
        f"Balanced Accuracy   : "
        f"{balanced_accuracy:.4f}"
    )

    print(
        f"MCC                 : {mcc:.4f}"
    )


    # ========================================================
    # CONFUSION MATRIX
    # ========================================================

    print(
        "\nConfusion Matrix:"
    )

    print(cm)

    print(
        "\nTN :", tn
    )

    print(
        "FP :", fp
    )

    print(
        "FN :", fn
    )

    print(
        "TP :", tp
    )


    # ========================================================
    # STORE RESULTS
    # ========================================================

    result = {

        # ---------------- CV ----------------

        "CV Accuracy":
            cv_accuracy_mean,

        "CV Precision":
            cv_precision_mean,

        "CV Sensitivity":
            cv_sensitivity_mean,

        "CV F1":
            cv_f1_mean,

        "CV ROC-AUC":
            cv_auc_mean,

        "CV Balanced Accuracy":
            cv_balanced_accuracy_mean,


        # ---------------- Test ----------------

        "Accuracy":
            accuracy,

        "Accuracy CI Low":
            acc_low,

        "Accuracy CI High":
            acc_high,


        "Precision":
            precision,

        "Precision CI Low":
            precision_low,

        "Precision CI High":
            precision_high,


        "Sensitivity":
            sensitivity,

        "Sensitivity CI Low":
            sensitivity_low,

        "Sensitivity CI High":
            sensitivity_high,


        "Specificity":
            specificity,

        "Specificity CI Low":
            specificity_low,

        "Specificity CI High":
            specificity_high,


        "F1":
            f1,

        "ROC-AUC":
            roc_auc,

        "Balanced Accuracy":
            balanced_accuracy,

        "MCC":
            mcc,


        # ---------------- Confusion Matrix ----------------

        "TN":
            tn,

        "FP":
            fp,

        "FN":
            fn,

        "TP":
            tp
    }


    return result


# ============================================================
# STEP 8: EVALUATE ALL MODELS
# ============================================================

model_names = [
    "XGBoost",
    "Random Forest",
    "HistGradientBoosting",
    "Voting Fusion",
    "Stacking Fusion"
]


results = {}

for name in model_names:

    print(
        "\n\n################################################"
    )

    print(
        f"Evaluating: {name}"
    )

    print(
        "################################################"
    )

    results[name] = evaluate_model(
        name
    )


# ============================================================
# STEP 9: FINAL RESULTS DATAFRAME
# ============================================================

results_df = pd.DataFrame(
    results
).T


# ============================================================
# STEP 10: ORDER RESULTS
# ============================================================

results_df = results_df[
    [

        # ---------------- CV ----------------

        "CV Accuracy",
        "CV Precision",
        "CV Sensitivity",
        "CV F1",
        "CV ROC-AUC",
        "CV Balanced Accuracy",


        # ---------------- Test ----------------

        "Accuracy",
        "Accuracy CI Low",
        "Accuracy CI High",

        "Precision",
        "Precision CI Low",
        "Precision CI High",

        "Sensitivity",
        "Sensitivity CI Low",
        "Sensitivity CI High",

        "Specificity",
        "Specificity CI Low",
        "Specificity CI High",

        "F1",
        "ROC-AUC",
        "Balanced Accuracy",
        "MCC",

        # ---------------- Confusion Matrix ----------------

        "TN",
        "FP",
        "FN",
        "TP"
    ]
]


# ============================================================
# STEP 11: DISPLAY FINAL RESULTS
# ============================================================

print(
    "\n================================================"
)

print(
    "FINAL MODEL COMPARISON"
)

print(
    "================================================\n"
)


display(
    results_df.sort_values(
        by="F1",
        ascending=False
    )
)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 9.2 MB/s eta 0:00:00

Class Weights:
{0: 1.2213740458015268, 1: 0.8465608465608465}

Train Shape : (256, 32)
Test Shape  : (64, 32)

Training Class Distribution:
PD_Label_Combined
1    151
0    105
Name: count, dtype: int64

Testing Class Distribution:
PD_Label_Combined
1    38
0    26
Name: count, dtype: int64

Training Class Weights:
{np.int64(0): np.float64(1.2190476190476192), np.int64(1): np.float64(0.847682119205298)}

XGBoost scale_pos_weight: 0.6953642384105959


################################################
Evaluating: XGBoost
################################################

XGBoost | Fold 1/10
Accuracy            : 0.6538
Precision           : 0.6842
Sensitivity         : 0.8125
F1 Score            : 0.7429
ROC-AUC             : 0.8250
Balanced Accuracy   : 0.6062

XGBoost | Fold 2/10
Accuracy            : 0.6154
Precision           : 0.6667
Sensitivity         : 0.6667
F1 Score            : 0.6667
ROC-AUC             : 0.7212
Balanced Accuracy   : 0.6061

XGBoost | Fold 3/10
Accuracy            : 0.8462
Precision           : 0.8667
Sensitivity         : 0.8667
F1 Score            : 0.8667
ROC-AUC             : 0.9273
Balanced Accuracy   : 0.8424

XGBoost | Fold 4/10
Accuracy            : 0.7308
Precision           : 0.7857
Sensitivity         : 0.7333
F1 Score            : 0.7586
ROC-AUC             : 0.8424
Balanced Accuracy   : 0.7303

XGBoost | Fold 5/10
Accuracy            : 0.8077
Precision           : 0.8125
Sensitivity         : 0.8667
F1 Score            : 0.8387
ROC-AUC             : 0.8667
Balanced Accuracy   : 0.7970

XGBoost | Fold 6/10
Accuracy            : 0.8077
Precision           : 0.8571
Sensitivity         : 0.8000
F1 Score            : 0.8276
ROC-AUC             : 0.8788
Balanced Accuracy   : 0.8091

XGBoost | Fold 7/10
Accuracy            : 0.8000
Precision           : 0.9167
Sensitivity         : 0.7333
F1 Score            : 0.8148
ROC-AUC             : 0.8433
Balanced Accuracy   : 0.8167

XGBoost | Fold 8/10
Accuracy            : 0.7200
Precision           : 0.7500
Sensitivity         : 0.8000
F1 Score            : 0.7742
ROC-AUC             : 0.8933
Balanced Accuracy   : 0.7000

XGBoost | Fold 9/10
Accuracy            : 0.9200
Precision           : 1.0000
Sensitivity         : 0.8667
F1 Score            : 0.9286
ROC-AUC             : 0.9800
Balanced Accuracy   : 0.9333

XGBoost | Fold 10/10
Accuracy            : 0.7600
Precision           : 0.8462
Sensitivity         : 0.7333
F1 Score            : 0.7857
ROC-AUC             : 0.9200
Balanced Accuracy   : 0.7667

================================================
XGBoost - Cross-Validation (10-fold)
================================================
Accuracy            : 0.7662
Precision           : 0.8186
Recall/Sensitivity  : 0.7879
F1 Score            : 0.8004
ROC-AUC             : 0.8698
Balanced Accuracy   : 0.7608

================================================
XGBoost - Test Set Performance
================================================
Accuracy            : 0.7656 (95% CI: 0.6487-0.8525)
Precision           : 0.7674 (95% CI: 0.6226-0.8685)
Sensitivity         : 0.8684 (95% CI: 0.7267-0.9425)
Specificity         : 0.6154 (95% CI: 0.4253-0.7757)
F1 Score            : 0.8148
ROC-AUC             : 0.8259
Balanced Accuracy   : 0.7419
MCC                 : 0.5061

Confusion Matrix:
[[16 10]
 [ 5 33]]

TN : 16
FP : 10
FN : 5
TP : 33


################################################
Evaluating: Random Forest
################################################

Random Forest | Fold 1/10
Accuracy            : 0.6538
Precision           : 0.6842
Sensitivity         : 0.8125
F1 Score            : 0.7429
ROC-AUC             : 0.8250
Balanced Accuracy   : 0.6062

Random Forest | Fold 2/10
Accuracy            : 0.6154
Precision           : 0.6471
Sensitivity         : 0.7333
F1 Score            : 0.6875
ROC-AUC             : 0.7636
Balanced Accuracy   : 0.5939

Random Forest | Fold 3/10
Accuracy            : 0.8462
Precision           : 0.8667
Sensitivity         : 0.8667
F1 Score            : 0.8667
ROC-AUC             : 0.9576
Balanced Accuracy   : 0.8424

Random Forest | Fold 4/10
Accuracy            : 0.7308
Precision           : 0.7857
Sensitivity         : 0.7333
F1 Score            : 0.7586
ROC-AUC             : 0.8606
Balanced Accuracy   : 0.7303

Random Forest | Fold 5/10
Accuracy            : 0.8077
Precision           : 0.8125
Sensitivity         : 0.8667
F1 Score            : 0.8387
ROC-AUC             : 0.9061
Balanced Accuracy   : 0.7970

Random Forest | Fold 6/10
Accuracy            : 0.7692
Precision           : 0.8000
Sensitivity         : 0.8000
F1 Score            : 0.8000
ROC-AUC             : 0.8788
Balanced Accuracy   : 0.7636

Random Forest | Fold 7/10
Accuracy            : 0.7200
Precision           : 0.8333
Sensitivity         : 0.6667
F1 Score            : 0.7407
ROC-AUC             : 0.8300
Balanced Accuracy   : 0.7333

Random Forest | Fold 8/10
Accuracy            : 0.8400
Precision           : 0.8235
Sensitivity         : 0.9333
F1 Score            : 0.8750
ROC-AUC             : 0.9133
Balanced Accuracy   : 0.8167

Random Forest | Fold 9/10
Accuracy            : 0.9200
Precision           : 1.0000
Sensitivity         : 0.8667
F1 Score            : 0.9286
ROC-AUC             : 0.9467
Balanced Accuracy   : 0.9333

Random Forest | Fold 10/10
Accuracy            : 0.8000
Precision           : 0.8571
Sensitivity         : 0.8000
F1 Score            : 0.8276
ROC-AUC             : 0.9333
Balanced Accuracy   : 0.8000

================================================
Random Forest - Cross-Validation (10-fold)
================================================
Accuracy            : 0.7703
Precision           : 0.8110
Recall/Sensitivity  : 0.8079
F1 Score            : 0.8066
ROC-AUC             : 0.8815
Balanced Accuracy   : 0.7617

================================================
Random Forest - Test Set Performance
================================================
Accuracy            : 0.7500 (95% CI: 0.6318-0.8399)
Precision           : 0.7619 (95% CI: 0.6147-0.8652)
Sensitivity         : 0.8421 (95% CI: 0.6958-0.9256)
Specificity         : 0.6154 (95% CI: 0.4253-0.7757)
F1 Score            : 0.8000
ROC-AUC             : 0.8284
Balanced Accuracy   : 0.7287
MCC                 : 0.4731

Confusion Matrix:
[[16 10]
 [ 6 32]]

TN : 16
FP : 10
FN : 6
TP : 32


################################################
Evaluating: HistGradientBoosting
################################################

HistGradientBoosting | Fold 1/10
Accuracy            : 0.6923
Precision           : 0.7222
Sensitivity         : 0.8125
F1 Score            : 0.7647
ROC-AUC             : 0.8125
Balanced Accuracy   : 0.6562

HistGradientBoosting | Fold 2/10
Accuracy            : 0.6538
Precision           : 0.7143
Sensitivity         : 0.6667
F1 Score            : 0.6897
ROC-AUC             : 0.7394
Balanced Accuracy   : 0.6515

HistGradientBoosting | Fold 3/10
Accuracy            : 0.8462
Precision           : 0.8235
Sensitivity         : 0.9333
F1 Score            : 0.8750
ROC-AUC             : 0.9394
Balanced Accuracy   : 0.8303

HistGradientBoosting | Fold 4/10
Accuracy            : 0.6538
Precision           : 0.7500
Sensitivity         : 0.6000
F1 Score            : 0.6667
ROC-AUC             : 0.8303
Balanced Accuracy   : 0.6636

HistGradientBoosting | Fold 5/10
Accuracy            : 0.8462
Precision           : 0.8235
Sensitivity         : 0.9333
F1 Score            : 0.8750
ROC-AUC             : 0.9152
Balanced Accuracy   : 0.8303

HistGradientBoosting | Fold 6/10
Accuracy            : 0.8077
Precision           : 0.9167
Sensitivity         : 0.7333
F1 Score            : 0.8148
ROC-AUC             : 0.8606
Balanced Accuracy   : 0.8212

HistGradientBoosting | Fold 7/10
Accuracy            : 0.7600
Precision           : 0.8462
Sensitivity         : 0.7333
F1 Score            : 0.7857
ROC-AUC             : 0.8967
Balanced Accuracy   : 0.7667

HistGradientBoosting | Fold 8/10
Accuracy            : 0.7200
Precision           : 0.7500
Sensitivity         : 0.8000
F1 Score            : 0.7742
ROC-AUC             : 0.8933
Balanced Accuracy   : 0.7000

HistGradientBoosting | Fold 9/10
Accuracy            : 0.9200
Precision           : 0.9333
Sensitivity         : 0.9333
F1 Score            : 0.9333
ROC-AUC             : 0.9533
Balanced Accuracy   : 0.9167

HistGradientBoosting | Fold 10/10
Accuracy            : 0.8400
Precision           : 0.8667
Sensitivity         : 0.8667
F1 Score            : 0.8667
ROC-AUC             : 0.9067
Balanced Accuracy   : 0.8333

================================================
HistGradientBoosting - Cross-Validation (10-fold)
================================================
Accuracy            : 0.7740
Precision           : 0.8146
Recall/Sensitivity  : 0.8012
F1 Score            : 0.8046
ROC-AUC             : 0.8747
Balanced Accuracy   : 0.7670

================================================
HistGradientBoosting - Test Set Performance
================================================
Accuracy            : 0.7500 (95% CI: 0.6318-0.8399)
Precision           : 0.7619 (95% CI: 0.6147-0.8652)
Sensitivity         : 0.8421 (95% CI: 0.6958-0.9256)
Specificity         : 0.6154 (95% CI: 0.4253-0.7757)
F1 Score            : 0.8000
ROC-AUC             : 0.8229
Balanced Accuracy   : 0.7287
MCC                 : 0.4731

Confusion Matrix:
[[16 10]
 [ 6 32]]

TN : 16
FP : 10
FN : 6
TP : 32


################################################
Evaluating: Voting Fusion
################################################

Voting Fusion | Fold 1/10
Accuracy            : 0.6538
Precision           : 0.6842
Sensitivity         : 0.8125
F1 Score            : 0.7429
ROC-AUC             : 0.8187
Balanced Accuracy   : 0.6062

Voting Fusion | Fold 2/10
Accuracy            : 0.6154
Precision           : 0.6667
Sensitivity         : 0.6667
F1 Score            : 0.6667
ROC-AUC             : 0.7515
Balanced Accuracy   : 0.6061

Voting Fusion | Fold 3/10
Accuracy            : 0.8462
Precision           : 0.8235
Sensitivity         : 0.9333
F1 Score            : 0.8750
ROC-AUC             : 0.9394
Balanced Accuracy   : 0.8303

Voting Fusion | Fold 4/10
Accuracy            : 0.6538
Precision           : 0.7500
Sensitivity         : 0.6000
F1 Score            : 0.6667
ROC-AUC             : 0.8485
Balanced Accuracy   : 0.6636

Voting Fusion | Fold 5/10
Accuracy            : 0.8077
Precision           : 0.8125
Sensitivity         : 0.8667
F1 Score            : 0.8387
ROC-AUC             : 0.9091
Balanced Accuracy   : 0.7970

Voting Fusion | Fold 6/10
Accuracy            : 0.7692
Precision           : 0.8000
Sensitivity         : 0.8000
F1 Score            : 0.8000
ROC-AUC             : 0.8848
Balanced Accuracy   : 0.7636

Voting Fusion | Fold 7/10
Accuracy            : 0.8000
Precision           : 0.9167
Sensitivity         : 0.7333
F1 Score            : 0.8148
ROC-AUC             : 0.8500
Balanced Accuracy   : 0.8167

Voting Fusion | Fold 8/10
Accuracy            : 0.7200
Precision           : 0.7500
Sensitivity         : 0.8000
F1 Score            : 0.7742
ROC-AUC             : 0.9000
Balanced Accuracy   : 0.7000

Voting Fusion | Fold 9/10
Accuracy            : 0.9200
Precision           : 1.0000
Sensitivity         : 0.8667
F1 Score            : 0.9286
ROC-AUC             : 0.9600
Balanced Accuracy   : 0.9333

Voting Fusion | Fold 10/10
Accuracy            : 0.8400
Precision           : 0.8667
Sensitivity         : 0.8667
F1 Score            : 0.8667
ROC-AUC             : 0.9200
Balanced Accuracy   : 0.8333

================================================
Voting Fusion - Cross-Validation (10-fold)
================================================
Accuracy            : 0.7626
Precision           : 0.8070
Recall/Sensitivity  : 0.7946
F1 Score            : 0.7974
ROC-AUC             : 0.8782
Balanced Accuracy   : 0.7550

================================================
Voting Fusion - Test Set Performance
================================================
Accuracy            : 0.7188 (95% CI: 0.5987-0.8141)
Precision           : 0.7381 (95% CI: 0.5893-0.8470)
Sensitivity         : 0.8158 (95% CI: 0.6658-0.9078)
Specificity         : 0.5769 (95% CI: 0.3895-0.7446)
F1 Score            : 0.7750
ROC-AUC             : 0.8300
Balanced Accuracy   : 0.6964
MCC                 : 0.4061

Confusion Matrix:
[[15 11]
 [ 7 31]]

TN : 15
FP : 11
FN : 7
TP : 31


################################################
Evaluating: Stacking Fusion
################################################

Stacking Fusion | Fold 1/10
Accuracy            : 0.6538
Precision           : 0.7059
Sensitivity         : 0.7500
F1 Score            : 0.7273
ROC-AUC             : 0.7688
Balanced Accuracy   : 0.6250

Stacking Fusion | Fold 2/10
Accuracy            : 0.6154
Precision           : 0.6923
Sensitivity         : 0.6000
F1 Score            : 0.6429
ROC-AUC             : 0.7394
Balanced Accuracy   : 0.6182

Stacking Fusion | Fold 3/10
Accuracy            : 0.8462
Precision           : 0.9231
Sensitivity         : 0.8000
F1 Score            : 0.8571
ROC-AUC             : 0.9455
Balanced Accuracy   : 0.8545

Stacking Fusion | Fold 4/10
Accuracy            : 0.6923
Precision           : 0.8889
Sensitivity         : 0.5333
F1 Score            : 0.6667
ROC-AUC             : 0.7939
Balanced Accuracy   : 0.7212

Stacking Fusion | Fold 5/10
Accuracy            : 0.8462
Precision           : 0.9231
Sensitivity         : 0.8000
F1 Score            : 0.8571
ROC-AUC             : 0.9152
Balanced Accuracy   : 0.8545

Stacking Fusion | Fold 6/10
Accuracy            : 0.6923
Precision           : 0.8182
Sensitivity         : 0.6000
F1 Score            : 0.6923
ROC-AUC             : 0.8848
Balanced Accuracy   : 0.7091

Stacking Fusion | Fold 7/10
Accuracy            : 0.8000
Precision           : 0.9167
Sensitivity         : 0.7333
F1 Score            : 0.8148
ROC-AUC             : 0.8900
Balanced Accuracy   : 0.8167

Stacking Fusion | Fold 8/10
Accuracy            : 0.8000
Precision           : 0.8125
Sensitivity         : 0.8667
F1 Score            : 0.8387
ROC-AUC             : 0.8733
Balanced Accuracy   : 0.7833

Stacking Fusion | Fold 9/10
Accuracy            : 0.8000
Precision           : 1.0000
Sensitivity         : 0.6667
F1 Score            : 0.8000
ROC-AUC             : 0.9733
Balanced Accuracy   : 0.8333

Stacking Fusion | Fold 10/10
Accuracy            : 0.8000
Precision           : 0.9167
Sensitivity         : 0.7333
F1 Score            : 0.8148
ROC-AUC             : 0.9467
Balanced Accuracy   : 0.8167

================================================
Stacking Fusion - Cross-Validation (10-fold)
================================================
Accuracy            : 0.7546
Precision           : 0.8597
Recall/Sensitivity  : 0.7083
F1 Score            : 0.7712
ROC-AUC             : 0.8731
Balanced Accuracy   : 0.7633

================================================
Stacking Fusion - Test Set Performance
================================================
Accuracy            : 0.8281 (95% CI: 0.7179-0.9012)
Precision           : 0.8462 (95% CI: 0.7027-0.9275)
Sensitivity         : 0.8684 (95% CI: 0.7267-0.9425)
Specificity         : 0.7692 (95% CI: 0.5795-0.8897)
F1 Score            : 0.8571
ROC-AUC             : 0.8725
Balanced Accuracy   : 0.8188
MCC                 : 0.6419

Confusion Matrix:
[[20  6]
 [ 5 33]]

TN : 20
FP : 6
FN : 5
TP : 33

================================================
FINAL MODEL COMPARISON
================================================

,CV Accuracy,CV Precision,CV Sensitivity,CV F1,CV ROC-AUC,CV Balanced Accuracy,Accuracy,Accuracy CI Low,Accuracy CI High,Precision,...,Specificity CI Low,Specificity CI High,F1,ROC-AUC,Balanced Accuracy,MCC,TN,FP,FN,TP
Stacking Fusion,0.754615,0.859725,0.708333,0.771173,0.873087,0.763258,0.828125,0.717868,0.901223,0.846154,...,0.579484,0.889662,0.857143,0.872470,0.818826,0.641889,20.0,6.0,5.0,33.0
XGBoost,0.766154,0.818572,0.787917,0.800440,0.869803,0.760777,0.765625,0.648667,0.852501,0.767442,...,0.425349,0.775714,0.814815,0.825911,0.741903,0.506064,16.0,10.0,5.0,33.0
Random Forest,0.770308,0.811016,0.807917,0.806625,0.881500,0.761686,0.750000,0.631837,0.839851,0.761905,...,0.425349,0.775714,0.800000,0.828441,0.728745,0.473068,16.0,10.0,6.0,32.0
HistGradientBoosting,0.774000,0.814639,0.801250,0.804575,0.874735,0.766989,0.750000,0.631837,0.839851,0.761905,...,0.425349,0.775714,0.800000,0.822874,0.728745,0.473068,16.0,10.0,6.0,32.0
Voting Fusion,0.762615,0.807024,0.794583,0.797415,0.878208,0.755019,0.718750,0.598661,0.814066,0.738095,...,0.389486,0.744556,0.775000,0.829960,0.696356,0.406085,15.0,11.0,7.0,31.0