***MIRA-Net***

In [1]:
# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd

df_acoustic_top7 = pd.read_csv('/content/drive/MyDrive/Acoustic-subject-level-dataset_top7.csv')
df_acoustic_top7 = df_acoustic_top7.drop(columns=['Participant_ID'])
print(df_acoustic_top7.shape)
print(df_acoustic_top7.head())

(193, 8)
       RPDE  Degree-voice breaks  Delta2  Delta3  Delta11  MFCC5   spread1  \
0  0.428488                  0.0     0.0     0.0      0.0    0.0 -4.239926
1  0.542488                  0.0     0.0     0.0      0.0    0.0 -4.519291
2  0.332247                  0.0     0.0     0.0      0.0    0.0 -7.226125
3  0.498593                  0.0     0.0     0.0      0.0    0.0 -5.632290
4  0.470775                  0.0     0.0     0.0      0.0    0.0 -5.523149

   Status
0       1
1       1
2       0
3       1
4       1

In [4]:
import pandas as pd

final_meg_df = pd.read_csv('/content/drive/MyDrive/final_meg-go(par)_top7_rfc+shap_10-fold_analysis_last_column.csv')

print("Loaded data shape:", final_meg_df.shape)
print(final_meg_df.head())

Loaded data shape: (127, 8)
   env_kurt_R_mean  env_kurt_R_std  env_kurt_L_mean  env_kurt_L_std  \
0         5.749049       15.894836         5.962378       17.165772
1         4.459546        7.184608         4.390848        6.578943
2         1.161476        0.718562         1.885349        1.714298
3         1.138575        0.699601         1.365950        0.817770
4     18283.789736     4480.567058     18277.357293     4487.602704

   burst_dur_cv_L_std  env_mod_rate_L_std  env_skew_L_mean  PD_Label_Combined
0        4.938551e-02            0.244843         1.123760                  0
1        1.147524e-01            0.117228         1.400286                  0
2        5.040195e-02            0.275503         0.953293                  0
3        4.311462e-02            0.460356         0.920828                  1
4        1.043683e-16            0.064449       129.243639                  1

Advance EDANN+SCL with cross modality & cross participant solution

In [5]:
# ============================================================
#     SIMPLE + STABLE DANN + SCL + MLP CLASSIFIER
#     CROSS-MODAL + CROSS-PARTICIPANT ANALYSIS
# ============================================================

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from torch.autograd import Function
import torch.nn.functional as F

import numpy as np

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# ============================================================
# LOAD DATA
# ============================================================

# First 7 columns -> Features
# Last column     -> PD / HC labels

X_acoustic = df_acoustic_top7.iloc[:, :-1].values.astype(np.float32)
y_acoustic = df_acoustic_top7.iloc[:, -1].values.astype(np.int64)

X_meg = final_meg_df.iloc[:, :-1].values.astype(np.float32)
y_meg = final_meg_df.iloc[:, -1].values.astype(np.int64)

# ============================================================
# STANDARDIZATION
# ============================================================

scaler_acoustic = StandardScaler()
scaler_meg = StandardScaler()

X_acoustic = scaler_acoustic.fit_transform(X_acoustic)
X_meg = scaler_meg.fit_transform(X_meg)

# ============================================================
# DOMAIN LABELS
# ============================================================

# 0 -> Acoustic
# 1 -> MEG

domain_acoustic = np.zeros(len(X_acoustic))
domain_meg = np.ones(len(X_meg))

# ============================================================
# COMBINE
# ============================================================

X_all = np.vstack([
    X_acoustic,
    X_meg
]).astype(np.float32)

task_labels = np.hstack([
    y_acoustic,
    y_meg
]).astype(np.int64)

domain_labels = np.hstack([
    domain_acoustic,
    domain_meg
]).astype(np.int64)

# ============================================================
# TENSORS
# ============================================================

X_all_tensor = torch.tensor(
    X_all
).float().to(device)

task_labels_tensor = torch.tensor(
    task_labels
).long().to(device)

domain_labels_tensor = torch.tensor(
    domain_labels
).long().to(device)

# ============================================================
# GRADIENT REVERSAL
# ============================================================

class GradReverse(Function):

    @staticmethod
    def forward(ctx, x, lambd):

        ctx.lambd = lambd

        return x.view_as(x)

    @staticmethod
    def backward(ctx, grad_output):

        return -ctx.lambd * grad_output, None

def grad_reverse(x, lambd):

    return GradReverse.apply(x, lambd)

# ============================================================
# SIMPLE RESIDUAL BLOCK
# ============================================================

class ResidualBlock(nn.Module):

    def __init__(self, dim):

        super().__init__()

        self.block = nn.Sequential(

            nn.Linear(dim, dim),
            nn.ReLU(),

            nn.Linear(dim, dim)
        )

    def forward(self, x):

        return F.relu(
            self.block(x) + x
        )

# ============================================================
# DANN + SCL MODEL
# ============================================================

class DANNContrastive(nn.Module):

    def __init__(self, input_dim, latent_dim=32):

        super().__init__()

        # ====================================================
        # SIMPLE ENCODER
        # ====================================================

        self.encoder = nn.Sequential(

            nn.Linear(input_dim, 128),
            nn.ReLU(),

            ResidualBlock(128),

            nn.Linear(128, 64),
            nn.ReLU(),

            nn.Dropout(0.1),

            nn.Linear(64, latent_dim)
        )

        # ====================================================
        # TASK HEAD
        # ====================================================

        self.task_head = nn.Sequential(

            nn.Linear(latent_dim, 32),
            nn.ReLU(),

            nn.Dropout(0.2),

            nn.Linear(32, 2)
        )

        # ====================================================
        # DOMAIN HEAD
        # ====================================================

        self.domain_head = nn.Sequential(

            nn.Linear(latent_dim, 16),
            nn.ReLU(),

            nn.Linear(16, 2)
        )

    def forward(self, x, lambd=1.0):

        z = self.encoder(x)

        # L2 NORMALIZATION

        z_norm = F.normalize(
            z,
            p=2,
            dim=1
        )

        # DANN

        rev_z = grad_reverse(
            z_norm,
            lambd
        )

        task_out = self.task_head(z_norm)

        domain_out = self.domain_head(rev_z)

        return task_out, domain_out, z_norm

# ============================================================
# SUPERVISED CONTRASTIVE LOSS
# ============================================================

class SupConLoss(nn.Module):

    def __init__(self, temperature=0.07):

        super().__init__()

        self.temperature = temperature

    def forward(self, features, labels):

        device = features.device

        labels = labels.contiguous().view(-1, 1)

        mask = torch.eq(
            labels,
            labels.T
        ).float().to(device)

        similarity = torch.matmul(
            features,
            features.T
        ) / self.temperature

        logits_max, _ = torch.max(
            similarity,
            dim=1,
            keepdim=True
        )

        logits = similarity - logits_max.detach()

        logits_mask = torch.ones_like(mask) - torch.eye(
            mask.shape[0]
        ).to(device)

        mask = mask * logits_mask

        exp_logits = torch.exp(logits) * logits_mask

        log_prob = logits - torch.log(
            exp_logits.sum(1, keepdim=True) + 1e-8
        )

        mean_log_prob_pos = (
            mask * log_prob
        ).sum(1) / (mask.sum(1) + 1e-8)

        loss = -mean_log_prob_pos.mean()

        return loss

# ============================================================
# DATA LOADER
# ============================================================

dataset = TensorDataset(
    X_all_tensor,
    task_labels_tensor,
    domain_labels_tensor
)

loader = DataLoader(
    dataset,
    batch_size=128,
    shuffle=True
)

# ============================================================
# MODEL
# ============================================================

model = DANNContrastive(
    input_dim=X_all.shape[1],
    latent_dim=32
).to(device)

# ============================================================
# OPTIMIZER
# ============================================================

optimizer = optim.Adam(
    model.parameters(),
    lr=1e-3,
    weight_decay=1e-4
)

# ============================================================
# LOSSES
# ============================================================

task_loss_fn = nn.CrossEntropyLoss()

domain_loss_fn = nn.CrossEntropyLoss()

contrastive_loss_fn = SupConLoss(
    temperature=0.07
)

epochs = 120

print("\nTraining Started...\n")

# ============================================================
# TRAINING
# ============================================================

for epoch in range(epochs):

    model.train()

    total_correct = 0
    total_samples = 0

    # ========================================================
    # WEAKER DANN
    # ========================================================

    p = min(epoch / 50.0, 1.0)

    lambd = 0.25 * (
        2 / (1 + np.exp(-10 * p)) - 1
    )

    for xb, y_task, y_dom in loader:

        optimizer.zero_grad()

        task_out, dom_out, z = model(
            xb,
            lambd
        )

        # ====================================================
        # LOSSES
        # ====================================================

        loss_task = task_loss_fn(
            task_out,
            y_task
        )

        loss_domain = domain_loss_fn(
            dom_out,
            y_dom
        )

        loss_contrastive = contrastive_loss_fn(
            z,
            y_task
        )

        # ====================================================
        # FINAL LOSS
        # ====================================================

        loss = (
            3.0 * loss_task +
            0.25 * loss_domain +
            0.55 * loss_contrastive
        )

        loss.backward()

        optimizer.step()

        preds = task_out.argmax(1)

        total_correct += (
            preds == y_task
        ).sum().item()

        total_samples += len(y_task)

    acc = total_correct / total_samples

    print(
        f"Epoch {epoch+1}/{epochs} "
        f"| λ={lambd:.3f} "
        f"| Acc={acc:.4f}"
    )

# ============================================================
# EXTRACT LATENT FEATURES
# ============================================================

model.eval()

with torch.no_grad():

    fused_acoustic_32D = model(
        torch.tensor(X_acoustic).float().to(device),
        0
    )[2].cpu().numpy()

    fused_meg_32D = model(
        torch.tensor(X_meg).float().to(device),
        0
    )[2].cpu().numpy()

# ============================================================
# COMBINE LATENTS
# ============================================================

X_fused = np.vstack([
    fused_acoustic_32D,
    fused_meg_32D
])

y_fused = np.hstack([
    y_acoustic,
    y_meg
])

# ============================================================
# SIMPLE MLP CLASSIFIER
# ============================================================

class FinalMLP(nn.Module):

    def __init__(self, input_dim=32):

        super().__init__()

        self.net = nn.Sequential(

            nn.Linear(input_dim, 64),
            nn.ReLU(),

            nn.Dropout(0.2),

            nn.Linear(64, 32),
            nn.ReLU(),

            nn.Linear(32, 2)
        )

    def forward(self, x):

        return self.net(x)

# ============================================================
# CROSS PARTICIPANT EVALUATION
# ============================================================

print("\n======================================")
print(" CROSS PARTICIPANT ANALYSIS")
print("======================================\n")

skf = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

accs = []
precs = []
recs = []
f1s = []
aucs = []

fold = 1

for train_idx, test_idx in skf.split(X_fused, y_fused):

    X_train = torch.tensor(
        X_fused[train_idx]
    ).float().to(device)

    X_test = torch.tensor(
        X_fused[test_idx]
    ).float().to(device)

    y_train = torch.tensor(
        y_fused[train_idx]
    ).long().to(device)

    y_test = y_fused[test_idx]

    clf = FinalMLP().to(device)

    optimizer_clf = optim.Adam(
        clf.parameters(),
        lr=1e-3
    )

    criterion = nn.CrossEntropyLoss()

    # ========================================================
    # TRAIN MLP
    # ========================================================

    clf.train()

    for epoch in range(80):

        optimizer_clf.zero_grad()

        outputs = clf(X_train)

        loss = criterion(
            outputs,
            y_train
        )

        loss.backward()

        optimizer_clf.step()

    # ========================================================
    # TEST
    # ========================================================

    clf.eval()

    with torch.no_grad():

        outputs = clf(X_test)

        probs = F.softmax(
            outputs,
            dim=1
        )[:, 1].cpu().numpy()

        preds = outputs.argmax(1).cpu().numpy()

    acc = accuracy_score(y_test, preds)

    prec = precision_score(y_test, preds)

    rec = recall_score(y_test, preds)

    f1 = f1_score(y_test, preds)

    auc = roc_auc_score(y_test, probs)

    accs.append(acc)
    precs.append(prec)
    recs.append(rec)
    f1s.append(f1)
    aucs.append(auc)

    print(f"Fold {fold}")

    print(f"Accuracy  : {acc:.4f}")
    print(f"Precision : {prec:.4f}")
    print(f"Recall    : {rec:.4f}")
    print(f"F1-Score  : {f1:.4f}")
    print(f"AUC       : {auc:.4f}")

    print()

    fold += 1

# ============================================================
# FINAL RESULTS
# ============================================================

print("\n======================================")
print(" FINAL RESULTS")
print("======================================\n")

print(f"Mean Accuracy  : {np.mean(accs)*100:.2f}%")
print(f"Mean Precision : {np.mean(precs)*100:.2f}%")
print(f"Mean Recall    : {np.mean(recs)*100:.2f}%")
print(f"Mean F1-Score  : {np.mean(f1s)*100:.2f}%")
print(f"Mean AUC       : {np.mean(aucs)*100:.2f}%")

print("\n======================================")
print(" LATENT SHAPES")
print("======================================\n")

print("Acoustic :", fused_acoustic_32D.shape)
print("MEG      :", fused_meg_32D.shape)

Training Started...

Epoch 1/120 | λ=0.000 | Acc=0.4094
Epoch 2/120 | λ=0.025 | Acc=0.4094
Epoch 3/120 | λ=0.049 | Acc=0.4094
Epoch 4/120 | λ=0.073 | Acc=0.4094
Epoch 5/120 | λ=0.095 | Acc=0.4406
Epoch 6/120 | λ=0.116 | Acc=0.5375
Epoch 7/120 | λ=0.134 | Acc=0.5375
Epoch 8/120 | λ=0.151 | Acc=0.6188
Epoch 9/120 | λ=0.166 | Acc=0.5813
Epoch 10/120 | λ=0.179 | Acc=0.5813
Epoch 11/120 | λ=0.190 | Acc=0.5906
Epoch 12/120 | λ=0.200 | Acc=0.5844
Epoch 13/120 | λ=0.208 | Acc=0.5938
Epoch 14/120 | λ=0.215 | Acc=0.5938
Epoch 15/120 | λ=0.221 | Acc=0.5906
Epoch 16/120 | λ=0.226 | Acc=0.5875
Epoch 17/120 | λ=0.230 | Acc=0.5938
Epoch 18/120 | λ=0.234 | Acc=0.6000
Epoch 19/120 | λ=0.237 | Acc=0.5906
Epoch 20/120 | λ=0.239 | Acc=0.6031
Epoch 21/120 | λ=0.241 | Acc=0.6062
Epoch 22/120 | λ=0.243 | Acc=0.6250
Epoch 23/120 | λ=0.244 | Acc=0.6125
Epoch 24/120 | λ=0.245 | Acc=0.6281
Epoch 25/120 | λ=0.246 | Acc=0.6531
Epoch 26/120 | λ=0.247 | Acc=0.6594
Epoch 27/120 | λ=0.247 | Acc=0.6562
Epoch 28/120 | λ=0.248 | Acc=0.6625
Epoch 29/120 | λ=0.248 | Acc=0.6906
Epoch 30/120 | λ=0.248 | Acc=0.6750
Epoch 31/120 | λ=0.249 | Acc=0.6906
Epoch 32/120 | λ=0.249 | Acc=0.6937
Epoch 33/120 | λ=0.249 | Acc=0.7344
Epoch 34/120 | λ=0.249 | Acc=0.7500
Epoch 35/120 | λ=0.249 | Acc=0.7188
Epoch 36/120 | λ=0.250 | Acc=0.7156
Epoch 37/120 | λ=0.250 | Acc=0.7375
Epoch 38/120 | λ=0.250 | Acc=0.7312
Epoch 39/120 | λ=0.250 | Acc=0.7438
Epoch 40/120 | λ=0.250 | Acc=0.7531
Epoch 41/120 | λ=0.250 | Acc=0.7500
Epoch 42/120 | λ=0.250 | Acc=0.7719
Epoch 43/120 | λ=0.250 | Acc=0.7531
Epoch 44/120 | λ=0.250 | Acc=0.7594
Epoch 45/120 | λ=0.250 | Acc=0.7344
Epoch 46/120 | λ=0.250 | Acc=0.7469
Epoch 47/120 | λ=0.250 | Acc=0.7469
Epoch 48/120 | λ=0.250 | Acc=0.7500
Epoch 49/120 | λ=0.250 | Acc=0.7500
Epoch 50/120 | λ=0.250 | Acc=0.7719
Epoch 51/120 | λ=0.250 | Acc=0.7594
Epoch 52/120 | λ=0.250 | Acc=0.7500
Epoch 53/120 | λ=0.250 | Acc=0.7594
Epoch 54/120 | λ=0.250 | Acc=0.7688
Epoch 55/120 | λ=0.250 | Acc=0.7469
Epoch 56/120 | λ=0.250 | Acc=0.7406
Epoch 57/120 | λ=0.250 | Acc=0.7750
Epoch 58/120 | λ=0.250 | Acc=0.7688
Epoch 59/120 | λ=0.250 | Acc=0.7531
Epoch 60/120 | λ=0.250 | Acc=0.7625
Epoch 61/120 | λ=0.250 | Acc=0.7562
Epoch 62/120 | λ=0.250 | Acc=0.7906
Epoch 63/120 | λ=0.250 | Acc=0.7875
Epoch 64/120 | λ=0.250 | Acc=0.7688
Epoch 65/120 | λ=0.250 | Acc=0.7719
Epoch 66/120 | λ=0.250 | Acc=0.7812
Epoch 67/120 | λ=0.250 | Acc=0.7500
Epoch 68/120 | λ=0.250 | Acc=0.7750
Epoch 69/120 | λ=0.250 | Acc=0.7562
Epoch 70/120 | λ=0.250 | Acc=0.7875
Epoch 71/120 | λ=0.250 | Acc=0.7688
Epoch 72/120 | λ=0.250 | Acc=0.7688
Epoch 73/120 | λ=0.250 | Acc=0.7875
Epoch 74/120 | λ=0.250 | Acc=0.7719
Epoch 75/120 | λ=0.250 | Acc=0.7781
Epoch 76/120 | λ=0.250 | Acc=0.7844
Epoch 77/120 | λ=0.250 | Acc=0.7594
Epoch 78/120 | λ=0.250 | Acc=0.7781
Epoch 79/120 | λ=0.250 | Acc=0.7656
Epoch 80/120 | λ=0.250 | Acc=0.7750
Epoch 81/120 | λ=0.250 | Acc=0.7719
Epoch 82/120 | λ=0.250 | Acc=0.7688
Epoch 83/120 | λ=0.250 | Acc=0.7750
Epoch 84/120 | λ=0.250 | Acc=0.7812
Epoch 85/120 | λ=0.250 | Acc=0.7812
Epoch 86/120 | λ=0.250 | Acc=0.7688
Epoch 87/120 | λ=0.250 | Acc=0.7812
Epoch 88/120 | λ=0.250 | Acc=0.7750
Epoch 89/120 | λ=0.250 | Acc=0.7812
Epoch 90/120 | λ=0.250 | Acc=0.8063
Epoch 91/120 | λ=0.250 | Acc=0.7750
Epoch 92/120 | λ=0.250 | Acc=0.8031
Epoch 93/120 | λ=0.250 | Acc=0.7719
Epoch 94/120 | λ=0.250 | Acc=0.7906
Epoch 95/120 | λ=0.250 | Acc=0.8063
Epoch 96/120 | λ=0.250 | Acc=0.7625
Epoch 97/120 | λ=0.250 | Acc=0.7688
Epoch 98/120 | λ=0.250 | Acc=0.7906
Epoch 99/120 | λ=0.250 | Acc=0.7812
Epoch 100/120 | λ=0.250 | Acc=0.7906
Epoch 101/120 | λ=0.250 | Acc=0.7812
Epoch 102/120 | λ=0.250 | Acc=0.8000
Epoch 103/120 | λ=0.250 | Acc=0.8094
Epoch 104/120 | λ=0.250 | Acc=0.7937
Epoch 105/120 | λ=0.250 | Acc=0.7750
Epoch 106/120 | λ=0.250 | Acc=0.8125
Epoch 107/120 | λ=0.250 | Acc=0.8063
Epoch 108/120 | λ=0.250 | Acc=0.7812
Epoch 109/120 | λ=0.250 | Acc=0.8063
Epoch 110/120 | λ=0.250 | Acc=0.8125
Epoch 111/120 | λ=0.250 | Acc=0.7594
Epoch 112/120 | λ=0.250 | Acc=0.7969
Epoch 113/120 | λ=0.250 | Acc=0.8063
Epoch 114/120 | λ=0.250 | Acc=0.7906
Epoch 115/120 | λ=0.250 | Acc=0.7875
Epoch 116/120 | λ=0.250 | Acc=0.7844
Epoch 117/120 | λ=0.250 | Acc=0.7906
Epoch 118/120 | λ=0.250 | Acc=0.7844
Epoch 119/120 | λ=0.250 | Acc=0.7969
Epoch 120/120 | λ=0.250 | Acc=0.8125

======================================
 CROSS PARTICIPANT ANALYSIS
======================================

Fold 1
Accuracy  : 0.7188
Precision : 0.8333
Recall    : 0.6579
F1-Score  : 0.7353
AUC       : 0.8421

Fold 2
Accuracy  : 0.7969
Precision : 0.7907
Recall    : 0.8947
F1-Score  : 0.8395
AUC       : 0.8907

Fold 3
Accuracy  : 0.8594
Precision : 0.8718
Recall    : 0.8947
F1-Score  : 0.8831
AUC       : 0.9367

Fold 4
Accuracy  : 0.8750
Precision : 0.8947
Recall    : 0.8947
F1-Score  : 0.8947
AUC       : 0.9342

Fold 5
Accuracy  : 0.7969
Precision : 0.8529
Recall    : 0.7838
F1-Score  : 0.8169
AUC       : 0.8879


======================================
 FINAL RESULTS
======================================

Mean Accuracy  : 80.94%
Mean Precision : 84.87%
Mean Recall    : 82.52%
Mean F1-Score  : 83.39%
Mean AUC       : 89.83%

======================================
 LATENT SHAPES
======================================

Acoustic : (193, 32)
MEG      : (127, 32)

Concatenating acoustic and meg

In [6]:
import torch

# Assuming fused_acoustic_32D and fused_meg_32D are numpy arrays of shape (7350, 32)

# Step 1: Convert numpy arrays to torch tensors (float32)
fused_acoustic_tensor = torch.from_numpy(fused_acoustic_32D).float()
fused_meg_tensor = torch.from_numpy(fused_meg_32D).float()

# Step 2: Concatenate row-wise (along dim=0)
fused_output_tensor = torch.cat([fused_acoustic_tensor, fused_meg_tensor], dim=0)  # Shape: (14700, 32)

# Step 3: Print shape and dtype
print(fused_output_tensor.shape)  # torch.Size([14700, 32])
print(fused_output_tensor.dtype)  # torch.float32

torch.Size([320, 32])
torch.float32

Adding target columns of acoustic & meg

In [7]:
import torch
import numpy as np

# ------------------------
# Step 1: Extract targets correctly
# ------------------------

# Acoustic target from df_acoustic_top7 (last column)
y_acoustic = df_acoustic_top7.iloc[:, -1].values.astype(np.int32)   # (7350,)

# MEG target from final_meg_df (last column)
y_meg = final_meg_df.iloc[:, -1].values.astype(np.int32)           # (7350,)

# Convert to tensors (reshape to column)
acoustic_target_tensor = torch.tensor(y_acoustic).long().reshape(-1, 1)   # (7350, 1)
meg_target_tensor      = torch.tensor(y_meg).long().reshape(-1, 1)        # (7350, 1)

# ------------------------
# Step 2: Convert 32D latent features to tensors
# ------------------------

fused_acoustic_tensor = torch.from_numpy(fused_acoustic_32D).float()  # (7350, 32)
fused_meg_tensor      = torch.from_numpy(fused_meg_32D).float()       # (7350, 32)

# ------------------------
# Step 3: Attach target columns
# ------------------------

# Concatenate latent features with target
acoustic_full = torch.cat([fused_acoustic_tensor, acoustic_target_tensor.float()], dim=1)  # (7350, 65)
meg_full      = torch.cat([fused_meg_tensor,      meg_target_tensor.float()],      dim=1)  # (7350, 65)

# ------------------------
# Step 4: Concatenate both datasets
# ------------------------

fused_df = torch.cat([acoustic_full, meg_full], dim=0)  # (14700, 65)

# ------------------------
# Step 5: Separate features and labels for PyTorch
# ------------------------

X = fused_df[:, :-1].float()   # Features (32D) -> float32
y = fused_df[:, -1].long()     # Target -> int32

# ------------------------
# Step 6: Print shapes and dtypes
# ------------------------

print(f"Features shape: {X.shape}, dtype: {X.dtype}")  # (14700, 32), float32
print(f"Labels shape: {y.shape}, dtype: {y.dtype}")    # (14700,), int32

Features shape: torch.Size([320, 32]), dtype: torch.float32
Labels shape: torch.Size([320]), dtype: torch.int64

In [8]:
import torch
import pandas as pd

# fused_df shape = (14700, 33)

# Step 6: Convert fused tensor to numpy
fused_df_np = fused_df.numpy()

# Step 7: Create correct column names for 32 latent features + 1 label
feature_names = [f"feat_{i}" for i in range(32)]
feature_names.append("PD_Label_Combined")

# Step 8: Convert to DataFrame
fused_df_named = pd.DataFrame(fused_df_np, columns=feature_names)

# Step 9: Verify
print(fused_df_named.shape)
print(fused_df_named.head())
print(fused_df_named.tail())

(320, 33)
     feat_0    feat_1    feat_2    feat_3    feat_4    feat_5    feat_6  \
0 -0.018772  0.079011 -0.231570  0.194846 -0.143616  0.085767 -0.046142
1 -0.011404  0.079184 -0.230050  0.195819 -0.144949  0.090309 -0.078442
2 -0.156525 -0.079700 -0.247852  0.230286  0.047218 -0.055897  0.039394
3 -0.027779  0.062175 -0.234910  0.202834 -0.128086  0.089055 -0.048962
4 -0.030145  0.064047 -0.234835  0.204415 -0.129516  0.085315 -0.038533

     feat_7    feat_8    feat_9  ...   feat_23   feat_24   feat_25   feat_26  \
0 -0.231958 -0.040770 -0.062883  ...  0.170493 -0.104889  0.186469 -0.094237
1 -0.230429 -0.055978 -0.074549  ...  0.171172 -0.114990  0.187813 -0.088468
2 -0.162000  0.117055  0.098641  ...  0.104002 -0.228786  0.166334  0.049440
3 -0.232467 -0.043471 -0.053426  ...  0.163710 -0.108866  0.190487 -0.085083
4 -0.230215 -0.036532 -0.047249  ...  0.164248 -0.109925  0.188674 -0.086853

    feat_27   feat_28   feat_29   feat_30   feat_31  PD_Label_Combined
0  0.189094  0.004586 -0.193345 -0.215038  0.252935                1.0
1  0.175056  0.022514 -0.203139 -0.228855  0.254441                1.0
2  0.104827  0.228946 -0.098359 -0.275248  0.255883                0.0
3  0.180007  0.024549 -0.212170 -0.222989  0.252107                1.0
4  0.184822  0.019620 -0.205970 -0.218949  0.253043                1.0

[5 rows x 33 columns]
       feat_0    feat_1    feat_2    feat_3    feat_4    feat_5    feat_6  \
315 -0.128994 -0.034035 -0.237745  0.224155 -0.023602  0.013575  0.013241
316 -0.080835 -0.002401 -0.241852  0.255833 -0.061573  0.057536 -0.076646
317 -0.114417 -0.034526 -0.246915  0.222497 -0.000537  0.022274 -0.006510
318 -0.112975 -0.032956 -0.246281  0.224330 -0.004673  0.025666 -0.009950
319 -0.121703 -0.030800 -0.228843  0.247985 -0.002989  0.024434 -0.051860

       feat_7    feat_8    feat_9  ...   feat_23   feat_24   feat_25  \
315 -0.202380  0.070248  0.061855  ...  0.134852 -0.212297  0.211628
316 -0.230101 -0.024163  0.058137  ...  0.153164 -0.183919  0.211835
317 -0.188246  0.026615  0.029480  ...  0.136714 -0.200632  0.219132
318 -0.189131  0.022173  0.028904  ...  0.137799 -0.198879  0.220156
319 -0.192313  0.021036  0.074084  ...  0.125089 -0.222523  0.226411

      feat_26   feat_27   feat_28   feat_29   feat_30   feat_31  \
315  0.015921  0.112547  0.176145 -0.127216 -0.283121  0.220656
316 -0.032662  0.156810  0.143883 -0.224260 -0.261217  0.234964
317  0.013093  0.128798  0.179681 -0.159639 -0.300259  0.219541
318  0.010307  0.131764  0.178556 -0.163693 -0.299240  0.221568
319  0.022966  0.115782  0.222468 -0.197564 -0.301250  0.218814

     PD_Label_Combined
315                0.0
316                1.0
317                0.0
318                0.0
319                1.0

[5 rows x 33 columns]

In [9]:
# Make a copy to be safe (optional)
fused_df_named_int = fused_df_named.copy()

# Convert only the last column to int
fused_df_named_int['PD_Label_Combined'] = fused_df_named_int['PD_Label_Combined'].astype(int)

# Verify
print(fused_df_named_int.dtypes)
print(fused_df_named_int.head())

feat_0               float32
feat_1               float32
feat_2               float32
feat_3               float32
feat_4               float32
feat_5               float32
feat_6               float32
feat_7               float32
feat_8               float32
feat_9               float32
feat_10              float32
feat_11              float32
feat_12              float32
feat_13              float32
feat_14              float32
feat_15              float32
feat_16              float32
feat_17              float32
feat_18              float32
feat_19              float32
feat_20              float32
feat_21              float32
feat_22              float32
feat_23              float32
feat_24              float32
feat_25              float32
feat_26              float32
feat_27              float32
feat_28              float32
feat_29              float32
feat_30              float32
feat_31              float32
PD_Label_Combined      int64
dtype: object
     feat_0    feat_1    feat_2    feat_3    feat_4    feat_5    feat_6  \
0 -0.018772  0.079011 -0.231570  0.194846 -0.143616  0.085767 -0.046142
1 -0.011404  0.079184 -0.230050  0.195819 -0.144949  0.090309 -0.078442
2 -0.156525 -0.079700 -0.247852  0.230286  0.047218 -0.055897  0.039394
3 -0.027779  0.062175 -0.234910  0.202834 -0.128086  0.089055 -0.048962
4 -0.030145  0.064047 -0.234835  0.204415 -0.129516  0.085315 -0.038533

     feat_7    feat_8    feat_9  ...   feat_23   feat_24   feat_25   feat_26  \
0 -0.231958 -0.040770 -0.062883  ...  0.170493 -0.104889  0.186469 -0.094237
1 -0.230429 -0.055978 -0.074549  ...  0.171172 -0.114990  0.187813 -0.088468
2 -0.162000  0.117055  0.098641  ...  0.104002 -0.228786  0.166334  0.049440
3 -0.232467 -0.043471 -0.053426  ...  0.163710 -0.108866  0.190487 -0.085083
4 -0.230215 -0.036532 -0.047249  ...  0.164248 -0.109925  0.188674 -0.086853

    feat_27   feat_28   feat_29   feat_30   feat_31  PD_Label_Combined
0  0.189094  0.004586 -0.193345 -0.215038  0.252935                  1
1  0.175056  0.022514 -0.203139 -0.228855  0.254441                  1
2  0.104827  0.228946 -0.098359 -0.275248  0.255883                  0
3  0.180007  0.024549 -0.212170 -0.222989  0.252107                  1
4  0.184822  0.019620 -0.205970 -0.218949  0.253043                  1

[5 rows x 33 columns]

Saving the data

In [10]:
# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [11]:
import pandas as pd

fused_df_named_int.to_csv('/content/drive//MyDrive/Subject-level-fused_fgo_(with_120_epoches)_MIRA-Net_data.csv', index=False)

In [1]:
# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd
fused_df_named_int = pd.read_csv('/content/drive//MyDrive/Subject-level-fused_fgo_(with_120_epoches)_MIRA-Net_data.csv')
fused_df_named_int.head()

,feat_0,feat_1,feat_2,feat_3,feat_4,feat_5,feat_6,feat_7,feat_8,feat_9,...,feat_23,feat_24,feat_25,feat_26,feat_27,feat_28,feat_29,feat_30,feat_31,PD_Label_Combined
0,-0.018772,0.079011,-0.231570,0.194846,-0.143617,0.085767,-0.046142,-0.231958,-0.040770,-0.062883,...,0.170493,-0.104889,0.186469,-0.094237,0.189094,0.004586,-0.193345,-0.215038,0.252935,1
1,-0.011404,0.079184,-0.230050,0.195819,-0.144949,0.090309,-0.078442,-0.230429,-0.055978,-0.074549,...,0.171172,-0.114990,0.187813,-0.088468,0.175056,0.022514,-0.203139,-0.228855,0.254441,1
2,-0.156525,-0.079700,-0.247852,0.230286,0.047218,-0.055897,0.039394,-0.162000,0.117055,0.098641,...,0.104002,-0.228786,0.166334,0.049440,0.104827,0.228946,-0.098359,-0.275248,0.255883,0
3,-0.027779,0.062175,-0.234910,0.202834,-0.128086,0.089055,-0.048962,-0.232467,-0.043471,-0.053426,...,0.163710,-0.108866,0.190487,-0.085083,0.180007,0.024549,-0.212171,-0.222989,0.252107,1
4,-0.030145,0.064047,-0.234835,0.204415,-0.129516,0.085315,-0.038533,-0.230215,-0.036532,-0.047249,...,0.164248,-0.109925,0.188674,-0.086853,0.184822,0.019620,-0.205970,-0.218949,0.253043,1

Evaluation

In [4]:
# ============================================================
# ###8)###
# ENSEMBLE CLASSIFICATION WITH STRATIFIED 10-FOLD CV
# ============================================================

# ------------------ Install Required Packages ------------------

!pip install xgboost lightgbm catboost scikit-learn statsmodels matplotlib seaborn --quiet


# ------------------ Imports ------------------

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.utils.class_weight import compute_class_weight

from sklearn.model_selection import (
    train_test_split,
    StratifiedKFold
)

from sklearn.preprocessing import StandardScaler

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    balanced_accuracy_score,
    matthews_corrcoef,
    confusion_matrix
)

from sklearn.ensemble import (
    VotingClassifier,
    StackingClassifier,
    RandomForestClassifier,
    HistGradientBoostingClassifier
)

from sklearn.linear_model import LogisticRegression

from xgboost import XGBClassifier

from statsmodels.stats.proportion import proportion_confint


# ============================================================
# STEP 1: PREPARE DATA
# ============================================================

X = fused_df_named_int[
    [f'feat_{i}' for i in range(32)]
].copy()

y = fused_df_named_int[
    "PD_Label_Combined"
].copy()


# ------------------ Convert X to numeric ------------------

X = X.apply(
    pd.to_numeric,
    errors='coerce'
)

X.fillna(
    0,
    inplace=True
)


# ============================================================
# STEP 2: CLASS WEIGHTS
# ============================================================

classes = np.unique(y)

class_weights = compute_class_weight(
    class_weight='balanced',
    classes=classes,
    y=y
)

class_weights_dict = {
    int(classes[0]): float(class_weights[0]),
    int(classes[1]): float(class_weights[1])
}

print("\nClass Weights:")
print(class_weights_dict)


# ============================================================
# STEP 3: TRAIN-TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=42
)


print("\nTrain Shape :", X_train.shape)
print("Test Shape  :", X_test.shape)

print("\nTraining Class Distribution:")
print(y_train.value_counts())

print("\nTesting Class Distribution:")
print(y_test.value_counts())


# ============================================================
# STEP 4: HANDLE CLASS IMBALANCE
# ============================================================

cw = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_train),
    y=y_train
)

cw_dict = dict(
    zip(
        np.unique(y_train),
        cw
    )
)

scale_pos_weight = (
    cw[1] / cw[0]
)

print("\nTraining Class Weights:")
print(cw_dict)

print(
    "\nXGBoost scale_pos_weight:",
    scale_pos_weight
)


# ============================================================
# STEP 5: BASE MODEL CREATION FUNCTION
# ============================================================

def create_models():

    # ---------------- XGBoost ----------------

    xgb = XGBClassifier(
        n_estimators=200,
        max_depth=4,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,

        scale_pos_weight=scale_pos_weight,

        eval_metric='logloss',

        random_state=42,
        n_jobs=-1
    )


    # ---------------- Random Forest ----------------

    rf = RandomForestClassifier(
        n_estimators=200,

        class_weight='balanced',

        random_state=42,
        n_jobs=-1
    )


    # ---------------- HistGradientBoosting ----------------

    hgb = HistGradientBoostingClassifier(
        max_iter=200,
        learning_rate=0.05,
        max_leaf_nodes=31,

        class_weight='balanced',

        random_state=42
    )


    return xgb, rf, hgb


# ============================================================
# STEP 6: STRATIFIED 10-FOLD CV
# ============================================================

skf = StratifiedKFold(
    n_splits=10,
    shuffle=True,
    random_state=42
)


# ============================================================
# STEP 7: EVALUATION FUNCTION
# ============================================================

def evaluate_model(model_name):

    # ========================================================
    # CV METRIC STORAGE
    # ========================================================

    cv_accuracy = []
    cv_precision = []
    cv_sensitivity = []
    cv_f1 = []
    cv_auc = []
    cv_balanced_accuracy = []


    # ========================================================
    # 10-FOLD STRATIFIED CROSS-VALIDATION
    # ========================================================

    for fold, (train_idx, val_idx) in enumerate(
        skf.split(X_train, y_train),
        start=1
    ):

        print(
            f"\n{model_name} | Fold {fold}/10"
        )


        # ----------------------------------------------------
        # Split fold
        # ----------------------------------------------------

        X_tr = X_train.iloc[
            train_idx
        ]

        X_val = X_train.iloc[
            val_idx
        ]

        y_tr = y_train.iloc[
            train_idx
        ]

        y_val = y_train.iloc[
            val_idx
        ]


        # ----------------------------------------------------
        # Scaling INSIDE EACH FOLD
        # ----------------------------------------------------

        scaler = StandardScaler()

        X_tr_scaled = scaler.fit_transform(
            X_tr
        )

        X_val_scaled = scaler.transform(
            X_val
        )


        # ----------------------------------------------------
        # Create FRESH models for every fold
        # ----------------------------------------------------

        xgb, rf, hgb = create_models()


        # ----------------------------------------------------
        # Select requested model
        # ----------------------------------------------------

        if model_name == "XGBoost":

            model = xgb


        elif model_name == "Random Forest":

            model = rf


        elif model_name == "HistGradientBoosting":

            model = hgb


        elif model_name == "Voting Fusion":

            model = VotingClassifier(
                estimators=[
                    ('xgb', xgb),
                    ('rf', rf),
                    ('hgb', hgb)
                ],
                voting='soft'
            )


        elif model_name == "Stacking Fusion":

            model = StackingClassifier(
                estimators=[
                    ('xgb', xgb),
                    ('rf', rf),
                    ('hgb', hgb)
                ],

                final_estimator=LogisticRegression(
                    max_iter=1000,
                    class_weight='balanced'
                ),

                passthrough=True,

                cv=5
            )


        else:

            raise ValueError(
                f"Unknown model: {model_name}"
            )


        # ----------------------------------------------------
        # Train fold
        # ----------------------------------------------------

        model.fit(
            X_tr_scaled,
            y_tr
        )


        # ----------------------------------------------------
        # Validation predictions
        # ----------------------------------------------------

        val_preds = model.predict(
            X_val_scaled
        )

        val_probs = model.predict_proba(
            X_val_scaled
        )[:, 1]


        # ----------------------------------------------------
        # Fold metrics
        # ----------------------------------------------------

        fold_accuracy = accuracy_score(
            y_val,
            val_preds
        )

        fold_precision = precision_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_sensitivity = recall_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_f1 = f1_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_auc = roc_auc_score(
            y_val,
            val_probs
        )

        fold_balanced_accuracy = balanced_accuracy_score(
            y_val,
            val_preds
        )


        # ----------------------------------------------------
        # Store fold metrics
        # ----------------------------------------------------

        cv_accuracy.append(
            fold_accuracy
        )

        cv_precision.append(
            fold_precision
        )

        cv_sensitivity.append(
            fold_sensitivity
        )

        cv_f1.append(
            fold_f1
        )

        cv_auc.append(
            fold_auc
        )

        cv_balanced_accuracy.append(
            fold_balanced_accuracy
        )


        # ----------------------------------------------------
        # Print fold result
        # ----------------------------------------------------

        print(
            f"Accuracy            : {fold_accuracy:.4f}"
        )

        print(
            f"Precision           : {fold_precision:.4f}"
        )

        print(
            f"Sensitivity         : {fold_sensitivity:.4f}"
        )

        print(
            f"F1 Score            : {fold_f1:.4f}"
        )

        print(
            f"ROC-AUC             : {fold_auc:.4f}"
        )

        print(
            f"Balanced Accuracy   : "
            f"{fold_balanced_accuracy:.4f}"
        )


    # ========================================================
    # CV MEAN RESULTS
    # ========================================================

    cv_accuracy_mean = np.mean(
        cv_accuracy
    )

    cv_precision_mean = np.mean(
        cv_precision
    )

    cv_sensitivity_mean = np.mean(
        cv_sensitivity
    )

    cv_f1_mean = np.mean(
        cv_f1
    )

    cv_auc_mean = np.mean(
        cv_auc
    )

    cv_balanced_accuracy_mean = np.mean(
        cv_balanced_accuracy
    )


    # ========================================================
    # CROSS-VALIDATION RESULTS
    # ========================================================

    print(
        "\n================================================"
    )

    print(
        f"{model_name} - Cross-Validation (10-fold)"
    )

    print(
        "================================================"
    )

    print(
        f"Accuracy            : "
        f"{cv_accuracy_mean:.4f}"
    )

    print(
        f"Precision           : "
        f"{cv_precision_mean:.4f}"
    )

    print(
        f"Recall/Sensitivity  : "
        f"{cv_sensitivity_mean:.4f}"
    )

    print(
        f"F1 Score            : "
        f"{cv_f1_mean:.4f}"
    )

    print(
        f"ROC-AUC             : "
        f"{cv_auc_mean:.4f}"
    )

    print(
        f"Balanced Accuracy   : "
        f"{cv_balanced_accuracy_mean:.4f}"
    )


    # ========================================================
    # TRAIN FINAL MODEL ON COMPLETE TRAINING SET
    # ========================================================

    final_scaler = StandardScaler()

    X_train_final_scaled = final_scaler.fit_transform(
        X_train
    )

    X_test_final_scaled = final_scaler.transform(
        X_test
    )


    # --------------------------------------------------------
    # Create fresh final models
    # --------------------------------------------------------

    xgb, rf, hgb = create_models()


    if model_name == "XGBoost":

        final_model = xgb


    elif model_name == "Random Forest":

        final_model = rf


    elif model_name == "HistGradientBoosting":

        final_model = hgb


    elif model_name == "Voting Fusion":

        final_model = VotingClassifier(
            estimators=[
                ('xgb', xgb),
                ('rf', rf),
                ('hgb', hgb)
            ],
            voting='soft'
        )


    elif model_name == "Stacking Fusion":

        final_model = StackingClassifier(
            estimators=[
                ('xgb', xgb),
                ('rf', rf),
                ('hgb', hgb)
            ],

            final_estimator=LogisticRegression(
                max_iter=1000,
                class_weight='balanced'
            ),

            passthrough=True,

            cv=5
        )


    # ========================================================
    # FINAL TRAINING
    # ========================================================

    final_model.fit(
        X_train_final_scaled,
        y_train
    )


    # ========================================================
    # TEST PREDICTIONS
    # ========================================================

    test_preds = final_model.predict(
        X_test_final_scaled
    )

    test_probs = final_model.predict_proba(
        X_test_final_scaled
    )[:, 1]


    # ========================================================
    # TEST METRICS
    # ========================================================

    accuracy = accuracy_score(
        y_test,
        test_preds
    )

    precision = precision_score(
        y_test,
        test_preds,
        zero_division=0
    )

    sensitivity = recall_score(
        y_test,
        test_preds,
        zero_division=0
    )

    f1 = f1_score(
        y_test,
        test_preds,
        zero_division=0
    )

    roc_auc = roc_auc_score(
        y_test,
        test_probs
    )

    balanced_accuracy = balanced_accuracy_score(
        y_test,
        test_preds
    )

    mcc = matthews_corrcoef(
        y_test,
        test_preds
    )


    # ========================================================
    # CONFUSION MATRIX
    # ========================================================

    cm = confusion_matrix(
        y_test,
        test_preds,
        labels=[0, 1]
    )

    tn, fp, fn, tp = cm.ravel()


    # ========================================================
    # SENSITIVITY / SPECIFICITY
    # ========================================================

    sensitivity = (
        tp / (tp + fn)
        if (tp + fn) > 0
        else 0
    )

    specificity = (
        tn / (tn + fp)
        if (tn + fp) > 0
        else 0
    )


    # ========================================================
    # 95% CONFIDENCE INTERVALS
    # ========================================================

    # ---------------- Accuracy CI ----------------

    acc_low, acc_high = proportion_confint(
        count=int(round(accuracy * len(y_test))),
        nobs=len(y_test),
        alpha=0.05,
        method='wilson'
    )


    # ---------------- Precision CI ----------------

    precision_low, precision_high = proportion_confint(
        count=tp,
        nobs=(tp + fp),
        alpha=0.05,
        method='wilson'
    ) if (tp + fp) > 0 else (0.0, 0.0)


    # ---------------- Sensitivity CI ----------------

    sensitivity_low, sensitivity_high = proportion_confint(
        count=tp,
        nobs=(tp + fn),
        alpha=0.05,
        method='wilson'
    ) if (tp + fn) > 0 else (0.0, 0.0)


    # ---------------- Specificity CI ----------------

    specificity_low, specificity_high = proportion_confint(
        count=tn,
        nobs=(tn + fp),
        alpha=0.05,
        method='wilson'
    ) if (tn + fp) > 0 else (0.0, 0.0)


    # ========================================================
    # TEST SET PERFORMANCE
    # ========================================================

    print(
        "\n================================================"
    )

    print(
        f"{model_name} - Test Set Performance"
    )

    print(
        "================================================"
    )

    print(
        f"Accuracy            : {accuracy:.4f} "
        f"(95% CI: "
        f"{acc_low:.4f}-{acc_high:.4f})"
    )

    print(
        f"Precision           : {precision:.4f} "
        f"(95% CI: "
        f"{precision_low:.4f}-{precision_high:.4f})"
    )

    print(
        f"Sensitivity         : {sensitivity:.4f} "
        f"(95% CI: "
        f"{sensitivity_low:.4f}-{sensitivity_high:.4f})"
    )

    print(
        f"Specificity         : {specificity:.4f} "
        f"(95% CI: "
        f"{specificity_low:.4f}-{specificity_high:.4f})"
    )

    print(
        f"F1 Score            : {f1:.4f}"
    )

    print(
        f"ROC-AUC             : {roc_auc:.4f}"
    )

    print(
        f"Balanced Accuracy   : "
        f"{balanced_accuracy:.4f}"
    )

    print(
        f"MCC                 : {mcc:.4f}"
    )


    # ========================================================
    # CONFUSION MATRIX
    # ========================================================

    print(
        "\nConfusion Matrix:"
    )

    print(cm)

    print(
        "\nTN :", tn
    )

    print(
        "FP :", fp
    )

    print(
        "FN :", fn
    )

    print(
        "TP :", tp
    )


    # ========================================================
    # STORE RESULTS
    # ========================================================

    result = {

        # ---------------- CV ----------------

        "CV Accuracy":
            cv_accuracy_mean,

        "CV Precision":
            cv_precision_mean,

        "CV Sensitivity":
            cv_sensitivity_mean,

        "CV F1":
            cv_f1_mean,

        "CV ROC-AUC":
            cv_auc_mean,

        "CV Balanced Accuracy":
            cv_balanced_accuracy_mean,


        # ---------------- Test ----------------

        "Accuracy":
            accuracy,

        "Accuracy CI Low":
            acc_low,

        "Accuracy CI High":
            acc_high,


        "Precision":
            precision,

        "Precision CI Low":
            precision_low,

        "Precision CI High":
            precision_high,


        "Sensitivity":
            sensitivity,

        "Sensitivity CI Low":
            sensitivity_low,

        "Sensitivity CI High":
            sensitivity_high,


        "Specificity":
            specificity,

        "Specificity CI Low":
            specificity_low,

        "Specificity CI High":
            specificity_high,


        "F1":
            f1,

        "ROC-AUC":
            roc_auc,

        "Balanced Accuracy":
            balanced_accuracy,

        "MCC":
            mcc,


        # ---------------- Confusion Matrix ----------------

        "TN":
            tn,

        "FP":
            fp,

        "FN":
            fn,

        "TP":
            tp
    }


    return result


# ============================================================
# STEP 8: EVALUATE ALL MODELS
# ============================================================

model_names = [
    "XGBoost",
    "Random Forest",
    "HistGradientBoosting",
    "Voting Fusion",
    "Stacking Fusion"
]


results = {}

for name in model_names:

    print(
        "\n\n################################################"
    )

    print(
        f"Evaluating: {name}"
    )

    print(
        "################################################"
    )

    results[name] = evaluate_model(
        name
    )


# ============================================================
# STEP 9: FINAL RESULTS DATAFRAME
# ============================================================

results_df = pd.DataFrame(
    results
).T


# ============================================================
# STEP 10: ORDER RESULTS
# ============================================================

results_df = results_df[
    [

        # ---------------- CV ----------------

        "CV Accuracy",
        "CV Precision",
        "CV Sensitivity",
        "CV F1",
        "CV ROC-AUC",
        "CV Balanced Accuracy",


        # ---------------- Test ----------------

        "Accuracy",
        "Accuracy CI Low",
        "Accuracy CI High",

        "Precision",
        "Precision CI Low",
        "Precision CI High",

        "Sensitivity",
        "Sensitivity CI Low",
        "Sensitivity CI High",

        "Specificity",
        "Specificity CI Low",
        "Specificity CI High",

        "F1",
        "ROC-AUC",
        "Balanced Accuracy",
        "MCC",

        # ---------------- Confusion Matrix ----------------

        "TN",
        "FP",
        "FN",
        "TP"
    ]
]


# ============================================================
# STEP 11: DISPLAY FINAL RESULTS
# ============================================================

print(
    "\n================================================"
)

print(
    "FINAL MODEL COMPARISON"
)

print(
    "================================================\n"
)


display(
    results_df.sort_values(
        by="F1",
        ascending=False
    )
)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 8.8 MB/s eta 0:00:00

Class Weights:
{0: 1.2213740458015268, 1: 0.8465608465608465}

Train Shape : (256, 32)
Test Shape  : (64, 32)

Training Class Distribution:
PD_Label_Combined
1    151
0    105
Name: count, dtype: int64

Testing Class Distribution:
PD_Label_Combined
1    38
0    26
Name: count, dtype: int64

Training Class Weights:
{np.int64(0): np.float64(1.2190476190476192), np.int64(1): np.float64(0.847682119205298)}

XGBoost scale_pos_weight: 0.6953642384105959


################################################
Evaluating: XGBoost
################################################

XGBoost | Fold 1/10
Accuracy            : 0.7308
Precision           : 0.7647
Sensitivity         : 0.8125
F1 Score            : 0.7879
ROC-AUC             : 0.8375
Balanced Accuracy   : 0.7063

XGBoost | Fold 2/10
Accuracy            : 0.5769
Precision           : 0.6250
Sensitivity         : 0.6667
F1 Score            : 0.6452
ROC-AUC             : 0.7818
Balanced Accuracy   : 0.5606

XGBoost | Fold 3/10
Accuracy            : 0.7692
Precision           : 0.7647
Sensitivity         : 0.8667
F1 Score            : 0.8125
ROC-AUC             : 0.8606
Balanced Accuracy   : 0.7515

XGBoost | Fold 4/10
Accuracy            : 0.7692
Precision           : 0.9091
Sensitivity         : 0.6667
F1 Score            : 0.7692
ROC-AUC             : 0.8667
Balanced Accuracy   : 0.7879

XGBoost | Fold 5/10
Accuracy            : 0.8462
Precision           : 0.9231
Sensitivity         : 0.8000
F1 Score            : 0.8571
ROC-AUC             : 0.9636
Balanced Accuracy   : 0.8545

XGBoost | Fold 6/10
Accuracy            : 0.8462
Precision           : 1.0000
Sensitivity         : 0.7333
F1 Score            : 0.8462
ROC-AUC             : 0.9333
Balanced Accuracy   : 0.8667

XGBoost | Fold 7/10
Accuracy            : 0.7600
Precision           : 0.8462
Sensitivity         : 0.7333
F1 Score            : 0.7857
ROC-AUC             : 0.8833
Balanced Accuracy   : 0.7667

XGBoost | Fold 8/10
Accuracy            : 0.6800
Precision           : 0.7059
Sensitivity         : 0.8000
F1 Score            : 0.7500
ROC-AUC             : 0.8933
Balanced Accuracy   : 0.6500

XGBoost | Fold 9/10
Accuracy            : 0.8000
Precision           : 0.9167
Sensitivity         : 0.7333
F1 Score            : 0.8148
ROC-AUC             : 0.8800
Balanced Accuracy   : 0.8167

XGBoost | Fold 10/10
Accuracy            : 0.7600
Precision           : 0.8462
Sensitivity         : 0.7333
F1 Score            : 0.7857
ROC-AUC             : 0.8733
Balanced Accuracy   : 0.7667

================================================
XGBoost - Cross-Validation (10-fold)
================================================
Accuracy            : 0.7538
Precision           : 0.8301
Recall/Sensitivity  : 0.7546
F1 Score            : 0.7854
ROC-AUC             : 0.8774
Balanced Accuracy   : 0.7527

================================================
XGBoost - Test Set Performance
================================================
Accuracy            : 0.7031 (95% CI: 0.5823-0.8009)
Precision           : 0.7436 (95% CI: 0.5892-0.8543)
Sensitivity         : 0.7632 (95% CI: 0.6079-0.8701)
Specificity         : 0.6154 (95% CI: 0.4253-0.7757)
F1 Score            : 0.7532
ROC-AUC             : 0.8107
Balanced Accuracy   : 0.6893
MCC                 : 0.3811

Confusion Matrix:
[[16 10]
 [ 9 29]]

TN : 16
FP : 10
FN : 9
TP : 29


################################################
Evaluating: Random Forest
################################################

Random Forest | Fold 1/10
Accuracy            : 0.7308
Precision           : 0.7368
Sensitivity         : 0.8750
F1 Score            : 0.8000
ROC-AUC             : 0.8625
Balanced Accuracy   : 0.6875

Random Forest | Fold 2/10
Accuracy            : 0.6923
Precision           : 0.7692
Sensitivity         : 0.6667
F1 Score            : 0.7143
ROC-AUC             : 0.7758
Balanced Accuracy   : 0.6970

Random Forest | Fold 3/10
Accuracy            : 0.7692
Precision           : 0.7647
Sensitivity         : 0.8667
F1 Score            : 0.8125
ROC-AUC             : 0.8818
Balanced Accuracy   : 0.7515

Random Forest | Fold 4/10
Accuracy            : 0.7692
Precision           : 0.8462
Sensitivity         : 0.7333
F1 Score            : 0.7857
ROC-AUC             : 0.8606
Balanced Accuracy   : 0.7758

Random Forest | Fold 5/10
Accuracy            : 0.7692
Precision           : 0.8000
Sensitivity         : 0.8000
F1 Score            : 0.8000
ROC-AUC             : 0.9242
Balanced Accuracy   : 0.7636

Random Forest | Fold 6/10
Accuracy            : 0.8462
Precision           : 1.0000
Sensitivity         : 0.7333
F1 Score            : 0.8462
ROC-AUC             : 0.9364
Balanced Accuracy   : 0.8667

Random Forest | Fold 7/10
Accuracy            : 0.7200
Precision           : 0.7857
Sensitivity         : 0.7333
F1 Score            : 0.7586
ROC-AUC             : 0.8367
Balanced Accuracy   : 0.7167

Random Forest | Fold 8/10
Accuracy            : 0.7600
Precision           : 0.7368
Sensitivity         : 0.9333
F1 Score            : 0.8235
ROC-AUC             : 0.9133
Balanced Accuracy   : 0.7167

Random Forest | Fold 9/10
Accuracy            : 0.8000
Precision           : 0.9167
Sensitivity         : 0.7333
F1 Score            : 0.8148
ROC-AUC             : 0.9000
Balanced Accuracy   : 0.8167

Random Forest | Fold 10/10
Accuracy            : 0.7600
Precision           : 0.8462
Sensitivity         : 0.7333
F1 Score            : 0.7857
ROC-AUC             : 0.8800
Balanced Accuracy   : 0.7667

================================================
Random Forest - Cross-Validation (10-fold)
================================================
Accuracy            : 0.7617
Precision           : 0.8202
Recall/Sensitivity  : 0.7808
F1 Score            : 0.7941
ROC-AUC             : 0.8771
Balanced Accuracy   : 0.7559

================================================
Random Forest - Test Set Performance
================================================
Accuracy            : 0.6719 (95% CI: 0.5500-0.7743)
Precision           : 0.7073 (95% CI: 0.5552-0.8239)
Sensitivity         : 0.7632 (95% CI: 0.6079-0.8701)
Specificity         : 0.5385 (95% CI: 0.3546-0.7124)
F1 Score            : 0.7342
ROC-AUC             : 0.7844
Balanced Accuracy   : 0.6508
MCC                 : 0.3087

Confusion Matrix:
[[14 12]
 [ 9 29]]

TN : 14
FP : 12
FN : 9
TP : 29


################################################
Evaluating: HistGradientBoosting
################################################

HistGradientBoosting | Fold 1/10
Accuracy            : 0.6538
Precision           : 0.6667
Sensitivity         : 0.8750
F1 Score            : 0.7568
ROC-AUC             : 0.8438
Balanced Accuracy   : 0.5875

HistGradientBoosting | Fold 2/10
Accuracy            : 0.5769
Precision           : 0.6250
Sensitivity         : 0.6667
F1 Score            : 0.6452
ROC-AUC             : 0.7000
Balanced Accuracy   : 0.5606

HistGradientBoosting | Fold 3/10
Accuracy            : 0.7308
Precision           : 0.7222
Sensitivity         : 0.8667
F1 Score            : 0.7879
ROC-AUC             : 0.8545
Balanced Accuracy   : 0.7061

HistGradientBoosting | Fold 4/10
Accuracy            : 0.6538
Precision           : 0.8000
Sensitivity         : 0.5333
F1 Score            : 0.6400
ROC-AUC             : 0.8727
Balanced Accuracy   : 0.6758

HistGradientBoosting | Fold 5/10
Accuracy            : 0.8846
Precision           : 0.9286
Sensitivity         : 0.8667
F1 Score            : 0.8966
ROC-AUC             : 0.9758
Balanced Accuracy   : 0.8879

HistGradientBoosting | Fold 6/10
Accuracy            : 0.7692
Precision           : 0.9091
Sensitivity         : 0.6667
F1 Score            : 0.7692
ROC-AUC             : 0.8788
Balanced Accuracy   : 0.7879

HistGradientBoosting | Fold 7/10
Accuracy            : 0.7200
Precision           : 0.7857
Sensitivity         : 0.7333
F1 Score            : 0.7586
ROC-AUC             : 0.8500
Balanced Accuracy   : 0.7167

HistGradientBoosting | Fold 8/10
Accuracy            : 0.8000
Precision           : 0.7778
Sensitivity         : 0.9333
F1 Score            : 0.8485
ROC-AUC             : 0.9133
Balanced Accuracy   : 0.7667

HistGradientBoosting | Fold 9/10
Accuracy            : 0.8800
Precision           : 1.0000
Sensitivity         : 0.8000
F1 Score            : 0.8889
ROC-AUC             : 0.9067
Balanced Accuracy   : 0.9000

HistGradientBoosting | Fold 10/10
Accuracy            : 0.7600
Precision           : 0.8000
Sensitivity         : 0.8000
F1 Score            : 0.8000
ROC-AUC             : 0.8933
Balanced Accuracy   : 0.7500

================================================
HistGradientBoosting - Cross-Validation (10-fold)
================================================
Accuracy            : 0.7429
Precision           : 0.8015
Recall/Sensitivity  : 0.7742
F1 Score            : 0.7792
ROC-AUC             : 0.8689
Balanced Accuracy   : 0.7339

================================================
HistGradientBoosting - Test Set Performance
================================================
Accuracy            : 0.6719 (95% CI: 0.5500-0.7743)
Precision           : 0.7297 (95% CI: 0.5702-0.8460)
Sensitivity         : 0.7105 (95% CI: 0.5524-0.8300)
Specificity         : 0.6154 (95% CI: 0.4253-0.7757)
F1 Score            : 0.7200
ROC-AUC             : 0.8036
Balanced Accuracy   : 0.6630
MCC                 : 0.3241

Confusion Matrix:
[[16 10]
 [11 27]]

TN : 16
FP : 10
FN : 11
TP : 27


################################################
Evaluating: Voting Fusion
################################################

Voting Fusion | Fold 1/10
Accuracy            : 0.6923
Precision           : 0.7000
Sensitivity         : 0.8750
F1 Score            : 0.7778
ROC-AUC             : 0.8500
Balanced Accuracy   : 0.6375

Voting Fusion | Fold 2/10
Accuracy            : 0.6154
Precision           : 0.6471
Sensitivity         : 0.7333
F1 Score            : 0.6875
ROC-AUC             : 0.7697
Balanced Accuracy   : 0.5939

Voting Fusion | Fold 3/10
Accuracy            : 0.7692
Precision           : 0.7368
Sensitivity         : 0.9333
F1 Score            : 0.8235
ROC-AUC             : 0.8545
Balanced Accuracy   : 0.7394

Voting Fusion | Fold 4/10
Accuracy            : 0.7692
Precision           : 0.9091
Sensitivity         : 0.6667
F1 Score            : 0.7692
ROC-AUC             : 0.8848
Balanced Accuracy   : 0.7879

Voting Fusion | Fold 5/10
Accuracy            : 0.8846
Precision           : 0.9286
Sensitivity         : 0.8667
F1 Score            : 0.8966
ROC-AUC             : 0.9576
Balanced Accuracy   : 0.8879

Voting Fusion | Fold 6/10
Accuracy            : 0.8077
Precision           : 1.0000
Sensitivity         : 0.6667
F1 Score            : 0.8000
ROC-AUC             : 0.9212
Balanced Accuracy   : 0.8333

Voting Fusion | Fold 7/10
Accuracy            : 0.7600
Precision           : 0.8462
Sensitivity         : 0.7333
F1 Score            : 0.7857
ROC-AUC             : 0.8567
Balanced Accuracy   : 0.7667

Voting Fusion | Fold 8/10
Accuracy            : 0.7600
Precision           : 0.7368
Sensitivity         : 0.9333
F1 Score            : 0.8235
ROC-AUC             : 0.8933
Balanced Accuracy   : 0.7167

Voting Fusion | Fold 9/10
Accuracy            : 0.8800
Precision           : 1.0000
Sensitivity         : 0.8000
F1 Score            : 0.8889
ROC-AUC             : 0.9000
Balanced Accuracy   : 0.9000

Voting Fusion | Fold 10/10
Accuracy            : 0.7600
Precision           : 0.8462
Sensitivity         : 0.7333
F1 Score            : 0.7857
ROC-AUC             : 0.8733
Balanced Accuracy   : 0.7667

================================================
Voting Fusion - Cross-Validation (10-fold)
================================================
Accuracy            : 0.7698
Precision           : 0.8351
Recall/Sensitivity  : 0.7942
F1 Score            : 0.8038
ROC-AUC             : 0.8761
Balanced Accuracy   : 0.7630

================================================
Voting Fusion - Test Set Performance
================================================
Accuracy            : 0.6562 (95% CI: 0.5340-0.7608)
Precision           : 0.7000 (95% CI: 0.5457-0.8193)
Sensitivity         : 0.7368 (95% CI: 0.5799-0.8503)
Specificity         : 0.5385 (95% CI: 0.3546-0.7124)
F1 Score            : 0.7179
ROC-AUC             : 0.7945
Balanced Accuracy   : 0.6377
MCC                 : 0.2793

Confusion Matrix:
[[14 12]
 [10 28]]

TN : 14
FP : 12
FN : 10
TP : 28


################################################
Evaluating: Stacking Fusion
################################################

Stacking Fusion | Fold 1/10
Accuracy            : 0.7692
Precision           : 0.8125
Sensitivity         : 0.8125
F1 Score            : 0.8125
ROC-AUC             : 0.8625
Balanced Accuracy   : 0.7562

Stacking Fusion | Fold 2/10
Accuracy            : 0.6538
Precision           : 0.7143
Sensitivity         : 0.6667
F1 Score            : 0.6897
ROC-AUC             : 0.7697
Balanced Accuracy   : 0.6515

Stacking Fusion | Fold 3/10
Accuracy            : 0.8462
Precision           : 0.9231
Sensitivity         : 0.8000
F1 Score            : 0.8571
ROC-AUC             : 0.9394
Balanced Accuracy   : 0.8545

Stacking Fusion | Fold 4/10
Accuracy            : 0.7692
Precision           : 0.9091
Sensitivity         : 0.6667
F1 Score            : 0.7692
ROC-AUC             : 0.8970
Balanced Accuracy   : 0.7879

Stacking Fusion | Fold 5/10
Accuracy            : 0.9231
Precision           : 0.9333
Sensitivity         : 0.9333
F1 Score            : 0.9333
ROC-AUC             : 0.9879
Balanced Accuracy   : 0.9212

Stacking Fusion | Fold 6/10
Accuracy            : 0.8077
Precision           : 1.0000
Sensitivity         : 0.6667
F1 Score            : 0.8000
ROC-AUC             : 0.9576
Balanced Accuracy   : 0.8333

Stacking Fusion | Fold 7/10
Accuracy            : 0.7200
Precision           : 0.7857
Sensitivity         : 0.7333
F1 Score            : 0.7586
ROC-AUC             : 0.8700
Balanced Accuracy   : 0.7167

Stacking Fusion | Fold 8/10
Accuracy            : 0.8000
Precision           : 0.9167
Sensitivity         : 0.7333
F1 Score            : 0.8148
ROC-AUC             : 0.9333
Balanced Accuracy   : 0.8167

Stacking Fusion | Fold 9/10
Accuracy            : 0.8000
Precision           : 0.8571
Sensitivity         : 0.8000
F1 Score            : 0.8276
ROC-AUC             : 0.8800
Balanced Accuracy   : 0.8000

Stacking Fusion | Fold 10/10
Accuracy            : 0.8400
Precision           : 0.9231
Sensitivity         : 0.8000
F1 Score            : 0.8571
ROC-AUC             : 0.9333
Balanced Accuracy   : 0.8500

================================================
Stacking Fusion - Cross-Validation (10-fold)
================================================
Accuracy            : 0.7929
Precision           : 0.8775
Recall/Sensitivity  : 0.7612
F1 Score            : 0.8120
ROC-AUC             : 0.9031
Balanced Accuracy   : 0.7988

================================================
Stacking Fusion - Test Set Performance
================================================
Accuracy            : 0.7656 (95% CI: 0.6487-0.8525)
Precision           : 0.8286 (95% CI: 0.6732-0.9190)
Sensitivity         : 0.7632 (95% CI: 0.6079-0.8701)
Specificity         : 0.7692 (95% CI: 0.5795-0.8897)
F1 Score            : 0.7945
ROC-AUC             : 0.8623
Balanced Accuracy   : 0.7662
MCC                 : 0.5253

Confusion Matrix:
[[20  6]
 [ 9 29]]

TN : 20
FP : 6
FN : 9
TP : 29

================================================
FINAL MODEL COMPARISON
================================================

,CV Accuracy,CV Precision,CV Sensitivity,CV F1,CV ROC-AUC,CV Balanced Accuracy,Accuracy,Accuracy CI Low,Accuracy CI High,Precision,...,Specificity CI Low,Specificity CI High,F1,ROC-AUC,Balanced Accuracy,MCC,TN,FP,FN,TP
Stacking Fusion,0.792923,0.877489,0.761250,0.812003,0.903068,0.798807,0.765625,0.648667,0.852501,0.828571,...,0.579484,0.889662,0.794521,0.862348,0.766194,0.525260,20.0,6.0,9.0,29.0
XGBoost,0.753846,0.830144,0.754583,0.785431,0.877356,0.752746,0.703125,0.582298,0.800948,0.743590,...,0.425349,0.775714,0.753247,0.810729,0.689271,0.381058,16.0,10.0,9.0,29.0
Random Forest,0.761692,0.820231,0.780833,0.794133,0.877129,0.755871,0.671875,0.549991,0.774294,0.707317,...,0.354579,0.712441,0.734177,0.784413,0.650810,0.308732,14.0,12.0,9.0,29.0
HistGradientBoosting,0.742923,0.801504,0.774167,0.779157,0.868890,0.733902,0.671875,0.549991,0.774294,0.729730,...,0.425349,0.775714,0.720000,0.803644,0.662955,0.324112,16.0,10.0,11.0,27.0
Voting Fusion,0.769846,0.835071,0.794167,0.803844,0.876121,0.762992,0.656250,0.534036,0.760769,0.700000,...,0.354579,0.712441,0.717949,0.794534,0.637652,0.279290,14.0,12.0,10.0,28.0

**Early Fusion**

In [1]:
# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

df_acoustic_top7 = pd.read_csv('/content/drive/MyDrive/Acoustic-subject-level-dataset_top7.csv')
df_acoustic_top7 = df_acoustic_top7.drop(columns=['Participant_ID'])
print(df_acoustic_top7.shape)
print(df_acoustic_top7.head())

(193, 8)
       RPDE  Degree-voice breaks  Delta2  Delta3  Delta11  MFCC5   spread1  \
0  0.428488                  0.0     0.0     0.0      0.0    0.0 -4.239926
1  0.542488                  0.0     0.0     0.0      0.0    0.0 -4.519291
2  0.332247                  0.0     0.0     0.0      0.0    0.0 -7.226125
3  0.498593                  0.0     0.0     0.0      0.0    0.0 -5.632290
4  0.470775                  0.0     0.0     0.0      0.0    0.0 -5.523149

   Status
0       1
1       1
2       0
3       1
4       1

In [3]:
import pandas as pd

final_meg_df = pd.read_csv('/content/drive/MyDrive/final_meg-go(par)_top7_rfc+shap_10-fold_analysis_last_column.csv')

print("Loaded data shape:", final_meg_df.shape)
print(final_meg_df.head())

Loaded data shape: (127, 8)
   env_kurt_R_mean  env_kurt_R_std  env_kurt_L_mean  env_kurt_L_std  \
0         5.749049       15.894836         5.962378       17.165772
1         4.459546        7.184608         4.390848        6.578943
2         1.161476        0.718562         1.885349        1.714298
3         1.138575        0.699601         1.365950        0.817770
4     18283.789736     4480.567058     18277.357293     4487.602704

   burst_dur_cv_L_std  env_mod_rate_L_std  env_skew_L_mean  PD_Label_Combined
0        4.938551e-02            0.244843         1.123760                  0
1        1.147524e-01            0.117228         1.400286                  0
2        5.040195e-02            0.275503         0.953293                  0
3        4.311462e-02            0.460356         0.920828                  1
4        1.043683e-16            0.064449       129.243639                  1

In [4]:
# ============================================================
#        EARLY FUSION BASELINE (BALANCED + 32D)
#               + 5-FOLD CROSS VALIDATION
# ============================================================

import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

from imblearn.over_sampling import SMOTE

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# ============================================================
# STEP 1 — LOAD FEATURES + LABELS
# ============================================================

# Acoustic
X_acoustic = df_acoustic_top7.iloc[:, :-1].values.astype(np.float32)
y_acoustic = df_acoustic_top7.iloc[:, -1].values.astype(np.int64)

# MEG
X_meg = final_meg_df.iloc[:, :-1].values.astype(np.float32)
y_meg = final_meg_df.iloc[:, -1].values.astype(np.int64)

print("Acoustic Shape:", X_acoustic.shape)
print("MEG Shape:", X_meg.shape)

# ============================================================
# STEP 2 — NORMALIZATION
# ============================================================

scaler_acoustic = StandardScaler()
scaler_meg = StandardScaler()

X_acoustic = scaler_acoustic.fit_transform(X_acoustic)
X_meg = scaler_meg.fit_transform(X_meg)

# ============================================================
# STEP 3 — COMBINE MODALITIES
# ============================================================

X_early = np.vstack([X_acoustic, X_meg]).astype(np.float32)

y_early = np.hstack([
    y_acoustic,
    y_meg
]).astype(np.int64)

print("\nCombined Shape:", X_early.shape)
print("Combined Labels:", y_early.shape)

# ============================================================
# STEP 4 — EARLY FUSION MLP (32D LATENT)
# ============================================================

class EarlyFusionMLP(nn.Module):

    def __init__(self, input_dim):

        super().__init__()

        self.feature_extractor = nn.Sequential(

            nn.Linear(input_dim, 64),
            nn.ReLU(),
            nn.BatchNorm1d(64),
            nn.Dropout(0.3),

            nn.Linear(64, 32),
            nn.ReLU(),
            nn.BatchNorm1d(32)
        )

        self.classifier = nn.Sequential(

            nn.Dropout(0.2),

            nn.Linear(32, 2)
        )

    def forward(self, x):

        latent = self.feature_extractor(x)

        out = self.classifier(latent)

        return out, latent

# ============================================================
# STEP 5 — CROSS VALIDATION
# ============================================================

print("\n======================================")
print(" 5-FOLD CROSS VALIDATION")
print("======================================\n")

skf = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

accs = []
precs = []
recs = []
f1s = []
aucs = []

fold = 1

# ============================================================
# STEP 6 — FOLD LOOP
# ============================================================

for train_idx, test_idx in skf.split(X_early, y_early):

    X_train = X_early[train_idx]
    X_test = X_early[test_idx]

    y_train = y_early[train_idx]
    y_test = y_early[test_idx]

    # ========================================================
    # SMOTE
    # ========================================================

    smote = SMOTE(random_state=42)

    X_train, y_train = smote.fit_resample(
        X_train,
        y_train
    )

    # ========================================================
    # TENSORS
    # ========================================================

    X_train = torch.tensor(X_train).float().to(device)
    X_test = torch.tensor(X_test).float().to(device)

    y_train = torch.tensor(y_train).long().to(device)

    # ========================================================
    # MODEL
    # ========================================================

    model = EarlyFusionMLP(
        input_dim=X_early.shape[1]
    ).to(device)

    optimizer = optim.Adam(
        model.parameters(),
        lr=1e-3,
        weight_decay=1e-4
    )

    criterion = nn.CrossEntropyLoss()

    # ========================================================
    # TRAINING
    # ========================================================

    epochs = 120

    for epoch in range(epochs):

        model.train()

        optimizer.zero_grad()

        outputs, latent = model(X_train)

        loss = criterion(outputs, y_train)

        loss.backward()

        optimizer.step()

    # ========================================================
    # EVALUATION
    # ========================================================

    model.eval()

    with torch.no_grad():

        outputs, latent_test = model(X_test)

        probs = torch.softmax(
            outputs,
            dim=1
        )[:, 1].cpu().numpy()

        preds = outputs.argmax(1).cpu().numpy()

    # ========================================================
    # METRICS
    # ========================================================

    acc = accuracy_score(
        y_test,
        preds
    )

    precision = precision_score(
        y_test,
        preds
    )

    recall = recall_score(
        y_test,
        preds
    )

    f1 = f1_score(
        y_test,
        preds
    )

    auc = roc_auc_score(
        y_test,
        probs
    )

    accs.append(acc)
    precs.append(precision)
    recs.append(recall)
    f1s.append(f1)
    aucs.append(auc)

    # ========================================================
    # PRINT FOLD RESULTS
    # ========================================================

    print(f"Fold {fold}")

    print(f"Accuracy  : {acc:.4f}")
    print(f"Precision : {precision:.4f}")
    print(f"Recall    : {recall:.4f}")
    print(f"F1-Score  : {f1:.4f}")
    print(f"AUC       : {auc:.4f}")

    print()

    fold += 1

# ============================================================
# FINAL RESULTS
# ============================================================

print("\n======================================")
print(" FINAL RESULTS")
print("======================================\n")

print(f"Mean Accuracy  : {np.mean(accs)*100:.2f}%")
print(f"Mean Precision : {np.mean(precs)*100:.2f}%")
print(f"Mean Recall    : {np.mean(recs)*100:.2f}%")
print(f"Mean F1-Score  : {np.mean(f1s)*100:.2f}%")
print(f"Mean AUC       : {np.mean(aucs)*100:.2f}%")

# ============================================================
# EXTRACT 32D FEATURES
# ============================================================

with torch.no_grad():

    acoustic_tensor = torch.tensor(
        X_acoustic
    ).float().to(device)

    meg_tensor = torch.tensor(
        X_meg
    ).float().to(device)

    _, acoustic_32D = model(acoustic_tensor)

    _, meg_32D = model(meg_tensor)

acoustic_32D = acoustic_32D.cpu().numpy()
meg_32D = meg_32D.cpu().numpy()

print("\n======================================")
print(" LATENT SHAPES")
print("======================================\n")

print("Acoustic 32D Shape :", acoustic_32D.shape)
print("MEG 32D Shape      :", meg_32D.shape)

Acoustic Shape: (193, 7)
MEG Shape: (127, 7)

Combined Shape: (320, 7)
Combined Labels: (320,)

======================================
 5-FOLD CROSS VALIDATION
======================================

Fold 1
Accuracy  : 0.7031
Precision : 0.8276
Recall    : 0.6316
F1-Score  : 0.7164
AUC       : 0.7804

Fold 2
Accuracy  : 0.6875
Precision : 0.8000
Recall    : 0.6316
F1-Score  : 0.7059
AUC       : 0.8158

Fold 3
Accuracy  : 0.6719
Precision : 0.8400
Recall    : 0.5526
F1-Score  : 0.6667
AUC       : 0.7768

Fold 4
Accuracy  : 0.7344
Precision : 0.8182
Recall    : 0.7105
F1-Score  : 0.7606
AUC       : 0.8674

Fold 5
Accuracy  : 0.6875
Precision : 0.8148
Recall    : 0.5946
F1-Score  : 0.6875
AUC       : 0.7608


======================================
 FINAL RESULTS
======================================

Mean Accuracy  : 69.69%
Mean Precision : 82.01%
Mean Recall    : 62.42%
Mean F1-Score  : 70.74%
Mean AUC       : 80.02%

======================================
 LATENT SHAPES
======================================

Acoustic 32D Shape : (193, 32)
MEG 32D Shape      : (127, 32)

In [5]:
import torch

# Assuming fused_acoustic_32D and fused_meg_32D are numpy arrays of shape (7350, 32)

# Step 1: Convert numpy arrays to torch tensors (float32)
fused_acoustic_tensor = torch.from_numpy(acoustic_32D).float()
fused_meg_tensor = torch.from_numpy(meg_32D).float()

# Step 2: Concatenate row-wise (along dim=0)
fused_output_tensor = torch.cat([fused_acoustic_tensor, fused_meg_tensor], dim=0)  # Shape: (14700, 32)

# Step 3: Print shape and dtype
print(fused_output_tensor.shape)  # torch.Size([14700, 32])
print(fused_output_tensor.dtype)  # torch.float32

torch.Size([320, 32])
torch.float32

In [6]:
import torch
import numpy as np

# ------------------------
# Step 1: Extract targets correctly
# ------------------------

# Acoustic target from df_acoustic_top7 (last column)
y_acoustic = df_acoustic_top7.iloc[:, -1].values.astype(np.int32)   # (7350,)

# MEG target from final_meg_df (last column)
y_meg = final_meg_df.iloc[:, -1].values.astype(np.int32)           # (7350,)

# Convert to tensors (reshape to column)
acoustic_target_tensor = torch.tensor(y_acoustic).long().reshape(-1, 1)   # (7350, 1)
meg_target_tensor      = torch.tensor(y_meg).long().reshape(-1, 1)        # (7350, 1)

# ------------------------
# Step 2: Convert 32D latent features to tensors
# ------------------------

fused_acoustic_tensor = torch.from_numpy(acoustic_32D).float()  # (7350, 32)
fused_meg_tensor      = torch.from_numpy(meg_32D).float()       # (7350, 32)

# ------------------------
# Step 3: Attach target columns
# ------------------------

# Concatenate latent features with target
acoustic_full = torch.cat([fused_acoustic_tensor, acoustic_target_tensor.float()], dim=1)  # (7350, 65)
meg_full      = torch.cat([fused_meg_tensor,      meg_target_tensor.float()],      dim=1)  # (7350, 65)

# ------------------------
# Step 4: Concatenate both datasets
# ------------------------

fused_df = torch.cat([acoustic_full, meg_full], dim=0)  # (14700, 65)

# ------------------------
# Step 5: Separate features and labels for PyTorch
# ------------------------

X = fused_df[:, :-1].float()   # Features (32D) -> float32
y = fused_df[:, -1].long()     # Target -> int32

# ------------------------
# Step 6: Print shapes and dtypes
# ------------------------

print(f"Features shape: {X.shape}, dtype: {X.dtype}")  # (14700, 32), float32
print(f"Labels shape: {y.shape}, dtype: {y.dtype}")    # (14700,), int32

Features shape: torch.Size([320, 32]), dtype: torch.float32
Labels shape: torch.Size([320]), dtype: torch.int64

In [7]:
import torch
import pandas as pd

# fused_df shape = (14700, 33)

# Step 6: Convert fused tensor to numpy
fused_df_np = fused_df.numpy()

# Step 7: Create correct column names for 32 latent features + 1 label
feature_names = [f"feat_{i}" for i in range(32)]
feature_names.append("PD_Label_Combined")

# Step 8: Convert to DataFrame
fused_df_named = pd.DataFrame(fused_df_np, columns=feature_names)

# Step 9: Verify
print(fused_df_named.shape)
print(fused_df_named.head())
print(fused_df_named.tail())

(320, 33)
     feat_0    feat_1    feat_2    feat_3    feat_4    feat_5    feat_6  \
0  0.637920 -0.301188 -0.613893  1.496413 -1.024064 -0.320334 -0.063105
1  1.522877 -0.678763 -0.940817  1.376105 -1.024064 -0.065830  0.766043
2 -0.240189  0.187642  2.086477  1.042789 -1.024064 -0.491106 -0.438392
3  1.014099 -0.673626 -0.849420  1.681111 -1.024064 -0.491106  0.281229
4  0.805437 -0.545399 -0.512587  1.676008 -1.024064 -0.491106  0.083132

     feat_7    feat_8    feat_9  ...   feat_23   feat_24   feat_25   feat_26  \
0 -0.392427  0.279214 -0.149443  ... -0.497326 -0.512370 -0.135520  0.633898
1 -0.392427  1.283560 -0.567701  ... -0.497326  0.011659 -0.135520  1.377656
2  0.275612 -0.412685  2.177988  ... -0.497326 -0.827733  0.286599 -0.091239
3 -0.392427  0.551663  0.186647  ... -0.497326 -0.422240 -0.135520  0.938300
4 -0.392427  0.318572  0.280824  ... -0.497326 -0.549159 -0.135520  0.739413

    feat_27   feat_28  feat_29  feat_30   feat_31  PD_Label_Combined
0 -0.713041  1.142967 -0.57877  -0.9368  0.238721                1.0
1 -0.713041  0.286354 -0.57877  -0.9368 -0.959728                1.0
2  0.576999  3.881901 -0.57877  -0.9368  3.154872                0.0
3 -0.713041  1.492735 -0.57877  -0.9368 -0.137266                1.0
4 -0.713041  1.651628 -0.57877  -0.9368  0.169903                1.0

[5 rows x 33 columns]
       feat_0    feat_1    feat_2    feat_3    feat_4    feat_5    feat_6  \
315 -0.435524  0.175094  0.417266 -0.447851  1.062477 -0.491106 -0.438392
316 -0.181770 -0.566785 -0.848766 -0.017265  0.048191  0.244197 -0.438392
317 -0.435524 -0.039561  0.214548 -0.447851  1.183186 -0.491106 -0.438392
318 -0.435524 -0.063291  0.202897 -0.447851  1.167353 -0.491106 -0.438392
319 -0.222536 -0.478560 -0.611569 -0.157595  0.410778  0.093679 -0.438392

       feat_7    feat_8    feat_9  ...   feat_23   feat_24   feat_25  \
315 -0.392427 -0.359785 -0.567701  ... -0.497326  0.003951 -0.135520
316 -0.392427 -0.412685 -0.567701  ... -0.497326 -0.334463 -0.005764
317 -0.392427 -0.412685 -0.567701  ... -0.497326 -0.138963 -0.135520
318 -0.392427 -0.412685 -0.567701  ... -0.497326 -0.153443 -0.135520
319 -0.392427 -0.412685 -0.567701  ... -0.497326 -0.324550 -0.042065

      feat_26   feat_27   feat_28   feat_29   feat_30   feat_31  \
315 -0.408634 -0.161426  0.501031 -0.394205  0.620750  1.088701
316 -0.408634 -0.598926 -0.663174 -0.563571 -0.619786  0.483366
317 -0.408634 -0.113414 -0.197526 -0.426398  0.168151  1.232360
318 -0.408634 -0.080294 -0.208682 -0.433605  0.110965  1.222510
319 -0.408634 -0.430557 -0.663174 -0.531753 -0.454319  0.715605

     PD_Label_Combined
315                0.0
316                1.0
317                0.0
318                0.0
319                1.0

[5 rows x 33 columns]

In [8]:
# Make a copy to be safe (optional)
fused_df_named_int = fused_df_named.copy()

# Convert only the last column to int
fused_df_named_int['PD_Label_Combined'] = fused_df_named_int['PD_Label_Combined'].astype(int)

# Verify
print(fused_df_named_int.dtypes)
print(fused_df_named_int.head())

feat_0               float32
feat_1               float32
feat_2               float32
feat_3               float32
feat_4               float32
feat_5               float32
feat_6               float32
feat_7               float32
feat_8               float32
feat_9               float32
feat_10              float32
feat_11              float32
feat_12              float32
feat_13              float32
feat_14              float32
feat_15              float32
feat_16              float32
feat_17              float32
feat_18              float32
feat_19              float32
feat_20              float32
feat_21              float32
feat_22              float32
feat_23              float32
feat_24              float32
feat_25              float32
feat_26              float32
feat_27              float32
feat_28              float32
feat_29              float32
feat_30              float32
feat_31              float32
PD_Label_Combined      int64
dtype: object
     feat_0    feat_1    feat_2    feat_3    feat_4    feat_5    feat_6  \
0  0.637920 -0.301188 -0.613893  1.496413 -1.024064 -0.320334 -0.063105
1  1.522877 -0.678763 -0.940817  1.376105 -1.024064 -0.065830  0.766043
2 -0.240189  0.187642  2.086477  1.042789 -1.024064 -0.491106 -0.438392
3  1.014099 -0.673626 -0.849420  1.681111 -1.024064 -0.491106  0.281229
4  0.805437 -0.545399 -0.512587  1.676008 -1.024064 -0.491106  0.083132

     feat_7    feat_8    feat_9  ...   feat_23   feat_24   feat_25   feat_26  \
0 -0.392427  0.279214 -0.149443  ... -0.497326 -0.512370 -0.135520  0.633898
1 -0.392427  1.283560 -0.567701  ... -0.497326  0.011659 -0.135520  1.377656
2  0.275612 -0.412685  2.177988  ... -0.497326 -0.827733  0.286599 -0.091239
3 -0.392427  0.551663  0.186647  ... -0.497326 -0.422240 -0.135520  0.938300
4 -0.392427  0.318572  0.280824  ... -0.497326 -0.549159 -0.135520  0.739413

    feat_27   feat_28  feat_29  feat_30   feat_31  PD_Label_Combined
0 -0.713041  1.142967 -0.57877  -0.9368  0.238721                  1
1 -0.713041  0.286354 -0.57877  -0.9368 -0.959728                  1
2  0.576999  3.881901 -0.57877  -0.9368  3.154872                  0
3 -0.713041  1.492735 -0.57877  -0.9368 -0.137266                  1
4 -0.713041  1.651628 -0.57877  -0.9368  0.169903                  1

[5 rows x 33 columns]

In [9]:
# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [10]:
import pandas as pd

fused_df_named_int.to_csv('/content/drive//MyDrive/Subject-level-fused-Early_fusion_MLP_fgo_data_5-fold_cross_validation_2.csv', index=False)

In [1]:
# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

fused_df_named_int = pd.read_csv('/content/drive//MyDrive/Subject-level-fused-Early_fusion_MLP_fgo_data_5-fold_cross_validation_2.csv')
fused_df_named_int.head()

,feat_0,feat_1,feat_2,feat_3,feat_4,feat_5,feat_6,feat_7,feat_8,feat_9,...,feat_23,feat_24,feat_25,feat_26,feat_27,feat_28,feat_29,feat_30,feat_31,PD_Label_Combined
0,0.637920,-0.301188,-0.613893,1.496413,-1.024064,-0.320334,-0.063105,-0.392427,0.279214,-0.149443,...,-0.497326,-0.512370,-0.135520,0.633898,-0.713041,1.142967,-0.57877,-0.9368,0.238721,1
1,1.522877,-0.678763,-0.940817,1.376105,-1.024064,-0.065830,0.766043,-0.392427,1.283560,-0.567701,...,-0.497326,0.011659,-0.135520,1.377656,-0.713041,0.286354,-0.57877,-0.9368,-0.959728,1
2,-0.240189,0.187642,2.086477,1.042790,-1.024064,-0.491106,-0.438392,0.275612,-0.412685,2.177988,...,-0.497326,-0.827733,0.286599,-0.091239,0.576999,3.881900,-0.57877,-0.9368,3.154872,0
3,1.014099,-0.673626,-0.849420,1.681111,-1.024064,-0.491106,0.281229,-0.392427,0.551663,0.186647,...,-0.497326,-0.422240,-0.135520,0.938300,-0.713041,1.492735,-0.57877,-0.9368,-0.137266,1
4,0.805437,-0.545399,-0.512587,1.676008,-1.024064,-0.491106,0.083132,-0.392427,0.318572,0.280824,...,-0.497326,-0.549159,-0.135520,0.739413,-0.713041,1.651628,-0.57877,-0.9368,0.169903,1

Evaluation

In [3]:
# ============================================================
# ###8)###
# ENSEMBLE CLASSIFICATION WITH STRATIFIED 10-FOLD CV
# ============================================================

# ------------------ Install Required Packages ------------------

!pip install xgboost lightgbm catboost scikit-learn statsmodels matplotlib seaborn --quiet


# ------------------ Imports ------------------

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.utils.class_weight import compute_class_weight

from sklearn.model_selection import (
    train_test_split,
    StratifiedKFold
)

from sklearn.preprocessing import StandardScaler

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    balanced_accuracy_score,
    matthews_corrcoef,
    confusion_matrix
)

from sklearn.ensemble import (
    VotingClassifier,
    StackingClassifier,
    RandomForestClassifier,
    HistGradientBoostingClassifier
)

from sklearn.linear_model import LogisticRegression

from xgboost import XGBClassifier

from statsmodels.stats.proportion import proportion_confint


# ============================================================
# STEP 1: PREPARE DATA
# ============================================================

X = fused_df_named_int[
    [f'feat_{i}' for i in range(32)]
].copy()

y = fused_df_named_int[
    "PD_Label_Combined"
].copy()


# ------------------ Convert X to numeric ------------------

X = X.apply(
    pd.to_numeric,
    errors='coerce'
)

X.fillna(
    0,
    inplace=True
)


# ============================================================
# STEP 2: CLASS WEIGHTS
# ============================================================

classes = np.unique(y)

class_weights = compute_class_weight(
    class_weight='balanced',
    classes=classes,
    y=y
)

class_weights_dict = {
    int(classes[0]): float(class_weights[0]),
    int(classes[1]): float(class_weights[1])
}

print("\nClass Weights:")
print(class_weights_dict)


# ============================================================
# STEP 3: TRAIN-TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=42
)


print("\nTrain Shape :", X_train.shape)
print("Test Shape  :", X_test.shape)

print("\nTraining Class Distribution:")
print(y_train.value_counts())

print("\nTesting Class Distribution:")
print(y_test.value_counts())


# ============================================================
# STEP 4: HANDLE CLASS IMBALANCE
# ============================================================

cw = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_train),
    y=y_train
)

cw_dict = dict(
    zip(
        np.unique(y_train),
        cw
    )
)

scale_pos_weight = (
    cw[1] / cw[0]
)

print("\nTraining Class Weights:")
print(cw_dict)

print(
    "\nXGBoost scale_pos_weight:",
    scale_pos_weight
)


# ============================================================
# STEP 5: BASE MODEL CREATION FUNCTION
# ============================================================

def create_models():

    # ---------------- XGBoost ----------------

    xgb = XGBClassifier(
        n_estimators=200,
        max_depth=4,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,

        scale_pos_weight=scale_pos_weight,

        eval_metric='logloss',

        random_state=42,
        n_jobs=-1
    )


    # ---------------- Random Forest ----------------

    rf = RandomForestClassifier(
        n_estimators=200,

        class_weight='balanced',

        random_state=42,
        n_jobs=-1
    )


    # ---------------- HistGradientBoosting ----------------

    hgb = HistGradientBoostingClassifier(
        max_iter=200,
        learning_rate=0.05,
        max_leaf_nodes=31,

        class_weight='balanced',

        random_state=42
    )


    return xgb, rf, hgb


# ============================================================
# STEP 6: STRATIFIED 10-FOLD CV
# ============================================================

skf = StratifiedKFold(
    n_splits=10,
    shuffle=True,
    random_state=42
)


# ============================================================
# STEP 7: EVALUATION FUNCTION
# ============================================================

def evaluate_model(model_name):

    # ========================================================
    # CV METRIC STORAGE
    # ========================================================

    cv_accuracy = []
    cv_precision = []
    cv_sensitivity = []
    cv_f1 = []
    cv_auc = []
    cv_balanced_accuracy = []


    # ========================================================
    # 10-FOLD STRATIFIED CROSS-VALIDATION
    # ========================================================

    for fold, (train_idx, val_idx) in enumerate(
        skf.split(X_train, y_train),
        start=1
    ):

        print(
            f"\n{model_name} | Fold {fold}/10"
        )


        # ----------------------------------------------------
        # Split fold
        # ----------------------------------------------------

        X_tr = X_train.iloc[
            train_idx
        ]

        X_val = X_train.iloc[
            val_idx
        ]

        y_tr = y_train.iloc[
            train_idx
        ]

        y_val = y_train.iloc[
            val_idx
        ]


        # ----------------------------------------------------
        # Scaling INSIDE EACH FOLD
        # ----------------------------------------------------

        scaler = StandardScaler()

        X_tr_scaled = scaler.fit_transform(
            X_tr
        )

        X_val_scaled = scaler.transform(
            X_val
        )


        # ----------------------------------------------------
        # Create FRESH models for every fold
        # ----------------------------------------------------

        xgb, rf, hgb = create_models()


        # ----------------------------------------------------
        # Select requested model
        # ----------------------------------------------------

        if model_name == "XGBoost":

            model = xgb


        elif model_name == "Random Forest":

            model = rf


        elif model_name == "HistGradientBoosting":

            model = hgb


        elif model_name == "Voting Fusion":

            model = VotingClassifier(
                estimators=[
                    ('xgb', xgb),
                    ('rf', rf),
                    ('hgb', hgb)
                ],
                voting='soft'
            )


        elif model_name == "Stacking Fusion":

            model = StackingClassifier(
                estimators=[
                    ('xgb', xgb),
                    ('rf', rf),
                    ('hgb', hgb)
                ],

                final_estimator=LogisticRegression(
                    max_iter=1000,
                    class_weight='balanced'
                ),

                passthrough=True,

                cv=5
            )


        else:

            raise ValueError(
                f"Unknown model: {model_name}"
            )


        # ----------------------------------------------------
        # Train fold
        # ----------------------------------------------------

        model.fit(
            X_tr_scaled,
            y_tr
        )


        # ----------------------------------------------------
        # Validation predictions
        # ----------------------------------------------------

        val_preds = model.predict(
            X_val_scaled
        )

        val_probs = model.predict_proba(
            X_val_scaled
        )[:, 1]


        # ----------------------------------------------------
        # Fold metrics
        # ----------------------------------------------------

        fold_accuracy = accuracy_score(
            y_val,
            val_preds
        )

        fold_precision = precision_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_sensitivity = recall_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_f1 = f1_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_auc = roc_auc_score(
            y_val,
            val_probs
        )

        fold_balanced_accuracy = balanced_accuracy_score(
            y_val,
            val_preds
        )


        # ----------------------------------------------------
        # Store fold metrics
        # ----------------------------------------------------

        cv_accuracy.append(
            fold_accuracy
        )

        cv_precision.append(
            fold_precision
        )

        cv_sensitivity.append(
            fold_sensitivity
        )

        cv_f1.append(
            fold_f1
        )

        cv_auc.append(
            fold_auc
        )

        cv_balanced_accuracy.append(
            fold_balanced_accuracy
        )


        # ----------------------------------------------------
        # Print fold result
        # ----------------------------------------------------

        print(
            f"Accuracy            : {fold_accuracy:.4f}"
        )

        print(
            f"Precision           : {fold_precision:.4f}"
        )

        print(
            f"Sensitivity         : {fold_sensitivity:.4f}"
        )

        print(
            f"F1 Score            : {fold_f1:.4f}"
        )

        print(
            f"ROC-AUC             : {fold_auc:.4f}"
        )

        print(
            f"Balanced Accuracy   : "
            f"{fold_balanced_accuracy:.4f}"
        )


    # ========================================================
    # CV MEAN RESULTS
    # ========================================================

    cv_accuracy_mean = np.mean(
        cv_accuracy
    )

    cv_precision_mean = np.mean(
        cv_precision
    )

    cv_sensitivity_mean = np.mean(
        cv_sensitivity
    )

    cv_f1_mean = np.mean(
        cv_f1
    )

    cv_auc_mean = np.mean(
        cv_auc
    )

    cv_balanced_accuracy_mean = np.mean(
        cv_balanced_accuracy
    )


    # ========================================================
    # CROSS-VALIDATION RESULTS
    # ========================================================

    print(
        "\n================================================"
    )

    print(
        f"{model_name} - Cross-Validation (10-fold)"
    )

    print(
        "================================================"
    )

    print(
        f"Accuracy            : "
        f"{cv_accuracy_mean:.4f}"
    )

    print(
        f"Precision           : "
        f"{cv_precision_mean:.4f}"
    )

    print(
        f"Recall/Sensitivity  : "
        f"{cv_sensitivity_mean:.4f}"
    )

    print(
        f"F1 Score            : "
        f"{cv_f1_mean:.4f}"
    )

    print(
        f"ROC-AUC             : "
        f"{cv_auc_mean:.4f}"
    )

    print(
        f"Balanced Accuracy   : "
        f"{cv_balanced_accuracy_mean:.4f}"
    )


    # ========================================================
    # TRAIN FINAL MODEL ON COMPLETE TRAINING SET
    # ========================================================

    final_scaler = StandardScaler()

    X_train_final_scaled = final_scaler.fit_transform(
        X_train
    )

    X_test_final_scaled = final_scaler.transform(
        X_test
    )


    # --------------------------------------------------------
    # Create fresh final models
    # --------------------------------------------------------

    xgb, rf, hgb = create_models()


    if model_name == "XGBoost":

        final_model = xgb


    elif model_name == "Random Forest":

        final_model = rf


    elif model_name == "HistGradientBoosting":

        final_model = hgb


    elif model_name == "Voting Fusion":

        final_model = VotingClassifier(
            estimators=[
                ('xgb', xgb),
                ('rf', rf),
                ('hgb', hgb)
            ],
            voting='soft'
        )


    elif model_name == "Stacking Fusion":

        final_model = StackingClassifier(
            estimators=[
                ('xgb', xgb),
                ('rf', rf),
                ('hgb', hgb)
            ],

            final_estimator=LogisticRegression(
                max_iter=1000,
                class_weight='balanced'
            ),

            passthrough=True,

            cv=5
        )


    # ========================================================
    # FINAL TRAINING
    # ========================================================

    final_model.fit(
        X_train_final_scaled,
        y_train
    )


    # ========================================================
    # TEST PREDICTIONS
    # ========================================================

    test_preds = final_model.predict(
        X_test_final_scaled
    )

    test_probs = final_model.predict_proba(
        X_test_final_scaled
    )[:, 1]


    # ========================================================
    # TEST METRICS
    # ========================================================

    accuracy = accuracy_score(
        y_test,
        test_preds
    )

    precision = precision_score(
        y_test,
        test_preds,
        zero_division=0
    )

    sensitivity = recall_score(
        y_test,
        test_preds,
        zero_division=0
    )

    f1 = f1_score(
        y_test,
        test_preds,
        zero_division=0
    )

    roc_auc = roc_auc_score(
        y_test,
        test_probs
    )

    balanced_accuracy = balanced_accuracy_score(
        y_test,
        test_preds
    )

    mcc = matthews_corrcoef(
        y_test,
        test_preds
    )


    # ========================================================
    # CONFUSION MATRIX
    # ========================================================

    cm = confusion_matrix(
        y_test,
        test_preds,
        labels=[0, 1]
    )

    tn, fp, fn, tp = cm.ravel()


    # ========================================================
    # SENSITIVITY / SPECIFICITY
    # ========================================================

    sensitivity = (
        tp / (tp + fn)
        if (tp + fn) > 0
        else 0
    )

    specificity = (
        tn / (tn + fp)
        if (tn + fp) > 0
        else 0
    )


    # ========================================================
    # 95% CONFIDENCE INTERVALS
    # ========================================================

    # ---------------- Accuracy CI ----------------

    acc_low, acc_high = proportion_confint(
        count=int(round(accuracy * len(y_test))),
        nobs=len(y_test),
        alpha=0.05,
        method='wilson'
    )


    # ---------------- Precision CI ----------------

    precision_low, precision_high = proportion_confint(
        count=tp,
        nobs=(tp + fp),
        alpha=0.05,
        method='wilson'
    ) if (tp + fp) > 0 else (0.0, 0.0)


    # ---------------- Sensitivity CI ----------------

    sensitivity_low, sensitivity_high = proportion_confint(
        count=tp,
        nobs=(tp + fn),
        alpha=0.05,
        method='wilson'
    ) if (tp + fn) > 0 else (0.0, 0.0)


    # ---------------- Specificity CI ----------------

    specificity_low, specificity_high = proportion_confint(
        count=tn,
        nobs=(tn + fp),
        alpha=0.05,
        method='wilson'
    ) if (tn + fp) > 0 else (0.0, 0.0)


    # ========================================================
    # TEST SET PERFORMANCE
    # ========================================================

    print(
        "\n================================================"
    )

    print(
        f"{model_name} - Test Set Performance"
    )

    print(
        "================================================"
    )

    print(
        f"Accuracy            : {accuracy:.4f} "
        f"(95% CI: "
        f"{acc_low:.4f}-{acc_high:.4f})"
    )

    print(
        f"Precision           : {precision:.4f} "
        f"(95% CI: "
        f"{precision_low:.4f}-{precision_high:.4f})"
    )

    print(
        f"Sensitivity         : {sensitivity:.4f} "
        f"(95% CI: "
        f"{sensitivity_low:.4f}-{sensitivity_high:.4f})"
    )

    print(
        f"Specificity         : {specificity:.4f} "
        f"(95% CI: "
        f"{specificity_low:.4f}-{specificity_high:.4f})"
    )

    print(
        f"F1 Score            : {f1:.4f}"
    )

    print(
        f"ROC-AUC             : {roc_auc:.4f}"
    )

    print(
        f"Balanced Accuracy   : "
        f"{balanced_accuracy:.4f}"
    )

    print(
        f"MCC                 : {mcc:.4f}"
    )


    # ========================================================
    # CONFUSION MATRIX
    # ========================================================

    print(
        "\nConfusion Matrix:"
    )

    print(cm)

    print(
        "\nTN :", tn
    )

    print(
        "FP :", fp
    )

    print(
        "FN :", fn
    )

    print(
        "TP :", tp
    )


    # ========================================================
    # STORE RESULTS
    # ========================================================

    result = {

        # ---------------- CV ----------------

        "CV Accuracy":
            cv_accuracy_mean,

        "CV Precision":
            cv_precision_mean,

        "CV Sensitivity":
            cv_sensitivity_mean,

        "CV F1":
            cv_f1_mean,

        "CV ROC-AUC":
            cv_auc_mean,

        "CV Balanced Accuracy":
            cv_balanced_accuracy_mean,


        # ---------------- Test ----------------

        "Accuracy":
            accuracy,

        "Accuracy CI Low":
            acc_low,

        "Accuracy CI High":
            acc_high,


        "Precision":
            precision,

        "Precision CI Low":
            precision_low,

        "Precision CI High":
            precision_high,


        "Sensitivity":
            sensitivity,

        "Sensitivity CI Low":
            sensitivity_low,

        "Sensitivity CI High":
            sensitivity_high,


        "Specificity":
            specificity,

        "Specificity CI Low":
            specificity_low,

        "Specificity CI High":
            specificity_high,


        "F1":
            f1,

        "ROC-AUC":
            roc_auc,

        "Balanced Accuracy":
            balanced_accuracy,

        "MCC":
            mcc,


        # ---------------- Confusion Matrix ----------------

        "TN":
            tn,

        "FP":
            fp,

        "FN":
            fn,

        "TP":
            tp
    }


    return result


# ============================================================
# STEP 8: EVALUATE ALL MODELS
# ============================================================

model_names = [
    "XGBoost",
    "Random Forest",
    "HistGradientBoosting",
    "Voting Fusion",
    "Stacking Fusion"
]


results = {}

for name in model_names:

    print(
        "\n\n################################################"
    )

    print(
        f"Evaluating: {name}"
    )

    print(
        "################################################"
    )

    results[name] = evaluate_model(
        name
    )


# ============================================================
# STEP 9: FINAL RESULTS DATAFRAME
# ============================================================

results_df = pd.DataFrame(
    results
).T


# ============================================================
# STEP 10: ORDER RESULTS
# ============================================================

results_df = results_df[
    [

        # ---------------- CV ----------------

        "CV Accuracy",
        "CV Precision",
        "CV Sensitivity",
        "CV F1",
        "CV ROC-AUC",
        "CV Balanced Accuracy",


        # ---------------- Test ----------------

        "Accuracy",
        "Accuracy CI Low",
        "Accuracy CI High",

        "Precision",
        "Precision CI Low",
        "Precision CI High",

        "Sensitivity",
        "Sensitivity CI Low",
        "Sensitivity CI High",

        "Specificity",
        "Specificity CI Low",
        "Specificity CI High",

        "F1",
        "ROC-AUC",
        "Balanced Accuracy",
        "MCC",

        # ---------------- Confusion Matrix ----------------

        "TN",
        "FP",
        "FN",
        "TP"
    ]
]


# ============================================================
# STEP 11: DISPLAY FINAL RESULTS
# ============================================================

print(
    "\n================================================"
)

print(
    "FINAL MODEL COMPARISON"
)

print(
    "================================================\n"
)


display(
    results_df.sort_values(
        by="F1",
        ascending=False
    )
)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 8.5 MB/s eta 0:00:00

Class Weights:
{0: 1.2213740458015268, 1: 0.8465608465608465}

Train Shape : (256, 32)
Test Shape  : (64, 32)

Training Class Distribution:
PD_Label_Combined
1    151
0    105
Name: count, dtype: int64

Testing Class Distribution:
PD_Label_Combined
1    38
0    26
Name: count, dtype: int64

Training Class Weights:
{np.int64(0): np.float64(1.2190476190476192), np.int64(1): np.float64(0.847682119205298)}

XGBoost scale_pos_weight: 0.6953642384105959


################################################
Evaluating: XGBoost
################################################

XGBoost | Fold 1/10
Accuracy            : 0.6923
Precision           : 0.7000
Sensitivity         : 0.8750
F1 Score            : 0.7778
ROC-AUC             : 0.8187
Balanced Accuracy   : 0.6375

XGBoost | Fold 2/10
Accuracy            : 0.6923
Precision           : 0.7692
Sensitivity         : 0.6667
F1 Score            : 0.7143
ROC-AUC             : 0.7667
Balanced Accuracy   : 0.6970

XGBoost | Fold 3/10
Accuracy            : 0.7692
Precision           : 0.7647
Sensitivity         : 0.8667
F1 Score            : 0.8125
ROC-AUC             : 0.8485
Balanced Accuracy   : 0.7515

XGBoost | Fold 4/10
Accuracy            : 0.7692
Precision           : 0.8000
Sensitivity         : 0.8000
F1 Score            : 0.8000
ROC-AUC             : 0.8242
Balanced Accuracy   : 0.7636

XGBoost | Fold 5/10
Accuracy            : 0.8077
Precision           : 0.9167
Sensitivity         : 0.7333
F1 Score            : 0.8148
ROC-AUC             : 0.8788
Balanced Accuracy   : 0.8212

XGBoost | Fold 6/10
Accuracy            : 0.7692
Precision           : 1.0000
Sensitivity         : 0.6000
F1 Score            : 0.7500
ROC-AUC             : 0.8485
Balanced Accuracy   : 0.8000

XGBoost | Fold 7/10
Accuracy            : 0.7200
Precision           : 0.8333
Sensitivity         : 0.6667
F1 Score            : 0.7407
ROC-AUC             : 0.7967
Balanced Accuracy   : 0.7333

XGBoost | Fold 8/10
Accuracy            : 0.8000
Precision           : 0.8571
Sensitivity         : 0.8000
F1 Score            : 0.8276
ROC-AUC             : 0.8667
Balanced Accuracy   : 0.8000

XGBoost | Fold 9/10
Accuracy            : 0.7600
Precision           : 0.8462
Sensitivity         : 0.7333
F1 Score            : 0.7857
ROC-AUC             : 0.8000
Balanced Accuracy   : 0.7667

XGBoost | Fold 10/10
Accuracy            : 0.8000
Precision           : 0.8571
Sensitivity         : 0.8000
F1 Score            : 0.8276
ROC-AUC             : 0.8333
Balanced Accuracy   : 0.8000

================================================
XGBoost - Cross-Validation (10-fold)
================================================
Accuracy            : 0.7580
Precision           : 0.8344
Recall/Sensitivity  : 0.7542
F1 Score            : 0.7851
ROC-AUC             : 0.8282
Balanced Accuracy   : 0.7571

================================================
XGBoost - Test Set Performance
================================================
Accuracy            : 0.6406 (95% CI: 0.5182-0.7471)
Precision           : 0.6923 (95% CI: 0.5358-0.8143)
Sensitivity         : 0.7105 (95% CI: 0.5524-0.8300)
Specificity         : 0.5385 (95% CI: 0.3546-0.7124)
F1 Score            : 0.7013
ROC-AUC             : 0.7794
Balanced Accuracy   : 0.6245
MCC                 : 0.2506

Confusion Matrix:
[[14 12]
 [11 27]]

TN : 14
FP : 12
FN : 11
TP : 27


################################################
Evaluating: Random Forest
################################################

Random Forest | Fold 1/10
Accuracy            : 0.6538
Precision           : 0.6667
Sensitivity         : 0.8750
F1 Score            : 0.7568
ROC-AUC             : 0.8625
Balanced Accuracy   : 0.5875

Random Forest | Fold 2/10
Accuracy            : 0.6538
Precision           : 0.7143
Sensitivity         : 0.6667
F1 Score            : 0.6897
ROC-AUC             : 0.7152
Balanced Accuracy   : 0.6515

Random Forest | Fold 3/10
Accuracy            : 0.8462
Precision           : 0.8667
Sensitivity         : 0.8667
F1 Score            : 0.8667
ROC-AUC             : 0.8788
Balanced Accuracy   : 0.8424

Random Forest | Fold 4/10
Accuracy            : 0.7308
Precision           : 0.7500
Sensitivity         : 0.8000
F1 Score            : 0.7742
ROC-AUC             : 0.8061
Balanced Accuracy   : 0.7182

Random Forest | Fold 5/10
Accuracy            : 0.8462
Precision           : 1.0000
Sensitivity         : 0.7333
F1 Score            : 0.8462
ROC-AUC             : 0.8788
Balanced Accuracy   : 0.8667

Random Forest | Fold 6/10
Accuracy            : 0.8077
Precision           : 1.0000
Sensitivity         : 0.6667
F1 Score            : 0.8000
ROC-AUC             : 0.8364
Balanced Accuracy   : 0.8333

Random Forest | Fold 7/10
Accuracy            : 0.6400
Precision           : 0.7143
Sensitivity         : 0.6667
F1 Score            : 0.6897
ROC-AUC             : 0.7433
Balanced Accuracy   : 0.6333

Random Forest | Fold 8/10
Accuracy            : 0.8000
Precision           : 0.8125
Sensitivity         : 0.8667
F1 Score            : 0.8387
ROC-AUC             : 0.8667
Balanced Accuracy   : 0.7833

Random Forest | Fold 9/10
Accuracy            : 0.7600
Precision           : 0.8462
Sensitivity         : 0.7333
F1 Score            : 0.7857
ROC-AUC             : 0.8067
Balanced Accuracy   : 0.7667

Random Forest | Fold 10/10
Accuracy            : 0.7600
Precision           : 0.8462
Sensitivity         : 0.7333
F1 Score            : 0.7857
ROC-AUC             : 0.8100
Balanced Accuracy   : 0.7667

================================================
Random Forest - Cross-Validation (10-fold)
================================================
Accuracy            : 0.7498
Precision           : 0.8217
Recall/Sensitivity  : 0.7608
F1 Score            : 0.7833
ROC-AUC             : 0.8204
Balanced Accuracy   : 0.7450

================================================
Random Forest - Test Set Performance
================================================
Accuracy            : 0.6562 (95% CI: 0.5340-0.7608)
Precision           : 0.6905 (95% CI: 0.5397-0.8093)
Sensitivity         : 0.7632 (95% CI: 0.6079-0.8701)
Specificity         : 0.5000 (95% CI: 0.3206-0.6794)
F1 Score            : 0.7250
ROC-AUC             : 0.7419
Balanced Accuracy   : 0.6316
MCC                 : 0.2721

Confusion Matrix:
[[13 13]
 [ 9 29]]

TN : 13
FP : 13
FN : 9
TP : 29


################################################
Evaluating: HistGradientBoosting
################################################

HistGradientBoosting | Fold 1/10
Accuracy            : 0.6923
Precision           : 0.7000
Sensitivity         : 0.8750
F1 Score            : 0.7778
ROC-AUC             : 0.8062
Balanced Accuracy   : 0.6375

HistGradientBoosting | Fold 2/10
Accuracy            : 0.6538
Precision           : 0.7143
Sensitivity         : 0.6667
F1 Score            : 0.6897
ROC-AUC             : 0.6879
Balanced Accuracy   : 0.6515

HistGradientBoosting | Fold 3/10
Accuracy            : 0.7308
Precision           : 0.7222
Sensitivity         : 0.8667
F1 Score            : 0.7879
ROC-AUC             : 0.7879
Balanced Accuracy   : 0.7061

HistGradientBoosting | Fold 4/10
Accuracy            : 0.6538
Precision           : 0.6875
Sensitivity         : 0.7333
F1 Score            : 0.7097
ROC-AUC             : 0.7879
Balanced Accuracy   : 0.6394

HistGradientBoosting | Fold 5/10
Accuracy            : 0.8462
Precision           : 1.0000
Sensitivity         : 0.7333
F1 Score            : 0.8462
ROC-AUC             : 0.9030
Balanced Accuracy   : 0.8667

HistGradientBoosting | Fold 6/10
Accuracy            : 0.7692
Precision           : 1.0000
Sensitivity         : 0.6000
F1 Score            : 0.7500
ROC-AUC             : 0.8848
Balanced Accuracy   : 0.8000

HistGradientBoosting | Fold 7/10
Accuracy            : 0.6800
Precision           : 0.8182
Sensitivity         : 0.6000
F1 Score            : 0.6923
ROC-AUC             : 0.7900
Balanced Accuracy   : 0.7000

HistGradientBoosting | Fold 8/10
Accuracy            : 0.7600
Precision           : 0.8462
Sensitivity         : 0.7333
F1 Score            : 0.7857
ROC-AUC             : 0.8467
Balanced Accuracy   : 0.7667

HistGradientBoosting | Fold 9/10
Accuracy            : 0.8000
Precision           : 0.9167
Sensitivity         : 0.7333
F1 Score            : 0.8148
ROC-AUC             : 0.8000
Balanced Accuracy   : 0.8167

HistGradientBoosting | Fold 10/10
Accuracy            : 0.8000
Precision           : 0.8571
Sensitivity         : 0.8000
F1 Score            : 0.8276
ROC-AUC             : 0.8200
Balanced Accuracy   : 0.8000

================================================
HistGradientBoosting - Cross-Validation (10-fold)
================================================
Accuracy            : 0.7386
Precision           : 0.8262
Recall/Sensitivity  : 0.7342
F1 Score            : 0.7682
ROC-AUC             : 0.8114
Balanced Accuracy   : 0.7384

================================================
HistGradientBoosting - Test Set Performance
================================================
Accuracy            : 0.6719 (95% CI: 0.5500-0.7743)
Precision           : 0.7179 (95% CI: 0.5622-0.8346)
Sensitivity         : 0.7368 (95% CI: 0.5799-0.8503)
Specificity         : 0.5769 (95% CI: 0.3895-0.7446)
F1 Score            : 0.7273
ROC-AUC             : 0.7743
Balanced Accuracy   : 0.6569
MCC                 : 0.3159

Confusion Matrix:
[[15 11]
 [10 28]]

TN : 15
FP : 11
FN : 10
TP : 28


################################################
Evaluating: Voting Fusion
################################################

Voting Fusion | Fold 1/10
Accuracy            : 0.6923
Precision           : 0.7000
Sensitivity         : 0.8750
F1 Score            : 0.7778
ROC-AUC             : 0.8375
Balanced Accuracy   : 0.6375

Voting Fusion | Fold 2/10
Accuracy            : 0.6923
Precision           : 0.7692
Sensitivity         : 0.6667
F1 Score            : 0.7143
ROC-AUC             : 0.7091
Balanced Accuracy   : 0.6970

Voting Fusion | Fold 3/10
Accuracy            : 0.7692
Precision           : 0.7647
Sensitivity         : 0.8667
F1 Score            : 0.8125
ROC-AUC             : 0.8485
Balanced Accuracy   : 0.7515

Voting Fusion | Fold 4/10
Accuracy            : 0.6923
Precision           : 0.7059
Sensitivity         : 0.8000
F1 Score            : 0.7500
ROC-AUC             : 0.8000
Balanced Accuracy   : 0.6727

Voting Fusion | Fold 5/10
Accuracy            : 0.8462
Precision           : 1.0000
Sensitivity         : 0.7333
F1 Score            : 0.8462
ROC-AUC             : 0.8727
Balanced Accuracy   : 0.8667

Voting Fusion | Fold 6/10
Accuracy            : 0.7692
Precision           : 1.0000
Sensitivity         : 0.6000
F1 Score            : 0.7500
ROC-AUC             : 0.8606
Balanced Accuracy   : 0.8000

Voting Fusion | Fold 7/10
Accuracy            : 0.7200
Precision           : 0.8333
Sensitivity         : 0.6667
F1 Score            : 0.7407
ROC-AUC             : 0.7767
Balanced Accuracy   : 0.7333

Voting Fusion | Fold 8/10
Accuracy            : 0.7200
Precision           : 0.7857
Sensitivity         : 0.7333
F1 Score            : 0.7586
ROC-AUC             : 0.8600
Balanced Accuracy   : 0.7167

Voting Fusion | Fold 9/10
Accuracy            : 0.7600
Precision           : 0.8462
Sensitivity         : 0.7333
F1 Score            : 0.7857
ROC-AUC             : 0.8067
Balanced Accuracy   : 0.7667

Voting Fusion | Fold 10/10
Accuracy            : 0.8000
Precision           : 0.8571
Sensitivity         : 0.8000
F1 Score            : 0.8276
ROC-AUC             : 0.8333
Balanced Accuracy   : 0.8000

================================================
Voting Fusion - Cross-Validation (10-fold)
================================================
Accuracy            : 0.7462
Precision           : 0.8262
Recall/Sensitivity  : 0.7475
F1 Score            : 0.7763
ROC-AUC             : 0.8205
Balanced Accuracy   : 0.7442

================================================
Voting Fusion - Test Set Performance
================================================
Accuracy            : 0.6562 (95% CI: 0.5340-0.7608)
Precision           : 0.7105 (95% CI: 0.5524-0.8300)
Sensitivity         : 0.7105 (95% CI: 0.5524-0.8300)
Specificity         : 0.5769 (95% CI: 0.3895-0.7446)
F1 Score            : 0.7105
ROC-AUC             : 0.7733
Balanced Accuracy   : 0.6437
MCC                 : 0.2874

Confusion Matrix:
[[15 11]
 [11 27]]

TN : 15
FP : 11
FN : 11
TP : 27


################################################
Evaluating: Stacking Fusion
################################################

Stacking Fusion | Fold 1/10
Accuracy            : 0.6923
Precision           : 0.7500
Sensitivity         : 0.7500
F1 Score            : 0.7500
ROC-AUC             : 0.8000
Balanced Accuracy   : 0.6750

Stacking Fusion | Fold 2/10
Accuracy            : 0.6538
Precision           : 0.7143
Sensitivity         : 0.6667
F1 Score            : 0.6897
ROC-AUC             : 0.7818
Balanced Accuracy   : 0.6515

Stacking Fusion | Fold 3/10
Accuracy            : 0.7308
Precision           : 0.7857
Sensitivity         : 0.7333
F1 Score            : 0.7586
ROC-AUC             : 0.7697
Balanced Accuracy   : 0.7303

Stacking Fusion | Fold 4/10
Accuracy            : 0.6538
Precision           : 0.8000
Sensitivity         : 0.5333
F1 Score            : 0.6400
ROC-AUC             : 0.7636
Balanced Accuracy   : 0.6758

Stacking Fusion | Fold 5/10
Accuracy            : 0.8462
Precision           : 1.0000
Sensitivity         : 0.7333
F1 Score            : 0.8462
ROC-AUC             : 0.9273
Balanced Accuracy   : 0.8667

Stacking Fusion | Fold 6/10
Accuracy            : 0.6538
Precision           : 0.8750
Sensitivity         : 0.4667
F1 Score            : 0.6087
ROC-AUC             : 0.7152
Balanced Accuracy   : 0.6879

Stacking Fusion | Fold 7/10
Accuracy            : 0.7200
Precision           : 0.8333
Sensitivity         : 0.6667
F1 Score            : 0.7407
ROC-AUC             : 0.8300
Balanced Accuracy   : 0.7333

Stacking Fusion | Fold 8/10
Accuracy            : 0.8400
Precision           : 1.0000
Sensitivity         : 0.7333
F1 Score            : 0.8462
ROC-AUC             : 0.9600
Balanced Accuracy   : 0.8667

Stacking Fusion | Fold 9/10
Accuracy            : 0.7200
Precision           : 0.8333
Sensitivity         : 0.6667
F1 Score            : 0.7407
ROC-AUC             : 0.8467
Balanced Accuracy   : 0.7333

Stacking Fusion | Fold 10/10
Accuracy            : 0.6800
Precision           : 0.8889
Sensitivity         : 0.5333
F1 Score            : 0.6667
ROC-AUC             : 0.9000
Balanced Accuracy   : 0.7167

================================================
Stacking Fusion - Cross-Validation (10-fold)
================================================
Accuracy            : 0.7191
Precision           : 0.8481
Recall/Sensitivity  : 0.6483
F1 Score            : 0.7287
ROC-AUC             : 0.8294
Balanced Accuracy   : 0.7337

================================================
Stacking Fusion - Test Set Performance
================================================
Accuracy            : 0.7344 (95% CI: 0.6152-0.8270)
Precision           : 0.8182 (95% CI: 0.6561-0.9139)
Sensitivity         : 0.7105 (95% CI: 0.5524-0.8300)
Specificity         : 0.7692 (95% CI: 0.5795-0.8897)
F1 Score            : 0.7606
ROC-AUC             : 0.8249
Balanced Accuracy   : 0.7399
MCC                 : 0.4715

Confusion Matrix:
[[20  6]
 [11 27]]

TN : 20
FP : 6
FN : 11
TP : 27

================================================
FINAL MODEL COMPARISON
================================================

,CV Accuracy,CV Precision,CV Sensitivity,CV F1,CV ROC-AUC,CV Balanced Accuracy,Accuracy,Accuracy CI Low,Accuracy CI High,Precision,...,Specificity CI Low,Specificity CI High,F1,ROC-AUC,Balanced Accuracy,MCC,TN,FP,FN,TP
Stacking Fusion,0.719077,0.848056,0.648333,0.728743,0.829424,0.733712,0.734375,0.615171,0.827036,0.818182,...,0.579484,0.889662,0.760563,0.824899,0.739879,0.471479,20.0,6.0,11.0,27.0
HistGradientBoosting,0.738615,0.826215,0.734167,0.768157,0.811443,0.738447,0.671875,0.549991,0.774294,0.717949,...,0.389486,0.744556,0.727273,0.774291,0.656883,0.315850,15.0,11.0,10.0,28.0
Random Forest,0.749846,0.821671,0.760833,0.783322,0.820432,0.744962,0.656250,0.534036,0.760769,0.690476,...,0.320606,0.679394,0.725000,0.741903,0.631579,0.272119,13.0,13.0,9.0,29.0
Voting Fusion,0.746154,0.826216,0.747500,0.776338,0.820508,0.744205,0.656250,0.534036,0.760769,0.710526,...,0.389486,0.744556,0.710526,0.773279,0.643725,0.287449,15.0,11.0,11.0,27.0
XGBoost,0.758000,0.834438,0.754167,0.785101,0.828208,0.757083,0.640625,0.518209,0.747116,0.692308,...,0.354579,0.712441,0.701299,0.779352,0.624494,0.250642,14.0,12.0,11.0,27.0

Vanilla DANN

In [1]:
# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

df_acoustic_top7 = pd.read_csv('/content/drive/MyDrive/Acoustic-subject-level-dataset_top7.csv')
df_acoustic_top7 = df_acoustic_top7.drop(columns=['Participant_ID'])
print(df_acoustic_top7.shape)
print(df_acoustic_top7.head())

(193, 8)
       RPDE  Degree-voice breaks  Delta2  Delta3  Delta11  MFCC5   spread1  \
0  0.428488                  0.0     0.0     0.0      0.0    0.0 -4.239926
1  0.542488                  0.0     0.0     0.0      0.0    0.0 -4.519291
2  0.332247                  0.0     0.0     0.0      0.0    0.0 -7.226125
3  0.498593                  0.0     0.0     0.0      0.0    0.0 -5.632290
4  0.470775                  0.0     0.0     0.0      0.0    0.0 -5.523149

   Status
0       1
1       1
2       0
3       1
4       1

In [3]:
import pandas as pd

final_meg_df = pd.read_csv('/content/drive/MyDrive/final_meg-go(par)_top7_rfc+shap_10-fold_analysis_last_column.csv')

print("Loaded data shape:", final_meg_df.shape)
print(final_meg_df.head())

Loaded data shape: (127, 8)
   env_kurt_R_mean  env_kurt_R_std  env_kurt_L_mean  env_kurt_L_std  \
0         5.749049       15.894836         5.962378       17.165772
1         4.459546        7.184608         4.390848        6.578943
2         1.161476        0.718562         1.885349        1.714298
3         1.138575        0.699601         1.365950        0.817770
4     18283.789736     4480.567058     18277.357293     4487.602704

   burst_dur_cv_L_std  env_mod_rate_L_std  env_skew_L_mean  PD_Label_Combined
0        4.938551e-02            0.244843         1.123760                  0
1        1.147524e-01            0.117228         1.400286                  0
2        5.040195e-02            0.275503         0.953293                  0
3        4.311462e-02            0.460356         0.920828                  1
4        1.043683e-16            0.064449       129.243639                  1

In [4]:
# ============================================================
#                VANILLA DANN BASELINE
#     DOMAIN + TASK ADVERSARIAL LEARNING
#          + 5-FOLD CROSS VALIDATION
# ============================================================

# ============================================================
# IMPORTS
# ============================================================

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from torch.autograd import Function

import torch.nn.functional as F

import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

# ============================================================
# LOAD DATA
# ============================================================

X_acoustic = df_acoustic_top7.iloc[:, :-1].values.astype(np.float32)
y_acoustic = df_acoustic_top7.iloc[:, -1].values.astype(np.int32)

X_meg = final_meg_df.iloc[:, :-1].values.astype(np.float32)
y_meg = final_meg_df.iloc[:, -1].values.astype(np.int32)

# ============================================================
# STANDARDIZATION
# ============================================================

scaler_acoustic = StandardScaler()
scaler_meg = StandardScaler()

X_acoustic = scaler_acoustic.fit_transform(X_acoustic)
X_meg = scaler_meg.fit_transform(X_meg)

# ============================================================
# DOMAIN LABELS
# ============================================================

domain_acoustic = np.zeros(len(X_acoustic))
domain_meg = np.ones(len(X_meg))

# ============================================================
# COMBINE DATA
# ============================================================

X_all = np.vstack([
    X_acoustic,
    X_meg
]).astype(np.float32)

task_labels = np.hstack([
    y_acoustic,
    y_meg
]).astype(np.int32)

domain_labels = np.hstack([
    domain_acoustic,
    domain_meg
]).astype(np.int32)

# ============================================================
# TENSORS
# ============================================================

X_all_tensor = torch.tensor(
    X_all
).float().to(device)

task_labels_tensor = torch.tensor(
    task_labels
).long().to(device)

domain_labels_tensor = torch.tensor(
    domain_labels
).long().to(device)

# ============================================================
# DATA LOADER
# ============================================================

dataset = TensorDataset(
    X_all_tensor,
    task_labels_tensor,
    domain_labels_tensor
)

loader = DataLoader(
    dataset,
    batch_size=128,
    shuffle=True
)

# ============================================================
# GRADIENT REVERSAL LAYER
# ============================================================

class GradReverse(Function):

    @staticmethod
    def forward(ctx, x, lambd=1.0):

        ctx.lambd = lambd

        return x.view_as(x)

    @staticmethod
    def backward(ctx, grad_output):

        return -ctx.lambd * grad_output, None

def grad_reverse(x, lambd=1.0):

    return GradReverse.apply(x, lambd)

# ============================================================
# VANILLA DANN MODEL
# ============================================================

class VanillaDANN(nn.Module):

    def __init__(
        self,
        input_dim=7,
        hidden_dim=32,
        task_classes=2,
        domain_classes=2
    ):

        super(VanillaDANN, self).__init__()

        self.feature_extractor = nn.Sequential(

            nn.Linear(input_dim, 32),
            nn.ReLU(),

            nn.Linear(32, hidden_dim),
            nn.ReLU()
        )

        self.task_classifier = nn.Sequential(

            nn.Linear(hidden_dim, 32),
            nn.ReLU(),

            nn.Linear(32, task_classes)
        )

        self.domain_classifier = nn.Sequential(

            nn.Linear(hidden_dim, 32),
            nn.ReLU(),

            nn.Linear(32, domain_classes)
        )

    def forward(self, x, lambd=1.0):

        features = self.feature_extractor(x)

        task_out = self.task_classifier(features)

        reversed_feat = grad_reverse(
            features,
            lambd
        )

        domain_out = self.domain_classifier(
            reversed_feat
        )

        return task_out, domain_out, features

# ============================================================
# MODEL
# ============================================================

model = VanillaDANN().to(device)

# ============================================================
# OPTIMIZER
# ============================================================

optimizer = optim.Adam(
    model.parameters(),
    lr=0.001
)

# ============================================================
# LOSSES
# ============================================================

task_loss_fn = nn.CrossEntropyLoss()

domain_loss_fn = nn.CrossEntropyLoss()

# ============================================================
# TRAINING
# ============================================================

epochs = 120

print("\nTraining Vanilla DANN...\n")

for epoch in range(epochs):

    model.train()

    total_loss = 0
    total_correct = 0
    total_samples = 0

    p = min(epoch / 50.0, 1.0)

    lambd = 2 / (1 + np.exp(-10 * p)) - 1

    for x_batch, y_batch, d_batch in loader:

        optimizer.zero_grad()

        task_out, domain_out, _ = model(
            x_batch,
            lambd
        )

        loss_task = task_loss_fn(
            task_out,
            y_batch
        )

        loss_domain = domain_loss_fn(
            domain_out,
            d_batch
        )

        loss = (
            loss_task +
            0.5 * loss_domain
        )

        loss.backward()

        optimizer.step()

        total_loss += loss.item()

        preds = task_out.argmax(1)

        total_correct += (
            preds == y_batch
        ).sum().item()

        total_samples += len(y_batch)

    acc = total_correct / total_samples

    print(
        f"Epoch {epoch+1}/{epochs} "
        f"| λ={lambd:.3f} "
        f"| Loss={total_loss:.4f} "
        f"| Task Acc={acc:.4f}"
    )

# ============================================================
# EXTRACT LATENT FEATURES
# ============================================================

model.eval()

with torch.no_grad():

    _, _, acoustic_latent = model(
        torch.tensor(X_acoustic).float().to(device),
        0
    )

    _, _, meg_latent = model(
        torch.tensor(X_meg).float().to(device),
        0
    )

# ============================================================
# CONVERT TO NUMPY
# ============================================================

fused_acoustic_32D = acoustic_latent.cpu().numpy()

fused_meg_32D = meg_latent.cpu().numpy()

# ============================================================
# COMBINE LATENT FEATURES
# ============================================================

X_fused = np.vstack([
    fused_acoustic_32D,
    fused_meg_32D
])

y_fused = np.hstack([
    y_acoustic,
    y_meg
])

# ============================================================
# FINAL MLP CLASSIFIER
# ============================================================

class FinalMLP(nn.Module):

    def __init__(self, input_dim=32):

        super().__init__()

        self.net = nn.Sequential(

            nn.Linear(input_dim, 64),
            nn.ReLU(),

            nn.Dropout(0.2),

            nn.Linear(64, 32),
            nn.ReLU(),

            nn.Linear(32, 2)
        )

    def forward(self, x):

        return self.net(x)

# ============================================================
# 5-FOLD CROSS VALIDATION
# ============================================================

print("\n======================================")
print(" CROSS VALIDATION RESULTS")
print("======================================\n")

skf = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

accs = []
precs = []
recs = []
f1s = []
aucs = []

fold = 1

for train_idx, test_idx in skf.split(X_fused, y_fused):

    X_train = torch.tensor(
        X_fused[train_idx]
    ).float().to(device)

    X_test = torch.tensor(
        X_fused[test_idx]
    ).float().to(device)

    y_train = torch.tensor(
        y_fused[train_idx]
    ).long().to(device)

    y_test = y_fused[test_idx]

    clf = FinalMLP().to(device)

    optimizer_clf = optim.Adam(
        clf.parameters(),
        lr=1e-3
    )

    criterion = nn.CrossEntropyLoss()

    # ========================================================
    # TRAIN CLASSIFIER
    # ========================================================

    clf.train()

    for epoch in range(80):

        optimizer_clf.zero_grad()

        outputs = clf(X_train)

        loss = criterion(
            outputs,
            y_train
        )

        loss.backward()

        optimizer_clf.step()

    # ========================================================
    # TEST
    # ========================================================

    clf.eval()

    with torch.no_grad():

        outputs = clf(X_test)

        probs = F.softmax(
            outputs,
            dim=1
        )[:, 1].cpu().numpy()

        preds = outputs.argmax(1).cpu().numpy()

    acc = accuracy_score(y_test, preds)

    prec = precision_score(y_test, preds)

    rec = recall_score(y_test, preds)

    f1 = f1_score(y_test, preds)

    auc = roc_auc_score(y_test, probs)

    accs.append(acc)
    precs.append(prec)
    recs.append(rec)
    f1s.append(f1)
    aucs.append(auc)

    print(f"Fold {fold}")

    print(f"Accuracy  : {acc:.4f}")
    print(f"Precision : {prec:.4f}")
    print(f"Recall    : {rec:.4f}")
    print(f"F1-Score  : {f1:.4f}")
    print(f"AUC       : {auc:.4f}")

    print()

    fold += 1

# ============================================================
# FINAL RESULTS
# ============================================================

print("\n======================================")
print(" FINAL RESULTS")
print("======================================\n")

print(f"Mean Accuracy  : {np.mean(accs)*100:.2f}%")
print(f"Mean Precision : {np.mean(precs)*100:.2f}%")
print(f"Mean Recall    : {np.mean(recs)*100:.2f}%")
print(f"Mean F1-Score  : {np.mean(f1s)*100:.2f}%")
print(f"Mean AUC       : {np.mean(aucs)*100:.2f}%")

# ============================================================
# LATENT SHAPES
# ============================================================

print("\n===================================")
print(" LATENT FEATURE SHAPES")
print("===================================\n")

print(
    f"Acoustic Latent Shape: "
    f"{fused_acoustic_32D.shape}"
)

print(
    f"MEG Latent Shape: "
    f"{fused_meg_32D.shape}"
)

Training Vanilla DANN...

Epoch 1/120 | λ=0.000 | Loss=3.0526 | Task Acc=0.5906
Epoch 2/120 | λ=0.100 | Loss=3.0264 | Task Acc=0.5906
Epoch 3/120 | λ=0.197 | Loss=3.0010 | Task Acc=0.5906
Epoch 4/120 | λ=0.291 | Loss=2.9994 | Task Acc=0.5906
Epoch 5/120 | λ=0.380 | Loss=2.9567 | Task Acc=0.5906
Epoch 6/120 | λ=0.462 | Loss=2.9424 | Task Acc=0.5906
Epoch 7/120 | λ=0.537 | Loss=2.9424 | Task Acc=0.5906
Epoch 8/120 | λ=0.604 | Loss=2.9225 | Task Acc=0.5906
Epoch 9/120 | λ=0.664 | Loss=2.8951 | Task Acc=0.5906
Epoch 10/120 | λ=0.716 | Loss=2.8875 | Task Acc=0.5906
Epoch 11/120 | λ=0.762 | Loss=2.8571 | Task Acc=0.5906
Epoch 12/120 | λ=0.800 | Loss=2.8373 | Task Acc=0.5906
Epoch 13/120 | λ=0.834 | Loss=2.8591 | Task Acc=0.5906
Epoch 14/120 | λ=0.862 | Loss=2.8228 | Task Acc=0.5906
Epoch 15/120 | λ=0.885 | Loss=2.8286 | Task Acc=0.5938
Epoch 16/120 | λ=0.905 | Loss=2.8199 | Task Acc=0.6000
Epoch 17/120 | λ=0.922 | Loss=2.7607 | Task Acc=0.6281
Epoch 18/120 | λ=0.935 | Loss=2.7606 | Task Acc=0.6781
Epoch 19/120 | λ=0.947 | Loss=2.7711 | Task Acc=0.6813
Epoch 20/120 | λ=0.956 | Loss=2.7255 | Task Acc=0.6937
Epoch 21/120 | λ=0.964 | Loss=2.7029 | Task Acc=0.7000
Epoch 22/120 | λ=0.970 | Loss=2.6908 | Task Acc=0.7031
Epoch 23/120 | λ=0.976 | Loss=2.6905 | Task Acc=0.7031
Epoch 24/120 | λ=0.980 | Loss=2.6654 | Task Acc=0.7031
Epoch 25/120 | λ=0.984 | Loss=2.6501 | Task Acc=0.6906
Epoch 26/120 | λ=0.987 | Loss=2.6348 | Task Acc=0.6906
Epoch 27/120 | λ=0.989 | Loss=2.6148 | Task Acc=0.6906
Epoch 28/120 | λ=0.991 | Loss=2.6057 | Task Acc=0.6969
Epoch 29/120 | λ=0.993 | Loss=2.6149 | Task Acc=0.6969
Epoch 30/120 | λ=0.994 | Loss=2.5886 | Task Acc=0.7063
Epoch 31/120 | λ=0.995 | Loss=2.5637 | Task Acc=0.7000
Epoch 32/120 | λ=0.996 | Loss=2.5500 | Task Acc=0.7094
Epoch 33/120 | λ=0.997 | Loss=2.5484 | Task Acc=0.7250
Epoch 34/120 | λ=0.997 | Loss=2.5210 | Task Acc=0.7188
Epoch 35/120 | λ=0.998 | Loss=2.5402 | Task Acc=0.7281
Epoch 36/120 | λ=0.998 | Loss=2.4952 | Task Acc=0.7156
Epoch 37/120 | λ=0.999 | Loss=2.4963 | Task Acc=0.7219
Epoch 38/120 | λ=0.999 | Loss=2.4539 | Task Acc=0.7500
Epoch 39/120 | λ=0.999 | Loss=2.4334 | Task Acc=0.7438
Epoch 40/120 | λ=0.999 | Loss=2.4557 | Task Acc=0.7469
Epoch 41/120 | λ=0.999 | Loss=2.4184 | Task Acc=0.7406
Epoch 42/120 | λ=0.999 | Loss=2.4655 | Task Acc=0.7375
Epoch 43/120 | λ=1.000 | Loss=2.3809 | Task Acc=0.7375
Epoch 44/120 | λ=1.000 | Loss=2.4222 | Task Acc=0.7469
Epoch 45/120 | λ=1.000 | Loss=2.3940 | Task Acc=0.7438
Epoch 46/120 | λ=1.000 | Loss=2.3542 | Task Acc=0.7500
Epoch 47/120 | λ=1.000 | Loss=2.3627 | Task Acc=0.7531
Epoch 48/120 | λ=1.000 | Loss=2.3610 | Task Acc=0.7500
Epoch 49/120 | λ=1.000 | Loss=2.3724 | Task Acc=0.7438
Epoch 50/120 | λ=1.000 | Loss=2.3596 | Task Acc=0.7406
Epoch 51/120 | λ=1.000 | Loss=2.3871 | Task Acc=0.7438
Epoch 52/120 | λ=1.000 | Loss=2.3574 | Task Acc=0.7500
Epoch 53/120 | λ=1.000 | Loss=2.3874 | Task Acc=0.7562
Epoch 54/120 | λ=1.000 | Loss=2.3431 | Task Acc=0.7375
Epoch 55/120 | λ=1.000 | Loss=2.3495 | Task Acc=0.7406
Epoch 56/120 | λ=1.000 | Loss=2.3235 | Task Acc=0.7531
Epoch 57/120 | λ=1.000 | Loss=2.3255 | Task Acc=0.7531
Epoch 58/120 | λ=1.000 | Loss=2.3536 | Task Acc=0.7531
Epoch 59/120 | λ=1.000 | Loss=2.3544 | Task Acc=0.7500
Epoch 60/120 | λ=1.000 | Loss=2.3322 | Task Acc=0.7531
Epoch 61/120 | λ=1.000 | Loss=2.3297 | Task Acc=0.7469
Epoch 62/120 | λ=1.000 | Loss=2.2988 | Task Acc=0.7469
Epoch 63/120 | λ=1.000 | Loss=2.3218 | Task Acc=0.7500
Epoch 64/120 | λ=1.000 | Loss=2.3401 | Task Acc=0.7562
Epoch 65/120 | λ=1.000 | Loss=2.3114 | Task Acc=0.7594
Epoch 66/120 | λ=1.000 | Loss=2.3067 | Task Acc=0.7625
Epoch 67/120 | λ=1.000 | Loss=2.2647 | Task Acc=0.7594
Epoch 68/120 | λ=1.000 | Loss=2.2382 | Task Acc=0.7594
Epoch 69/120 | λ=1.000 | Loss=2.2379 | Task Acc=0.7625
Epoch 70/120 | λ=1.000 | Loss=2.2509 | Task Acc=0.7531
Epoch 71/120 | λ=1.000 | Loss=2.2687 | Task Acc=0.7594
Epoch 72/120 | λ=1.000 | Loss=2.2710 | Task Acc=0.7562
Epoch 73/120 | λ=1.000 | Loss=2.2156 | Task Acc=0.7594
Epoch 74/120 | λ=1.000 | Loss=2.2993 | Task Acc=0.7562
Epoch 75/120 | λ=1.000 | Loss=2.2072 | Task Acc=0.7594
Epoch 76/120 | λ=1.000 | Loss=2.2421 | Task Acc=0.7594
Epoch 77/120 | λ=1.000 | Loss=2.2385 | Task Acc=0.7625
Epoch 78/120 | λ=1.000 | Loss=2.2361 | Task Acc=0.7625
Epoch 79/120 | λ=1.000 | Loss=2.1912 | Task Acc=0.7656
Epoch 80/120 | λ=1.000 | Loss=2.3064 | Task Acc=0.7656
Epoch 81/120 | λ=1.000 | Loss=2.2395 | Task Acc=0.7625
Epoch 82/120 | λ=1.000 | Loss=2.2508 | Task Acc=0.7625
Epoch 83/120 | λ=1.000 | Loss=2.2454 | Task Acc=0.7594
Epoch 84/120 | λ=1.000 | Loss=2.2564 | Task Acc=0.7594
Epoch 85/120 | λ=1.000 | Loss=2.2663 | Task Acc=0.7625
Epoch 86/120 | λ=1.000 | Loss=2.2768 | Task Acc=0.7625
Epoch 87/120 | λ=1.000 | Loss=2.2938 | Task Acc=0.7625
Epoch 88/120 | λ=1.000 | Loss=2.2457 | Task Acc=0.7594
Epoch 89/120 | λ=1.000 | Loss=2.2993 | Task Acc=0.7625
Epoch 90/120 | λ=1.000 | Loss=2.2128 | Task Acc=0.7625
Epoch 91/120 | λ=1.000 | Loss=2.2797 | Task Acc=0.7531
Epoch 92/120 | λ=1.000 | Loss=2.2463 | Task Acc=0.7531
Epoch 93/120 | λ=1.000 | Loss=2.2580 | Task Acc=0.7562
Epoch 94/120 | λ=1.000 | Loss=2.2389 | Task Acc=0.7594
Epoch 95/120 | λ=1.000 | Loss=2.2640 | Task Acc=0.7625
Epoch 96/120 | λ=1.000 | Loss=2.2511 | Task Acc=0.7594
Epoch 97/120 | λ=1.000 | Loss=2.2531 | Task Acc=0.7531
Epoch 98/120 | λ=1.000 | Loss=2.2468 | Task Acc=0.7562
Epoch 99/120 | λ=1.000 | Loss=2.2545 | Task Acc=0.7594
Epoch 100/120 | λ=1.000 | Loss=2.2167 | Task Acc=0.7562
Epoch 101/120 | λ=1.000 | Loss=2.2150 | Task Acc=0.7625
Epoch 102/120 | λ=1.000 | Loss=2.2351 | Task Acc=0.7594
Epoch 103/120 | λ=1.000 | Loss=2.2157 | Task Acc=0.7625
Epoch 104/120 | λ=1.000 | Loss=2.2527 | Task Acc=0.7625
Epoch 105/120 | λ=1.000 | Loss=2.2082 | Task Acc=0.7531
Epoch 106/120 | λ=1.000 | Loss=2.2115 | Task Acc=0.7562
Epoch 107/120 | λ=1.000 | Loss=2.1544 | Task Acc=0.7594
Epoch 108/120 | λ=1.000 | Loss=2.1613 | Task Acc=0.7625
Epoch 109/120 | λ=1.000 | Loss=2.2156 | Task Acc=0.7625
Epoch 110/120 | λ=1.000 | Loss=2.2177 | Task Acc=0.7562
Epoch 111/120 | λ=1.000 | Loss=2.1949 | Task Acc=0.7656
Epoch 112/120 | λ=1.000 | Loss=2.2690 | Task Acc=0.7625
Epoch 113/120 | λ=1.000 | Loss=2.2272 | Task Acc=0.7656
Epoch 114/120 | λ=1.000 | Loss=2.1882 | Task Acc=0.7594
Epoch 115/120 | λ=1.000 | Loss=2.1727 | Task Acc=0.7688
Epoch 116/120 | λ=1.000 | Loss=2.1803 | Task Acc=0.7594
Epoch 117/120 | λ=1.000 | Loss=2.2036 | Task Acc=0.7688
Epoch 118/120 | λ=1.000 | Loss=2.2007 | Task Acc=0.7625
Epoch 119/120 | λ=1.000 | Loss=2.2091 | Task Acc=0.7656
Epoch 120/120 | λ=1.000 | Loss=2.1777 | Task Acc=0.7719

======================================
 CROSS VALIDATION RESULTS
======================================

Fold 1
Accuracy  : 0.6875
Precision : 0.7250
Recall    : 0.7632
F1-Score  : 0.7436
AUC       : 0.7945

Fold 2
Accuracy  : 0.7656
Precision : 0.8108
Recall    : 0.7895
F1-Score  : 0.8000
AUC       : 0.8512

Fold 3
Accuracy  : 0.8438
Precision : 0.9375
Recall    : 0.7895
F1-Score  : 0.8571
AUC       : 0.9337

Fold 4
Accuracy  : 0.7656
Precision : 0.8108
Recall    : 0.7895
F1-Score  : 0.8000
AUC       : 0.8998

Fold 5
Accuracy  : 0.7344
Precision : 0.7941
Recall    : 0.7297
F1-Score  : 0.7606
AUC       : 0.7908


======================================
 FINAL RESULTS
======================================

Mean Accuracy  : 75.94%
Mean Precision : 81.56%
Mean Recall    : 77.23%
Mean F1-Score  : 79.23%
Mean AUC       : 85.40%

===================================
 LATENT FEATURE SHAPES
===================================

Acoustic Latent Shape: (193, 32)
MEG Latent Shape: (127, 32)

In [5]:
import torch

# Assuming fused_acoustic_32D and fused_meg_32D are numpy arrays of shape (7350, 32)

# Step 1: Convert numpy arrays to torch tensors (float32)
fused_acoustic_tensor = torch.from_numpy(fused_acoustic_32D).float()
fused_meg_tensor = torch.from_numpy(fused_meg_32D).float()

# Step 2: Concatenate row-wise (along dim=0)
fused_output_tensor = torch.cat([fused_acoustic_tensor, fused_meg_tensor], dim=0)  # Shape: (14700, 32)

# Step 3: Print shape and dtype
print(fused_output_tensor.shape)  # torch.Size([14700, 32])
print(fused_output_tensor.dtype)  # torch.float32

torch.Size([320, 32])
torch.float32

In [6]:
import torch
import numpy as np

# ------------------------
# Step 1: Extract targets correctly
# ------------------------

# Acoustic target from df_acoustic_top7 (last column)
y_acoustic = df_acoustic_top7.iloc[:, -1].values.astype(np.int32)   # (7350,)

# MEG target from final_meg_df (last column)
y_meg = final_meg_df.iloc[:, -1].values.astype(np.int32)           # (7350,)

# Convert to tensors (reshape to column)
acoustic_target_tensor = torch.tensor(y_acoustic).long().reshape(-1, 1)   # (7350, 1)
meg_target_tensor      = torch.tensor(y_meg).long().reshape(-1, 1)        # (7350, 1)

# ------------------------
# Step 2: Convert 32D latent features to tensors
# ------------------------

fused_acoustic_tensor = torch.from_numpy(fused_acoustic_32D).float()  # (7350, 32)
fused_meg_tensor      = torch.from_numpy(fused_meg_32D).float()       # (7350, 32)

# ------------------------
# Step 3: Attach target columns
# ------------------------

# Concatenate latent features with target
acoustic_full = torch.cat([fused_acoustic_tensor, acoustic_target_tensor.float()], dim=1)  # (7350, 65)
meg_full      = torch.cat([fused_meg_tensor,      meg_target_tensor.float()],      dim=1)  # (7350, 65)

# ------------------------
# Step 4: Concatenate both datasets
# ------------------------

fused_df = torch.cat([acoustic_full, meg_full], dim=0)  # (14700, 65)

# ------------------------
# Step 5: Separate features and labels for PyTorch
# ------------------------

X = fused_df[:, :-1].float()   # Features (32D) -> float32
y = fused_df[:, -1].long()     # Target -> int32

# ------------------------
# Step 6: Print shapes and dtypes
# ------------------------

print(f"Features shape: {X.shape}, dtype: {X.dtype}")  # (14700, 32), float32
print(f"Labels shape: {y.shape}, dtype: {y.dtype}")    # (14700,), int32

Features shape: torch.Size([320, 32]), dtype: torch.float32
Labels shape: torch.Size([320]), dtype: torch.int64

In [7]:
import torch
import pandas as pd

# fused_df shape = (14700, 33)

# Step 6: Convert fused tensor to numpy
fused_df_np = fused_df.numpy()

# Step 7: Create correct column names for 32 latent features + 1 label
feature_names = [f"feat_{i}" for i in range(32)]
feature_names.append("PD_Label_Combined")

# Step 8: Convert to DataFrame
fused_df_named = pd.DataFrame(fused_df_np, columns=feature_names)

# Step 9: Verify
print(fused_df_named.shape)
print(fused_df_named.head())
print(fused_df_named.tail())

(320, 33)
   feat_0  feat_1    feat_2    feat_3  feat_4    feat_5  feat_6  feat_7  \
0     0.0     0.0  0.000000  0.110135     0.0  0.608933     0.0     0.0
1     0.0     0.0  0.000000  0.149674     0.0  0.614074     0.0     0.0
2     0.0     0.0  0.236298  0.000000     0.0  0.556597     0.0     0.0
3     0.0     0.0  0.000000  0.135428     0.0  0.611338     0.0     0.0
4     0.0     0.0  0.000000  0.131041     0.0  0.613933     0.0     0.0

     feat_8    feat_9  ...  feat_23  feat_24  feat_25  feat_26  feat_27  \
0  0.038362  0.279181  ...      0.0      0.0      0.0      0.0      0.0
1  0.000000  0.237277  ...      0.0      0.0      0.0      0.0      0.0
2  0.458350  0.060499  ...      0.0      0.0      0.0      0.0      0.0
3  0.117138  0.178453  ...      0.0      0.0      0.0      0.0      0.0
4  0.124046  0.190780  ...      0.0      0.0      0.0      0.0      0.0

    feat_28   feat_29  feat_30  feat_31  PD_Label_Combined
0  0.738507  0.000000      0.0      0.0                1.0
1  0.867541  0.000000      0.0      0.0                1.0
2  0.575536  0.138301      0.0      0.0                0.0
3  0.766817  0.000000      0.0      0.0                1.0
4  0.734409  0.000000      0.0      0.0                1.0

[5 rows x 33 columns]
     feat_0  feat_1    feat_2    feat_3  feat_4    feat_5  feat_6  feat_7  \
315     0.0     0.0  0.170162  0.000000     0.0  0.549756     0.0     0.0
316     0.0     0.0  0.230229  0.243218     0.0  0.734765     0.0     0.0
317     0.0     0.0  0.228042  0.084910     0.0  0.623091     0.0     0.0
318     0.0     0.0  0.231037  0.088723     0.0  0.626426     0.0     0.0
319     0.0     0.0  0.234886  0.198809     0.0  0.710382     0.0     0.0

       feat_8    feat_9  ...  feat_23  feat_24  feat_25  feat_26  feat_27  \
315  0.396956  0.140996  ...      0.0      0.0      0.0      0.0      0.0
316  0.175886  0.142508  ...      0.0      0.0      0.0      0.0      0.0
317  0.307121  0.107875  ...      0.0      0.0      0.0      0.0      0.0
318  0.304509  0.105822  ...      0.0      0.0      0.0      0.0      0.0
319  0.205778  0.120478  ...      0.0      0.0      0.0      0.0      0.0

      feat_28  feat_29  feat_30   feat_31  PD_Label_Combined
315  0.323843      0.0      0.0  0.000000                0.0
316  0.632057      0.0      0.0  0.074315                1.0
317  0.451678      0.0      0.0  0.000000                0.0
318  0.459916      0.0      0.0  0.000000                0.0
319  0.596242      0.0      0.0  0.046691                1.0

[5 rows x 33 columns]

In [8]:
# Make a copy to be safe (optional)
fused_df_named_int = fused_df_named.copy()

# Convert only the last column to int
fused_df_named_int['PD_Label_Combined'] = fused_df_named_int['PD_Label_Combined'].astype(int)

# Verify
print(fused_df_named_int.dtypes)
print(fused_df_named_int.head())

feat_0               float32
feat_1               float32
feat_2               float32
feat_3               float32
feat_4               float32
feat_5               float32
feat_6               float32
feat_7               float32
feat_8               float32
feat_9               float32
feat_10              float32
feat_11              float32
feat_12              float32
feat_13              float32
feat_14              float32
feat_15              float32
feat_16              float32
feat_17              float32
feat_18              float32
feat_19              float32
feat_20              float32
feat_21              float32
feat_22              float32
feat_23              float32
feat_24              float32
feat_25              float32
feat_26              float32
feat_27              float32
feat_28              float32
feat_29              float32
feat_30              float32
feat_31              float32
PD_Label_Combined      int64
dtype: object
   feat_0  feat_1    feat_2    feat_3  feat_4    feat_5  feat_6  feat_7  \
0     0.0     0.0  0.000000  0.110135     0.0  0.608933     0.0     0.0
1     0.0     0.0  0.000000  0.149674     0.0  0.614074     0.0     0.0
2     0.0     0.0  0.236298  0.000000     0.0  0.556597     0.0     0.0
3     0.0     0.0  0.000000  0.135428     0.0  0.611338     0.0     0.0
4     0.0     0.0  0.000000  0.131041     0.0  0.613933     0.0     0.0

     feat_8    feat_9  ...  feat_23  feat_24  feat_25  feat_26  feat_27  \
0  0.038362  0.279181  ...      0.0      0.0      0.0      0.0      0.0
1  0.000000  0.237277  ...      0.0      0.0      0.0      0.0      0.0
2  0.458350  0.060499  ...      0.0      0.0      0.0      0.0      0.0
3  0.117138  0.178453  ...      0.0      0.0      0.0      0.0      0.0
4  0.124046  0.190780  ...      0.0      0.0      0.0      0.0      0.0

    feat_28   feat_29  feat_30  feat_31  PD_Label_Combined
0  0.738507  0.000000      0.0      0.0                  1
1  0.867541  0.000000      0.0      0.0                  1
2  0.575536  0.138301      0.0      0.0                  0
3  0.766817  0.000000      0.0      0.0                  1
4  0.734409  0.000000      0.0      0.0                  1

[5 rows x 33 columns]

In [9]:
# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [10]:
import pandas as pd

fused_df_named_int.to_csv('/content/drive//MyDrive/Subject-level-fused_df_Vanilla_DANN_fgo_data_5-fold_cross_validation.csv', index=False)

In [1]:
# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

fused_df_named_int = pd.read_csv('/content/drive//MyDrive/Subject-level-fused_df_Vanilla_DANN_fgo_data_5-fold_cross_validation.csv')
fused_df_named_int.head()

,feat_0,feat_1,feat_2,feat_3,feat_4,feat_5,feat_6,feat_7,feat_8,feat_9,...,feat_23,feat_24,feat_25,feat_26,feat_27,feat_28,feat_29,feat_30,feat_31,PD_Label_Combined
0,0.0,0.0,0.000000,0.110135,0.0,0.608933,0.0,0.0,0.038362,0.279181,...,0.0,0.0,0.0,0.0,0.0,0.738507,0.000000,0.0,0.0,1
1,0.0,0.0,0.000000,0.149674,0.0,0.614074,0.0,0.0,0.000000,0.237277,...,0.0,0.0,0.0,0.0,0.0,0.867541,0.000000,0.0,0.0,1
2,0.0,0.0,0.236298,0.000000,0.0,0.556597,0.0,0.0,0.458350,0.060499,...,0.0,0.0,0.0,0.0,0.0,0.575536,0.138301,0.0,0.0,0
3,0.0,0.0,0.000000,0.135428,0.0,0.611338,0.0,0.0,0.117138,0.178453,...,0.0,0.0,0.0,0.0,0.0,0.766817,0.000000,0.0,0.0,1
4,0.0,0.0,0.000000,0.131041,0.0,0.613933,0.0,0.0,0.124046,0.190780,...,0.0,0.0,0.0,0.0,0.0,0.734409,0.000000,0.0,0.0,1

Evaluation

In [3]:
# ============================================================
# ###8)###
# ENSEMBLE CLASSIFICATION WITH STRATIFIED 10-FOLD CV
# ============================================================

# ------------------ Install Required Packages ------------------

!pip install xgboost lightgbm catboost scikit-learn statsmodels matplotlib seaborn --quiet


# ------------------ Imports ------------------

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.utils.class_weight import compute_class_weight

from sklearn.model_selection import (
    train_test_split,
    StratifiedKFold
)

from sklearn.preprocessing import StandardScaler

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    balanced_accuracy_score,
    matthews_corrcoef,
    confusion_matrix
)

from sklearn.ensemble import (
    VotingClassifier,
    StackingClassifier,
    RandomForestClassifier,
    HistGradientBoostingClassifier
)

from sklearn.linear_model import LogisticRegression

from xgboost import XGBClassifier

from statsmodels.stats.proportion import proportion_confint


# ============================================================
# STEP 1: PREPARE DATA
# ============================================================

X = fused_df_named_int[
    [f'feat_{i}' for i in range(32)]
].copy()

y = fused_df_named_int[
    "PD_Label_Combined"
].copy()


# ------------------ Convert X to numeric ------------------

X = X.apply(
    pd.to_numeric,
    errors='coerce'
)

X.fillna(
    0,
    inplace=True
)


# ============================================================
# STEP 2: CLASS WEIGHTS
# ============================================================

classes = np.unique(y)

class_weights = compute_class_weight(
    class_weight='balanced',
    classes=classes,
    y=y
)

class_weights_dict = {
    int(classes[0]): float(class_weights[0]),
    int(classes[1]): float(class_weights[1])
}

print("\nClass Weights:")
print(class_weights_dict)


# ============================================================
# STEP 3: TRAIN-TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=42
)


print("\nTrain Shape :", X_train.shape)
print("Test Shape  :", X_test.shape)

print("\nTraining Class Distribution:")
print(y_train.value_counts())

print("\nTesting Class Distribution:")
print(y_test.value_counts())


# ============================================================
# STEP 4: HANDLE CLASS IMBALANCE
# ============================================================

cw = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_train),
    y=y_train
)

cw_dict = dict(
    zip(
        np.unique(y_train),
        cw
    )
)

scale_pos_weight = (
    cw[1] / cw[0]
)

print("\nTraining Class Weights:")
print(cw_dict)

print(
    "\nXGBoost scale_pos_weight:",
    scale_pos_weight
)


# ============================================================
# STEP 5: BASE MODEL CREATION FUNCTION
# ============================================================

def create_models():

    # ---------------- XGBoost ----------------

    xgb = XGBClassifier(
        n_estimators=200,
        max_depth=4,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,

        scale_pos_weight=scale_pos_weight,

        eval_metric='logloss',

        random_state=42,
        n_jobs=-1
    )


    # ---------------- Random Forest ----------------

    rf = RandomForestClassifier(
        n_estimators=200,

        class_weight='balanced',

        random_state=42,
        n_jobs=-1
    )


    # ---------------- HistGradientBoosting ----------------

    hgb = HistGradientBoostingClassifier(
        max_iter=200,
        learning_rate=0.05,
        max_leaf_nodes=31,

        class_weight='balanced',

        random_state=42
    )


    return xgb, rf, hgb


# ============================================================
# STEP 6: STRATIFIED 10-FOLD CV
# ============================================================

skf = StratifiedKFold(
    n_splits=10,
    shuffle=True,
    random_state=42
)


# ============================================================
# STEP 7: EVALUATION FUNCTION
# ============================================================

def evaluate_model(model_name):

    # ========================================================
    # CV METRIC STORAGE
    # ========================================================

    cv_accuracy = []
    cv_precision = []
    cv_sensitivity = []
    cv_f1 = []
    cv_auc = []
    cv_balanced_accuracy = []


    # ========================================================
    # 10-FOLD STRATIFIED CROSS-VALIDATION
    # ========================================================

    for fold, (train_idx, val_idx) in enumerate(
        skf.split(X_train, y_train),
        start=1
    ):

        print(
            f"\n{model_name} | Fold {fold}/10"
        )


        # ----------------------------------------------------
        # Split fold
        # ----------------------------------------------------

        X_tr = X_train.iloc[
            train_idx
        ]

        X_val = X_train.iloc[
            val_idx
        ]

        y_tr = y_train.iloc[
            train_idx
        ]

        y_val = y_train.iloc[
            val_idx
        ]


        # ----------------------------------------------------
        # Scaling INSIDE EACH FOLD
        # ----------------------------------------------------

        scaler = StandardScaler()

        X_tr_scaled = scaler.fit_transform(
            X_tr
        )

        X_val_scaled = scaler.transform(
            X_val
        )


        # ----------------------------------------------------
        # Create FRESH models for every fold
        # ----------------------------------------------------

        xgb, rf, hgb = create_models()


        # ----------------------------------------------------
        # Select requested model
        # ----------------------------------------------------

        if model_name == "XGBoost":

            model = xgb


        elif model_name == "Random Forest":

            model = rf


        elif model_name == "HistGradientBoosting":

            model = hgb


        elif model_name == "Voting Fusion":

            model = VotingClassifier(
                estimators=[
                    ('xgb', xgb),
                    ('rf', rf),
                    ('hgb', hgb)
                ],
                voting='soft'
            )


        elif model_name == "Stacking Fusion":

            model = StackingClassifier(
                estimators=[
                    ('xgb', xgb),
                    ('rf', rf),
                    ('hgb', hgb)
                ],

                final_estimator=LogisticRegression(
                    max_iter=1000,
                    class_weight='balanced'
                ),

                passthrough=True,

                cv=5
            )


        else:

            raise ValueError(
                f"Unknown model: {model_name}"
            )


        # ----------------------------------------------------
        # Train fold
        # ----------------------------------------------------

        model.fit(
            X_tr_scaled,
            y_tr
        )


        # ----------------------------------------------------
        # Validation predictions
        # ----------------------------------------------------

        val_preds = model.predict(
            X_val_scaled
        )

        val_probs = model.predict_proba(
            X_val_scaled
        )[:, 1]


        # ----------------------------------------------------
        # Fold metrics
        # ----------------------------------------------------

        fold_accuracy = accuracy_score(
            y_val,
            val_preds
        )

        fold_precision = precision_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_sensitivity = recall_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_f1 = f1_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_auc = roc_auc_score(
            y_val,
            val_probs
        )

        fold_balanced_accuracy = balanced_accuracy_score(
            y_val,
            val_preds
        )


        # ----------------------------------------------------
        # Store fold metrics
        # ----------------------------------------------------

        cv_accuracy.append(
            fold_accuracy
        )

        cv_precision.append(
            fold_precision
        )

        cv_sensitivity.append(
            fold_sensitivity
        )

        cv_f1.append(
            fold_f1
        )

        cv_auc.append(
            fold_auc
        )

        cv_balanced_accuracy.append(
            fold_balanced_accuracy
        )


        # ----------------------------------------------------
        # Print fold result
        # ----------------------------------------------------

        print(
            f"Accuracy            : {fold_accuracy:.4f}"
        )

        print(
            f"Precision           : {fold_precision:.4f}"
        )

        print(
            f"Sensitivity         : {fold_sensitivity:.4f}"
        )

        print(
            f"F1 Score            : {fold_f1:.4f}"
        )

        print(
            f"ROC-AUC             : {fold_auc:.4f}"
        )

        print(
            f"Balanced Accuracy   : "
            f"{fold_balanced_accuracy:.4f}"
        )


    # ========================================================
    # CV MEAN RESULTS
    # ========================================================

    cv_accuracy_mean = np.mean(
        cv_accuracy
    )

    cv_precision_mean = np.mean(
        cv_precision
    )

    cv_sensitivity_mean = np.mean(
        cv_sensitivity
    )

    cv_f1_mean = np.mean(
        cv_f1
    )

    cv_auc_mean = np.mean(
        cv_auc
    )

    cv_balanced_accuracy_mean = np.mean(
        cv_balanced_accuracy
    )


    # ========================================================
    # CROSS-VALIDATION RESULTS
    # ========================================================

    print(
        "\n================================================"
    )

    print(
        f"{model_name} - Cross-Validation (10-fold)"
    )

    print(
        "================================================"
    )

    print(
        f"Accuracy            : "
        f"{cv_accuracy_mean:.4f}"
    )

    print(
        f"Precision           : "
        f"{cv_precision_mean:.4f}"
    )

    print(
        f"Recall/Sensitivity  : "
        f"{cv_sensitivity_mean:.4f}"
    )

    print(
        f"F1 Score            : "
        f"{cv_f1_mean:.4f}"
    )

    print(
        f"ROC-AUC             : "
        f"{cv_auc_mean:.4f}"
    )

    print(
        f"Balanced Accuracy   : "
        f"{cv_balanced_accuracy_mean:.4f}"
    )


    # ========================================================
    # TRAIN FINAL MODEL ON COMPLETE TRAINING SET
    # ========================================================

    final_scaler = StandardScaler()

    X_train_final_scaled = final_scaler.fit_transform(
        X_train
    )

    X_test_final_scaled = final_scaler.transform(
        X_test
    )


    # --------------------------------------------------------
    # Create fresh final models
    # --------------------------------------------------------

    xgb, rf, hgb = create_models()


    if model_name == "XGBoost":

        final_model = xgb


    elif model_name == "Random Forest":

        final_model = rf


    elif model_name == "HistGradientBoosting":

        final_model = hgb


    elif model_name == "Voting Fusion":

        final_model = VotingClassifier(
            estimators=[
                ('xgb', xgb),
                ('rf', rf),
                ('hgb', hgb)
            ],
            voting='soft'
        )


    elif model_name == "Stacking Fusion":

        final_model = StackingClassifier(
            estimators=[
                ('xgb', xgb),
                ('rf', rf),
                ('hgb', hgb)
            ],

            final_estimator=LogisticRegression(
                max_iter=1000,
                class_weight='balanced'
            ),

            passthrough=True,

            cv=5
        )


    # ========================================================
    # FINAL TRAINING
    # ========================================================

    final_model.fit(
        X_train_final_scaled,
        y_train
    )


    # ========================================================
    # TEST PREDICTIONS
    # ========================================================

    test_preds = final_model.predict(
        X_test_final_scaled
    )

    test_probs = final_model.predict_proba(
        X_test_final_scaled
    )[:, 1]


    # ========================================================
    # TEST METRICS
    # ========================================================

    accuracy = accuracy_score(
        y_test,
        test_preds
    )

    precision = precision_score(
        y_test,
        test_preds,
        zero_division=0
    )

    sensitivity = recall_score(
        y_test,
        test_preds,
        zero_division=0
    )

    f1 = f1_score(
        y_test,
        test_preds,
        zero_division=0
    )

    roc_auc = roc_auc_score(
        y_test,
        test_probs
    )

    balanced_accuracy = balanced_accuracy_score(
        y_test,
        test_preds
    )

    mcc = matthews_corrcoef(
        y_test,
        test_preds
    )


    # ========================================================
    # CONFUSION MATRIX
    # ========================================================

    cm = confusion_matrix(
        y_test,
        test_preds,
        labels=[0, 1]
    )

    tn, fp, fn, tp = cm.ravel()


    # ========================================================
    # SENSITIVITY / SPECIFICITY
    # ========================================================

    sensitivity = (
        tp / (tp + fn)
        if (tp + fn) > 0
        else 0
    )

    specificity = (
        tn / (tn + fp)
        if (tn + fp) > 0
        else 0
    )


    # ========================================================
    # 95% CONFIDENCE INTERVALS
    # ========================================================

    # ---------------- Accuracy CI ----------------

    acc_low, acc_high = proportion_confint(
        count=int(round(accuracy * len(y_test))),
        nobs=len(y_test),
        alpha=0.05,
        method='wilson'
    )


    # ---------------- Precision CI ----------------

    precision_low, precision_high = proportion_confint(
        count=tp,
        nobs=(tp + fp),
        alpha=0.05,
        method='wilson'
    ) if (tp + fp) > 0 else (0.0, 0.0)


    # ---------------- Sensitivity CI ----------------

    sensitivity_low, sensitivity_high = proportion_confint(
        count=tp,
        nobs=(tp + fn),
        alpha=0.05,
        method='wilson'
    ) if (tp + fn) > 0 else (0.0, 0.0)


    # ---------------- Specificity CI ----------------

    specificity_low, specificity_high = proportion_confint(
        count=tn,
        nobs=(tn + fp),
        alpha=0.05,
        method='wilson'
    ) if (tn + fp) > 0 else (0.0, 0.0)


    # ========================================================
    # TEST SET PERFORMANCE
    # ========================================================

    print(
        "\n================================================"
    )

    print(
        f"{model_name} - Test Set Performance"
    )

    print(
        "================================================"
    )

    print(
        f"Accuracy            : {accuracy:.4f} "
        f"(95% CI: "
        f"{acc_low:.4f}-{acc_high:.4f})"
    )

    print(
        f"Precision           : {precision:.4f} "
        f"(95% CI: "
        f"{precision_low:.4f}-{precision_high:.4f})"
    )

    print(
        f"Sensitivity         : {sensitivity:.4f} "
        f"(95% CI: "
        f"{sensitivity_low:.4f}-{sensitivity_high:.4f})"
    )

    print(
        f"Specificity         : {specificity:.4f} "
        f"(95% CI: "
        f"{specificity_low:.4f}-{specificity_high:.4f})"
    )

    print(
        f"F1 Score            : {f1:.4f}"
    )

    print(
        f"ROC-AUC             : {roc_auc:.4f}"
    )

    print(
        f"Balanced Accuracy   : "
        f"{balanced_accuracy:.4f}"
    )

    print(
        f"MCC                 : {mcc:.4f}"
    )


    # ========================================================
    # CONFUSION MATRIX
    # ========================================================

    print(
        "\nConfusion Matrix:"
    )

    print(cm)

    print(
        "\nTN :", tn
    )

    print(
        "FP :", fp
    )

    print(
        "FN :", fn
    )

    print(
        "TP :", tp
    )


    # ========================================================
    # STORE RESULTS
    # ========================================================

    result = {

        # ---------------- CV ----------------

        "CV Accuracy":
            cv_accuracy_mean,

        "CV Precision":
            cv_precision_mean,

        "CV Sensitivity":
            cv_sensitivity_mean,

        "CV F1":
            cv_f1_mean,

        "CV ROC-AUC":
            cv_auc_mean,

        "CV Balanced Accuracy":
            cv_balanced_accuracy_mean,


        # ---------------- Test ----------------

        "Accuracy":
            accuracy,

        "Accuracy CI Low":
            acc_low,

        "Accuracy CI High":
            acc_high,


        "Precision":
            precision,

        "Precision CI Low":
            precision_low,

        "Precision CI High":
            precision_high,


        "Sensitivity":
            sensitivity,

        "Sensitivity CI Low":
            sensitivity_low,

        "Sensitivity CI High":
            sensitivity_high,


        "Specificity":
            specificity,

        "Specificity CI Low":
            specificity_low,

        "Specificity CI High":
            specificity_high,


        "F1":
            f1,

        "ROC-AUC":
            roc_auc,

        "Balanced Accuracy":
            balanced_accuracy,

        "MCC":
            mcc,


        # ---------------- Confusion Matrix ----------------

        "TN":
            tn,

        "FP":
            fp,

        "FN":
            fn,

        "TP":
            tp
    }


    return result


# ============================================================
# STEP 8: EVALUATE ALL MODELS
# ============================================================

model_names = [
    "XGBoost",
    "Random Forest",
    "HistGradientBoosting",
    "Voting Fusion",
    "Stacking Fusion"
]


results = {}

for name in model_names:

    print(
        "\n\n################################################"
    )

    print(
        f"Evaluating: {name}"
    )

    print(
        "################################################"
    )

    results[name] = evaluate_model(
        name
    )


# ============================================================
# STEP 9: FINAL RESULTS DATAFRAME
# ============================================================

results_df = pd.DataFrame(
    results
).T


# ============================================================
# STEP 10: ORDER RESULTS
# ============================================================

results_df = results_df[
    [

        # ---------------- CV ----------------

        "CV Accuracy",
        "CV Precision",
        "CV Sensitivity",
        "CV F1",
        "CV ROC-AUC",
        "CV Balanced Accuracy",


        # ---------------- Test ----------------

        "Accuracy",
        "Accuracy CI Low",
        "Accuracy CI High",

        "Precision",
        "Precision CI Low",
        "Precision CI High",

        "Sensitivity",
        "Sensitivity CI Low",
        "Sensitivity CI High",

        "Specificity",
        "Specificity CI Low",
        "Specificity CI High",

        "F1",
        "ROC-AUC",
        "Balanced Accuracy",
        "MCC",

        # ---------------- Confusion Matrix ----------------

        "TN",
        "FP",
        "FN",
        "TP"
    ]
]


# ============================================================
# STEP 11: DISPLAY FINAL RESULTS
# ============================================================

print(
    "\n================================================"
)

print(
    "FINAL MODEL COMPARISON"
)

print(
    "================================================\n"
)


display(
    results_df.sort_values(
        by="F1",
        ascending=False
    )
)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 8.9 MB/s eta 0:00:00

Class Weights:
{0: 1.2213740458015268, 1: 0.8465608465608465}

Train Shape : (256, 32)
Test Shape  : (64, 32)

Training Class Distribution:
PD_Label_Combined
1    151
0    105
Name: count, dtype: int64

Testing Class Distribution:
PD_Label_Combined
1    38
0    26
Name: count, dtype: int64

Training Class Weights:
{np.int64(0): np.float64(1.2190476190476192), np.int64(1): np.float64(0.847682119205298)}

XGBoost scale_pos_weight: 0.6953642384105959


################################################
Evaluating: XGBoost
################################################

XGBoost | Fold 1/10
Accuracy            : 0.6538
Precision           : 0.6842
Sensitivity         : 0.8125
F1 Score            : 0.7429
ROC-AUC             : 0.8438
Balanced Accuracy   : 0.6062

XGBoost | Fold 2/10
Accuracy            : 0.6923
Precision           : 0.7059
Sensitivity         : 0.8000
F1 Score            : 0.7500
ROC-AUC             : 0.8000
Balanced Accuracy   : 0.6727

XGBoost | Fold 3/10
Accuracy            : 0.6923
Precision           : 0.7059
Sensitivity         : 0.8000
F1 Score            : 0.7500
ROC-AUC             : 0.8000
Balanced Accuracy   : 0.6727

XGBoost | Fold 4/10
Accuracy            : 0.8462
Precision           : 0.9231
Sensitivity         : 0.8000
F1 Score            : 0.8571
ROC-AUC             : 0.8970
Balanced Accuracy   : 0.8545

XGBoost | Fold 5/10
Accuracy            : 0.8462
Precision           : 0.9231
Sensitivity         : 0.8000
F1 Score            : 0.8571
ROC-AUC             : 0.8788
Balanced Accuracy   : 0.8545

XGBoost | Fold 6/10
Accuracy            : 0.7308
Precision           : 1.0000
Sensitivity         : 0.5333
F1 Score            : 0.6957
ROC-AUC             : 0.8909
Balanced Accuracy   : 0.7667

XGBoost | Fold 7/10
Accuracy            : 0.7200
Precision           : 0.8333
Sensitivity         : 0.6667
F1 Score            : 0.7407
ROC-AUC             : 0.8633
Balanced Accuracy   : 0.7333

XGBoost | Fold 8/10
Accuracy            : 0.7600
Precision           : 0.8000
Sensitivity         : 0.8000
F1 Score            : 0.8000
ROC-AUC             : 0.8400
Balanced Accuracy   : 0.7500

XGBoost | Fold 9/10
Accuracy            : 0.7600
Precision           : 0.8462
Sensitivity         : 0.7333
F1 Score            : 0.7857
ROC-AUC             : 0.8667
Balanced Accuracy   : 0.7667

XGBoost | Fold 10/10
Accuracy            : 0.8000
Precision           : 0.8571
Sensitivity         : 0.8000
F1 Score            : 0.8276
ROC-AUC             : 0.8600
Balanced Accuracy   : 0.8000

================================================
XGBoost - Cross-Validation (10-fold)
================================================
Accuracy            : 0.7502
Precision           : 0.8279
Recall/Sensitivity  : 0.7546
F1 Score            : 0.7807
ROC-AUC             : 0.8540
Balanced Accuracy   : 0.7477

================================================
XGBoost - Test Set Performance
================================================
Accuracy            : 0.6875 (95% CI: 0.5661-0.7877)
Precision           : 0.7500 (95% CI: 0.5893-0.8625)
Sensitivity         : 0.7105 (95% CI: 0.5524-0.8300)
Specificity         : 0.6538 (95% CI: 0.4622-0.8059)
F1 Score            : 0.7297
ROC-AUC             : 0.7571
Balanced Accuracy   : 0.6822
MCC                 : 0.3607

Confusion Matrix:
[[17  9]
 [11 27]]

TN : 17
FP : 9
FN : 11
TP : 27


################################################
Evaluating: Random Forest
################################################

Random Forest | Fold 1/10
Accuracy            : 0.6154
Precision           : 0.6364
Sensitivity         : 0.8750
F1 Score            : 0.7368
ROC-AUC             : 0.8250
Balanced Accuracy   : 0.5375

Random Forest | Fold 2/10
Accuracy            : 0.6923
Precision           : 0.7059
Sensitivity         : 0.8000
F1 Score            : 0.7500
ROC-AUC             : 0.8273
Balanced Accuracy   : 0.6727

Random Forest | Fold 3/10
Accuracy            : 0.6538
Precision           : 0.6667
Sensitivity         : 0.8000
F1 Score            : 0.7273
ROC-AUC             : 0.8606
Balanced Accuracy   : 0.6273

Random Forest | Fold 4/10
Accuracy            : 0.8077
Precision           : 0.8571
Sensitivity         : 0.8000
F1 Score            : 0.8276
ROC-AUC             : 0.8364
Balanced Accuracy   : 0.8091

Random Forest | Fold 5/10
Accuracy            : 0.7692
Precision           : 0.8000
Sensitivity         : 0.8000
F1 Score            : 0.8000
ROC-AUC             : 0.8788
Balanced Accuracy   : 0.7636

Random Forest | Fold 6/10
Accuracy            : 0.7308
Precision           : 1.0000
Sensitivity         : 0.5333
F1 Score            : 0.6957
ROC-AUC             : 0.8727
Balanced Accuracy   : 0.7667

Random Forest | Fold 7/10
Accuracy            : 0.7200
Precision           : 0.7500
Sensitivity         : 0.8000
F1 Score            : 0.7742
ROC-AUC             : 0.8400
Balanced Accuracy   : 0.7000

Random Forest | Fold 8/10
Accuracy            : 0.7600
Precision           : 0.8000
Sensitivity         : 0.8000
F1 Score            : 0.8000
ROC-AUC             : 0.8467
Balanced Accuracy   : 0.7500

Random Forest | Fold 9/10
Accuracy            : 0.8000
Precision           : 0.8571
Sensitivity         : 0.8000
F1 Score            : 0.8276
ROC-AUC             : 0.7933
Balanced Accuracy   : 0.8000

Random Forest | Fold 10/10
Accuracy            : 0.7600
Precision           : 0.8462
Sensitivity         : 0.7333
F1 Score            : 0.7857
ROC-AUC             : 0.8567
Balanced Accuracy   : 0.7667

================================================
Random Forest - Cross-Validation (10-fold)
================================================
Accuracy            : 0.7309
Precision           : 0.7919
Recall/Sensitivity  : 0.7742
F1 Score            : 0.7725
ROC-AUC             : 0.8437
Balanced Accuracy   : 0.7194

================================================
Random Forest - Test Set Performance
================================================
Accuracy            : 0.6406 (95% CI: 0.5182-0.7471)
Precision           : 0.6923 (95% CI: 0.5358-0.8143)
Sensitivity         : 0.7105 (95% CI: 0.5524-0.8300)
Specificity         : 0.5385 (95% CI: 0.3546-0.7124)
F1 Score            : 0.7013
ROC-AUC             : 0.7287
Balanced Accuracy   : 0.6245
MCC                 : 0.2506

Confusion Matrix:
[[14 12]
 [11 27]]

TN : 14
FP : 12
FN : 11
TP : 27


################################################
Evaluating: HistGradientBoosting
################################################

HistGradientBoosting | Fold 1/10
Accuracy            : 0.6923
Precision           : 0.7222
Sensitivity         : 0.8125
F1 Score            : 0.7647
ROC-AUC             : 0.8063
Balanced Accuracy   : 0.6562

HistGradientBoosting | Fold 2/10
Accuracy            : 0.6538
Precision           : 0.6667
Sensitivity         : 0.8000
F1 Score            : 0.7273
ROC-AUC             : 0.7909
Balanced Accuracy   : 0.6273

HistGradientBoosting | Fold 3/10
Accuracy            : 0.7692
Precision           : 0.7647
Sensitivity         : 0.8667
F1 Score            : 0.8125
ROC-AUC             : 0.8061
Balanced Accuracy   : 0.7515

HistGradientBoosting | Fold 4/10
Accuracy            : 0.8077
Precision           : 0.9167
Sensitivity         : 0.7333
F1 Score            : 0.8148
ROC-AUC             : 0.8848
Balanced Accuracy   : 0.8212

HistGradientBoosting | Fold 5/10
Accuracy            : 0.8077
Precision           : 0.9167
Sensitivity         : 0.7333
F1 Score            : 0.8148
ROC-AUC             : 0.8364
Balanced Accuracy   : 0.8212

HistGradientBoosting | Fold 6/10
Accuracy            : 0.7308
Precision           : 1.0000
Sensitivity         : 0.5333
F1 Score            : 0.6957
ROC-AUC             : 0.8545
Balanced Accuracy   : 0.7667

HistGradientBoosting | Fold 7/10
Accuracy            : 0.8000
Precision           : 0.9167
Sensitivity         : 0.7333
F1 Score            : 0.8148
ROC-AUC             : 0.8433
Balanced Accuracy   : 0.8167

HistGradientBoosting | Fold 8/10
Accuracy            : 0.7200
Precision           : 0.7500
Sensitivity         : 0.8000
F1 Score            : 0.7742
ROC-AUC             : 0.8333
Balanced Accuracy   : 0.7000

HistGradientBoosting | Fold 9/10
Accuracy            : 0.7200
Precision           : 0.8333
Sensitivity         : 0.6667
F1 Score            : 0.7407
ROC-AUC             : 0.8733
Balanced Accuracy   : 0.7333

HistGradientBoosting | Fold 10/10
Accuracy            : 0.7600
Precision           : 0.8462
Sensitivity         : 0.7333
F1 Score            : 0.7857
ROC-AUC             : 0.8467
Balanced Accuracy   : 0.7667

================================================
HistGradientBoosting - Cross-Validation (10-fold)
================================================
Accuracy            : 0.7462
Precision           : 0.8333
Recall/Sensitivity  : 0.7413
F1 Score            : 0.7745
ROC-AUC             : 0.8376
Balanced Accuracy   : 0.7461

================================================
HistGradientBoosting - Test Set Performance
================================================
Accuracy            : 0.6406 (95% CI: 0.5182-0.7471)
Precision           : 0.7273 (95% CI: 0.5578-0.8493)
Sensitivity         : 0.6316 (95% CI: 0.4728-0.7662)
Specificity         : 0.6538 (95% CI: 0.4622-0.8059)
F1 Score            : 0.6761
ROC-AUC             : 0.7156
Balanced Accuracy   : 0.6427
MCC                 : 0.2805

Confusion Matrix:
[[17  9]
 [14 24]]

TN : 17
FP : 9
FN : 14
TP : 24


################################################
Evaluating: Voting Fusion
################################################

Voting Fusion | Fold 1/10
Accuracy            : 0.6923
Precision           : 0.7222
Sensitivity         : 0.8125
F1 Score            : 0.7647
ROC-AUC             : 0.8188
Balanced Accuracy   : 0.6562

Voting Fusion | Fold 2/10
Accuracy            : 0.7308
Precision           : 0.7500
Sensitivity         : 0.8000
F1 Score            : 0.7742
ROC-AUC             : 0.7818
Balanced Accuracy   : 0.7182

Voting Fusion | Fold 3/10
Accuracy            : 0.6923
Precision           : 0.7059
Sensitivity         : 0.8000
F1 Score            : 0.7500
ROC-AUC             : 0.8364
Balanced Accuracy   : 0.6727

Voting Fusion | Fold 4/10
Accuracy            : 0.8462
Precision           : 0.9231
Sensitivity         : 0.8000
F1 Score            : 0.8571
ROC-AUC             : 0.8909
Balanced Accuracy   : 0.8545

Voting Fusion | Fold 5/10
Accuracy            : 0.8077
Precision           : 0.8571
Sensitivity         : 0.8000
F1 Score            : 0.8276
ROC-AUC             : 0.8909
Balanced Accuracy   : 0.8091

Voting Fusion | Fold 6/10
Accuracy            : 0.7308
Precision           : 1.0000
Sensitivity         : 0.5333
F1 Score            : 0.6957
ROC-AUC             : 0.8545
Balanced Accuracy   : 0.7667

Voting Fusion | Fold 7/10
Accuracy            : 0.7600
Precision           : 0.8462
Sensitivity         : 0.7333
F1 Score            : 0.7857
ROC-AUC             : 0.8767
Balanced Accuracy   : 0.7667

Voting Fusion | Fold 8/10
Accuracy            : 0.7600
Precision           : 0.8000
Sensitivity         : 0.8000
F1 Score            : 0.8000
ROC-AUC             : 0.8400
Balanced Accuracy   : 0.7500

Voting Fusion | Fold 9/10
Accuracy            : 0.7600
Precision           : 0.8462
Sensitivity         : 0.7333
F1 Score            : 0.7857
ROC-AUC             : 0.8467
Balanced Accuracy   : 0.7667

Voting Fusion | Fold 10/10
Accuracy            : 0.7600
Precision           : 0.8462
Sensitivity         : 0.7333
F1 Score            : 0.7857
ROC-AUC             : 0.8600
Balanced Accuracy   : 0.7667

================================================
Voting Fusion - Cross-Validation (10-fold)
================================================
Accuracy            : 0.7540
Precision           : 0.8297
Recall/Sensitivity  : 0.7546
F1 Score            : 0.7826
ROC-AUC             : 0.8497
Balanced Accuracy   : 0.7527

================================================
Voting Fusion - Test Set Performance
================================================
Accuracy            : 0.6250 (95% CI: 0.5025-0.7333)
Precision           : 0.6944 (95% CI: 0.5314-0.8200)
Sensitivity         : 0.6579 (95% CI: 0.4989-0.7879)
Specificity         : 0.5769 (95% CI: 0.3895-0.7446)
F1 Score            : 0.6757
ROC-AUC             : 0.7429
Balanced Accuracy   : 0.6174
MCC                 : 0.2325

Confusion Matrix:
[[15 11]
 [13 25]]

TN : 15
FP : 11
FN : 13
TP : 25


################################################
Evaluating: Stacking Fusion
################################################

Stacking Fusion | Fold 1/10
Accuracy            : 0.7308
Precision           : 0.8000
Sensitivity         : 0.7500
F1 Score            : 0.7742
ROC-AUC             : 0.8125
Balanced Accuracy   : 0.7250

Stacking Fusion | Fold 2/10
Accuracy            : 0.7308
Precision           : 0.7857
Sensitivity         : 0.7333
F1 Score            : 0.7586
ROC-AUC             : 0.8364
Balanced Accuracy   : 0.7303

Stacking Fusion | Fold 3/10
Accuracy            : 0.6923
Precision           : 0.8182
Sensitivity         : 0.6000
F1 Score            : 0.6923
ROC-AUC             : 0.8788
Balanced Accuracy   : 0.7091

Stacking Fusion | Fold 4/10
Accuracy            : 0.6923
Precision           : 0.8889
Sensitivity         : 0.5333
F1 Score            : 0.6667
ROC-AUC             : 0.8242
Balanced Accuracy   : 0.7212

Stacking Fusion | Fold 5/10
Accuracy            : 0.8077
Precision           : 1.0000
Sensitivity         : 0.6667
F1 Score            : 0.8000
ROC-AUC             : 0.8848
Balanced Accuracy   : 0.8333

Stacking Fusion | Fold 6/10
Accuracy            : 0.6538
Precision           : 0.8750
Sensitivity         : 0.4667
F1 Score            : 0.6087
ROC-AUC             : 0.8727
Balanced Accuracy   : 0.6879

Stacking Fusion | Fold 7/10
Accuracy            : 0.7600
Precision           : 0.8000
Sensitivity         : 0.8000
F1 Score            : 0.8000
ROC-AUC             : 0.8900
Balanced Accuracy   : 0.7500

Stacking Fusion | Fold 8/10
Accuracy            : 0.7600
Precision           : 1.0000
Sensitivity         : 0.6000
F1 Score            : 0.7500
ROC-AUC             : 0.9133
Balanced Accuracy   : 0.8000

Stacking Fusion | Fold 9/10
Accuracy            : 0.8000
Precision           : 0.8571
Sensitivity         : 0.8000
F1 Score            : 0.8276
ROC-AUC             : 0.8933
Balanced Accuracy   : 0.8000

Stacking Fusion | Fold 10/10
Accuracy            : 0.7200
Precision           : 0.9000
Sensitivity         : 0.6000
F1 Score            : 0.7200
ROC-AUC             : 0.9000
Balanced Accuracy   : 0.7500

================================================
Stacking Fusion - Cross-Validation (10-fold)
================================================
Accuracy            : 0.7348
Precision           : 0.8725
Recall/Sensitivity  : 0.6550
F1 Score            : 0.7398
ROC-AUC             : 0.8706
Balanced Accuracy   : 0.7507

================================================
Stacking Fusion - Test Set Performance
================================================
Accuracy            : 0.7031 (95% CI: 0.5823-0.8009)
Precision           : 0.7714 (95% CI: 0.6098-0.8793)
Sensitivity         : 0.7105 (95% CI: 0.5524-0.8300)
Specificity         : 0.6923 (95% CI: 0.5001-0.8350)
F1 Score            : 0.7397
ROC-AUC             : 0.7966
Balanced Accuracy   : 0.7014
MCC                 : 0.3974

Confusion Matrix:
[[18  8]
 [11 27]]

TN : 18
FP : 8
FN : 11
TP : 27

================================================
FINAL MODEL COMPARISON
================================================

,CV Accuracy,CV Precision,CV Sensitivity,CV F1,CV ROC-AUC,CV Balanced Accuracy,Accuracy,Accuracy CI Low,Accuracy CI High,Precision,...,Specificity CI Low,Specificity CI High,F1,ROC-AUC,Balanced Accuracy,MCC,TN,FP,FN,TP
Stacking Fusion,0.734769,0.872493,0.655000,0.739807,0.870614,0.750682,0.703125,0.582298,0.800948,0.771429,...,0.500117,0.834987,0.739726,0.796559,0.701417,0.397440,18.0,8.0,11.0,27.0
XGBoost,0.750154,0.827876,0.754583,0.780684,0.854042,0.747746,0.687500,0.566077,0.787689,0.750000,...,0.462206,0.805878,0.729730,0.757085,0.682186,0.360740,17.0,9.0,11.0,27.0
Random Forest,0.730923,0.791935,0.774167,0.772485,0.843742,0.719356,0.640625,0.518209,0.747116,0.692308,...,0.354579,0.712441,0.701299,0.728745,0.624494,0.250642,14.0,12.0,11.0,27.0
HistGradientBoosting,0.746154,0.833308,0.741250,0.774522,0.837564,0.746080,0.640625,0.518209,0.747116,0.727273,...,0.462206,0.805878,0.676056,0.715587,0.642713,0.280500,17.0,9.0,14.0,24.0
Voting Fusion,0.754000,0.829679,0.754583,0.782642,0.849663,0.752746,0.625000,0.502504,0.733340,0.694444,...,0.389486,0.744556,0.675676,0.742915,0.617409,0.232477,15.0,11.0,13.0,25.0

Baseline SCL

In [1]:
# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

df_acoustic_top7 = pd.read_csv('/content/drive/MyDrive/Acoustic-subject-level-dataset_top7.csv')
df_acoustic_top7 = df_acoustic_top7.drop(columns=['Participant_ID'])
print(df_acoustic_top7.shape)
print(df_acoustic_top7.head())

(193, 8)
       RPDE  Degree-voice breaks  Delta2  Delta3  Delta11  MFCC5   spread1  \
0  0.428488                  0.0     0.0     0.0      0.0    0.0 -4.239926
1  0.542488                  0.0     0.0     0.0      0.0    0.0 -4.519291
2  0.332247                  0.0     0.0     0.0      0.0    0.0 -7.226125
3  0.498593                  0.0     0.0     0.0      0.0    0.0 -5.632290
4  0.470775                  0.0     0.0     0.0      0.0    0.0 -5.523149

   Status
0       1
1       1
2       0
3       1
4       1

In [3]:
import pandas as pd

final_meg_df = pd.read_csv('/content/drive/MyDrive/final_meg-go(par)_top7_rfc+shap_10-fold_analysis_last_column.csv')

print("Loaded data shape:", final_meg_df.shape)
print(final_meg_df.head())

Loaded data shape: (127, 8)
   env_kurt_R_mean  env_kurt_R_std  env_kurt_L_mean  env_kurt_L_std  \
0         5.749049       15.894836         5.962378       17.165772
1         4.459546        7.184608         4.390848        6.578943
2         1.161476        0.718562         1.885349        1.714298
3         1.138575        0.699601         1.365950        0.817770
4     18283.789736     4480.567058     18277.357293     4487.602704

   burst_dur_cv_L_std  env_mod_rate_L_std  env_skew_L_mean  PD_Label_Combined
0        4.938551e-02            0.244843         1.123760                  0
1        1.147524e-01            0.117228         1.400286                  0
2        5.040195e-02            0.275503         0.953293                  0
3        4.311462e-02            0.460356         0.920828                  1
4        1.043683e-16            0.064449       129.243639                  1

In [4]:
# ============================================================
#           BASELINE SUPERVISED CONTRASTIVE LEARNING
#        (BASIC SCL BASELINE + 5-FOLD CROSS VALIDATION)
# ============================================================

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

import torch.nn.functional as F
import numpy as np

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# ============================================================
# LOAD DATA
# ============================================================

sc = StandardScaler()

# Acoustic
X_acoustic = sc.fit_transform(
    df_acoustic_top7.iloc[:, :-1]
).astype(np.float32)

# MEG
X_meg = sc.fit_transform(
    final_meg_df.iloc[:, :-1]
).astype(np.float32)

# LABELS

acoustic_labels = df_acoustic_top7.iloc[:, -1].values.astype(np.int64)

meg_labels = final_meg_df.iloc[:, -1].values.astype(np.int64)

# ============================================================
# COMBINE MODALITIES
# ============================================================

X_all = np.vstack([
    X_acoustic,
    X_meg
]).astype(np.float32)

task_labels = np.hstack([
    acoustic_labels,
    meg_labels
]).astype(np.int64)

# ============================================================
# TENSORS
# ============================================================

X_all_tensor = torch.tensor(
    X_all
).float().to(device)

task_labels_tensor = torch.tensor(
    task_labels
).long().to(device)

# ============================================================
# SIMPLE SCL MODEL
# ============================================================

class BasicSCLModel(nn.Module):

    def __init__(self, input_dim, latent_dim=32):

        super().__init__()

        # SIMPLE ENCODER

        self.encoder = nn.Sequential(

            nn.Linear(input_dim, 64),
            nn.ReLU(),

            nn.Linear(64, latent_dim)
        )

        # SIMPLE TASK HEAD

        self.task_head = nn.Sequential(

            nn.Linear(latent_dim, 16),
            nn.ReLU(),

            nn.Linear(16, 2)
        )

    def forward(self, x):

        # LATENT FEATURES

        z = self.encoder(x)

        # NORMALIZATION

        z_norm = F.normalize(
            z,
            p=2,
            dim=1
        )

        # CLASSIFICATION

        task_out = self.task_head(z_norm)

        return task_out, z_norm

# ============================================================
# BASIC SUPERVISED CONTRASTIVE LOSS
# ============================================================

class SupConLoss(nn.Module):

    def __init__(self, temperature=0.1):

        super().__init__()

        self.temperature = temperature

    def forward(self, features, labels):

        device = features.device

        labels = labels.contiguous().view(-1, 1)

        mask = torch.eq(
            labels,
            labels.T
        ).float().to(device)

        similarity = torch.matmul(
            features,
            features.T
        ) / self.temperature

        logits_mask = torch.ones_like(mask) - torch.eye(
            mask.shape[0]
        ).to(device)

        mask = mask * logits_mask

        exp_sim = torch.exp(similarity) * logits_mask

        log_prob = similarity - torch.log(
            exp_sim.sum(1, keepdim=True) + 1e-8
        )

        mean_log_prob_pos = (
            mask * log_prob
        ).sum(1) / (mask.sum(1) + 1e-8)

        loss = -mean_log_prob_pos.mean()

        return loss

# ============================================================
# DATA LOADER
# ============================================================

dataset = TensorDataset(
    X_all_tensor,
    task_labels_tensor
)

loader = DataLoader(
    dataset,
    batch_size=128,
    shuffle=True
)

# ============================================================
# MODEL
# ============================================================

model = BasicSCLModel(
    input_dim=X_all.shape[1],
    latent_dim=32
).to(device)

# ============================================================
# OPTIMIZER
# ============================================================

optimizer = optim.Adam(
    model.parameters(),
    lr=1e-3
)

# ============================================================
# LOSSES
# ============================================================

task_loss_fn = nn.CrossEntropyLoss()

contrastive_loss_fn = SupConLoss(
    temperature=0.1
)

epochs = 120

print("\nTraining Started...\n")

# ============================================================
# TRAINING
# ============================================================

for epoch in range(epochs):

    model.train()

    total_correct = 0
    total_samples = 0

    for xb, y_task in loader:

        optimizer.zero_grad()

        # FORWARD

        task_out, z = model(xb)

        # TASK LOSS

        loss_task = task_loss_fn(
            task_out,
            y_task
        )

        # CONTRASTIVE LOSS

        loss_contrastive = contrastive_loss_fn(
            z,
            y_task
        )

        # FINAL LOSS

        loss = (
            1.0 * loss_task +
            0.3 * loss_contrastive
        )

        loss.backward()

        optimizer.step()

        # ACCURACY

        preds = task_out.argmax(1)

        total_correct += (
            preds == y_task
        ).sum().item()

        total_samples += len(y_task)

    acc = total_correct / total_samples

    print(
        f"Epoch {epoch+1}/{epochs} "
        f"| Accuracy={acc:.4f}"
    )

# ============================================================
# EXTRACT 32D LATENT FEATURES
# ============================================================

model.eval()

with torch.no_grad():

    fused_acoustic_32D = model(
        torch.tensor(X_acoustic).float().to(device)
    )[1].cpu().numpy()

    fused_meg_32D = model(
        torch.tensor(X_meg).float().to(device)
    )[1].cpu().numpy()

# ============================================================
# COMBINE LATENT FEATURES
# ============================================================

combined_32D = np.vstack([
    fused_acoustic_32D,
    fused_meg_32D
]).astype(np.float32)

combined_labels = np.hstack([
    acoustic_labels,
    meg_labels
]).astype(np.int64)

# ============================================================
# FINAL MLP CLASSIFIER
# ============================================================

class FinalMLP(nn.Module):

    def __init__(self, input_dim=32):

        super().__init__()

        self.net = nn.Sequential(

            nn.Linear(input_dim, 64),
            nn.ReLU(),

            nn.Dropout(0.2),

            nn.Linear(64, 32),
            nn.ReLU(),

            nn.Linear(32, 2)
        )

    def forward(self, x):

        return self.net(x)

# ============================================================
# 5-FOLD CROSS VALIDATION
# ============================================================

print("\n======================================")
print(" CROSS VALIDATION RESULTS")
print("======================================\n")

skf = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

accs = []
precs = []
recs = []
f1s = []
aucs = []

fold = 1

for train_idx, test_idx in skf.split(combined_32D, combined_labels):

    X_train = torch.tensor(
        combined_32D[train_idx]
    ).float().to(device)

    X_test = torch.tensor(
        combined_32D[test_idx]
    ).float().to(device)

    y_train = torch.tensor(
        combined_labels[train_idx]
    ).long().to(device)

    y_test = combined_labels[test_idx]

    clf = FinalMLP().to(device)

    optimizer_clf = optim.Adam(
        clf.parameters(),
        lr=1e-3
    )

    criterion = nn.CrossEntropyLoss()

    # ========================================================
    # TRAIN CLASSIFIER
    # ========================================================

    clf.train()

    for epoch in range(80):

        optimizer_clf.zero_grad()

        outputs = clf(X_train)

        loss = criterion(
            outputs,
            y_train
        )

        loss.backward()

        optimizer_clf.step()

    # ========================================================
    # TEST
    # ========================================================

    clf.eval()

    with torch.no_grad():

        outputs = clf(X_test)

        probs = F.softmax(
            outputs,
            dim=1
        )[:, 1].cpu().numpy()

        preds = outputs.argmax(1).cpu().numpy()

    acc = accuracy_score(y_test, preds)

    prec = precision_score(y_test, preds)

    rec = recall_score(y_test, preds)

    f1 = f1_score(y_test, preds)

    auc = roc_auc_score(y_test, probs)

    accs.append(acc)
    precs.append(prec)
    recs.append(rec)
    f1s.append(f1)
    aucs.append(auc)

    print(f"Fold {fold}")

    print(f"Accuracy  : {acc:.4f}")
    print(f"Precision : {prec:.4f}")
    print(f"Recall    : {rec:.4f}")
    print(f"F1-Score  : {f1:.4f}")
    print(f"AUC       : {auc:.4f}")

    print()

    fold += 1

# ============================================================
# FINAL RESULTS
# ============================================================

print("\n======================================")
print(" FINAL RESULTS")
print("======================================\n")

print(f"Mean Accuracy  : {np.mean(accs)*100:.2f}%")
print(f"Mean Precision : {np.mean(precs)*100:.2f}%")
print(f"Mean Recall    : {np.mean(recs)*100:.2f}%")
print(f"Mean F1-Score  : {np.mean(f1s)*100:.2f}%")
print(f"Mean AUC       : {np.mean(aucs)*100:.2f}%")

# ============================================================
# FINAL RESULTS
# ============================================================

print("\n========== LATENT FEATURE SHAPES ==========\n")

print("Acoustic 32D :", fused_acoustic_32D.shape)

print("MEG 32D      :", fused_meg_32D.shape)

print("Combined 32D :", combined_32D.shape)

print("Labels Shape :", combined_labels.shape)

Training Started...

Epoch 1/120 | Accuracy=0.5906
Epoch 2/120 | Accuracy=0.5906
Epoch 3/120 | Accuracy=0.5906
Epoch 4/120 | Accuracy=0.5906
Epoch 5/120 | Accuracy=0.5906
Epoch 6/120 | Accuracy=0.5906
Epoch 7/120 | Accuracy=0.5906
Epoch 8/120 | Accuracy=0.5906
Epoch 9/120 | Accuracy=0.5906
Epoch 10/120 | Accuracy=0.5906
Epoch 11/120 | Accuracy=0.5906
Epoch 12/120 | Accuracy=0.5906
Epoch 13/120 | Accuracy=0.5906
Epoch 14/120 | Accuracy=0.5906
Epoch 15/120 | Accuracy=0.5906
Epoch 16/120 | Accuracy=0.5906
Epoch 17/120 | Accuracy=0.5906
Epoch 18/120 | Accuracy=0.5906
Epoch 19/120 | Accuracy=0.5906
Epoch 20/120 | Accuracy=0.5906
Epoch 21/120 | Accuracy=0.5906
Epoch 22/120 | Accuracy=0.5906
Epoch 23/120 | Accuracy=0.5906
Epoch 24/120 | Accuracy=0.5906
Epoch 25/120 | Accuracy=0.5906
Epoch 26/120 | Accuracy=0.5906
Epoch 27/120 | Accuracy=0.5906
Epoch 28/120 | Accuracy=0.5906
Epoch 29/120 | Accuracy=0.5906
Epoch 30/120 | Accuracy=0.5906
Epoch 31/120 | Accuracy=0.6031
Epoch 32/120 | Accuracy=0.6031
Epoch 33/120 | Accuracy=0.6156
Epoch 34/120 | Accuracy=0.6156
Epoch 35/120 | Accuracy=0.6406
Epoch 36/120 | Accuracy=0.6562
Epoch 37/120 | Accuracy=0.6906
Epoch 38/120 | Accuracy=0.7125
Epoch 39/120 | Accuracy=0.7125
Epoch 40/120 | Accuracy=0.7188
Epoch 41/120 | Accuracy=0.7281
Epoch 42/120 | Accuracy=0.7344
Epoch 43/120 | Accuracy=0.7531
Epoch 44/120 | Accuracy=0.7531
Epoch 45/120 | Accuracy=0.7438
Epoch 46/120 | Accuracy=0.7406
Epoch 47/120 | Accuracy=0.7469
Epoch 48/120 | Accuracy=0.7406
Epoch 49/120 | Accuracy=0.7406
Epoch 50/120 | Accuracy=0.7469
Epoch 51/120 | Accuracy=0.7531
Epoch 52/120 | Accuracy=0.7406
Epoch 53/120 | Accuracy=0.7438
Epoch 54/120 | Accuracy=0.7438
Epoch 55/120 | Accuracy=0.7375
Epoch 56/120 | Accuracy=0.7312
Epoch 57/120 | Accuracy=0.7375
Epoch 58/120 | Accuracy=0.7438
Epoch 59/120 | Accuracy=0.7531
Epoch 60/120 | Accuracy=0.7562
Epoch 61/120 | Accuracy=0.7375
Epoch 62/120 | Accuracy=0.7469
Epoch 63/120 | Accuracy=0.7531
Epoch 64/120 | Accuracy=0.7531
Epoch 65/120 | Accuracy=0.7406
Epoch 66/120 | Accuracy=0.7438
Epoch 67/120 | Accuracy=0.7406
Epoch 68/120 | Accuracy=0.7469
Epoch 69/120 | Accuracy=0.7406
Epoch 70/120 | Accuracy=0.7406
Epoch 71/120 | Accuracy=0.7438
Epoch 72/120 | Accuracy=0.7438
Epoch 73/120 | Accuracy=0.7500
Epoch 74/120 | Accuracy=0.7562
Epoch 75/120 | Accuracy=0.7500
Epoch 76/120 | Accuracy=0.7344
Epoch 77/120 | Accuracy=0.7469
Epoch 78/120 | Accuracy=0.7438
Epoch 79/120 | Accuracy=0.7375
Epoch 80/120 | Accuracy=0.7531
Epoch 81/120 | Accuracy=0.7469
Epoch 82/120 | Accuracy=0.7469
Epoch 83/120 | Accuracy=0.7344
Epoch 84/120 | Accuracy=0.7438
Epoch 85/120 | Accuracy=0.7375
Epoch 86/120 | Accuracy=0.7531
Epoch 87/120 | Accuracy=0.7656
Epoch 88/120 | Accuracy=0.7562
Epoch 89/120 | Accuracy=0.7438
Epoch 90/120 | Accuracy=0.7406
Epoch 91/120 | Accuracy=0.7438
Epoch 92/120 | Accuracy=0.7500
Epoch 93/120 | Accuracy=0.7531
Epoch 94/120 | Accuracy=0.7531
Epoch 95/120 | Accuracy=0.7469
Epoch 96/120 | Accuracy=0.7438
Epoch 97/120 | Accuracy=0.7469
Epoch 98/120 | Accuracy=0.7500
Epoch 99/120 | Accuracy=0.7438
Epoch 100/120 | Accuracy=0.7375
Epoch 101/120 | Accuracy=0.7406
Epoch 102/120 | Accuracy=0.7469
Epoch 103/120 | Accuracy=0.7531
Epoch 104/120 | Accuracy=0.7531
Epoch 105/120 | Accuracy=0.7469
Epoch 106/120 | Accuracy=0.7406
Epoch 107/120 | Accuracy=0.7500
Epoch 108/120 | Accuracy=0.7562
Epoch 109/120 | Accuracy=0.7469
Epoch 110/120 | Accuracy=0.7469
Epoch 111/120 | Accuracy=0.7531
Epoch 112/120 | Accuracy=0.7625
Epoch 113/120 | Accuracy=0.7562
Epoch 114/120 | Accuracy=0.7531
Epoch 115/120 | Accuracy=0.7469
Epoch 116/120 | Accuracy=0.7531
Epoch 117/120 | Accuracy=0.7469
Epoch 118/120 | Accuracy=0.7469
Epoch 119/120 | Accuracy=0.7406
Epoch 120/120 | Accuracy=0.7469

======================================
 CROSS VALIDATION RESULTS
======================================

Fold 1
Accuracy  : 0.7656
Precision : 0.8286
Recall    : 0.7632
F1-Score  : 0.7945
AUC       : 0.8168

Fold 2
Accuracy  : 0.6719
Precision : 0.7297
Recall    : 0.7105
F1-Score  : 0.7200
AUC       : 0.8350

Fold 3
Accuracy  : 0.7656
Precision : 0.8485
Recall    : 0.7368
F1-Score  : 0.7887
AUC       : 0.9226

Fold 4
Accuracy  : 0.7969
Precision : 0.8571
Recall    : 0.7895
F1-Score  : 0.8219
AUC       : 0.9221

Fold 5
Accuracy  : 0.7344
Precision : 0.8571
Recall    : 0.6486
F1-Score  : 0.7385
AUC       : 0.7948


======================================
 FINAL RESULTS
======================================

Mean Accuracy  : 74.69%
Mean Precision : 82.42%
Mean Recall    : 72.97%
Mean F1-Score  : 77.27%
Mean AUC       : 85.83%

========== LATENT FEATURE SHAPES ==========

Acoustic 32D : (193, 32)
MEG 32D      : (127, 32)
Combined 32D : (320, 32)
Labels Shape : (320,)

In [5]:
import torch

# Assuming fused_acoustic_32D and fused_meg_32D are numpy arrays of shape (7350, 32)

# Step 1: Convert numpy arrays to torch tensors (float32)
fused_acoustic_tensor = torch.from_numpy(fused_acoustic_32D).float()
fused_meg_tensor = torch.from_numpy(fused_meg_32D).float()

# Step 2: Concatenate row-wise (along dim=0)
fused_output_tensor = torch.cat([fused_acoustic_tensor, fused_meg_tensor], dim=0)  # Shape: (14700, 32)

# Step 3: Print shape and dtype
print(fused_output_tensor.shape)  # torch.Size([14700, 32])
print(fused_output_tensor.dtype)  # torch.float32

torch.Size([320, 32])
torch.float32

In [6]:
import torch
import numpy as np

# ------------------------
# Step 1: Extract targets correctly
# ------------------------

# Acoustic target from df_acoustic_top7 (last column)
y_acoustic = df_acoustic_top7.iloc[:, -1].values.astype(np.int32)   # (7350,)

# MEG target from final_meg_df (last column)
y_meg = final_meg_df.iloc[:, -1].values.astype(np.int32)           # (7350,)

# Convert to tensors (reshape to column)
acoustic_target_tensor = torch.tensor(y_acoustic).long().reshape(-1, 1)   # (7350, 1)
meg_target_tensor      = torch.tensor(y_meg).long().reshape(-1, 1)        # (7350, 1)

# ------------------------
# Step 2: Convert 32D latent features to tensors
# ------------------------

fused_acoustic_tensor = torch.from_numpy(fused_acoustic_32D).float()  # (7350, 32)
fused_meg_tensor      = torch.from_numpy(fused_meg_32D).float()       # (7350, 32)

# ------------------------
# Step 3: Attach target columns
# ------------------------

# Concatenate latent features with target
acoustic_full = torch.cat([fused_acoustic_tensor, acoustic_target_tensor.float()], dim=1)  # (7350, 65)
meg_full      = torch.cat([fused_meg_tensor,      meg_target_tensor.float()],      dim=1)  # (7350, 65)

# ------------------------
# Step 4: Concatenate both datasets
# ------------------------

fused_df = torch.cat([acoustic_full, meg_full], dim=0)  # (14700, 65)

# ------------------------
# Step 5: Separate features and labels for PyTorch
# ------------------------

X = fused_df[:, :-1].float()   # Features (32D) -> float32
y = fused_df[:, -1].long()     # Target -> int32

# ------------------------
# Step 6: Print shapes and dtypes
# ------------------------

print(f"Features shape: {X.shape}, dtype: {X.dtype}")  # (14700, 32), float32
print(f"Labels shape: {y.shape}, dtype: {y.dtype}")    # (14700,), int32

Features shape: torch.Size([320, 32]), dtype: torch.float32
Labels shape: torch.Size([320]), dtype: torch.int64

In [7]:
import torch
import pandas as pd

# fused_df shape = (14700, 33)

# Step 6: Convert fused tensor to numpy
fused_df_np = fused_df.numpy()

# Step 7: Create correct column names for 32 latent features + 1 label
feature_names = [f"feat_{i}" for i in range(32)]
feature_names.append("PD_Label_Combined")

# Step 8: Convert to DataFrame
fused_df_named = pd.DataFrame(fused_df_np, columns=feature_names)

# Step 9: Verify
print(fused_df_named.shape)
print(fused_df_named.head())
print(fused_df_named.tail())

(320, 33)
     feat_0    feat_1    feat_2    feat_3    feat_4    feat_5    feat_6  \
0 -0.137377 -0.123854  0.047952 -0.129671 -0.044504  0.180183 -0.111899
1 -0.147138 -0.142424  0.031854 -0.147703  0.013617  0.220541 -0.140908
2  0.028352 -0.058407  0.105410 -0.026430 -0.221880  0.072979  0.069830
3 -0.126131 -0.145256  0.044962 -0.139764 -0.039056  0.191326 -0.102493
4 -0.122634 -0.138478  0.048761 -0.131158 -0.046799  0.179307 -0.095198

     feat_7    feat_8    feat_9  ...   feat_23   feat_24   feat_25   feat_26  \
0  0.304191  0.351378  0.028819  ...  0.064271  0.179407 -0.210484 -0.137064
1  0.314693  0.311851  0.066231  ...  0.045833  0.143630 -0.177370 -0.074331
2  0.300850  0.345376 -0.168055  ...  0.233930  0.269326 -0.205322 -0.182274
3  0.316277  0.336077  0.000034  ...  0.076607  0.206698 -0.189512 -0.086647
4  0.319234  0.348135 -0.013587  ...  0.081966  0.208282 -0.196657 -0.098891

    feat_27   feat_28   feat_29   feat_30   feat_31  PD_Label_Combined
0  0.101078  0.209802 -0.240622 -0.032476  0.226007                1.0
1  0.123555  0.197567 -0.258744  0.027090  0.213927                1.0
2 -0.060913  0.346742 -0.116895 -0.059874  0.136661                0.0
3  0.083903  0.235103 -0.247946  0.012332  0.204074                1.0
4  0.081164  0.240909 -0.244131  0.002586  0.209736                1.0

[5 rows x 33 columns]
       feat_0    feat_1    feat_2    feat_3    feat_4    feat_5    feat_6  \
315 -0.009160 -0.137267  0.112335 -0.117952 -0.120429  0.155791 -0.019289
316 -0.058128 -0.101787  0.107164 -0.115690 -0.029147  0.202005 -0.031084
317 -0.026328 -0.112315  0.094288 -0.120270 -0.097345  0.178831 -0.012342
318 -0.026282 -0.111709  0.093648 -0.119558 -0.095246  0.180856 -0.012726
319 -0.042949 -0.093697  0.112756 -0.113250 -0.053375  0.192451 -0.020734

       feat_7    feat_8    feat_9  ...   feat_23   feat_24   feat_25  \
315  0.344038  0.318028 -0.053813  ...  0.174907  0.283702 -0.202393
316  0.370976  0.312604 -0.013099  ...  0.126896  0.156182 -0.123030
317  0.355857  0.313712 -0.058272  ...  0.184905  0.228406 -0.168854
318  0.355974  0.313451 -0.059105  ...  0.186139  0.225885 -0.165793
319  0.372202  0.310698 -0.033724  ...  0.150387  0.177178 -0.123501

      feat_26   feat_27   feat_28   feat_29   feat_30   feat_31  \
315 -0.164857 -0.000969  0.290911 -0.128412 -0.055841  0.113563
316 -0.129417  0.084349  0.241354 -0.228482  0.003639  0.237904
317 -0.187773  0.024204  0.289895 -0.140908 -0.047929  0.152822
318 -0.186669  0.026781  0.291040 -0.143129 -0.047298  0.155588
319 -0.149160  0.065379  0.256433 -0.206346 -0.018994  0.221769

     PD_Label_Combined
315                0.0
316                1.0
317                0.0
318                0.0
319                1.0

[5 rows x 33 columns]

In [8]:
# Make a copy to be safe (optional)
fused_df_named_int = fused_df_named.copy()

# Convert only the last column to int
fused_df_named_int['PD_Label_Combined'] = fused_df_named_int['PD_Label_Combined'].astype(int)

# Verify
print(fused_df_named_int.dtypes)
print(fused_df_named_int.head())

feat_0               float32
feat_1               float32
feat_2               float32
feat_3               float32
feat_4               float32
feat_5               float32
feat_6               float32
feat_7               float32
feat_8               float32
feat_9               float32
feat_10              float32
feat_11              float32
feat_12              float32
feat_13              float32
feat_14              float32
feat_15              float32
feat_16              float32
feat_17              float32
feat_18              float32
feat_19              float32
feat_20              float32
feat_21              float32
feat_22              float32
feat_23              float32
feat_24              float32
feat_25              float32
feat_26              float32
feat_27              float32
feat_28              float32
feat_29              float32
feat_30              float32
feat_31              float32
PD_Label_Combined      int64
dtype: object
     feat_0    feat_1    feat_2    feat_3    feat_4    feat_5    feat_6  \
0 -0.137377 -0.123854  0.047952 -0.129671 -0.044504  0.180183 -0.111899
1 -0.147138 -0.142424  0.031854 -0.147703  0.013617  0.220541 -0.140908
2  0.028352 -0.058407  0.105410 -0.026430 -0.221880  0.072979  0.069830
3 -0.126131 -0.145256  0.044962 -0.139764 -0.039056  0.191326 -0.102493
4 -0.122634 -0.138478  0.048761 -0.131158 -0.046799  0.179307 -0.095198

     feat_7    feat_8    feat_9  ...   feat_23   feat_24   feat_25   feat_26  \
0  0.304191  0.351378  0.028819  ...  0.064271  0.179407 -0.210484 -0.137064
1  0.314693  0.311851  0.066231  ...  0.045833  0.143630 -0.177370 -0.074331
2  0.300850  0.345376 -0.168055  ...  0.233930  0.269326 -0.205322 -0.182274
3  0.316277  0.336077  0.000034  ...  0.076607  0.206698 -0.189512 -0.086647
4  0.319234  0.348135 -0.013587  ...  0.081966  0.208282 -0.196657 -0.098891

    feat_27   feat_28   feat_29   feat_30   feat_31  PD_Label_Combined
0  0.101078  0.209802 -0.240622 -0.032476  0.226007                  1
1  0.123555  0.197567 -0.258744  0.027090  0.213927                  1
2 -0.060913  0.346742 -0.116895 -0.059874  0.136661                  0
3  0.083903  0.235103 -0.247946  0.012332  0.204074                  1
4  0.081164  0.240909 -0.244131  0.002586  0.209736                  1

[5 rows x 33 columns]

In [9]:
# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [10]:
import pandas as pd

fused_df_named_int.to_csv('/content/drive//MyDrive/Subject-level-fused_df_Baseline_SCL_fgo_data_5-fold_cross_validation.csv', index=False)

In [1]:
# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd

fused_df_named_int = pd.read_csv('/content/drive//MyDrive/Subject-level-fused_df_Baseline_SCL_fgo_data_5-fold_cross_validation.csv')
fused_df_named_int.head()

,feat_0,feat_1,feat_2,feat_3,feat_4,feat_5,feat_6,feat_7,feat_8,feat_9,...,feat_23,feat_24,feat_25,feat_26,feat_27,feat_28,feat_29,feat_30,feat_31,PD_Label_Combined
0,-0.137377,-0.123854,0.047952,-0.129671,-0.044504,0.180183,-0.111899,0.304191,0.351378,0.028819,...,0.064271,0.179407,-0.210484,-0.137064,0.101078,0.209802,-0.240622,-0.032476,0.226007,1
1,-0.147138,-0.142424,0.031854,-0.147703,0.013617,0.220541,-0.140908,0.314693,0.311851,0.066231,...,0.045833,0.143630,-0.177370,-0.074331,0.123555,0.197567,-0.258744,0.027090,0.213927,1
2,0.028352,-0.058407,0.105410,-0.026430,-0.221880,0.072979,0.069830,0.300850,0.345376,-0.168055,...,0.233930,0.269326,-0.205322,-0.182274,-0.060913,0.346742,-0.116895,-0.059874,0.136661,0
3,-0.126131,-0.145256,0.044962,-0.139764,-0.039056,0.191326,-0.102493,0.316277,0.336077,0.000034,...,0.076607,0.206698,-0.189512,-0.086647,0.083903,0.235103,-0.247946,0.012332,0.204074,1
4,-0.122634,-0.138478,0.048761,-0.131158,-0.046799,0.179307,-0.095198,0.319234,0.348135,-0.013587,...,0.081966,0.208282,-0.196657,-0.098891,0.081164,0.240909,-0.244131,0.002586,0.209736,1

Evaluation

In [4]:
# ============================================================
# ###8)###
# ENSEMBLE CLASSIFICATION WITH STRATIFIED 10-FOLD CV
# ============================================================

# ------------------ Install Required Packages ------------------

!pip install xgboost lightgbm catboost scikit-learn statsmodels matplotlib seaborn --quiet


# ------------------ Imports ------------------

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.utils.class_weight import compute_class_weight

from sklearn.model_selection import (
    train_test_split,
    StratifiedKFold
)

from sklearn.preprocessing import StandardScaler

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    balanced_accuracy_score,
    matthews_corrcoef,
    confusion_matrix
)

from sklearn.ensemble import (
    VotingClassifier,
    StackingClassifier,
    RandomForestClassifier,
    HistGradientBoostingClassifier
)

from sklearn.linear_model import LogisticRegression

from xgboost import XGBClassifier

from statsmodels.stats.proportion import proportion_confint


# ============================================================
# STEP 1: PREPARE DATA
# ============================================================

X = fused_df_named_int[
    [f'feat_{i}' for i in range(32)]
].copy()

y = fused_df_named_int[
    "PD_Label_Combined"
].copy()


# ------------------ Convert X to numeric ------------------

X = X.apply(
    pd.to_numeric,
    errors='coerce'
)

X.fillna(
    0,
    inplace=True
)


# ============================================================
# STEP 2: CLASS WEIGHTS
# ============================================================

classes = np.unique(y)

class_weights = compute_class_weight(
    class_weight='balanced',
    classes=classes,
    y=y
)

class_weights_dict = {
    int(classes[0]): float(class_weights[0]),
    int(classes[1]): float(class_weights[1])
}

print("\nClass Weights:")
print(class_weights_dict)


# ============================================================
# STEP 3: TRAIN-TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=42
)


print("\nTrain Shape :", X_train.shape)
print("Test Shape  :", X_test.shape)

print("\nTraining Class Distribution:")
print(y_train.value_counts())

print("\nTesting Class Distribution:")
print(y_test.value_counts())


# ============================================================
# STEP 4: HANDLE CLASS IMBALANCE
# ============================================================

cw = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_train),
    y=y_train
)

cw_dict = dict(
    zip(
        np.unique(y_train),
        cw
    )
)

scale_pos_weight = (
    cw[1] / cw[0]
)

print("\nTraining Class Weights:")
print(cw_dict)

print(
    "\nXGBoost scale_pos_weight:",
    scale_pos_weight
)


# ============================================================
# STEP 5: BASE MODEL CREATION FUNCTION
# ============================================================

def create_models():

    # ---------------- XGBoost ----------------

    xgb = XGBClassifier(
        n_estimators=200,
        max_depth=4,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,

        scale_pos_weight=scale_pos_weight,

        eval_metric='logloss',

        random_state=42,
        n_jobs=-1
    )


    # ---------------- Random Forest ----------------

    rf = RandomForestClassifier(
        n_estimators=200,

        class_weight='balanced',

        random_state=42,
        n_jobs=-1
    )


    # ---------------- HistGradientBoosting ----------------

    hgb = HistGradientBoostingClassifier(
        max_iter=200,
        learning_rate=0.05,
        max_leaf_nodes=31,

        class_weight='balanced',

        random_state=42
    )


    return xgb, rf, hgb


# ============================================================
# STEP 6: STRATIFIED 10-FOLD CV
# ============================================================

skf = StratifiedKFold(
    n_splits=10,
    shuffle=True,
    random_state=42
)


# ============================================================
# STEP 7: EVALUATION FUNCTION
# ============================================================

def evaluate_model(model_name):

    # ========================================================
    # CV METRIC STORAGE
    # ========================================================

    cv_accuracy = []
    cv_precision = []
    cv_sensitivity = []
    cv_f1 = []
    cv_auc = []
    cv_balanced_accuracy = []


    # ========================================================
    # 10-FOLD STRATIFIED CROSS-VALIDATION
    # ========================================================

    for fold, (train_idx, val_idx) in enumerate(
        skf.split(X_train, y_train),
        start=1
    ):

        print(
            f"\n{model_name} | Fold {fold}/10"
        )


        # ----------------------------------------------------
        # Split fold
        # ----------------------------------------------------

        X_tr = X_train.iloc[
            train_idx
        ]

        X_val = X_train.iloc[
            val_idx
        ]

        y_tr = y_train.iloc[
            train_idx
        ]

        y_val = y_train.iloc[
            val_idx
        ]


        # ----------------------------------------------------
        # Scaling INSIDE EACH FOLD
        # ----------------------------------------------------

        scaler = StandardScaler()

        X_tr_scaled = scaler.fit_transform(
            X_tr
        )

        X_val_scaled = scaler.transform(
            X_val
        )


        # ----------------------------------------------------
        # Create FRESH models for every fold
        # ----------------------------------------------------

        xgb, rf, hgb = create_models()


        # ----------------------------------------------------
        # Select requested model
        # ----------------------------------------------------

        if model_name == "XGBoost":

            model = xgb


        elif model_name == "Random Forest":

            model = rf


        elif model_name == "HistGradientBoosting":

            model = hgb


        elif model_name == "Voting Fusion":

            model = VotingClassifier(
                estimators=[
                    ('xgb', xgb),
                    ('rf', rf),
                    ('hgb', hgb)
                ],
                voting='soft'
            )


        elif model_name == "Stacking Fusion":

            model = StackingClassifier(
                estimators=[
                    ('xgb', xgb),
                    ('rf', rf),
                    ('hgb', hgb)
                ],

                final_estimator=LogisticRegression(
                    max_iter=1000,
                    class_weight='balanced'
                ),

                passthrough=True,

                cv=5
            )


        else:

            raise ValueError(
                f"Unknown model: {model_name}"
            )


        # ----------------------------------------------------
        # Train fold
        # ----------------------------------------------------

        model.fit(
            X_tr_scaled,
            y_tr
        )


        # ----------------------------------------------------
        # Validation predictions
        # ----------------------------------------------------

        val_preds = model.predict(
            X_val_scaled
        )

        val_probs = model.predict_proba(
            X_val_scaled
        )[:, 1]


        # ----------------------------------------------------
        # Fold metrics
        # ----------------------------------------------------

        fold_accuracy = accuracy_score(
            y_val,
            val_preds
        )

        fold_precision = precision_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_sensitivity = recall_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_f1 = f1_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_auc = roc_auc_score(
            y_val,
            val_probs
        )

        fold_balanced_accuracy = balanced_accuracy_score(
            y_val,
            val_preds
        )


        # ----------------------------------------------------
        # Store fold metrics
        # ----------------------------------------------------

        cv_accuracy.append(
            fold_accuracy
        )

        cv_precision.append(
            fold_precision
        )

        cv_sensitivity.append(
            fold_sensitivity
        )

        cv_f1.append(
            fold_f1
        )

        cv_auc.append(
            fold_auc
        )

        cv_balanced_accuracy.append(
            fold_balanced_accuracy
        )


        # ----------------------------------------------------
        # Print fold result
        # ----------------------------------------------------

        print(
            f"Accuracy            : {fold_accuracy:.4f}"
        )

        print(
            f"Precision           : {fold_precision:.4f}"
        )

        print(
            f"Sensitivity         : {fold_sensitivity:.4f}"
        )

        print(
            f"F1 Score            : {fold_f1:.4f}"
        )

        print(
            f"ROC-AUC             : {fold_auc:.4f}"
        )

        print(
            f"Balanced Accuracy   : "
            f"{fold_balanced_accuracy:.4f}"
        )


    # ========================================================
    # CV MEAN RESULTS
    # ========================================================

    cv_accuracy_mean = np.mean(
        cv_accuracy
    )

    cv_precision_mean = np.mean(
        cv_precision
    )

    cv_sensitivity_mean = np.mean(
        cv_sensitivity
    )

    cv_f1_mean = np.mean(
        cv_f1
    )

    cv_auc_mean = np.mean(
        cv_auc
    )

    cv_balanced_accuracy_mean = np.mean(
        cv_balanced_accuracy
    )


    # ========================================================
    # CROSS-VALIDATION RESULTS
    # ========================================================

    print(
        "\n================================================"
    )

    print(
        f"{model_name} - Cross-Validation (10-fold)"
    )

    print(
        "================================================"
    )

    print(
        f"Accuracy            : "
        f"{cv_accuracy_mean:.4f}"
    )

    print(
        f"Precision           : "
        f"{cv_precision_mean:.4f}"
    )

    print(
        f"Recall/Sensitivity  : "
        f"{cv_sensitivity_mean:.4f}"
    )

    print(
        f"F1 Score            : "
        f"{cv_f1_mean:.4f}"
    )

    print(
        f"ROC-AUC             : "
        f"{cv_auc_mean:.4f}"
    )

    print(
        f"Balanced Accuracy   : "
        f"{cv_balanced_accuracy_mean:.4f}"
    )


    # ========================================================
    # TRAIN FINAL MODEL ON COMPLETE TRAINING SET
    # ========================================================

    final_scaler = StandardScaler()

    X_train_final_scaled = final_scaler.fit_transform(
        X_train
    )

    X_test_final_scaled = final_scaler.transform(
        X_test
    )


    # --------------------------------------------------------
    # Create fresh final models
    # --------------------------------------------------------

    xgb, rf, hgb = create_models()


    if model_name == "XGBoost":

        final_model = xgb


    elif model_name == "Random Forest":

        final_model = rf


    elif model_name == "HistGradientBoosting":

        final_model = hgb


    elif model_name == "Voting Fusion":

        final_model = VotingClassifier(
            estimators=[
                ('xgb', xgb),
                ('rf', rf),
                ('hgb', hgb)
            ],
            voting='soft'
        )


    elif model_name == "Stacking Fusion":

        final_model = StackingClassifier(
            estimators=[
                ('xgb', xgb),
                ('rf', rf),
                ('hgb', hgb)
            ],

            final_estimator=LogisticRegression(
                max_iter=1000,
                class_weight='balanced'
            ),

            passthrough=True,

            cv=5
        )


    # ========================================================
    # FINAL TRAINING
    # ========================================================

    final_model.fit(
        X_train_final_scaled,
        y_train
    )


    # ========================================================
    # TEST PREDICTIONS
    # ========================================================

    test_preds = final_model.predict(
        X_test_final_scaled
    )

    test_probs = final_model.predict_proba(
        X_test_final_scaled
    )[:, 1]


    # ========================================================
    # TEST METRICS
    # ========================================================

    accuracy = accuracy_score(
        y_test,
        test_preds
    )

    precision = precision_score(
        y_test,
        test_preds,
        zero_division=0
    )

    sensitivity = recall_score(
        y_test,
        test_preds,
        zero_division=0
    )

    f1 = f1_score(
        y_test,
        test_preds,
        zero_division=0
    )

    roc_auc = roc_auc_score(
        y_test,
        test_probs
    )

    balanced_accuracy = balanced_accuracy_score(
        y_test,
        test_preds
    )

    mcc = matthews_corrcoef(
        y_test,
        test_preds
    )


    # ========================================================
    # CONFUSION MATRIX
    # ========================================================

    cm = confusion_matrix(
        y_test,
        test_preds,
        labels=[0, 1]
    )

    tn, fp, fn, tp = cm.ravel()


    # ========================================================
    # SENSITIVITY / SPECIFICITY
    # ========================================================

    sensitivity = (
        tp / (tp + fn)
        if (tp + fn) > 0
        else 0
    )

    specificity = (
        tn / (tn + fp)
        if (tn + fp) > 0
        else 0
    )


    # ========================================================
    # 95% CONFIDENCE INTERVALS
    # ========================================================

    # ---------------- Accuracy CI ----------------

    acc_low, acc_high = proportion_confint(
        count=int(round(accuracy * len(y_test))),
        nobs=len(y_test),
        alpha=0.05,
        method='wilson'
    )


    # ---------------- Precision CI ----------------

    precision_low, precision_high = proportion_confint(
        count=tp,
        nobs=(tp + fp),
        alpha=0.05,
        method='wilson'
    ) if (tp + fp) > 0 else (0.0, 0.0)


    # ---------------- Sensitivity CI ----------------

    sensitivity_low, sensitivity_high = proportion_confint(
        count=tp,
        nobs=(tp + fn),
        alpha=0.05,
        method='wilson'
    ) if (tp + fn) > 0 else (0.0, 0.0)


    # ---------------- Specificity CI ----------------

    specificity_low, specificity_high = proportion_confint(
        count=tn,
        nobs=(tn + fp),
        alpha=0.05,
        method='wilson'
    ) if (tn + fp) > 0 else (0.0, 0.0)


    # ========================================================
    # TEST SET PERFORMANCE
    # ========================================================

    print(
        "\n================================================"
    )

    print(
        f"{model_name} - Test Set Performance"
    )

    print(
        "================================================"
    )

    print(
        f"Accuracy            : {accuracy:.4f} "
        f"(95% CI: "
        f"{acc_low:.4f}-{acc_high:.4f})"
    )

    print(
        f"Precision           : {precision:.4f} "
        f"(95% CI: "
        f"{precision_low:.4f}-{precision_high:.4f})"
    )

    print(
        f"Sensitivity         : {sensitivity:.4f} "
        f"(95% CI: "
        f"{sensitivity_low:.4f}-{sensitivity_high:.4f})"
    )

    print(
        f"Specificity         : {specificity:.4f} "
        f"(95% CI: "
        f"{specificity_low:.4f}-{specificity_high:.4f})"
    )

    print(
        f"F1 Score            : {f1:.4f}"
    )

    print(
        f"ROC-AUC             : {roc_auc:.4f}"
    )

    print(
        f"Balanced Accuracy   : "
        f"{balanced_accuracy:.4f}"
    )

    print(
        f"MCC                 : {mcc:.4f}"
    )


    # ========================================================
    # CONFUSION MATRIX
    # ========================================================

    print(
        "\nConfusion Matrix:"
    )

    print(cm)

    print(
        "\nTN :", tn
    )

    print(
        "FP :", fp
    )

    print(
        "FN :", fn
    )

    print(
        "TP :", tp
    )


    # ========================================================
    # STORE RESULTS
    # ========================================================

    result = {

        # ---------------- CV ----------------

        "CV Accuracy":
            cv_accuracy_mean,

        "CV Precision":
            cv_precision_mean,

        "CV Sensitivity":
            cv_sensitivity_mean,

        "CV F1":
            cv_f1_mean,

        "CV ROC-AUC":
            cv_auc_mean,

        "CV Balanced Accuracy":
            cv_balanced_accuracy_mean,


        # ---------------- Test ----------------

        "Accuracy":
            accuracy,

        "Accuracy CI Low":
            acc_low,

        "Accuracy CI High":
            acc_high,


        "Precision":
            precision,

        "Precision CI Low":
            precision_low,

        "Precision CI High":
            precision_high,


        "Sensitivity":
            sensitivity,

        "Sensitivity CI Low":
            sensitivity_low,

        "Sensitivity CI High":
            sensitivity_high,


        "Specificity":
            specificity,

        "Specificity CI Low":
            specificity_low,

        "Specificity CI High":
            specificity_high,


        "F1":
            f1,

        "ROC-AUC":
            roc_auc,

        "Balanced Accuracy":
            balanced_accuracy,

        "MCC":
            mcc,


        # ---------------- Confusion Matrix ----------------

        "TN":
            tn,

        "FP":
            fp,

        "FN":
            fn,

        "TP":
            tp
    }


    return result


# ============================================================
# STEP 8: EVALUATE ALL MODELS
# ============================================================

model_names = [
    "XGBoost",
    "Random Forest",
    "HistGradientBoosting",
    "Voting Fusion",
    "Stacking Fusion"
]


results = {}

for name in model_names:

    print(
        "\n\n################################################"
    )

    print(
        f"Evaluating: {name}"
    )

    print(
        "################################################"
    )

    results[name] = evaluate_model(
        name
    )


# ============================================================
# STEP 9: FINAL RESULTS DATAFRAME
# ============================================================

results_df = pd.DataFrame(
    results
).T


# ============================================================
# STEP 10: ORDER RESULTS
# ============================================================

results_df = results_df[
    [

        # ---------------- CV ----------------

        "CV Accuracy",
        "CV Precision",
        "CV Sensitivity",
        "CV F1",
        "CV ROC-AUC",
        "CV Balanced Accuracy",


        # ---------------- Test ----------------

        "Accuracy",
        "Accuracy CI Low",
        "Accuracy CI High",

        "Precision",
        "Precision CI Low",
        "Precision CI High",

        "Sensitivity",
        "Sensitivity CI Low",
        "Sensitivity CI High",

        "Specificity",
        "Specificity CI Low",
        "Specificity CI High",

        "F1",
        "ROC-AUC",
        "Balanced Accuracy",
        "MCC",

        # ---------------- Confusion Matrix ----------------

        "TN",
        "FP",
        "FN",
        "TP"
    ]
]


# ============================================================
# STEP 11: DISPLAY FINAL RESULTS
# ============================================================

print(
    "\n================================================"
)

print(
    "FINAL MODEL COMPARISON"
)

print(
    "================================================\n"
)


display(
    results_df.sort_values(
        by="F1",
        ascending=False
    )
)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 7.9 MB/s eta 0:00:00

Class Weights:
{0: 1.2213740458015268, 1: 0.8465608465608465}

Train Shape : (256, 32)
Test Shape  : (64, 32)

Training Class Distribution:
PD_Label_Combined
1    151
0    105
Name: count, dtype: int64

Testing Class Distribution:
PD_Label_Combined
1    38
0    26
Name: count, dtype: int64

Training Class Weights:
{np.int64(0): np.float64(1.2190476190476192), np.int64(1): np.float64(0.847682119205298)}

XGBoost scale_pos_weight: 0.6953642384105959


################################################
Evaluating: XGBoost
################################################

XGBoost | Fold 1/10
Accuracy            : 0.6538
Precision           : 0.6842
Sensitivity         : 0.8125
F1 Score            : 0.7429
ROC-AUC             : 0.7812
Balanced Accuracy   : 0.6062

XGBoost | Fold 2/10
Accuracy            : 0.6538
Precision           : 0.7143
Sensitivity         : 0.6667
F1 Score            : 0.6897
ROC-AUC             : 0.7212
Balanced Accuracy   : 0.6515

XGBoost | Fold 3/10
Accuracy            : 0.7308
Precision           : 0.7222
Sensitivity         : 0.8667
F1 Score            : 0.7879
ROC-AUC             : 0.8242
Balanced Accuracy   : 0.7061

XGBoost | Fold 4/10
Accuracy            : 0.7692
Precision           : 0.8462
Sensitivity         : 0.7333
F1 Score            : 0.7857
ROC-AUC             : 0.8545
Balanced Accuracy   : 0.7758

XGBoost | Fold 5/10
Accuracy            : 0.8462
Precision           : 0.9231
Sensitivity         : 0.8000
F1 Score            : 0.8571
ROC-AUC             : 0.8848
Balanced Accuracy   : 0.8545

XGBoost | Fold 6/10
Accuracy            : 0.8077
Precision           : 1.0000
Sensitivity         : 0.6667
F1 Score            : 0.8000
ROC-AUC             : 0.8727
Balanced Accuracy   : 0.8333

XGBoost | Fold 7/10
Accuracy            : 0.8000
Precision           : 0.9167
Sensitivity         : 0.7333
F1 Score            : 0.8148
ROC-AUC             : 0.9033
Balanced Accuracy   : 0.8167

XGBoost | Fold 8/10
Accuracy            : 0.8000
Precision           : 0.8571
Sensitivity         : 0.8000
F1 Score            : 0.8276
ROC-AUC             : 0.9200
Balanced Accuracy   : 0.8000

XGBoost | Fold 9/10
Accuracy            : 0.8000
Precision           : 0.8571
Sensitivity         : 0.8000
F1 Score            : 0.8276
ROC-AUC             : 0.8733
Balanced Accuracy   : 0.8000

XGBoost | Fold 10/10
Accuracy            : 0.7600
Precision           : 0.8462
Sensitivity         : 0.7333
F1 Score            : 0.7857
ROC-AUC             : 0.8800
Balanced Accuracy   : 0.7667

================================================
XGBoost - Cross-Validation (10-fold)
================================================
Accuracy            : 0.7622
Precision           : 0.8367
Recall/Sensitivity  : 0.7612
F1 Score            : 0.7919
ROC-AUC             : 0.8515
Balanced Accuracy   : 0.7611

================================================
XGBoost - Test Set Performance
================================================
Accuracy            : 0.7031 (95% CI: 0.5823-0.8009)
Precision           : 0.7317 (95% CI: 0.5807-0.8431)
Sensitivity         : 0.7895 (95% CI: 0.6365-0.8893)
Specificity         : 0.5769 (95% CI: 0.3895-0.7446)
F1 Score            : 0.7595
ROC-AUC             : 0.7692
Balanced Accuracy   : 0.6832
MCC                 : 0.3750

Confusion Matrix:
[[15 11]
 [ 8 30]]

TN : 15
FP : 11
FN : 8
TP : 30


################################################
Evaluating: Random Forest
################################################

Random Forest | Fold 1/10
Accuracy            : 0.6538
Precision           : 0.6667
Sensitivity         : 0.8750
F1 Score            : 0.7568
ROC-AUC             : 0.8313
Balanced Accuracy   : 0.5875

Random Forest | Fold 2/10
Accuracy            : 0.6538
Precision           : 0.6875
Sensitivity         : 0.7333
F1 Score            : 0.7097
ROC-AUC             : 0.7273
Balanced Accuracy   : 0.6394

Random Forest | Fold 3/10
Accuracy            : 0.6538
Precision           : 0.6667
Sensitivity         : 0.8000
F1 Score            : 0.7273
ROC-AUC             : 0.8303
Balanced Accuracy   : 0.6273

Random Forest | Fold 4/10
Accuracy            : 0.7308
Precision           : 0.7857
Sensitivity         : 0.7333
F1 Score            : 0.7586
ROC-AUC             : 0.8242
Balanced Accuracy   : 0.7303

Random Forest | Fold 5/10
Accuracy            : 0.7308
Precision           : 0.7857
Sensitivity         : 0.7333
F1 Score            : 0.7586
ROC-AUC             : 0.8606
Balanced Accuracy   : 0.7303

Random Forest | Fold 6/10
Accuracy            : 0.8077
Precision           : 1.0000
Sensitivity         : 0.6667
F1 Score            : 0.8000
ROC-AUC             : 0.8727
Balanced Accuracy   : 0.8333

Random Forest | Fold 7/10
Accuracy            : 0.8000
Precision           : 0.8571
Sensitivity         : 0.8000
F1 Score            : 0.8276
ROC-AUC             : 0.8500
Balanced Accuracy   : 0.8000

Random Forest | Fold 8/10
Accuracy            : 0.7200
Precision           : 0.7500
Sensitivity         : 0.8000
F1 Score            : 0.7742
ROC-AUC             : 0.8933
Balanced Accuracy   : 0.7000

Random Forest | Fold 9/10
Accuracy            : 0.8000
Precision           : 0.8571
Sensitivity         : 0.8000
F1 Score            : 0.8276
ROC-AUC             : 0.8267
Balanced Accuracy   : 0.8000

Random Forest | Fold 10/10
Accuracy            : 0.8000
Precision           : 0.8571
Sensitivity         : 0.8000
F1 Score            : 0.8276
ROC-AUC             : 0.8833
Balanced Accuracy   : 0.8000

================================================
Random Forest - Cross-Validation (10-fold)
================================================
Accuracy            : 0.7351
Precision           : 0.7914
Recall/Sensitivity  : 0.7742
F1 Score            : 0.7768
ROC-AUC             : 0.8400
Balanced Accuracy   : 0.7248

================================================
Random Forest - Test Set Performance
================================================
Accuracy            : 0.6406 (95% CI: 0.5182-0.7471)
Precision           : 0.6829 (95% CI: 0.5302-0.8044)
Sensitivity         : 0.7368 (95% CI: 0.5799-0.8503)
Specificity         : 0.5000 (95% CI: 0.3206-0.6794)
F1 Score            : 0.7089
ROC-AUC             : 0.7596
Balanced Accuracy   : 0.6184
MCC                 : 0.2424

Confusion Matrix:
[[13 13]
 [10 28]]

TN : 13
FP : 13
FN : 10
TP : 28


################################################
Evaluating: HistGradientBoosting
################################################

HistGradientBoosting | Fold 1/10
Accuracy            : 0.6538
Precision           : 0.6667
Sensitivity         : 0.8750
F1 Score            : 0.7568
ROC-AUC             : 0.7812
Balanced Accuracy   : 0.5875

HistGradientBoosting | Fold 2/10
Accuracy            : 0.6538
Precision           : 0.6875
Sensitivity         : 0.7333
F1 Score            : 0.7097
ROC-AUC             : 0.7424
Balanced Accuracy   : 0.6394

HistGradientBoosting | Fold 3/10
Accuracy            : 0.6923
Precision           : 0.6842
Sensitivity         : 0.8667
F1 Score            : 0.7647
ROC-AUC             : 0.7939
Balanced Accuracy   : 0.6606

HistGradientBoosting | Fold 4/10
Accuracy            : 0.7692
Precision           : 0.8462
Sensitivity         : 0.7333
F1 Score            : 0.7857
ROC-AUC             : 0.8545
Balanced Accuracy   : 0.7758

HistGradientBoosting | Fold 5/10
Accuracy            : 0.8462
Precision           : 0.9231
Sensitivity         : 0.8000
F1 Score            : 0.8571
ROC-AUC             : 0.8848
Balanced Accuracy   : 0.8545

HistGradientBoosting | Fold 6/10
Accuracy            : 0.8077
Precision           : 1.0000
Sensitivity         : 0.6667
F1 Score            : 0.8000
ROC-AUC             : 0.8788
Balanced Accuracy   : 0.8333

HistGradientBoosting | Fold 7/10
Accuracy            : 0.7200
Precision           : 0.7857
Sensitivity         : 0.7333
F1 Score            : 0.7586
ROC-AUC             : 0.8833
Balanced Accuracy   : 0.7167

HistGradientBoosting | Fold 8/10
Accuracy            : 0.8000
Precision           : 0.8571
Sensitivity         : 0.8000
F1 Score            : 0.8276
ROC-AUC             : 0.9133
Balanced Accuracy   : 0.8000

HistGradientBoosting | Fold 9/10
Accuracy            : 0.8000
Precision           : 0.8571
Sensitivity         : 0.8000
F1 Score            : 0.8276
ROC-AUC             : 0.9000
Balanced Accuracy   : 0.8000

HistGradientBoosting | Fold 10/10
Accuracy            : 0.8000
Precision           : 0.8571
Sensitivity         : 0.8000
F1 Score            : 0.8276
ROC-AUC             : 0.8733
Balanced Accuracy   : 0.8000

================================================
HistGradientBoosting - Cross-Validation (10-fold)
================================================
Accuracy            : 0.7543
Precision           : 0.8165
Recall/Sensitivity  : 0.7808
F1 Score            : 0.7915
ROC-AUC             : 0.8506
Balanced Accuracy   : 0.7468

================================================
HistGradientBoosting - Test Set Performance
================================================
Accuracy            : 0.7031 (95% CI: 0.5823-0.8009)
Precision           : 0.7209 (95% CI: 0.5731-0.8325)
Sensitivity         : 0.8158 (95% CI: 0.6658-0.9078)
Specificity         : 0.5385 (95% CI: 0.3546-0.7124)
F1 Score            : 0.7654
ROC-AUC             : 0.7794
Balanced Accuracy   : 0.6771
MCC                 : 0.3705

Confusion Matrix:
[[14 12]
 [ 7 31]]

TN : 14
FP : 12
FN : 7
TP : 31


################################################
Evaluating: Voting Fusion
################################################

Voting Fusion | Fold 1/10
Accuracy            : 0.6538
Precision           : 0.6842
Sensitivity         : 0.8125
F1 Score            : 0.7429
ROC-AUC             : 0.8187
Balanced Accuracy   : 0.6062

Voting Fusion | Fold 2/10
Accuracy            : 0.6154
Precision           : 0.6667
Sensitivity         : 0.6667
F1 Score            : 0.6667
ROC-AUC             : 0.7333
Balanced Accuracy   : 0.6061

Voting Fusion | Fold 3/10
Accuracy            : 0.6923
Precision           : 0.6842
Sensitivity         : 0.8667
F1 Score            : 0.7647
ROC-AUC             : 0.8182
Balanced Accuracy   : 0.6606

Voting Fusion | Fold 4/10
Accuracy            : 0.8077
Precision           : 0.8571
Sensitivity         : 0.8000
F1 Score            : 0.8276
ROC-AUC             : 0.8606
Balanced Accuracy   : 0.8091

Voting Fusion | Fold 5/10
Accuracy            : 0.8462
Precision           : 0.9231
Sensitivity         : 0.8000
F1 Score            : 0.8571
ROC-AUC             : 0.8848
Balanced Accuracy   : 0.8545

Voting Fusion | Fold 6/10
Accuracy            : 0.8077
Precision           : 1.0000
Sensitivity         : 0.6667
F1 Score            : 0.8000
ROC-AUC             : 0.8788
Balanced Accuracy   : 0.8333

Voting Fusion | Fold 7/10
Accuracy            : 0.7600
Precision           : 0.8462
Sensitivity         : 0.7333
F1 Score            : 0.7857
ROC-AUC             : 0.8767
Balanced Accuracy   : 0.7667

Voting Fusion | Fold 8/10
Accuracy            : 0.7600
Precision           : 0.8000
Sensitivity         : 0.8000
F1 Score            : 0.8000
ROC-AUC             : 0.9000
Balanced Accuracy   : 0.7500

Voting Fusion | Fold 9/10
Accuracy            : 0.8000
Precision           : 0.8571
Sensitivity         : 0.8000
F1 Score            : 0.8276
ROC-AUC             : 0.8600
Balanced Accuracy   : 0.8000

Voting Fusion | Fold 10/10
Accuracy            : 0.8000
Precision           : 0.8571
Sensitivity         : 0.8000
F1 Score            : 0.8276
ROC-AUC             : 0.8600
Balanced Accuracy   : 0.8000

================================================
Voting Fusion - Cross-Validation (10-fold)
================================================
Accuracy            : 0.7543
Precision           : 0.8176
Recall/Sensitivity  : 0.7746
F1 Score            : 0.7900
ROC-AUC             : 0.8491
Balanced Accuracy   : 0.7487

================================================
Voting Fusion - Test Set Performance
================================================
Accuracy            : 0.6875 (95% CI: 0.5661-0.7877)
Precision           : 0.7045 (95% CI: 0.5578-0.8184)
Sensitivity         : 0.8158 (95% CI: 0.6658-0.9078)
Specificity         : 0.5000 (95% CI: 0.3206-0.6794)
F1 Score            : 0.7561
ROC-AUC             : 0.7783
Balanced Accuracy   : 0.6579
MCC                 : 0.3346

Confusion Matrix:
[[13 13]
 [ 7 31]]

TN : 13
FP : 13
FN : 7
TP : 31


################################################
Evaluating: Stacking Fusion
################################################

Stacking Fusion | Fold 1/10
Accuracy            : 0.6923
Precision           : 0.7222
Sensitivity         : 0.8125
F1 Score            : 0.7647
ROC-AUC             : 0.8000
Balanced Accuracy   : 0.6562

Stacking Fusion | Fold 2/10
Accuracy            : 0.6538
Precision           : 0.7143
Sensitivity         : 0.6667
F1 Score            : 0.6897
ROC-AUC             : 0.7212
Balanced Accuracy   : 0.6515

Stacking Fusion | Fold 3/10
Accuracy            : 0.7692
Precision           : 0.8000
Sensitivity         : 0.8000
F1 Score            : 0.8000
ROC-AUC             : 0.9152
Balanced Accuracy   : 0.7636

Stacking Fusion | Fold 4/10
Accuracy            : 0.6923
Precision           : 0.8889
Sensitivity         : 0.5333
F1 Score            : 0.6667
ROC-AUC             : 0.8606
Balanced Accuracy   : 0.7212

Stacking Fusion | Fold 5/10
Accuracy            : 0.8077
Precision           : 1.0000
Sensitivity         : 0.6667
F1 Score            : 0.8000
ROC-AUC             : 0.9273
Balanced Accuracy   : 0.8333

Stacking Fusion | Fold 6/10
Accuracy            : 0.6154
Precision           : 0.7778
Sensitivity         : 0.4667
F1 Score            : 0.5833
ROC-AUC             : 0.8242
Balanced Accuracy   : 0.6424

Stacking Fusion | Fold 7/10
Accuracy            : 0.7200
Precision           : 0.7857
Sensitivity         : 0.7333
F1 Score            : 0.7586
ROC-AUC             : 0.8700
Balanced Accuracy   : 0.7167

Stacking Fusion | Fold 8/10
Accuracy            : 0.8000
Precision           : 1.0000
Sensitivity         : 0.6667
F1 Score            : 0.8000
ROC-AUC             : 0.8467
Balanced Accuracy   : 0.8333

Stacking Fusion | Fold 9/10
Accuracy            : 0.7600
Precision           : 0.8462
Sensitivity         : 0.7333
F1 Score            : 0.7857
ROC-AUC             : 0.8933
Balanced Accuracy   : 0.7667

Stacking Fusion | Fold 10/10
Accuracy            : 0.7200
Precision           : 0.9000
Sensitivity         : 0.6000
F1 Score            : 0.7200
ROC-AUC             : 0.9000
Balanced Accuracy   : 0.7500

================================================
Stacking Fusion - Cross-Validation (10-fold)
================================================
Accuracy            : 0.7231
Precision           : 0.8435
Recall/Sensitivity  : 0.6679
F1 Score            : 0.7369
ROC-AUC             : 0.8558
Balanced Accuracy   : 0.7335

================================================
Stacking Fusion - Test Set Performance
================================================
Accuracy            : 0.7656 (95% CI: 0.6487-0.8525)
Precision           : 0.8710 (95% CI: 0.7115-0.9487)
Sensitivity         : 0.7105 (95% CI: 0.5524-0.8300)
Specificity         : 0.8462 (95% CI: 0.6647-0.9385)
F1 Score            : 0.7826
ROC-AUC             : 0.8259
Balanced Accuracy   : 0.7783
MCC                 : 0.5471

Confusion Matrix:
[[22  4]
 [11 27]]

TN : 22
FP : 4
FN : 11
TP : 27

================================================
FINAL MODEL COMPARISON
================================================

,CV Accuracy,CV Precision,CV Sensitivity,CV F1,CV ROC-AUC,CV Balanced Accuracy,Accuracy,Accuracy CI Low,Accuracy CI High,Precision,...,Specificity CI Low,Specificity CI High,F1,ROC-AUC,Balanced Accuracy,MCC,TN,FP,FN,TP
Stacking Fusion,0.723077,0.843504,0.667917,0.736870,0.855848,0.733504,0.765625,0.648667,0.852501,0.870968,...,0.664688,0.938500,0.782609,0.825911,0.778340,0.547074,22.0,4.0,11.0,27.0
HistGradientBoosting,0.754308,0.816475,0.780833,0.791538,0.850580,0.746780,0.703125,0.582298,0.800948,0.720930,...,0.354579,0.712441,0.765432,0.779352,0.677126,0.370549,14.0,12.0,7.0,31.0
XGBoost,0.762154,0.836706,0.761250,0.791895,0.851549,0.761080,0.703125,0.582298,0.800948,0.731707,...,0.389486,0.744556,0.759494,0.769231,0.683198,0.375037,15.0,11.0,8.0,30.0
Voting Fusion,0.754308,0.817575,0.774583,0.789985,0.849117,0.748655,0.687500,0.566077,0.787689,0.704545,...,0.320606,0.679394,0.756098,0.778340,0.657895,0.334607,13.0,13.0,7.0,31.0
Random Forest,0.735077,0.791369,0.774167,0.776790,0.839973,0.724811,0.640625,0.518209,0.747116,0.682927,...,0.320606,0.679394,0.708861,0.759615,0.618421,0.242427,13.0,13.0,10.0,28.0