Rest task

In [ ]:
# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
fused_df_named_int = pd.read_csv('/content/drive//MyDrive/Subject-level-fused_frest_(with_120_epoches)_MIRA-Net_data.csv')
fused_df_named_int.head()

,feat_0,feat_1,feat_2,feat_3,feat_4,feat_5,feat_6,feat_7,feat_8,feat_9,...,feat_23,feat_24,feat_25,feat_26,feat_27,feat_28,feat_29,feat_30,feat_31,PD_Label_Combined
0,-0.167408,0.247791,0.108752,0.145678,0.128758,0.139512,-0.388908,0.054051,0.095272,0.254308,...,0.108517,-0.281111,0.177043,0.142417,0.167025,-0.078603,0.080411,0.143566,-0.061701,1
1,-0.180029,0.247106,0.100994,0.151763,0.123837,0.135823,-0.402635,0.052673,0.077987,0.259495,...,0.100198,-0.276510,0.187728,0.125000,0.170609,-0.067088,0.090003,0.144013,-0.061494,1
2,-0.001097,0.241502,0.040228,-0.006898,-0.064571,0.300266,-0.410168,-0.137268,-0.039887,0.266537,...,0.046432,-0.352390,0.039223,0.215824,0.131209,-0.130986,-0.058039,0.051696,-0.153072,0
3,-0.176504,0.251508,0.101407,0.158764,0.116113,0.131070,-0.395935,0.038676,0.080782,0.265491,...,0.101161,-0.292017,0.183169,0.119719,0.178148,-0.062601,0.082337,0.140690,-0.052108,1
4,-0.173168,0.251137,0.105332,0.155920,0.118184,0.132368,-0.391873,0.043918,0.086204,0.263430,...,0.104799,-0.291758,0.184798,0.124395,0.174616,-0.067344,0.082248,0.141177,-0.051903,1

In [ ]:
fused_df_named_int.shape

(320, 33)

Testing on meg

In [ ]:
# ============================================================
# ###8)###
# ENSEMBLE CLASSIFICATION WITH STRATIFIED 10-FOLD CV
# ============================================================

# ------------------ Install Required Packages ------------------

!pip install xgboost lightgbm catboost scikit-learn statsmodels matplotlib seaborn --quiet


# ------------------ Imports ------------------

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.utils.class_weight import compute_class_weight

from sklearn.model_selection import (
    train_test_split,
    StratifiedKFold
)

from sklearn.preprocessing import StandardScaler

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    balanced_accuracy_score,
    matthews_corrcoef,
    confusion_matrix
)

from sklearn.ensemble import (
    VotingClassifier,
    StackingClassifier,
    RandomForestClassifier,
    HistGradientBoostingClassifier
)

from sklearn.linear_model import LogisticRegression

from xgboost import XGBClassifier

from statsmodels.stats.proportion import proportion_confint



# ============================================================
# STEP 1: PREPARE DATA
# ============================================================

# Feature columns
feature_cols = [f'feat_{i}' for i in range(32)]

# Target column
target_col = "PD_Label_Combined"

X = fused_df_named_int[feature_cols].copy()

y = fused_df_named_int[target_col].copy()


# ------------------ Convert X to numeric ------------------

X = X.apply(
    pd.to_numeric,
    errors='coerce'
)

X.fillna(
    0,
    inplace=True
)


# ============================================================
# STEP 2: FIXED TRAIN-TEST SPLIT BY ROW ORDER
# ============================================================

TRAIN_SIZE = 193

# ------------------------------------------------------------
# FIRST 193 ROWS = TRAINING DATA
# ------------------------------------------------------------

X_train = X.iloc[:TRAIN_SIZE].copy()
y_train = y.iloc[:TRAIN_SIZE].copy()


# ------------------------------------------------------------
# REMAINING 127 ROWS = TESTING DATA
# ------------------------------------------------------------

X_test = X.iloc[TRAIN_SIZE:].copy()
y_test = y.iloc[TRAIN_SIZE:].copy()


# ============================================================
# STEP 3: PRINT DATA SHAPES
# ============================================================

print("\n" + "=" * 70)
print("FIXED TRAIN-TEST SPLIT")
print("=" * 70)

print("\nComplete Dataset:")
print("X shape :", X.shape)
print("y shape :", y.shape)

print("\nTraining Data:")
print("X_train shape :", X_train.shape)
print("y_train shape :", y_train.shape)

print("\nTesting Data:")
print("X_test shape  :", X_test.shape)
print("y_test shape  :", y_test.shape)


# ============================================================
# STEP 4: VERIFY CLASS DISTRIBUTIONS
# ============================================================

print("\n" + "=" * 70)
print("CLASS DISTRIBUTION")
print("=" * 70)

print("\nTraining Class Distribution:")
print(
    y_train.value_counts()
    .sort_index()
)

print("\nTesting Class Distribution:")
print(
    y_test.value_counts()
    .sort_index()
)


# ============================================================
# STEP 5: CLASS WEIGHTS
# ============================================================

classes = np.unique(y_train)

class_weights = compute_class_weight(
    class_weight='balanced',
    classes=classes,
    y=y_train
)

class_weights_dict = dict(
    zip(
        classes,
        class_weights
    )
)

print("\n" + "=" * 70)
print("TRAINING CLASS WEIGHTS")
print("=" * 70)

print(class_weights_dict)


# ============================================================
# STEP 6: XGBOOST SCALE_POS_WEIGHT
# ============================================================

negative_count = np.sum(y_train == 0)
positive_count = np.sum(y_train == 1)

if positive_count > 0:
    scale_pos_weight = (
        negative_count / positive_count
    )
else:
    scale_pos_weight = 1.0

print(
    "\nXGBoost scale_pos_weight:",
    scale_pos_weight
)


# ============================================================
# STEP 7: CHECK MISSING VALUES
# ============================================================

print("\n" + "=" * 70)
print("MISSING VALUE CHECK")
print("=" * 70)

print(
    "X_train missing values:",
    X_train.isna().sum().sum()
)

print(
    "X_test missing values :",
    X_test.isna().sum().sum()
)


# ============================================================
# STEP 8: VERIFY EXACT ROW COUNTS
# ============================================================

assert len(X_train) == 193, \
    "Training data must contain exactly 193 rows"

assert len(X_test) == 127, \
    "Testing data must contain exactly 127 rows"

assert len(X_train) + len(X_test) == len(X), \
    "Train + test rows do not equal total dataset rows"


# ============================================================
# STEP 9: VERIFY NO OVERLAP
# ============================================================

train_indices = set(X_train.index)
test_indices = set(X_test.index)

assert len(train_indices.intersection(test_indices)) == 0, \
    "ERROR: Training and testing data overlap!"

print("\n" + "=" * 70)
print("FINAL VERIFICATION")
print("=" * 70)

print("Training rows :", len(X_train))
print("Testing rows  :", len(X_test))
print("Total rows    :", len(X_train) + len(X_test))

print("\nTraining row range:")
print(
    X_train.index[0],
    "to",
    X_train.index[-1]
)

print("\nTesting row range:")
print(
    X_test.index[0],
    "to",
    X_test.index[-1]
)

print("\nNo train-test overlap detected.")
print("Data preparation completed successfully.")

# ============================================================
# STEP 5: BASE MODEL CREATION FUNCTION
# ============================================================

def create_models():

    # ---------------- XGBoost ----------------

    xgb = XGBClassifier(
        n_estimators=200,
        max_depth=4,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,

        scale_pos_weight=scale_pos_weight,

        eval_metric='logloss',

        random_state=42,
        n_jobs=-1
    )


    # ---------------- Random Forest ----------------

    rf = RandomForestClassifier(
        n_estimators=200,

        class_weight='balanced',

        random_state=42,
        n_jobs=-1
    )


    # ---------------- HistGradientBoosting ----------------

    hgb = HistGradientBoostingClassifier(
        max_iter=200,
        learning_rate=0.05,
        max_leaf_nodes=31,

        class_weight='balanced',

        random_state=42
    )


    return xgb, rf, hgb


# ============================================================
# STEP 6: STRATIFIED 10-FOLD CV
# ============================================================

skf = StratifiedKFold(
    n_splits=10,
    shuffle=True,
    random_state=42
)


# ============================================================
# STEP 7: EVALUATION FUNCTION
# ============================================================

def evaluate_model(model_name):

    # ========================================================
    # CV METRIC STORAGE
    # ========================================================

    cv_accuracy = []
    cv_precision = []
    cv_sensitivity = []
    cv_f1 = []
    cv_auc = []
    cv_balanced_accuracy = []


    # ========================================================
    # 10-FOLD STRATIFIED CROSS-VALIDATION
    # ========================================================

    for fold, (train_idx, val_idx) in enumerate(
        skf.split(X_train, y_train),
        start=1
    ):

        print(
            f"\n{model_name} | Fold {fold}/10"
        )


        # ----------------------------------------------------
        # Split fold
        # ----------------------------------------------------

        X_tr = X_train.iloc[
            train_idx
        ]

        X_val = X_train.iloc[
            val_idx
        ]

        y_tr = y_train.iloc[
            train_idx
        ]

        y_val = y_train.iloc[
            val_idx
        ]


        # ----------------------------------------------------
        # Scaling INSIDE EACH FOLD
        # ----------------------------------------------------

        scaler = StandardScaler()

        X_tr_scaled = scaler.fit_transform(
            X_tr
        )

        X_val_scaled = scaler.transform(
            X_val
        )


        # ----------------------------------------------------
        # Create FRESH models for every fold
        # ----------------------------------------------------

        xgb, rf, hgb = create_models()


        # ----------------------------------------------------
        # Select requested model
        # ----------------------------------------------------

        if model_name == "XGBoost":

            model = xgb


        elif model_name == "Random Forest":

            model = rf


        elif model_name == "HistGradientBoosting":

            model = hgb


        elif model_name == "Voting Fusion":

            model = VotingClassifier(
                estimators=[
                    ('xgb', xgb),
                    ('rf', rf),
                    ('hgb', hgb)
                ],
                voting='soft'
            )


        elif model_name == "Stacking Fusion":

            model = StackingClassifier(
                estimators=[
                    ('xgb', xgb),
                    ('rf', rf),
                    ('hgb', hgb)
                ],

                final_estimator=LogisticRegression(
                    max_iter=1000,
                    class_weight='balanced'
                ),

                passthrough=True,

                cv=5
            )


        else:

            raise ValueError(
                f"Unknown model: {model_name}"
            )


        # ----------------------------------------------------
        # Train fold
        # ----------------------------------------------------

        model.fit(
            X_tr_scaled,
            y_tr
        )


        # ----------------------------------------------------
        # Validation predictions
        # ----------------------------------------------------

        val_preds = model.predict(
            X_val_scaled
        )

        val_probs = model.predict_proba(
            X_val_scaled
        )[:, 1]


        # ----------------------------------------------------
        # Fold metrics
        # ----------------------------------------------------

        fold_accuracy = accuracy_score(
            y_val,
            val_preds
        )

        fold_precision = precision_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_sensitivity = recall_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_f1 = f1_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_auc = roc_auc_score(
            y_val,
            val_probs
        )

        fold_balanced_accuracy = balanced_accuracy_score(
            y_val,
            val_preds
        )


        # ----------------------------------------------------
        # Store fold metrics
        # ----------------------------------------------------

        cv_accuracy.append(
            fold_accuracy
        )

        cv_precision.append(
            fold_precision
        )

        cv_sensitivity.append(
            fold_sensitivity
        )

        cv_f1.append(
            fold_f1
        )

        cv_auc.append(
            fold_auc
        )

        cv_balanced_accuracy.append(
            fold_balanced_accuracy
        )


        # ----------------------------------------------------
        # Print fold result
        # ----------------------------------------------------

        print(
            f"Accuracy            : {fold_accuracy:.4f}"
        )

        print(
            f"Precision           : {fold_precision:.4f}"
        )

        print(
            f"Sensitivity         : {fold_sensitivity:.4f}"
        )

        print(
            f"F1 Score            : {fold_f1:.4f}"
        )

        print(
            f"ROC-AUC             : {fold_auc:.4f}"
        )

        print(
            f"Balanced Accuracy   : "
            f"{fold_balanced_accuracy:.4f}"
        )


    # ========================================================
    # CV MEAN RESULTS
    # ========================================================

    cv_accuracy_mean = np.mean(
        cv_accuracy
    )

    cv_precision_mean = np.mean(
        cv_precision
    )

    cv_sensitivity_mean = np.mean(
        cv_sensitivity
    )

    cv_f1_mean = np.mean(
        cv_f1
    )

    cv_auc_mean = np.mean(
        cv_auc
    )

    cv_balanced_accuracy_mean = np.mean(
        cv_balanced_accuracy
    )


    # ========================================================
    # CROSS-VALIDATION RESULTS
    # ========================================================

    print(
        "\n================================================"
    )

    print(
        f"{model_name} - Cross-Validation (10-fold)"
    )

    print(
        "================================================"
    )

    print(
        f"Accuracy            : "
        f"{cv_accuracy_mean:.4f}"
    )

    print(
        f"Precision           : "
        f"{cv_precision_mean:.4f}"
    )

    print(
        f"Recall/Sensitivity  : "
        f"{cv_sensitivity_mean:.4f}"
    )

    print(
        f"F1 Score            : "
        f"{cv_f1_mean:.4f}"
    )

    print(
        f"ROC-AUC             : "
        f"{cv_auc_mean:.4f}"
    )

    print(
        f"Balanced Accuracy   : "
        f"{cv_balanced_accuracy_mean:.4f}"
    )


    # ========================================================
    # TRAIN FINAL MODEL ON COMPLETE TRAINING SET
    # ========================================================

    final_scaler = StandardScaler()

    X_train_final_scaled = final_scaler.fit_transform(
        X_train
    )

    X_test_final_scaled = final_scaler.transform(
        X_test
    )


    # --------------------------------------------------------
    # Create fresh final models
    # --------------------------------------------------------

    xgb, rf, hgb = create_models()


    if model_name == "XGBoost":

        final_model = xgb


    elif model_name == "Random Forest":

        final_model = rf


    elif model_name == "HistGradientBoosting":

        final_model = hgb


    elif model_name == "Voting Fusion":

        final_model = VotingClassifier(
            estimators=[
                ('xgb', xgb),
                ('rf', rf),
                ('hgb', hgb)
            ],
            voting='soft'
        )


    elif model_name == "Stacking Fusion":

        final_model = StackingClassifier(
            estimators=[
                ('xgb', xgb),
                ('rf', rf),
                ('hgb', hgb)
            ],

            final_estimator=LogisticRegression(
                max_iter=1000,
                class_weight='balanced'
            ),

            passthrough=True,

            cv=5
        )


    # ========================================================
    # FINAL TRAINING
    # ========================================================

    final_model.fit(
        X_train_final_scaled,
        y_train
    )


    # ========================================================
    # TEST PREDICTIONS
    # ========================================================

    test_preds = final_model.predict(
        X_test_final_scaled
    )

    test_probs = final_model.predict_proba(
        X_test_final_scaled
    )[:, 1]


    # ========================================================
    # TEST METRICS
    # ========================================================

    accuracy = accuracy_score(
        y_test,
        test_preds
    )

    precision = precision_score(
        y_test,
        test_preds,
        zero_division=0
    )

    sensitivity = recall_score(
        y_test,
        test_preds,
        zero_division=0
    )

    f1 = f1_score(
        y_test,
        test_preds,
        zero_division=0
    )

    roc_auc = roc_auc_score(
        y_test,
        test_probs
    )

    balanced_accuracy = balanced_accuracy_score(
        y_test,
        test_preds
    )

    mcc = matthews_corrcoef(
        y_test,
        test_preds
    )


    # ========================================================
    # CONFUSION MATRIX
    # ========================================================

    cm = confusion_matrix(
        y_test,
        test_preds,
        labels=[0, 1]
    )

    tn, fp, fn, tp = cm.ravel()


    # ========================================================
    # SENSITIVITY / SPECIFICITY
    # ========================================================

    sensitivity = (
        tp / (tp + fn)
        if (tp + fn) > 0
        else 0
    )

    specificity = (
        tn / (tn + fp)
        if (tn + fp) > 0
        else 0
    )


    # ========================================================
    # 95% CONFIDENCE INTERVALS
    # ========================================================

    # ---------------- Accuracy CI ----------------

    acc_low, acc_high = proportion_confint(
        count=int(round(accuracy * len(y_test))),
        nobs=len(y_test),
        alpha=0.05,
        method='wilson'
    )


    # ---------------- Precision CI ----------------

    precision_low, precision_high = proportion_confint(
        count=tp,
        nobs=(tp + fp),
        alpha=0.05,
        method='wilson'
    ) if (tp + fp) > 0 else (0.0, 0.0)


    # ---------------- Sensitivity CI ----------------

    sensitivity_low, sensitivity_high = proportion_confint(
        count=tp,
        nobs=(tp + fn),
        alpha=0.05,
        method='wilson'
    ) if (tp + fn) > 0 else (0.0, 0.0)


    # ---------------- Specificity CI ----------------

    specificity_low, specificity_high = proportion_confint(
        count=tn,
        nobs=(tn + fp),
        alpha=0.05,
        method='wilson'
    ) if (tn + fp) > 0 else (0.0, 0.0)


    # ========================================================
    # TEST SET PERFORMANCE
    # ========================================================

    print(
        "\n================================================"
    )

    print(
        f"{model_name} - Test Set Performance"
    )

    print(
        "================================================"
    )

    print(
        f"Accuracy            : {accuracy:.4f} "
        f"(95% CI: "
        f"{acc_low:.4f}-{acc_high:.4f})"
    )

    print(
        f"Precision           : {precision:.4f} "
        f"(95% CI: "
        f"{precision_low:.4f}-{precision_high:.4f})"
    )

    print(
        f"Sensitivity         : {sensitivity:.4f} "
        f"(95% CI: "
        f"{sensitivity_low:.4f}-{sensitivity_high:.4f})"
    )

    print(
        f"Specificity         : {specificity:.4f} "
        f"(95% CI: "
        f"{specificity_low:.4f}-{specificity_high:.4f})"
    )

    print(
        f"F1 Score            : {f1:.4f}"
    )

    print(
        f"ROC-AUC             : {roc_auc:.4f}"
    )

    print(
        f"Balanced Accuracy   : "
        f"{balanced_accuracy:.4f}"
    )

    print(
        f"MCC                 : {mcc:.4f}"
    )


    # ========================================================
    # CONFUSION MATRIX
    # ========================================================

    print(
        "\nConfusion Matrix:"
    )

    print(cm)

    print(
        "\nTN :", tn
    )

    print(
        "FP :", fp
    )

    print(
        "FN :", fn
    )

    print(
        "TP :", tp
    )


    # ========================================================
    # STORE RESULTS
    # ========================================================

    result = {

        # ---------------- CV ----------------

        "CV Accuracy":
            cv_accuracy_mean,

        "CV Precision":
            cv_precision_mean,

        "CV Sensitivity":
            cv_sensitivity_mean,

        "CV F1":
            cv_f1_mean,

        "CV ROC-AUC":
            cv_auc_mean,

        "CV Balanced Accuracy":
            cv_balanced_accuracy_mean,


        # ---------------- Test ----------------

        "Accuracy":
            accuracy,

        "Accuracy CI Low":
            acc_low,

        "Accuracy CI High":
            acc_high,


        "Precision":
            precision,

        "Precision CI Low":
            precision_low,

        "Precision CI High":
            precision_high,


        "Sensitivity":
            sensitivity,

        "Sensitivity CI Low":
            sensitivity_low,

        "Sensitivity CI High":
            sensitivity_high,


        "Specificity":
            specificity,

        "Specificity CI Low":
            specificity_low,

        "Specificity CI High":
            specificity_high,


        "F1":
            f1,

        "ROC-AUC":
            roc_auc,

        "Balanced Accuracy":
            balanced_accuracy,

        "MCC":
            mcc,


        # ---------------- Confusion Matrix ----------------

        "TN":
            tn,

        "FP":
            fp,

        "FN":
            fn,

        "TP":
            tp
    }


    return result


# ============================================================
# STEP 8: EVALUATE ALL MODELS
# ============================================================

model_names = [
    "XGBoost",
    "Random Forest",
    "HistGradientBoosting",
    "Voting Fusion",
    "Stacking Fusion"
]


results = {}

for name in model_names:

    print(
        "\n\n################################################"
    )

    print(
        f"Evaluating: {name}"
    )

    print(
        "################################################"
    )

    results[name] = evaluate_model(
        name
    )


# ============================================================
# STEP 9: FINAL RESULTS DATAFRAME
# ============================================================

results_df = pd.DataFrame(
    results
).T


# ============================================================
# STEP 10: ORDER RESULTS
# ============================================================

results_df = results_df[
    [

        # ---------------- CV ----------------

        "CV Accuracy",
        "CV Precision",
        "CV Sensitivity",
        "CV F1",
        "CV ROC-AUC",
        "CV Balanced Accuracy",


        # ---------------- Test ----------------

        "Accuracy",
        "Accuracy CI Low",
        "Accuracy CI High",

        "Precision",
        "Precision CI Low",
        "Precision CI High",

        "Sensitivity",
        "Sensitivity CI Low",
        "Sensitivity CI High",

        "Specificity",
        "Specificity CI Low",
        "Specificity CI High",

        "F1",
        "ROC-AUC",
        "Balanced Accuracy",
        "MCC",

        # ---------------- Confusion Matrix ----------------

        "TN",
        "FP",
        "FN",
        "TP"
    ]
]


# ============================================================
# STEP 11: DISPLAY FINAL RESULTS
# ============================================================

print(
    "\n================================================"
)

print(
    "FINAL MODEL COMPARISON"
)

print(
    "================================================\n"
)


display(
    results_df.sort_values(
        by="F1",
        ascending=False
    )
)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 8.6 MB/s eta 0:00:00

======================================================================
FIXED TRAIN-TEST SPLIT
======================================================================

Complete Dataset:
X shape : (320, 32)
y shape : (320,)

Training Data:
X_train shape : (193, 32)
y_train shape : (193,)

Testing Data:
X_test shape  : (127, 32)
y_test shape  : (127,)

======================================================================
CLASS DISTRIBUTION
======================================================================

Training Class Distribution:
PD_Label_Combined
0     66
1    127
Name: count, dtype: int64

Testing Class Distribution:
PD_Label_Combined
0    65
1    62
Name: count, dtype: int64

======================================================================
TRAINING CLASS WEIGHTS
======================================================================
{np.int64(0): np.float64(1.4621212121212122), np.int64(1): np.float64(0.7598425196850394)}

XGBoost scale_pos_weight: 0.5196850393700787

======================================================================
MISSING VALUE CHECK
======================================================================
X_train missing values: 0
X_test missing values : 0

======================================================================
FINAL VERIFICATION
======================================================================
Training rows : 193
Testing rows  : 127
Total rows    : 320

Training row range:
0 to 192

Testing row range:
193 to 319

No train-test overlap detected.
Data preparation completed successfully.


################################################
Evaluating: XGBoost
################################################

XGBoost | Fold 1/10
Accuracy            : 0.8000
Precision           : 0.9091
Sensitivity         : 0.7692
F1 Score            : 0.8333
ROC-AUC             : 0.9670
Balanced Accuracy   : 0.8132

XGBoost | Fold 2/10
Accuracy            : 0.7500
Precision           : 1.0000
Sensitivity         : 0.6154
F1 Score            : 0.7619
ROC-AUC             : 0.9011
Balanced Accuracy   : 0.8077

XGBoost | Fold 3/10
Accuracy            : 0.7000
Precision           : 0.8182
Sensitivity         : 0.6923
F1 Score            : 0.7500
ROC-AUC             : 0.8462
Balanced Accuracy   : 0.7033

XGBoost | Fold 4/10
Accuracy            : 0.7895
Precision           : 0.8462
Sensitivity         : 0.8462
F1 Score            : 0.8462
ROC-AUC             : 0.9487
Balanced Accuracy   : 0.7564

XGBoost | Fold 5/10
Accuracy            : 0.9474
Precision           : 1.0000
Sensitivity         : 0.9231
F1 Score            : 0.9600
ROC-AUC             : 0.9872
Balanced Accuracy   : 0.9615

XGBoost | Fold 6/10
Accuracy            : 0.5789
Precision           : 1.0000
Sensitivity         : 0.3846
F1 Score            : 0.5556
ROC-AUC             : 0.8974
Balanced Accuracy   : 0.6923

XGBoost | Fold 7/10
Accuracy            : 0.8421
Precision           : 0.8125
Sensitivity         : 1.0000
F1 Score            : 0.8966
ROC-AUC             : 0.9872
Balanced Accuracy   : 0.7500

XGBoost | Fold 8/10
Accuracy            : 0.8947
Precision           : 0.8571
Sensitivity         : 1.0000
F1 Score            : 0.9231
ROC-AUC             : 0.9762
Balanced Accuracy   : 0.8571

XGBoost | Fold 9/10
Accuracy            : 0.7368
Precision           : 0.7333
Sensitivity         : 0.9167
F1 Score            : 0.8148
ROC-AUC             : 0.9167
Balanced Accuracy   : 0.6726

XGBoost | Fold 10/10
Accuracy            : 0.8947
Precision           : 0.9167
Sensitivity         : 0.9167
F1 Score            : 0.9167
ROC-AUC             : 0.9524
Balanced Accuracy   : 0.8869

================================================
XGBoost - Cross-Validation (10-fold)
================================================
Accuracy            : 0.7934
Precision           : 0.8893
Recall/Sensitivity  : 0.8064
F1 Score            : 0.8258
ROC-AUC             : 0.9380
Balanced Accuracy   : 0.7901

================================================
XGBoost - Test Set Performance
================================================
Accuracy            : 0.8819 (95% CI: 0.8143-0.9271)
Precision           : 0.9273 (95% CI: 0.8274-0.9714)
Sensitivity         : 0.8226 (95% CI: 0.7096-0.8979)
Specificity         : 0.9385 (95% CI: 0.8522-0.9758)
F1 Score            : 0.8718
ROC-AUC             : 0.9630
Balanced Accuracy   : 0.8805
MCC                 : 0.7677

Confusion Matrix:
[[61  4]
 [11 51]]

TN : 61
FP : 4
FN : 11
TP : 51


################################################
Evaluating: Random Forest
################################################

Random Forest | Fold 1/10
Accuracy            : 0.8000
Precision           : 0.9091
Sensitivity         : 0.7692
F1 Score            : 0.8333
ROC-AUC             : 0.9560
Balanced Accuracy   : 0.8132

Random Forest | Fold 2/10
Accuracy            : 0.7500
Precision           : 0.9000
Sensitivity         : 0.6923
F1 Score            : 0.7826
ROC-AUC             : 0.8571
Balanced Accuracy   : 0.7747

Random Forest | Fold 3/10
Accuracy            : 0.7000
Precision           : 0.7692
Sensitivity         : 0.7692
F1 Score            : 0.7692
ROC-AUC             : 0.8132
Balanced Accuracy   : 0.6703

Random Forest | Fold 4/10
Accuracy            : 0.7895
Precision           : 0.8462
Sensitivity         : 0.8462
F1 Score            : 0.8462
ROC-AUC             : 0.9359
Balanced Accuracy   : 0.7564

Random Forest | Fold 5/10
Accuracy            : 0.8947
Precision           : 0.9231
Sensitivity         : 0.9231
F1 Score            : 0.9231
ROC-AUC             : 0.9872
Balanced Accuracy   : 0.8782

Random Forest | Fold 6/10
Accuracy            : 0.6316
Precision           : 1.0000
Sensitivity         : 0.4615
F1 Score            : 0.6316
ROC-AUC             : 0.8846
Balanced Accuracy   : 0.7308

Random Forest | Fold 7/10
Accuracy            : 0.8421
Precision           : 0.8125
Sensitivity         : 1.0000
F1 Score            : 0.8966
ROC-AUC             : 0.9679
Balanced Accuracy   : 0.7500

Random Forest | Fold 8/10
Accuracy            : 0.8947
Precision           : 0.8571
Sensitivity         : 1.0000
F1 Score            : 0.9231
ROC-AUC             : 0.9643
Balanced Accuracy   : 0.8571

Random Forest | Fold 9/10
Accuracy            : 0.7895
Precision           : 0.7500
Sensitivity         : 1.0000
F1 Score            : 0.8571
ROC-AUC             : 0.9286
Balanced Accuracy   : 0.7143

Random Forest | Fold 10/10
Accuracy            : 0.9474
Precision           : 0.9231
Sensitivity         : 1.0000
F1 Score            : 0.9600
ROC-AUC             : 0.9762
Balanced Accuracy   : 0.9286

================================================
Random Forest - Cross-Validation (10-fold)
================================================
Accuracy            : 0.8039
Precision           : 0.8690
Recall/Sensitivity  : 0.8462
F1 Score            : 0.8423
ROC-AUC             : 0.9271
Balanced Accuracy   : 0.7874

================================================
Random Forest - Test Set Performance
================================================
Accuracy            : 0.8898 (95% CI: 0.8235-0.9332)
Precision           : 0.8333 (95% CI: 0.7309-0.9020)
Sensitivity         : 0.9677 (95% CI: 0.8898-0.9911)
Specificity         : 0.8154 (95% CI: 0.7045-0.8911)
F1 Score            : 0.8955
ROC-AUC             : 0.9731
Balanced Accuracy   : 0.8916
MCC                 : 0.7900

Confusion Matrix:
[[53 12]
 [ 2 60]]

TN : 53
FP : 12
FN : 2
TP : 60


################################################
Evaluating: HistGradientBoosting
################################################

HistGradientBoosting | Fold 1/10
Accuracy            : 0.9000
Precision           : 0.9231
Sensitivity         : 0.9231
F1 Score            : 0.9231
ROC-AUC             : 0.9780
Balanced Accuracy   : 0.8901

HistGradientBoosting | Fold 2/10
Accuracy            : 0.8500
Precision           : 1.0000
Sensitivity         : 0.7692
F1 Score            : 0.8696
ROC-AUC             : 0.9560
Balanced Accuracy   : 0.8846

HistGradientBoosting | Fold 3/10
Accuracy            : 0.7500
Precision           : 0.8333
Sensitivity         : 0.7692
F1 Score            : 0.8000
ROC-AUC             : 0.8901
Balanced Accuracy   : 0.7418

HistGradientBoosting | Fold 4/10
Accuracy            : 0.7895
Precision           : 0.8462
Sensitivity         : 0.8462
F1 Score            : 0.8462
ROC-AUC             : 0.9487
Balanced Accuracy   : 0.7564

HistGradientBoosting | Fold 5/10
Accuracy            : 0.9474
Precision           : 1.0000
Sensitivity         : 0.9231
F1 Score            : 0.9600
ROC-AUC             : 1.0000
Balanced Accuracy   : 0.9615

HistGradientBoosting | Fold 6/10
Accuracy            : 0.6316
Precision           : 1.0000
Sensitivity         : 0.4615
F1 Score            : 0.6316
ROC-AUC             : 0.8910
Balanced Accuracy   : 0.7308

HistGradientBoosting | Fold 7/10
Accuracy            : 0.8421
Precision           : 0.8125
Sensitivity         : 1.0000
F1 Score            : 0.8966
ROC-AUC             : 0.9744
Balanced Accuracy   : 0.7500

HistGradientBoosting | Fold 8/10
Accuracy            : 0.8947
Precision           : 0.8571
Sensitivity         : 1.0000
F1 Score            : 0.9231
ROC-AUC             : 0.9643
Balanced Accuracy   : 0.8571

HistGradientBoosting | Fold 9/10
Accuracy            : 0.7895
Precision           : 0.7500
Sensitivity         : 1.0000
F1 Score            : 0.8571
ROC-AUC             : 0.9405
Balanced Accuracy   : 0.7143

HistGradientBoosting | Fold 10/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

================================================
HistGradientBoosting - Cross-Validation (10-fold)
================================================
Accuracy            : 0.8395
Precision           : 0.9022
Recall/Sensitivity  : 0.8692
F1 Score            : 0.8707
ROC-AUC             : 0.9543
Balanced Accuracy   : 0.8287

================================================
HistGradientBoosting - Test Set Performance
================================================
Accuracy            : 0.8583 (95% CI: 0.7871-0.9084)
Precision           : 0.9231 (95% CI: 0.8183-0.9697)
Sensitivity         : 0.7742 (95% CI: 0.6559-0.8604)
Specificity         : 0.9385 (95% CI: 0.8522-0.9758)
F1 Score            : 0.8421
ROC-AUC             : 0.9525
Balanced Accuracy   : 0.8563
MCC                 : 0.7244

Confusion Matrix:
[[61  4]
 [14 48]]

TN : 61
FP : 4
FN : 14
TP : 48


################################################
Evaluating: Voting Fusion
################################################

Voting Fusion | Fold 1/10
Accuracy            : 0.8000
Precision           : 0.9091
Sensitivity         : 0.7692
F1 Score            : 0.8333
ROC-AUC             : 0.9670
Balanced Accuracy   : 0.8132

Voting Fusion | Fold 2/10
Accuracy            : 0.7500
Precision           : 0.9000
Sensitivity         : 0.6923
F1 Score            : 0.7826
ROC-AUC             : 0.9121
Balanced Accuracy   : 0.7747

Voting Fusion | Fold 3/10
Accuracy            : 0.7500
Precision           : 0.8333
Sensitivity         : 0.7692
F1 Score            : 0.8000
ROC-AUC             : 0.8462
Balanced Accuracy   : 0.7418

Voting Fusion | Fold 4/10
Accuracy            : 0.7895
Precision           : 0.8462
Sensitivity         : 0.8462
F1 Score            : 0.8462
ROC-AUC             : 0.9487
Balanced Accuracy   : 0.7564

Voting Fusion | Fold 5/10
Accuracy            : 0.8947
Precision           : 0.9231
Sensitivity         : 0.9231
F1 Score            : 0.9231
ROC-AUC             : 0.9872
Balanced Accuracy   : 0.8782

Voting Fusion | Fold 6/10
Accuracy            : 0.6316
Precision           : 1.0000
Sensitivity         : 0.4615
F1 Score            : 0.6316
ROC-AUC             : 0.8974
Balanced Accuracy   : 0.7308

Voting Fusion | Fold 7/10
Accuracy            : 0.8421
Precision           : 0.8125
Sensitivity         : 1.0000
F1 Score            : 0.8966
ROC-AUC             : 0.9872
Balanced Accuracy   : 0.7500

Voting Fusion | Fold 8/10
Accuracy            : 0.8947
Precision           : 0.8571
Sensitivity         : 1.0000
F1 Score            : 0.9231
ROC-AUC             : 0.9643
Balanced Accuracy   : 0.8571

Voting Fusion | Fold 9/10
Accuracy            : 0.7895
Precision           : 0.7500
Sensitivity         : 1.0000
F1 Score            : 0.8571
ROC-AUC             : 0.9286
Balanced Accuracy   : 0.7143

Voting Fusion | Fold 10/10
Accuracy            : 0.8947
Precision           : 0.9167
Sensitivity         : 0.9167
F1 Score            : 0.9167
ROC-AUC             : 0.9881
Balanced Accuracy   : 0.8869

================================================
Voting Fusion - Cross-Validation (10-fold)
================================================
Accuracy            : 0.8037
Precision           : 0.8748
Recall/Sensitivity  : 0.8378
F1 Score            : 0.8410
ROC-AUC             : 0.9427
Balanced Accuracy   : 0.7903

================================================
Voting Fusion - Test Set Performance
================================================
Accuracy            : 0.8740 (95% CI: 0.8051-0.9209)
Precision           : 0.9259 (95% CI: 0.8245-0.9708)
Sensitivity         : 0.8065 (95% CI: 0.6915-0.8857)
Specificity         : 0.9385 (95% CI: 0.8522-0.9758)
F1 Score            : 0.8621
ROC-AUC             : 0.9635
Balanced Accuracy   : 0.8725
MCC                 : 0.7532

Confusion Matrix:
[[61  4]
 [12 50]]

TN : 61
FP : 4
FN : 12
TP : 50


################################################
Evaluating: Stacking Fusion
################################################

Stacking Fusion | Fold 1/10
Accuracy            : 0.8000
Precision           : 1.0000
Sensitivity         : 0.6923
F1 Score            : 0.8182
ROC-AUC             : 0.9121
Balanced Accuracy   : 0.8462

Stacking Fusion | Fold 2/10
Accuracy            : 0.8500
Precision           : 1.0000
Sensitivity         : 0.7692
F1 Score            : 0.8696
ROC-AUC             : 0.9560
Balanced Accuracy   : 0.8846

Stacking Fusion | Fold 3/10
Accuracy            : 0.9000
Precision           : 1.0000
Sensitivity         : 0.8462
F1 Score            : 0.9167
ROC-AUC             : 0.9560
Balanced Accuracy   : 0.9231

Stacking Fusion | Fold 4/10
Accuracy            : 0.8421
Precision           : 0.9167
Sensitivity         : 0.8462
F1 Score            : 0.8800
ROC-AUC             : 0.9744
Balanced Accuracy   : 0.8397

Stacking Fusion | Fold 5/10
Accuracy            : 0.9474
Precision           : 1.0000
Sensitivity         : 0.9231
F1 Score            : 0.9600
ROC-AUC             : 0.9487
Balanced Accuracy   : 0.9615

Stacking Fusion | Fold 6/10
Accuracy            : 0.7368
Precision           : 1.0000
Sensitivity         : 0.6154
F1 Score            : 0.7619
ROC-AUC             : 0.8974
Balanced Accuracy   : 0.8077

Stacking Fusion | Fold 7/10
Accuracy            : 0.8947
Precision           : 0.9231
Sensitivity         : 0.9231
F1 Score            : 0.9231
ROC-AUC             : 0.9872
Balanced Accuracy   : 0.8782

Stacking Fusion | Fold 8/10
Accuracy            : 0.8947
Precision           : 0.8571
Sensitivity         : 1.0000
F1 Score            : 0.9231
ROC-AUC             : 0.9524
Balanced Accuracy   : 0.8571

Stacking Fusion | Fold 9/10
Accuracy            : 0.8947
Precision           : 0.9167
Sensitivity         : 0.9167
F1 Score            : 0.9167
ROC-AUC             : 0.9167
Balanced Accuracy   : 0.8869

Stacking Fusion | Fold 10/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

================================================
Stacking Fusion - Cross-Validation (10-fold)
================================================
Accuracy            : 0.8761
Precision           : 0.9614
Recall/Sensitivity  : 0.8532
F1 Score            : 0.8969
ROC-AUC             : 0.9501
Balanced Accuracy   : 0.8885

================================================
Stacking Fusion - Test Set Performance
================================================
Accuracy            : 0.8740 (95% CI: 0.8051-0.9209)
Precision           : 0.8966 (95% CI: 0.7921-0.9517)
Sensitivity         : 0.8387 (95% CI: 0.7279-0.9100)
Specificity         : 0.9077 (95% CI: 0.8129-0.9570)
F1 Score            : 0.8667
ROC-AUC             : 0.9553
Balanced Accuracy   : 0.8732
MCC                 : 0.7490

Confusion Matrix:
[[59  6]
 [10 52]]

TN : 59
FP : 6
FN : 10
TP : 52

================================================
FINAL MODEL COMPARISON
================================================

,CV Accuracy,CV Precision,CV Sensitivity,CV F1,CV ROC-AUC,CV Balanced Accuracy,Accuracy,Accuracy CI Low,Accuracy CI High,Precision,...,Specificity CI Low,Specificity CI High,F1,ROC-AUC,Balanced Accuracy,MCC,TN,FP,FN,TP
Random Forest,0.803947,0.869027,0.846154,0.842275,0.927106,0.787363,0.889764,0.823451,0.933190,0.833333,...,0.704460,0.891111,0.895522,0.973077,0.891563,0.790018,53.0,12.0,2.0,60.0
XGBoost,0.793421,0.889307,0.806410,0.825806,0.938004,0.790110,0.881890,0.814252,0.927103,0.927273,...,0.852178,0.975811,0.871795,0.963027,0.880521,0.767739,61.0,4.0,11.0,51.0
Stacking Fusion,0.876053,0.961355,0.853205,0.896914,0.950092,0.888507,0.874016,0.805126,0.920944,0.896552,...,0.812880,0.957005,0.866667,0.955335,0.873201,0.749009,59.0,6.0,10.0,52.0
Voting Fusion,0.803684,0.874796,0.837821,0.841019,0.942674,0.790339,0.874016,0.805126,0.920944,0.925926,...,0.852178,0.975811,0.862069,0.963524,0.872457,0.753182,61.0,4.0,12.0,50.0
HistGradientBoosting,0.839474,0.902221,0.869231,0.870715,0.954304,0.828663,0.858268,0.787069,0.908429,0.923077,...,0.852178,0.975811,0.842105,0.952481,0.856328,0.724435,61.0,4.0,14.0,48.0

Testing on acoustic

In [ ]:
# ============================================================
# ###8)###
# ENSEMBLE CLASSIFICATION WITH STRATIFIED 10-FOLD CV
# ============================================================

# ------------------ Install Required Packages ------------------

!pip install xgboost lightgbm catboost scikit-learn statsmodels matplotlib seaborn --quiet


# ------------------ Imports ------------------

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.utils.class_weight import compute_class_weight

from sklearn.model_selection import (
    train_test_split,
    StratifiedKFold
)

from sklearn.preprocessing import StandardScaler

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    balanced_accuracy_score,
    matthews_corrcoef,
    confusion_matrix
)

from sklearn.ensemble import (
    VotingClassifier,
    StackingClassifier,
    RandomForestClassifier,
    HistGradientBoostingClassifier
)

from sklearn.linear_model import LogisticRegression

from xgboost import XGBClassifier

from statsmodels.stats.proportion import proportion_confint



# ============================================================
# STEP 1: PREPARE DATA
# ============================================================

feature_cols = [f'feat_{i}' for i in range(32)]
target_col = "PD_Label_Combined"

X = fused_df_named_int[feature_cols].copy()
y = fused_df_named_int[target_col].copy()


# ------------------ Convert X to numeric ------------------

X = X.apply(
    pd.to_numeric,
    errors='coerce'
)

X.fillna(
    0,
    inplace=True
)


# ============================================================
# STEP 2: FIXED TRAIN-TEST SPLIT BY ROW ORDER
# ============================================================

TEST_SIZE = 193

# ------------------------------------------------------------
# FIRST 193 ROWS = TESTING DATA
# ------------------------------------------------------------

X_test = X.iloc[:TEST_SIZE].copy()
y_test = y.iloc[:TEST_SIZE].copy()


# ------------------------------------------------------------
# REMAINING 127 ROWS = TRAINING DATA
# ------------------------------------------------------------

X_train = X.iloc[TEST_SIZE:].copy()
y_train = y.iloc[TEST_SIZE:].copy()


# ============================================================
# STEP 3: PRINT DATA SHAPES
# ============================================================

print("\n" + "=" * 70)
print("FIXED TRAIN-TEST SPLIT")
print("=" * 70)

print("\nComplete Dataset:")
print("X shape :", X.shape)
print("y shape :", y.shape)

print("\nTraining Data:")
print("X_train shape :", X_train.shape)
print("y_train shape :", y_train.shape)

print("\nTesting Data:")
print("X_test shape  :", X_test.shape)
print("y_test shape  :", y_test.shape)


# ============================================================
# STEP 4: CLASS DISTRIBUTION
# ============================================================

print("\n" + "=" * 70)
print("CLASS DISTRIBUTION")
print("=" * 70)

print("\nTraining Class Distribution:")
print(
    y_train.value_counts()
    .sort_index()
)

print("\nTesting Class Distribution:")
print(
    y_test.value_counts()
    .sort_index()
)


# ============================================================
# STEP 5: CLASS WEIGHTS
# ============================================================

classes = np.unique(y_train)

class_weights = compute_class_weight(
    class_weight='balanced',
    classes=classes,
    y=y_train
)

class_weights_dict = dict(
    zip(
        classes,
        class_weights
    )
)

print("\n" + "=" * 70)
print("TRAINING CLASS WEIGHTS")
print("=" * 70)

print(class_weights_dict)


# ============================================================
# STEP 6: XGBOOST SCALE_POS_WEIGHT
# ============================================================

negative_count = np.sum(y_train == 0)
positive_count = np.sum(y_train == 1)

if positive_count > 0:
    scale_pos_weight = (
        negative_count / positive_count
    )
else:
    scale_pos_weight = 1.0

print(
    "\nXGBoost scale_pos_weight:",
    scale_pos_weight
)


# ============================================================
# STEP 7: CHECK MISSING VALUES
# ============================================================

print("\n" + "=" * 70)
print("MISSING VALUE CHECK")
print("=" * 70)

print(
    "X_train missing values:",
    X_train.isna().sum().sum()
)

print(
    "X_test missing values :",
    X_test.isna().sum().sum()
)


# ============================================================
# STEP 8: VERIFY EXACT ROW COUNTS
# ============================================================

assert len(X_train) == 127, \
    "Training data must contain exactly 127 rows"

assert len(X_test) == 193, \
    "Testing data must contain exactly 193 rows"

assert len(X_train) + len(X_test) == len(X), \
    "Train + test rows do not equal total dataset rows"


# ============================================================
# STEP 9: VERIFY NO OVERLAP
# ============================================================

train_indices = set(X_train.index)
test_indices = set(X_test.index)

assert len(
    train_indices.intersection(test_indices)
) == 0, \
    "ERROR: Training and testing data overlap!"


# ============================================================
# STEP 10: FINAL VERIFICATION
# ============================================================

print("\n" + "=" * 70)
print("FINAL VERIFICATION")
print("=" * 70)

print("Training rows :", len(X_train))
print("Testing rows  :", len(X_test))
print("Total rows    :", len(X_train) + len(X_test))

print("\nTesting row range:")
print(
    X_test.index[0],
    "to",
    X_test.index[-1]
)

print("\nTraining row range:")
print(
    X_train.index[0],
    "to",
    X_train.index[-1]
)

print("\nNo train-test overlap detected.")
print("Data preparation completed successfully.")

# ============================================================
# STEP 5: BASE MODEL CREATION FUNCTION
# ============================================================

def create_models():

    # ---------------- XGBoost ----------------

    xgb = XGBClassifier(
        n_estimators=200,
        max_depth=4,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,

        scale_pos_weight=scale_pos_weight,

        eval_metric='logloss',

        random_state=42,
        n_jobs=-1
    )


    # ---------------- Random Forest ----------------

    rf = RandomForestClassifier(
        n_estimators=200,

        class_weight='balanced',

        random_state=42,
        n_jobs=-1
    )


    # ---------------- HistGradientBoosting ----------------

    hgb = HistGradientBoostingClassifier(
        max_iter=200,
        learning_rate=0.05,
        max_leaf_nodes=31,

        class_weight='balanced',

        random_state=42
    )


    return xgb, rf, hgb


# ============================================================
# STEP 6: STRATIFIED 10-FOLD CV
# ============================================================

skf = StratifiedKFold(
    n_splits=10,
    shuffle=True,
    random_state=42
)


# ============================================================
# STEP 7: EVALUATION FUNCTION
# ============================================================

def evaluate_model(model_name):

    # ========================================================
    # CV METRIC STORAGE
    # ========================================================

    cv_accuracy = []
    cv_precision = []
    cv_sensitivity = []
    cv_f1 = []
    cv_auc = []
    cv_balanced_accuracy = []


    # ========================================================
    # 10-FOLD STRATIFIED CROSS-VALIDATION
    # ========================================================

    for fold, (train_idx, val_idx) in enumerate(
        skf.split(X_train, y_train),
        start=1
    ):

        print(
            f"\n{model_name} | Fold {fold}/10"
        )


        # ----------------------------------------------------
        # Split fold
        # ----------------------------------------------------

        X_tr = X_train.iloc[
            train_idx
        ]

        X_val = X_train.iloc[
            val_idx
        ]

        y_tr = y_train.iloc[
            train_idx
        ]

        y_val = y_train.iloc[
            val_idx
        ]


        # ----------------------------------------------------
        # Scaling INSIDE EACH FOLD
        # ----------------------------------------------------

        scaler = StandardScaler()

        X_tr_scaled = scaler.fit_transform(
            X_tr
        )

        X_val_scaled = scaler.transform(
            X_val
        )


        # ----------------------------------------------------
        # Create FRESH models for every fold
        # ----------------------------------------------------

        xgb, rf, hgb = create_models()


        # ----------------------------------------------------
        # Select requested model
        # ----------------------------------------------------

        if model_name == "XGBoost":

            model = xgb


        elif model_name == "Random Forest":

            model = rf


        elif model_name == "HistGradientBoosting":

            model = hgb


        elif model_name == "Voting Fusion":

            model = VotingClassifier(
                estimators=[
                    ('xgb', xgb),
                    ('rf', rf),
                    ('hgb', hgb)
                ],
                voting='soft'
            )


        elif model_name == "Stacking Fusion":

            model = StackingClassifier(
                estimators=[
                    ('xgb', xgb),
                    ('rf', rf),
                    ('hgb', hgb)
                ],

                final_estimator=LogisticRegression(
                    max_iter=1000,
                    class_weight='balanced'
                ),

                passthrough=True,

                cv=5
            )


        else:

            raise ValueError(
                f"Unknown model: {model_name}"
            )


        # ----------------------------------------------------
        # Train fold
        # ----------------------------------------------------

        model.fit(
            X_tr_scaled,
            y_tr
        )


        # ----------------------------------------------------
        # Validation predictions
        # ----------------------------------------------------

        val_preds = model.predict(
            X_val_scaled
        )

        val_probs = model.predict_proba(
            X_val_scaled
        )[:, 1]


        # ----------------------------------------------------
        # Fold metrics
        # ----------------------------------------------------

        fold_accuracy = accuracy_score(
            y_val,
            val_preds
        )

        fold_precision = precision_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_sensitivity = recall_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_f1 = f1_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_auc = roc_auc_score(
            y_val,
            val_probs
        )

        fold_balanced_accuracy = balanced_accuracy_score(
            y_val,
            val_preds
        )


        # ----------------------------------------------------
        # Store fold metrics
        # ----------------------------------------------------

        cv_accuracy.append(
            fold_accuracy
        )

        cv_precision.append(
            fold_precision
        )

        cv_sensitivity.append(
            fold_sensitivity
        )

        cv_f1.append(
            fold_f1
        )

        cv_auc.append(
            fold_auc
        )

        cv_balanced_accuracy.append(
            fold_balanced_accuracy
        )


        # ----------------------------------------------------
        # Print fold result
        # ----------------------------------------------------

        print(
            f"Accuracy            : {fold_accuracy:.4f}"
        )

        print(
            f"Precision           : {fold_precision:.4f}"
        )

        print(
            f"Sensitivity         : {fold_sensitivity:.4f}"
        )

        print(
            f"F1 Score            : {fold_f1:.4f}"
        )

        print(
            f"ROC-AUC             : {fold_auc:.4f}"
        )

        print(
            f"Balanced Accuracy   : "
            f"{fold_balanced_accuracy:.4f}"
        )


    # ========================================================
    # CV MEAN RESULTS
    # ========================================================

    cv_accuracy_mean = np.mean(
        cv_accuracy
    )

    cv_precision_mean = np.mean(
        cv_precision
    )

    cv_sensitivity_mean = np.mean(
        cv_sensitivity
    )

    cv_f1_mean = np.mean(
        cv_f1
    )

    cv_auc_mean = np.mean(
        cv_auc
    )

    cv_balanced_accuracy_mean = np.mean(
        cv_balanced_accuracy
    )


    # ========================================================
    # CROSS-VALIDATION RESULTS
    # ========================================================

    print(
        "\n================================================"
    )

    print(
        f"{model_name} - Cross-Validation (10-fold)"
    )

    print(
        "================================================"
    )

    print(
        f"Accuracy            : "
        f"{cv_accuracy_mean:.4f}"
    )

    print(
        f"Precision           : "
        f"{cv_precision_mean:.4f}"
    )

    print(
        f"Recall/Sensitivity  : "
        f"{cv_sensitivity_mean:.4f}"
    )

    print(
        f"F1 Score            : "
        f"{cv_f1_mean:.4f}"
    )

    print(
        f"ROC-AUC             : "
        f"{cv_auc_mean:.4f}"
    )

    print(
        f"Balanced Accuracy   : "
        f"{cv_balanced_accuracy_mean:.4f}"
    )


    # ========================================================
    # TRAIN FINAL MODEL ON COMPLETE TRAINING SET
    # ========================================================

    final_scaler = StandardScaler()

    X_train_final_scaled = final_scaler.fit_transform(
        X_train
    )

    X_test_final_scaled = final_scaler.transform(
        X_test
    )


    # --------------------------------------------------------
    # Create fresh final models
    # --------------------------------------------------------

    xgb, rf, hgb = create_models()


    if model_name == "XGBoost":

        final_model = xgb


    elif model_name == "Random Forest":

        final_model = rf


    elif model_name == "HistGradientBoosting":

        final_model = hgb


    elif model_name == "Voting Fusion":

        final_model = VotingClassifier(
            estimators=[
                ('xgb', xgb),
                ('rf', rf),
                ('hgb', hgb)
            ],
            voting='soft'
        )


    elif model_name == "Stacking Fusion":

        final_model = StackingClassifier(
            estimators=[
                ('xgb', xgb),
                ('rf', rf),
                ('hgb', hgb)
            ],

            final_estimator=LogisticRegression(
                max_iter=1000,
                class_weight='balanced'
            ),

            passthrough=True,

            cv=5
        )


    # ========================================================
    # FINAL TRAINING
    # ========================================================

    final_model.fit(
        X_train_final_scaled,
        y_train
    )


    # ========================================================
    # TEST PREDICTIONS
    # ========================================================

    test_preds = final_model.predict(
        X_test_final_scaled
    )

    test_probs = final_model.predict_proba(
        X_test_final_scaled
    )[:, 1]


    # ========================================================
    # TEST METRICS
    # ========================================================

    accuracy = accuracy_score(
        y_test,
        test_preds
    )

    precision = precision_score(
        y_test,
        test_preds,
        zero_division=0
    )

    sensitivity = recall_score(
        y_test,
        test_preds,
        zero_division=0
    )

    f1 = f1_score(
        y_test,
        test_preds,
        zero_division=0
    )

    roc_auc = roc_auc_score(
        y_test,
        test_probs
    )

    balanced_accuracy = balanced_accuracy_score(
        y_test,
        test_preds
    )

    mcc = matthews_corrcoef(
        y_test,
        test_preds
    )


    # ========================================================
    # CONFUSION MATRIX
    # ========================================================

    cm = confusion_matrix(
        y_test,
        test_preds,
        labels=[0, 1]
    )

    tn, fp, fn, tp = cm.ravel()


    # ========================================================
    # SENSITIVITY / SPECIFICITY
    # ========================================================

    sensitivity = (
        tp / (tp + fn)
        if (tp + fn) > 0
        else 0
    )

    specificity = (
        tn / (tn + fp)
        if (tn + fp) > 0
        else 0
    )


    # ========================================================
    # 95% CONFIDENCE INTERVALS
    # ========================================================

    # ---------------- Accuracy CI ----------------

    acc_low, acc_high = proportion_confint(
        count=int(round(accuracy * len(y_test))),
        nobs=len(y_test),
        alpha=0.05,
        method='wilson'
    )


    # ---------------- Precision CI ----------------

    precision_low, precision_high = proportion_confint(
        count=tp,
        nobs=(tp + fp),
        alpha=0.05,
        method='wilson'
    ) if (tp + fp) > 0 else (0.0, 0.0)


    # ---------------- Sensitivity CI ----------------

    sensitivity_low, sensitivity_high = proportion_confint(
        count=tp,
        nobs=(tp + fn),
        alpha=0.05,
        method='wilson'
    ) if (tp + fn) > 0 else (0.0, 0.0)


    # ---------------- Specificity CI ----------------

    specificity_low, specificity_high = proportion_confint(
        count=tn,
        nobs=(tn + fp),
        alpha=0.05,
        method='wilson'
    ) if (tn + fp) > 0 else (0.0, 0.0)


    # ========================================================
    # TEST SET PERFORMANCE
    # ========================================================

    print(
        "\n================================================"
    )

    print(
        f"{model_name} - Test Set Performance"
    )

    print(
        "================================================"
    )

    print(
        f"Accuracy            : {accuracy:.4f} "
        f"(95% CI: "
        f"{acc_low:.4f}-{acc_high:.4f})"
    )

    print(
        f"Precision           : {precision:.4f} "
        f"(95% CI: "
        f"{precision_low:.4f}-{precision_high:.4f})"
    )

    print(
        f"Sensitivity         : {sensitivity:.4f} "
        f"(95% CI: "
        f"{sensitivity_low:.4f}-{sensitivity_high:.4f})"
    )

    print(
        f"Specificity         : {specificity:.4f} "
        f"(95% CI: "
        f"{specificity_low:.4f}-{specificity_high:.4f})"
    )

    print(
        f"F1 Score            : {f1:.4f}"
    )

    print(
        f"ROC-AUC             : {roc_auc:.4f}"
    )

    print(
        f"Balanced Accuracy   : "
        f"{balanced_accuracy:.4f}"
    )

    print(
        f"MCC                 : {mcc:.4f}"
    )


    # ========================================================
    # CONFUSION MATRIX
    # ========================================================

    print(
        "\nConfusion Matrix:"
    )

    print(cm)

    print(
        "\nTN :", tn
    )

    print(
        "FP :", fp
    )

    print(
        "FN :", fn
    )

    print(
        "TP :", tp
    )


    # ========================================================
    # STORE RESULTS
    # ========================================================

    result = {

        # ---------------- CV ----------------

        "CV Accuracy":
            cv_accuracy_mean,

        "CV Precision":
            cv_precision_mean,

        "CV Sensitivity":
            cv_sensitivity_mean,

        "CV F1":
            cv_f1_mean,

        "CV ROC-AUC":
            cv_auc_mean,

        "CV Balanced Accuracy":
            cv_balanced_accuracy_mean,


        # ---------------- Test ----------------

        "Accuracy":
            accuracy,

        "Accuracy CI Low":
            acc_low,

        "Accuracy CI High":
            acc_high,


        "Precision":
            precision,

        "Precision CI Low":
            precision_low,

        "Precision CI High":
            precision_high,


        "Sensitivity":
            sensitivity,

        "Sensitivity CI Low":
            sensitivity_low,

        "Sensitivity CI High":
            sensitivity_high,


        "Specificity":
            specificity,

        "Specificity CI Low":
            specificity_low,

        "Specificity CI High":
            specificity_high,


        "F1":
            f1,

        "ROC-AUC":
            roc_auc,

        "Balanced Accuracy":
            balanced_accuracy,

        "MCC":
            mcc,


        # ---------------- Confusion Matrix ----------------

        "TN":
            tn,

        "FP":
            fp,

        "FN":
            fn,

        "TP":
            tp
    }


    return result


# ============================================================
# STEP 8: EVALUATE ALL MODELS
# ============================================================

model_names = [
    "XGBoost",
    "Random Forest",
    "HistGradientBoosting",
    "Voting Fusion",
    "Stacking Fusion"
]


results = {}

for name in model_names:

    print(
        "\n\n################################################"
    )

    print(
        f"Evaluating: {name}"
    )

    print(
        "################################################"
    )

    results[name] = evaluate_model(
        name
    )


# ============================================================
# STEP 9: FINAL RESULTS DATAFRAME
# ============================================================

results_df = pd.DataFrame(
    results
).T


# ============================================================
# STEP 10: ORDER RESULTS
# ============================================================

results_df = results_df[
    [

        # ---------------- CV ----------------

        "CV Accuracy",
        "CV Precision",
        "CV Sensitivity",
        "CV F1",
        "CV ROC-AUC",
        "CV Balanced Accuracy",


        # ---------------- Test ----------------

        "Accuracy",
        "Accuracy CI Low",
        "Accuracy CI High",

        "Precision",
        "Precision CI Low",
        "Precision CI High",

        "Sensitivity",
        "Sensitivity CI Low",
        "Sensitivity CI High",

        "Specificity",
        "Specificity CI Low",
        "Specificity CI High",

        "F1",
        "ROC-AUC",
        "Balanced Accuracy",
        "MCC",

        # ---------------- Confusion Matrix ----------------

        "TN",
        "FP",
        "FN",
        "TP"
    ]
]


# ============================================================
# STEP 11: DISPLAY FINAL RESULTS
# ============================================================

print(
    "\n================================================"
)

print(
    "FINAL MODEL COMPARISON"
)

print(
    "================================================\n"
)


display(
    results_df.sort_values(
        by="F1",
        ascending=False
    )
)

======================================================================
FIXED TRAIN-TEST SPLIT
======================================================================

Complete Dataset:
X shape : (320, 32)
y shape : (320,)

Training Data:
X_train shape : (127, 32)
y_train shape : (127,)

Testing Data:
X_test shape  : (193, 32)
y_test shape  : (193,)

======================================================================
CLASS DISTRIBUTION
======================================================================

Training Class Distribution:
PD_Label_Combined
0    65
1    62
Name: count, dtype: int64

Testing Class Distribution:
PD_Label_Combined
0     66
1    127
Name: count, dtype: int64

======================================================================
TRAINING CLASS WEIGHTS
======================================================================
{np.int64(0): np.float64(0.9769230769230769), np.int64(1): np.float64(1.0241935483870968)}

XGBoost scale_pos_weight: 1.0483870967741935

======================================================================
MISSING VALUE CHECK
======================================================================
X_train missing values: 0
X_test missing values : 0

======================================================================
FINAL VERIFICATION
======================================================================
Training rows : 127
Testing rows  : 193
Total rows    : 320

Testing row range:
0 to 192

Training row range:
193 to 319

No train-test overlap detected.
Data preparation completed successfully.


################################################
Evaluating: XGBoost
################################################

XGBoost | Fold 1/10
Accuracy            : 0.7692
Precision           : 0.8000
Sensitivity         : 0.6667
F1 Score            : 0.7273
ROC-AUC             : 0.9524
Balanced Accuracy   : 0.7619

XGBoost | Fold 2/10
Accuracy            : 0.9231
Precision           : 0.8571
Sensitivity         : 1.0000
F1 Score            : 0.9231
ROC-AUC             : 0.9048
Balanced Accuracy   : 0.9286

XGBoost | Fold 3/10
Accuracy            : 0.9231
Precision           : 0.8571
Sensitivity         : 1.0000
F1 Score            : 0.9231
ROC-AUC             : 1.0000
Balanced Accuracy   : 0.9286

XGBoost | Fold 4/10
Accuracy            : 0.8462
Precision           : 1.0000
Sensitivity         : 0.6667
F1 Score            : 0.8000
ROC-AUC             : 0.9286
Balanced Accuracy   : 0.8333

XGBoost | Fold 5/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

XGBoost | Fold 6/10
Accuracy            : 0.9231
Precision           : 0.8750
Sensitivity         : 1.0000
F1 Score            : 0.9333
ROC-AUC             : 0.9286
Balanced Accuracy   : 0.9167

XGBoost | Fold 7/10
Accuracy            : 0.8462
Precision           : 0.8571
Sensitivity         : 0.8571
F1 Score            : 0.8571
ROC-AUC             : 0.8810
Balanced Accuracy   : 0.8452

XGBoost | Fold 8/10
Accuracy            : 0.8333
Precision           : 0.7500
Sensitivity         : 1.0000
F1 Score            : 0.8571
ROC-AUC             : 0.9444
Balanced Accuracy   : 0.8333

XGBoost | Fold 9/10
Accuracy            : 0.6667
Precision           : 0.7500
Sensitivity         : 0.5000
F1 Score            : 0.6000
ROC-AUC             : 0.6944
Balanced Accuracy   : 0.6667

XGBoost | Fold 10/10
Accuracy            : 0.9167
Precision           : 0.8571
Sensitivity         : 1.0000
F1 Score            : 0.9231
ROC-AUC             : 0.9722
Balanced Accuracy   : 0.9167

================================================
XGBoost - Cross-Validation (10-fold)
================================================
Accuracy            : 0.8647
Precision           : 0.8604
Recall/Sensitivity  : 0.8690
F1 Score            : 0.8544
ROC-AUC             : 0.9206
Balanced Accuracy   : 0.8631

================================================
XGBoost - Test Set Performance
================================================
Accuracy            : 0.8756 (95% CI: 0.8216-0.9150)
Precision           : 0.9187 (95% CI: 0.8568-0.9552)
Sensitivity         : 0.8898 (95% CI: 0.8235-0.9332)
Specificity         : 0.8485 (95% CI: 0.7431-0.9156)
F1 Score            : 0.9040
ROC-AUC             : 0.9471
Balanced Accuracy   : 0.8691
MCC                 : 0.7284

Confusion Matrix:
[[ 56  10]
 [ 14 113]]

TN : 56
FP : 10
FN : 14
TP : 113


################################################
Evaluating: Random Forest
################################################

Random Forest | Fold 1/10
Accuracy            : 0.8462
Precision           : 0.8333
Sensitivity         : 0.8333
F1 Score            : 0.8333
ROC-AUC             : 0.9286
Balanced Accuracy   : 0.8452

Random Forest | Fold 2/10
Accuracy            : 0.9231
Precision           : 0.8571
Sensitivity         : 1.0000
F1 Score            : 0.9231
ROC-AUC             : 0.8810
Balanced Accuracy   : 0.9286

Random Forest | Fold 3/10
Accuracy            : 0.9231
Precision           : 0.8571
Sensitivity         : 1.0000
F1 Score            : 0.9231
ROC-AUC             : 1.0000
Balanced Accuracy   : 0.9286

Random Forest | Fold 4/10
Accuracy            : 0.8462
Precision           : 1.0000
Sensitivity         : 0.6667
F1 Score            : 0.8000
ROC-AUC             : 0.9524
Balanced Accuracy   : 0.8333

Random Forest | Fold 5/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Random Forest | Fold 6/10
Accuracy            : 0.8462
Precision           : 0.7778
Sensitivity         : 1.0000
F1 Score            : 0.8750
ROC-AUC             : 0.9643
Balanced Accuracy   : 0.8333

Random Forest | Fold 7/10
Accuracy            : 0.8462
Precision           : 0.8571
Sensitivity         : 0.8571
F1 Score            : 0.8571
ROC-AUC             : 0.9048
Balanced Accuracy   : 0.8452

Random Forest | Fold 8/10
Accuracy            : 0.8333
Precision           : 0.7500
Sensitivity         : 1.0000
F1 Score            : 0.8571
ROC-AUC             : 0.9583
Balanced Accuracy   : 0.8333

Random Forest | Fold 9/10
Accuracy            : 0.5833
Precision           : 0.6667
Sensitivity         : 0.3333
F1 Score            : 0.4444
ROC-AUC             : 0.6806
Balanced Accuracy   : 0.5833

Random Forest | Fold 10/10
Accuracy            : 0.9167
Precision           : 0.8571
Sensitivity         : 1.0000
F1 Score            : 0.9231
ROC-AUC             : 1.0000
Balanced Accuracy   : 0.9167

================================================
Random Forest - Cross-Validation (10-fold)
================================================
Accuracy            : 0.8564
Precision           : 0.8456
Recall/Sensitivity  : 0.8690
F1 Score            : 0.8436
ROC-AUC             : 0.9270
Balanced Accuracy   : 0.8548

================================================
Random Forest - Test Set Performance
================================================
Accuracy            : 0.8756 (95% CI: 0.8216-0.9150)
Precision           : 0.9402 (95% CI: 0.8816-0.9707)
Sensitivity         : 0.8661 (95% CI: 0.7961-0.9147)
Specificity         : 0.8939 (95% CI: 0.7969-0.9477)
F1 Score            : 0.9016
ROC-AUC             : 0.9540
Balanced Accuracy   : 0.8800
MCC                 : 0.7380

Confusion Matrix:
[[ 59   7]
 [ 17 110]]

TN : 59
FP : 7
FN : 17
TP : 110


################################################
Evaluating: HistGradientBoosting
################################################

HistGradientBoosting | Fold 1/10
Accuracy            : 0.7692
Precision           : 0.8000
Sensitivity         : 0.6667
F1 Score            : 0.7273
ROC-AUC             : 0.9524
Balanced Accuracy   : 0.7619

HistGradientBoosting | Fold 2/10
Accuracy            : 0.9231
Precision           : 0.8571
Sensitivity         : 1.0000
F1 Score            : 0.9231
ROC-AUC             : 0.9048
Balanced Accuracy   : 0.9286

HistGradientBoosting | Fold 3/10
Accuracy            : 0.9231
Precision           : 0.8571
Sensitivity         : 1.0000
F1 Score            : 0.9231
ROC-AUC             : 1.0000
Balanced Accuracy   : 0.9286

HistGradientBoosting | Fold 4/10
Accuracy            : 0.9231
Precision           : 1.0000
Sensitivity         : 0.8333
F1 Score            : 0.9091
ROC-AUC             : 0.9762
Balanced Accuracy   : 0.9167

HistGradientBoosting | Fold 5/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

HistGradientBoosting | Fold 6/10
Accuracy            : 0.9231
Precision           : 0.8750
Sensitivity         : 1.0000
F1 Score            : 0.9333
ROC-AUC             : 0.9286
Balanced Accuracy   : 0.9167

HistGradientBoosting | Fold 7/10
Accuracy            : 0.8462
Precision           : 0.8571
Sensitivity         : 0.8571
F1 Score            : 0.8571
ROC-AUC             : 0.8333
Balanced Accuracy   : 0.8452

HistGradientBoosting | Fold 8/10
Accuracy            : 0.7500
Precision           : 0.6667
Sensitivity         : 1.0000
F1 Score            : 0.8000
ROC-AUC             : 0.9167
Balanced Accuracy   : 0.7500

HistGradientBoosting | Fold 9/10
Accuracy            : 0.5833
Precision           : 0.6000
Sensitivity         : 0.5000
F1 Score            : 0.5455
ROC-AUC             : 0.7222
Balanced Accuracy   : 0.5833

HistGradientBoosting | Fold 10/10
Accuracy            : 0.9167
Precision           : 0.8571
Sensitivity         : 1.0000
F1 Score            : 0.9231
ROC-AUC             : 0.9722
Balanced Accuracy   : 0.9167

================================================
HistGradientBoosting - Cross-Validation (10-fold)
================================================
Accuracy            : 0.8558
Precision           : 0.8370
Recall/Sensitivity  : 0.8857
F1 Score            : 0.8542
ROC-AUC             : 0.9206
Balanced Accuracy   : 0.8548

================================================
HistGradientBoosting - Test Set Performance
================================================
Accuracy            : 0.8808 (95% CI: 0.8275-0.9193)
Precision           : 0.9262 (95% CI: 0.8657-0.9607)
Sensitivity         : 0.8898 (95% CI: 0.8235-0.9332)
Specificity         : 0.8636 (95% CI: 0.7607-0.9266)
F1 Score            : 0.9076
ROC-AUC             : 0.9338
Balanced Accuracy   : 0.8767
MCC                 : 0.7411

Confusion Matrix:
[[ 57   9]
 [ 14 113]]

TN : 57
FP : 9
FN : 14
TP : 113


################################################
Evaluating: Voting Fusion
################################################

Voting Fusion | Fold 1/10
Accuracy            : 0.7692
Precision           : 0.8000
Sensitivity         : 0.6667
F1 Score            : 0.7273
ROC-AUC             : 0.9524
Balanced Accuracy   : 0.7619

Voting Fusion | Fold 2/10
Accuracy            : 0.9231
Precision           : 0.8571
Sensitivity         : 1.0000
F1 Score            : 0.9231
ROC-AUC             : 0.8810
Balanced Accuracy   : 0.9286

Voting Fusion | Fold 3/10
Accuracy            : 0.9231
Precision           : 0.8571
Sensitivity         : 1.0000
F1 Score            : 0.9231
ROC-AUC             : 1.0000
Balanced Accuracy   : 0.9286

Voting Fusion | Fold 4/10
Accuracy            : 0.8462
Precision           : 1.0000
Sensitivity         : 0.6667
F1 Score            : 0.8000
ROC-AUC             : 0.9524
Balanced Accuracy   : 0.8333

Voting Fusion | Fold 5/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Voting Fusion | Fold 6/10
Accuracy            : 0.9231
Precision           : 0.8750
Sensitivity         : 1.0000
F1 Score            : 0.9333
ROC-AUC             : 0.9524
Balanced Accuracy   : 0.9167

Voting Fusion | Fold 7/10
Accuracy            : 0.8462
Precision           : 0.8571
Sensitivity         : 0.8571
F1 Score            : 0.8571
ROC-AUC             : 0.9048
Balanced Accuracy   : 0.8452

Voting Fusion | Fold 8/10
Accuracy            : 0.8333
Precision           : 0.7500
Sensitivity         : 1.0000
F1 Score            : 0.8571
ROC-AUC             : 0.9444
Balanced Accuracy   : 0.8333

Voting Fusion | Fold 9/10
Accuracy            : 0.5833
Precision           : 0.6000
Sensitivity         : 0.5000
F1 Score            : 0.5455
ROC-AUC             : 0.7222
Balanced Accuracy   : 0.5833

Voting Fusion | Fold 10/10
Accuracy            : 0.9167
Precision           : 0.8571
Sensitivity         : 1.0000
F1 Score            : 0.9231
ROC-AUC             : 0.9722
Balanced Accuracy   : 0.9167

================================================
Voting Fusion - Cross-Validation (10-fold)
================================================
Accuracy            : 0.8564
Precision           : 0.8454
Recall/Sensitivity  : 0.8690
F1 Score            : 0.8490
ROC-AUC             : 0.9282
Balanced Accuracy   : 0.8548

================================================
Voting Fusion - Test Set Performance
================================================
Accuracy            : 0.8756 (95% CI: 0.8216-0.9150)
Precision           : 0.9256 (95% CI: 0.8647-0.9604)
Sensitivity         : 0.8819 (95% CI: 0.8143-0.9271)
Specificity         : 0.8636 (95% CI: 0.7607-0.9266)
F1 Score            : 0.9032
ROC-AUC             : 0.9522
Balanced Accuracy   : 0.8728
MCC                 : 0.7313

Confusion Matrix:
[[ 57   9]
 [ 15 112]]

TN : 57
FP : 9
FN : 15
TP : 112


################################################
Evaluating: Stacking Fusion
################################################

Stacking Fusion | Fold 1/10
Accuracy            : 0.9231
Precision           : 0.8571
Sensitivity         : 1.0000
F1 Score            : 0.9231
ROC-AUC             : 0.9524
Balanced Accuracy   : 0.9286

Stacking Fusion | Fold 2/10
Accuracy            : 0.9231
Precision           : 0.8571
Sensitivity         : 1.0000
F1 Score            : 0.9231
ROC-AUC             : 0.9524
Balanced Accuracy   : 0.9286

Stacking Fusion | Fold 3/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Stacking Fusion | Fold 4/10
Accuracy            : 0.8462
Precision           : 1.0000
Sensitivity         : 0.6667
F1 Score            : 0.8000
ROC-AUC             : 0.9762
Balanced Accuracy   : 0.8333

Stacking Fusion | Fold 5/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Stacking Fusion | Fold 6/10
Accuracy            : 0.8462
Precision           : 0.7778
Sensitivity         : 1.0000
F1 Score            : 0.8750
ROC-AUC             : 1.0000
Balanced Accuracy   : 0.8333

Stacking Fusion | Fold 7/10
Accuracy            : 0.8462
Precision           : 0.8571
Sensitivity         : 0.8571
F1 Score            : 0.8571
ROC-AUC             : 0.9524
Balanced Accuracy   : 0.8452

Stacking Fusion | Fold 8/10
Accuracy            : 0.9167
Precision           : 0.8571
Sensitivity         : 1.0000
F1 Score            : 0.9231
ROC-AUC             : 1.0000
Balanced Accuracy   : 0.9167

Stacking Fusion | Fold 9/10
Accuracy            : 0.8333
Precision           : 0.8333
Sensitivity         : 0.8333
F1 Score            : 0.8333
ROC-AUC             : 0.8889
Balanced Accuracy   : 0.8333

Stacking Fusion | Fold 10/10
Accuracy            : 0.9167
Precision           : 0.8571
Sensitivity         : 1.0000
F1 Score            : 0.9231
ROC-AUC             : 1.0000
Balanced Accuracy   : 0.9167

================================================
Stacking Fusion - Cross-Validation (10-fold)
================================================
Accuracy            : 0.9051
Precision           : 0.8897
Recall/Sensitivity  : 0.9357
F1 Score            : 0.9058
ROC-AUC             : 0.9722
Balanced Accuracy   : 0.9036

================================================
Stacking Fusion - Test Set Performance
================================================
Accuracy            : 0.8705 (95% CI: 0.8158-0.9107)
Precision           : 0.9180 (95% CI: 0.8557-0.9549)
Sensitivity         : 0.8819 (95% CI: 0.8143-0.9271)
Specificity         : 0.8485 (95% CI: 0.7431-0.9156)
F1 Score            : 0.8996
ROC-AUC             : 0.9486
Balanced Accuracy   : 0.8652
MCC                 : 0.7185

Confusion Matrix:
[[ 56  10]
 [ 15 112]]

TN : 56
FP : 10
FN : 15
TP : 112

================================================
FINAL MODEL COMPARISON
================================================

,CV Accuracy,CV Precision,CV Sensitivity,CV F1,CV ROC-AUC,CV Balanced Accuracy,Accuracy,Accuracy CI Low,Accuracy CI High,Precision,...,Specificity CI Low,Specificity CI High,F1,ROC-AUC,Balanced Accuracy,MCC,TN,FP,FN,TP
HistGradientBoosting,0.855769,0.837024,0.885714,0.854153,0.920635,0.854762,0.880829,0.827530,0.919264,0.926230,...,0.760704,0.926567,0.907631,0.933846,0.876700,0.741123,57.0,9.0,14.0,113.0
XGBoost,0.864744,0.860357,0.869048,0.854412,0.920635,0.863095,0.875648,0.821640,0.914994,0.918699,...,0.743071,0.915564,0.904000,0.947149,0.869124,0.728408,56.0,10.0,14.0,113.0
Voting Fusion,0.856410,0.845357,0.869048,0.848958,0.928175,0.854762,0.875648,0.821640,0.914994,0.925620,...,0.760704,0.926567,0.903226,0.952159,0.872763,0.731270,57.0,9.0,15.0,112.0
Random Forest,0.856410,0.845635,0.869048,0.843629,0.926984,0.854762,0.875648,0.821640,0.914994,0.940171,...,0.796877,0.947667,0.901639,0.954009,0.880041,0.737962,59.0,7.0,17.0,110.0
Stacking Fusion,0.905128,0.889683,0.935714,0.905778,0.972222,0.903571,0.870466,0.815774,0.910699,0.918033,...,0.743071,0.915564,0.899598,0.948580,0.865187,0.718473,56.0,10.0,15.0,112.0

Go task

In [ ]:
# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
fused_df_named_int = pd.read_csv('/content/drive//MyDrive/Subject-level-fused_fgo_(with_120_epoches)_MIRA-Net_data.csv')
fused_df_named_int.head()

,feat_0,feat_1,feat_2,feat_3,feat_4,feat_5,feat_6,feat_7,feat_8,feat_9,...,feat_23,feat_24,feat_25,feat_26,feat_27,feat_28,feat_29,feat_30,feat_31,PD_Label_Combined
0,-0.018772,0.079011,-0.231570,0.194846,-0.143617,0.085767,-0.046142,-0.231958,-0.040770,-0.062883,...,0.170493,-0.104889,0.186469,-0.094237,0.189094,0.004586,-0.193345,-0.215038,0.252935,1
1,-0.011404,0.079184,-0.230050,0.195819,-0.144949,0.090309,-0.078442,-0.230429,-0.055978,-0.074549,...,0.171172,-0.114990,0.187813,-0.088468,0.175056,0.022514,-0.203139,-0.228855,0.254441,1
2,-0.156525,-0.079700,-0.247852,0.230286,0.047218,-0.055897,0.039394,-0.162000,0.117055,0.098641,...,0.104002,-0.228786,0.166334,0.049440,0.104827,0.228946,-0.098359,-0.275248,0.255883,0
3,-0.027779,0.062175,-0.234910,0.202834,-0.128086,0.089055,-0.048962,-0.232467,-0.043471,-0.053426,...,0.163710,-0.108866,0.190487,-0.085083,0.180007,0.024549,-0.212171,-0.222989,0.252107,1
4,-0.030145,0.064047,-0.234835,0.204415,-0.129516,0.085315,-0.038533,-0.230215,-0.036532,-0.047249,...,0.164248,-0.109925,0.188674,-0.086853,0.184822,0.019620,-0.205970,-0.218949,0.253043,1

In [ ]:
fused_df_named_int.shape

(320, 33)

In [ ]:
# ============================================================
# ###8)###
# ENSEMBLE CLASSIFICATION WITH STRATIFIED 10-FOLD CV
# ============================================================

# ------------------ Install Required Packages ------------------

!pip install xgboost lightgbm catboost scikit-learn statsmodels matplotlib seaborn --quiet


# ------------------ Imports ------------------

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.utils.class_weight import compute_class_weight

from sklearn.model_selection import (
    train_test_split,
    StratifiedKFold
)

from sklearn.preprocessing import StandardScaler

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    balanced_accuracy_score,
    matthews_corrcoef,
    confusion_matrix
)

from sklearn.ensemble import (
    VotingClassifier,
    StackingClassifier,
    RandomForestClassifier,
    HistGradientBoostingClassifier
)

from sklearn.linear_model import LogisticRegression

from xgboost import XGBClassifier

from statsmodels.stats.proportion import proportion_confint



# ============================================================
# STEP 1: PREPARE DATA
# ============================================================

# Feature columns
feature_cols = [f'feat_{i}' for i in range(32)]

# Target column
target_col = "PD_Label_Combined"

X = fused_df_named_int[feature_cols].copy()

y = fused_df_named_int[target_col].copy()


# ------------------ Convert X to numeric ------------------

X = X.apply(
    pd.to_numeric,
    errors='coerce'
)

X.fillna(
    0,
    inplace=True
)


# ============================================================
# STEP 2: FIXED TRAIN-TEST SPLIT BY ROW ORDER
# ============================================================

TRAIN_SIZE = 193

# ------------------------------------------------------------
# FIRST 193 ROWS = TRAINING DATA
# ------------------------------------------------------------

X_train = X.iloc[:TRAIN_SIZE].copy()
y_train = y.iloc[:TRAIN_SIZE].copy()


# ------------------------------------------------------------
# REMAINING 127 ROWS = TESTING DATA
# ------------------------------------------------------------

X_test = X.iloc[TRAIN_SIZE:].copy()
y_test = y.iloc[TRAIN_SIZE:].copy()


# ============================================================
# STEP 3: PRINT DATA SHAPES
# ============================================================

print("\n" + "=" * 70)
print("FIXED TRAIN-TEST SPLIT")
print("=" * 70)

print("\nComplete Dataset:")
print("X shape :", X.shape)
print("y shape :", y.shape)

print("\nTraining Data:")
print("X_train shape :", X_train.shape)
print("y_train shape :", y_train.shape)

print("\nTesting Data:")
print("X_test shape  :", X_test.shape)
print("y_test shape  :", y_test.shape)


# ============================================================
# STEP 4: VERIFY CLASS DISTRIBUTIONS
# ============================================================

print("\n" + "=" * 70)
print("CLASS DISTRIBUTION")
print("=" * 70)

print("\nTraining Class Distribution:")
print(
    y_train.value_counts()
    .sort_index()
)

print("\nTesting Class Distribution:")
print(
    y_test.value_counts()
    .sort_index()
)


# ============================================================
# STEP 5: CLASS WEIGHTS
# ============================================================

classes = np.unique(y_train)

class_weights = compute_class_weight(
    class_weight='balanced',
    classes=classes,
    y=y_train
)

class_weights_dict = dict(
    zip(
        classes,
        class_weights
    )
)

print("\n" + "=" * 70)
print("TRAINING CLASS WEIGHTS")
print("=" * 70)

print(class_weights_dict)


# ============================================================
# STEP 6: XGBOOST SCALE_POS_WEIGHT
# ============================================================

negative_count = np.sum(y_train == 0)
positive_count = np.sum(y_train == 1)

if positive_count > 0:
    scale_pos_weight = (
        negative_count / positive_count
    )
else:
    scale_pos_weight = 1.0

print(
    "\nXGBoost scale_pos_weight:",
    scale_pos_weight
)


# ============================================================
# STEP 7: CHECK MISSING VALUES
# ============================================================

print("\n" + "=" * 70)
print("MISSING VALUE CHECK")
print("=" * 70)

print(
    "X_train missing values:",
    X_train.isna().sum().sum()
)

print(
    "X_test missing values :",
    X_test.isna().sum().sum()
)


# ============================================================
# STEP 8: VERIFY EXACT ROW COUNTS
# ============================================================

assert len(X_train) == 193, \
    "Training data must contain exactly 193 rows"

assert len(X_test) == 127, \
    "Testing data must contain exactly 127 rows"

assert len(X_train) + len(X_test) == len(X), \
    "Train + test rows do not equal total dataset rows"


# ============================================================
# STEP 9: VERIFY NO OVERLAP
# ============================================================

train_indices = set(X_train.index)
test_indices = set(X_test.index)

assert len(train_indices.intersection(test_indices)) == 0, \
    "ERROR: Training and testing data overlap!"

print("\n" + "=" * 70)
print("FINAL VERIFICATION")
print("=" * 70)

print("Training rows :", len(X_train))
print("Testing rows  :", len(X_test))
print("Total rows    :", len(X_train) + len(X_test))

print("\nTraining row range:")
print(
    X_train.index[0],
    "to",
    X_train.index[-1]
)

print("\nTesting row range:")
print(
    X_test.index[0],
    "to",
    X_test.index[-1]
)

print("\nNo train-test overlap detected.")
print("Data preparation completed successfully.")

# ============================================================
# STEP 5: BASE MODEL CREATION FUNCTION
# ============================================================

def create_models():

    # ---------------- XGBoost ----------------

    xgb = XGBClassifier(
        n_estimators=200,
        max_depth=4,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,

        scale_pos_weight=scale_pos_weight,

        eval_metric='logloss',

        random_state=42,
        n_jobs=-1
    )


    # ---------------- Random Forest ----------------

    rf = RandomForestClassifier(
        n_estimators=200,

        class_weight='balanced',

        random_state=42,
        n_jobs=-1
    )


    # ---------------- HistGradientBoosting ----------------

    hgb = HistGradientBoostingClassifier(
        max_iter=200,
        learning_rate=0.05,
        max_leaf_nodes=31,

        class_weight='balanced',

        random_state=42
    )


    return xgb, rf, hgb


# ============================================================
# STEP 6: STRATIFIED 10-FOLD CV
# ============================================================

skf = StratifiedKFold(
    n_splits=10,
    shuffle=True,
    random_state=42
)


# ============================================================
# STEP 7: EVALUATION FUNCTION
# ============================================================

def evaluate_model(model_name):

    # ========================================================
    # CV METRIC STORAGE
    # ========================================================

    cv_accuracy = []
    cv_precision = []
    cv_sensitivity = []
    cv_f1 = []
    cv_auc = []
    cv_balanced_accuracy = []


    # ========================================================
    # 10-FOLD STRATIFIED CROSS-VALIDATION
    # ========================================================

    for fold, (train_idx, val_idx) in enumerate(
        skf.split(X_train, y_train),
        start=1
    ):

        print(
            f"\n{model_name} | Fold {fold}/10"
        )


        # ----------------------------------------------------
        # Split fold
        # ----------------------------------------------------

        X_tr = X_train.iloc[
            train_idx
        ]

        X_val = X_train.iloc[
            val_idx
        ]

        y_tr = y_train.iloc[
            train_idx
        ]

        y_val = y_train.iloc[
            val_idx
        ]


        # ----------------------------------------------------
        # Scaling INSIDE EACH FOLD
        # ----------------------------------------------------

        scaler = StandardScaler()

        X_tr_scaled = scaler.fit_transform(
            X_tr
        )

        X_val_scaled = scaler.transform(
            X_val
        )


        # ----------------------------------------------------
        # Create FRESH models for every fold
        # ----------------------------------------------------

        xgb, rf, hgb = create_models()


        # ----------------------------------------------------
        # Select requested model
        # ----------------------------------------------------

        if model_name == "XGBoost":

            model = xgb


        elif model_name == "Random Forest":

            model = rf


        elif model_name == "HistGradientBoosting":

            model = hgb


        elif model_name == "Voting Fusion":

            model = VotingClassifier(
                estimators=[
                    ('xgb', xgb),
                    ('rf', rf),
                    ('hgb', hgb)
                ],
                voting='soft'
            )


        elif model_name == "Stacking Fusion":

            model = StackingClassifier(
                estimators=[
                    ('xgb', xgb),
                    ('rf', rf),
                    ('hgb', hgb)
                ],

                final_estimator=LogisticRegression(
                    max_iter=1000,
                    class_weight='balanced'
                ),

                passthrough=True,

                cv=5
            )


        else:

            raise ValueError(
                f"Unknown model: {model_name}"
            )


        # ----------------------------------------------------
        # Train fold
        # ----------------------------------------------------

        model.fit(
            X_tr_scaled,
            y_tr
        )


        # ----------------------------------------------------
        # Validation predictions
        # ----------------------------------------------------

        val_preds = model.predict(
            X_val_scaled
        )

        val_probs = model.predict_proba(
            X_val_scaled
        )[:, 1]


        # ----------------------------------------------------
        # Fold metrics
        # ----------------------------------------------------

        fold_accuracy = accuracy_score(
            y_val,
            val_preds
        )

        fold_precision = precision_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_sensitivity = recall_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_f1 = f1_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_auc = roc_auc_score(
            y_val,
            val_probs
        )

        fold_balanced_accuracy = balanced_accuracy_score(
            y_val,
            val_preds
        )


        # ----------------------------------------------------
        # Store fold metrics
        # ----------------------------------------------------

        cv_accuracy.append(
            fold_accuracy
        )

        cv_precision.append(
            fold_precision
        )

        cv_sensitivity.append(
            fold_sensitivity
        )

        cv_f1.append(
            fold_f1
        )

        cv_auc.append(
            fold_auc
        )

        cv_balanced_accuracy.append(
            fold_balanced_accuracy
        )


        # ----------------------------------------------------
        # Print fold result
        # ----------------------------------------------------

        print(
            f"Accuracy            : {fold_accuracy:.4f}"
        )

        print(
            f"Precision           : {fold_precision:.4f}"
        )

        print(
            f"Sensitivity         : {fold_sensitivity:.4f}"
        )

        print(
            f"F1 Score            : {fold_f1:.4f}"
        )

        print(
            f"ROC-AUC             : {fold_auc:.4f}"
        )

        print(
            f"Balanced Accuracy   : "
            f"{fold_balanced_accuracy:.4f}"
        )


    # ========================================================
    # CV MEAN RESULTS
    # ========================================================

    cv_accuracy_mean = np.mean(
        cv_accuracy
    )

    cv_precision_mean = np.mean(
        cv_precision
    )

    cv_sensitivity_mean = np.mean(
        cv_sensitivity
    )

    cv_f1_mean = np.mean(
        cv_f1
    )

    cv_auc_mean = np.mean(
        cv_auc
    )

    cv_balanced_accuracy_mean = np.mean(
        cv_balanced_accuracy
    )


    # ========================================================
    # CROSS-VALIDATION RESULTS
    # ========================================================

    print(
        "\n================================================"
    )

    print(
        f"{model_name} - Cross-Validation (10-fold)"
    )

    print(
        "================================================"
    )

    print(
        f"Accuracy            : "
        f"{cv_accuracy_mean:.4f}"
    )

    print(
        f"Precision           : "
        f"{cv_precision_mean:.4f}"
    )

    print(
        f"Recall/Sensitivity  : "
        f"{cv_sensitivity_mean:.4f}"
    )

    print(
        f"F1 Score            : "
        f"{cv_f1_mean:.4f}"
    )

    print(
        f"ROC-AUC             : "
        f"{cv_auc_mean:.4f}"
    )

    print(
        f"Balanced Accuracy   : "
        f"{cv_balanced_accuracy_mean:.4f}"
    )


    # ========================================================
    # TRAIN FINAL MODEL ON COMPLETE TRAINING SET
    # ========================================================

    final_scaler = StandardScaler()

    X_train_final_scaled = final_scaler.fit_transform(
        X_train
    )

    X_test_final_scaled = final_scaler.transform(
        X_test
    )


    # --------------------------------------------------------
    # Create fresh final models
    # --------------------------------------------------------

    xgb, rf, hgb = create_models()


    if model_name == "XGBoost":

        final_model = xgb


    elif model_name == "Random Forest":

        final_model = rf


    elif model_name == "HistGradientBoosting":

        final_model = hgb


    elif model_name == "Voting Fusion":

        final_model = VotingClassifier(
            estimators=[
                ('xgb', xgb),
                ('rf', rf),
                ('hgb', hgb)
            ],
            voting='soft'
        )


    elif model_name == "Stacking Fusion":

        final_model = StackingClassifier(
            estimators=[
                ('xgb', xgb),
                ('rf', rf),
                ('hgb', hgb)
            ],

            final_estimator=LogisticRegression(
                max_iter=1000,
                class_weight='balanced'
            ),

            passthrough=True,

            cv=5
        )


    # ========================================================
    # FINAL TRAINING
    # ========================================================

    final_model.fit(
        X_train_final_scaled,
        y_train
    )


    # ========================================================
    # TEST PREDICTIONS
    # ========================================================

    test_preds = final_model.predict(
        X_test_final_scaled
    )

    test_probs = final_model.predict_proba(
        X_test_final_scaled
    )[:, 1]


    # ========================================================
    # TEST METRICS
    # ========================================================

    accuracy = accuracy_score(
        y_test,
        test_preds
    )

    precision = precision_score(
        y_test,
        test_preds,
        zero_division=0
    )

    sensitivity = recall_score(
        y_test,
        test_preds,
        zero_division=0
    )

    f1 = f1_score(
        y_test,
        test_preds,
        zero_division=0
    )

    roc_auc = roc_auc_score(
        y_test,
        test_probs
    )

    balanced_accuracy = balanced_accuracy_score(
        y_test,
        test_preds
    )

    mcc = matthews_corrcoef(
        y_test,
        test_preds
    )


    # ========================================================
    # CONFUSION MATRIX
    # ========================================================

    cm = confusion_matrix(
        y_test,
        test_preds,
        labels=[0, 1]
    )

    tn, fp, fn, tp = cm.ravel()


    # ========================================================
    # SENSITIVITY / SPECIFICITY
    # ========================================================

    sensitivity = (
        tp / (tp + fn)
        if (tp + fn) > 0
        else 0
    )

    specificity = (
        tn / (tn + fp)
        if (tn + fp) > 0
        else 0
    )


    # ========================================================
    # 95% CONFIDENCE INTERVALS
    # ========================================================

    # ---------------- Accuracy CI ----------------

    acc_low, acc_high = proportion_confint(
        count=int(round(accuracy * len(y_test))),
        nobs=len(y_test),
        alpha=0.05,
        method='wilson'
    )


    # ---------------- Precision CI ----------------

    precision_low, precision_high = proportion_confint(
        count=tp,
        nobs=(tp + fp),
        alpha=0.05,
        method='wilson'
    ) if (tp + fp) > 0 else (0.0, 0.0)


    # ---------------- Sensitivity CI ----------------

    sensitivity_low, sensitivity_high = proportion_confint(
        count=tp,
        nobs=(tp + fn),
        alpha=0.05,
        method='wilson'
    ) if (tp + fn) > 0 else (0.0, 0.0)


    # ---------------- Specificity CI ----------------

    specificity_low, specificity_high = proportion_confint(
        count=tn,
        nobs=(tn + fp),
        alpha=0.05,
        method='wilson'
    ) if (tn + fp) > 0 else (0.0, 0.0)


    # ========================================================
    # TEST SET PERFORMANCE
    # ========================================================

    print(
        "\n================================================"
    )

    print(
        f"{model_name} - Test Set Performance"
    )

    print(
        "================================================"
    )

    print(
        f"Accuracy            : {accuracy:.4f} "
        f"(95% CI: "
        f"{acc_low:.4f}-{acc_high:.4f})"
    )

    print(
        f"Precision           : {precision:.4f} "
        f"(95% CI: "
        f"{precision_low:.4f}-{precision_high:.4f})"
    )

    print(
        f"Sensitivity         : {sensitivity:.4f} "
        f"(95% CI: "
        f"{sensitivity_low:.4f}-{sensitivity_high:.4f})"
    )

    print(
        f"Specificity         : {specificity:.4f} "
        f"(95% CI: "
        f"{specificity_low:.4f}-{specificity_high:.4f})"
    )

    print(
        f"F1 Score            : {f1:.4f}"
    )

    print(
        f"ROC-AUC             : {roc_auc:.4f}"
    )

    print(
        f"Balanced Accuracy   : "
        f"{balanced_accuracy:.4f}"
    )

    print(
        f"MCC                 : {mcc:.4f}"
    )


    # ========================================================
    # CONFUSION MATRIX
    # ========================================================

    print(
        "\nConfusion Matrix:"
    )

    print(cm)

    print(
        "\nTN :", tn
    )

    print(
        "FP :", fp
    )

    print(
        "FN :", fn
    )

    print(
        "TP :", tp
    )


    # ========================================================
    # STORE RESULTS
    # ========================================================

    result = {

        # ---------------- CV ----------------

        "CV Accuracy":
            cv_accuracy_mean,

        "CV Precision":
            cv_precision_mean,

        "CV Sensitivity":
            cv_sensitivity_mean,

        "CV F1":
            cv_f1_mean,

        "CV ROC-AUC":
            cv_auc_mean,

        "CV Balanced Accuracy":
            cv_balanced_accuracy_mean,


        # ---------------- Test ----------------

        "Accuracy":
            accuracy,

        "Accuracy CI Low":
            acc_low,

        "Accuracy CI High":
            acc_high,


        "Precision":
            precision,

        "Precision CI Low":
            precision_low,

        "Precision CI High":
            precision_high,


        "Sensitivity":
            sensitivity,

        "Sensitivity CI Low":
            sensitivity_low,

        "Sensitivity CI High":
            sensitivity_high,


        "Specificity":
            specificity,

        "Specificity CI Low":
            specificity_low,

        "Specificity CI High":
            specificity_high,


        "F1":
            f1,

        "ROC-AUC":
            roc_auc,

        "Balanced Accuracy":
            balanced_accuracy,

        "MCC":
            mcc,


        # ---------------- Confusion Matrix ----------------

        "TN":
            tn,

        "FP":
            fp,

        "FN":
            fn,

        "TP":
            tp
    }


    return result


# ============================================================
# STEP 8: EVALUATE ALL MODELS
# ============================================================

model_names = [
    "XGBoost",
    "Random Forest",
    "HistGradientBoosting",
    "Voting Fusion",
    "Stacking Fusion"
]


results = {}

for name in model_names:

    print(
        "\n\n################################################"
    )

    print(
        f"Evaluating: {name}"
    )

    print(
        "################################################"
    )

    results[name] = evaluate_model(
        name
    )


# ============================================================
# STEP 9: FINAL RESULTS DATAFRAME
# ============================================================

results_df = pd.DataFrame(
    results
).T


# ============================================================
# STEP 10: ORDER RESULTS
# ============================================================

results_df = results_df[
    [

        # ---------------- CV ----------------

        "CV Accuracy",
        "CV Precision",
        "CV Sensitivity",
        "CV F1",
        "CV ROC-AUC",
        "CV Balanced Accuracy",


        # ---------------- Test ----------------

        "Accuracy",
        "Accuracy CI Low",
        "Accuracy CI High",

        "Precision",
        "Precision CI Low",
        "Precision CI High",

        "Sensitivity",
        "Sensitivity CI Low",
        "Sensitivity CI High",

        "Specificity",
        "Specificity CI Low",
        "Specificity CI High",

        "F1",
        "ROC-AUC",
        "Balanced Accuracy",
        "MCC",

        # ---------------- Confusion Matrix ----------------

        "TN",
        "FP",
        "FN",
        "TP"
    ]
]


# ============================================================
# STEP 11: DISPLAY FINAL RESULTS
# ============================================================

print(
    "\n================================================"
)

print(
    "FINAL MODEL COMPARISON"
)

print(
    "================================================\n"
)


display(
    results_df.sort_values(
        by="F1",
        ascending=False
    )
)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 8.6 MB/s eta 0:00:00

======================================================================
FIXED TRAIN-TEST SPLIT
======================================================================

Complete Dataset:
X shape : (320, 32)
y shape : (320,)

Training Data:
X_train shape : (193, 32)
y_train shape : (193,)

Testing Data:
X_test shape  : (127, 32)
y_test shape  : (127,)

======================================================================
CLASS DISTRIBUTION
======================================================================

Training Class Distribution:
PD_Label_Combined
0     66
1    127
Name: count, dtype: int64

Testing Class Distribution:
PD_Label_Combined
0    65
1    62
Name: count, dtype: int64

======================================================================
TRAINING CLASS WEIGHTS
======================================================================
{np.int64(0): np.float64(1.4621212121212122), np.int64(1): np.float64(0.7598425196850394)}

XGBoost scale_pos_weight: 0.5196850393700787

======================================================================
MISSING VALUE CHECK
======================================================================
X_train missing values: 0
X_test missing values : 0

======================================================================
FINAL VERIFICATION
======================================================================
Training rows : 193
Testing rows  : 127
Total rows    : 320

Training row range:
0 to 192

Testing row range:
193 to 319

No train-test overlap detected.
Data preparation completed successfully.


################################################
Evaluating: XGBoost
################################################

XGBoost | Fold 1/10
Accuracy            : 0.8000
Precision           : 0.9091
Sensitivity         : 0.7692
F1 Score            : 0.8333
ROC-AUC             : 0.8901
Balanced Accuracy   : 0.8132

XGBoost | Fold 2/10
Accuracy            : 0.7500
Precision           : 1.0000
Sensitivity         : 0.6154
F1 Score            : 0.7619
ROC-AUC             : 0.9231
Balanced Accuracy   : 0.8077

XGBoost | Fold 3/10
Accuracy            : 0.8000
Precision           : 0.9091
Sensitivity         : 0.7692
F1 Score            : 0.8333
ROC-AUC             : 0.9341
Balanced Accuracy   : 0.8132

XGBoost | Fold 4/10
Accuracy            : 0.7895
Precision           : 0.8462
Sensitivity         : 0.8462
F1 Score            : 0.8462
ROC-AUC             : 0.9359
Balanced Accuracy   : 0.7564

XGBoost | Fold 5/10
Accuracy            : 0.9474
Precision           : 1.0000
Sensitivity         : 0.9231
F1 Score            : 0.9600
ROC-AUC             : 0.9872
Balanced Accuracy   : 0.9615

XGBoost | Fold 6/10
Accuracy            : 0.7368
Precision           : 1.0000
Sensitivity         : 0.6154
F1 Score            : 0.7619
ROC-AUC             : 0.9295
Balanced Accuracy   : 0.8077

XGBoost | Fold 7/10
Accuracy            : 0.8421
Precision           : 0.8125
Sensitivity         : 1.0000
F1 Score            : 0.8966
ROC-AUC             : 0.9423
Balanced Accuracy   : 0.7500

XGBoost | Fold 8/10
Accuracy            : 0.8947
Precision           : 0.8571
Sensitivity         : 1.0000
F1 Score            : 0.9231
ROC-AUC             : 0.9643
Balanced Accuracy   : 0.8571

XGBoost | Fold 9/10
Accuracy            : 0.8421
Precision           : 0.8462
Sensitivity         : 0.9167
F1 Score            : 0.8800
ROC-AUC             : 0.9405
Balanced Accuracy   : 0.8155

XGBoost | Fold 10/10
Accuracy            : 0.8947
Precision           : 1.0000
Sensitivity         : 0.8333
F1 Score            : 0.9091
ROC-AUC             : 0.9762
Balanced Accuracy   : 0.9167

================================================
XGBoost - Cross-Validation (10-fold)
================================================
Accuracy            : 0.8297
Precision           : 0.9180
Recall/Sensitivity  : 0.8288
F1 Score            : 0.8605
ROC-AUC             : 0.9423
Balanced Accuracy   : 0.8299

================================================
XGBoost - Test Set Performance
================================================
Accuracy            : 0.6457 (95% CI: 0.5593-0.7235)
Precision           : 0.6269 (95% CI: 0.5072-0.7328)
Sensitivity         : 0.6774 (95% CI: 0.5537-0.7805)
Specificity         : 0.6154 (95% CI: 0.4938-0.7240)
F1 Score            : 0.6512
ROC-AUC             : 0.7433
Balanced Accuracy   : 0.6464
MCC                 : 0.2932

Confusion Matrix:
[[40 25]
 [20 42]]

TN : 40
FP : 25
FN : 20
TP : 42


################################################
Evaluating: Random Forest
################################################

Random Forest | Fold 1/10
Accuracy            : 0.8000
Precision           : 0.9091
Sensitivity         : 0.7692
F1 Score            : 0.8333
ROC-AUC             : 0.9011
Balanced Accuracy   : 0.8132

Random Forest | Fold 2/10
Accuracy            : 0.7000
Precision           : 0.8889
Sensitivity         : 0.6154
F1 Score            : 0.7273
ROC-AUC             : 0.8187
Balanced Accuracy   : 0.7363

Random Forest | Fold 3/10
Accuracy            : 0.8500
Precision           : 0.8571
Sensitivity         : 0.9231
F1 Score            : 0.8889
ROC-AUC             : 0.9231
Balanced Accuracy   : 0.8187

Random Forest | Fold 4/10
Accuracy            : 0.8421
Precision           : 0.8571
Sensitivity         : 0.9231
F1 Score            : 0.8889
ROC-AUC             : 0.9359
Balanced Accuracy   : 0.7949

Random Forest | Fold 5/10
Accuracy            : 0.8947
Precision           : 0.9231
Sensitivity         : 0.9231
F1 Score            : 0.9231
ROC-AUC             : 0.9808
Balanced Accuracy   : 0.8782

Random Forest | Fold 6/10
Accuracy            : 0.7368
Precision           : 0.9000
Sensitivity         : 0.6923
F1 Score            : 0.7826
ROC-AUC             : 0.8718
Balanced Accuracy   : 0.7628

Random Forest | Fold 7/10
Accuracy            : 0.8421
Precision           : 0.8125
Sensitivity         : 1.0000
F1 Score            : 0.8966
ROC-AUC             : 0.9615
Balanced Accuracy   : 0.7500

Random Forest | Fold 8/10
Accuracy            : 0.8947
Precision           : 0.8571
Sensitivity         : 1.0000
F1 Score            : 0.9231
ROC-AUC             : 0.8929
Balanced Accuracy   : 0.8571

Random Forest | Fold 9/10
Accuracy            : 0.8421
Precision           : 0.8462
Sensitivity         : 0.9167
F1 Score            : 0.8800
ROC-AUC             : 0.9524
Balanced Accuracy   : 0.8155

Random Forest | Fold 10/10
Accuracy            : 0.8947
Precision           : 1.0000
Sensitivity         : 0.8333
F1 Score            : 0.9091
ROC-AUC             : 1.0000
Balanced Accuracy   : 0.9167

================================================
Random Forest - Cross-Validation (10-fold)
================================================
Accuracy            : 0.8297
Precision           : 0.8851
Recall/Sensitivity  : 0.8596
F1 Score            : 0.8653
ROC-AUC             : 0.9238
Balanced Accuracy   : 0.8143

================================================
Random Forest - Test Set Performance
================================================
Accuracy            : 0.6693 (95% CI: 0.5836-0.7451)
Precision           : 0.6471 (95% CI: 0.5284-0.7500)
Sensitivity         : 0.7097 (95% CI: 0.5871-0.8078)
Specificity         : 0.6308 (95% CI: 0.5092-0.7377)
F1 Score            : 0.6769
ROC-AUC             : 0.7635
Balanced Accuracy   : 0.6702
MCC                 : 0.3412

Confusion Matrix:
[[41 24]
 [18 44]]

TN : 41
FP : 24
FN : 18
TP : 44


################################################
Evaluating: HistGradientBoosting
################################################

HistGradientBoosting | Fold 1/10
Accuracy            : 0.8500
Precision           : 1.0000
Sensitivity         : 0.7692
F1 Score            : 0.8696
ROC-AUC             : 0.8571
Balanced Accuracy   : 0.8846

HistGradientBoosting | Fold 2/10
Accuracy            : 0.7000
Precision           : 0.8889
Sensitivity         : 0.6154
F1 Score            : 0.7273
ROC-AUC             : 0.9121
Balanced Accuracy   : 0.7363

HistGradientBoosting | Fold 3/10
Accuracy            : 0.8000
Precision           : 0.8462
Sensitivity         : 0.8462
F1 Score            : 0.8462
ROC-AUC             : 0.9011
Balanced Accuracy   : 0.7802

HistGradientBoosting | Fold 4/10
Accuracy            : 0.7895
Precision           : 0.8462
Sensitivity         : 0.8462
F1 Score            : 0.8462
ROC-AUC             : 0.9359
Balanced Accuracy   : 0.7564

HistGradientBoosting | Fold 5/10
Accuracy            : 0.8947
Precision           : 0.9231
Sensitivity         : 0.9231
F1 Score            : 0.9231
ROC-AUC             : 0.9872
Balanced Accuracy   : 0.8782

HistGradientBoosting | Fold 6/10
Accuracy            : 0.6842
Precision           : 0.8889
Sensitivity         : 0.6154
F1 Score            : 0.7273
ROC-AUC             : 0.9295
Balanced Accuracy   : 0.7244

HistGradientBoosting | Fold 7/10
Accuracy            : 0.8421
Precision           : 0.8125
Sensitivity         : 1.0000
F1 Score            : 0.8966
ROC-AUC             : 0.9744
Balanced Accuracy   : 0.7500

HistGradientBoosting | Fold 8/10
Accuracy            : 0.8947
Precision           : 0.8571
Sensitivity         : 1.0000
F1 Score            : 0.9231
ROC-AUC             : 0.9643
Balanced Accuracy   : 0.8571

HistGradientBoosting | Fold 9/10
Accuracy            : 0.8421
Precision           : 0.8000
Sensitivity         : 1.0000
F1 Score            : 0.8889
ROC-AUC             : 0.9405
Balanced Accuracy   : 0.7857

HistGradientBoosting | Fold 10/10
Accuracy            : 0.8947
Precision           : 1.0000
Sensitivity         : 0.8333
F1 Score            : 0.9091
ROC-AUC             : 0.9405
Balanced Accuracy   : 0.9167

================================================
HistGradientBoosting - Cross-Validation (10-fold)
================================================
Accuracy            : 0.8192
Precision           : 0.8863
Recall/Sensitivity  : 0.8449
F1 Score            : 0.8557
ROC-AUC             : 0.9342
Balanced Accuracy   : 0.8070

================================================
HistGradientBoosting - Test Set Performance
================================================
Accuracy            : 0.6220 (95% CI: 0.5353-0.7016)
Precision           : 0.5921 (95% CI: 0.4798-0.6956)
Sensitivity         : 0.7258 (95% CI: 0.6041-0.8212)
Specificity         : 0.5231 (95% CI: 0.4038-0.6398)
F1 Score            : 0.6522
ROC-AUC             : 0.7298
Balanced Accuracy   : 0.6244
MCC                 : 0.2538

Confusion Matrix:
[[34 31]
 [17 45]]

TN : 34
FP : 31
FN : 17
TP : 45


################################################
Evaluating: Voting Fusion
################################################

Voting Fusion | Fold 1/10
Accuracy            : 0.8000
Precision           : 0.9091
Sensitivity         : 0.7692
F1 Score            : 0.8333
ROC-AUC             : 0.9231
Balanced Accuracy   : 0.8132

Voting Fusion | Fold 2/10
Accuracy            : 0.7000
Precision           : 0.8889
Sensitivity         : 0.6154
F1 Score            : 0.7273
ROC-AUC             : 0.8571
Balanced Accuracy   : 0.7363

Voting Fusion | Fold 3/10
Accuracy            : 0.8000
Precision           : 0.8462
Sensitivity         : 0.8462
F1 Score            : 0.8462
ROC-AUC             : 0.9231
Balanced Accuracy   : 0.7802

Voting Fusion | Fold 4/10
Accuracy            : 0.7895
Precision           : 0.8462
Sensitivity         : 0.8462
F1 Score            : 0.8462
ROC-AUC             : 0.9359
Balanced Accuracy   : 0.7564

Voting Fusion | Fold 5/10
Accuracy            : 0.8947
Precision           : 0.9231
Sensitivity         : 0.9231
F1 Score            : 0.9231
ROC-AUC             : 0.9872
Balanced Accuracy   : 0.8782

Voting Fusion | Fold 6/10
Accuracy            : 0.6842
Precision           : 1.0000
Sensitivity         : 0.5385
F1 Score            : 0.7000
ROC-AUC             : 0.8974
Balanced Accuracy   : 0.7692

Voting Fusion | Fold 7/10
Accuracy            : 0.8421
Precision           : 0.8125
Sensitivity         : 1.0000
F1 Score            : 0.8966
ROC-AUC             : 0.9744
Balanced Accuracy   : 0.7500

Voting Fusion | Fold 8/10
Accuracy            : 0.8947
Precision           : 0.8571
Sensitivity         : 1.0000
F1 Score            : 0.9231
ROC-AUC             : 0.9524
Balanced Accuracy   : 0.8571

Voting Fusion | Fold 9/10
Accuracy            : 0.7895
Precision           : 0.7857
Sensitivity         : 0.9167
F1 Score            : 0.8462
ROC-AUC             : 0.9405
Balanced Accuracy   : 0.7440

Voting Fusion | Fold 10/10
Accuracy            : 0.8947
Precision           : 1.0000
Sensitivity         : 0.8333
F1 Score            : 0.9091
ROC-AUC             : 0.9762
Balanced Accuracy   : 0.9167

================================================
Voting Fusion - Cross-Validation (10-fold)
================================================
Accuracy            : 0.8089
Precision           : 0.8869
Recall/Sensitivity  : 0.8288
F1 Score            : 0.8451
ROC-AUC             : 0.9367
Balanced Accuracy   : 0.8001

================================================
Voting Fusion - Test Set Performance
================================================
Accuracy            : 0.6457 (95% CI: 0.5593-0.7235)
Precision           : 0.6349 (95% CI: 0.5115-0.7428)
Sensitivity         : 0.6452 (95% CI: 0.5208-0.7526)
Specificity         : 0.6462 (95% CI: 0.5248-0.7512)
F1 Score            : 0.6400
ROC-AUC             : 0.7516
Balanced Accuracy   : 0.6457
MCC                 : 0.2912

Confusion Matrix:
[[42 23]
 [22 40]]

TN : 42
FP : 23
FN : 22
TP : 40


################################################
Evaluating: Stacking Fusion
################################################

Stacking Fusion | Fold 1/10
Accuracy            : 0.8500
Precision           : 1.0000
Sensitivity         : 0.7692
F1 Score            : 0.8696
ROC-AUC             : 0.9121
Balanced Accuracy   : 0.8846

Stacking Fusion | Fold 2/10
Accuracy            : 0.8000
Precision           : 1.0000
Sensitivity         : 0.6923
F1 Score            : 0.8182
ROC-AUC             : 0.9560
Balanced Accuracy   : 0.8462

Stacking Fusion | Fold 3/10
Accuracy            : 0.8500
Precision           : 1.0000
Sensitivity         : 0.7692
F1 Score            : 0.8696
ROC-AUC             : 0.9341
Balanced Accuracy   : 0.8846

Stacking Fusion | Fold 4/10
Accuracy            : 0.8947
Precision           : 1.0000
Sensitivity         : 0.8462
F1 Score            : 0.9167
ROC-AUC             : 0.9744
Balanced Accuracy   : 0.9231

Stacking Fusion | Fold 5/10
Accuracy            : 0.9474
Precision           : 1.0000
Sensitivity         : 0.9231
F1 Score            : 0.9600
ROC-AUC             : 0.9744
Balanced Accuracy   : 0.9615

Stacking Fusion | Fold 6/10
Accuracy            : 0.7895
Precision           : 1.0000
Sensitivity         : 0.6923
F1 Score            : 0.8182
ROC-AUC             : 0.9615
Balanced Accuracy   : 0.8462

Stacking Fusion | Fold 7/10
Accuracy            : 0.8421
Precision           : 0.8125
Sensitivity         : 1.0000
F1 Score            : 0.8966
ROC-AUC             : 0.9872
Balanced Accuracy   : 0.7500

Stacking Fusion | Fold 8/10
Accuracy            : 0.8947
Precision           : 0.8571
Sensitivity         : 1.0000
F1 Score            : 0.9231
ROC-AUC             : 0.9524
Balanced Accuracy   : 0.8571

Stacking Fusion | Fold 9/10
Accuracy            : 0.8947
Precision           : 0.9167
Sensitivity         : 0.9167
F1 Score            : 0.9167
ROC-AUC             : 0.9167
Balanced Accuracy   : 0.8869

Stacking Fusion | Fold 10/10
Accuracy            : 0.9474
Precision           : 1.0000
Sensitivity         : 0.9167
F1 Score            : 0.9565
ROC-AUC             : 0.9762
Balanced Accuracy   : 0.9583

================================================
Stacking Fusion - Cross-Validation (10-fold)
================================================
Accuracy            : 0.8711
Precision           : 0.9586
Recall/Sensitivity  : 0.8526
F1 Score            : 0.8945
ROC-AUC             : 0.9545
Balanced Accuracy   : 0.8799

================================================
Stacking Fusion - Test Set Performance
================================================
Accuracy            : 0.6220 (95% CI: 0.5353-0.7016)
Precision           : 0.6842 (95% CI: 0.5254-0.8092)
Sensitivity         : 0.4194 (95% CI: 0.3048-0.5433)
Specificity         : 0.8154 (95% CI: 0.7045-0.8911)
F1 Score            : 0.5200
ROC-AUC             : 0.7069
Balanced Accuracy   : 0.6174
MCC                 : 0.2562

Confusion Matrix:
[[53 12]
 [36 26]]

TN : 53
FP : 12
FN : 36
TP : 26

================================================
FINAL MODEL COMPARISON
================================================

,CV Accuracy,CV Precision,CV Sensitivity,CV F1,CV ROC-AUC,CV Balanced Accuracy,Accuracy,Accuracy CI Low,Accuracy CI High,Precision,...,Specificity CI Low,Specificity CI High,F1,ROC-AUC,Balanced Accuracy,MCC,TN,FP,FN,TP
Random Forest,0.829737,0.885114,0.859615,0.865279,0.923810,0.814332,0.669291,0.583555,0.745087,0.647059,...,0.509238,0.737706,0.676923,0.763524,0.670223,0.341210,41.0,24.0,18.0,44.0
HistGradientBoosting,0.819211,0.886281,0.844872,0.855710,0.934249,0.806960,0.622047,0.535305,0.701623,0.592105,...,0.403796,0.639782,0.652174,0.729777,0.624442,0.253779,34.0,31.0,17.0,45.0
XGBoost,0.829737,0.918013,0.828846,0.860535,0.942308,0.829899,0.645669,0.559324,0.723461,0.626866,...,0.493842,0.724050,0.651163,0.743300,0.646402,0.293168,40.0,25.0,20.0,42.0
Voting Fusion,0.808947,0.886872,0.828846,0.845086,0.936722,0.800137,0.645669,0.559324,0.723461,0.634921,...,0.524751,0.751245,0.640000,0.751613,0.645658,0.291243,42.0,23.0,22.0,40.0
Stacking Fusion,0.871053,0.958631,0.852564,0.894498,0.954487,0.879853,0.622047,0.535305,0.701623,0.684211,...,0.704460,0.891111,0.520000,0.706948,0.617370,0.256243,53.0,12.0,36.0,26.0

In [ ]:
# ============================================================
# ###8)###
# ENSEMBLE CLASSIFICATION WITH STRATIFIED 10-FOLD CV
# ============================================================

# ------------------ Install Required Packages ------------------

!pip install xgboost lightgbm catboost scikit-learn statsmodels matplotlib seaborn --quiet


# ------------------ Imports ------------------

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.utils.class_weight import compute_class_weight

from sklearn.model_selection import (
    train_test_split,
    StratifiedKFold
)

from sklearn.preprocessing import StandardScaler

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    balanced_accuracy_score,
    matthews_corrcoef,
    confusion_matrix
)

from sklearn.ensemble import (
    VotingClassifier,
    StackingClassifier,
    RandomForestClassifier,
    HistGradientBoostingClassifier
)

from sklearn.linear_model import LogisticRegression

from xgboost import XGBClassifier

from statsmodels.stats.proportion import proportion_confint



# ============================================================
# STEP 1: PREPARE DATA
# ============================================================

feature_cols = [f'feat_{i}' for i in range(32)]
target_col = "PD_Label_Combined"

X = fused_df_named_int[feature_cols].copy()
y = fused_df_named_int[target_col].copy()


# ------------------ Convert X to numeric ------------------

X = X.apply(
    pd.to_numeric,
    errors='coerce'
)

X.fillna(
    0,
    inplace=True
)


# ============================================================
# STEP 2: FIXED TRAIN-TEST SPLIT BY ROW ORDER
# ============================================================

TEST_SIZE = 193

# ------------------------------------------------------------
# FIRST 193 ROWS = TESTING DATA
# ------------------------------------------------------------

X_test = X.iloc[:TEST_SIZE].copy()
y_test = y.iloc[:TEST_SIZE].copy()


# ------------------------------------------------------------
# REMAINING 127 ROWS = TRAINING DATA
# ------------------------------------------------------------

X_train = X.iloc[TEST_SIZE:].copy()
y_train = y.iloc[TEST_SIZE:].copy()


# ============================================================
# STEP 3: PRINT DATA SHAPES
# ============================================================

print("\n" + "=" * 70)
print("FIXED TRAIN-TEST SPLIT")
print("=" * 70)

print("\nComplete Dataset:")
print("X shape :", X.shape)
print("y shape :", y.shape)

print("\nTraining Data:")
print("X_train shape :", X_train.shape)
print("y_train shape :", y_train.shape)

print("\nTesting Data:")
print("X_test shape  :", X_test.shape)
print("y_test shape  :", y_test.shape)


# ============================================================
# STEP 4: CLASS DISTRIBUTION
# ============================================================

print("\n" + "=" * 70)
print("CLASS DISTRIBUTION")
print("=" * 70)

print("\nTraining Class Distribution:")
print(
    y_train.value_counts()
    .sort_index()
)

print("\nTesting Class Distribution:")
print(
    y_test.value_counts()
    .sort_index()
)


# ============================================================
# STEP 5: CLASS WEIGHTS
# ============================================================

classes = np.unique(y_train)

class_weights = compute_class_weight(
    class_weight='balanced',
    classes=classes,
    y=y_train
)

class_weights_dict = dict(
    zip(
        classes,
        class_weights
    )
)

print("\n" + "=" * 70)
print("TRAINING CLASS WEIGHTS")
print("=" * 70)

print(class_weights_dict)


# ============================================================
# STEP 6: XGBOOST SCALE_POS_WEIGHT
# ============================================================

negative_count = np.sum(y_train == 0)
positive_count = np.sum(y_train == 1)

if positive_count > 0:
    scale_pos_weight = (
        negative_count / positive_count
    )
else:
    scale_pos_weight = 1.0

print(
    "\nXGBoost scale_pos_weight:",
    scale_pos_weight
)


# ============================================================
# STEP 7: CHECK MISSING VALUES
# ============================================================

print("\n" + "=" * 70)
print("MISSING VALUE CHECK")
print("=" * 70)

print(
    "X_train missing values:",
    X_train.isna().sum().sum()
)

print(
    "X_test missing values :",
    X_test.isna().sum().sum()
)


# ============================================================
# STEP 8: VERIFY EXACT ROW COUNTS
# ============================================================

assert len(X_train) == 127, \
    "Training data must contain exactly 127 rows"

assert len(X_test) == 193, \
    "Testing data must contain exactly 193 rows"

assert len(X_train) + len(X_test) == len(X), \
    "Train + test rows do not equal total dataset rows"


# ============================================================
# STEP 9: VERIFY NO OVERLAP
# ============================================================

train_indices = set(X_train.index)
test_indices = set(X_test.index)

assert len(
    train_indices.intersection(test_indices)
) == 0, \
    "ERROR: Training and testing data overlap!"


# ============================================================
# STEP 10: FINAL VERIFICATION
# ============================================================

print("\n" + "=" * 70)
print("FINAL VERIFICATION")
print("=" * 70)

print("Training rows :", len(X_train))
print("Testing rows  :", len(X_test))
print("Total rows    :", len(X_train) + len(X_test))

print("\nTesting row range:")
print(
    X_test.index[0],
    "to",
    X_test.index[-1]
)

print("\nTraining row range:")
print(
    X_train.index[0],
    "to",
    X_train.index[-1]
)

print("\nNo train-test overlap detected.")
print("Data preparation completed successfully.")

# ============================================================
# STEP 5: BASE MODEL CREATION FUNCTION
# ============================================================

def create_models():

    # ---------------- XGBoost ----------------

    xgb = XGBClassifier(
        n_estimators=200,
        max_depth=4,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,

        scale_pos_weight=scale_pos_weight,

        eval_metric='logloss',

        random_state=42,
        n_jobs=-1
    )


    # ---------------- Random Forest ----------------

    rf = RandomForestClassifier(
        n_estimators=200,

        class_weight='balanced',

        random_state=42,
        n_jobs=-1
    )


    # ---------------- HistGradientBoosting ----------------

    hgb = HistGradientBoostingClassifier(
        max_iter=200,
        learning_rate=0.05,
        max_leaf_nodes=31,

        class_weight='balanced',

        random_state=42
    )


    return xgb, rf, hgb


# ============================================================
# STEP 6: STRATIFIED 10-FOLD CV
# ============================================================

skf = StratifiedKFold(
    n_splits=10,
    shuffle=True,
    random_state=42
)


# ============================================================
# STEP 7: EVALUATION FUNCTION
# ============================================================

def evaluate_model(model_name):

    # ========================================================
    # CV METRIC STORAGE
    # ========================================================

    cv_accuracy = []
    cv_precision = []
    cv_sensitivity = []
    cv_f1 = []
    cv_auc = []
    cv_balanced_accuracy = []


    # ========================================================
    # 10-FOLD STRATIFIED CROSS-VALIDATION
    # ========================================================

    for fold, (train_idx, val_idx) in enumerate(
        skf.split(X_train, y_train),
        start=1
    ):

        print(
            f"\n{model_name} | Fold {fold}/10"
        )


        # ----------------------------------------------------
        # Split fold
        # ----------------------------------------------------

        X_tr = X_train.iloc[
            train_idx
        ]

        X_val = X_train.iloc[
            val_idx
        ]

        y_tr = y_train.iloc[
            train_idx
        ]

        y_val = y_train.iloc[
            val_idx
        ]


        # ----------------------------------------------------
        # Scaling INSIDE EACH FOLD
        # ----------------------------------------------------

        scaler = StandardScaler()

        X_tr_scaled = scaler.fit_transform(
            X_tr
        )

        X_val_scaled = scaler.transform(
            X_val
        )


        # ----------------------------------------------------
        # Create FRESH models for every fold
        # ----------------------------------------------------

        xgb, rf, hgb = create_models()


        # ----------------------------------------------------
        # Select requested model
        # ----------------------------------------------------

        if model_name == "XGBoost":

            model = xgb


        elif model_name == "Random Forest":

            model = rf


        elif model_name == "HistGradientBoosting":

            model = hgb


        elif model_name == "Voting Fusion":

            model = VotingClassifier(
                estimators=[
                    ('xgb', xgb),
                    ('rf', rf),
                    ('hgb', hgb)
                ],
                voting='soft'
            )


        elif model_name == "Stacking Fusion":

            model = StackingClassifier(
                estimators=[
                    ('xgb', xgb),
                    ('rf', rf),
                    ('hgb', hgb)
                ],

                final_estimator=LogisticRegression(
                    max_iter=1000,
                    class_weight='balanced'
                ),

                passthrough=True,

                cv=5
            )


        else:

            raise ValueError(
                f"Unknown model: {model_name}"
            )


        # ----------------------------------------------------
        # Train fold
        # ----------------------------------------------------

        model.fit(
            X_tr_scaled,
            y_tr
        )


        # ----------------------------------------------------
        # Validation predictions
        # ----------------------------------------------------

        val_preds = model.predict(
            X_val_scaled
        )

        val_probs = model.predict_proba(
            X_val_scaled
        )[:, 1]


        # ----------------------------------------------------
        # Fold metrics
        # ----------------------------------------------------

        fold_accuracy = accuracy_score(
            y_val,
            val_preds
        )

        fold_precision = precision_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_sensitivity = recall_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_f1 = f1_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_auc = roc_auc_score(
            y_val,
            val_probs
        )

        fold_balanced_accuracy = balanced_accuracy_score(
            y_val,
            val_preds
        )


        # ----------------------------------------------------
        # Store fold metrics
        # ----------------------------------------------------

        cv_accuracy.append(
            fold_accuracy
        )

        cv_precision.append(
            fold_precision
        )

        cv_sensitivity.append(
            fold_sensitivity
        )

        cv_f1.append(
            fold_f1
        )

        cv_auc.append(
            fold_auc
        )

        cv_balanced_accuracy.append(
            fold_balanced_accuracy
        )


        # ----------------------------------------------------
        # Print fold result
        # ----------------------------------------------------

        print(
            f"Accuracy            : {fold_accuracy:.4f}"
        )

        print(
            f"Precision           : {fold_precision:.4f}"
        )

        print(
            f"Sensitivity         : {fold_sensitivity:.4f}"
        )

        print(
            f"F1 Score            : {fold_f1:.4f}"
        )

        print(
            f"ROC-AUC             : {fold_auc:.4f}"
        )

        print(
            f"Balanced Accuracy   : "
            f"{fold_balanced_accuracy:.4f}"
        )


    # ========================================================
    # CV MEAN RESULTS
    # ========================================================

    cv_accuracy_mean = np.mean(
        cv_accuracy
    )

    cv_precision_mean = np.mean(
        cv_precision
    )

    cv_sensitivity_mean = np.mean(
        cv_sensitivity
    )

    cv_f1_mean = np.mean(
        cv_f1
    )

    cv_auc_mean = np.mean(
        cv_auc
    )

    cv_balanced_accuracy_mean = np.mean(
        cv_balanced_accuracy
    )


    # ========================================================
    # CROSS-VALIDATION RESULTS
    # ========================================================

    print(
        "\n================================================"
    )

    print(
        f"{model_name} - Cross-Validation (10-fold)"
    )

    print(
        "================================================"
    )

    print(
        f"Accuracy            : "
        f"{cv_accuracy_mean:.4f}"
    )

    print(
        f"Precision           : "
        f"{cv_precision_mean:.4f}"
    )

    print(
        f"Recall/Sensitivity  : "
        f"{cv_sensitivity_mean:.4f}"
    )

    print(
        f"F1 Score            : "
        f"{cv_f1_mean:.4f}"
    )

    print(
        f"ROC-AUC             : "
        f"{cv_auc_mean:.4f}"
    )

    print(
        f"Balanced Accuracy   : "
        f"{cv_balanced_accuracy_mean:.4f}"
    )


    # ========================================================
    # TRAIN FINAL MODEL ON COMPLETE TRAINING SET
    # ========================================================

    final_scaler = StandardScaler()

    X_train_final_scaled = final_scaler.fit_transform(
        X_train
    )

    X_test_final_scaled = final_scaler.transform(
        X_test
    )


    # --------------------------------------------------------
    # Create fresh final models
    # --------------------------------------------------------

    xgb, rf, hgb = create_models()


    if model_name == "XGBoost":

        final_model = xgb


    elif model_name == "Random Forest":

        final_model = rf


    elif model_name == "HistGradientBoosting":

        final_model = hgb


    elif model_name == "Voting Fusion":

        final_model = VotingClassifier(
            estimators=[
                ('xgb', xgb),
                ('rf', rf),
                ('hgb', hgb)
            ],
            voting='soft'
        )


    elif model_name == "Stacking Fusion":

        final_model = StackingClassifier(
            estimators=[
                ('xgb', xgb),
                ('rf', rf),
                ('hgb', hgb)
            ],

            final_estimator=LogisticRegression(
                max_iter=1000,
                class_weight='balanced'
            ),

            passthrough=True,

            cv=5
        )


    # ========================================================
    # FINAL TRAINING
    # ========================================================

    final_model.fit(
        X_train_final_scaled,
        y_train
    )


    # ========================================================
    # TEST PREDICTIONS
    # ========================================================

    test_preds = final_model.predict(
        X_test_final_scaled
    )

    test_probs = final_model.predict_proba(
        X_test_final_scaled
    )[:, 1]


    # ========================================================
    # TEST METRICS
    # ========================================================

    accuracy = accuracy_score(
        y_test,
        test_preds
    )

    precision = precision_score(
        y_test,
        test_preds,
        zero_division=0
    )

    sensitivity = recall_score(
        y_test,
        test_preds,
        zero_division=0
    )

    f1 = f1_score(
        y_test,
        test_preds,
        zero_division=0
    )

    roc_auc = roc_auc_score(
        y_test,
        test_probs
    )

    balanced_accuracy = balanced_accuracy_score(
        y_test,
        test_preds
    )

    mcc = matthews_corrcoef(
        y_test,
        test_preds
    )


    # ========================================================
    # CONFUSION MATRIX
    # ========================================================

    cm = confusion_matrix(
        y_test,
        test_preds,
        labels=[0, 1]
    )

    tn, fp, fn, tp = cm.ravel()


    # ========================================================
    # SENSITIVITY / SPECIFICITY
    # ========================================================

    sensitivity = (
        tp / (tp + fn)
        if (tp + fn) > 0
        else 0
    )

    specificity = (
        tn / (tn + fp)
        if (tn + fp) > 0
        else 0
    )


    # ========================================================
    # 95% CONFIDENCE INTERVALS
    # ========================================================

    # ---------------- Accuracy CI ----------------

    acc_low, acc_high = proportion_confint(
        count=int(round(accuracy * len(y_test))),
        nobs=len(y_test),
        alpha=0.05,
        method='wilson'
    )


    # ---------------- Precision CI ----------------

    precision_low, precision_high = proportion_confint(
        count=tp,
        nobs=(tp + fp),
        alpha=0.05,
        method='wilson'
    ) if (tp + fp) > 0 else (0.0, 0.0)


    # ---------------- Sensitivity CI ----------------

    sensitivity_low, sensitivity_high = proportion_confint(
        count=tp,
        nobs=(tp + fn),
        alpha=0.05,
        method='wilson'
    ) if (tp + fn) > 0 else (0.0, 0.0)


    # ---------------- Specificity CI ----------------

    specificity_low, specificity_high = proportion_confint(
        count=tn,
        nobs=(tn + fp),
        alpha=0.05,
        method='wilson'
    ) if (tn + fp) > 0 else (0.0, 0.0)


    # ========================================================
    # TEST SET PERFORMANCE
    # ========================================================

    print(
        "\n================================================"
    )

    print(
        f"{model_name} - Test Set Performance"
    )

    print(
        "================================================"
    )

    print(
        f"Accuracy            : {accuracy:.4f} "
        f"(95% CI: "
        f"{acc_low:.4f}-{acc_high:.4f})"
    )

    print(
        f"Precision           : {precision:.4f} "
        f"(95% CI: "
        f"{precision_low:.4f}-{precision_high:.4f})"
    )

    print(
        f"Sensitivity         : {sensitivity:.4f} "
        f"(95% CI: "
        f"{sensitivity_low:.4f}-{sensitivity_high:.4f})"
    )

    print(
        f"Specificity         : {specificity:.4f} "
        f"(95% CI: "
        f"{specificity_low:.4f}-{specificity_high:.4f})"
    )

    print(
        f"F1 Score            : {f1:.4f}"
    )

    print(
        f"ROC-AUC             : {roc_auc:.4f}"
    )

    print(
        f"Balanced Accuracy   : "
        f"{balanced_accuracy:.4f}"
    )

    print(
        f"MCC                 : {mcc:.4f}"
    )


    # ========================================================
    # CONFUSION MATRIX
    # ========================================================

    print(
        "\nConfusion Matrix:"
    )

    print(cm)

    print(
        "\nTN :", tn
    )

    print(
        "FP :", fp
    )

    print(
        "FN :", fn
    )

    print(
        "TP :", tp
    )


    # ========================================================
    # STORE RESULTS
    # ========================================================

    result = {

        # ---------------- CV ----------------

        "CV Accuracy":
            cv_accuracy_mean,

        "CV Precision":
            cv_precision_mean,

        "CV Sensitivity":
            cv_sensitivity_mean,

        "CV F1":
            cv_f1_mean,

        "CV ROC-AUC":
            cv_auc_mean,

        "CV Balanced Accuracy":
            cv_balanced_accuracy_mean,


        # ---------------- Test ----------------

        "Accuracy":
            accuracy,

        "Accuracy CI Low":
            acc_low,

        "Accuracy CI High":
            acc_high,


        "Precision":
            precision,

        "Precision CI Low":
            precision_low,

        "Precision CI High":
            precision_high,


        "Sensitivity":
            sensitivity,

        "Sensitivity CI Low":
            sensitivity_low,

        "Sensitivity CI High":
            sensitivity_high,


        "Specificity":
            specificity,

        "Specificity CI Low":
            specificity_low,

        "Specificity CI High":
            specificity_high,


        "F1":
            f1,

        "ROC-AUC":
            roc_auc,

        "Balanced Accuracy":
            balanced_accuracy,

        "MCC":
            mcc,


        # ---------------- Confusion Matrix ----------------

        "TN":
            tn,

        "FP":
            fp,

        "FN":
            fn,

        "TP":
            tp
    }


    return result


# ============================================================
# STEP 8: EVALUATE ALL MODELS
# ============================================================

model_names = [
    "XGBoost",
    "Random Forest",
    "HistGradientBoosting",
    "Voting Fusion",
    "Stacking Fusion"
]


results = {}

for name in model_names:

    print(
        "\n\n################################################"
    )

    print(
        f"Evaluating: {name}"
    )

    print(
        "################################################"
    )

    results[name] = evaluate_model(
        name
    )


# ============================================================
# STEP 9: FINAL RESULTS DATAFRAME
# ============================================================

results_df = pd.DataFrame(
    results
).T


# ============================================================
# STEP 10: ORDER RESULTS
# ============================================================

results_df = results_df[
    [

        # ---------------- CV ----------------

        "CV Accuracy",
        "CV Precision",
        "CV Sensitivity",
        "CV F1",
        "CV ROC-AUC",
        "CV Balanced Accuracy",


        # ---------------- Test ----------------

        "Accuracy",
        "Accuracy CI Low",
        "Accuracy CI High",

        "Precision",
        "Precision CI Low",
        "Precision CI High",

        "Sensitivity",
        "Sensitivity CI Low",
        "Sensitivity CI High",

        "Specificity",
        "Specificity CI Low",
        "Specificity CI High",

        "F1",
        "ROC-AUC",
        "Balanced Accuracy",
        "MCC",

        # ---------------- Confusion Matrix ----------------

        "TN",
        "FP",
        "FN",
        "TP"
    ]
]


# ============================================================
# STEP 11: DISPLAY FINAL RESULTS
# ============================================================

print(
    "\n================================================"
)

print(
    "FINAL MODEL COMPARISON"
)

print(
    "================================================\n"
)


display(
    results_df.sort_values(
        by="F1",
        ascending=False
    )
)

======================================================================
FIXED TRAIN-TEST SPLIT
======================================================================

Complete Dataset:
X shape : (320, 32)
y shape : (320,)

Training Data:
X_train shape : (127, 32)
y_train shape : (127,)

Testing Data:
X_test shape  : (193, 32)
y_test shape  : (193,)

======================================================================
CLASS DISTRIBUTION
======================================================================

Training Class Distribution:
PD_Label_Combined
0    65
1    62
Name: count, dtype: int64

Testing Class Distribution:
PD_Label_Combined
0     66
1    127
Name: count, dtype: int64

======================================================================
TRAINING CLASS WEIGHTS
======================================================================
{np.int64(0): np.float64(0.9769230769230769), np.int64(1): np.float64(1.0241935483870968)}

XGBoost scale_pos_weight: 1.0483870967741935

======================================================================
MISSING VALUE CHECK
======================================================================
X_train missing values: 0
X_test missing values : 0

======================================================================
FINAL VERIFICATION
======================================================================
Training rows : 127
Testing rows  : 193
Total rows    : 320

Testing row range:
0 to 192

Training row range:
193 to 319

No train-test overlap detected.
Data preparation completed successfully.


################################################
Evaluating: XGBoost
################################################

XGBoost | Fold 1/10
Accuracy            : 0.6154
Precision           : 0.6000
Sensitivity         : 0.5000
F1 Score            : 0.5455
ROC-AUC             : 0.6190
Balanced Accuracy   : 0.6071

XGBoost | Fold 2/10
Accuracy            : 0.6923
Precision           : 0.6667
Sensitivity         : 0.6667
F1 Score            : 0.6667
ROC-AUC             : 0.7143
Balanced Accuracy   : 0.6905

XGBoost | Fold 3/10
Accuracy            : 0.6154
Precision           : 0.6000
Sensitivity         : 0.5000
F1 Score            : 0.5455
ROC-AUC             : 0.7381
Balanced Accuracy   : 0.6071

XGBoost | Fold 4/10
Accuracy            : 0.7692
Precision           : 0.8000
Sensitivity         : 0.6667
F1 Score            : 0.7273
ROC-AUC             : 0.8095
Balanced Accuracy   : 0.7619

XGBoost | Fold 5/10
Accuracy            : 0.6154
Precision           : 0.6000
Sensitivity         : 0.5000
F1 Score            : 0.5455
ROC-AUC             : 0.5476
Balanced Accuracy   : 0.6071

XGBoost | Fold 6/10
Accuracy            : 0.6923
Precision           : 0.6667
Sensitivity         : 0.8571
F1 Score            : 0.7500
ROC-AUC             : 0.7143
Balanced Accuracy   : 0.6786

XGBoost | Fold 7/10
Accuracy            : 0.4615
Precision           : 0.5000
Sensitivity         : 0.4286
F1 Score            : 0.4615
ROC-AUC             : 0.4286
Balanced Accuracy   : 0.4643

XGBoost | Fold 8/10
Accuracy            : 0.7500
Precision           : 0.6667
Sensitivity         : 1.0000
F1 Score            : 0.8000
ROC-AUC             : 0.8611
Balanced Accuracy   : 0.7500

XGBoost | Fold 9/10
Accuracy            : 0.6667
Precision           : 0.7500
Sensitivity         : 0.5000
F1 Score            : 0.6000
ROC-AUC             : 0.8611
Balanced Accuracy   : 0.6667

XGBoost | Fold 10/10
Accuracy            : 0.4167
Precision           : 0.4286
Sensitivity         : 0.5000
F1 Score            : 0.4615
ROC-AUC             : 0.5556
Balanced Accuracy   : 0.4167

================================================
XGBoost - Cross-Validation (10-fold)
================================================
Accuracy            : 0.6295
Precision           : 0.6279
Recall/Sensitivity  : 0.6119
F1 Score            : 0.6103
ROC-AUC             : 0.6849
Balanced Accuracy   : 0.6250

================================================
XGBoost - Test Set Performance
================================================
Accuracy            : 0.8653 (95% CI: 0.8099-0.9064)
Precision           : 0.9174 (95% CI: 0.8545-0.9545)
Sensitivity         : 0.8740 (95% CI: 0.8051-0.9209)
Specificity         : 0.8485 (95% CI: 0.7431-0.9156)
F1 Score            : 0.8952
ROC-AUC             : 0.9273
Balanced Accuracy   : 0.8613
MCC                 : 0.7087

Confusion Matrix:
[[ 56  10]
 [ 16 111]]

TN : 56
FP : 10
FN : 16
TP : 111


################################################
Evaluating: Random Forest
################################################

Random Forest | Fold 1/10
Accuracy            : 0.6923
Precision           : 0.7500
Sensitivity         : 0.5000
F1 Score            : 0.6000
ROC-AUC             : 0.6548
Balanced Accuracy   : 0.6786

Random Forest | Fold 2/10
Accuracy            : 0.6923
Precision           : 0.6250
Sensitivity         : 0.8333
F1 Score            : 0.7143
ROC-AUC             : 0.7381
Balanced Accuracy   : 0.7024

Random Forest | Fold 3/10
Accuracy            : 0.5385
Precision           : 0.5000
Sensitivity         : 0.3333
F1 Score            : 0.4000
ROC-AUC             : 0.7381
Balanced Accuracy   : 0.5238

Random Forest | Fold 4/10
Accuracy            : 0.6154
Precision           : 0.6000
Sensitivity         : 0.5000
F1 Score            : 0.5455
ROC-AUC             : 0.7738
Balanced Accuracy   : 0.6071

Random Forest | Fold 5/10
Accuracy            : 0.6154
Precision           : 0.6000
Sensitivity         : 0.5000
F1 Score            : 0.5455
ROC-AUC             : 0.5952
Balanced Accuracy   : 0.6071

Random Forest | Fold 6/10
Accuracy            : 0.6923
Precision           : 0.6667
Sensitivity         : 0.8571
F1 Score            : 0.7500
ROC-AUC             : 0.6905
Balanced Accuracy   : 0.6786

Random Forest | Fold 7/10
Accuracy            : 0.4615
Precision           : 0.5000
Sensitivity         : 0.4286
F1 Score            : 0.4615
ROC-AUC             : 0.5714
Balanced Accuracy   : 0.4643

Random Forest | Fold 8/10
Accuracy            : 0.7500
Precision           : 0.6667
Sensitivity         : 1.0000
F1 Score            : 0.8000
ROC-AUC             : 0.8611
Balanced Accuracy   : 0.7500

Random Forest | Fold 9/10
Accuracy            : 0.6667
Precision           : 0.7500
Sensitivity         : 0.5000
F1 Score            : 0.6000
ROC-AUC             : 0.7778
Balanced Accuracy   : 0.6667

Random Forest | Fold 10/10
Accuracy            : 0.4167
Precision           : 0.4286
Sensitivity         : 0.5000
F1 Score            : 0.4615
ROC-AUC             : 0.5833
Balanced Accuracy   : 0.4167

================================================
Random Forest - Cross-Validation (10-fold)
================================================
Accuracy            : 0.6141
Precision           : 0.6087
Recall/Sensitivity  : 0.5952
F1 Score            : 0.5878
ROC-AUC             : 0.6984
Balanced Accuracy   : 0.6095

================================================
Random Forest - Test Set Performance
================================================
Accuracy            : 0.8653 (95% CI: 0.8099-0.9064)
Precision           : 0.9174 (95% CI: 0.8545-0.9545)
Sensitivity         : 0.8740 (95% CI: 0.8051-0.9209)
Specificity         : 0.8485 (95% CI: 0.7431-0.9156)
F1 Score            : 0.8952
ROC-AUC             : 0.9418
Balanced Accuracy   : 0.8613
MCC                 : 0.7087

Confusion Matrix:
[[ 56  10]
 [ 16 111]]

TN : 56
FP : 10
FN : 16
TP : 111


################################################
Evaluating: HistGradientBoosting
################################################

HistGradientBoosting | Fold 1/10
Accuracy            : 0.6154
Precision           : 0.6000
Sensitivity         : 0.5000
F1 Score            : 0.5455
ROC-AUC             : 0.6429
Balanced Accuracy   : 0.6071

HistGradientBoosting | Fold 2/10
Accuracy            : 0.6154
Precision           : 0.5714
Sensitivity         : 0.6667
F1 Score            : 0.6154
ROC-AUC             : 0.6667
Balanced Accuracy   : 0.6190

HistGradientBoosting | Fold 3/10
Accuracy            : 0.6154
Precision           : 0.6000
Sensitivity         : 0.5000
F1 Score            : 0.5455
ROC-AUC             : 0.8095
Balanced Accuracy   : 0.6071

HistGradientBoosting | Fold 4/10
Accuracy            : 0.7692
Precision           : 0.8000
Sensitivity         : 0.6667
F1 Score            : 0.7273
ROC-AUC             : 0.7619
Balanced Accuracy   : 0.7619

HistGradientBoosting | Fold 5/10
Accuracy            : 0.6154
Precision           : 0.6000
Sensitivity         : 0.5000
F1 Score            : 0.5455
ROC-AUC             : 0.6310
Balanced Accuracy   : 0.6071

HistGradientBoosting | Fold 6/10
Accuracy            : 0.6923
Precision           : 0.6667
Sensitivity         : 0.8571
F1 Score            : 0.7500
ROC-AUC             : 0.7857
Balanced Accuracy   : 0.6786

HistGradientBoosting | Fold 7/10
Accuracy            : 0.5385
Precision           : 0.6000
Sensitivity         : 0.4286
F1 Score            : 0.5000
ROC-AUC             : 0.4524
Balanced Accuracy   : 0.5476

HistGradientBoosting | Fold 8/10
Accuracy            : 0.8333
Precision           : 0.7500
Sensitivity         : 1.0000
F1 Score            : 0.8571
ROC-AUC             : 0.9722
Balanced Accuracy   : 0.8333

HistGradientBoosting | Fold 9/10
Accuracy            : 0.7500
Precision           : 0.8000
Sensitivity         : 0.6667
F1 Score            : 0.7273
ROC-AUC             : 0.8333
Balanced Accuracy   : 0.7500

HistGradientBoosting | Fold 10/10
Accuracy            : 0.4167
Precision           : 0.4286
Sensitivity         : 0.5000
F1 Score            : 0.4615
ROC-AUC             : 0.6111
Balanced Accuracy   : 0.4167

================================================
HistGradientBoosting - Cross-Validation (10-fold)
================================================
Accuracy            : 0.6462
Precision           : 0.6417
Recall/Sensitivity  : 0.6286
F1 Score            : 0.6275
ROC-AUC             : 0.7167
Balanced Accuracy   : 0.6429

================================================
HistGradientBoosting - Test Set Performance
================================================
Accuracy            : 0.8601 (95% CI: 0.8041-0.9020)
Precision           : 0.9098 (95% CI: 0.8457-0.9489)
Sensitivity         : 0.8740 (95% CI: 0.8051-0.9209)
Specificity         : 0.8333 (95% CI: 0.7257-0.9043)
F1 Score            : 0.8916
ROC-AUC             : 0.9188
Balanced Accuracy   : 0.8537
MCC                 : 0.6958

Confusion Matrix:
[[ 55  11]
 [ 16 111]]

TN : 55
FP : 11
FN : 16
TP : 111


################################################
Evaluating: Voting Fusion
################################################

Voting Fusion | Fold 1/10
Accuracy            : 0.6923
Precision           : 0.7500
Sensitivity         : 0.5000
F1 Score            : 0.6000
ROC-AUC             : 0.6190
Balanced Accuracy   : 0.6786

Voting Fusion | Fold 2/10
Accuracy            : 0.6154
Precision           : 0.5714
Sensitivity         : 0.6667
F1 Score            : 0.6154
ROC-AUC             : 0.7619
Balanced Accuracy   : 0.6190

Voting Fusion | Fold 3/10
Accuracy            : 0.6154
Precision           : 0.6000
Sensitivity         : 0.5000
F1 Score            : 0.5455
ROC-AUC             : 0.7619
Balanced Accuracy   : 0.6071

Voting Fusion | Fold 4/10
Accuracy            : 0.7692
Precision           : 0.8000
Sensitivity         : 0.6667
F1 Score            : 0.7273
ROC-AUC             : 0.8333
Balanced Accuracy   : 0.7619

Voting Fusion | Fold 5/10
Accuracy            : 0.6154
Precision           : 0.6000
Sensitivity         : 0.5000
F1 Score            : 0.5455
ROC-AUC             : 0.5476
Balanced Accuracy   : 0.6071

Voting Fusion | Fold 6/10
Accuracy            : 0.6923
Precision           : 0.6667
Sensitivity         : 0.8571
F1 Score            : 0.7500
ROC-AUC             : 0.7143
Balanced Accuracy   : 0.6786

Voting Fusion | Fold 7/10
Accuracy            : 0.4615
Precision           : 0.5000
Sensitivity         : 0.4286
F1 Score            : 0.4615
ROC-AUC             : 0.4286
Balanced Accuracy   : 0.4643

Voting Fusion | Fold 8/10
Accuracy            : 0.8333
Precision           : 0.7500
Sensitivity         : 1.0000
F1 Score            : 0.8571
ROC-AUC             : 0.9722
Balanced Accuracy   : 0.8333

Voting Fusion | Fold 9/10
Accuracy            : 0.6667
Precision           : 0.7500
Sensitivity         : 0.5000
F1 Score            : 0.6000
ROC-AUC             : 0.7778
Balanced Accuracy   : 0.6667

Voting Fusion | Fold 10/10
Accuracy            : 0.4167
Precision           : 0.4286
Sensitivity         : 0.5000
F1 Score            : 0.4615
ROC-AUC             : 0.5556
Balanced Accuracy   : 0.4167

================================================
Voting Fusion - Cross-Validation (10-fold)
================================================
Accuracy            : 0.6378
Precision           : 0.6417
Recall/Sensitivity  : 0.6119
F1 Score            : 0.6164
ROC-AUC             : 0.6972
Balanced Accuracy   : 0.6333

================================================
Voting Fusion - Test Set Performance
================================================
Accuracy            : 0.8653 (95% CI: 0.8099-0.9064)
Precision           : 0.9106 (95% CI: 0.8469-0.9493)
Sensitivity         : 0.8819 (95% CI: 0.8143-0.9271)
Specificity         : 0.8333 (95% CI: 0.7257-0.9043)
F1 Score            : 0.8960
ROC-AUC             : 0.9343
Balanced Accuracy   : 0.8576
MCC                 : 0.7057

Confusion Matrix:
[[ 55  11]
 [ 15 112]]

TN : 55
FP : 11
FN : 15
TP : 112


################################################
Evaluating: Stacking Fusion
################################################

Stacking Fusion | Fold 1/10
Accuracy            : 0.6154
Precision           : 0.6667
Sensitivity         : 0.3333
F1 Score            : 0.4444
ROC-AUC             : 0.6190
Balanced Accuracy   : 0.5952

Stacking Fusion | Fold 2/10
Accuracy            : 0.6154
Precision           : 0.5556
Sensitivity         : 0.8333
F1 Score            : 0.6667
ROC-AUC             : 0.7381
Balanced Accuracy   : 0.6310

Stacking Fusion | Fold 3/10
Accuracy            : 0.7692
Precision           : 0.8000
Sensitivity         : 0.6667
F1 Score            : 0.7273
ROC-AUC             : 0.8333
Balanced Accuracy   : 0.7619

Stacking Fusion | Fold 4/10
Accuracy            : 0.7692
Precision           : 0.7143
Sensitivity         : 0.8333
F1 Score            : 0.7692
ROC-AUC             : 0.8095
Balanced Accuracy   : 0.7738

Stacking Fusion | Fold 5/10
Accuracy            : 0.5385
Precision           : 0.5000
Sensitivity         : 0.8333
F1 Score            : 0.6250
ROC-AUC             : 0.6667
Balanced Accuracy   : 0.5595

Stacking Fusion | Fold 6/10
Accuracy            : 0.8462
Precision           : 0.8571
Sensitivity         : 0.8571
F1 Score            : 0.8571
ROC-AUC             : 0.9048
Balanced Accuracy   : 0.8452

Stacking Fusion | Fold 7/10
Accuracy            : 0.6923
Precision           : 0.7143
Sensitivity         : 0.7143
F1 Score            : 0.7143
ROC-AUC             : 0.9048
Balanced Accuracy   : 0.6905

Stacking Fusion | Fold 8/10
Accuracy            : 0.6667
Precision           : 0.6250
Sensitivity         : 0.8333
F1 Score            : 0.7143
ROC-AUC             : 0.8056
Balanced Accuracy   : 0.6667

Stacking Fusion | Fold 9/10
Accuracy            : 0.9167
Precision           : 1.0000
Sensitivity         : 0.8333
F1 Score            : 0.9091
ROC-AUC             : 1.0000
Balanced Accuracy   : 0.9167

Stacking Fusion | Fold 10/10
Accuracy            : 0.6667
Precision           : 0.6667
Sensitivity         : 0.6667
F1 Score            : 0.6667
ROC-AUC             : 0.6667
Balanced Accuracy   : 0.6667

================================================
Stacking Fusion - Cross-Validation (10-fold)
================================================
Accuracy            : 0.7096
Precision           : 0.7100
Recall/Sensitivity  : 0.7405
F1 Score            : 0.7094
ROC-AUC             : 0.7948
Balanced Accuracy   : 0.7107

================================================
Stacking Fusion - Test Set Performance
================================================
Accuracy            : 0.8549 (95% CI: 0.7983-0.8977)
Precision           : 0.9304 (95% CI: 0.8687-0.9643)
Sensitivity         : 0.8425 (95% CI: 0.7692-0.8957)
Specificity         : 0.8788 (95% CI: 0.7786-0.9373)
F1 Score            : 0.8843
ROC-AUC             : 0.9331
Balanced Accuracy   : 0.8607
MCC                 : 0.6973

Confusion Matrix:
[[ 58   8]
 [ 20 107]]

TN : 58
FP : 8
FN : 20
TP : 107

================================================
FINAL MODEL COMPARISON
================================================

,CV Accuracy,CV Precision,CV Sensitivity,CV F1,CV ROC-AUC,CV Balanced Accuracy,Accuracy,Accuracy CI Low,Accuracy CI High,Precision,...,Specificity CI Low,Specificity CI High,F1,ROC-AUC,Balanced Accuracy,MCC,TN,FP,FN,TP
Voting Fusion,0.637821,0.641667,0.611905,0.616379,0.697222,0.633333,0.865285,0.809931,0.906382,0.910569,...,0.725694,0.904304,0.896000,0.934264,0.857612,0.705690,55.0,11.0,15.0,112.0
XGBoost,0.629487,0.627857,0.611905,0.610338,0.684921,0.625000,0.865285,0.809931,0.906382,0.917355,...,0.743071,0.915564,0.895161,0.927344,0.861250,0.708685,56.0,10.0,16.0,111.0
Random Forest,0.614103,0.608690,0.595238,0.587827,0.698413,0.609524,0.865285,0.809931,0.906382,0.917355,...,0.743071,0.915564,0.895161,0.941840,0.861250,0.708685,56.0,10.0,16.0,111.0
HistGradientBoosting,0.646154,0.641667,0.628571,0.627498,0.716667,0.642857,0.860104,0.804111,0.902041,0.909836,...,0.725694,0.904304,0.891566,0.918754,0.853675,0.695823,55.0,11.0,16.0,111.0
Stacking Fusion,0.709615,0.709960,0.740476,0.709409,0.794841,0.710714,0.854922,0.798312,0.897680,0.930435,...,0.778626,0.937282,0.884298,0.933071,0.860654,0.697265,58.0,8.0,20.0,107.0

Passive task

In [ ]:
# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
fused_df_named_int = pd.read_csv('/content/drive//MyDrive/Subject-level-fused_fpassive_(with_120_epoches)_MIRA-Net_data.csv')
fused_df_named_int.head()

,feat_0,feat_1,feat_2,feat_3,feat_4,feat_5,feat_6,feat_7,feat_8,feat_9,...,feat_23,feat_24,feat_25,feat_26,feat_27,feat_28,feat_29,feat_30,feat_31,PD_Label_Combined
0,-0.063580,0.222531,0.238970,-0.147646,0.063920,0.299229,-0.283284,0.130096,0.140345,0.195107,...,-0.103173,0.117264,0.180098,-0.245173,0.234747,0.030935,-0.116837,-0.156734,-0.132642,1
1,-0.063570,0.226054,0.234823,-0.148789,0.058145,0.299189,-0.290048,0.137462,0.133126,0.188994,...,-0.100787,0.116254,0.181355,-0.242283,0.234324,0.033561,-0.106613,-0.162216,-0.134554,1
2,-0.254879,0.226824,0.182010,-0.093167,0.042125,0.299335,-0.251624,-0.046365,0.245970,0.290505,...,-0.014137,0.006905,0.171293,-0.174122,0.247883,-0.173842,-0.231471,-0.003979,0.005921,0
3,-0.089376,0.230240,0.231722,-0.136595,0.063744,0.298580,-0.285835,0.123000,0.154149,0.200570,...,-0.093235,0.104472,0.175327,-0.241594,0.235989,0.022944,-0.105888,-0.153801,-0.129189,1
4,-0.087010,0.228269,0.234735,-0.139815,0.065690,0.296073,-0.283073,0.120749,0.155087,0.204744,...,-0.094610,0.104588,0.174507,-0.243292,0.236117,0.022092,-0.111647,-0.151648,-0.128134,1

In [ ]:
fused_df_named_int.shape

(320, 33)

In [ ]:
# ============================================================
# ###8)###
# ENSEMBLE CLASSIFICATION WITH STRATIFIED 10-FOLD CV
# ============================================================

# ------------------ Install Required Packages ------------------

!pip install xgboost lightgbm catboost scikit-learn statsmodels matplotlib seaborn --quiet


# ------------------ Imports ------------------

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.utils.class_weight import compute_class_weight

from sklearn.model_selection import (
    train_test_split,
    StratifiedKFold
)

from sklearn.preprocessing import StandardScaler

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    balanced_accuracy_score,
    matthews_corrcoef,
    confusion_matrix
)

from sklearn.ensemble import (
    VotingClassifier,
    StackingClassifier,
    RandomForestClassifier,
    HistGradientBoostingClassifier
)

from sklearn.linear_model import LogisticRegression

from xgboost import XGBClassifier

from statsmodels.stats.proportion import proportion_confint



# ============================================================
# STEP 1: PREPARE DATA
# ============================================================

# Feature columns
feature_cols = [f'feat_{i}' for i in range(32)]

# Target column
target_col = "PD_Label_Combined"

X = fused_df_named_int[feature_cols].copy()

y = fused_df_named_int[target_col].copy()


# ------------------ Convert X to numeric ------------------

X = X.apply(
    pd.to_numeric,
    errors='coerce'
)

X.fillna(
    0,
    inplace=True
)


# ============================================================
# STEP 2: FIXED TRAIN-TEST SPLIT BY ROW ORDER
# ============================================================

TRAIN_SIZE = 193

# ------------------------------------------------------------
# FIRST 193 ROWS = TRAINING DATA
# ------------------------------------------------------------

X_train = X.iloc[:TRAIN_SIZE].copy()
y_train = y.iloc[:TRAIN_SIZE].copy()


# ------------------------------------------------------------
# REMAINING 127 ROWS = TESTING DATA
# ------------------------------------------------------------

X_test = X.iloc[TRAIN_SIZE:].copy()
y_test = y.iloc[TRAIN_SIZE:].copy()


# ============================================================
# STEP 3: PRINT DATA SHAPES
# ============================================================

print("\n" + "=" * 70)
print("FIXED TRAIN-TEST SPLIT")
print("=" * 70)

print("\nComplete Dataset:")
print("X shape :", X.shape)
print("y shape :", y.shape)

print("\nTraining Data:")
print("X_train shape :", X_train.shape)
print("y_train shape :", y_train.shape)

print("\nTesting Data:")
print("X_test shape  :", X_test.shape)
print("y_test shape  :", y_test.shape)


# ============================================================
# STEP 4: VERIFY CLASS DISTRIBUTIONS
# ============================================================

print("\n" + "=" * 70)
print("CLASS DISTRIBUTION")
print("=" * 70)

print("\nTraining Class Distribution:")
print(
    y_train.value_counts()
    .sort_index()
)

print("\nTesting Class Distribution:")
print(
    y_test.value_counts()
    .sort_index()
)


# ============================================================
# STEP 5: CLASS WEIGHTS
# ============================================================

classes = np.unique(y_train)

class_weights = compute_class_weight(
    class_weight='balanced',
    classes=classes,
    y=y_train
)

class_weights_dict = dict(
    zip(
        classes,
        class_weights
    )
)

print("\n" + "=" * 70)
print("TRAINING CLASS WEIGHTS")
print("=" * 70)

print(class_weights_dict)


# ============================================================
# STEP 6: XGBOOST SCALE_POS_WEIGHT
# ============================================================

negative_count = np.sum(y_train == 0)
positive_count = np.sum(y_train == 1)

if positive_count > 0:
    scale_pos_weight = (
        negative_count / positive_count
    )
else:
    scale_pos_weight = 1.0

print(
    "\nXGBoost scale_pos_weight:",
    scale_pos_weight
)


# ============================================================
# STEP 7: CHECK MISSING VALUES
# ============================================================

print("\n" + "=" * 70)
print("MISSING VALUE CHECK")
print("=" * 70)

print(
    "X_train missing values:",
    X_train.isna().sum().sum()
)

print(
    "X_test missing values :",
    X_test.isna().sum().sum()
)


# ============================================================
# STEP 8: VERIFY EXACT ROW COUNTS
# ============================================================

assert len(X_train) == 193, \
    "Training data must contain exactly 193 rows"

assert len(X_test) == 127, \
    "Testing data must contain exactly 127 rows"

assert len(X_train) + len(X_test) == len(X), \
    "Train + test rows do not equal total dataset rows"


# ============================================================
# STEP 9: VERIFY NO OVERLAP
# ============================================================

train_indices = set(X_train.index)
test_indices = set(X_test.index)

assert len(train_indices.intersection(test_indices)) == 0, \
    "ERROR: Training and testing data overlap!"

print("\n" + "=" * 70)
print("FINAL VERIFICATION")
print("=" * 70)

print("Training rows :", len(X_train))
print("Testing rows  :", len(X_test))
print("Total rows    :", len(X_train) + len(X_test))

print("\nTraining row range:")
print(
    X_train.index[0],
    "to",
    X_train.index[-1]
)

print("\nTesting row range:")
print(
    X_test.index[0],
    "to",
    X_test.index[-1]
)

print("\nNo train-test overlap detected.")
print("Data preparation completed successfully.")

# ============================================================
# STEP 5: BASE MODEL CREATION FUNCTION
# ============================================================

def create_models():

    # ---------------- XGBoost ----------------

    xgb = XGBClassifier(
        n_estimators=200,
        max_depth=4,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,

        scale_pos_weight=scale_pos_weight,

        eval_metric='logloss',

        random_state=42,
        n_jobs=-1
    )


    # ---------------- Random Forest ----------------

    rf = RandomForestClassifier(
        n_estimators=200,

        class_weight='balanced',

        random_state=42,
        n_jobs=-1
    )


    # ---------------- HistGradientBoosting ----------------

    hgb = HistGradientBoostingClassifier(
        max_iter=200,
        learning_rate=0.05,
        max_leaf_nodes=31,

        class_weight='balanced',

        random_state=42
    )


    return xgb, rf, hgb


# ============================================================
# STEP 6: STRATIFIED 10-FOLD CV
# ============================================================

skf = StratifiedKFold(
    n_splits=10,
    shuffle=True,
    random_state=42
)


# ============================================================
# STEP 7: EVALUATION FUNCTION
# ============================================================

def evaluate_model(model_name):

    # ========================================================
    # CV METRIC STORAGE
    # ========================================================

    cv_accuracy = []
    cv_precision = []
    cv_sensitivity = []
    cv_f1 = []
    cv_auc = []
    cv_balanced_accuracy = []


    # ========================================================
    # 10-FOLD STRATIFIED CROSS-VALIDATION
    # ========================================================

    for fold, (train_idx, val_idx) in enumerate(
        skf.split(X_train, y_train),
        start=1
    ):

        print(
            f"\n{model_name} | Fold {fold}/10"
        )


        # ----------------------------------------------------
        # Split fold
        # ----------------------------------------------------

        X_tr = X_train.iloc[
            train_idx
        ]

        X_val = X_train.iloc[
            val_idx
        ]

        y_tr = y_train.iloc[
            train_idx
        ]

        y_val = y_train.iloc[
            val_idx
        ]


        # ----------------------------------------------------
        # Scaling INSIDE EACH FOLD
        # ----------------------------------------------------

        scaler = StandardScaler()

        X_tr_scaled = scaler.fit_transform(
            X_tr
        )

        X_val_scaled = scaler.transform(
            X_val
        )


        # ----------------------------------------------------
        # Create FRESH models for every fold
        # ----------------------------------------------------

        xgb, rf, hgb = create_models()


        # ----------------------------------------------------
        # Select requested model
        # ----------------------------------------------------

        if model_name == "XGBoost":

            model = xgb


        elif model_name == "Random Forest":

            model = rf


        elif model_name == "HistGradientBoosting":

            model = hgb


        elif model_name == "Voting Fusion":

            model = VotingClassifier(
                estimators=[
                    ('xgb', xgb),
                    ('rf', rf),
                    ('hgb', hgb)
                ],
                voting='soft'
            )


        elif model_name == "Stacking Fusion":

            model = StackingClassifier(
                estimators=[
                    ('xgb', xgb),
                    ('rf', rf),
                    ('hgb', hgb)
                ],

                final_estimator=LogisticRegression(
                    max_iter=1000,
                    class_weight='balanced'
                ),

                passthrough=True,

                cv=5
            )


        else:

            raise ValueError(
                f"Unknown model: {model_name}"
            )


        # ----------------------------------------------------
        # Train fold
        # ----------------------------------------------------

        model.fit(
            X_tr_scaled,
            y_tr
        )


        # ----------------------------------------------------
        # Validation predictions
        # ----------------------------------------------------

        val_preds = model.predict(
            X_val_scaled
        )

        val_probs = model.predict_proba(
            X_val_scaled
        )[:, 1]


        # ----------------------------------------------------
        # Fold metrics
        # ----------------------------------------------------

        fold_accuracy = accuracy_score(
            y_val,
            val_preds
        )

        fold_precision = precision_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_sensitivity = recall_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_f1 = f1_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_auc = roc_auc_score(
            y_val,
            val_probs
        )

        fold_balanced_accuracy = balanced_accuracy_score(
            y_val,
            val_preds
        )


        # ----------------------------------------------------
        # Store fold metrics
        # ----------------------------------------------------

        cv_accuracy.append(
            fold_accuracy
        )

        cv_precision.append(
            fold_precision
        )

        cv_sensitivity.append(
            fold_sensitivity
        )

        cv_f1.append(
            fold_f1
        )

        cv_auc.append(
            fold_auc
        )

        cv_balanced_accuracy.append(
            fold_balanced_accuracy
        )


        # ----------------------------------------------------
        # Print fold result
        # ----------------------------------------------------

        print(
            f"Accuracy            : {fold_accuracy:.4f}"
        )

        print(
            f"Precision           : {fold_precision:.4f}"
        )

        print(
            f"Sensitivity         : {fold_sensitivity:.4f}"
        )

        print(
            f"F1 Score            : {fold_f1:.4f}"
        )

        print(
            f"ROC-AUC             : {fold_auc:.4f}"
        )

        print(
            f"Balanced Accuracy   : "
            f"{fold_balanced_accuracy:.4f}"
        )


    # ========================================================
    # CV MEAN RESULTS
    # ========================================================

    cv_accuracy_mean = np.mean(
        cv_accuracy
    )

    cv_precision_mean = np.mean(
        cv_precision
    )

    cv_sensitivity_mean = np.mean(
        cv_sensitivity
    )

    cv_f1_mean = np.mean(
        cv_f1
    )

    cv_auc_mean = np.mean(
        cv_auc
    )

    cv_balanced_accuracy_mean = np.mean(
        cv_balanced_accuracy
    )


    # ========================================================
    # CROSS-VALIDATION RESULTS
    # ========================================================

    print(
        "\n================================================"
    )

    print(
        f"{model_name} - Cross-Validation (10-fold)"
    )

    print(
        "================================================"
    )

    print(
        f"Accuracy            : "
        f"{cv_accuracy_mean:.4f}"
    )

    print(
        f"Precision           : "
        f"{cv_precision_mean:.4f}"
    )

    print(
        f"Recall/Sensitivity  : "
        f"{cv_sensitivity_mean:.4f}"
    )

    print(
        f"F1 Score            : "
        f"{cv_f1_mean:.4f}"
    )

    print(
        f"ROC-AUC             : "
        f"{cv_auc_mean:.4f}"
    )

    print(
        f"Balanced Accuracy   : "
        f"{cv_balanced_accuracy_mean:.4f}"
    )


    # ========================================================
    # TRAIN FINAL MODEL ON COMPLETE TRAINING SET
    # ========================================================

    final_scaler = StandardScaler()

    X_train_final_scaled = final_scaler.fit_transform(
        X_train
    )

    X_test_final_scaled = final_scaler.transform(
        X_test
    )


    # --------------------------------------------------------
    # Create fresh final models
    # --------------------------------------------------------

    xgb, rf, hgb = create_models()


    if model_name == "XGBoost":

        final_model = xgb


    elif model_name == "Random Forest":

        final_model = rf


    elif model_name == "HistGradientBoosting":

        final_model = hgb


    elif model_name == "Voting Fusion":

        final_model = VotingClassifier(
            estimators=[
                ('xgb', xgb),
                ('rf', rf),
                ('hgb', hgb)
            ],
            voting='soft'
        )


    elif model_name == "Stacking Fusion":

        final_model = StackingClassifier(
            estimators=[
                ('xgb', xgb),
                ('rf', rf),
                ('hgb', hgb)
            ],

            final_estimator=LogisticRegression(
                max_iter=1000,
                class_weight='balanced'
            ),

            passthrough=True,

            cv=5
        )


    # ========================================================
    # FINAL TRAINING
    # ========================================================

    final_model.fit(
        X_train_final_scaled,
        y_train
    )


    # ========================================================
    # TEST PREDICTIONS
    # ========================================================

    test_preds = final_model.predict(
        X_test_final_scaled
    )

    test_probs = final_model.predict_proba(
        X_test_final_scaled
    )[:, 1]


    # ========================================================
    # TEST METRICS
    # ========================================================

    accuracy = accuracy_score(
        y_test,
        test_preds
    )

    precision = precision_score(
        y_test,
        test_preds,
        zero_division=0
    )

    sensitivity = recall_score(
        y_test,
        test_preds,
        zero_division=0
    )

    f1 = f1_score(
        y_test,
        test_preds,
        zero_division=0
    )

    roc_auc = roc_auc_score(
        y_test,
        test_probs
    )

    balanced_accuracy = balanced_accuracy_score(
        y_test,
        test_preds
    )

    mcc = matthews_corrcoef(
        y_test,
        test_preds
    )


    # ========================================================
    # CONFUSION MATRIX
    # ========================================================

    cm = confusion_matrix(
        y_test,
        test_preds,
        labels=[0, 1]
    )

    tn, fp, fn, tp = cm.ravel()


    # ========================================================
    # SENSITIVITY / SPECIFICITY
    # ========================================================

    sensitivity = (
        tp / (tp + fn)
        if (tp + fn) > 0
        else 0
    )

    specificity = (
        tn / (tn + fp)
        if (tn + fp) > 0
        else 0
    )


    # ========================================================
    # 95% CONFIDENCE INTERVALS
    # ========================================================

    # ---------------- Accuracy CI ----------------

    acc_low, acc_high = proportion_confint(
        count=int(round(accuracy * len(y_test))),
        nobs=len(y_test),
        alpha=0.05,
        method='wilson'
    )


    # ---------------- Precision CI ----------------

    precision_low, precision_high = proportion_confint(
        count=tp,
        nobs=(tp + fp),
        alpha=0.05,
        method='wilson'
    ) if (tp + fp) > 0 else (0.0, 0.0)


    # ---------------- Sensitivity CI ----------------

    sensitivity_low, sensitivity_high = proportion_confint(
        count=tp,
        nobs=(tp + fn),
        alpha=0.05,
        method='wilson'
    ) if (tp + fn) > 0 else (0.0, 0.0)


    # ---------------- Specificity CI ----------------

    specificity_low, specificity_high = proportion_confint(
        count=tn,
        nobs=(tn + fp),
        alpha=0.05,
        method='wilson'
    ) if (tn + fp) > 0 else (0.0, 0.0)


    # ========================================================
    # TEST SET PERFORMANCE
    # ========================================================

    print(
        "\n================================================"
    )

    print(
        f"{model_name} - Test Set Performance"
    )

    print(
        "================================================"
    )

    print(
        f"Accuracy            : {accuracy:.4f} "
        f"(95% CI: "
        f"{acc_low:.4f}-{acc_high:.4f})"
    )

    print(
        f"Precision           : {precision:.4f} "
        f"(95% CI: "
        f"{precision_low:.4f}-{precision_high:.4f})"
    )

    print(
        f"Sensitivity         : {sensitivity:.4f} "
        f"(95% CI: "
        f"{sensitivity_low:.4f}-{sensitivity_high:.4f})"
    )

    print(
        f"Specificity         : {specificity:.4f} "
        f"(95% CI: "
        f"{specificity_low:.4f}-{specificity_high:.4f})"
    )

    print(
        f"F1 Score            : {f1:.4f}"
    )

    print(
        f"ROC-AUC             : {roc_auc:.4f}"
    )

    print(
        f"Balanced Accuracy   : "
        f"{balanced_accuracy:.4f}"
    )

    print(
        f"MCC                 : {mcc:.4f}"
    )


    # ========================================================
    # CONFUSION MATRIX
    # ========================================================

    print(
        "\nConfusion Matrix:"
    )

    print(cm)

    print(
        "\nTN :", tn
    )

    print(
        "FP :", fp
    )

    print(
        "FN :", fn
    )

    print(
        "TP :", tp
    )


    # ========================================================
    # STORE RESULTS
    # ========================================================

    result = {

        # ---------------- CV ----------------

        "CV Accuracy":
            cv_accuracy_mean,

        "CV Precision":
            cv_precision_mean,

        "CV Sensitivity":
            cv_sensitivity_mean,

        "CV F1":
            cv_f1_mean,

        "CV ROC-AUC":
            cv_auc_mean,

        "CV Balanced Accuracy":
            cv_balanced_accuracy_mean,


        # ---------------- Test ----------------

        "Accuracy":
            accuracy,

        "Accuracy CI Low":
            acc_low,

        "Accuracy CI High":
            acc_high,


        "Precision":
            precision,

        "Precision CI Low":
            precision_low,

        "Precision CI High":
            precision_high,


        "Sensitivity":
            sensitivity,

        "Sensitivity CI Low":
            sensitivity_low,

        "Sensitivity CI High":
            sensitivity_high,


        "Specificity":
            specificity,

        "Specificity CI Low":
            specificity_low,

        "Specificity CI High":
            specificity_high,


        "F1":
            f1,

        "ROC-AUC":
            roc_auc,

        "Balanced Accuracy":
            balanced_accuracy,

        "MCC":
            mcc,


        # ---------------- Confusion Matrix ----------------

        "TN":
            tn,

        "FP":
            fp,

        "FN":
            fn,

        "TP":
            tp
    }


    return result


# ============================================================
# STEP 8: EVALUATE ALL MODELS
# ============================================================

model_names = [
    "XGBoost",
    "Random Forest",
    "HistGradientBoosting",
    "Voting Fusion",
    "Stacking Fusion"
]


results = {}

for name in model_names:

    print(
        "\n\n################################################"
    )

    print(
        f"Evaluating: {name}"
    )

    print(
        "################################################"
    )

    results[name] = evaluate_model(
        name
    )


# ============================================================
# STEP 9: FINAL RESULTS DATAFRAME
# ============================================================

results_df = pd.DataFrame(
    results
).T


# ============================================================
# STEP 10: ORDER RESULTS
# ============================================================

results_df = results_df[
    [

        # ---------------- CV ----------------

        "CV Accuracy",
        "CV Precision",
        "CV Sensitivity",
        "CV F1",
        "CV ROC-AUC",
        "CV Balanced Accuracy",


        # ---------------- Test ----------------

        "Accuracy",
        "Accuracy CI Low",
        "Accuracy CI High",

        "Precision",
        "Precision CI Low",
        "Precision CI High",

        "Sensitivity",
        "Sensitivity CI Low",
        "Sensitivity CI High",

        "Specificity",
        "Specificity CI Low",
        "Specificity CI High",

        "F1",
        "ROC-AUC",
        "Balanced Accuracy",
        "MCC",

        # ---------------- Confusion Matrix ----------------

        "TN",
        "FP",
        "FN",
        "TP"
    ]
]


# ============================================================
# STEP 11: DISPLAY FINAL RESULTS
# ============================================================

print(
    "\n================================================"
)

print(
    "FINAL MODEL COMPARISON"
)

print(
    "================================================\n"
)


display(
    results_df.sort_values(
        by="F1",
        ascending=False
    )
)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 8.5 MB/s eta 0:00:00

======================================================================
FIXED TRAIN-TEST SPLIT
======================================================================

Complete Dataset:
X shape : (320, 32)
y shape : (320,)

Training Data:
X_train shape : (193, 32)
y_train shape : (193,)

Testing Data:
X_test shape  : (127, 32)
y_test shape  : (127,)

======================================================================
CLASS DISTRIBUTION
======================================================================

Training Class Distribution:
PD_Label_Combined
0     66
1    127
Name: count, dtype: int64

Testing Class Distribution:
PD_Label_Combined
0    65
1    62
Name: count, dtype: int64

======================================================================
TRAINING CLASS WEIGHTS
======================================================================
{np.int64(0): np.float64(1.4621212121212122), np.int64(1): np.float64(0.7598425196850394)}

XGBoost scale_pos_weight: 0.5196850393700787

======================================================================
MISSING VALUE CHECK
======================================================================
X_train missing values: 0
X_test missing values : 0

======================================================================
FINAL VERIFICATION
======================================================================
Training rows : 193
Testing rows  : 127
Total rows    : 320

Training row range:
0 to 192

Testing row range:
193 to 319

No train-test overlap detected.
Data preparation completed successfully.


################################################
Evaluating: XGBoost
################################################

XGBoost | Fold 1/10
Accuracy            : 0.7500
Precision           : 0.9000
Sensitivity         : 0.6923
F1 Score            : 0.7826
ROC-AUC             : 0.9341
Balanced Accuracy   : 0.7747

XGBoost | Fold 2/10
Accuracy            : 0.8000
Precision           : 0.9091
Sensitivity         : 0.7692
F1 Score            : 0.8333
ROC-AUC             : 0.9011
Balanced Accuracy   : 0.8132

XGBoost | Fold 3/10
Accuracy            : 0.7500
Precision           : 0.9000
Sensitivity         : 0.6923
F1 Score            : 0.7826
ROC-AUC             : 0.8352
Balanced Accuracy   : 0.7747

XGBoost | Fold 4/10
Accuracy            : 0.7895
Precision           : 0.8462
Sensitivity         : 0.8462
F1 Score            : 0.8462
ROC-AUC             : 0.9487
Balanced Accuracy   : 0.7564

XGBoost | Fold 5/10
Accuracy            : 0.8947
Precision           : 0.9231
Sensitivity         : 0.9231
F1 Score            : 0.9231
ROC-AUC             : 0.9744
Balanced Accuracy   : 0.8782

XGBoost | Fold 6/10
Accuracy            : 0.7368
Precision           : 1.0000
Sensitivity         : 0.6154
F1 Score            : 0.7619
ROC-AUC             : 0.8910
Balanced Accuracy   : 0.8077

XGBoost | Fold 7/10
Accuracy            : 0.8421
Precision           : 0.8125
Sensitivity         : 1.0000
F1 Score            : 0.8966
ROC-AUC             : 0.9872
Balanced Accuracy   : 0.7500

XGBoost | Fold 8/10
Accuracy            : 0.8947
Precision           : 0.8571
Sensitivity         : 1.0000
F1 Score            : 0.9231
ROC-AUC             : 0.9167
Balanced Accuracy   : 0.8571

XGBoost | Fold 9/10
Accuracy            : 0.7895
Precision           : 0.7857
Sensitivity         : 0.9167
F1 Score            : 0.8462
ROC-AUC             : 0.9167
Balanced Accuracy   : 0.7440

XGBoost | Fold 10/10
Accuracy            : 0.9474
Precision           : 1.0000
Sensitivity         : 0.9167
F1 Score            : 0.9565
ROC-AUC             : 0.9762
Balanced Accuracy   : 0.9583

================================================
XGBoost - Cross-Validation (10-fold)
================================================
Accuracy            : 0.8195
Precision           : 0.8934
Recall/Sensitivity  : 0.8372
F1 Score            : 0.8552
ROC-AUC             : 0.9281
Balanced Accuracy   : 0.8114

================================================
XGBoost - Test Set Performance
================================================
Accuracy            : 0.9921 (95% CI: 0.9567-0.9986)
Precision           : 1.0000 (95% CI: 0.9408-1.0000)
Sensitivity         : 0.9839 (95% CI: 0.9141-0.9971)
Specificity         : 1.0000 (95% CI: 0.9442-1.0000)
F1 Score            : 0.9919
ROC-AUC             : 0.9990
Balanced Accuracy   : 0.9919
MCC                 : 0.9844

Confusion Matrix:
[[65  0]
 [ 1 61]]

TN : 65
FP : 0
FN : 1
TP : 61


################################################
Evaluating: Random Forest
################################################

Random Forest | Fold 1/10
Accuracy            : 0.7500
Precision           : 0.9000
Sensitivity         : 0.6923
F1 Score            : 0.7826
ROC-AUC             : 0.9341
Balanced Accuracy   : 0.7747

Random Forest | Fold 2/10
Accuracy            : 0.8000
Precision           : 0.9091
Sensitivity         : 0.7692
F1 Score            : 0.8333
ROC-AUC             : 0.8352
Balanced Accuracy   : 0.8132

Random Forest | Fold 3/10
Accuracy            : 0.7500
Precision           : 0.7857
Sensitivity         : 0.8462
F1 Score            : 0.8148
ROC-AUC             : 0.7857
Balanced Accuracy   : 0.7088

Random Forest | Fold 4/10
Accuracy            : 0.7895
Precision           : 0.8462
Sensitivity         : 0.8462
F1 Score            : 0.8462
ROC-AUC             : 0.9359
Balanced Accuracy   : 0.7564

Random Forest | Fold 5/10
Accuracy            : 0.8947
Precision           : 0.9231
Sensitivity         : 0.9231
F1 Score            : 0.9231
ROC-AUC             : 0.9872
Balanced Accuracy   : 0.8782

Random Forest | Fold 6/10
Accuracy            : 0.6842
Precision           : 0.8889
Sensitivity         : 0.6154
F1 Score            : 0.7273
ROC-AUC             : 0.8846
Balanced Accuracy   : 0.7244

Random Forest | Fold 7/10
Accuracy            : 0.8421
Precision           : 0.8125
Sensitivity         : 1.0000
F1 Score            : 0.8966
ROC-AUC             : 0.9487
Balanced Accuracy   : 0.7500

Random Forest | Fold 8/10
Accuracy            : 0.8947
Precision           : 0.8571
Sensitivity         : 1.0000
F1 Score            : 0.9231
ROC-AUC             : 0.8988
Balanced Accuracy   : 0.8571

Random Forest | Fold 9/10
Accuracy            : 0.7368
Precision           : 0.7333
Sensitivity         : 0.9167
F1 Score            : 0.8148
ROC-AUC             : 0.9286
Balanced Accuracy   : 0.6726

Random Forest | Fold 10/10
Accuracy            : 0.9474
Precision           : 1.0000
Sensitivity         : 0.9167
F1 Score            : 0.9565
ROC-AUC             : 0.9762
Balanced Accuracy   : 0.9583

================================================
Random Forest - Cross-Validation (10-fold)
================================================
Accuracy            : 0.8089
Precision           : 0.8656
Recall/Sensitivity  : 0.8526
F1 Score            : 0.8518
ROC-AUC             : 0.9115
Balanced Accuracy   : 0.7894

================================================
Random Forest - Test Set Performance
================================================
Accuracy            : 0.9921 (95% CI: 0.9567-0.9986)
Precision           : 1.0000 (95% CI: 0.9408-1.0000)
Sensitivity         : 0.9839 (95% CI: 0.9141-0.9971)
Specificity         : 1.0000 (95% CI: 0.9442-1.0000)
F1 Score            : 0.9919
ROC-AUC             : 0.9988
Balanced Accuracy   : 0.9919
MCC                 : 0.9844

Confusion Matrix:
[[65  0]
 [ 1 61]]

TN : 65
FP : 0
FN : 1
TP : 61


################################################
Evaluating: HistGradientBoosting
################################################

HistGradientBoosting | Fold 1/10
Accuracy            : 0.8000
Precision           : 0.9091
Sensitivity         : 0.7692
F1 Score            : 0.8333
ROC-AUC             : 0.9121
Balanced Accuracy   : 0.8132

HistGradientBoosting | Fold 2/10
Accuracy            : 0.8500
Precision           : 1.0000
Sensitivity         : 0.7692
F1 Score            : 0.8696
ROC-AUC             : 0.8791
Balanced Accuracy   : 0.8846

HistGradientBoosting | Fold 3/10
Accuracy            : 0.6000
Precision           : 0.7273
Sensitivity         : 0.6154
F1 Score            : 0.6667
ROC-AUC             : 0.8022
Balanced Accuracy   : 0.5934

HistGradientBoosting | Fold 4/10
Accuracy            : 0.7895
Precision           : 0.8462
Sensitivity         : 0.8462
F1 Score            : 0.8462
ROC-AUC             : 0.9487
Balanced Accuracy   : 0.7564

HistGradientBoosting | Fold 5/10
Accuracy            : 0.8421
Precision           : 0.8571
Sensitivity         : 0.9231
F1 Score            : 0.8889
ROC-AUC             : 0.9744
Balanced Accuracy   : 0.7949

HistGradientBoosting | Fold 6/10
Accuracy            : 0.6316
Precision           : 0.8000
Sensitivity         : 0.6154
F1 Score            : 0.6957
ROC-AUC             : 0.8397
Balanced Accuracy   : 0.6410

HistGradientBoosting | Fold 7/10
Accuracy            : 0.8421
Precision           : 0.8125
Sensitivity         : 1.0000
F1 Score            : 0.8966
ROC-AUC             : 0.9872
Balanced Accuracy   : 0.7500

HistGradientBoosting | Fold 8/10
Accuracy            : 0.8947
Precision           : 0.8571
Sensitivity         : 1.0000
F1 Score            : 0.9231
ROC-AUC             : 0.9643
Balanced Accuracy   : 0.8571

HistGradientBoosting | Fold 9/10
Accuracy            : 0.7368
Precision           : 0.7333
Sensitivity         : 0.9167
F1 Score            : 0.8148
ROC-AUC             : 0.8929
Balanced Accuracy   : 0.6726

HistGradientBoosting | Fold 10/10
Accuracy            : 0.8947
Precision           : 0.9167
Sensitivity         : 0.9167
F1 Score            : 0.9167
ROC-AUC             : 0.9881
Balanced Accuracy   : 0.8869

================================================
HistGradientBoosting - Cross-Validation (10-fold)
================================================
Accuracy            : 0.7882
Precision           : 0.8459
Recall/Sensitivity  : 0.8372
F1 Score            : 0.8351
ROC-AUC             : 0.9189
Balanced Accuracy   : 0.7650

================================================
HistGradientBoosting - Test Set Performance
================================================
Accuracy            : 0.9921 (95% CI: 0.9567-0.9986)
Precision           : 1.0000 (95% CI: 0.9408-1.0000)
Sensitivity         : 0.9839 (95% CI: 0.9141-0.9971)
Specificity         : 1.0000 (95% CI: 0.9442-1.0000)
F1 Score            : 0.9919
ROC-AUC             : 0.9995
Balanced Accuracy   : 0.9919
MCC                 : 0.9844

Confusion Matrix:
[[65  0]
 [ 1 61]]

TN : 65
FP : 0
FN : 1
TP : 61


################################################
Evaluating: Voting Fusion
################################################

Voting Fusion | Fold 1/10
Accuracy            : 0.7500
Precision           : 0.9000
Sensitivity         : 0.6923
F1 Score            : 0.7826
ROC-AUC             : 0.9231
Balanced Accuracy   : 0.7747

Voting Fusion | Fold 2/10
Accuracy            : 0.8500
Precision           : 1.0000
Sensitivity         : 0.7692
F1 Score            : 0.8696
ROC-AUC             : 0.8571
Balanced Accuracy   : 0.8846

Voting Fusion | Fold 3/10
Accuracy            : 0.6500
Precision           : 0.7500
Sensitivity         : 0.6923
F1 Score            : 0.7200
ROC-AUC             : 0.7912
Balanced Accuracy   : 0.6319

Voting Fusion | Fold 4/10
Accuracy            : 0.7895
Precision           : 0.8462
Sensitivity         : 0.8462
F1 Score            : 0.8462
ROC-AUC             : 0.9487
Balanced Accuracy   : 0.7564

Voting Fusion | Fold 5/10
Accuracy            : 0.8947
Precision           : 0.9231
Sensitivity         : 0.9231
F1 Score            : 0.9231
ROC-AUC             : 0.9744
Balanced Accuracy   : 0.8782

Voting Fusion | Fold 6/10
Accuracy            : 0.6842
Precision           : 0.8889
Sensitivity         : 0.6154
F1 Score            : 0.7273
ROC-AUC             : 0.8590
Balanced Accuracy   : 0.7244

Voting Fusion | Fold 7/10
Accuracy            : 0.8421
Precision           : 0.8125
Sensitivity         : 1.0000
F1 Score            : 0.8966
ROC-AUC             : 0.9872
Balanced Accuracy   : 0.7500

Voting Fusion | Fold 8/10
Accuracy            : 0.8947
Precision           : 0.8571
Sensitivity         : 1.0000
F1 Score            : 0.9231
ROC-AUC             : 0.9643
Balanced Accuracy   : 0.8571

Voting Fusion | Fold 9/10
Accuracy            : 0.7368
Precision           : 0.7333
Sensitivity         : 0.9167
F1 Score            : 0.8148
ROC-AUC             : 0.9286
Balanced Accuracy   : 0.6726

Voting Fusion | Fold 10/10
Accuracy            : 0.9474
Precision           : 1.0000
Sensitivity         : 0.9167
F1 Score            : 0.9565
ROC-AUC             : 0.9881
Balanced Accuracy   : 0.9583

================================================
Voting Fusion - Cross-Validation (10-fold)
================================================
Accuracy            : 0.8039
Precision           : 0.8711
Recall/Sensitivity  : 0.8372
F1 Score            : 0.8460
ROC-AUC             : 0.9222
Balanced Accuracy   : 0.7888

================================================
Voting Fusion - Test Set Performance
================================================
Accuracy            : 0.9921 (95% CI: 0.9567-0.9986)
Precision           : 1.0000 (95% CI: 0.9408-1.0000)
Sensitivity         : 0.9839 (95% CI: 0.9141-0.9971)
Specificity         : 1.0000 (95% CI: 0.9442-1.0000)
F1 Score            : 0.9919
ROC-AUC             : 0.9990
Balanced Accuracy   : 0.9919
MCC                 : 0.9844

Confusion Matrix:
[[65  0]
 [ 1 61]]

TN : 65
FP : 0
FN : 1
TP : 61


################################################
Evaluating: Stacking Fusion
################################################

Stacking Fusion | Fold 1/10
Accuracy            : 0.8000
Precision           : 1.0000
Sensitivity         : 0.6923
F1 Score            : 0.8182
ROC-AUC             : 0.9451
Balanced Accuracy   : 0.8462

Stacking Fusion | Fold 2/10
Accuracy            : 0.8500
Precision           : 1.0000
Sensitivity         : 0.7692
F1 Score            : 0.8696
ROC-AUC             : 0.9670
Balanced Accuracy   : 0.8846

Stacking Fusion | Fold 3/10
Accuracy            : 0.8500
Precision           : 1.0000
Sensitivity         : 0.7692
F1 Score            : 0.8696
ROC-AUC             : 0.9231
Balanced Accuracy   : 0.8846

Stacking Fusion | Fold 4/10
Accuracy            : 0.8421
Precision           : 0.9167
Sensitivity         : 0.8462
F1 Score            : 0.8800
ROC-AUC             : 0.9744
Balanced Accuracy   : 0.8397

Stacking Fusion | Fold 5/10
Accuracy            : 0.9474
Precision           : 1.0000
Sensitivity         : 0.9231
F1 Score            : 0.9600
ROC-AUC             : 0.9744
Balanced Accuracy   : 0.9615

Stacking Fusion | Fold 6/10
Accuracy            : 0.7368
Precision           : 1.0000
Sensitivity         : 0.6154
F1 Score            : 0.7619
ROC-AUC             : 0.9359
Balanced Accuracy   : 0.8077

Stacking Fusion | Fold 7/10
Accuracy            : 0.8947
Precision           : 0.9231
Sensitivity         : 0.9231
F1 Score            : 0.9231
ROC-AUC             : 0.9744
Balanced Accuracy   : 0.8782

Stacking Fusion | Fold 8/10
Accuracy            : 0.8947
Precision           : 0.8571
Sensitivity         : 1.0000
F1 Score            : 0.9231
ROC-AUC             : 0.9524
Balanced Accuracy   : 0.8571

Stacking Fusion | Fold 9/10
Accuracy            : 0.8421
Precision           : 0.9091
Sensitivity         : 0.8333
F1 Score            : 0.8696
ROC-AUC             : 0.9405
Balanced Accuracy   : 0.8452

Stacking Fusion | Fold 10/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

================================================
Stacking Fusion - Cross-Validation (10-fold)
================================================
Accuracy            : 0.8658
Precision           : 0.9606
Recall/Sensitivity  : 0.8372
F1 Score            : 0.8875
ROC-AUC             : 0.9587
Balanced Accuracy   : 0.8805

================================================
Stacking Fusion - Test Set Performance
================================================
Accuracy            : 0.9843 (95% CI: 0.9444-0.9957)
Precision           : 1.0000 (95% CI: 0.9398-1.0000)
Sensitivity         : 0.9677 (95% CI: 0.8898-0.9911)
Specificity         : 1.0000 (95% CI: 0.9442-1.0000)
F1 Score            : 0.9836
ROC-AUC             : 0.9990
Balanced Accuracy   : 0.9839
MCC                 : 0.9689

Confusion Matrix:
[[65  0]
 [ 2 60]]

TN : 65
FP : 0
FN : 2
TP : 60

================================================
FINAL MODEL COMPARISON
================================================

,CV Accuracy,CV Precision,CV Sensitivity,CV F1,CV ROC-AUC,CV Balanced Accuracy,Accuracy,Accuracy CI Low,Accuracy CI High,Precision,...,Specificity CI Low,Specificity CI High,F1,ROC-AUC,Balanced Accuracy,MCC,TN,FP,FN,TP
XGBoost,0.819474,0.893368,0.837179,0.855199,0.928114,0.811447,0.992126,0.956746,0.998609,1.0,...,0.944198,1.0,0.991870,0.999007,0.991935,0.984360,65.0,0.0,1.0,61.0
Random Forest,0.808947,0.865590,0.852564,0.851823,0.911493,0.789377,0.992126,0.956746,0.998609,1.0,...,0.944198,1.0,0.991870,0.998759,0.991935,0.984360,65.0,0.0,1.0,61.0
HistGradientBoosting,0.788158,0.845930,0.837179,0.835137,0.918864,0.765018,0.992126,0.956746,0.998609,1.0,...,0.944198,1.0,0.991870,0.999504,0.991935,0.984360,65.0,0.0,1.0,61.0
Voting Fusion,0.803947,0.871110,0.837179,0.845964,0.922161,0.788828,0.992126,0.956746,0.998609,1.0,...,0.944198,1.0,0.991870,0.999007,0.991935,0.984360,65.0,0.0,1.0,61.0
Stacking Fusion,0.865789,0.960598,0.837179,0.887494,0.958700,0.880495,0.984252,0.944398,0.995671,1.0,...,0.944198,1.0,0.983607,0.999007,0.983871,0.968945,65.0,0.0,2.0,60.0

In [ ]:
# ============================================================
# ###8)###
# ENSEMBLE CLASSIFICATION WITH STRATIFIED 10-FOLD CV
# ============================================================

# ------------------ Install Required Packages ------------------

!pip install xgboost lightgbm catboost scikit-learn statsmodels matplotlib seaborn --quiet


# ------------------ Imports ------------------

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.utils.class_weight import compute_class_weight

from sklearn.model_selection import (
    train_test_split,
    StratifiedKFold
)

from sklearn.preprocessing import StandardScaler

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    balanced_accuracy_score,
    matthews_corrcoef,
    confusion_matrix
)

from sklearn.ensemble import (
    VotingClassifier,
    StackingClassifier,
    RandomForestClassifier,
    HistGradientBoostingClassifier
)

from sklearn.linear_model import LogisticRegression

from xgboost import XGBClassifier

from statsmodels.stats.proportion import proportion_confint



# ============================================================
# STEP 1: PREPARE DATA
# ============================================================

feature_cols = [f'feat_{i}' for i in range(32)]
target_col = "PD_Label_Combined"

X = fused_df_named_int[feature_cols].copy()
y = fused_df_named_int[target_col].copy()


# ------------------ Convert X to numeric ------------------

X = X.apply(
    pd.to_numeric,
    errors='coerce'
)

X.fillna(
    0,
    inplace=True
)


# ============================================================
# STEP 2: FIXED TRAIN-TEST SPLIT BY ROW ORDER
# ============================================================

TEST_SIZE = 193

# ------------------------------------------------------------
# FIRST 193 ROWS = TESTING DATA
# ------------------------------------------------------------

X_test = X.iloc[:TEST_SIZE].copy()
y_test = y.iloc[:TEST_SIZE].copy()


# ------------------------------------------------------------
# REMAINING 127 ROWS = TRAINING DATA
# ------------------------------------------------------------

X_train = X.iloc[TEST_SIZE:].copy()
y_train = y.iloc[TEST_SIZE:].copy()


# ============================================================
# STEP 3: PRINT DATA SHAPES
# ============================================================

print("\n" + "=" * 70)
print("FIXED TRAIN-TEST SPLIT")
print("=" * 70)

print("\nComplete Dataset:")
print("X shape :", X.shape)
print("y shape :", y.shape)

print("\nTraining Data:")
print("X_train shape :", X_train.shape)
print("y_train shape :", y_train.shape)

print("\nTesting Data:")
print("X_test shape  :", X_test.shape)
print("y_test shape  :", y_test.shape)


# ============================================================
# STEP 4: CLASS DISTRIBUTION
# ============================================================

print("\n" + "=" * 70)
print("CLASS DISTRIBUTION")
print("=" * 70)

print("\nTraining Class Distribution:")
print(
    y_train.value_counts()
    .sort_index()
)

print("\nTesting Class Distribution:")
print(
    y_test.value_counts()
    .sort_index()
)


# ============================================================
# STEP 5: CLASS WEIGHTS
# ============================================================

classes = np.unique(y_train)

class_weights = compute_class_weight(
    class_weight='balanced',
    classes=classes,
    y=y_train
)

class_weights_dict = dict(
    zip(
        classes,
        class_weights
    )
)

print("\n" + "=" * 70)
print("TRAINING CLASS WEIGHTS")
print("=" * 70)

print(class_weights_dict)


# ============================================================
# STEP 6: XGBOOST SCALE_POS_WEIGHT
# ============================================================

negative_count = np.sum(y_train == 0)
positive_count = np.sum(y_train == 1)

if positive_count > 0:
    scale_pos_weight = (
        negative_count / positive_count
    )
else:
    scale_pos_weight = 1.0

print(
    "\nXGBoost scale_pos_weight:",
    scale_pos_weight
)


# ============================================================
# STEP 7: CHECK MISSING VALUES
# ============================================================

print("\n" + "=" * 70)
print("MISSING VALUE CHECK")
print("=" * 70)

print(
    "X_train missing values:",
    X_train.isna().sum().sum()
)

print(
    "X_test missing values :",
    X_test.isna().sum().sum()
)


# ============================================================
# STEP 8: VERIFY EXACT ROW COUNTS
# ============================================================

assert len(X_train) == 127, \
    "Training data must contain exactly 127 rows"

assert len(X_test) == 193, \
    "Testing data must contain exactly 193 rows"

assert len(X_train) + len(X_test) == len(X), \
    "Train + test rows do not equal total dataset rows"


# ============================================================
# STEP 9: VERIFY NO OVERLAP
# ============================================================

train_indices = set(X_train.index)
test_indices = set(X_test.index)

assert len(
    train_indices.intersection(test_indices)
) == 0, \
    "ERROR: Training and testing data overlap!"


# ============================================================
# STEP 10: FINAL VERIFICATION
# ============================================================

print("\n" + "=" * 70)
print("FINAL VERIFICATION")
print("=" * 70)

print("Training rows :", len(X_train))
print("Testing rows  :", len(X_test))
print("Total rows    :", len(X_train) + len(X_test))

print("\nTesting row range:")
print(
    X_test.index[0],
    "to",
    X_test.index[-1]
)

print("\nTraining row range:")
print(
    X_train.index[0],
    "to",
    X_train.index[-1]
)

print("\nNo train-test overlap detected.")
print("Data preparation completed successfully.")

# ============================================================
# STEP 5: BASE MODEL CREATION FUNCTION
# ============================================================

def create_models():

    # ---------------- XGBoost ----------------

    xgb = XGBClassifier(
        n_estimators=200,
        max_depth=4,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,

        scale_pos_weight=scale_pos_weight,

        eval_metric='logloss',

        random_state=42,
        n_jobs=-1
    )


    # ---------------- Random Forest ----------------

    rf = RandomForestClassifier(
        n_estimators=200,

        class_weight='balanced',

        random_state=42,
        n_jobs=-1
    )


    # ---------------- HistGradientBoosting ----------------

    hgb = HistGradientBoostingClassifier(
        max_iter=200,
        learning_rate=0.05,
        max_leaf_nodes=31,

        class_weight='balanced',

        random_state=42
    )


    return xgb, rf, hgb


# ============================================================
# STEP 6: STRATIFIED 10-FOLD CV
# ============================================================

skf = StratifiedKFold(
    n_splits=10,
    shuffle=True,
    random_state=42
)


# ============================================================
# STEP 7: EVALUATION FUNCTION
# ============================================================

def evaluate_model(model_name):

    # ========================================================
    # CV METRIC STORAGE
    # ========================================================

    cv_accuracy = []
    cv_precision = []
    cv_sensitivity = []
    cv_f1 = []
    cv_auc = []
    cv_balanced_accuracy = []


    # ========================================================
    # 10-FOLD STRATIFIED CROSS-VALIDATION
    # ========================================================

    for fold, (train_idx, val_idx) in enumerate(
        skf.split(X_train, y_train),
        start=1
    ):

        print(
            f"\n{model_name} | Fold {fold}/10"
        )


        # ----------------------------------------------------
        # Split fold
        # ----------------------------------------------------

        X_tr = X_train.iloc[
            train_idx
        ]

        X_val = X_train.iloc[
            val_idx
        ]

        y_tr = y_train.iloc[
            train_idx
        ]

        y_val = y_train.iloc[
            val_idx
        ]


        # ----------------------------------------------------
        # Scaling INSIDE EACH FOLD
        # ----------------------------------------------------

        scaler = StandardScaler()

        X_tr_scaled = scaler.fit_transform(
            X_tr
        )

        X_val_scaled = scaler.transform(
            X_val
        )


        # ----------------------------------------------------
        # Create FRESH models for every fold
        # ----------------------------------------------------

        xgb, rf, hgb = create_models()


        # ----------------------------------------------------
        # Select requested model
        # ----------------------------------------------------

        if model_name == "XGBoost":

            model = xgb


        elif model_name == "Random Forest":

            model = rf


        elif model_name == "HistGradientBoosting":

            model = hgb


        elif model_name == "Voting Fusion":

            model = VotingClassifier(
                estimators=[
                    ('xgb', xgb),
                    ('rf', rf),
                    ('hgb', hgb)
                ],
                voting='soft'
            )


        elif model_name == "Stacking Fusion":

            model = StackingClassifier(
                estimators=[
                    ('xgb', xgb),
                    ('rf', rf),
                    ('hgb', hgb)
                ],

                final_estimator=LogisticRegression(
                    max_iter=1000,
                    class_weight='balanced'
                ),

                passthrough=True,

                cv=5
            )


        else:

            raise ValueError(
                f"Unknown model: {model_name}"
            )


        # ----------------------------------------------------
        # Train fold
        # ----------------------------------------------------

        model.fit(
            X_tr_scaled,
            y_tr
        )


        # ----------------------------------------------------
        # Validation predictions
        # ----------------------------------------------------

        val_preds = model.predict(
            X_val_scaled
        )

        val_probs = model.predict_proba(
            X_val_scaled
        )[:, 1]


        # ----------------------------------------------------
        # Fold metrics
        # ----------------------------------------------------

        fold_accuracy = accuracy_score(
            y_val,
            val_preds
        )

        fold_precision = precision_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_sensitivity = recall_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_f1 = f1_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_auc = roc_auc_score(
            y_val,
            val_probs
        )

        fold_balanced_accuracy = balanced_accuracy_score(
            y_val,
            val_preds
        )


        # ----------------------------------------------------
        # Store fold metrics
        # ----------------------------------------------------

        cv_accuracy.append(
            fold_accuracy
        )

        cv_precision.append(
            fold_precision
        )

        cv_sensitivity.append(
            fold_sensitivity
        )

        cv_f1.append(
            fold_f1
        )

        cv_auc.append(
            fold_auc
        )

        cv_balanced_accuracy.append(
            fold_balanced_accuracy
        )


        # ----------------------------------------------------
        # Print fold result
        # ----------------------------------------------------

        print(
            f"Accuracy            : {fold_accuracy:.4f}"
        )

        print(
            f"Precision           : {fold_precision:.4f}"
        )

        print(
            f"Sensitivity         : {fold_sensitivity:.4f}"
        )

        print(
            f"F1 Score            : {fold_f1:.4f}"
        )

        print(
            f"ROC-AUC             : {fold_auc:.4f}"
        )

        print(
            f"Balanced Accuracy   : "
            f"{fold_balanced_accuracy:.4f}"
        )


    # ========================================================
    # CV MEAN RESULTS
    # ========================================================

    cv_accuracy_mean = np.mean(
        cv_accuracy
    )

    cv_precision_mean = np.mean(
        cv_precision
    )

    cv_sensitivity_mean = np.mean(
        cv_sensitivity
    )

    cv_f1_mean = np.mean(
        cv_f1
    )

    cv_auc_mean = np.mean(
        cv_auc
    )

    cv_balanced_accuracy_mean = np.mean(
        cv_balanced_accuracy
    )


    # ========================================================
    # CROSS-VALIDATION RESULTS
    # ========================================================

    print(
        "\n================================================"
    )

    print(
        f"{model_name} - Cross-Validation (10-fold)"
    )

    print(
        "================================================"
    )

    print(
        f"Accuracy            : "
        f"{cv_accuracy_mean:.4f}"
    )

    print(
        f"Precision           : "
        f"{cv_precision_mean:.4f}"
    )

    print(
        f"Recall/Sensitivity  : "
        f"{cv_sensitivity_mean:.4f}"
    )

    print(
        f"F1 Score            : "
        f"{cv_f1_mean:.4f}"
    )

    print(
        f"ROC-AUC             : "
        f"{cv_auc_mean:.4f}"
    )

    print(
        f"Balanced Accuracy   : "
        f"{cv_balanced_accuracy_mean:.4f}"
    )


    # ========================================================
    # TRAIN FINAL MODEL ON COMPLETE TRAINING SET
    # ========================================================

    final_scaler = StandardScaler()

    X_train_final_scaled = final_scaler.fit_transform(
        X_train
    )

    X_test_final_scaled = final_scaler.transform(
        X_test
    )


    # --------------------------------------------------------
    # Create fresh final models
    # --------------------------------------------------------

    xgb, rf, hgb = create_models()


    if model_name == "XGBoost":

        final_model = xgb


    elif model_name == "Random Forest":

        final_model = rf


    elif model_name == "HistGradientBoosting":

        final_model = hgb


    elif model_name == "Voting Fusion":

        final_model = VotingClassifier(
            estimators=[
                ('xgb', xgb),
                ('rf', rf),
                ('hgb', hgb)
            ],
            voting='soft'
        )


    elif model_name == "Stacking Fusion":

        final_model = StackingClassifier(
            estimators=[
                ('xgb', xgb),
                ('rf', rf),
                ('hgb', hgb)
            ],

            final_estimator=LogisticRegression(
                max_iter=1000,
                class_weight='balanced'
            ),

            passthrough=True,

            cv=5
        )


    # ========================================================
    # FINAL TRAINING
    # ========================================================

    final_model.fit(
        X_train_final_scaled,
        y_train
    )


    # ========================================================
    # TEST PREDICTIONS
    # ========================================================

    test_preds = final_model.predict(
        X_test_final_scaled
    )

    test_probs = final_model.predict_proba(
        X_test_final_scaled
    )[:, 1]


    # ========================================================
    # TEST METRICS
    # ========================================================

    accuracy = accuracy_score(
        y_test,
        test_preds
    )

    precision = precision_score(
        y_test,
        test_preds,
        zero_division=0
    )

    sensitivity = recall_score(
        y_test,
        test_preds,
        zero_division=0
    )

    f1 = f1_score(
        y_test,
        test_preds,
        zero_division=0
    )

    roc_auc = roc_auc_score(
        y_test,
        test_probs
    )

    balanced_accuracy = balanced_accuracy_score(
        y_test,
        test_preds
    )

    mcc = matthews_corrcoef(
        y_test,
        test_preds
    )


    # ========================================================
    # CONFUSION MATRIX
    # ========================================================

    cm = confusion_matrix(
        y_test,
        test_preds,
        labels=[0, 1]
    )

    tn, fp, fn, tp = cm.ravel()


    # ========================================================
    # SENSITIVITY / SPECIFICITY
    # ========================================================

    sensitivity = (
        tp / (tp + fn)
        if (tp + fn) > 0
        else 0
    )

    specificity = (
        tn / (tn + fp)
        if (tn + fp) > 0
        else 0
    )


    # ========================================================
    # 95% CONFIDENCE INTERVALS
    # ========================================================

    # ---------------- Accuracy CI ----------------

    acc_low, acc_high = proportion_confint(
        count=int(round(accuracy * len(y_test))),
        nobs=len(y_test),
        alpha=0.05,
        method='wilson'
    )


    # ---------------- Precision CI ----------------

    precision_low, precision_high = proportion_confint(
        count=tp,
        nobs=(tp + fp),
        alpha=0.05,
        method='wilson'
    ) if (tp + fp) > 0 else (0.0, 0.0)


    # ---------------- Sensitivity CI ----------------

    sensitivity_low, sensitivity_high = proportion_confint(
        count=tp,
        nobs=(tp + fn),
        alpha=0.05,
        method='wilson'
    ) if (tp + fn) > 0 else (0.0, 0.0)


    # ---------------- Specificity CI ----------------

    specificity_low, specificity_high = proportion_confint(
        count=tn,
        nobs=(tn + fp),
        alpha=0.05,
        method='wilson'
    ) if (tn + fp) > 0 else (0.0, 0.0)


    # ========================================================
    # TEST SET PERFORMANCE
    # ========================================================

    print(
        "\n================================================"
    )

    print(
        f"{model_name} - Test Set Performance"
    )

    print(
        "================================================"
    )

    print(
        f"Accuracy            : {accuracy:.4f} "
        f"(95% CI: "
        f"{acc_low:.4f}-{acc_high:.4f})"
    )

    print(
        f"Precision           : {precision:.4f} "
        f"(95% CI: "
        f"{precision_low:.4f}-{precision_high:.4f})"
    )

    print(
        f"Sensitivity         : {sensitivity:.4f} "
        f"(95% CI: "
        f"{sensitivity_low:.4f}-{sensitivity_high:.4f})"
    )

    print(
        f"Specificity         : {specificity:.4f} "
        f"(95% CI: "
        f"{specificity_low:.4f}-{specificity_high:.4f})"
    )

    print(
        f"F1 Score            : {f1:.4f}"
    )

    print(
        f"ROC-AUC             : {roc_auc:.4f}"
    )

    print(
        f"Balanced Accuracy   : "
        f"{balanced_accuracy:.4f}"
    )

    print(
        f"MCC                 : {mcc:.4f}"
    )


    # ========================================================
    # CONFUSION MATRIX
    # ========================================================

    print(
        "\nConfusion Matrix:"
    )

    print(cm)

    print(
        "\nTN :", tn
    )

    print(
        "FP :", fp
    )

    print(
        "FN :", fn
    )

    print(
        "TP :", tp
    )


    # ========================================================
    # STORE RESULTS
    # ========================================================

    result = {

        # ---------------- CV ----------------

        "CV Accuracy":
            cv_accuracy_mean,

        "CV Precision":
            cv_precision_mean,

        "CV Sensitivity":
            cv_sensitivity_mean,

        "CV F1":
            cv_f1_mean,

        "CV ROC-AUC":
            cv_auc_mean,

        "CV Balanced Accuracy":
            cv_balanced_accuracy_mean,


        # ---------------- Test ----------------

        "Accuracy":
            accuracy,

        "Accuracy CI Low":
            acc_low,

        "Accuracy CI High":
            acc_high,


        "Precision":
            precision,

        "Precision CI Low":
            precision_low,

        "Precision CI High":
            precision_high,


        "Sensitivity":
            sensitivity,

        "Sensitivity CI Low":
            sensitivity_low,

        "Sensitivity CI High":
            sensitivity_high,


        "Specificity":
            specificity,

        "Specificity CI Low":
            specificity_low,

        "Specificity CI High":
            specificity_high,


        "F1":
            f1,

        "ROC-AUC":
            roc_auc,

        "Balanced Accuracy":
            balanced_accuracy,

        "MCC":
            mcc,


        # ---------------- Confusion Matrix ----------------

        "TN":
            tn,

        "FP":
            fp,

        "FN":
            fn,

        "TP":
            tp
    }


    return result


# ============================================================
# STEP 8: EVALUATE ALL MODELS
# ============================================================

model_names = [
    "XGBoost",
    "Random Forest",
    "HistGradientBoosting",
    "Voting Fusion",
    "Stacking Fusion"
]


results = {}

for name in model_names:

    print(
        "\n\n################################################"
    )

    print(
        f"Evaluating: {name}"
    )

    print(
        "################################################"
    )

    results[name] = evaluate_model(
        name
    )


# ============================================================
# STEP 9: FINAL RESULTS DATAFRAME
# ============================================================

results_df = pd.DataFrame(
    results
).T


# ============================================================
# STEP 10: ORDER RESULTS
# ============================================================

results_df = results_df[
    [

        # ---------------- CV ----------------

        "CV Accuracy",
        "CV Precision",
        "CV Sensitivity",
        "CV F1",
        "CV ROC-AUC",
        "CV Balanced Accuracy",


        # ---------------- Test ----------------

        "Accuracy",
        "Accuracy CI Low",
        "Accuracy CI High",

        "Precision",
        "Precision CI Low",
        "Precision CI High",

        "Sensitivity",
        "Sensitivity CI Low",
        "Sensitivity CI High",

        "Specificity",
        "Specificity CI Low",
        "Specificity CI High",

        "F1",
        "ROC-AUC",
        "Balanced Accuracy",
        "MCC",

        # ---------------- Confusion Matrix ----------------

        "TN",
        "FP",
        "FN",
        "TP"
    ]
]


# ============================================================
# STEP 11: DISPLAY FINAL RESULTS
# ============================================================

print(
    "\n================================================"
)

print(
    "FINAL MODEL COMPARISON"
)

print(
    "================================================\n"
)


display(
    results_df.sort_values(
        by="F1",
        ascending=False
    )
)

======================================================================
FIXED TRAIN-TEST SPLIT
======================================================================

Complete Dataset:
X shape : (320, 32)
y shape : (320,)

Training Data:
X_train shape : (127, 32)
y_train shape : (127,)

Testing Data:
X_test shape  : (193, 32)
y_test shape  : (193,)

======================================================================
CLASS DISTRIBUTION
======================================================================

Training Class Distribution:
PD_Label_Combined
0    65
1    62
Name: count, dtype: int64

Testing Class Distribution:
PD_Label_Combined
0     66
1    127
Name: count, dtype: int64

======================================================================
TRAINING CLASS WEIGHTS
======================================================================
{np.int64(0): np.float64(0.9769230769230769), np.int64(1): np.float64(1.0241935483870968)}

XGBoost scale_pos_weight: 1.0483870967741935

======================================================================
MISSING VALUE CHECK
======================================================================
X_train missing values: 0
X_test missing values : 0

======================================================================
FINAL VERIFICATION
======================================================================
Training rows : 127
Testing rows  : 193
Total rows    : 320

Testing row range:
0 to 192

Training row range:
193 to 319

No train-test overlap detected.
Data preparation completed successfully.


################################################
Evaluating: XGBoost
################################################

XGBoost | Fold 1/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

XGBoost | Fold 2/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

XGBoost | Fold 3/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

XGBoost | Fold 4/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

XGBoost | Fold 5/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

XGBoost | Fold 6/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

XGBoost | Fold 7/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

XGBoost | Fold 8/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

XGBoost | Fold 9/10
Accuracy            : 0.9167
Precision           : 1.0000
Sensitivity         : 0.8333
F1 Score            : 0.9091
ROC-AUC             : 0.8750
Balanced Accuracy   : 0.9167

XGBoost | Fold 10/10
Accuracy            : 0.9167
Precision           : 1.0000
Sensitivity         : 0.8333
F1 Score            : 0.9091
ROC-AUC             : 1.0000
Balanced Accuracy   : 0.9167

================================================
XGBoost - Cross-Validation (10-fold)
================================================
Accuracy            : 0.9833
Precision           : 1.0000
Recall/Sensitivity  : 0.9667
F1 Score            : 0.9818
ROC-AUC             : 0.9875
Balanced Accuracy   : 0.9833

================================================
XGBoost - Test Set Performance
================================================
Accuracy            : 0.8238 (95% CI: 0.7639-0.8711)
Precision           : 0.8252 (95% CI: 0.7546-0.8787)
Sensitivity         : 0.9291 (95% CI: 0.8708-0.9623)
Specificity         : 0.6212 (95% CI: 0.5006-0.7285)
F1 Score            : 0.8741
ROC-AUC             : 0.9399
Balanced Accuracy   : 0.7752
MCC                 : 0.5959

Confusion Matrix:
[[ 41  25]
 [  9 118]]

TN : 41
FP : 25
FN : 9
TP : 118


################################################
Evaluating: Random Forest
################################################

Random Forest | Fold 1/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Random Forest | Fold 2/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Random Forest | Fold 3/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Random Forest | Fold 4/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Random Forest | Fold 5/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Random Forest | Fold 6/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Random Forest | Fold 7/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Random Forest | Fold 8/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Random Forest | Fold 9/10
Accuracy            : 0.9167
Precision           : 1.0000
Sensitivity         : 0.8333
F1 Score            : 0.9091
ROC-AUC             : 0.8889
Balanced Accuracy   : 0.9167

Random Forest | Fold 10/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

================================================
Random Forest - Cross-Validation (10-fold)
================================================
Accuracy            : 0.9917
Precision           : 1.0000
Recall/Sensitivity  : 0.9833
F1 Score            : 0.9909
ROC-AUC             : 0.9889
Balanced Accuracy   : 0.9917

================================================
Random Forest - Test Set Performance
================================================
Accuracy            : 0.8756 (95% CI: 0.8216-0.9150)
Precision           : 0.9187 (95% CI: 0.8568-0.9552)
Sensitivity         : 0.8898 (95% CI: 0.8235-0.9332)
Specificity         : 0.8485 (95% CI: 0.7431-0.9156)
F1 Score            : 0.9040
ROC-AUC             : 0.9488
Balanced Accuracy   : 0.8691
MCC                 : 0.7284

Confusion Matrix:
[[ 56  10]
 [ 14 113]]

TN : 56
FP : 10
FN : 14
TP : 113


################################################
Evaluating: HistGradientBoosting
################################################

HistGradientBoosting | Fold 1/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

HistGradientBoosting | Fold 2/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

HistGradientBoosting | Fold 3/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

HistGradientBoosting | Fold 4/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

HistGradientBoosting | Fold 5/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

HistGradientBoosting | Fold 6/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

HistGradientBoosting | Fold 7/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

HistGradientBoosting | Fold 8/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

HistGradientBoosting | Fold 9/10
Accuracy            : 0.9167
Precision           : 1.0000
Sensitivity         : 0.8333
F1 Score            : 0.9091
ROC-AUC             : 0.9167
Balanced Accuracy   : 0.9167

HistGradientBoosting | Fold 10/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

================================================
HistGradientBoosting - Cross-Validation (10-fold)
================================================
Accuracy            : 0.9917
Precision           : 1.0000
Recall/Sensitivity  : 0.9833
F1 Score            : 0.9909
ROC-AUC             : 0.9917
Balanced Accuracy   : 0.9917

================================================
HistGradientBoosting - Test Set Performance
================================================
Accuracy            : 0.8238 (95% CI: 0.7639-0.8711)
Precision           : 0.8252 (95% CI: 0.7546-0.8787)
Sensitivity         : 0.9291 (95% CI: 0.8708-0.9623)
Specificity         : 0.6212 (95% CI: 0.5006-0.7285)
F1 Score            : 0.8741
ROC-AUC             : 0.9359
Balanced Accuracy   : 0.7752
MCC                 : 0.5959

Confusion Matrix:
[[ 41  25]
 [  9 118]]

TN : 41
FP : 25
FN : 9
TP : 118


################################################
Evaluating: Voting Fusion
################################################

Voting Fusion | Fold 1/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Voting Fusion | Fold 2/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Voting Fusion | Fold 3/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Voting Fusion | Fold 4/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Voting Fusion | Fold 5/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Voting Fusion | Fold 6/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Voting Fusion | Fold 7/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Voting Fusion | Fold 8/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Voting Fusion | Fold 9/10
Accuracy            : 0.9167
Precision           : 1.0000
Sensitivity         : 0.8333
F1 Score            : 0.9091
ROC-AUC             : 0.8611
Balanced Accuracy   : 0.9167

Voting Fusion | Fold 10/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

================================================
Voting Fusion - Cross-Validation (10-fold)
================================================
Accuracy            : 0.9917
Precision           : 1.0000
Recall/Sensitivity  : 0.9833
F1 Score            : 0.9909
ROC-AUC             : 0.9861
Balanced Accuracy   : 0.9917

================================================
Voting Fusion - Test Set Performance
================================================
Accuracy            : 0.8238 (95% CI: 0.7639-0.8711)
Precision           : 0.8252 (95% CI: 0.7546-0.8787)
Sensitivity         : 0.9291 (95% CI: 0.8708-0.9623)
Specificity         : 0.6212 (95% CI: 0.5006-0.7285)
F1 Score            : 0.8741
ROC-AUC             : 0.9448
Balanced Accuracy   : 0.7752
MCC                 : 0.5959

Confusion Matrix:
[[ 41  25]
 [  9 118]]

TN : 41
FP : 25
FN : 9
TP : 118


################################################
Evaluating: Stacking Fusion
################################################

Stacking Fusion | Fold 1/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Stacking Fusion | Fold 2/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Stacking Fusion | Fold 3/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Stacking Fusion | Fold 4/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Stacking Fusion | Fold 5/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Stacking Fusion | Fold 6/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Stacking Fusion | Fold 7/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Stacking Fusion | Fold 8/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Stacking Fusion | Fold 9/10
Accuracy            : 0.9167
Precision           : 1.0000
Sensitivity         : 0.8333
F1 Score            : 0.9091
ROC-AUC             : 0.9722
Balanced Accuracy   : 0.9167

Stacking Fusion | Fold 10/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

================================================
Stacking Fusion - Cross-Validation (10-fold)
================================================
Accuracy            : 0.9917
Precision           : 1.0000
Recall/Sensitivity  : 0.9833
F1 Score            : 0.9909
ROC-AUC             : 0.9972
Balanced Accuracy   : 0.9917

================================================
Stacking Fusion - Test Set Performance
================================================
Accuracy            : 0.8653 (95% CI: 0.8099-0.9064)
Precision           : 0.8915 (95% CI: 0.8261-0.9342)
Sensitivity         : 0.9055 (95% CI: 0.8421-0.9451)
Specificity         : 0.7879 (95% CI: 0.6749-0.8692)
F1 Score            : 0.8984
ROC-AUC             : 0.9491
Balanced Accuracy   : 0.8467
MCC                 : 0.6987

Confusion Matrix:
[[ 52  14]
 [ 12 115]]

TN : 52
FP : 14
FN : 12
TP : 115

================================================
FINAL MODEL COMPARISON
================================================

,CV Accuracy,CV Precision,CV Sensitivity,CV F1,CV ROC-AUC,CV Balanced Accuracy,Accuracy,Accuracy CI Low,Accuracy CI High,Precision,...,Specificity CI Low,Specificity CI High,F1,ROC-AUC,Balanced Accuracy,MCC,TN,FP,FN,TP
Random Forest,0.991667,1.0,0.983333,0.990909,0.988889,0.991667,0.875648,0.821640,0.914994,0.918699,...,0.743071,0.915564,0.904000,0.948819,0.869124,0.728408,56.0,10.0,14.0,113.0
Stacking Fusion,0.991667,1.0,0.983333,0.990909,0.997222,0.991667,0.865285,0.809931,0.906382,0.891473,...,0.674869,0.869220,0.898438,0.949058,0.846695,0.698662,52.0,14.0,12.0,115.0
XGBoost,0.983333,1.0,0.966667,0.981818,0.987500,0.983333,0.823834,0.763921,0.871108,0.825175,...,0.500585,0.728506,0.874074,0.939931,0.775173,0.595877,41.0,25.0,9.0,118.0
HistGradientBoosting,0.991667,1.0,0.983333,0.990909,0.991667,0.991667,0.823834,0.763921,0.871108,0.825175,...,0.500585,0.728506,0.874074,0.935874,0.775173,0.595877,41.0,25.0,9.0,118.0
Voting Fusion,0.991667,1.0,0.983333,0.990909,0.986111,0.991667,0.823834,0.763921,0.871108,0.825175,...,0.500585,0.728506,0.874074,0.944763,0.775173,0.595877,41.0,25.0,9.0,118.0