Meg-go

In [1]:
# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

In [3]:
df_rest = pd.read_csv('/content/drive/MyDrive/final_7366_meg_passive_21.csv')
df_rest.shape
df_rest.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7366 entries, 0 to 7365
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   burst_rate            7366 non-null   float64
 1   mean_burst_duration   7366 non-null   float64
 2   mean_burst_amplitude  7366 non-null   float64
 3   ibi_cv                7366 non-null   float64
 4   duty_cycle            7366 non-null   float64
 5   peak_beta_freq        7366 non-null   float64
 6   burst_dur_cv          7366 non-null   float64
 7   burst_amp_cv          7366 non-null   float64
 8   mean_ibi              7366 non-null   float64
 9   env_mean              7366 non-null   float64
 10  env_var               7366 non-null   float64
 11  env_skew              7366 non-null   float64
 12  env_kurt              7366 non-null   float64
 13  env_mod_rate          7366 non-null   float64
 14  abs_beta_power        7366 non-null   float64
 15  peak_beta_power       7366 non-null   float64
 16  beta_median_freq      7366 non-null   float64
 17  beta_bandwidth        7366 non-null   float64
 18  spectral_entropy      7366 non-null   float64
 19  spectral_flatness     7366 non-null   float64
 20  spectral_slope        7366 non-null   float64
 21  Pd_indicator_meg      7366 non-null   int64
dtypes: float64(21), int64(1)
memory usage: 1.2 MB

In [4]:
df_rest.head()

,burst_rate,mean_burst_duration,mean_burst_amplitude,ibi_cv,duty_cycle,peak_beta_freq,burst_dur_cv,burst_amp_cv,mean_ibi,env_mean,...,env_kurt,env_mod_rate,abs_beta_power,peak_beta_power,beta_median_freq,beta_bandwidth,spectral_entropy,spectral_flatness,spectral_slope,Pd_indicator_meg
0,4.148423,0.060237,3.794677e-12,0.843069,0.249889,13.574219,0.777458,0.305079,0.241037,2.043562e-12,...,3.914747,0.195312,1.874163e-25,5.265793e-25,17.773438,16.894531,7.206411,0.845531,-4.507983e-13,0
1,4.089981,0.061125,2.134013e-13,0.767457,0.250000,13.085938,0.645478,0.357364,0.244544,1.067538e-13,...,2.946252,0.976562,5.285348e-28,1.364779e-27,18.261719,16.894531,7.280654,0.891629,0.000000e+00,0
2,4.163265,0.060049,3.607224e-12,0.786598,0.250000,14.355469,0.707344,0.298498,0.240213,1.886000e-12,...,2.400834,0.976562,1.569455e-25,3.408010e-25,18.359375,16.894531,7.300536,0.905791,-2.833324e-13,0
3,4.183673,0.059707,4.139047e-12,0.750612,0.249796,13.574219,0.648125,0.300105,0.239019,2.143006e-12,...,2.218268,0.976562,2.029341e-25,4.282226e-25,18.847656,16.894531,7.330078,0.922596,-3.310818e-13,0
4,4.333024,0.057641,2.012607e-13,0.775638,0.249759,24.218750,0.692503,0.250334,0.230763,1.095083e-13,...,1.650350,0.195312,5.110654e-28,1.109302e-27,19.238281,16.894531,7.343990,0.930455,0.000000e+00,0

In [5]:
df_rest.rename(
    columns={"Pd_indicator_meg": "Status"},
    inplace=True
)

# Verify
print(df_rest.columns)

Index(['burst_rate', 'mean_burst_duration', 'mean_burst_amplitude', 'ibi_cv',
       'duty_cycle', 'peak_beta_freq', 'burst_dur_cv', 'burst_amp_cv',
       'mean_ibi', 'env_mean', 'env_var', 'env_skew', 'env_kurt',
       'env_mod_rate', 'abs_beta_power', 'peak_beta_power', 'beta_median_freq',
       'beta_bandwidth', 'spectral_entropy', 'spectral_flatness',
       'spectral_slope', 'Status'],
      dtype='object')

In [6]:
# ==========================================================
# Insert Participant_ID column
# ==========================================================

participant_ids = []

# S1–S8
for i in range(1, 9):
    participant_ids.extend([f"S{i}"] * 58)

# S10–S19
for i in range(10, 20):
    participant_ids.extend([f"S{i}"] * 58)

# S21–S33
for i in range(21, 34):
    participant_ids.extend([f"S{i}"] * 58)

# S35–S61
for i in range(35, 62):
    participant_ids.extend([f"S{i}"] * 58)

# S63–S91
for i in range(63, 92):
    participant_ids.extend([f"S{i}"] * 58)

# S93–S116
for i in range(93, 117):
    participant_ids.extend([f"S{i}"] * 58)

# S118–S125
for i in range(118, 126):
    participant_ids.extend([f"S{i}"] * 58)

# S127–S132
for i in range(127, 133):
    participant_ids.extend([f"S{i}"] * 58)

# S133 → 42 rows
participant_ids.extend(["S133"] * 58)

# S134 → 58 rows
participant_ids.extend(["S134"] * 58)

# ----------------------------------------------------------
# Verify
# ----------------------------------------------------------

print("Generated IDs :", len(participant_ids))
print("Dataset rows  :", len(df_rest))

assert len(participant_ids) == len(df_rest), "Length mismatch!"

Generated IDs : 7366
Dataset rows  : 7366

In [7]:
# ----------------------------------------------------------
# Insert as first column
# ----------------------------------------------------------

df_rest.insert(
    0,
    "Participant_ID",
    participant_ids
)

# ----------------------------------------------------------
# Verify
# ----------------------------------------------------------

print(df_rest.head(10))
print("\nUnique Participants :", df_rest["Participant_ID"].nunique())
print("\nRows per Participant:")
print(df_rest["Participant_ID"].value_counts().sort_index())

  Participant_ID  burst_rate  mean_burst_duration  mean_burst_amplitude  \
0             S1    4.148423             0.060237          3.794677e-12
1             S1    4.089981             0.061125          2.134013e-13
2             S1    4.163265             0.060049          3.607224e-12
3             S1    4.183673             0.059707          4.139047e-12
4             S1    4.333024             0.057641          2.012607e-13
5             S1    4.371058             0.057176          4.610327e-12
6             S1    4.287570             0.058308          4.451681e-12
7             S1    4.236549             0.058952          2.398121e-13
8             S1    4.117811             0.060712          5.814661e-12
9             S1    3.812616             0.065572          5.348073e-12

     ibi_cv  duty_cycle  peak_beta_freq  burst_dur_cv  burst_amp_cv  mean_ibi  \
0  0.843069    0.249889       13.574219      0.777458      0.305079  0.241037
1  0.767457    0.250000       13.085938      0.645478      0.357364  0.244544
2  0.786598    0.250000       14.355469      0.707344      0.298498  0.240213
3  0.750612    0.249796       13.574219      0.648125      0.300105  0.239019
4  0.775638    0.249759       24.218750      0.692503      0.250334  0.230763
5  0.759717    0.249921       19.238281      0.636262      0.261965  0.228784
6  0.782566    0.250000       16.601562      0.687627      0.254761  0.233256
7  0.818069    0.249754       13.085938      0.681069      0.264549  0.236023
8  0.837283    0.250000       16.210938      0.755196      0.304766  0.242808
9  0.860186    0.250000       16.015625      0.873943      0.341280  0.262299

   ...  env_kurt  env_mod_rate  abs_beta_power  peak_beta_power  \
0  ...  3.914747      0.195312    1.874163e-25     5.265793e-25
1  ...  2.946252      0.976562    5.285348e-28     1.364779e-27
2  ...  2.400834      0.976562    1.569455e-25     3.408010e-25
3  ...  2.218268      0.976562    2.029341e-25     4.282226e-25
4  ...  1.650350      0.195312    5.110654e-28     1.109302e-27
5  ...  1.627658      0.976562    2.605082e-25     4.509713e-25
6  ...  1.600730      0.195312    2.443661e-25     5.264662e-25
7  ...  1.863005      0.195312    7.199994e-28     1.984262e-27
8  ...  3.848815      0.195312    4.085239e-25     8.294189e-25
9  ...  5.042848      0.195312    3.603223e-25     9.419451e-25

   beta_median_freq  beta_bandwidth  spectral_entropy  spectral_flatness  \
0         17.773438       16.894531          7.206411           0.845531
1         18.261719       16.894531          7.280654           0.891629
2         18.359375       16.894531          7.300536           0.905791
3         18.847656       16.894531          7.330078           0.922596
4         19.238281       16.894531          7.343990           0.930455
5         19.433594       16.894531          7.375511           0.951991
6         18.847656       16.894531          7.329967           0.922764
7         18.359375       16.894531          7.271049           0.883401
8         18.652344       16.894531          7.312145           0.907734
9         17.578125       16.894531          7.194830           0.835679

   spectral_slope  Status
0   -4.507983e-13       0
1    0.000000e+00       0
2   -2.833324e-13       0
3   -3.310818e-13       0
4    0.000000e+00       0
5   -3.135452e-13       0
6   -3.925667e-13       0
7    0.000000e+00       0
8   -7.069722e-13       0
9   -8.424349e-13       0

[10 rows x 23 columns]

Unique Participants : 127

Rows per Participant:
Participant_ID
S1      58
S10     58
S100    58
S101    58
S102    58
        ..
S95     58
S96     58
S97     58
S98     58
S99     58
Name: count, Length: 127, dtype: int64

In [8]:
# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [9]:
df_rest.to_csv('/content/drive/MyDrive/final-meg-passive-7366-gc+par-id+status.csv', index=False)

In [10]:
# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [11]:
df_rest_1 = pd.read_csv('/content/drive/MyDrive/final-meg-passive-7366-gc+par-id+status.csv')
df_rest_1.info()
df_rest_1.shape
df_rest_1.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7366 entries, 0 to 7365
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Participant_ID        7366 non-null   object
 1   burst_rate            7366 non-null   float64
 2   mean_burst_duration   7366 non-null   float64
 3   mean_burst_amplitude  7366 non-null   float64
 4   ibi_cv                7366 non-null   float64
 5   duty_cycle            7366 non-null   float64
 6   peak_beta_freq        7366 non-null   float64
 7   burst_dur_cv          7366 non-null   float64
 8   burst_amp_cv          7366 non-null   float64
 9   mean_ibi              7366 non-null   float64
 10  env_mean              7366 non-null   float64
 11  env_var               7366 non-null   float64
 12  env_skew              7366 non-null   float64
 13  env_kurt              7366 non-null   float64
 14  env_mod_rate          7366 non-null   float64
 15  abs_beta_power        7366 non-null   float64
 16  peak_beta_power       7366 non-null   float64
 17  beta_median_freq      7366 non-null   float64
 18  beta_bandwidth        7366 non-null   float64
 19  spectral_entropy      7366 non-null   float64
 20  spectral_flatness     7366 non-null   float64
 21  spectral_slope        7366 non-null   float64
 22  Status                7366 non-null   int64
dtypes: float64(21), int64(1), object(1)
memory usage: 1.3+ MB

,Participant_ID,burst_rate,mean_burst_duration,mean_burst_amplitude,ibi_cv,duty_cycle,peak_beta_freq,burst_dur_cv,burst_amp_cv,mean_ibi,...,env_kurt,env_mod_rate,abs_beta_power,peak_beta_power,beta_median_freq,beta_bandwidth,spectral_entropy,spectral_flatness,spectral_slope,Status
0,S1,4.148423,0.060237,3.794677e-12,0.843069,0.249889,13.574219,0.777458,0.305079,0.241037,...,3.914747,0.195312,1.874163e-25,5.265793e-25,17.773438,16.894531,7.206411,0.845531,-4.507983e-13,0
1,S1,4.089981,0.061125,2.134013e-13,0.767457,0.250000,13.085938,0.645478,0.357364,0.244544,...,2.946252,0.976562,5.285348e-28,1.364779e-27,18.261719,16.894531,7.280654,0.891629,0.000000e+00,0
2,S1,4.163265,0.060049,3.607224e-12,0.786598,0.250000,14.355469,0.707344,0.298498,0.240213,...,2.400834,0.976562,1.569455e-25,3.408010e-25,18.359375,16.894531,7.300536,0.905791,-2.833324e-13,0
3,S1,4.183673,0.059707,4.139047e-12,0.750612,0.249796,13.574219,0.648125,0.300105,0.239019,...,2.218268,0.976562,2.029341e-25,4.282226e-25,18.847656,16.894531,7.330078,0.922596,-3.310818e-13,0
4,S1,4.333024,0.057641,2.012607e-13,0.775638,0.249759,24.218750,0.692503,0.250334,0.230763,...,1.650350,0.195312,5.110654e-28,1.109302e-27,19.238281,16.894531,7.343990,0.930455,0.000000e+00,0

In [12]:
df_rest_2 = df_rest_1.drop(
    columns=['Status']
)
df_rest_2.info()
df_rest_2.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7366 entries, 0 to 7365
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Participant_ID        7366 non-null   object
 1   burst_rate            7366 non-null   float64
 2   mean_burst_duration   7366 non-null   float64
 3   mean_burst_amplitude  7366 non-null   float64
 4   ibi_cv                7366 non-null   float64
 5   duty_cycle            7366 non-null   float64
 6   peak_beta_freq        7366 non-null   float64
 7   burst_dur_cv          7366 non-null   float64
 8   burst_amp_cv          7366 non-null   float64
 9   mean_ibi              7366 non-null   float64
 10  env_mean              7366 non-null   float64
 11  env_var               7366 non-null   float64
 12  env_skew              7366 non-null   float64
 13  env_kurt              7366 non-null   float64
 14  env_mod_rate          7366 non-null   float64
 15  abs_beta_power        7366 non-null   float64
 16  peak_beta_power       7366 non-null   float64
 17  beta_median_freq      7366 non-null   float64
 18  beta_bandwidth        7366 non-null   float64
 19  spectral_entropy      7366 non-null   float64
 20  spectral_flatness     7366 non-null   float64
 21  spectral_slope        7366 non-null   float64
dtypes: float64(21), object(1)
memory usage: 1.2+ MB

(7366, 22)

Groupshufflesplit

In [13]:
from sklearn.model_selection import GroupShuffleSplit

# -------------------------------
# GroupShuffleSplit (80:20)
# -------------------------------

gss = GroupShuffleSplit(
    n_splits=1,
    test_size=0.20,
    random_state=42
)

train_idx, test_idx = next(
    gss.split(
        df_rest_2,
        groups=df_rest_2["Participant_ID"]
    )
)

train_df = df_rest_2.iloc[train_idx].reset_index(drop=True)
test_df  = df_rest_2.iloc[test_idx].reset_index(drop=True)

# -------------------------------
# Shapes
# -------------------------------

print("Original Dataset :", df_rest_2.shape)
print("Training Dataset :", train_df.shape)
print("Testing Dataset  :", test_df.shape)

# -------------------------------
# Participant counts
# -------------------------------

train_participants = set(train_df["Participant_ID"])
test_participants  = set(test_df["Participant_ID"])

print("\nUnique Participants in Train :", len(train_participants))
print("Unique Participants in Test  :", len(test_participants))

# -------------------------------
# Leakage Check
# -------------------------------

overlap = train_participants.intersection(test_participants)

print("\nNumber of overlapping participants :", len(overlap))

if len(overlap) == 0:
    print("No participant leakage detected.")
else:
    print("Leakage detected!")
    print(overlap)

Original Dataset : (7366, 22)
Training Dataset : (5858, 22)
Testing Dataset  : (1508, 22)

Unique Participants in Train : 101
Unique Participants in Test  : 26

Number of overlapping participants : 0
No participant leakage detected.

In [14]:
print("Total unique Participant IDs:")
print(df_rest_2["Participant_ID"].nunique())

print("\nParticipant IDs:")
print(df_rest_2["Participant_ID"])

print("\nData type:")
print(df_rest_2["Participant_ID"].dtype)
print(df_rest_2["Participant_ID"].value_counts())
df_rest_2["Participant_ID"].nunique()

Total unique Participant IDs:
127

Participant IDs:
0         S1
1         S1
2         S1
3         S1
4         S1
        ...
7361    S134
7362    S134
7363    S134
7364    S134
7365    S134
Name: Participant_ID, Length: 7366, dtype: object

Data type:
object
Participant_ID
S1      58
S2      58
S3      58
S4      58
S5      58
        ..
S130    58
S131    58
S132    58
S133    58
S134    58
Name: count, Length: 127, dtype: int64

127

In [15]:
# Add Status column back from df57
df_rest_2["Status"] = df_rest_1["Status"].values

# Verify
print(df_rest_2[["Participant_ID", "Status"]].head())
print(df_rest_2.shape)

  Participant_ID  Status
0             S1       0
1             S1       0
2             S1       0
3             S1       0
4             S1       0
(7366, 23)

In [16]:
train_df["Status"] = df_rest_2.iloc[train_idx]["Status"].values
test_df["Status"]  = df_rest_2.iloc[test_idx]["Status"].values

In [17]:
print(train_df.columns)
print(test_df.columns)

Index(['Participant_ID', 'burst_rate', 'mean_burst_duration',
       'mean_burst_amplitude', 'ibi_cv', 'duty_cycle', 'peak_beta_freq',
       'burst_dur_cv', 'burst_amp_cv', 'mean_ibi', 'env_mean', 'env_var',
       'env_skew', 'env_kurt', 'env_mod_rate', 'abs_beta_power',
       'peak_beta_power', 'beta_median_freq', 'beta_bandwidth',
       'spectral_entropy', 'spectral_flatness', 'spectral_slope', 'Status'],
      dtype='object')
Index(['Participant_ID', 'burst_rate', 'mean_burst_duration',
       'mean_burst_amplitude', 'ibi_cv', 'duty_cycle', 'peak_beta_freq',
       'burst_dur_cv', 'burst_amp_cv', 'mean_ibi', 'env_mean', 'env_var',
       'env_skew', 'env_kurt', 'env_mod_rate', 'abs_beta_power',
       'peak_beta_power', 'beta_median_freq', 'beta_bandwidth',
       'spectral_entropy', 'spectral_flatness', 'spectral_slope', 'Status'],
      dtype='object')

In [18]:
import pandas as pd
import numpy as np
import shap
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
# ============================================================
# Separate Features and Labels
# ============================================================

X_train = train_df.drop(columns=["Participant_ID", "Status"])
y_train = train_df["Status"]

X_test = test_df.drop(columns=["Participant_ID", "Status"])
y_test = test_df["Status"]

# ============================================================
# Standardization
# (Fit ONLY on training data to avoid leakage)
# ============================================================

scaler = StandardScaler()

X_train_scaled = pd.DataFrame(
    scaler.fit_transform(X_train),
    columns=X_train.columns,
    index=X_train.index
)

X_test_scaled = pd.DataFrame(
    scaler.transform(X_test),
    columns=X_test.columns,
    index=X_test.index
)

# ============================================================
# Random Forest (TRAIN ONLY)
# ============================================================

rf = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train_scaled, y_train)

# ============================================================
# SHAP Feature Importance (TRAIN ONLY)
# ============================================================

# Use SHAP values for the PD class (class index = 1)
explainer = shap.TreeExplainer(rf)
shap_values = explainer.shap_values(X_train_scaled)

# Mean absolute SHAP importance for PD class
shap_importance = np.abs(shap_values[:, :, 1]).mean(axis=0)
# ============================================================
# Top 7 Features
# ============================================================

feature_importance = pd.DataFrame({
    "Feature": X_train_scaled.columns,
    "Importance": shap_importance
})

feature_importance = feature_importance.sort_values(
    by="Importance",
    ascending=False
)

top7_features = feature_importance.head(7)["Feature"].tolist()

In [19]:
# ============================================================
# Keep ONLY Top 7 Features
# ============================================================

train_top7 = train_df[["Participant_ID", "Status"] + top7_features].copy()
test_top7  = test_df[["Participant_ID", "Status"] + top7_features].copy()

print("\nTraining Shape after RF-SHAP :", train_top7.shape)
print("Testing Shape after RF-SHAP  :", test_top7.shape)

# ============================================================
# Combine Back
# ============================================================

df_rest_2_rfshap = pd.concat(
    [train_top7, test_top7],
    ignore_index=True
)

print("\nFinal Dataset Shape :", df_rest_2_rfshap.shape)

Training Shape after RF-SHAP : (5858, 9)
Testing Shape after RF-SHAP  : (1508, 9)

Final Dataset Shape : (7366, 9)

In [20]:
df_rest_2_rfshap.info()
df_rest_2_rfshap.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7366 entries, 0 to 7365
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Participant_ID     7366 non-null   object
 1   Status             7366 non-null   int64
 2   spectral_flatness  7366 non-null   float64
 3   env_kurt           7366 non-null   float64
 4   spectral_entropy   7366 non-null   float64
 5   burst_dur_cv       7366 non-null   float64
 6   env_skew           7366 non-null   float64
 7   peak_beta_freq     7366 non-null   float64
 8   ibi_cv             7366 non-null   float64
dtypes: float64(7), int64(1), object(1)
memory usage: 518.1+ KB

(7366, 9)

In [21]:
# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [22]:
print(df_rest_2_rfshap.shape)
df_rest_2_rfshap.to_csv('/content/drive/MyDrive/final-meg-passive-7366-gc+par-id+status+rf-shap_dataset_final.csv', index=False)

(7366, 9)

In [23]:
# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [24]:
df_rest_3 = pd.read_csv('/content/drive/MyDrive/final-meg-passive-7366-gc+par-id+status+rf-shap_dataset_final.csv')
df_rest_3.shape

(7366, 9)

In [25]:
# Count number of 0's and 1's in Status column
print(df_rest_3["Status"].value_counts())

Status
0    3770
1    3596
Name: count, dtype: int64