Meg-rest

In [1]:
# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

In [3]:
df_rest = pd.read_csv('/content/drive/MyDrive/final_7366_meg_rest_21.csv')
df_rest.shape
df_rest.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7366 entries, 0 to 7365
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   burst_rate            7366 non-null   float64
 1   mean_burst_duration   7366 non-null   float64
 2   mean_burst_amplitude  7366 non-null   float64
 3   ibi_cv                7366 non-null   float64
 4   duty_cycle            7366 non-null   float64
 5   peak_beta_freq        7366 non-null   float64
 6   burst_dur_cv          7366 non-null   float64
 7   burst_amp_cv          7366 non-null   float64
 8   mean_ibi              7366 non-null   float64
 9   env_mean              7366 non-null   float64
 10  env_var               7366 non-null   float64
 11  env_skew              7366 non-null   float64
 12  env_kurt              7366 non-null   float64
 13  env_mod_rate          7366 non-null   float64
 14  abs_beta_power        7366 non-null   float64
 15  peak_beta_power       7366 non-null   float64
 16  beta_median_freq      7366 non-null   float64
 17  beta_bandwidth        7366 non-null   float64
 18  spectral_entropy      7366 non-null   float64
 19  spectral_flatness     7366 non-null   float64
 20  spectral_slope        7366 non-null   float64
 21  Pd_indicator_meg      7366 non-null   int64
dtypes: float64(21), int64(1)
memory usage: 1.2 MB

In [4]:
df_rest.head()

,burst_rate,mean_burst_duration,mean_burst_amplitude,ibi_cv,duty_cycle,peak_beta_freq,burst_dur_cv,burst_amp_cv,mean_ibi,env_mean,...,env_kurt,env_mod_rate,abs_beta_power,peak_beta_power,beta_median_freq,beta_bandwidth,spectral_entropy,spectral_flatness,spectral_slope,Pd_indicator_meg
0,4.164894,0.060026,3.769601e-12,0.781471,0.250000,15.136719,0.726601,0.255265,0.239655,2.064214e-12,...,1.466246,0.195312,1.846138e-25,9.857440e-25,17.089844,16.894531,7.079007,0.780180,-4.999466e-13,0
1,4.063830,0.061518,2.130644e-13,0.733652,0.250000,13.085938,0.654570,0.368496,0.245832,1.065888e-13,...,3.071662,0.976562,5.268800e-28,1.644961e-27,17.968750,16.894531,7.198970,0.838372,0.000000e+00,0
2,4.324468,0.057811,3.549580e-12,0.779541,0.250000,16.992188,0.660386,0.289537,0.231207,1.876000e-12,...,1.901458,0.976562,1.582618e-25,4.224723e-25,18.164062,16.894531,7.247262,0.870514,-3.139988e-13,0
3,4.382979,0.056990,4.324233e-12,0.727869,0.249787,13.671875,0.604662,0.326943,0.228062,2.236881e-12,...,2.411873,0.976562,2.279249e-25,5.143276e-25,18.945312,16.894531,7.300018,0.901079,-3.811164e-13,0
4,4.361702,0.057317,1.885143e-13,0.732904,0.250000,13.183594,0.624805,0.237478,0.228602,1.018932e-13,...,1.114138,1.171875,4.502533e-28,1.245859e-27,18.847656,16.894531,7.288821,0.898278,0.000000e+00,0

In [5]:
df_rest.rename(
    columns={"Pd_indicator_meg": "Status"},
    inplace=True
)

# Verify
print(df_rest.columns)

Index(['burst_rate', 'mean_burst_duration', 'mean_burst_amplitude', 'ibi_cv',
       'duty_cycle', 'peak_beta_freq', 'burst_dur_cv', 'burst_amp_cv',
       'mean_ibi', 'env_mean', 'env_var', 'env_skew', 'env_kurt',
       'env_mod_rate', 'abs_beta_power', 'peak_beta_power', 'beta_median_freq',
       'beta_bandwidth', 'spectral_entropy', 'spectral_flatness',
       'spectral_slope', 'Status'],
      dtype='object')

In [6]:
# ==========================================================
# Insert Participant_ID column
# ==========================================================

participant_ids = []

# S1–S8
for i in range(1, 9):
    participant_ids.extend([f"S{i}"] * 58)

# S10–S19
for i in range(10, 20):
    participant_ids.extend([f"S{i}"] * 58)

# S21–S33
for i in range(21, 34):
    participant_ids.extend([f"S{i}"] * 58)

# S35–S61
for i in range(35, 62):
    participant_ids.extend([f"S{i}"] * 58)

# S63–S91
for i in range(63, 92):
    participant_ids.extend([f"S{i}"] * 58)

# S93–S116
for i in range(93, 117):
    participant_ids.extend([f"S{i}"] * 58)

# S118–S125
for i in range(118, 126):
    participant_ids.extend([f"S{i}"] * 58)

# S127–S132
for i in range(127, 133):
    participant_ids.extend([f"S{i}"] * 58)

# S133 → 42 rows
participant_ids.extend(["S133"] * 58)

# S134 → 58 rows
participant_ids.extend(["S134"] * 58)

# ----------------------------------------------------------
# Verify
# ----------------------------------------------------------

print("Generated IDs :", len(participant_ids))
print("Dataset rows  :", len(df_rest))

assert len(participant_ids) == len(df_rest), "Length mismatch!"

Generated IDs : 7366
Dataset rows  : 7366

In [7]:
# ----------------------------------------------------------
# Insert as first column
# ----------------------------------------------------------

df_rest.insert(
    0,
    "Participant_ID",
    participant_ids
)

# ----------------------------------------------------------
# Verify
# ----------------------------------------------------------

print(df_rest.head(10))
print("\nUnique Participants :", df_rest["Participant_ID"].nunique())
print("\nRows per Participant:")
print(df_rest["Participant_ID"].value_counts().sort_index())

  Participant_ID  burst_rate  mean_burst_duration  mean_burst_amplitude  \
0             S1    4.164894             0.060026          3.769601e-12
1             S1    4.063830             0.061518          2.130644e-13
2             S1    4.324468             0.057811          3.549580e-12
3             S1    4.382979             0.056990          4.324233e-12
4             S1    4.361702             0.057317          1.885143e-13
5             S1    4.329787             0.057740          4.505049e-12
6             S1    4.425532             0.056490          4.418243e-12
7             S1    4.132979             0.060489          2.413443e-13
8             S1    4.297872             0.058168          5.422376e-12
9             S1    4.058511             0.061547          4.894739e-12

     ibi_cv  duty_cycle  peak_beta_freq  burst_dur_cv  burst_amp_cv  mean_ibi  \
0  0.781471    0.250000       15.136719      0.726601      0.255265  0.239655
1  0.733652    0.250000       13.085938      0.654570      0.368496  0.245832
2  0.779541    0.250000       16.992188      0.660386      0.289537  0.231207
3  0.727869    0.249787       13.671875      0.604662      0.326943  0.228062
4  0.732904    0.250000       13.183594      0.624805      0.237478  0.228602
5  0.715429    0.250000       14.355469      0.589682      0.231118  0.230941
6  0.743334    0.250000       16.015625      0.681178      0.246778  0.225824
7  0.777770    0.250000       14.160156      0.731188      0.259278  0.242088
8  0.781027    0.250000       18.750000      0.727990      0.262130  0.232701
9  0.803391    0.249787       14.160156      0.792937      0.275299  0.246253

   ...  env_kurt  env_mod_rate  abs_beta_power  peak_beta_power  \
0  ...  1.466246      0.195312    1.846138e-25     9.857440e-25
1  ...  3.071662      0.976562    5.268800e-28     1.644961e-27
2  ...  1.901458      0.976562    1.582618e-25     4.224723e-25
3  ...  2.411873      0.976562    2.279249e-25     5.143276e-25
4  ...  1.114138      1.171875    4.502533e-28     1.245859e-27
5  ...  0.727206      0.976562    2.467218e-25     5.756799e-25
6  ...  1.469442      0.781250    2.462132e-25     5.884897e-25
7  ...  1.552569      1.171875    7.373088e-28     2.174567e-27
8  ...  1.881105      0.390625    3.794352e-25     9.479074e-25
9  ...  3.021448      0.390625    3.186687e-25     9.851119e-25

   beta_median_freq  beta_bandwidth  spectral_entropy  spectral_flatness  \
0         17.089844       16.894531          7.079007           0.780180
1         17.968750       16.894531          7.198970           0.838372
2         18.164062       16.894531          7.247262           0.870514
3         18.945312       16.894531          7.300018           0.901079
4         18.847656       16.894531          7.288821           0.898278
5         19.628906       16.894531          7.341686           0.930599
6         18.750000       16.894531          7.290112           0.898228
7         17.578125       16.894531          7.169756           0.824466
8         18.652344       16.894531          7.267977           0.879272
9         17.382812       16.894531          7.115745           0.778511

   spectral_slope  Status
0   -4.999466e-13       0
1    0.000000e+00       0
2   -3.139988e-13       0
3   -3.811164e-13       0
4    0.000000e+00       0
5   -2.799069e-13       0
6   -4.125873e-13       0
7   -5.561704e-16       0
8   -6.640117e-13       0
9   -8.606790e-13       0

[10 rows x 23 columns]

Unique Participants : 127

Rows per Participant:
Participant_ID
S1      58
S10     58
S100    58
S101    58
S102    58
        ..
S95     58
S96     58
S97     58
S98     58
S99     58
Name: count, Length: 127, dtype: int64

In [8]:
# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [9]:
df_rest.to_csv('/content/drive/MyDrive/final-meg-rest-7366-gc+par-id+status.csv', index=False)

In [10]:
# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [13]:
df_rest_1 = pd.read_csv('/content/drive/MyDrive/final-meg-rest-7366-gc+par-id+status.csv')
df_rest_1.info()
df_rest_1.shape
df_rest_1.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7366 entries, 0 to 7365
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Participant_ID        7366 non-null   object
 1   burst_rate            7366 non-null   float64
 2   mean_burst_duration   7366 non-null   float64
 3   mean_burst_amplitude  7366 non-null   float64
 4   ibi_cv                7366 non-null   float64
 5   duty_cycle            7366 non-null   float64
 6   peak_beta_freq        7366 non-null   float64
 7   burst_dur_cv          7366 non-null   float64
 8   burst_amp_cv          7366 non-null   float64
 9   mean_ibi              7366 non-null   float64
 10  env_mean              7366 non-null   float64
 11  env_var               7366 non-null   float64
 12  env_skew              7366 non-null   float64
 13  env_kurt              7366 non-null   float64
 14  env_mod_rate          7366 non-null   float64
 15  abs_beta_power        7366 non-null   float64
 16  peak_beta_power       7366 non-null   float64
 17  beta_median_freq      7366 non-null   float64
 18  beta_bandwidth        7366 non-null   float64
 19  spectral_entropy      7366 non-null   float64
 20  spectral_flatness     7366 non-null   float64
 21  spectral_slope        7366 non-null   float64
 22  Status                7366 non-null   int64
dtypes: float64(21), int64(1), object(1)
memory usage: 1.3+ MB

,Participant_ID,burst_rate,mean_burst_duration,mean_burst_amplitude,ibi_cv,duty_cycle,peak_beta_freq,burst_dur_cv,burst_amp_cv,mean_ibi,...,env_kurt,env_mod_rate,abs_beta_power,peak_beta_power,beta_median_freq,beta_bandwidth,spectral_entropy,spectral_flatness,spectral_slope,Status
0,S1,4.164894,0.060026,3.769601e-12,0.781471,0.250000,15.136719,0.726601,0.255265,0.239655,...,1.466246,0.195312,1.846138e-25,9.857440e-25,17.089844,16.894531,7.079007,0.780180,-4.999466e-13,0
1,S1,4.063830,0.061518,2.130644e-13,0.733652,0.250000,13.085938,0.654570,0.368496,0.245832,...,3.071662,0.976562,5.268800e-28,1.644961e-27,17.968750,16.894531,7.198970,0.838372,0.000000e+00,0
2,S1,4.324468,0.057811,3.549580e-12,0.779541,0.250000,16.992188,0.660386,0.289537,0.231207,...,1.901458,0.976562,1.582618e-25,4.224723e-25,18.164062,16.894531,7.247262,0.870514,-3.139988e-13,0
3,S1,4.382979,0.056990,4.324233e-12,0.727869,0.249787,13.671875,0.604662,0.326943,0.228062,...,2.411873,0.976562,2.279249e-25,5.143276e-25,18.945312,16.894531,7.300018,0.901079,-3.811164e-13,0
4,S1,4.361702,0.057317,1.885143e-13,0.732904,0.250000,13.183594,0.624805,0.237478,0.228602,...,1.114138,1.171875,4.502533e-28,1.245859e-27,18.847656,16.894531,7.288821,0.898278,0.000000e+00,0

In [14]:
df_rest_2 = df_rest_1.drop(
    columns=['Status']
)
df_rest_2.info()
df_rest_2.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7366 entries, 0 to 7365
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Participant_ID        7366 non-null   object
 1   burst_rate            7366 non-null   float64
 2   mean_burst_duration   7366 non-null   float64
 3   mean_burst_amplitude  7366 non-null   float64
 4   ibi_cv                7366 non-null   float64
 5   duty_cycle            7366 non-null   float64
 6   peak_beta_freq        7366 non-null   float64
 7   burst_dur_cv          7366 non-null   float64
 8   burst_amp_cv          7366 non-null   float64
 9   mean_ibi              7366 non-null   float64
 10  env_mean              7366 non-null   float64
 11  env_var               7366 non-null   float64
 12  env_skew              7366 non-null   float64
 13  env_kurt              7366 non-null   float64
 14  env_mod_rate          7366 non-null   float64
 15  abs_beta_power        7366 non-null   float64
 16  peak_beta_power       7366 non-null   float64
 17  beta_median_freq      7366 non-null   float64
 18  beta_bandwidth        7366 non-null   float64
 19  spectral_entropy      7366 non-null   float64
 20  spectral_flatness     7366 non-null   float64
 21  spectral_slope        7366 non-null   float64
dtypes: float64(21), object(1)
memory usage: 1.2+ MB

(7366, 22)

Groupshufflesplit

In [15]:
from sklearn.model_selection import GroupShuffleSplit

# -------------------------------
# GroupShuffleSplit (80:20)
# -------------------------------

gss = GroupShuffleSplit(
    n_splits=1,
    test_size=0.20,
    random_state=42
)

train_idx, test_idx = next(
    gss.split(
        df_rest_2,
        groups=df_rest_2["Participant_ID"]
    )
)

train_df = df_rest_2.iloc[train_idx].reset_index(drop=True)
test_df  = df_rest_2.iloc[test_idx].reset_index(drop=True)

# -------------------------------
# Shapes
# -------------------------------

print("Original Dataset :", df_rest_2.shape)
print("Training Dataset :", train_df.shape)
print("Testing Dataset  :", test_df.shape)

# -------------------------------
# Participant counts
# -------------------------------

train_participants = set(train_df["Participant_ID"])
test_participants  = set(test_df["Participant_ID"])

print("\nUnique Participants in Train :", len(train_participants))
print("Unique Participants in Test  :", len(test_participants))

# -------------------------------
# Leakage Check
# -------------------------------

overlap = train_participants.intersection(test_participants)

print("\nNumber of overlapping participants :", len(overlap))

if len(overlap) == 0:
    print("No participant leakage detected.")
else:
    print("Leakage detected!")
    print(overlap)

Original Dataset : (7366, 22)
Training Dataset : (5858, 22)
Testing Dataset  : (1508, 22)

Unique Participants in Train : 101
Unique Participants in Test  : 26

Number of overlapping participants : 0
No participant leakage detected.

In [16]:
print("Total unique Participant IDs:")
print(df_rest_2["Participant_ID"].nunique())

print("\nParticipant IDs:")
print(df_rest_2["Participant_ID"])

print("\nData type:")
print(df_rest_2["Participant_ID"].dtype)
print(df_rest_2["Participant_ID"].value_counts())
df_rest_2["Participant_ID"].nunique()

Total unique Participant IDs:
127

Participant IDs:
0         S1
1         S1
2         S1
3         S1
4         S1
        ...
7361    S134
7362    S134
7363    S134
7364    S134
7365    S134
Name: Participant_ID, Length: 7366, dtype: object

Data type:
object
Participant_ID
S1      58
S2      58
S3      58
S4      58
S5      58
        ..
S130    58
S131    58
S132    58
S133    58
S134    58
Name: count, Length: 127, dtype: int64

127

In [17]:
# Add Status column back from df57
df_rest_2["Status"] = df_rest_1["Status"].values

# Verify
print(df_rest_2[["Participant_ID", "Status"]].head())
print(df_rest_2.shape)

  Participant_ID  Status
0             S1       0
1             S1       0
2             S1       0
3             S1       0
4             S1       0
(7366, 23)

In [18]:
train_df["Status"] = df_rest_2.iloc[train_idx]["Status"].values
test_df["Status"]  = df_rest_2.iloc[test_idx]["Status"].values

In [19]:
print(train_df.columns)
print(test_df.columns)

Index(['Participant_ID', 'burst_rate', 'mean_burst_duration',
       'mean_burst_amplitude', 'ibi_cv', 'duty_cycle', 'peak_beta_freq',
       'burst_dur_cv', 'burst_amp_cv', 'mean_ibi', 'env_mean', 'env_var',
       'env_skew', 'env_kurt', 'env_mod_rate', 'abs_beta_power',
       'peak_beta_power', 'beta_median_freq', 'beta_bandwidth',
       'spectral_entropy', 'spectral_flatness', 'spectral_slope', 'Status'],
      dtype='object')
Index(['Participant_ID', 'burst_rate', 'mean_burst_duration',
       'mean_burst_amplitude', 'ibi_cv', 'duty_cycle', 'peak_beta_freq',
       'burst_dur_cv', 'burst_amp_cv', 'mean_ibi', 'env_mean', 'env_var',
       'env_skew', 'env_kurt', 'env_mod_rate', 'abs_beta_power',
       'peak_beta_power', 'beta_median_freq', 'beta_bandwidth',
       'spectral_entropy', 'spectral_flatness', 'spectral_slope', 'Status'],
      dtype='object')

In [20]:
import pandas as pd
import numpy as np
import shap
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
# ============================================================
# Separate Features and Labels
# ============================================================

X_train = train_df.drop(columns=["Participant_ID", "Status"])
y_train = train_df["Status"]

X_test = test_df.drop(columns=["Participant_ID", "Status"])
y_test = test_df["Status"]

# ============================================================
# Standardization
# (Fit ONLY on training data to avoid leakage)
# ============================================================

scaler = StandardScaler()

X_train_scaled = pd.DataFrame(
    scaler.fit_transform(X_train),
    columns=X_train.columns,
    index=X_train.index
)

X_test_scaled = pd.DataFrame(
    scaler.transform(X_test),
    columns=X_test.columns,
    index=X_test.index
)

# ============================================================
# Random Forest (TRAIN ONLY)
# ============================================================

rf = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train_scaled, y_train)

# ============================================================
# SHAP Feature Importance (TRAIN ONLY)
# ============================================================

# Use SHAP values for the PD class (class index = 1)
explainer = shap.TreeExplainer(rf)
shap_values = explainer.shap_values(X_train_scaled)

# Mean absolute SHAP importance for PD class
shap_importance = np.abs(shap_values[:, :, 1]).mean(axis=0)
# ============================================================
# Top 7 Features
# ============================================================

feature_importance = pd.DataFrame({
    "Feature": X_train_scaled.columns,
    "Importance": shap_importance
})

feature_importance = feature_importance.sort_values(
    by="Importance",
    ascending=False
)

top7_features = feature_importance.head(7)["Feature"].tolist()

In [21]:
# ============================================================
# Keep ONLY Top 7 Features
# ============================================================

train_top7 = train_df[["Participant_ID", "Status"] + top7_features].copy()
test_top7  = test_df[["Participant_ID", "Status"] + top7_features].copy()

print("\nTraining Shape after RF-SHAP :", train_top7.shape)
print("Testing Shape after RF-SHAP  :", test_top7.shape)

# ============================================================
# Combine Back
# ============================================================

df_rest_2_rfshap = pd.concat(
    [train_top7, test_top7],
    ignore_index=True
)

print("\nFinal Dataset Shape :", df_rest_2_rfshap.shape)

Training Shape after RF-SHAP : (5858, 9)
Testing Shape after RF-SHAP  : (1508, 9)

Final Dataset Shape : (7366, 9)

In [22]:
df_rest_2_rfshap.info()
df_rest_2_rfshap.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7366 entries, 0 to 7365
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Participant_ID       7366 non-null   object
 1   Status               7366 non-null   int64
 2   burst_dur_cv         7366 non-null   float64
 3   peak_beta_freq       7366 non-null   float64
 4   spectral_flatness    7366 non-null   float64
 5   spectral_entropy     7366 non-null   float64
 6   burst_rate           7366 non-null   float64
 7   ibi_cv               7366 non-null   float64
 8   mean_burst_duration  7366 non-null   float64
dtypes: float64(7), int64(1), object(1)
memory usage: 518.1+ KB

(7366, 9)

In [23]:
# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [24]:
print(df_rest_2_rfshap.shape)
df_rest_2_rfshap.to_csv('/content/drive/MyDrive/final-meg-rest-7366-gc+par-id+status+rf-shap_dataset_final.csv', index=False)

(7366, 9)

In [25]:
# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [28]:
df_rest_3 = pd.read_csv('/content/drive/MyDrive/final-meg-rest-7366-gc+par-id+status+rf-shap_dataset_final.csv')
df_rest_3.shape

(7366, 9)

In [30]:
# Count number of 0's and 1's in Status column
print(df_rest_3["Status"].value_counts())

Status
0    3770
1    3596
Name: count, dtype: int64