***Meg-Go task***

With MIRA-Net

In [1]:
# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

final_meg_df = pd.read_csv('/content/drive/MyDrive/final_meg_go_21_par-lev_final.csv')

print("Loaded data shape:", final_meg_df.shape)
print(final_meg_df.head())

Loaded data shape: (127, 106)
   burst_rate_L_mean  burst_rate_L_std  burst_rate_R_mean  burst_rate_R_std  \
0           4.407992          0.146692           4.465646          0.117633
1           3.793146          0.367291           3.882352          0.410346
2           4.517238          0.166177           4.604832          0.117440
3           4.096736          0.237234           4.162662          0.205532
4           5.911883          7.663211           4.961802          6.536711

   burst_rate_asym  mean_burst_duration_L_mean  mean_burst_duration_L_std  \
0        -0.006497                    0.056773                   0.001915
1        -0.011622                    0.066523                   0.006423
2        -0.009602                    0.055419                   0.002108
3        -0.007982                    0.061230                   0.003630
4         0.087374                    0.004383                   0.001650

   mean_burst_duration_R_mean  mean_burst_duration_R_std  \
0                    0.056017                   0.001495
1                    0.065139                   0.007151
2                    0.054324                   0.001410
3                    0.060201                   0.002986
4                    0.004410                   0.001619

   mean_burst_duration_asym  ...  spectral_flatness_L_std  \
0                  0.006700  ...                 0.054968
1                  0.010517  ...                 0.042931
2                  0.009974  ...                 0.021047
3                  0.008477  ...                 0.060342
4                 -0.003085  ...                 0.003310

   spectral_flatness_R_mean  spectral_flatness_R_std  spectral_flatness_asym  \
0                  0.948269                 0.039871               -0.007503
1                  0.931122                 0.042574               -0.003631
2                  0.972496                 0.017510               -0.000729
3                  0.862457                 0.051705               -0.004438
4                  0.935127                 0.007780               -0.000536

   spectral_slope_L_mean  spectral_slope_L_std  spectral_slope_R_mean  \
0          -2.705737e-13          3.891970e-13          -1.298295e-13
1          -4.771582e-13          5.571425e-13          -4.549048e-13
2          -9.685957e-14          1.288054e-13          -8.093741e-14
3          -7.628670e-13          9.692914e-13          -4.191067e-13
4          -1.331795e+00          5.033830e-01          -1.325357e+00

   spectral_slope_R_std  spectral_slope_asym  Pd_indicator_meg
0          1.789942e-13            -0.000014                 0
1          5.509281e-13            -0.000002                 0
2          9.458701e-14            -0.000002                 0
3          4.995036e-13            -0.000034                 1
4          5.015086e-01             0.002423                 1

[5 rows x 106 columns]

In [4]:
# ============================================================
#     SIMPLE + STABLE DANN + SCL + MLP CLASSIFIER
#     CROSS-MODAL + CROSS-PARTICIPANT ANALYSIS
# ============================================================

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from torch.autograd import Function
import torch.nn.functional as F

import numpy as np

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# ============================================================
# LOAD DATA
# ============================================================

# First 7 columns -> Features
# Last column     -> PD / HC labels


# ============================================================
# MEG FEATURES AND LABELS
# ============================================================

# All columns except the last one are MEG features
X_meg = final_meg_df.iloc[:, :-1].copy()

# Convert features to numeric
X_meg = X_meg.apply(
    pd.to_numeric,
    errors="coerce"
)

# Replace +inf and -inf with NaN
X_meg = X_meg.replace(
    [np.inf, -np.inf],
    np.nan
)

# ------------------------------------------------------------
# Check invalid values
# ------------------------------------------------------------

print(
    "NaN values before cleaning:",
    X_meg.isna().sum().sum()
)

print(
    "Infinite values before cleaning:",
    np.isinf(
        X_meg.select_dtypes(include=np.number)
    ).sum().sum()
)

# ------------------------------------------------------------
# Replace NaN with column median
# ------------------------------------------------------------

X_meg = X_meg.fillna(
    X_meg.median(numeric_only=True)
)

# Any remaining NaN -> 0
X_meg = X_meg.fillna(0)

# Convert to float64 to avoid float32 overflow
X_meg = X_meg.values.astype(np.float64)

# Labels
y_meg = final_meg_df.iloc[:, -1].values.astype(np.int64)

# ============================================================
# FINAL CHECK BEFORE STANDARDIZATION
# ============================================================

print(
    "All MEG values finite:",
    np.isfinite(X_meg).all()
)

print(
    "Maximum absolute MEG value:",
    np.max(np.abs(X_meg))
)

# ============================================================
# STANDARDIZATION
# ============================================================

scaler_meg = StandardScaler()

X_meg = scaler_meg.fit_transform(
    X_meg
)

# ============================================================
# FINAL CHECK AFTER STANDARDIZATION
# ============================================================

print(
    "All standardized values finite:",
    np.isfinite(X_meg).all()
)

print(
    "Standardized MEG shape:",
    X_meg.shape
)

# ============================================================
# DOMAIN LABELS
# ============================================================

# 0 -> Acoustic
# 1 -> MEG

domain_meg = np.ones(
    len(X_meg)
)

# ============================================================
# COMBINE
# ============================================================

X_all = np.vstack([

    X_meg
]).astype(np.float32)

task_labels = np.hstack([

    y_meg
]).astype(np.int64)

domain_labels = np.hstack([

    domain_meg
]).astype(np.int64)

# ============================================================
# TENSORS
# ============================================================

X_all_tensor = torch.tensor(
    X_all
).float().to(device)

task_labels_tensor = torch.tensor(
    task_labels
).long().to(device)

domain_labels_tensor = torch.tensor(
    domain_labels
).long().to(device)

# ============================================================
# GRADIENT REVERSAL
# ============================================================

class GradReverse(Function):

    @staticmethod
    def forward(ctx, x, lambd):

        ctx.lambd = lambd

        return x.view_as(x)

    @staticmethod
    def backward(ctx, grad_output):

        return -ctx.lambd * grad_output, None

def grad_reverse(x, lambd):

    return GradReverse.apply(x, lambd)

# ============================================================
# SIMPLE RESIDUAL BLOCK
# ============================================================

class ResidualBlock(nn.Module):

    def __init__(self, dim):

        super().__init__()

        self.block = nn.Sequential(

            nn.Linear(dim, dim),
            nn.ReLU(),

            nn.Linear(dim, dim)
        )

    def forward(self, x):

        return F.relu(
            self.block(x) + x
        )

# ============================================================
# DANN + SCL MODEL
# ============================================================

class DANNContrastive(nn.Module):

    def __init__(self, input_dim, latent_dim=32):

        super().__init__()

        # ====================================================
        # SIMPLE ENCODER
        # ====================================================

        self.encoder = nn.Sequential(

            nn.Linear(input_dim, 128),
            nn.ReLU(),

            ResidualBlock(128),

            nn.Linear(128, 64),
            nn.ReLU(),

            nn.Dropout(0.1),

            nn.Linear(64, latent_dim)
        )

        # ====================================================
        # TASK HEAD
        # ====================================================

        self.task_head = nn.Sequential(

            nn.Linear(latent_dim, 32),
            nn.ReLU(),

            nn.Dropout(0.2),

            nn.Linear(32, 2)
        )

        # ====================================================
        # DOMAIN HEAD
        # ====================================================

        self.domain_head = nn.Sequential(

            nn.Linear(latent_dim, 16),
            nn.ReLU(),

            nn.Linear(16, 2)
        )

    def forward(self, x, lambd=1.0):

        z = self.encoder(x)

        # L2 NORMALIZATION

        z_norm = F.normalize(
            z,
            p=2,
            dim=1
        )

        # DANN

        rev_z = grad_reverse(
            z_norm,
            lambd
        )

        task_out = self.task_head(z_norm)

        domain_out = self.domain_head(rev_z)

        return task_out, domain_out, z_norm

# ============================================================
# SUPERVISED CONTRASTIVE LOSS
# ============================================================

class SupConLoss(nn.Module):

    def __init__(self, temperature=0.07):

        super().__init__()

        self.temperature = temperature

    def forward(self, features, labels):

        device = features.device

        labels = labels.contiguous().view(-1, 1)

        mask = torch.eq(
            labels,
            labels.T
        ).float().to(device)

        similarity = torch.matmul(
            features,
            features.T
        ) / self.temperature

        logits_max, _ = torch.max(
            similarity,
            dim=1,
            keepdim=True
        )

        logits = similarity - logits_max.detach()

        logits_mask = torch.ones_like(mask) - torch.eye(
            mask.shape[0]
        ).to(device)

        mask = mask * logits_mask

        exp_logits = torch.exp(logits) * logits_mask

        log_prob = logits - torch.log(
            exp_logits.sum(1, keepdim=True) + 1e-8
        )

        mean_log_prob_pos = (
            mask * log_prob
        ).sum(1) / (mask.sum(1) + 1e-8)

        loss = -mean_log_prob_pos.mean()

        return loss

# ============================================================
# DATA LOADER
# ============================================================

dataset = TensorDataset(
    X_all_tensor,
    task_labels_tensor,
    domain_labels_tensor
)

loader = DataLoader(
    dataset,
    batch_size=128,
    shuffle=True
)

# ============================================================
# MODEL
# ============================================================

model = DANNContrastive(
    input_dim=X_all.shape[1],
    latent_dim=32
).to(device)

# ============================================================
# OPTIMIZER
# ============================================================

optimizer = optim.Adam(
    model.parameters(),
    lr=1e-3,
    weight_decay=1e-4
)

# ============================================================
# LOSSES
# ============================================================

task_loss_fn = nn.CrossEntropyLoss()

domain_loss_fn = nn.CrossEntropyLoss()

contrastive_loss_fn = SupConLoss(
    temperature=0.07
)

epochs = 120

print("\nTraining Started...\n")

# ============================================================
# TRAINING
# ============================================================

for epoch in range(epochs):

    model.train()

    total_correct = 0
    total_samples = 0

    # ========================================================
    # WEAKER DANN
    # ========================================================

    p = min(epoch / 50.0, 1.0)

    lambd = 0.25 * (
        2 / (1 + np.exp(-10 * p)) - 1
    )

    for xb, y_task, y_dom in loader:

        optimizer.zero_grad()

        task_out, dom_out, z = model(
            xb,
            lambd
        )

        # ====================================================
        # LOSSES
        # ====================================================

        loss_task = task_loss_fn(
            task_out,
            y_task
        )

        loss_domain = domain_loss_fn(
            dom_out,
            y_dom
        )

        loss_contrastive = contrastive_loss_fn(
            z,
            y_task
        )

        # ====================================================
        # FINAL LOSS
        # ====================================================

        loss = (
            3.0 * loss_task +
            0.25 * loss_domain +
            0.55 * loss_contrastive
        )

        loss.backward()

        optimizer.step()

        preds = task_out.argmax(1)

        total_correct += (
            preds == y_task
        ).sum().item()

        total_samples += len(y_task)

    acc = total_correct / total_samples

    print(
        f"Epoch {epoch+1}/{epochs} "
        f"| λ={lambd:.3f} "
        f"| Acc={acc:.4f}"
    )

# ============================================================
# EXTRACT LATENT FEATURES
# ============================================================

model.eval()

with torch.no_grad():

    fused_meg_32D = model(
        torch.tensor(X_meg).float().to(device),
        0
    )[2].cpu().numpy()

# ============================================================
# COMBINE LATENTS
# ============================================================

X_fused = np.vstack([

    fused_meg_32D
])

y_fused = np.hstack([

    y_meg
])

# ============================================================
# SIMPLE MLP CLASSIFIER
# ============================================================

class FinalMLP(nn.Module):

    def __init__(self, input_dim=32):

        super().__init__()

        self.net = nn.Sequential(

            nn.Linear(input_dim, 64),
            nn.ReLU(),

            nn.Dropout(0.2),

            nn.Linear(64, 32),
            nn.ReLU(),

            nn.Linear(32, 2)
        )

    def forward(self, x):

        return self.net(x)

# ============================================================
# CROSS PARTICIPANT EVALUATION
# ============================================================

print("\n======================================")
print(" CROSS PARTICIPANT ANALYSIS")
print("======================================\n")

skf = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

accs = []
precs = []
recs = []
f1s = []
aucs = []

fold = 1

for train_idx, test_idx in skf.split(X_fused, y_fused):

    X_train = torch.tensor(
        X_fused[train_idx]
    ).float().to(device)

    X_test = torch.tensor(
        X_fused[test_idx]
    ).float().to(device)

    y_train = torch.tensor(
        y_fused[train_idx]
    ).long().to(device)

    y_test = y_fused[test_idx]

    clf = FinalMLP().to(device)

    optimizer_clf = optim.Adam(
        clf.parameters(),
        lr=1e-3
    )

    criterion = nn.CrossEntropyLoss()

    # ========================================================
    # TRAIN MLP
    # ========================================================

    clf.train()

    for epoch in range(80):

        optimizer_clf.zero_grad()

        outputs = clf(X_train)

        loss = criterion(
            outputs,
            y_train
        )

        loss.backward()

        optimizer_clf.step()

    # ========================================================
    # TEST
    # ========================================================

    clf.eval()

    with torch.no_grad():

        outputs = clf(X_test)

        probs = F.softmax(
            outputs,
            dim=1
        )[:, 1].cpu().numpy()

        preds = outputs.argmax(1).cpu().numpy()

    acc = accuracy_score(y_test, preds)

    prec = precision_score(y_test, preds)

    rec = recall_score(y_test, preds)

    f1 = f1_score(y_test, preds)

    auc = roc_auc_score(y_test, probs)

    accs.append(acc)
    precs.append(prec)
    recs.append(rec)
    f1s.append(f1)
    aucs.append(auc)

    print(f"Fold {fold}")

    print(f"Accuracy  : {acc:.4f}")
    print(f"Precision : {prec:.4f}")
    print(f"Recall    : {rec:.4f}")
    print(f"F1-Score  : {f1:.4f}")
    print(f"AUC       : {auc:.4f}")

    print()

    fold += 1

# ============================================================
# FINAL RESULTS
# ============================================================

print("\n======================================")
print(" FINAL RESULTS")
print("======================================\n")

print(f"Mean Accuracy  : {np.mean(accs)*100:.2f}%")
print(f"Mean Precision : {np.mean(precs)*100:.2f}%")
print(f"Mean Recall    : {np.mean(recs)*100:.2f}%")
print(f"Mean F1-Score  : {np.mean(f1s)*100:.2f}%")
print(f"Mean AUC       : {np.mean(aucs)*100:.2f}%")

print("\n======================================")
print(" LATENT SHAPES")
print("======================================\n")


print("MEG      :", fused_meg_32D.shape)

NaN values before cleaning: 0
Infinite values before cleaning: 0
All MEG values finite: True
Maximum absolute MEG value: 1.1251926520717155e+55
All standardized values finite: True
Standardized MEG shape: (127, 105)

Training Started...

Epoch 1/120 | λ=0.000 | Acc=0.4882
Epoch 2/120 | λ=0.025 | Acc=0.5197
Epoch 3/120 | λ=0.049 | Acc=0.4882
Epoch 4/120 | λ=0.073 | Acc=0.5354
Epoch 5/120 | λ=0.095 | Acc=0.5591
Epoch 6/120 | λ=0.116 | Acc=0.5669
Epoch 7/120 | λ=0.134 | Acc=0.5669
Epoch 8/120 | λ=0.151 | Acc=0.5748
Epoch 9/120 | λ=0.166 | Acc=0.5669
Epoch 10/120 | λ=0.179 | Acc=0.5591
Epoch 11/120 | λ=0.190 | Acc=0.5512
Epoch 12/120 | λ=0.200 | Acc=0.5984
Epoch 13/120 | λ=0.208 | Acc=0.5748
Epoch 14/120 | λ=0.215 | Acc=0.6535
Epoch 15/120 | λ=0.221 | Acc=0.6378
Epoch 16/120 | λ=0.226 | Acc=0.6850
Epoch 17/120 | λ=0.230 | Acc=0.6614
Epoch 18/120 | λ=0.234 | Acc=0.7638
Epoch 19/120 | λ=0.237 | Acc=0.7795
Epoch 20/120 | λ=0.239 | Acc=0.8189
Epoch 21/120 | λ=0.241 | Acc=0.8031
Epoch 22/120 | λ=0.243 | Acc=0.7953
Epoch 23/120 | λ=0.244 | Acc=0.8268
Epoch 24/120 | λ=0.245 | Acc=0.8740
Epoch 25/120 | λ=0.246 | Acc=0.8661
Epoch 26/120 | λ=0.247 | Acc=0.8898
Epoch 27/120 | λ=0.247 | Acc=0.8898
Epoch 28/120 | λ=0.248 | Acc=0.9213
Epoch 29/120 | λ=0.248 | Acc=0.9606
Epoch 30/120 | λ=0.248 | Acc=0.9606
Epoch 31/120 | λ=0.249 | Acc=0.9606
Epoch 32/120 | λ=0.249 | Acc=0.9449
Epoch 33/120 | λ=0.249 | Acc=0.9449
Epoch 34/120 | λ=0.249 | Acc=0.9764
Epoch 35/120 | λ=0.249 | Acc=0.9843
Epoch 36/120 | λ=0.250 | Acc=0.9843
Epoch 37/120 | λ=0.250 | Acc=0.9764
Epoch 38/120 | λ=0.250 | Acc=0.9921
Epoch 39/120 | λ=0.250 | Acc=0.9921
Epoch 40/120 | λ=0.250 | Acc=0.9921
Epoch 41/120 | λ=0.250 | Acc=0.9921
Epoch 42/120 | λ=0.250 | Acc=0.9921
Epoch 43/120 | λ=0.250 | Acc=0.9921
Epoch 44/120 | λ=0.250 | Acc=0.9921
Epoch 45/120 | λ=0.250 | Acc=0.9921
Epoch 46/120 | λ=0.250 | Acc=0.9921
Epoch 47/120 | λ=0.250 | Acc=1.0000
Epoch 48/120 | λ=0.250 | Acc=0.9921
Epoch 49/120 | λ=0.250 | Acc=0.9921
Epoch 50/120 | λ=0.250 | Acc=0.9921
Epoch 51/120 | λ=0.250 | Acc=0.9921
Epoch 52/120 | λ=0.250 | Acc=0.9921
Epoch 53/120 | λ=0.250 | Acc=0.9921
Epoch 54/120 | λ=0.250 | Acc=0.9921
Epoch 55/120 | λ=0.250 | Acc=0.9921
Epoch 56/120 | λ=0.250 | Acc=0.9921
Epoch 57/120 | λ=0.250 | Acc=0.9921
Epoch 58/120 | λ=0.250 | Acc=0.9921
Epoch 59/120 | λ=0.250 | Acc=0.9921
Epoch 60/120 | λ=0.250 | Acc=0.9843
Epoch 61/120 | λ=0.250 | Acc=0.9921
Epoch 62/120 | λ=0.250 | Acc=0.9921
Epoch 63/120 | λ=0.250 | Acc=0.9921
Epoch 64/120 | λ=0.250 | Acc=0.9921
Epoch 65/120 | λ=0.250 | Acc=0.9921
Epoch 66/120 | λ=0.250 | Acc=0.9921
Epoch 67/120 | λ=0.250 | Acc=0.9921
Epoch 68/120 | λ=0.250 | Acc=0.9921
Epoch 69/120 | λ=0.250 | Acc=0.9921
Epoch 70/120 | λ=0.250 | Acc=0.9843
Epoch 71/120 | λ=0.250 | Acc=0.9921
Epoch 72/120 | λ=0.250 | Acc=0.9921
Epoch 73/120 | λ=0.250 | Acc=0.9921
Epoch 74/120 | λ=0.250 | Acc=0.9921
Epoch 75/120 | λ=0.250 | Acc=0.9921
Epoch 76/120 | λ=0.250 | Acc=0.9921
Epoch 77/120 | λ=0.250 | Acc=0.9921
Epoch 78/120 | λ=0.250 | Acc=0.9921
Epoch 79/120 | λ=0.250 | Acc=0.9921
Epoch 80/120 | λ=0.250 | Acc=0.9921
Epoch 81/120 | λ=0.250 | Acc=0.9921
Epoch 82/120 | λ=0.250 | Acc=0.9921
Epoch 83/120 | λ=0.250 | Acc=0.9843
Epoch 84/120 | λ=0.250 | Acc=0.9921
Epoch 85/120 | λ=0.250 | Acc=0.9921
Epoch 86/120 | λ=0.250 | Acc=0.9921
Epoch 87/120 | λ=0.250 | Acc=0.9921
Epoch 88/120 | λ=0.250 | Acc=0.9921
Epoch 89/120 | λ=0.250 | Acc=0.9921
Epoch 90/120 | λ=0.250 | Acc=0.9921
Epoch 91/120 | λ=0.250 | Acc=0.9921
Epoch 92/120 | λ=0.250 | Acc=0.9921
Epoch 93/120 | λ=0.250 | Acc=0.9921
Epoch 94/120 | λ=0.250 | Acc=0.9921
Epoch 95/120 | λ=0.250 | Acc=0.9921
Epoch 96/120 | λ=0.250 | Acc=0.9921
Epoch 97/120 | λ=0.250 | Acc=0.9921
Epoch 98/120 | λ=0.250 | Acc=0.9843
Epoch 99/120 | λ=0.250 | Acc=0.9921
Epoch 100/120 | λ=0.250 | Acc=0.9921
Epoch 101/120 | λ=0.250 | Acc=0.9764
Epoch 102/120 | λ=0.250 | Acc=0.9921
Epoch 103/120 | λ=0.250 | Acc=0.9921
Epoch 104/120 | λ=0.250 | Acc=0.9921
Epoch 105/120 | λ=0.250 | Acc=0.9921
Epoch 106/120 | λ=0.250 | Acc=0.9921
Epoch 107/120 | λ=0.250 | Acc=0.9921
Epoch 108/120 | λ=0.250 | Acc=0.9921
Epoch 109/120 | λ=0.250 | Acc=0.9921
Epoch 110/120 | λ=0.250 | Acc=0.9921
Epoch 111/120 | λ=0.250 | Acc=0.9921
Epoch 112/120 | λ=0.250 | Acc=0.9843
Epoch 113/120 | λ=0.250 | Acc=0.9843
Epoch 114/120 | λ=0.250 | Acc=0.9921
Epoch 115/120 | λ=0.250 | Acc=0.9921
Epoch 116/120 | λ=0.250 | Acc=0.9921
Epoch 117/120 | λ=0.250 | Acc=0.9921
Epoch 118/120 | λ=0.250 | Acc=0.9921
Epoch 119/120 | λ=0.250 | Acc=0.9921
Epoch 120/120 | λ=0.250 | Acc=0.9921

======================================
 CROSS PARTICIPANT ANALYSIS
======================================

Fold 1
Accuracy  : 1.0000
Precision : 1.0000
Recall    : 1.0000
F1-Score  : 1.0000
AUC       : 1.0000

Fold 2
Accuracy  : 1.0000
Precision : 1.0000
Recall    : 1.0000
F1-Score  : 1.0000
AUC       : 1.0000

Fold 3
Accuracy  : 1.0000
Precision : 1.0000
Recall    : 1.0000
F1-Score  : 1.0000
AUC       : 1.0000

Fold 4
Accuracy  : 1.0000
Precision : 1.0000
Recall    : 1.0000
F1-Score  : 1.0000
AUC       : 1.0000

Fold 5
Accuracy  : 0.9600
Precision : 1.0000
Recall    : 0.9167
F1-Score  : 0.9565
AUC       : 1.0000


======================================
 FINAL RESULTS
======================================

Mean Accuracy  : 99.20%
Mean Precision : 100.00%
Mean Recall    : 98.33%
Mean F1-Score  : 99.13%
Mean AUC       : 100.00%

======================================
 LATENT SHAPES
======================================

MEG      : (127, 32)

In [5]:
import torch

# Assuming fused_acoustic_32D and fused_meg_32D are numpy arrays of shape (7350, 32)

# Step 1: Convert numpy arrays to torch tensors (float32)

fused_meg_tensor = torch.from_numpy(fused_meg_32D).float()

# Step 2: Concatenate row-wise (along dim=0)
fused_output_tensor = torch.cat([fused_meg_tensor], dim=0)  # Shape: (14700, 32)

# Step 3: Print shape and dtype
print(fused_output_tensor.shape)  # torch.Size([14700, 32])
print(fused_output_tensor.dtype)  # torch.float32

torch.Size([127, 32])
torch.float32

In [6]:
import torch
import numpy as np

# ------------------------
# Step 1: Extract targets correctly
# ------------------------

# Acoustic target from df_acoustic_top7 (last column)


# MEG target from final_meg_df (last column)
y_meg = final_meg_df.iloc[:, -1].values.astype(np.int32)           # (7350,)

# Convert to tensors (reshape to column)
 # (7350, 1)
meg_target_tensor      = torch.tensor(y_meg).long().reshape(-1, 1)        # (7350, 1)

# ------------------------
# Step 2: Convert 32D latent features to tensors
# ------------------------

# (7350, 32)
fused_meg_tensor      = torch.from_numpy(fused_meg_32D).float()       # (7350, 32)

# ------------------------
# Step 3: Attach target columns
# ------------------------

# Concatenate latent features with target

meg_full      = torch.cat([fused_meg_tensor,      meg_target_tensor.float()],      dim=1)  # (7350, 65)

# ------------------------
# Step 4: Concatenate both datasets
# ------------------------

fused_df = torch.cat([meg_full], dim=0)  # (14700, 65)

# ------------------------
# Step 5: Separate features and labels for PyTorch
# ------------------------

X = fused_df[:, :-1].float()   # Features (32D) -> float32
y = fused_df[:, -1].long()     # Target -> int32

# ------------------------
# Step 6: Print shapes and dtypes
# ------------------------

print(f"Features shape: {X.shape}, dtype: {X.dtype}")  # (14700, 32), float32
print(f"Labels shape: {y.shape}, dtype: {y.dtype}")    # (14700,), int32

Features shape: torch.Size([127, 32]), dtype: torch.float32
Labels shape: torch.Size([127]), dtype: torch.int64

In [7]:
import torch
import pandas as pd

# fused_df shape = (14700, 33)

# Step 6: Convert fused tensor to numpy
fused_df_np = fused_df.numpy()

# Step 7: Create correct column names for 32 latent features + 1 label
feature_names = [f"feat_{i}" for i in range(32)]
feature_names.append("PD_Label_Combined")

# Step 8: Convert to DataFrame
fused_df_named = pd.DataFrame(fused_df_np, columns=feature_names)

# Step 9: Verify
print(fused_df_named.shape)
print(fused_df_named.head())
print(fused_df_named.tail())

(127, 33)
     feat_0    feat_1    feat_2    feat_3    feat_4    feat_5    feat_6  \
0 -0.236623  0.023379 -0.048138  0.088845  0.241576 -0.072249 -0.098408
1 -0.284421  0.029994 -0.035150  0.090232  0.252488 -0.076604 -0.106278
2 -0.256516  0.028062 -0.028662  0.089553  0.260864 -0.074782 -0.104450
3  0.120316 -0.223770  0.189287 -0.104960 -0.053971  0.150660  0.129517
4  0.115630 -0.223906  0.177751 -0.130675 -0.060676  0.168142  0.130759

     feat_7    feat_8    feat_9  ...   feat_23   feat_24   feat_25   feat_26  \
0  0.227777  0.212278 -0.184977  ...  0.141964 -0.188867  0.169329  0.208928
1  0.214887  0.199279 -0.193147  ...  0.161650 -0.182403  0.151206  0.198874
2  0.210737  0.201964 -0.212622  ...  0.144977 -0.196561  0.149710  0.197808
3  0.199552 -0.040106  0.129700  ... -0.133559  0.171421  0.296541 -0.112894
4  0.206628 -0.025384  0.126940  ... -0.113671  0.182526  0.312205 -0.106975

    feat_27   feat_28   feat_29   feat_30   feat_31  PD_Label_Combined
0  0.111700 -0.204104  0.016686  0.161542  0.192166                0.0
1  0.116208 -0.207540  0.045727  0.147894  0.184814                0.0
2  0.152996 -0.208476  0.040235  0.149959  0.162922                0.0
3  0.267845 -0.133356  0.253306  0.257301  0.222498                1.0
4  0.292750 -0.141752  0.245937  0.238240  0.222659                1.0

[5 rows x 33 columns]
       feat_0    feat_1    feat_2    feat_3    feat_4    feat_5    feat_6  \
122 -0.270131 -0.006070 -0.023047  0.085126  0.224865 -0.077238 -0.115021
123  0.129568 -0.242900  0.176173 -0.099788 -0.060611  0.160431  0.134572
124 -0.242971  0.042099 -0.027964  0.100685  0.250826 -0.072278 -0.104814
125 -0.268310  0.023536 -0.044704  0.074981  0.240040 -0.073943 -0.115127
126  0.114824 -0.239426  0.186669 -0.091256 -0.057072  0.154379  0.130329

       feat_7    feat_8    feat_9  ...   feat_23   feat_24   feat_25  \
122  0.225463  0.210982 -0.184537  ...  0.165274 -0.196039  0.149703
123  0.197650 -0.043784  0.139968  ... -0.141144  0.149727  0.291574
124  0.216519  0.195686 -0.197824  ...  0.129658 -0.201904  0.163564
125  0.217077  0.204066 -0.190368  ...  0.139824 -0.181581  0.166804
126  0.202217 -0.041014  0.123211  ... -0.139348  0.155398  0.297114

      feat_26   feat_27   feat_28   feat_29   feat_30   feat_31  \
122  0.182495  0.110671 -0.194879  0.036922  0.176170  0.212116
123 -0.128966  0.266363 -0.139483  0.245112  0.268691  0.209144
124  0.223822  0.135752 -0.203248  0.029905  0.147424  0.178414
125  0.208219  0.132319 -0.204232  0.037926  0.162084  0.179418
126 -0.116017  0.258818 -0.143153  0.247906  0.265424  0.226547

     PD_Label_Combined
122                0.0
123                1.0
124                0.0
125                0.0
126                1.0

[5 rows x 33 columns]

In [8]:
# Make a copy to be safe (optional)
fused_df_named_int = fused_df_named.copy()

# Convert only the last column to int
fused_df_named_int['PD_Label_Combined'] = fused_df_named_int['PD_Label_Combined'].astype(int)

# Verify
print(fused_df_named_int.dtypes)
print(fused_df_named_int.head())

feat_0               float32
feat_1               float32
feat_2               float32
feat_3               float32
feat_4               float32
feat_5               float32
feat_6               float32
feat_7               float32
feat_8               float32
feat_9               float32
feat_10              float32
feat_11              float32
feat_12              float32
feat_13              float32
feat_14              float32
feat_15              float32
feat_16              float32
feat_17              float32
feat_18              float32
feat_19              float32
feat_20              float32
feat_21              float32
feat_22              float32
feat_23              float32
feat_24              float32
feat_25              float32
feat_26              float32
feat_27              float32
feat_28              float32
feat_29              float32
feat_30              float32
feat_31              float32
PD_Label_Combined      int64
dtype: object
     feat_0    feat_1    feat_2    feat_3    feat_4    feat_5    feat_6  \
0 -0.236623  0.023379 -0.048138  0.088845  0.241576 -0.072249 -0.098408
1 -0.284421  0.029994 -0.035150  0.090232  0.252488 -0.076604 -0.106278
2 -0.256516  0.028062 -0.028662  0.089553  0.260864 -0.074782 -0.104450
3  0.120316 -0.223770  0.189287 -0.104960 -0.053971  0.150660  0.129517
4  0.115630 -0.223906  0.177751 -0.130675 -0.060676  0.168142  0.130759

     feat_7    feat_8    feat_9  ...   feat_23   feat_24   feat_25   feat_26  \
0  0.227777  0.212278 -0.184977  ...  0.141964 -0.188867  0.169329  0.208928
1  0.214887  0.199279 -0.193147  ...  0.161650 -0.182403  0.151206  0.198874
2  0.210737  0.201964 -0.212622  ...  0.144977 -0.196561  0.149710  0.197808
3  0.199552 -0.040106  0.129700  ... -0.133559  0.171421  0.296541 -0.112894
4  0.206628 -0.025384  0.126940  ... -0.113671  0.182526  0.312205 -0.106975

    feat_27   feat_28   feat_29   feat_30   feat_31  PD_Label_Combined
0  0.111700 -0.204104  0.016686  0.161542  0.192166                  0
1  0.116208 -0.207540  0.045727  0.147894  0.184814                  0
2  0.152996 -0.208476  0.040235  0.149959  0.162922                  0
3  0.267845 -0.133356  0.253306  0.257301  0.222498                  1
4  0.292750 -0.141752  0.245937  0.238240  0.222659                  1

[5 rows x 33 columns]

In [9]:
# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [10]:
import pandas as pd

fused_df_named_int.to_csv('/content/drive//MyDrive/Modality-par-meg(go)_MIRA-Net_data.csv', index=False)

In [11]:
# ============================================================
# ###8)###
# ENSEMBLE CLASSIFICATION WITH STRATIFIED 10-FOLD CV
# ============================================================

# ------------------ Install Required Packages ------------------

!pip install xgboost lightgbm catboost scikit-learn statsmodels matplotlib seaborn --quiet


# ------------------ Imports ------------------

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.utils.class_weight import compute_class_weight

from sklearn.model_selection import (
    train_test_split,
    StratifiedKFold
)

from sklearn.preprocessing import StandardScaler

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    balanced_accuracy_score,
    matthews_corrcoef,
    confusion_matrix
)

from sklearn.ensemble import (
    VotingClassifier,
    StackingClassifier,
    RandomForestClassifier,
    HistGradientBoostingClassifier
)

from sklearn.linear_model import LogisticRegression

from xgboost import XGBClassifier

from statsmodels.stats.proportion import proportion_confint


# ============================================================
# STEP 1: PREPARE DATA
# ============================================================

X = fused_df_named_int[
    [f'feat_{i}' for i in range(32)]
].copy()

y = fused_df_named_int[
    "PD_Label_Combined"
].copy()


# ------------------ Convert X to numeric ------------------

X = X.apply(
    pd.to_numeric,
    errors='coerce'
)

X.fillna(
    0,
    inplace=True
)


# ============================================================
# STEP 2: CLASS WEIGHTS
# ============================================================

classes = np.unique(y)

class_weights = compute_class_weight(
    class_weight='balanced',
    classes=classes,
    y=y
)

class_weights_dict = {
    int(classes[0]): float(class_weights[0]),
    int(classes[1]): float(class_weights[1])
}

print("\nClass Weights:")
print(class_weights_dict)


# ============================================================
# STEP 3: TRAIN-TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=42
)


print("\nTrain Shape :", X_train.shape)
print("Test Shape  :", X_test.shape)

print("\nTraining Class Distribution:")
print(y_train.value_counts())

print("\nTesting Class Distribution:")
print(y_test.value_counts())


# ============================================================
# STEP 4: HANDLE CLASS IMBALANCE
# ============================================================

cw = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_train),
    y=y_train
)

cw_dict = dict(
    zip(
        np.unique(y_train),
        cw
    )
)

scale_pos_weight = (
    cw[1] / cw[0]
)

print("\nTraining Class Weights:")
print(cw_dict)

print(
    "\nXGBoost scale_pos_weight:",
    scale_pos_weight
)


# ============================================================
# STEP 5: BASE MODEL CREATION FUNCTION
# ============================================================

def create_models():

    # ---------------- XGBoost ----------------

    xgb = XGBClassifier(
        n_estimators=200,
        max_depth=4,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,

        scale_pos_weight=scale_pos_weight,

        eval_metric='logloss',

        random_state=42,
        n_jobs=-1
    )


    # ---------------- Random Forest ----------------

    rf = RandomForestClassifier(
        n_estimators=200,

        class_weight='balanced',

        random_state=42,
        n_jobs=-1
    )


    # ---------------- HistGradientBoosting ----------------

    hgb = HistGradientBoostingClassifier(
        max_iter=200,
        learning_rate=0.05,
        max_leaf_nodes=31,

        class_weight='balanced',

        random_state=42
    )


    return xgb, rf, hgb


# ============================================================
# STEP 6: STRATIFIED 10-FOLD CV
# ============================================================

skf = StratifiedKFold(
    n_splits=10,
    shuffle=True,
    random_state=42
)


# ============================================================
# STEP 7: EVALUATION FUNCTION
# ============================================================

def evaluate_model(model_name):

    # ========================================================
    # CV METRIC STORAGE
    # ========================================================

    cv_accuracy = []
    cv_precision = []
    cv_sensitivity = []
    cv_f1 = []
    cv_auc = []
    cv_balanced_accuracy = []


    # ========================================================
    # 10-FOLD STRATIFIED CROSS-VALIDATION
    # ========================================================

    for fold, (train_idx, val_idx) in enumerate(
        skf.split(X_train, y_train),
        start=1
    ):

        print(
            f"\n{model_name} | Fold {fold}/10"
        )


        # ----------------------------------------------------
        # Split fold
        # ----------------------------------------------------

        X_tr = X_train.iloc[
            train_idx
        ]

        X_val = X_train.iloc[
            val_idx
        ]

        y_tr = y_train.iloc[
            train_idx
        ]

        y_val = y_train.iloc[
            val_idx
        ]


        # ----------------------------------------------------
        # Scaling INSIDE EACH FOLD
        # ----------------------------------------------------

        scaler = StandardScaler()

        X_tr_scaled = scaler.fit_transform(
            X_tr
        )

        X_val_scaled = scaler.transform(
            X_val
        )


        # ----------------------------------------------------
        # Create FRESH models for every fold
        # ----------------------------------------------------

        xgb, rf, hgb = create_models()


        # ----------------------------------------------------
        # Select requested model
        # ----------------------------------------------------

        if model_name == "XGBoost":

            model = xgb


        elif model_name == "Random Forest":

            model = rf


        elif model_name == "HistGradientBoosting":

            model = hgb


        elif model_name == "Voting Fusion":

            model = VotingClassifier(
                estimators=[
                    ('xgb', xgb),
                    ('rf', rf),
                    ('hgb', hgb)
                ],
                voting='soft'
            )


        elif model_name == "Stacking Fusion":

            model = StackingClassifier(
                estimators=[
                    ('xgb', xgb),
                    ('rf', rf),
                    ('hgb', hgb)
                ],

                final_estimator=LogisticRegression(
                    max_iter=1000,
                    class_weight='balanced'
                ),

                passthrough=True,

                cv=5
            )


        else:

            raise ValueError(
                f"Unknown model: {model_name}"
            )


        # ----------------------------------------------------
        # Train fold
        # ----------------------------------------------------

        model.fit(
            X_tr_scaled,
            y_tr
        )


        # ----------------------------------------------------
        # Validation predictions
        # ----------------------------------------------------

        val_preds = model.predict(
            X_val_scaled
        )

        val_probs = model.predict_proba(
            X_val_scaled
        )[:, 1]


        # ----------------------------------------------------
        # Fold metrics
        # ----------------------------------------------------

        fold_accuracy = accuracy_score(
            y_val,
            val_preds
        )

        fold_precision = precision_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_sensitivity = recall_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_f1 = f1_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_auc = roc_auc_score(
            y_val,
            val_probs
        )

        fold_balanced_accuracy = balanced_accuracy_score(
            y_val,
            val_preds
        )


        # ----------------------------------------------------
        # Store fold metrics
        # ----------------------------------------------------

        cv_accuracy.append(
            fold_accuracy
        )

        cv_precision.append(
            fold_precision
        )

        cv_sensitivity.append(
            fold_sensitivity
        )

        cv_f1.append(
            fold_f1
        )

        cv_auc.append(
            fold_auc
        )

        cv_balanced_accuracy.append(
            fold_balanced_accuracy
        )


        # ----------------------------------------------------
        # Print fold result
        # ----------------------------------------------------

        print(
            f"Accuracy            : {fold_accuracy:.4f}"
        )

        print(
            f"Precision           : {fold_precision:.4f}"
        )

        print(
            f"Sensitivity         : {fold_sensitivity:.4f}"
        )

        print(
            f"F1 Score            : {fold_f1:.4f}"
        )

        print(
            f"ROC-AUC             : {fold_auc:.4f}"
        )

        print(
            f"Balanced Accuracy   : "
            f"{fold_balanced_accuracy:.4f}"
        )


    # ========================================================
    # CV MEAN RESULTS
    # ========================================================

    cv_accuracy_mean = np.mean(
        cv_accuracy
    )

    cv_precision_mean = np.mean(
        cv_precision
    )

    cv_sensitivity_mean = np.mean(
        cv_sensitivity
    )

    cv_f1_mean = np.mean(
        cv_f1
    )

    cv_auc_mean = np.mean(
        cv_auc
    )

    cv_balanced_accuracy_mean = np.mean(
        cv_balanced_accuracy
    )


    # ========================================================
    # CROSS-VALIDATION RESULTS
    # ========================================================

    print(
        "\n================================================"
    )

    print(
        f"{model_name} - Cross-Validation (10-fold)"
    )

    print(
        "================================================"
    )

    print(
        f"Accuracy            : "
        f"{cv_accuracy_mean:.4f}"
    )

    print(
        f"Precision           : "
        f"{cv_precision_mean:.4f}"
    )

    print(
        f"Recall/Sensitivity  : "
        f"{cv_sensitivity_mean:.4f}"
    )

    print(
        f"F1 Score            : "
        f"{cv_f1_mean:.4f}"
    )

    print(
        f"ROC-AUC             : "
        f"{cv_auc_mean:.4f}"
    )

    print(
        f"Balanced Accuracy   : "
        f"{cv_balanced_accuracy_mean:.4f}"
    )


    # ========================================================
    # TRAIN FINAL MODEL ON COMPLETE TRAINING SET
    # ========================================================

    final_scaler = StandardScaler()

    X_train_final_scaled = final_scaler.fit_transform(
        X_train
    )

    X_test_final_scaled = final_scaler.transform(
        X_test
    )


    # --------------------------------------------------------
    # Create fresh final models
    # --------------------------------------------------------

    xgb, rf, hgb = create_models()


    if model_name == "XGBoost":

        final_model = xgb


    elif model_name == "Random Forest":

        final_model = rf


    elif model_name == "HistGradientBoosting":

        final_model = hgb


    elif model_name == "Voting Fusion":

        final_model = VotingClassifier(
            estimators=[
                ('xgb', xgb),
                ('rf', rf),
                ('hgb', hgb)
            ],
            voting='soft'
        )


    elif model_name == "Stacking Fusion":

        final_model = StackingClassifier(
            estimators=[
                ('xgb', xgb),
                ('rf', rf),
                ('hgb', hgb)
            ],

            final_estimator=LogisticRegression(
                max_iter=1000,
                class_weight='balanced'
            ),

            passthrough=True,

            cv=5
        )


    # ========================================================
    # FINAL TRAINING
    # ========================================================

    final_model.fit(
        X_train_final_scaled,
        y_train
    )


    # ========================================================
    # TEST PREDICTIONS
    # ========================================================

    test_preds = final_model.predict(
        X_test_final_scaled
    )

    test_probs = final_model.predict_proba(
        X_test_final_scaled
    )[:, 1]


    # ========================================================
    # TEST METRICS
    # ========================================================

    accuracy = accuracy_score(
        y_test,
        test_preds
    )

    precision = precision_score(
        y_test,
        test_preds,
        zero_division=0
    )

    sensitivity = recall_score(
        y_test,
        test_preds,
        zero_division=0
    )

    f1 = f1_score(
        y_test,
        test_preds,
        zero_division=0
    )

    roc_auc = roc_auc_score(
        y_test,
        test_probs
    )

    balanced_accuracy = balanced_accuracy_score(
        y_test,
        test_preds
    )

    mcc = matthews_corrcoef(
        y_test,
        test_preds
    )


    # ========================================================
    # CONFUSION MATRIX
    # ========================================================

    cm = confusion_matrix(
        y_test,
        test_preds,
        labels=[0, 1]
    )

    tn, fp, fn, tp = cm.ravel()


    # ========================================================
    # SENSITIVITY / SPECIFICITY
    # ========================================================

    sensitivity = (
        tp / (tp + fn)
        if (tp + fn) > 0
        else 0
    )

    specificity = (
        tn / (tn + fp)
        if (tn + fp) > 0
        else 0
    )


    # ========================================================
    # 95% CONFIDENCE INTERVALS
    # ========================================================

    # ---------------- Accuracy CI ----------------

    acc_low, acc_high = proportion_confint(
        count=int(round(accuracy * len(y_test))),
        nobs=len(y_test),
        alpha=0.05,
        method='wilson'
    )


    # ---------------- Precision CI ----------------

    precision_low, precision_high = proportion_confint(
        count=tp,
        nobs=(tp + fp),
        alpha=0.05,
        method='wilson'
    ) if (tp + fp) > 0 else (0.0, 0.0)


    # ---------------- Sensitivity CI ----------------

    sensitivity_low, sensitivity_high = proportion_confint(
        count=tp,
        nobs=(tp + fn),
        alpha=0.05,
        method='wilson'
    ) if (tp + fn) > 0 else (0.0, 0.0)


    # ---------------- Specificity CI ----------------

    specificity_low, specificity_high = proportion_confint(
        count=tn,
        nobs=(tn + fp),
        alpha=0.05,
        method='wilson'
    ) if (tn + fp) > 0 else (0.0, 0.0)


    # ========================================================
    # TEST SET PERFORMANCE
    # ========================================================

    print(
        "\n================================================"
    )

    print(
        f"{model_name} - Test Set Performance"
    )

    print(
        "================================================"
    )

    print(
        f"Accuracy            : {accuracy:.4f} "
        f"(95% CI: "
        f"{acc_low:.4f}-{acc_high:.4f})"
    )

    print(
        f"Precision           : {precision:.4f} "
        f"(95% CI: "
        f"{precision_low:.4f}-{precision_high:.4f})"
    )

    print(
        f"Sensitivity         : {sensitivity:.4f} "
        f"(95% CI: "
        f"{sensitivity_low:.4f}-{sensitivity_high:.4f})"
    )

    print(
        f"Specificity         : {specificity:.4f} "
        f"(95% CI: "
        f"{specificity_low:.4f}-{specificity_high:.4f})"
    )

    print(
        f"F1 Score            : {f1:.4f}"
    )

    print(
        f"ROC-AUC             : {roc_auc:.4f}"
    )

    print(
        f"Balanced Accuracy   : "
        f"{balanced_accuracy:.4f}"
    )

    print(
        f"MCC                 : {mcc:.4f}"
    )


    # ========================================================
    # CONFUSION MATRIX
    # ========================================================

    print(
        "\nConfusion Matrix:"
    )

    print(cm)

    print(
        "\nTN :", tn
    )

    print(
        "FP :", fp
    )

    print(
        "FN :", fn
    )

    print(
        "TP :", tp
    )


    # ========================================================
    # STORE RESULTS
    # ========================================================

    result = {

        # ---------------- CV ----------------

        "CV Accuracy":
            cv_accuracy_mean,

        "CV Precision":
            cv_precision_mean,

        "CV Sensitivity":
            cv_sensitivity_mean,

        "CV F1":
            cv_f1_mean,

        "CV ROC-AUC":
            cv_auc_mean,

        "CV Balanced Accuracy":
            cv_balanced_accuracy_mean,


        # ---------------- Test ----------------

        "Accuracy":
            accuracy,

        "Accuracy CI Low":
            acc_low,

        "Accuracy CI High":
            acc_high,


        "Precision":
            precision,

        "Precision CI Low":
            precision_low,

        "Precision CI High":
            precision_high,


        "Sensitivity":
            sensitivity,

        "Sensitivity CI Low":
            sensitivity_low,

        "Sensitivity CI High":
            sensitivity_high,


        "Specificity":
            specificity,

        "Specificity CI Low":
            specificity_low,

        "Specificity CI High":
            specificity_high,


        "F1":
            f1,

        "ROC-AUC":
            roc_auc,

        "Balanced Accuracy":
            balanced_accuracy,

        "MCC":
            mcc,


        # ---------------- Confusion Matrix ----------------

        "TN":
            tn,

        "FP":
            fp,

        "FN":
            fn,

        "TP":
            tp
    }


    return result


# ============================================================
# STEP 8: EVALUATE ALL MODELS
# ============================================================

model_names = [
    "XGBoost",
    "Random Forest",
    "HistGradientBoosting",
    "Voting Fusion",
    "Stacking Fusion"
]


results = {}

for name in model_names:

    print(
        "\n\n################################################"
    )

    print(
        f"Evaluating: {name}"
    )

    print(
        "################################################"
    )

    results[name] = evaluate_model(
        name
    )


# ============================================================
# STEP 9: FINAL RESULTS DATAFRAME
# ============================================================

results_df = pd.DataFrame(
    results
).T


# ============================================================
# STEP 10: ORDER RESULTS
# ============================================================

results_df = results_df[
    [

        # ---------------- CV ----------------

        "CV Accuracy",
        "CV Precision",
        "CV Sensitivity",
        "CV F1",
        "CV ROC-AUC",
        "CV Balanced Accuracy",


        # ---------------- Test ----------------

        "Accuracy",
        "Accuracy CI Low",
        "Accuracy CI High",

        "Precision",
        "Precision CI Low",
        "Precision CI High",

        "Sensitivity",
        "Sensitivity CI Low",
        "Sensitivity CI High",

        "Specificity",
        "Specificity CI Low",
        "Specificity CI High",

        "F1",
        "ROC-AUC",
        "Balanced Accuracy",
        "MCC",

        # ---------------- Confusion Matrix ----------------

        "TN",
        "FP",
        "FN",
        "TP"
    ]
]


# ============================================================
# STEP 11: DISPLAY FINAL RESULTS
# ============================================================

print(
    "\n================================================"
)

print(
    "FINAL MODEL COMPARISON"
)

print(
    "================================================\n"
)


display(
    results_df.sort_values(
        by="F1",
        ascending=False
    )
)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 7.3 MB/s eta 0:00:00

Class Weights:
{0: 0.9769230769230769, 1: 1.0241935483870968}

Train Shape : (101, 32)
Test Shape  : (26, 32)

Training Class Distribution:
PD_Label_Combined
0    52
1    49
Name: count, dtype: int64

Testing Class Distribution:
PD_Label_Combined
1    13
0    13
Name: count, dtype: int64

Training Class Weights:
{np.int64(0): np.float64(0.9711538461538461), np.int64(1): np.float64(1.030612244897959)}

XGBoost scale_pos_weight: 1.0612244897959182


################################################
Evaluating: XGBoost
################################################

XGBoost | Fold 1/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

XGBoost | Fold 2/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

XGBoost | Fold 3/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

XGBoost | Fold 4/10
Accuracy            : 0.9000
Precision           : 1.0000
Sensitivity         : 0.8000
F1 Score            : 0.8889
ROC-AUC             : 1.0000
Balanced Accuracy   : 0.9000

XGBoost | Fold 5/10
Accuracy            : 0.9000
Precision           : 1.0000
Sensitivity         : 0.8000
F1 Score            : 0.8889
ROC-AUC             : 0.9800
Balanced Accuracy   : 0.9000

XGBoost | Fold 6/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

XGBoost | Fold 7/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

XGBoost | Fold 8/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

XGBoost | Fold 9/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

XGBoost | Fold 10/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

================================================
XGBoost - Cross-Validation (10-fold)
================================================
Accuracy            : 0.9800
Precision           : 1.0000
Recall/Sensitivity  : 0.9600
F1 Score            : 0.9778
ROC-AUC             : 0.9980
Balanced Accuracy   : 0.9800

================================================
XGBoost - Test Set Performance
================================================
Accuracy            : 1.0000 (95% CI: 0.8713-1.0000)
Precision           : 1.0000 (95% CI: 0.7719-1.0000)
Sensitivity         : 1.0000 (95% CI: 0.7719-1.0000)
Specificity         : 1.0000 (95% CI: 0.7719-1.0000)
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000
MCC                 : 1.0000

Confusion Matrix:
[[13  0]
 [ 0 13]]

TN : 13
FP : 0
FN : 0
TP : 13


################################################
Evaluating: Random Forest
################################################

Random Forest | Fold 1/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Random Forest | Fold 2/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Random Forest | Fold 3/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Random Forest | Fold 4/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Random Forest | Fold 5/10
Accuracy            : 0.9000
Precision           : 1.0000
Sensitivity         : 0.8000
F1 Score            : 0.8889
ROC-AUC             : 0.9800
Balanced Accuracy   : 0.9000

Random Forest | Fold 6/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Random Forest | Fold 7/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Random Forest | Fold 8/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Random Forest | Fold 9/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Random Forest | Fold 10/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

================================================
Random Forest - Cross-Validation (10-fold)
================================================
Accuracy            : 0.9900
Precision           : 1.0000
Recall/Sensitivity  : 0.9800
F1 Score            : 0.9889
ROC-AUC             : 0.9980
Balanced Accuracy   : 0.9900

================================================
Random Forest - Test Set Performance
================================================
Accuracy            : 1.0000 (95% CI: 0.8713-1.0000)
Precision           : 1.0000 (95% CI: 0.7719-1.0000)
Sensitivity         : 1.0000 (95% CI: 0.7719-1.0000)
Specificity         : 1.0000 (95% CI: 0.7719-1.0000)
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000
MCC                 : 1.0000

Confusion Matrix:
[[13  0]
 [ 0 13]]

TN : 13
FP : 0
FN : 0
TP : 13


################################################
Evaluating: HistGradientBoosting
################################################

HistGradientBoosting | Fold 1/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

HistGradientBoosting | Fold 2/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

HistGradientBoosting | Fold 3/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

HistGradientBoosting | Fold 4/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

HistGradientBoosting | Fold 5/10
Accuracy            : 0.9000
Precision           : 1.0000
Sensitivity         : 0.8000
F1 Score            : 0.8889
ROC-AUC             : 0.9000
Balanced Accuracy   : 0.9000

HistGradientBoosting | Fold 6/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

HistGradientBoosting | Fold 7/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

HistGradientBoosting | Fold 8/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

HistGradientBoosting | Fold 9/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

HistGradientBoosting | Fold 10/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

================================================
HistGradientBoosting - Cross-Validation (10-fold)
================================================
Accuracy            : 0.9900
Precision           : 1.0000
Recall/Sensitivity  : 0.9800
F1 Score            : 0.9889
ROC-AUC             : 0.9900
Balanced Accuracy   : 0.9900

================================================
HistGradientBoosting - Test Set Performance
================================================
Accuracy            : 1.0000 (95% CI: 0.8713-1.0000)
Precision           : 1.0000 (95% CI: 0.7719-1.0000)
Sensitivity         : 1.0000 (95% CI: 0.7719-1.0000)
Specificity         : 1.0000 (95% CI: 0.7719-1.0000)
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000
MCC                 : 1.0000

Confusion Matrix:
[[13  0]
 [ 0 13]]

TN : 13
FP : 0
FN : 0
TP : 13


################################################
Evaluating: Voting Fusion
################################################

Voting Fusion | Fold 1/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Voting Fusion | Fold 2/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Voting Fusion | Fold 3/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Voting Fusion | Fold 4/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Voting Fusion | Fold 5/10
Accuracy            : 0.9000
Precision           : 1.0000
Sensitivity         : 0.8000
F1 Score            : 0.8889
ROC-AUC             : 0.9800
Balanced Accuracy   : 0.9000

Voting Fusion | Fold 6/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Voting Fusion | Fold 7/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Voting Fusion | Fold 8/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Voting Fusion | Fold 9/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Voting Fusion | Fold 10/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

================================================
Voting Fusion - Cross-Validation (10-fold)
================================================
Accuracy            : 0.9900
Precision           : 1.0000
Recall/Sensitivity  : 0.9800
F1 Score            : 0.9889
ROC-AUC             : 0.9980
Balanced Accuracy   : 0.9900

================================================
Voting Fusion - Test Set Performance
================================================
Accuracy            : 1.0000 (95% CI: 0.8713-1.0000)
Precision           : 1.0000 (95% CI: 0.7719-1.0000)
Sensitivity         : 1.0000 (95% CI: 0.7719-1.0000)
Specificity         : 1.0000 (95% CI: 0.7719-1.0000)
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000
MCC                 : 1.0000

Confusion Matrix:
[[13  0]
 [ 0 13]]

TN : 13
FP : 0
FN : 0
TP : 13


################################################
Evaluating: Stacking Fusion
################################################

Stacking Fusion | Fold 1/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Stacking Fusion | Fold 2/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Stacking Fusion | Fold 3/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Stacking Fusion | Fold 4/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Stacking Fusion | Fold 5/10
Accuracy            : 0.9000
Precision           : 1.0000
Sensitivity         : 0.8000
F1 Score            : 0.8889
ROC-AUC             : 0.9800
Balanced Accuracy   : 0.9000

Stacking Fusion | Fold 6/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Stacking Fusion | Fold 7/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Stacking Fusion | Fold 8/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Stacking Fusion | Fold 9/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Stacking Fusion | Fold 10/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

================================================
Stacking Fusion - Cross-Validation (10-fold)
================================================
Accuracy            : 0.9900
Precision           : 1.0000
Recall/Sensitivity  : 0.9800
F1 Score            : 0.9889
ROC-AUC             : 0.9980
Balanced Accuracy   : 0.9900

================================================
Stacking Fusion - Test Set Performance
================================================
Accuracy            : 1.0000 (95% CI: 0.8713-1.0000)
Precision           : 1.0000 (95% CI: 0.7719-1.0000)
Sensitivity         : 1.0000 (95% CI: 0.7719-1.0000)
Specificity         : 1.0000 (95% CI: 0.7719-1.0000)
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000
MCC                 : 1.0000

Confusion Matrix:
[[13  0]
 [ 0 13]]

TN : 13
FP : 0
FN : 0
TP : 13

================================================
FINAL MODEL COMPARISON
================================================

,CV Accuracy,CV Precision,CV Sensitivity,CV F1,CV ROC-AUC,CV Balanced Accuracy,Accuracy,Accuracy CI Low,Accuracy CI High,Precision,...,Specificity CI Low,Specificity CI High,F1,ROC-AUC,Balanced Accuracy,MCC,TN,FP,FN,TP
XGBoost,0.98,1.0,0.96,0.977778,0.998,0.98,1.0,0.871271,1.0,1.0,...,0.771905,1.0,1.0,1.0,1.0,1.0,13.0,0.0,0.0,13.0
Random Forest,0.99,1.0,0.98,0.988889,0.998,0.99,1.0,0.871271,1.0,1.0,...,0.771905,1.0,1.0,1.0,1.0,1.0,13.0,0.0,0.0,13.0
HistGradientBoosting,0.99,1.0,0.98,0.988889,0.990,0.99,1.0,0.871271,1.0,1.0,...,0.771905,1.0,1.0,1.0,1.0,1.0,13.0,0.0,0.0,13.0
Voting Fusion,0.99,1.0,0.98,0.988889,0.998,0.99,1.0,0.871271,1.0,1.0,...,0.771905,1.0,1.0,1.0,1.0,1.0,13.0,0.0,0.0,13.0
Stacking Fusion,0.99,1.0,0.98,0.988889,0.998,0.99,1.0,0.871271,1.0,1.0,...,0.771905,1.0,1.0,1.0,1.0,1.0,13.0,0.0,0.0,13.0

Without MIRA-Net

In [1]:
# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

final_meg_df = pd.read_csv('/content/drive/MyDrive/final_meg_go_21_par-lev_final.csv')

print("Loaded data shape:", final_meg_df.shape)
print(final_meg_df.head())

Loaded data shape: (127, 106)
   burst_rate_L_mean  burst_rate_L_std  burst_rate_R_mean  burst_rate_R_std  \
0           4.407992          0.146692           4.465646          0.117633
1           3.793146          0.367291           3.882352          0.410346
2           4.517238          0.166177           4.604832          0.117440
3           4.096736          0.237234           4.162662          0.205532
4           5.911883          7.663211           4.961802          6.536711

   burst_rate_asym  mean_burst_duration_L_mean  mean_burst_duration_L_std  \
0        -0.006497                    0.056773                   0.001915
1        -0.011622                    0.066523                   0.006423
2        -0.009602                    0.055419                   0.002108
3        -0.007982                    0.061230                   0.003630
4         0.087374                    0.004383                   0.001650

   mean_burst_duration_R_mean  mean_burst_duration_R_std  \
0                    0.056017                   0.001495
1                    0.065139                   0.007151
2                    0.054324                   0.001410
3                    0.060201                   0.002986
4                    0.004410                   0.001619

   mean_burst_duration_asym  ...  spectral_flatness_L_std  \
0                  0.006700  ...                 0.054968
1                  0.010517  ...                 0.042931
2                  0.009974  ...                 0.021047
3                  0.008477  ...                 0.060342
4                 -0.003085  ...                 0.003310

   spectral_flatness_R_mean  spectral_flatness_R_std  spectral_flatness_asym  \
0                  0.948269                 0.039871               -0.007503
1                  0.931122                 0.042574               -0.003631
2                  0.972496                 0.017510               -0.000729
3                  0.862457                 0.051705               -0.004438
4                  0.935127                 0.007780               -0.000536

   spectral_slope_L_mean  spectral_slope_L_std  spectral_slope_R_mean  \
0          -2.705737e-13          3.891970e-13          -1.298295e-13
1          -4.771582e-13          5.571425e-13          -4.549048e-13
2          -9.685957e-14          1.288054e-13          -8.093741e-14
3          -7.628670e-13          9.692914e-13          -4.191067e-13
4          -1.331795e+00          5.033830e-01          -1.325357e+00

   spectral_slope_R_std  spectral_slope_asym  Pd_indicator_meg
0          1.789942e-13            -0.000014                 0
1          5.509281e-13            -0.000002                 0
2          9.458701e-14            -0.000002                 0
3          4.995036e-13            -0.000034                 1
4          5.015086e-01             0.002423                 1

[5 rows x 106 columns]

In [3]:
fused_df_named_int = final_meg_df.rename(columns={"Pd_indicator_meg": "PD_Label_Combined"})
fused_df_named_int.head()
fused_df_named_int.shape

(127, 106)

In [4]:
fused_df_named_int.head()

,burst_rate_L_mean,burst_rate_L_std,burst_rate_R_mean,burst_rate_R_std,burst_rate_asym,mean_burst_duration_L_mean,mean_burst_duration_L_std,mean_burst_duration_R_mean,mean_burst_duration_R_std,mean_burst_duration_asym,...,spectral_flatness_L_std,spectral_flatness_R_mean,spectral_flatness_R_std,spectral_flatness_asym,spectral_slope_L_mean,spectral_slope_L_std,spectral_slope_R_mean,spectral_slope_R_std,spectral_slope_asym,PD_Label_Combined
0,4.407992,0.146692,4.465646,0.117633,-0.006497,0.056773,0.001915,0.056017,0.001495,0.006700,...,0.054968,0.948269,0.039871,-0.007503,-2.705737e-13,3.891970e-13,-1.298295e-13,1.789942e-13,-0.000014,0
1,3.793146,0.367291,3.882352,0.410346,-0.011622,0.066523,0.006423,0.065139,0.007151,0.010517,...,0.042931,0.931122,0.042574,-0.003631,-4.771582e-13,5.571425e-13,-4.549048e-13,5.509281e-13,-0.000002,0
2,4.517238,0.166177,4.604832,0.117440,-0.009602,0.055419,0.002108,0.054324,0.001410,0.009974,...,0.021047,0.972496,0.017510,-0.000729,-9.685957e-14,1.288054e-13,-8.093741e-14,9.458701e-14,-0.000002,0
3,4.096736,0.237234,4.162662,0.205532,-0.007982,0.061230,0.003630,0.060201,0.002986,0.008477,...,0.060342,0.862457,0.051705,-0.004438,-7.628670e-13,9.692914e-13,-4.191067e-13,4.995036e-13,-0.000034,1
4,5.911883,7.663211,4.961802,6.536711,0.087374,0.004383,0.001650,0.004410,0.001619,-0.003085,...,0.003310,0.935127,0.007780,-0.000536,-1.331795e+00,5.033830e-01,-1.325357e+00,5.015086e-01,0.002423,1

In [10]:
# ============================================================
# ###8)###
#
# ENSEMBLE CLASSIFICATION WITH STRATIFIED 10-FOLD CV
# ============================================================

# ------------------ Install Required Packages ------------------

!pip install xgboost lightgbm catboost scikit-learn statsmodels matplotlib seaborn --quiet


# ------------------ Imports ------------------

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.utils.class_weight import compute_class_weight

from sklearn.model_selection import (
    train_test_split,
    StratifiedKFold
)

from sklearn.preprocessing import StandardScaler

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    balanced_accuracy_score,
    matthews_corrcoef,
    confusion_matrix
)

from sklearn.ensemble import (
    VotingClassifier,
    StackingClassifier,
    RandomForestClassifier,
    HistGradientBoostingClassifier
)

from sklearn.linear_model import LogisticRegression

from xgboost import XGBClassifier

from statsmodels.stats.proportion import proportion_confint


# ============================================================
# STEP 1: PREPARE DATA
# ============================================================

# All feature columns except the final label column
X = fused_df_named_int.iloc[:, :-1].copy()

# Target
y = fused_df_named_int["PD_Label_Combined"].copy()


# ============================================================
# CONVERT FEATURES TO NUMERIC
# ============================================================

X = X.apply(
    pd.to_numeric,
    errors="coerce"
)


# ============================================================
# CHECK RAW VALUES
# ============================================================

print("\nRaw feature statistics:")
print("Shape :", X.shape)

print(
    "NaN values before cleaning :",
    X.isna().sum().sum()
)

print(
    "Inf values before cleaning :",
    np.isinf(
        X.to_numpy(dtype=np.float64)
    ).sum()
)


# ============================================================
# HANDLE +INF / -INF
# ============================================================

X = X.replace(
    [np.inf, -np.inf],
    np.nan
)


# ============================================================
# COLUMN-WISE MEDIAN IMPUTATION
# ============================================================

col_medians = X.median(
    axis=0,
    skipna=True
)

# If an entire column is NaN,
# replace its median with 0
col_medians = col_medians.fillna(0)

X = X.fillna(
    col_medians
)


# ============================================================
# CLIP EXTREMELY LARGE VALUES
# ============================================================

# Prevent overflow when converting to float32.
#
# Values larger than this are clipped rather than allowed
# to produce inf during float32 conversion.

CLIP_VALUE = 1e10

X = X.clip(
    lower=-CLIP_VALUE,
    upper=CLIP_VALUE
)


# ============================================================
# CONVERT TO FLOAT32 AFTER CLEANING
# ============================================================

X = X.astype(
    np.float32
)


# ============================================================
# FINAL FINITE-VALUE CHECK
# ============================================================

X_array = X.to_numpy()

print("\nAfter cleaning:")

print(
    "NaN values :",
    np.isnan(X_array).sum()
)

print(
    "Inf values :",
    np.isinf(X_array).sum()
)

print(
    "Finite     :",
    np.isfinite(X_array).all()
)

print(
    "Maximum    :",
    np.max(X_array)
)

print(
    "Minimum    :",
    np.min(X_array)
)


# ============================================================
# TARGET CLEANING
# ============================================================

y = pd.to_numeric(
    y,
    errors="coerce"
)

# Make sure target contains no missing values
valid_idx = y.notna()

X = X.loc[valid_idx].reset_index(drop=True)

y = y.loc[valid_idx].astype(
    np.int64
).reset_index(drop=True)


print("\nFinal data:")
print("X shape :", X.shape)
print("y shape :", y.shape)

print("\nClass distribution:")
print(y.value_counts())


# ============================================================
# STEP 2: CLASS WEIGHTS
# ============================================================

classes = np.unique(y)

class_weights = compute_class_weight(
    class_weight="balanced",
    classes=classes,
    y=y
)

class_weights_dict = {
    int(classes[0]): float(class_weights[0]),
    int(classes[1]): float(class_weights[1])
}

print("\nClass Weights:")
print(class_weights_dict)


# ============================================================
# STEP 3: TRAIN-TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    stratify=y,
    random_state=42
)


print("\nTrain Shape :", X_train.shape)
print("Test Shape  :", X_test.shape)


print("\nTraining Class Distribution:")
print(
    y_train.value_counts()
)


print("\nTesting Class Distribution:")
print(
    y_test.value_counts()
)


# ============================================================
# STEP 4: HANDLE CLASS IMBALANCE
# ============================================================

cw = compute_class_weight(
    class_weight="balanced",
    classes=np.unique(y_train),
    y=y_train
)

cw_dict = dict(
    zip(
        np.unique(y_train),
        cw
    )
)

scale_pos_weight = (
    cw_dict[1] / cw_dict[0]
)


print("\nTraining Class Weights:")
print(cw_dict)

print(
    "\nXGBoost scale_pos_weight:",
    scale_pos_weight
)




# ============================================================
# STEP 5: BASE MODEL CREATION FUNCTION
# ============================================================

def create_models():

    # ---------------- XGBoost ----------------

    xgb = XGBClassifier(
        n_estimators=200,
        max_depth=4,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,

        scale_pos_weight=scale_pos_weight,

        eval_metric='logloss',

        random_state=42,
        n_jobs=-1
    )


    # ---------------- Random Forest ----------------

    rf = RandomForestClassifier(
        n_estimators=200,

        class_weight='balanced',

        random_state=42,
        n_jobs=-1
    )


    # ---------------- HistGradientBoosting ----------------

    hgb = HistGradientBoostingClassifier(
        max_iter=200,
        learning_rate=0.05,
        max_leaf_nodes=31,

        class_weight='balanced',

        random_state=42
    )


    return xgb, rf, hgb


# ============================================================
# STEP 6: STRATIFIED 10-FOLD CV
# ============================================================

skf = StratifiedKFold(
    n_splits=10,
    shuffle=True,
    random_state=42
)


# ============================================================
# STEP 7: EVALUATION FUNCTION
# ============================================================

def evaluate_model(model_name):

    # ========================================================
    # CV METRIC STORAGE
    # ========================================================

    cv_accuracy = []
    cv_precision = []
    cv_sensitivity = []
    cv_f1 = []
    cv_auc = []
    cv_balanced_accuracy = []


    # ========================================================
    # 10-FOLD STRATIFIED CROSS-VALIDATION
    # ========================================================

    for fold, (train_idx, val_idx) in enumerate(
        skf.split(X_train, y_train),
        start=1
    ):

        print(
            f"\n{model_name} | Fold {fold}/10"
        )


        # ----------------------------------------------------
        # Split fold
        # ----------------------------------------------------

        X_tr = X_train.iloc[
            train_idx
        ]

        X_val = X_train.iloc[
            val_idx
        ]

        y_tr = y_train.iloc[
            train_idx
        ]

        y_val = y_train.iloc[
            val_idx
        ]


        # ----------------------------------------------------
        # Scaling INSIDE EACH FOLD
        # ----------------------------------------------------

        scaler = StandardScaler()

        X_tr_scaled = scaler.fit_transform(
            X_tr
        )

        X_val_scaled = scaler.transform(
            X_val
        )


        # ----------------------------------------------------
        # Create FRESH models for every fold
        # ----------------------------------------------------

        xgb, rf, hgb = create_models()


        # ----------------------------------------------------
        # Select requested model
        # ----------------------------------------------------

        if model_name == "XGBoost":

            model = xgb


        elif model_name == "Random Forest":

            model = rf


        elif model_name == "HistGradientBoosting":

            model = hgb


        elif model_name == "Voting Fusion":

            model = VotingClassifier(
                estimators=[
                    ('xgb', xgb),
                    ('rf', rf),
                    ('hgb', hgb)
                ],
                voting='soft'
            )


        elif model_name == "Stacking Fusion":

            model = StackingClassifier(
                estimators=[
                    ('xgb', xgb),
                    ('rf', rf),
                    ('hgb', hgb)
                ],

                final_estimator=LogisticRegression(
                    max_iter=1000,
                    class_weight='balanced'
                ),

                passthrough=True,

                cv=5
            )


        else:

            raise ValueError(
                f"Unknown model: {model_name}"
            )


        # ----------------------------------------------------
        # Train fold
        # ----------------------------------------------------

        model.fit(
            X_tr_scaled,
            y_tr
        )


        # ----------------------------------------------------
        # Validation predictions
        # ----------------------------------------------------

        scaler = StandardScaler()
        X_tr = X_tr.astype(np.float64)
        X_val = X_val.astype(np.float64)
        X_tr = np.nan_to_num(
            X_tr,
            nan=0.0,
            posinf=0.0,
            neginf=0.0
        )
        X_val = np.nan_to_num(
            X_val,
            nan=0.0,
            posinf=0.0,
            neginf=0.0
        )
        X_tr_scaled = scaler.fit_transform(X_tr)
        X_val_scaled = scaler.transform(X_val)
        # ----------------------------------------------------
        # Safety check after scaling
        # ----------------------------------------------------
        X_tr_scaled = np.nan_to_num(
            X_tr,
            nan=0.0,
            posinf=0.0,
            neginf=0.0
        )
        X_val = np.nan_to_num(
            X_val,
            nan=0.0,
            posinf=0.0,
            neginf=0.0
        )
        print(
            f"Fold {fold}: "
            f"max|X_val|={np.max(np.abs(X_val_scaled)):.4f}"
        )

        val_preds = model.predict(
             X_val_scaled
        )
        val_probs = model.predict_proba(
            X_val_scaled
        )[:, 1]

        # ----------------------------------------------------
        # Fold metrics
        # ----------------------------------------------------

        fold_accuracy = accuracy_score(
            y_val,
            val_preds
        )

        fold_precision = precision_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_sensitivity = recall_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_f1 = f1_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_auc = roc_auc_score(
            y_val,
            val_probs
        )

        fold_balanced_accuracy = balanced_accuracy_score(
            y_val,
            val_preds
        )


        # ----------------------------------------------------
        # Store fold metrics
        # ----------------------------------------------------

        cv_accuracy.append(
            fold_accuracy
        )

        cv_precision.append(
            fold_precision
        )

        cv_sensitivity.append(
            fold_sensitivity
        )

        cv_f1.append(
            fold_f1
        )

        cv_auc.append(
            fold_auc
        )

        cv_balanced_accuracy.append(
            fold_balanced_accuracy
        )


        # ----------------------------------------------------
        # Print fold result
        # ----------------------------------------------------

        print(
            f"Accuracy            : {fold_accuracy:.4f}"
        )

        print(
            f"Precision           : {fold_precision:.4f}"
        )

        print(
            f"Sensitivity         : {fold_sensitivity:.4f}"
        )

        print(
            f"F1 Score            : {fold_f1:.4f}"
        )

        print(
            f"ROC-AUC             : {fold_auc:.4f}"
        )

        print(
            f"Balanced Accuracy   : "
            f"{fold_balanced_accuracy:.4f}"
        )


    # ========================================================
    # CV MEAN RESULTS
    # ========================================================

    cv_accuracy_mean = np.mean(
        cv_accuracy
    )

    cv_precision_mean = np.mean(
        cv_precision
    )

    cv_sensitivity_mean = np.mean(
        cv_sensitivity
    )

    cv_f1_mean = np.mean(
        cv_f1
    )

    cv_auc_mean = np.mean(
        cv_auc
    )

    cv_balanced_accuracy_mean = np.mean(
        cv_balanced_accuracy
    )


    # ========================================================
    # CROSS-VALIDATION RESULTS
    # ========================================================

    print(
        "\n================================================"
    )

    print(
        f"{model_name} - Cross-Validation (10-fold)"
    )

    print(
        "================================================"
    )

    print(
        f"Accuracy            : "
        f"{cv_accuracy_mean:.4f}"
    )

    print(
        f"Precision           : "
        f"{cv_precision_mean:.4f}"
    )

    print(
        f"Recall/Sensitivity  : "
        f"{cv_sensitivity_mean:.4f}"
    )

    print(
        f"F1 Score            : "
        f"{cv_f1_mean:.4f}"
    )

    print(
        f"ROC-AUC             : "
        f"{cv_auc_mean:.4f}"
    )

    print(
        f"Balanced Accuracy   : "
        f"{cv_balanced_accuracy_mean:.4f}"
    )


    # ========================================================
    # TRAIN FINAL MODEL ON COMPLETE TRAINING SET
    # ========================================================

    final_scaler = StandardScaler()

    X_train_final_scaled = final_scaler.fit_transform(
        X_train
    )

    X_test_final_scaled = final_scaler.transform(
        X_test
    )


    # --------------------------------------------------------
    # Create fresh final models
    # --------------------------------------------------------

    xgb, rf, hgb = create_models()


    if model_name == "XGBoost":

        final_model = xgb


    elif model_name == "Random Forest":

        final_model = rf


    elif model_name == "HistGradientBoosting":

        final_model = hgb


    elif model_name == "Voting Fusion":

        final_model = VotingClassifier(
            estimators=[
                ('xgb', xgb),
                ('rf', rf),
                ('hgb', hgb)
            ],
            voting='soft'
        )


    elif model_name == "Stacking Fusion":

        final_model = StackingClassifier(
            estimators=[
                ('xgb', xgb),
                ('rf', rf),
                ('hgb', hgb)
            ],

            final_estimator=LogisticRegression(
                max_iter=1000,
                class_weight='balanced'
            ),

            passthrough=True,

            cv=5
        )


    # ========================================================
    # FINAL TRAINING
    # ========================================================

    final_model.fit(
        X_train_final_scaled,
        y_train
    )


    # ========================================================
    # TEST PREDICTIONS
    # ========================================================

    test_preds = final_model.predict(
        X_test_final_scaled
    )

    test_probs = final_model.predict_proba(
        X_test_final_scaled
    )[:, 1]


    # ========================================================
    # TEST METRICS
    # ========================================================

    accuracy = accuracy_score(
        y_test,
        test_preds
    )

    precision = precision_score(
        y_test,
        test_preds,
        zero_division=0
    )

    sensitivity = recall_score(
        y_test,
        test_preds,
        zero_division=0
    )

    f1 = f1_score(
        y_test,
        test_preds,
        zero_division=0
    )

    roc_auc = roc_auc_score(
        y_test,
        test_probs
    )

    balanced_accuracy = balanced_accuracy_score(
        y_test,
        test_preds
    )

    mcc = matthews_corrcoef(
        y_test,
        test_preds
    )


    # ========================================================
    # CONFUSION MATRIX
    # ========================================================

    cm = confusion_matrix(
        y_test,
        test_preds,
        labels=[0, 1]
    )

    tn, fp, fn, tp = cm.ravel()


    # ========================================================
    # SENSITIVITY / SPECIFICITY
    # ========================================================

    sensitivity = (
        tp / (tp + fn)
        if (tp + fn) > 0
        else 0
    )

    specificity = (
        tn / (tn + fp)
        if (tn + fp) > 0
        else 0
    )


    # ========================================================
    # 95% CONFIDENCE INTERVALS
    # ========================================================

    # ---------------- Accuracy CI ----------------

    acc_low, acc_high = proportion_confint(
        count=int(round(accuracy * len(y_test))),
        nobs=len(y_test),
        alpha=0.05,
        method='wilson'
    )


    # ---------------- Precision CI ----------------

    precision_low, precision_high = proportion_confint(
        count=tp,
        nobs=(tp + fp),
        alpha=0.05,
        method='wilson'
    ) if (tp + fp) > 0 else (0.0, 0.0)


    # ---------------- Sensitivity CI ----------------

    sensitivity_low, sensitivity_high = proportion_confint(
        count=tp,
        nobs=(tp + fn),
        alpha=0.05,
        method='wilson'
    ) if (tp + fn) > 0 else (0.0, 0.0)


    # ---------------- Specificity CI ----------------

    specificity_low, specificity_high = proportion_confint(
        count=tn,
        nobs=(tn + fp),
        alpha=0.05,
        method='wilson'
    ) if (tn + fp) > 0 else (0.0, 0.0)


    # ========================================================
    # TEST SET PERFORMANCE
    # ========================================================

    print(
        "\n================================================"
    )

    print(
        f"{model_name} - Test Set Performance"
    )

    print(
        "================================================"
    )

    print(
        f"Accuracy            : {accuracy:.4f} "
        f"(95% CI: "
        f"{acc_low:.4f}-{acc_high:.4f})"
    )

    print(
        f"Precision           : {precision:.4f} "
        f"(95% CI: "
        f"{precision_low:.4f}-{precision_high:.4f})"
    )

    print(
        f"Sensitivity         : {sensitivity:.4f} "
        f"(95% CI: "
        f"{sensitivity_low:.4f}-{sensitivity_high:.4f})"
    )

    print(
        f"Specificity         : {specificity:.4f} "
        f"(95% CI: "
        f"{specificity_low:.4f}-{specificity_high:.4f})"
    )

    print(
        f"F1 Score            : {f1:.4f}"
    )

    print(
        f"ROC-AUC             : {roc_auc:.4f}"
    )

    print(
        f"Balanced Accuracy   : "
        f"{balanced_accuracy:.4f}"
    )

    print(
        f"MCC                 : {mcc:.4f}"
    )


    # ========================================================
    # CONFUSION MATRIX
    # ========================================================

    print(
        "\nConfusion Matrix:"
    )

    print(cm)

    print(
        "\nTN :", tn
    )

    print(
        "FP :", fp
    )

    print(
        "FN :", fn
    )

    print(
        "TP :", tp
    )


    # ========================================================
    # STORE RESULTS
    # ========================================================

    result = {

        # ---------------- CV ----------------

        "CV Accuracy":
            cv_accuracy_mean,

        "CV Precision":
            cv_precision_mean,

        "CV Sensitivity":
            cv_sensitivity_mean,

        "CV F1":
            cv_f1_mean,

        "CV ROC-AUC":
            cv_auc_mean,

        "CV Balanced Accuracy":
            cv_balanced_accuracy_mean,


        # ---------------- Test ----------------

        "Accuracy":
            accuracy,

        "Accuracy CI Low":
            acc_low,

        "Accuracy CI High":
            acc_high,


        "Precision":
            precision,

        "Precision CI Low":
            precision_low,

        "Precision CI High":
            precision_high,


        "Sensitivity":
            sensitivity,

        "Sensitivity CI Low":
            sensitivity_low,

        "Sensitivity CI High":
            sensitivity_high,


        "Specificity":
            specificity,

        "Specificity CI Low":
            specificity_low,

        "Specificity CI High":
            specificity_high,


        "F1":
            f1,

        "ROC-AUC":
            roc_auc,

        "Balanced Accuracy":
            balanced_accuracy,

        "MCC":
            mcc,


        # ---------------- Confusion Matrix ----------------

        "TN":
            tn,

        "FP":
            fp,

        "FN":
            fn,

        "TP":
            tp
    }


    return result


# ============================================================
# STEP 8: EVALUATE ALL MODELS
# ============================================================

model_names = [
    "XGBoost",
    "Random Forest",
    "HistGradientBoosting",
    "Voting Fusion",
    "Stacking Fusion"
]


results = {}

for name in model_names:

    print(
        "\n\n################################################"
    )

    print(
        f"Evaluating: {name}"
    )

    print(
        "################################################"
    )

    results[name] = evaluate_model(
        name
    )


# ============================================================
# STEP 9: FINAL RESULTS DATAFRAME
# ============================================================

results_df = pd.DataFrame(
    results
).T


# ============================================================
# STEP 10: ORDER RESULTS
# ============================================================

results_df = results_df[
    [

        # ---------------- CV ----------------

        "CV Accuracy",
        "CV Precision",
        "CV Sensitivity",
        "CV F1",
        "CV ROC-AUC",
        "CV Balanced Accuracy",


        # ---------------- Test ----------------

        "Accuracy",
        "Accuracy CI Low",
        "Accuracy CI High",

        "Precision",
        "Precision CI Low",
        "Precision CI High",

        "Sensitivity",
        "Sensitivity CI Low",
        "Sensitivity CI High",

        "Specificity",
        "Specificity CI Low",
        "Specificity CI High",

        "F1",
        "ROC-AUC",
        "Balanced Accuracy",
        "MCC",

        # ---------------- Confusion Matrix ----------------

        "TN",
        "FP",
        "FN",
        "TP"
    ]
]


# ============================================================
# STEP 11: DISPLAY FINAL RESULTS
# ============================================================

print(
    "\n================================================"
)

print(
    "FINAL MODEL COMPARISON"
)

print(
    "================================================\n"
)


display(
    results_df.sort_values(
        by="F1",
        ascending=False
    )
)

Raw feature statistics:
Shape : (127, 105)
NaN values before cleaning : 0
Inf values before cleaning : 0

After cleaning:
NaN values : 0
Inf values : 0
Finite     : True
Maximum    : 10000000000.0
Minimum    : -1.3317952

Final data:
X shape : (127, 105)
y shape : (127,)

Class distribution:
PD_Label_Combined
0    65
1    62
Name: count, dtype: int64

Class Weights:
{0: 0.9769230769230769, 1: 1.0241935483870968}

Train Shape : (101, 105)
Test Shape  : (26, 105)

Training Class Distribution:
PD_Label_Combined
0    52
1    49
Name: count, dtype: int64

Testing Class Distribution:
PD_Label_Combined
1    13
0    13
Name: count, dtype: int64

Training Class Weights:
{np.int64(0): np.float64(0.9711538461538461), np.int64(1): np.float64(1.030612244897959)}

XGBoost scale_pos_weight: 1.0612244897959182


################################################
Evaluating: XGBoost
################################################

XGBoost | Fold 1/10
Fold 1: max|X_val|=2.6785
Accuracy            : 0.7273
Precision           : 0.6667
Sensitivity         : 0.8000
F1 Score            : 0.7273
ROC-AUC             : 0.8333
Balanced Accuracy   : 0.7333

XGBoost | Fold 2/10
Fold 2: max|X_val|=9.0144
Accuracy            : 0.8000
Precision           : 0.6667
Sensitivity         : 1.0000
F1 Score            : 0.8000
ROC-AUC             : 1.0000
Balanced Accuracy   : 0.8333

XGBoost | Fold 3/10
Fold 3: max|X_val|=3.9953
Accuracy            : 0.8000
Precision           : 0.8000
Sensitivity         : 0.8000
F1 Score            : 0.8000
ROC-AUC             : 0.8000
Balanced Accuracy   : 0.8000

XGBoost | Fold 4/10
Fold 4: max|X_val|=2.7280
Accuracy            : 0.5000
Precision           : 0.5000
Sensitivity         : 0.4000
F1 Score            : 0.4444
ROC-AUC             : 0.7600
Balanced Accuracy   : 0.5000

XGBoost | Fold 5/10
Fold 5: max|X_val|=114.1189
Accuracy            : 0.6000
Precision           : 0.6000
Sensitivity         : 0.6000
F1 Score            : 0.6000
ROC-AUC             : 0.6600
Balanced Accuracy   : 0.6000

XGBoost | Fold 6/10
Fold 6: max|X_val|=4.6024
Accuracy            : 0.7000
Precision           : 0.7500
Sensitivity         : 0.6000
F1 Score            : 0.6667
ROC-AUC             : 0.8800
Balanced Accuracy   : 0.7000

XGBoost | Fold 7/10
Fold 7: max|X_val|=5.1882
Accuracy            : 0.7000
Precision           : 0.6667
Sensitivity         : 0.8000
F1 Score            : 0.7273
ROC-AUC             : 0.7600
Balanced Accuracy   : 0.7000

XGBoost | Fold 8/10
Fold 8: max|X_val|=65033807064500151462341811705479168.0000
Accuracy            : 0.6000
Precision           : 0.6000
Sensitivity         : 0.6000
F1 Score            : 0.6000
ROC-AUC             : 0.7600
Balanced Accuracy   : 0.6000

XGBoost | Fold 9/10
Fold 9: max|X_val|=2.8462
Accuracy            : 0.7000
Precision           : 1.0000
Sensitivity         : 0.4000
F1 Score            : 0.5714
ROC-AUC             : 0.7600
Balanced Accuracy   : 0.7000

XGBoost | Fold 10/10
Fold 10: max|X_val|=10.7091
Accuracy            : 0.8000
Precision           : 1.0000
Sensitivity         : 0.6000
F1 Score            : 0.7500
ROC-AUC             : 0.9200
Balanced Accuracy   : 0.8000

================================================
XGBoost - Cross-Validation (10-fold)
================================================
Accuracy            : 0.6927
Precision           : 0.7250
Recall/Sensitivity  : 0.6600
F1 Score            : 0.6687
ROC-AUC             : 0.8133
Balanced Accuracy   : 0.6967

================================================
XGBoost - Test Set Performance
================================================
Accuracy            : 0.6154 (95% CI: 0.4253-0.7757)
Precision           : 0.6000 (95% CI: 0.3575-0.8018)
Sensitivity         : 0.6923 (95% CI: 0.4237-0.8732)
Specificity         : 0.5385 (95% CI: 0.2914-0.7679)
F1 Score            : 0.6429
ROC-AUC             : 0.6627
Balanced Accuracy   : 0.6154
MCC                 : 0.2335

Confusion Matrix:
[[7 6]
 [4 9]]

TN : 7
FP : 6
FN : 4
TP : 9


################################################
Evaluating: Random Forest
################################################

Random Forest | Fold 1/10
Fold 1: max|X_val|=2.6785
Accuracy            : 0.7273
Precision           : 0.6667
Sensitivity         : 0.8000
F1 Score            : 0.7273
ROC-AUC             : 0.7667
Balanced Accuracy   : 0.7333

Random Forest | Fold 2/10
Fold 2: max|X_val|=9.0144
Accuracy            : 0.8000
Precision           : 0.6667
Sensitivity         : 1.0000
F1 Score            : 0.8000
ROC-AUC             : 1.0000
Balanced Accuracy   : 0.8333

Random Forest | Fold 3/10
Fold 3: max|X_val|=3.9953
Accuracy            : 0.8000
Precision           : 0.8000
Sensitivity         : 0.8000
F1 Score            : 0.8000
ROC-AUC             : 0.8000
Balanced Accuracy   : 0.8000

Random Forest | Fold 4/10
Fold 4: max|X_val|=2.7280
Accuracy            : 0.4000
Precision           : 0.3333
Sensitivity         : 0.2000
F1 Score            : 0.2500
ROC-AUC             : 0.6800
Balanced Accuracy   : 0.4000

Random Forest | Fold 5/10
Fold 5: max|X_val|=114.1189
Accuracy            : 0.6000
Precision           : 0.6000
Sensitivity         : 0.6000
F1 Score            : 0.6000
ROC-AUC             : 0.7000
Balanced Accuracy   : 0.6000

Random Forest | Fold 6/10
Fold 6: max|X_val|=4.6024
Accuracy            : 0.9000
Precision           : 0.8333
Sensitivity         : 1.0000
F1 Score            : 0.9091
ROC-AUC             : 0.9200
Balanced Accuracy   : 0.9000

Random Forest | Fold 7/10
Fold 7: max|X_val|=5.1882
Accuracy            : 0.8000
Precision           : 0.8000
Sensitivity         : 0.8000
F1 Score            : 0.8000
ROC-AUC             : 0.8800
Balanced Accuracy   : 0.8000

Random Forest | Fold 8/10
Fold 8: max|X_val|=65033807064500151462341811705479168.0000
Accuracy            : 0.7000
Precision           : 0.6667
Sensitivity         : 0.8000
F1 Score            : 0.7273
ROC-AUC             : 0.8000
Balanced Accuracy   : 0.7000

Random Forest | Fold 9/10
Fold 9: max|X_val|=2.8462
Accuracy            : 0.7000
Precision           : 1.0000
Sensitivity         : 0.4000
F1 Score            : 0.5714
ROC-AUC             : 0.7200
Balanced Accuracy   : 0.7000

Random Forest | Fold 10/10
Fold 10: max|X_val|=10.7091
Accuracy            : 0.8000
Precision           : 1.0000
Sensitivity         : 0.6000
F1 Score            : 0.7500
ROC-AUC             : 0.9200
Balanced Accuracy   : 0.8000

================================================
Random Forest - Cross-Validation (10-fold)
================================================
Accuracy            : 0.7227
Precision           : 0.7367
Recall/Sensitivity  : 0.7000
F1 Score            : 0.6935
ROC-AUC             : 0.8187
Balanced Accuracy   : 0.7267

================================================
Random Forest - Test Set Performance
================================================
Accuracy            : 0.5769 (95% CI: 0.3895-0.7446)
Precision           : 0.5833 (95% CI: 0.3195-0.8067)
Sensitivity         : 0.5385 (95% CI: 0.2914-0.7679)
Specificity         : 0.6154 (95% CI: 0.3552-0.8229)
F1 Score            : 0.5600
ROC-AUC             : 0.7101
Balanced Accuracy   : 0.5769
MCC                 : 0.1543

Confusion Matrix:
[[8 5]
 [6 7]]

TN : 8
FP : 5
FN : 6
TP : 7


################################################
Evaluating: HistGradientBoosting
################################################

HistGradientBoosting | Fold 1/10
Fold 1: max|X_val|=2.6785
Accuracy            : 0.5455
Precision           : 0.5000
Sensitivity         : 0.4000
F1 Score            : 0.4444
ROC-AUC             : 0.7000
Balanced Accuracy   : 0.5333

HistGradientBoosting | Fold 2/10
Fold 2: max|X_val|=9.0144
Accuracy            : 0.8000
Precision           : 0.6667
Sensitivity         : 1.0000
F1 Score            : 0.8000
ROC-AUC             : 0.9583
Balanced Accuracy   : 0.8333

HistGradientBoosting | Fold 3/10
Fold 3: max|X_val|=3.9953
Accuracy            : 0.8000
Precision           : 0.8000
Sensitivity         : 0.8000
F1 Score            : 0.8000
ROC-AUC             : 0.8000
Balanced Accuracy   : 0.8000

HistGradientBoosting | Fold 4/10
Fold 4: max|X_val|=2.7280
Accuracy            : 0.6000
Precision           : 0.6667
Sensitivity         : 0.4000
F1 Score            : 0.5000
ROC-AUC             : 0.7600
Balanced Accuracy   : 0.6000

HistGradientBoosting | Fold 5/10
Fold 5: max|X_val|=114.1189
Accuracy            : 0.7000
Precision           : 0.7500
Sensitivity         : 0.6000
F1 Score            : 0.6667
ROC-AUC             : 0.7400
Balanced Accuracy   : 0.7000

HistGradientBoosting | Fold 6/10
Fold 6: max|X_val|=4.6024
Accuracy            : 0.7000
Precision           : 0.7500
Sensitivity         : 0.6000
F1 Score            : 0.6667
ROC-AUC             : 0.8800
Balanced Accuracy   : 0.7000

HistGradientBoosting | Fold 7/10
Fold 7: max|X_val|=5.1882
Accuracy            : 0.6000
Precision           : 0.6000
Sensitivity         : 0.6000
F1 Score            : 0.6000
ROC-AUC             : 0.6000
Balanced Accuracy   : 0.6000

HistGradientBoosting | Fold 8/10
Fold 8: max|X_val|=65033807064500151462341811705479168.0000
Accuracy            : 0.7000
Precision           : 0.6667
Sensitivity         : 0.8000
F1 Score            : 0.7273
ROC-AUC             : 0.8000
Balanced Accuracy   : 0.7000

HistGradientBoosting | Fold 9/10
Fold 9: max|X_val|=2.8462
Accuracy            : 0.7000
Precision           : 1.0000
Sensitivity         : 0.4000
F1 Score            : 0.5714
ROC-AUC             : 0.8400
Balanced Accuracy   : 0.7000

HistGradientBoosting | Fold 10/10
Fold 10: max|X_val|=10.7091
Accuracy            : 0.9000
Precision           : 1.0000
Sensitivity         : 0.8000
F1 Score            : 0.8889
ROC-AUC             : 0.8800
Balanced Accuracy   : 0.9000

================================================
HistGradientBoosting - Cross-Validation (10-fold)
================================================
Accuracy            : 0.7045
Precision           : 0.7400
Recall/Sensitivity  : 0.6400
F1 Score            : 0.6665
ROC-AUC             : 0.7958
Balanced Accuracy   : 0.7067

================================================
HistGradientBoosting - Test Set Performance
================================================
Accuracy            : 0.5000 (95% CI: 0.3206-0.6794)
Precision           : 0.5000 (95% CI: 0.2538-0.7462)
Sensitivity         : 0.4615 (95% CI: 0.2321-0.7086)
Specificity         : 0.5385 (95% CI: 0.2914-0.7679)
F1 Score            : 0.4800
ROC-AUC             : 0.6450
Balanced Accuracy   : 0.5000
MCC                 : 0.0000

Confusion Matrix:
[[7 6]
 [7 6]]

TN : 7
FP : 6
FN : 7
TP : 6


################################################
Evaluating: Voting Fusion
################################################

Voting Fusion | Fold 1/10
Fold 1: max|X_val|=2.6785
Accuracy            : 0.6364
Precision           : 0.6000
Sensitivity         : 0.6000
F1 Score            : 0.6000
ROC-AUC             : 0.8000
Balanced Accuracy   : 0.6333

Voting Fusion | Fold 2/10
Fold 2: max|X_val|=9.0144
Accuracy            : 0.8000
Precision           : 0.6667
Sensitivity         : 1.0000
F1 Score            : 0.8000
ROC-AUC             : 0.9583
Balanced Accuracy   : 0.8333

Voting Fusion | Fold 3/10
Fold 3: max|X_val|=3.9953
Accuracy            : 0.8000
Precision           : 0.8000
Sensitivity         : 0.8000
F1 Score            : 0.8000
ROC-AUC             : 0.8400
Balanced Accuracy   : 0.8000

Voting Fusion | Fold 4/10
Fold 4: max|X_val|=2.7280
Accuracy            : 0.5000
Precision           : 0.5000
Sensitivity         : 0.4000
F1 Score            : 0.4444
ROC-AUC             : 0.7600
Balanced Accuracy   : 0.5000

Voting Fusion | Fold 5/10
Fold 5: max|X_val|=114.1189
Accuracy            : 0.7000
Precision           : 0.7500
Sensitivity         : 0.6000
F1 Score            : 0.6667
ROC-AUC             : 0.7000
Balanced Accuracy   : 0.7000

Voting Fusion | Fold 6/10
Fold 6: max|X_val|=4.6024
Accuracy            : 0.7000
Precision           : 0.7500
Sensitivity         : 0.6000
F1 Score            : 0.6667
ROC-AUC             : 0.9200
Balanced Accuracy   : 0.7000

Voting Fusion | Fold 7/10
Fold 7: max|X_val|=5.1882
Accuracy            : 0.7000
Precision           : 0.6667
Sensitivity         : 0.8000
F1 Score            : 0.7273
ROC-AUC             : 0.6800
Balanced Accuracy   : 0.7000

Voting Fusion | Fold 8/10
Fold 8: max|X_val|=65033807064500151462341811705479168.0000
Accuracy            : 0.7000
Precision           : 0.6667
Sensitivity         : 0.8000
F1 Score            : 0.7273
ROC-AUC             : 0.7600
Balanced Accuracy   : 0.7000

Voting Fusion | Fold 9/10
Fold 9: max|X_val|=2.8462
Accuracy            : 0.7000
Precision           : 1.0000
Sensitivity         : 0.4000
F1 Score            : 0.5714
ROC-AUC             : 0.6400
Balanced Accuracy   : 0.7000

Voting Fusion | Fold 10/10
Fold 10: max|X_val|=10.7091
Accuracy            : 0.9000
Precision           : 1.0000
Sensitivity         : 0.8000
F1 Score            : 0.8889
ROC-AUC             : 0.9200
Balanced Accuracy   : 0.9000

================================================
Voting Fusion - Cross-Validation (10-fold)
================================================
Accuracy            : 0.7136
Precision           : 0.7400
Recall/Sensitivity  : 0.6800
F1 Score            : 0.6893
ROC-AUC             : 0.7978
Balanced Accuracy   : 0.7167

================================================
Voting Fusion - Test Set Performance
================================================
Accuracy            : 0.5769 (95% CI: 0.3895-0.7446)
Precision           : 0.5625 (95% CI: 0.3318-0.7690)
Sensitivity         : 0.6923 (95% CI: 0.4237-0.8732)
Specificity         : 0.4615 (95% CI: 0.2321-0.7086)
F1 Score            : 0.6207
ROC-AUC             : 0.6509
Balanced Accuracy   : 0.5769
MCC                 : 0.1581

Confusion Matrix:
[[6 7]
 [4 9]]

TN : 6
FP : 7
FN : 4
TP : 9


################################################
Evaluating: Stacking Fusion
################################################

Stacking Fusion | Fold 1/10
Fold 1: max|X_val|=2.6785
Accuracy            : 0.7273
Precision           : 0.6667
Sensitivity         : 0.8000
F1 Score            : 0.7273
ROC-AUC             : 0.8667
Balanced Accuracy   : 0.7333

Stacking Fusion | Fold 2/10
Fold 2: max|X_val|=9.0144
Accuracy            : 0.6000
Precision           : 0.5000
Sensitivity         : 1.0000
F1 Score            : 0.6667
ROC-AUC             : 1.0000
Balanced Accuracy   : 0.6667

Stacking Fusion | Fold 3/10
Fold 3: max|X_val|=3.9953
Accuracy            : 0.7000
Precision           : 0.6667
Sensitivity         : 0.8000
F1 Score            : 0.7273
ROC-AUC             : 0.7600
Balanced Accuracy   : 0.7000

Stacking Fusion | Fold 4/10
Fold 4: max|X_val|=2.7280
Accuracy            : 0.6000
Precision           : 0.6667
Sensitivity         : 0.4000
F1 Score            : 0.5000
ROC-AUC             : 0.7200
Balanced Accuracy   : 0.6000

Stacking Fusion | Fold 5/10
Fold 5: max|X_val|=114.1189
Accuracy            : 0.6000
Precision           : 0.6000
Sensitivity         : 0.6000
F1 Score            : 0.6000
ROC-AUC             : 0.5400
Balanced Accuracy   : 0.6000

Stacking Fusion | Fold 6/10
Fold 6: max|X_val|=4.6024
Accuracy            : 0.8000
Precision           : 1.0000
Sensitivity         : 0.6000
F1 Score            : 0.7500
ROC-AUC             : 0.7600
Balanced Accuracy   : 0.8000

Stacking Fusion | Fold 7/10
Fold 7: max|X_val|=5.1882
Accuracy            : 0.8000
Precision           : 1.0000
Sensitivity         : 0.6000
F1 Score            : 0.7500
ROC-AUC             : 0.6800
Balanced Accuracy   : 0.8000

Stacking Fusion | Fold 8/10
Fold 8: max|X_val|=65033807064500151462341811705479168.0000
Accuracy            : 0.8000
Precision           : 0.7143
Sensitivity         : 1.0000
F1 Score            : 0.8333
ROC-AUC             : 0.8000
Balanced Accuracy   : 0.8000

Stacking Fusion | Fold 9/10
Fold 9: max|X_val|=2.8462
Accuracy            : 0.8000
Precision           : 1.0000
Sensitivity         : 0.6000
F1 Score            : 0.7500
ROC-AUC             : 0.7200
Balanced Accuracy   : 0.8000

Stacking Fusion | Fold 10/10
Fold 10: max|X_val|=10.7091
Accuracy            : 0.7000
Precision           : 0.7500
Sensitivity         : 0.6000
F1 Score            : 0.6667
ROC-AUC             : 0.7200
Balanced Accuracy   : 0.7000

================================================
Stacking Fusion - Cross-Validation (10-fold)
================================================
Accuracy            : 0.7127
Precision           : 0.7564
Recall/Sensitivity  : 0.7000
F1 Score            : 0.6971
ROC-AUC             : 0.7567
Balanced Accuracy   : 0.7200

================================================
Stacking Fusion - Test Set Performance
================================================
Accuracy            : 0.6923 (95% CI: 0.5001-0.8350)
Precision           : 0.6667 (95% CI: 0.4171-0.8482)
Sensitivity         : 0.7692 (95% CI: 0.4974-0.9182)
Specificity         : 0.6154 (95% CI: 0.3552-0.8229)
F1 Score            : 0.7143
ROC-AUC             : 0.7456
Balanced Accuracy   : 0.6923
MCC                 : 0.3892

Confusion Matrix:
[[ 8  5]
 [ 3 10]]

TN : 8
FP : 5
FN : 3
TP : 10

================================================
FINAL MODEL COMPARISON
================================================

,CV Accuracy,CV Precision,CV Sensitivity,CV F1,CV ROC-AUC,CV Balanced Accuracy,Accuracy,Accuracy CI Low,Accuracy CI High,Precision,...,Specificity CI Low,Specificity CI High,F1,ROC-AUC,Balanced Accuracy,MCC,TN,FP,FN,TP
Stacking Fusion,0.712727,0.756429,0.70,0.697121,0.756667,0.720000,0.692308,0.500117,0.834987,0.666667,...,0.355229,0.822903,0.714286,0.745562,0.692308,0.389249,8.0,5.0,3.0,10.0
XGBoost,0.692727,0.725000,0.66,0.668709,0.813333,0.696667,0.615385,0.425349,0.775714,0.600000,...,0.291438,0.767939,0.642857,0.662722,0.615385,0.233550,7.0,6.0,4.0,9.0
Voting Fusion,0.713636,0.740000,0.68,0.689264,0.797833,0.716667,0.576923,0.389486,0.744556,0.562500,...,0.232061,0.708562,0.620690,0.650888,0.576923,0.158114,6.0,7.0,4.0,9.0
Random Forest,0.722727,0.736667,0.70,0.693506,0.818667,0.726667,0.576923,0.389486,0.744556,0.583333,...,0.355229,0.822903,0.560000,0.710059,0.576923,0.154303,8.0,5.0,6.0,7.0
HistGradientBoosting,0.704545,0.740000,0.64,0.666537,0.795833,0.706667,0.500000,0.320606,0.679394,0.500000,...,0.291438,0.767939,0.480000,0.644970,0.500000,0.000000,7.0,6.0,7.0,6.0

***Meg-passive task***

With MIRA-Net

In [1]:
# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

final_meg_df = pd.read_csv('/content/drive/MyDrive/final_meg_passive_21_par-lev_final.csv')

print("Loaded data shape:", final_meg_df.shape)
print(final_meg_df.head())

Loaded data shape: (127, 106)
   burst_rate_L_mean  burst_rate_L_std  burst_rate_R_mean  burst_rate_R_std  \
0           4.307989          0.204442           4.411462          0.166274
1           3.640013          0.519092           3.661284          0.572175
2           4.518955          0.174000           4.563599          0.153873
3           4.057439          0.259270           4.177064          0.215284
4           4.025205          0.324785           4.047333          0.306122

   burst_rate_asym  mean_burst_duration_L_mean  mean_burst_duration_L_std  \
0        -0.011867                    0.058159                   0.002800
1        -0.002913                    0.070172                   0.010659
2        -0.004915                    0.055402                   0.002179
3        -0.014527                    0.061874                   0.004100
4        -0.002741                    0.062525                   0.005235

   mean_burst_duration_R_mean  mean_burst_duration_R_std  \
0                    0.056750                   0.002180
1                    0.070130                   0.012065
2                    0.054841                   0.001874
3                    0.060008                   0.003089
4                    0.062123                   0.004726

   mean_burst_duration_asym  ...  spectral_flatness_L_std  \
0                  0.012260  ...                 0.067009
1                  0.000296  ...                 0.054090
2                  0.005089  ...                 0.019396
3                  0.015307  ...                 0.059372
4                  0.003232  ...                 0.035967

   spectral_flatness_R_mean  spectral_flatness_R_std  spectral_flatness_asym  \
0                  0.924763                 0.056414               -0.005716
1                  0.904192                 0.054053               -0.001599
2                  0.970397                 0.019833               -0.000493
3                  0.856283                 0.048577               -0.004424
4                  0.916349                 0.027035               -0.003870

   spectral_slope_L_mean  spectral_slope_L_std  spectral_slope_R_mean  \
0          -3.355146e-13          4.743884e-13          -1.831488e-13
1          -7.294939e-13          8.859464e-13          -6.976051e-13
2          -8.533174e-14          1.089821e-13          -8.562178e-14
3          -8.767126e-13          1.197989e-12          -3.583790e-13
4          -5.900980e-13          7.427183e-13          -2.455170e-13

   spectral_slope_R_std  spectral_slope_asym  Pd_indicator_meg
0          2.524731e-13        -1.523737e-05                 0
1          8.500454e-13        -3.189341e-06                 0
2          1.041308e-13         2.900524e-08                 0
3          4.214089e-13        -5.183976e-05                 1
4          2.848580e-13        -3.446098e-05                 1

[5 rows x 106 columns]

In [3]:
# ============================================================
#     SIMPLE + STABLE DANN + SCL + MLP CLASSIFIER
#     CROSS-MODAL + CROSS-PARTICIPANT ANALYSIS
# ============================================================

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from torch.autograd import Function
import torch.nn.functional as F

import numpy as np

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# ============================================================
# LOAD DATA
# ============================================================

# First 7 columns -> Features
# Last column     -> PD / HC labels


# ============================================================
# MEG FEATURES AND LABELS
# ============================================================

# All columns except the last one are MEG features
X_meg = final_meg_df.iloc[:, :-1].copy()

# Convert features to numeric
X_meg = X_meg.apply(
    pd.to_numeric,
    errors="coerce"
)

# Replace +inf and -inf with NaN
X_meg = X_meg.replace(
    [np.inf, -np.inf],
    np.nan
)

# ------------------------------------------------------------
# Check invalid values
# ------------------------------------------------------------

print(
    "NaN values before cleaning:",
    X_meg.isna().sum().sum()
)

print(
    "Infinite values before cleaning:",
    np.isinf(
        X_meg.select_dtypes(include=np.number)
    ).sum().sum()
)

# ------------------------------------------------------------
# Replace NaN with column median
# ------------------------------------------------------------

X_meg = X_meg.fillna(
    X_meg.median(numeric_only=True)
)

# Any remaining NaN -> 0
X_meg = X_meg.fillna(0)

# Convert to float64 to avoid float32 overflow
X_meg = X_meg.values.astype(np.float64)

# Labels
y_meg = final_meg_df.iloc[:, -1].values.astype(np.int64)

# ============================================================
# FINAL CHECK BEFORE STANDARDIZATION
# ============================================================

print(
    "All MEG values finite:",
    np.isfinite(X_meg).all()
)

print(
    "Maximum absolute MEG value:",
    np.max(np.abs(X_meg))
)

# ============================================================
# STANDARDIZATION
# ============================================================

scaler_meg = StandardScaler()

X_meg = scaler_meg.fit_transform(
    X_meg
)

# ============================================================
# FINAL CHECK AFTER STANDARDIZATION
# ============================================================

print(
    "All standardized values finite:",
    np.isfinite(X_meg).all()
)

print(
    "Standardized MEG shape:",
    X_meg.shape
)

# ============================================================
# DOMAIN LABELS
# ============================================================

# 0 -> Acoustic
# 1 -> MEG

domain_meg = np.ones(
    len(X_meg)
)

# ============================================================
# COMBINE
# ============================================================

X_all = np.vstack([

    X_meg
]).astype(np.float32)

task_labels = np.hstack([

    y_meg
]).astype(np.int64)

domain_labels = np.hstack([

    domain_meg
]).astype(np.int64)

# ============================================================
# TENSORS
# ============================================================

X_all_tensor = torch.tensor(
    X_all
).float().to(device)

task_labels_tensor = torch.tensor(
    task_labels
).long().to(device)

domain_labels_tensor = torch.tensor(
    domain_labels
).long().to(device)

# ============================================================
# GRADIENT REVERSAL
# ============================================================

class GradReverse(Function):

    @staticmethod
    def forward(ctx, x, lambd):

        ctx.lambd = lambd

        return x.view_as(x)

    @staticmethod
    def backward(ctx, grad_output):

        return -ctx.lambd * grad_output, None

def grad_reverse(x, lambd):

    return GradReverse.apply(x, lambd)

# ============================================================
# SIMPLE RESIDUAL BLOCK
# ============================================================

class ResidualBlock(nn.Module):

    def __init__(self, dim):

        super().__init__()

        self.block = nn.Sequential(

            nn.Linear(dim, dim),
            nn.ReLU(),

            nn.Linear(dim, dim)
        )

    def forward(self, x):

        return F.relu(
            self.block(x) + x
        )

# ============================================================
# DANN + SCL MODEL
# ============================================================

class DANNContrastive(nn.Module):

    def __init__(self, input_dim, latent_dim=32):

        super().__init__()

        # ====================================================
        # SIMPLE ENCODER
        # ====================================================

        self.encoder = nn.Sequential(

            nn.Linear(input_dim, 128),
            nn.ReLU(),

            ResidualBlock(128),

            nn.Linear(128, 64),
            nn.ReLU(),

            nn.Dropout(0.1),

            nn.Linear(64, latent_dim)
        )

        # ====================================================
        # TASK HEAD
        # ====================================================

        self.task_head = nn.Sequential(

            nn.Linear(latent_dim, 32),
            nn.ReLU(),

            nn.Dropout(0.2),

            nn.Linear(32, 2)
        )

        # ====================================================
        # DOMAIN HEAD
        # ====================================================

        self.domain_head = nn.Sequential(

            nn.Linear(latent_dim, 16),
            nn.ReLU(),

            nn.Linear(16, 2)
        )

    def forward(self, x, lambd=1.0):

        z = self.encoder(x)

        # L2 NORMALIZATION

        z_norm = F.normalize(
            z,
            p=2,
            dim=1
        )

        # DANN

        rev_z = grad_reverse(
            z_norm,
            lambd
        )

        task_out = self.task_head(z_norm)

        domain_out = self.domain_head(rev_z)

        return task_out, domain_out, z_norm

# ============================================================
# SUPERVISED CONTRASTIVE LOSS
# ============================================================

class SupConLoss(nn.Module):

    def __init__(self, temperature=0.07):

        super().__init__()

        self.temperature = temperature

    def forward(self, features, labels):

        device = features.device

        labels = labels.contiguous().view(-1, 1)

        mask = torch.eq(
            labels,
            labels.T
        ).float().to(device)

        similarity = torch.matmul(
            features,
            features.T
        ) / self.temperature

        logits_max, _ = torch.max(
            similarity,
            dim=1,
            keepdim=True
        )

        logits = similarity - logits_max.detach()

        logits_mask = torch.ones_like(mask) - torch.eye(
            mask.shape[0]
        ).to(device)

        mask = mask * logits_mask

        exp_logits = torch.exp(logits) * logits_mask

        log_prob = logits - torch.log(
            exp_logits.sum(1, keepdim=True) + 1e-8
        )

        mean_log_prob_pos = (
            mask * log_prob
        ).sum(1) / (mask.sum(1) + 1e-8)

        loss = -mean_log_prob_pos.mean()

        return loss

# ============================================================
# DATA LOADER
# ============================================================

dataset = TensorDataset(
    X_all_tensor,
    task_labels_tensor,
    domain_labels_tensor
)

loader = DataLoader(
    dataset,
    batch_size=128,
    shuffle=True
)

# ============================================================
# MODEL
# ============================================================

model = DANNContrastive(
    input_dim=X_all.shape[1],
    latent_dim=32
).to(device)

# ============================================================
# OPTIMIZER
# ============================================================

optimizer = optim.Adam(
    model.parameters(),
    lr=1e-3,
    weight_decay=1e-4
)

# ============================================================
# LOSSES
# ============================================================

task_loss_fn = nn.CrossEntropyLoss()

domain_loss_fn = nn.CrossEntropyLoss()

contrastive_loss_fn = SupConLoss(
    temperature=0.07
)

epochs = 120

print("\nTraining Started...\n")

# ============================================================
# TRAINING
# ============================================================

for epoch in range(epochs):

    model.train()

    total_correct = 0
    total_samples = 0

    # ========================================================
    # WEAKER DANN
    # ========================================================

    p = min(epoch / 50.0, 1.0)

    lambd = 0.25 * (
        2 / (1 + np.exp(-10 * p)) - 1
    )

    for xb, y_task, y_dom in loader:

        optimizer.zero_grad()

        task_out, dom_out, z = model(
            xb,
            lambd
        )

        # ====================================================
        # LOSSES
        # ====================================================

        loss_task = task_loss_fn(
            task_out,
            y_task
        )

        loss_domain = domain_loss_fn(
            dom_out,
            y_dom
        )

        loss_contrastive = contrastive_loss_fn(
            z,
            y_task
        )

        # ====================================================
        # FINAL LOSS
        # ====================================================

        loss = (
            3.0 * loss_task +
            0.25 * loss_domain +
            0.55 * loss_contrastive
        )

        loss.backward()

        optimizer.step()

        preds = task_out.argmax(1)

        total_correct += (
            preds == y_task
        ).sum().item()

        total_samples += len(y_task)

    acc = total_correct / total_samples

    print(
        f"Epoch {epoch+1}/{epochs} "
        f"| λ={lambd:.3f} "
        f"| Acc={acc:.4f}"
    )

# ============================================================
# EXTRACT LATENT FEATURES
# ============================================================

model.eval()

with torch.no_grad():

    fused_meg_32D = model(
        torch.tensor(X_meg).float().to(device),
        0
    )[2].cpu().numpy()

# ============================================================
# COMBINE LATENTS
# ============================================================

X_fused = np.vstack([

    fused_meg_32D
])

y_fused = np.hstack([

    y_meg
])

# ============================================================
# SIMPLE MLP CLASSIFIER
# ============================================================

class FinalMLP(nn.Module):

    def __init__(self, input_dim=32):

        super().__init__()

        self.net = nn.Sequential(

            nn.Linear(input_dim, 64),
            nn.ReLU(),

            nn.Dropout(0.2),

            nn.Linear(64, 32),
            nn.ReLU(),

            nn.Linear(32, 2)
        )

    def forward(self, x):

        return self.net(x)

# ============================================================
# CROSS PARTICIPANT EVALUATION
# ============================================================

print("\n======================================")
print(" CROSS PARTICIPANT ANALYSIS")
print("======================================\n")

skf = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

accs = []
precs = []
recs = []
f1s = []
aucs = []

fold = 1

for train_idx, test_idx in skf.split(X_fused, y_fused):

    X_train = torch.tensor(
        X_fused[train_idx]
    ).float().to(device)

    X_test = torch.tensor(
        X_fused[test_idx]
    ).float().to(device)

    y_train = torch.tensor(
        y_fused[train_idx]
    ).long().to(device)

    y_test = y_fused[test_idx]

    clf = FinalMLP().to(device)

    optimizer_clf = optim.Adam(
        clf.parameters(),
        lr=1e-3
    )

    criterion = nn.CrossEntropyLoss()

    # ========================================================
    # TRAIN MLP
    # ========================================================

    clf.train()

    for epoch in range(80):

        optimizer_clf.zero_grad()

        outputs = clf(X_train)

        loss = criterion(
            outputs,
            y_train
        )

        loss.backward()

        optimizer_clf.step()

    # ========================================================
    # TEST
    # ========================================================

    clf.eval()

    with torch.no_grad():

        outputs = clf(X_test)

        probs = F.softmax(
            outputs,
            dim=1
        )[:, 1].cpu().numpy()

        preds = outputs.argmax(1).cpu().numpy()

    acc = accuracy_score(y_test, preds)

    prec = precision_score(y_test, preds)

    rec = recall_score(y_test, preds)

    f1 = f1_score(y_test, preds)

    auc = roc_auc_score(y_test, probs)

    accs.append(acc)
    precs.append(prec)
    recs.append(rec)
    f1s.append(f1)
    aucs.append(auc)

    print(f"Fold {fold}")

    print(f"Accuracy  : {acc:.4f}")
    print(f"Precision : {prec:.4f}")
    print(f"Recall    : {rec:.4f}")
    print(f"F1-Score  : {f1:.4f}")
    print(f"AUC       : {auc:.4f}")

    print()

    fold += 1

# ============================================================
# FINAL RESULTS
# ============================================================

print("\n======================================")
print(" FINAL RESULTS")
print("======================================\n")

print(f"Mean Accuracy  : {np.mean(accs)*100:.2f}%")
print(f"Mean Precision : {np.mean(precs)*100:.2f}%")
print(f"Mean Recall    : {np.mean(recs)*100:.2f}%")
print(f"Mean F1-Score  : {np.mean(f1s)*100:.2f}%")
print(f"Mean AUC       : {np.mean(aucs)*100:.2f}%")

print("\n======================================")
print(" LATENT SHAPES")
print("======================================\n")


print("MEG      :", fused_meg_32D.shape)

NaN values before cleaning: 0
Infinite values before cleaning: 0
All MEG values finite: True
Maximum absolute MEG value: 5.596228423086247e+52
All standardized values finite: True
Standardized MEG shape: (127, 105)

Training Started...

Epoch 1/120 | λ=0.000 | Acc=0.5118
Epoch 2/120 | λ=0.025 | Acc=0.5118
Epoch 3/120 | λ=0.049 | Acc=0.5118
Epoch 4/120 | λ=0.073 | Acc=0.5118
Epoch 5/120 | λ=0.095 | Acc=0.5118
Epoch 6/120 | λ=0.116 | Acc=0.5118
Epoch 7/120 | λ=0.134 | Acc=0.5118
Epoch 8/120 | λ=0.151 | Acc=0.5118
Epoch 9/120 | λ=0.166 | Acc=0.5118
Epoch 10/120 | λ=0.179 | Acc=0.5118
Epoch 11/120 | λ=0.190 | Acc=0.5118
Epoch 12/120 | λ=0.200 | Acc=0.5118
Epoch 13/120 | λ=0.208 | Acc=0.5118
Epoch 14/120 | λ=0.215 | Acc=0.5118
Epoch 15/120 | λ=0.221 | Acc=0.5197
Epoch 16/120 | λ=0.226 | Acc=0.5354
Epoch 17/120 | λ=0.230 | Acc=0.5276
Epoch 18/120 | λ=0.234 | Acc=0.5118
Epoch 19/120 | λ=0.237 | Acc=0.5512
Epoch 20/120 | λ=0.239 | Acc=0.5669
Epoch 21/120 | λ=0.241 | Acc=0.5354
Epoch 22/120 | λ=0.243 | Acc=0.5669
Epoch 23/120 | λ=0.244 | Acc=0.5669
Epoch 24/120 | λ=0.245 | Acc=0.6457
Epoch 25/120 | λ=0.246 | Acc=0.5669
Epoch 26/120 | λ=0.247 | Acc=0.6220
Epoch 27/120 | λ=0.247 | Acc=0.6929
Epoch 28/120 | λ=0.248 | Acc=0.7323
Epoch 29/120 | λ=0.248 | Acc=0.7087
Epoch 30/120 | λ=0.248 | Acc=0.7244
Epoch 31/120 | λ=0.249 | Acc=0.8031
Epoch 32/120 | λ=0.249 | Acc=0.8189
Epoch 33/120 | λ=0.249 | Acc=0.8110
Epoch 34/120 | λ=0.249 | Acc=0.8504
Epoch 35/120 | λ=0.249 | Acc=0.8504
Epoch 36/120 | λ=0.250 | Acc=0.8740
Epoch 37/120 | λ=0.250 | Acc=0.8268
Epoch 38/120 | λ=0.250 | Acc=0.8898
Epoch 39/120 | λ=0.250 | Acc=0.9528
Epoch 40/120 | λ=0.250 | Acc=0.9370
Epoch 41/120 | λ=0.250 | Acc=0.9606
Epoch 42/120 | λ=0.250 | Acc=0.9843
Epoch 43/120 | λ=0.250 | Acc=0.9921
Epoch 44/120 | λ=0.250 | Acc=0.9764
Epoch 45/120 | λ=0.250 | Acc=0.9921
Epoch 46/120 | λ=0.250 | Acc=0.9921
Epoch 47/120 | λ=0.250 | Acc=0.9921
Epoch 48/120 | λ=0.250 | Acc=0.9921
Epoch 49/120 | λ=0.250 | Acc=0.9921
Epoch 50/120 | λ=0.250 | Acc=0.9921
Epoch 51/120 | λ=0.250 | Acc=0.9921
Epoch 52/120 | λ=0.250 | Acc=0.9921
Epoch 53/120 | λ=0.250 | Acc=0.9921
Epoch 54/120 | λ=0.250 | Acc=0.9921
Epoch 55/120 | λ=0.250 | Acc=0.9921
Epoch 56/120 | λ=0.250 | Acc=0.9921
Epoch 57/120 | λ=0.250 | Acc=0.9921
Epoch 58/120 | λ=0.250 | Acc=0.9921
Epoch 59/120 | λ=0.250 | Acc=0.9921
Epoch 60/120 | λ=0.250 | Acc=0.9921
Epoch 61/120 | λ=0.250 | Acc=0.9921
Epoch 62/120 | λ=0.250 | Acc=1.0000
Epoch 63/120 | λ=0.250 | Acc=0.9921
Epoch 64/120 | λ=0.250 | Acc=0.9921
Epoch 65/120 | λ=0.250 | Acc=0.9921
Epoch 66/120 | λ=0.250 | Acc=0.9921
Epoch 67/120 | λ=0.250 | Acc=0.9921
Epoch 68/120 | λ=0.250 | Acc=0.9921
Epoch 69/120 | λ=0.250 | Acc=0.9921
Epoch 70/120 | λ=0.250 | Acc=0.9843
Epoch 71/120 | λ=0.250 | Acc=0.9921
Epoch 72/120 | λ=0.250 | Acc=0.9921
Epoch 73/120 | λ=0.250 | Acc=0.9921
Epoch 74/120 | λ=0.250 | Acc=0.9921
Epoch 75/120 | λ=0.250 | Acc=0.9921
Epoch 76/120 | λ=0.250 | Acc=0.9921
Epoch 77/120 | λ=0.250 | Acc=0.9921
Epoch 78/120 | λ=0.250 | Acc=0.9921
Epoch 79/120 | λ=0.250 | Acc=0.9921
Epoch 80/120 | λ=0.250 | Acc=0.9921
Epoch 81/120 | λ=0.250 | Acc=0.9921
Epoch 82/120 | λ=0.250 | Acc=0.9921
Epoch 83/120 | λ=0.250 | Acc=0.9921
Epoch 84/120 | λ=0.250 | Acc=0.9921
Epoch 85/120 | λ=0.250 | Acc=0.9921
Epoch 86/120 | λ=0.250 | Acc=0.9921
Epoch 87/120 | λ=0.250 | Acc=0.9921
Epoch 88/120 | λ=0.250 | Acc=0.9921
Epoch 89/120 | λ=0.250 | Acc=0.9921
Epoch 90/120 | λ=0.250 | Acc=0.9921
Epoch 91/120 | λ=0.250 | Acc=0.9921
Epoch 92/120 | λ=0.250 | Acc=0.9921
Epoch 93/120 | λ=0.250 | Acc=0.9921
Epoch 94/120 | λ=0.250 | Acc=0.9921
Epoch 95/120 | λ=0.250 | Acc=0.9921
Epoch 96/120 | λ=0.250 | Acc=0.9921
Epoch 97/120 | λ=0.250 | Acc=0.9921
Epoch 98/120 | λ=0.250 | Acc=0.9921
Epoch 99/120 | λ=0.250 | Acc=0.9921
Epoch 100/120 | λ=0.250 | Acc=0.9921
Epoch 101/120 | λ=0.250 | Acc=0.9921
Epoch 102/120 | λ=0.250 | Acc=0.9921
Epoch 103/120 | λ=0.250 | Acc=0.9921
Epoch 104/120 | λ=0.250 | Acc=0.9921
Epoch 105/120 | λ=0.250 | Acc=0.9921
Epoch 106/120 | λ=0.250 | Acc=0.9921
Epoch 107/120 | λ=0.250 | Acc=0.9921
Epoch 108/120 | λ=0.250 | Acc=0.9921
Epoch 109/120 | λ=0.250 | Acc=0.9921
Epoch 110/120 | λ=0.250 | Acc=0.9921
Epoch 111/120 | λ=0.250 | Acc=0.9921
Epoch 112/120 | λ=0.250 | Acc=0.9921
Epoch 113/120 | λ=0.250 | Acc=0.9921
Epoch 114/120 | λ=0.250 | Acc=0.9921
Epoch 115/120 | λ=0.250 | Acc=0.9921
Epoch 116/120 | λ=0.250 | Acc=0.9921
Epoch 117/120 | λ=0.250 | Acc=0.9921
Epoch 118/120 | λ=0.250 | Acc=0.9921
Epoch 119/120 | λ=0.250 | Acc=0.9921
Epoch 120/120 | λ=0.250 | Acc=0.9921

======================================
 CROSS PARTICIPANT ANALYSIS
======================================

Fold 1
Accuracy  : 1.0000
Precision : 1.0000
Recall    : 1.0000
F1-Score  : 1.0000
AUC       : 1.0000

Fold 2
Accuracy  : 1.0000
Precision : 1.0000
Recall    : 1.0000
F1-Score  : 1.0000
AUC       : 1.0000

Fold 3
Accuracy  : 1.0000
Precision : 1.0000
Recall    : 1.0000
F1-Score  : 1.0000
AUC       : 1.0000

Fold 4
Accuracy  : 1.0000
Precision : 1.0000
Recall    : 1.0000
F1-Score  : 1.0000
AUC       : 1.0000

Fold 5
Accuracy  : 0.9600
Precision : 1.0000
Recall    : 0.9167
F1-Score  : 0.9565
AUC       : 1.0000


======================================
 FINAL RESULTS
======================================

Mean Accuracy  : 99.20%
Mean Precision : 100.00%
Mean Recall    : 98.33%
Mean F1-Score  : 99.13%
Mean AUC       : 100.00%

======================================
 LATENT SHAPES
======================================

MEG      : (127, 32)

In [4]:
import torch

# Assuming fused_acoustic_32D and fused_meg_32D are numpy arrays of shape (7350, 32)

# Step 1: Convert numpy arrays to torch tensors (float32)

fused_meg_tensor = torch.from_numpy(fused_meg_32D).float()

# Step 2: Concatenate row-wise (along dim=0)
fused_output_tensor = torch.cat([fused_meg_tensor], dim=0)  # Shape: (14700, 32)

# Step 3: Print shape and dtype
print(fused_output_tensor.shape)  # torch.Size([14700, 32])
print(fused_output_tensor.dtype)  # torch.float32

torch.Size([127, 32])
torch.float32

In [5]:
import torch
import numpy as np

# ------------------------
# Step 1: Extract targets correctly
# ------------------------

# Acoustic target from df_acoustic_top7 (last column)


# MEG target from final_meg_df (last column)
y_meg = final_meg_df.iloc[:, -1].values.astype(np.int32)           # (7350,)

# Convert to tensors (reshape to column)
 # (7350, 1)
meg_target_tensor      = torch.tensor(y_meg).long().reshape(-1, 1)        # (7350, 1)

# ------------------------
# Step 2: Convert 32D latent features to tensors
# ------------------------

# (7350, 32)
fused_meg_tensor      = torch.from_numpy(fused_meg_32D).float()       # (7350, 32)

# ------------------------
# Step 3: Attach target columns
# ------------------------

# Concatenate latent features with target

meg_full      = torch.cat([fused_meg_tensor,      meg_target_tensor.float()],      dim=1)  # (7350, 65)

# ------------------------
# Step 4: Concatenate both datasets
# ------------------------

fused_df = torch.cat([meg_full], dim=0)  # (14700, 65)

# ------------------------
# Step 5: Separate features and labels for PyTorch
# ------------------------

X = fused_df[:, :-1].float()   # Features (32D) -> float32
y = fused_df[:, -1].long()     # Target -> int32

# ------------------------
# Step 6: Print shapes and dtypes
# ------------------------

print(f"Features shape: {X.shape}, dtype: {X.dtype}")  # (14700, 32), float32
print(f"Labels shape: {y.shape}, dtype: {y.dtype}")    # (14700,), int32

Features shape: torch.Size([127, 32]), dtype: torch.float32
Labels shape: torch.Size([127]), dtype: torch.int64

In [6]:
import torch
import pandas as pd

# fused_df shape = (14700, 33)

# Step 6: Convert fused tensor to numpy
fused_df_np = fused_df.numpy()

# Step 7: Create correct column names for 32 latent features + 1 label
feature_names = [f"feat_{i}" for i in range(32)]
feature_names.append("PD_Label_Combined")

# Step 8: Convert to DataFrame
fused_df_named = pd.DataFrame(fused_df_np, columns=feature_names)

# Step 9: Verify
print(fused_df_named.shape)
print(fused_df_named.head())
print(fused_df_named.tail())

(127, 33)
     feat_0    feat_1    feat_2    feat_3    feat_4    feat_5    feat_6  \
0  0.087140  0.096083  0.049204 -0.071214  0.214633  0.095384  0.153374
1  0.076432  0.076741  0.077576 -0.068338  0.216998  0.122726  0.159202
2  0.064832  0.118307  0.034137 -0.057597  0.265400  0.071063  0.165341
3 -0.220202  0.304828 -0.259936 -0.065405  0.311552 -0.204893  0.201435
4 -0.223483  0.313236 -0.256013 -0.067937  0.292214 -0.194846  0.215071

     feat_7    feat_8    feat_9  ...   feat_23   feat_24   feat_25   feat_26  \
0  0.188717  0.218071 -0.168180  ...  0.126722 -0.229567  0.175720  0.194382
1  0.180173  0.198234 -0.190945  ...  0.115547 -0.194368  0.155384  0.203362
2  0.232546  0.207809 -0.185457  ...  0.090002 -0.209709  0.162844  0.182451
3 -0.005492  0.216769 -0.117691  ... -0.149213  0.062661 -0.145674  0.007600
4 -0.010638  0.243313 -0.133310  ... -0.137389  0.058514 -0.145171  0.022605

    feat_27   feat_28   feat_29   feat_30   feat_31  PD_Label_Combined
0 -0.003952  0.151453  0.251947 -0.140546 -0.103983                0.0
1 -0.026240  0.125245  0.267916 -0.163753 -0.127173                0.0
2 -0.014093  0.140906  0.238341 -0.128308 -0.138824                0.0
3  0.190504 -0.166660 -0.166704  0.096099 -0.259555                1.0
4  0.195833 -0.152784 -0.162052  0.071212 -0.238080                1.0

[5 rows x 33 columns]
       feat_0    feat_1    feat_2    feat_3    feat_4    feat_5    feat_6  \
122  0.051656  0.089501  0.069233 -0.077706  0.248062  0.099679  0.191876
123 -0.238439  0.308266 -0.253090 -0.069775  0.285194 -0.190688  0.178076
124  0.079733  0.088164  0.057558 -0.048568  0.242867  0.087982  0.159033
125  0.067840  0.098507  0.075400 -0.063639  0.238596  0.097726  0.153156
126 -0.249997  0.314058 -0.258606 -0.079688  0.276846 -0.212123  0.173098

       feat_7    feat_8    feat_9  ...   feat_23   feat_24   feat_25  \
122  0.206238  0.224738 -0.174753  ...  0.126133 -0.186243  0.150569
123  0.013317  0.237828 -0.140185  ... -0.161989  0.093002 -0.130400
124  0.200692  0.184729 -0.181497  ...  0.107231 -0.207593  0.167812
125  0.202223  0.210917 -0.182649  ...  0.111672 -0.204548  0.153336
126  0.019808  0.254314 -0.143918  ... -0.148006  0.067955 -0.118290

      feat_26   feat_27   feat_28   feat_29   feat_30   feat_31  \
122  0.185238 -0.035778  0.112964  0.256865 -0.147285 -0.119434
123  0.012412  0.164969 -0.149655 -0.147717  0.104826 -0.269381
124  0.184332 -0.024039  0.144428  0.252033 -0.143213 -0.126790
125  0.199316 -0.020878  0.136441  0.254555 -0.153445 -0.127854
126  0.011948  0.177278 -0.152343 -0.143419  0.102158 -0.242025

     PD_Label_Combined
122                0.0
123                1.0
124                0.0
125                0.0
126                1.0

[5 rows x 33 columns]

In [7]:
# Make a copy to be safe (optional)
fused_df_named_int = fused_df_named.copy()

# Convert only the last column to int
fused_df_named_int['PD_Label_Combined'] = fused_df_named_int['PD_Label_Combined'].astype(int)

# Verify
print(fused_df_named_int.dtypes)
print(fused_df_named_int.head())

feat_0               float32
feat_1               float32
feat_2               float32
feat_3               float32
feat_4               float32
feat_5               float32
feat_6               float32
feat_7               float32
feat_8               float32
feat_9               float32
feat_10              float32
feat_11              float32
feat_12              float32
feat_13              float32
feat_14              float32
feat_15              float32
feat_16              float32
feat_17              float32
feat_18              float32
feat_19              float32
feat_20              float32
feat_21              float32
feat_22              float32
feat_23              float32
feat_24              float32
feat_25              float32
feat_26              float32
feat_27              float32
feat_28              float32
feat_29              float32
feat_30              float32
feat_31              float32
PD_Label_Combined      int64
dtype: object
     feat_0    feat_1    feat_2    feat_3    feat_4    feat_5    feat_6  \
0  0.087140  0.096083  0.049204 -0.071214  0.214633  0.095384  0.153374
1  0.076432  0.076741  0.077576 -0.068338  0.216998  0.122726  0.159202
2  0.064832  0.118307  0.034137 -0.057597  0.265400  0.071063  0.165341
3 -0.220202  0.304828 -0.259936 -0.065405  0.311552 -0.204893  0.201435
4 -0.223483  0.313236 -0.256013 -0.067937  0.292214 -0.194846  0.215071

     feat_7    feat_8    feat_9  ...   feat_23   feat_24   feat_25   feat_26  \
0  0.188717  0.218071 -0.168180  ...  0.126722 -0.229567  0.175720  0.194382
1  0.180173  0.198234 -0.190945  ...  0.115547 -0.194368  0.155384  0.203362
2  0.232546  0.207809 -0.185457  ...  0.090002 -0.209709  0.162844  0.182451
3 -0.005492  0.216769 -0.117691  ... -0.149213  0.062661 -0.145674  0.007600
4 -0.010638  0.243313 -0.133310  ... -0.137389  0.058514 -0.145171  0.022605

    feat_27   feat_28   feat_29   feat_30   feat_31  PD_Label_Combined
0 -0.003952  0.151453  0.251947 -0.140546 -0.103983                  0
1 -0.026240  0.125245  0.267916 -0.163753 -0.127173                  0
2 -0.014093  0.140906  0.238341 -0.128308 -0.138824                  0
3  0.190504 -0.166660 -0.166704  0.096099 -0.259555                  1
4  0.195833 -0.152784 -0.162052  0.071212 -0.238080                  1

[5 rows x 33 columns]

In [8]:
# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [9]:
import pandas as pd

fused_df_named_int.to_csv('/content/drive//MyDrive/Modality-meg(passive)_par_MIRA-Net_data.csv', index=False)

In [10]:
# ============================================================
# ###8)###
# ENSEMBLE CLASSIFICATION WITH STRATIFIED 10-FOLD CV
# ============================================================

# ------------------ Install Required Packages ------------------

!pip install xgboost lightgbm catboost scikit-learn statsmodels matplotlib seaborn --quiet


# ------------------ Imports ------------------

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.utils.class_weight import compute_class_weight

from sklearn.model_selection import (
    train_test_split,
    StratifiedKFold
)

from sklearn.preprocessing import StandardScaler

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    balanced_accuracy_score,
    matthews_corrcoef,
    confusion_matrix
)

from sklearn.ensemble import (
    VotingClassifier,
    StackingClassifier,
    RandomForestClassifier,
    HistGradientBoostingClassifier
)

from sklearn.linear_model import LogisticRegression

from xgboost import XGBClassifier

from statsmodels.stats.proportion import proportion_confint


# ============================================================
# STEP 1: PREPARE DATA
# ============================================================

X = fused_df_named_int[
    [f'feat_{i}' for i in range(32)]
].copy()

y = fused_df_named_int[
    "PD_Label_Combined"
].copy()


# ------------------ Convert X to numeric ------------------

X = X.apply(
    pd.to_numeric,
    errors='coerce'
)

X.fillna(
    0,
    inplace=True
)


# ============================================================
# STEP 2: CLASS WEIGHTS
# ============================================================

classes = np.unique(y)

class_weights = compute_class_weight(
    class_weight='balanced',
    classes=classes,
    y=y
)

class_weights_dict = {
    int(classes[0]): float(class_weights[0]),
    int(classes[1]): float(class_weights[1])
}

print("\nClass Weights:")
print(class_weights_dict)


# ============================================================
# STEP 3: TRAIN-TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=42
)


print("\nTrain Shape :", X_train.shape)
print("Test Shape  :", X_test.shape)

print("\nTraining Class Distribution:")
print(y_train.value_counts())

print("\nTesting Class Distribution:")
print(y_test.value_counts())


# ============================================================
# STEP 4: HANDLE CLASS IMBALANCE
# ============================================================

cw = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_train),
    y=y_train
)

cw_dict = dict(
    zip(
        np.unique(y_train),
        cw
    )
)

scale_pos_weight = (
    cw[1] / cw[0]
)

print("\nTraining Class Weights:")
print(cw_dict)

print(
    "\nXGBoost scale_pos_weight:",
    scale_pos_weight
)


# ============================================================
# STEP 5: BASE MODEL CREATION FUNCTION
# ============================================================

def create_models():

    # ---------------- XGBoost ----------------

    xgb = XGBClassifier(
        n_estimators=200,
        max_depth=4,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,

        scale_pos_weight=scale_pos_weight,

        eval_metric='logloss',

        random_state=42,
        n_jobs=-1
    )


    # ---------------- Random Forest ----------------

    rf = RandomForestClassifier(
        n_estimators=200,

        class_weight='balanced',

        random_state=42,
        n_jobs=-1
    )


    # ---------------- HistGradientBoosting ----------------

    hgb = HistGradientBoostingClassifier(
        max_iter=200,
        learning_rate=0.05,
        max_leaf_nodes=31,

        class_weight='balanced',

        random_state=42
    )


    return xgb, rf, hgb


# ============================================================
# STEP 6: STRATIFIED 10-FOLD CV
# ============================================================

skf = StratifiedKFold(
    n_splits=10,
    shuffle=True,
    random_state=42
)


# ============================================================
# STEP 7: EVALUATION FUNCTION
# ============================================================

def evaluate_model(model_name):

    # ========================================================
    # CV METRIC STORAGE
    # ========================================================

    cv_accuracy = []
    cv_precision = []
    cv_sensitivity = []
    cv_f1 = []
    cv_auc = []
    cv_balanced_accuracy = []


    # ========================================================
    # 10-FOLD STRATIFIED CROSS-VALIDATION
    # ========================================================

    for fold, (train_idx, val_idx) in enumerate(
        skf.split(X_train, y_train),
        start=1
    ):

        print(
            f"\n{model_name} | Fold {fold}/10"
        )


        # ----------------------------------------------------
        # Split fold
        # ----------------------------------------------------

        X_tr = X_train.iloc[
            train_idx
        ]

        X_val = X_train.iloc[
            val_idx
        ]

        y_tr = y_train.iloc[
            train_idx
        ]

        y_val = y_train.iloc[
            val_idx
        ]


        # ----------------------------------------------------
        # Scaling INSIDE EACH FOLD
        # ----------------------------------------------------

        scaler = StandardScaler()

        X_tr_scaled = scaler.fit_transform(
            X_tr
        )

        X_val_scaled = scaler.transform(
            X_val
        )


        # ----------------------------------------------------
        # Create FRESH models for every fold
        # ----------------------------------------------------

        xgb, rf, hgb = create_models()


        # ----------------------------------------------------
        # Select requested model
        # ----------------------------------------------------

        if model_name == "XGBoost":

            model = xgb


        elif model_name == "Random Forest":

            model = rf


        elif model_name == "HistGradientBoosting":

            model = hgb


        elif model_name == "Voting Fusion":

            model = VotingClassifier(
                estimators=[
                    ('xgb', xgb),
                    ('rf', rf),
                    ('hgb', hgb)
                ],
                voting='soft'
            )


        elif model_name == "Stacking Fusion":

            model = StackingClassifier(
                estimators=[
                    ('xgb', xgb),
                    ('rf', rf),
                    ('hgb', hgb)
                ],

                final_estimator=LogisticRegression(
                    max_iter=1000,
                    class_weight='balanced'
                ),

                passthrough=True,

                cv=5
            )


        else:

            raise ValueError(
                f"Unknown model: {model_name}"
            )


        # ----------------------------------------------------
        # Train fold
        # ----------------------------------------------------

        model.fit(
            X_tr_scaled,
            y_tr
        )


        # ----------------------------------------------------
        # Validation predictions
        # ----------------------------------------------------

        val_preds = model.predict(
            X_val_scaled
        )

        val_probs = model.predict_proba(
            X_val_scaled
        )[:, 1]


        # ----------------------------------------------------
        # Fold metrics
        # ----------------------------------------------------

        fold_accuracy = accuracy_score(
            y_val,
            val_preds
        )

        fold_precision = precision_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_sensitivity = recall_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_f1 = f1_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_auc = roc_auc_score(
            y_val,
            val_probs
        )

        fold_balanced_accuracy = balanced_accuracy_score(
            y_val,
            val_preds
        )


        # ----------------------------------------------------
        # Store fold metrics
        # ----------------------------------------------------

        cv_accuracy.append(
            fold_accuracy
        )

        cv_precision.append(
            fold_precision
        )

        cv_sensitivity.append(
            fold_sensitivity
        )

        cv_f1.append(
            fold_f1
        )

        cv_auc.append(
            fold_auc
        )

        cv_balanced_accuracy.append(
            fold_balanced_accuracy
        )


        # ----------------------------------------------------
        # Print fold result
        # ----------------------------------------------------

        print(
            f"Accuracy            : {fold_accuracy:.4f}"
        )

        print(
            f"Precision           : {fold_precision:.4f}"
        )

        print(
            f"Sensitivity         : {fold_sensitivity:.4f}"
        )

        print(
            f"F1 Score            : {fold_f1:.4f}"
        )

        print(
            f"ROC-AUC             : {fold_auc:.4f}"
        )

        print(
            f"Balanced Accuracy   : "
            f"{fold_balanced_accuracy:.4f}"
        )


    # ========================================================
    # CV MEAN RESULTS
    # ========================================================

    cv_accuracy_mean = np.mean(
        cv_accuracy
    )

    cv_precision_mean = np.mean(
        cv_precision
    )

    cv_sensitivity_mean = np.mean(
        cv_sensitivity
    )

    cv_f1_mean = np.mean(
        cv_f1
    )

    cv_auc_mean = np.mean(
        cv_auc
    )

    cv_balanced_accuracy_mean = np.mean(
        cv_balanced_accuracy
    )


    # ========================================================
    # CROSS-VALIDATION RESULTS
    # ========================================================

    print(
        "\n================================================"
    )

    print(
        f"{model_name} - Cross-Validation (10-fold)"
    )

    print(
        "================================================"
    )

    print(
        f"Accuracy            : "
        f"{cv_accuracy_mean:.4f}"
    )

    print(
        f"Precision           : "
        f"{cv_precision_mean:.4f}"
    )

    print(
        f"Recall/Sensitivity  : "
        f"{cv_sensitivity_mean:.4f}"
    )

    print(
        f"F1 Score            : "
        f"{cv_f1_mean:.4f}"
    )

    print(
        f"ROC-AUC             : "
        f"{cv_auc_mean:.4f}"
    )

    print(
        f"Balanced Accuracy   : "
        f"{cv_balanced_accuracy_mean:.4f}"
    )


    # ========================================================
    # TRAIN FINAL MODEL ON COMPLETE TRAINING SET
    # ========================================================

    final_scaler = StandardScaler()

    X_train_final_scaled = final_scaler.fit_transform(
        X_train
    )

    X_test_final_scaled = final_scaler.transform(
        X_test
    )


    # --------------------------------------------------------
    # Create fresh final models
    # --------------------------------------------------------

    xgb, rf, hgb = create_models()


    if model_name == "XGBoost":

        final_model = xgb


    elif model_name == "Random Forest":

        final_model = rf


    elif model_name == "HistGradientBoosting":

        final_model = hgb


    elif model_name == "Voting Fusion":

        final_model = VotingClassifier(
            estimators=[
                ('xgb', xgb),
                ('rf', rf),
                ('hgb', hgb)
            ],
            voting='soft'
        )


    elif model_name == "Stacking Fusion":

        final_model = StackingClassifier(
            estimators=[
                ('xgb', xgb),
                ('rf', rf),
                ('hgb', hgb)
            ],

            final_estimator=LogisticRegression(
                max_iter=1000,
                class_weight='balanced'
            ),

            passthrough=True,

            cv=5
        )


    # ========================================================
    # FINAL TRAINING
    # ========================================================

    final_model.fit(
        X_train_final_scaled,
        y_train
    )


    # ========================================================
    # TEST PREDICTIONS
    # ========================================================

    test_preds = final_model.predict(
        X_test_final_scaled
    )

    test_probs = final_model.predict_proba(
        X_test_final_scaled
    )[:, 1]


    # ========================================================
    # TEST METRICS
    # ========================================================

    accuracy = accuracy_score(
        y_test,
        test_preds
    )

    precision = precision_score(
        y_test,
        test_preds,
        zero_division=0
    )

    sensitivity = recall_score(
        y_test,
        test_preds,
        zero_division=0
    )

    f1 = f1_score(
        y_test,
        test_preds,
        zero_division=0
    )

    roc_auc = roc_auc_score(
        y_test,
        test_probs
    )

    balanced_accuracy = balanced_accuracy_score(
        y_test,
        test_preds
    )

    mcc = matthews_corrcoef(
        y_test,
        test_preds
    )


    # ========================================================
    # CONFUSION MATRIX
    # ========================================================

    cm = confusion_matrix(
        y_test,
        test_preds,
        labels=[0, 1]
    )

    tn, fp, fn, tp = cm.ravel()


    # ========================================================
    # SENSITIVITY / SPECIFICITY
    # ========================================================

    sensitivity = (
        tp / (tp + fn)
        if (tp + fn) > 0
        else 0
    )

    specificity = (
        tn / (tn + fp)
        if (tn + fp) > 0
        else 0
    )


    # ========================================================
    # 95% CONFIDENCE INTERVALS
    # ========================================================

    # ---------------- Accuracy CI ----------------

    acc_low, acc_high = proportion_confint(
        count=int(round(accuracy * len(y_test))),
        nobs=len(y_test),
        alpha=0.05,
        method='wilson'
    )


    # ---------------- Precision CI ----------------

    precision_low, precision_high = proportion_confint(
        count=tp,
        nobs=(tp + fp),
        alpha=0.05,
        method='wilson'
    ) if (tp + fp) > 0 else (0.0, 0.0)


    # ---------------- Sensitivity CI ----------------

    sensitivity_low, sensitivity_high = proportion_confint(
        count=tp,
        nobs=(tp + fn),
        alpha=0.05,
        method='wilson'
    ) if (tp + fn) > 0 else (0.0, 0.0)


    # ---------------- Specificity CI ----------------

    specificity_low, specificity_high = proportion_confint(
        count=tn,
        nobs=(tn + fp),
        alpha=0.05,
        method='wilson'
    ) if (tn + fp) > 0 else (0.0, 0.0)


    # ========================================================
    # TEST SET PERFORMANCE
    # ========================================================

    print(
        "\n================================================"
    )

    print(
        f"{model_name} - Test Set Performance"
    )

    print(
        "================================================"
    )

    print(
        f"Accuracy            : {accuracy:.4f} "
        f"(95% CI: "
        f"{acc_low:.4f}-{acc_high:.4f})"
    )

    print(
        f"Precision           : {precision:.4f} "
        f"(95% CI: "
        f"{precision_low:.4f}-{precision_high:.4f})"
    )

    print(
        f"Sensitivity         : {sensitivity:.4f} "
        f"(95% CI: "
        f"{sensitivity_low:.4f}-{sensitivity_high:.4f})"
    )

    print(
        f"Specificity         : {specificity:.4f} "
        f"(95% CI: "
        f"{specificity_low:.4f}-{specificity_high:.4f})"
    )

    print(
        f"F1 Score            : {f1:.4f}"
    )

    print(
        f"ROC-AUC             : {roc_auc:.4f}"
    )

    print(
        f"Balanced Accuracy   : "
        f"{balanced_accuracy:.4f}"
    )

    print(
        f"MCC                 : {mcc:.4f}"
    )


    # ========================================================
    # CONFUSION MATRIX
    # ========================================================

    print(
        "\nConfusion Matrix:"
    )

    print(cm)

    print(
        "\nTN :", tn
    )

    print(
        "FP :", fp
    )

    print(
        "FN :", fn
    )

    print(
        "TP :", tp
    )


    # ========================================================
    # STORE RESULTS
    # ========================================================

    result = {

        # ---------------- CV ----------------

        "CV Accuracy":
            cv_accuracy_mean,

        "CV Precision":
            cv_precision_mean,

        "CV Sensitivity":
            cv_sensitivity_mean,

        "CV F1":
            cv_f1_mean,

        "CV ROC-AUC":
            cv_auc_mean,

        "CV Balanced Accuracy":
            cv_balanced_accuracy_mean,


        # ---------------- Test ----------------

        "Accuracy":
            accuracy,

        "Accuracy CI Low":
            acc_low,

        "Accuracy CI High":
            acc_high,


        "Precision":
            precision,

        "Precision CI Low":
            precision_low,

        "Precision CI High":
            precision_high,


        "Sensitivity":
            sensitivity,

        "Sensitivity CI Low":
            sensitivity_low,

        "Sensitivity CI High":
            sensitivity_high,


        "Specificity":
            specificity,

        "Specificity CI Low":
            specificity_low,

        "Specificity CI High":
            specificity_high,


        "F1":
            f1,

        "ROC-AUC":
            roc_auc,

        "Balanced Accuracy":
            balanced_accuracy,

        "MCC":
            mcc,


        # ---------------- Confusion Matrix ----------------

        "TN":
            tn,

        "FP":
            fp,

        "FN":
            fn,

        "TP":
            tp
    }


    return result


# ============================================================
# STEP 8: EVALUATE ALL MODELS
# ============================================================

model_names = [
    "XGBoost",
    "Random Forest",
    "HistGradientBoosting",
    "Voting Fusion",
    "Stacking Fusion"
]


results = {}

for name in model_names:

    print(
        "\n\n################################################"
    )

    print(
        f"Evaluating: {name}"
    )

    print(
        "################################################"
    )

    results[name] = evaluate_model(
        name
    )


# ============================================================
# STEP 9: FINAL RESULTS DATAFRAME
# ============================================================

results_df = pd.DataFrame(
    results
).T


# ============================================================
# STEP 10: ORDER RESULTS
# ============================================================

results_df = results_df[
    [

        # ---------------- CV ----------------

        "CV Accuracy",
        "CV Precision",
        "CV Sensitivity",
        "CV F1",
        "CV ROC-AUC",
        "CV Balanced Accuracy",


        # ---------------- Test ----------------

        "Accuracy",
        "Accuracy CI Low",
        "Accuracy CI High",

        "Precision",
        "Precision CI Low",
        "Precision CI High",

        "Sensitivity",
        "Sensitivity CI Low",
        "Sensitivity CI High",

        "Specificity",
        "Specificity CI Low",
        "Specificity CI High",

        "F1",
        "ROC-AUC",
        "Balanced Accuracy",
        "MCC",

        # ---------------- Confusion Matrix ----------------

        "TN",
        "FP",
        "FN",
        "TP"
    ]
]


# ============================================================
# STEP 11: DISPLAY FINAL RESULTS
# ============================================================

print(
    "\n================================================"
)

print(
    "FINAL MODEL COMPARISON"
)

print(
    "================================================\n"
)


display(
    results_df.sort_values(
        by="F1",
        ascending=False
    )
)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 8.9 MB/s eta 0:00:00

Class Weights:
{0: 0.9769230769230769, 1: 1.0241935483870968}

Train Shape : (101, 32)
Test Shape  : (26, 32)

Training Class Distribution:
PD_Label_Combined
0    52
1    49
Name: count, dtype: int64

Testing Class Distribution:
PD_Label_Combined
1    13
0    13
Name: count, dtype: int64

Training Class Weights:
{np.int64(0): np.float64(0.9711538461538461), np.int64(1): np.float64(1.030612244897959)}

XGBoost scale_pos_weight: 1.0612244897959182


################################################
Evaluating: XGBoost
################################################

XGBoost | Fold 1/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

XGBoost | Fold 2/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

XGBoost | Fold 3/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

XGBoost | Fold 4/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

XGBoost | Fold 5/10
Accuracy            : 0.9000
Precision           : 1.0000
Sensitivity         : 0.8000
F1 Score            : 0.8889
ROC-AUC             : 0.9800
Balanced Accuracy   : 0.9000

XGBoost | Fold 6/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

XGBoost | Fold 7/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

XGBoost | Fold 8/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

XGBoost | Fold 9/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

XGBoost | Fold 10/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

================================================
XGBoost - Cross-Validation (10-fold)
================================================
Accuracy            : 0.9900
Precision           : 1.0000
Recall/Sensitivity  : 0.9800
F1 Score            : 0.9889
ROC-AUC             : 0.9980
Balanced Accuracy   : 0.9900

================================================
XGBoost - Test Set Performance
================================================
Accuracy            : 1.0000 (95% CI: 0.8713-1.0000)
Precision           : 1.0000 (95% CI: 0.7719-1.0000)
Sensitivity         : 1.0000 (95% CI: 0.7719-1.0000)
Specificity         : 1.0000 (95% CI: 0.7719-1.0000)
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000
MCC                 : 1.0000

Confusion Matrix:
[[13  0]
 [ 0 13]]

TN : 13
FP : 0
FN : 0
TP : 13


################################################
Evaluating: Random Forest
################################################

Random Forest | Fold 1/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Random Forest | Fold 2/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Random Forest | Fold 3/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Random Forest | Fold 4/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Random Forest | Fold 5/10
Accuracy            : 0.9000
Precision           : 1.0000
Sensitivity         : 0.8000
F1 Score            : 0.8889
ROC-AUC             : 0.9800
Balanced Accuracy   : 0.9000

Random Forest | Fold 6/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Random Forest | Fold 7/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Random Forest | Fold 8/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Random Forest | Fold 9/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Random Forest | Fold 10/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

================================================
Random Forest - Cross-Validation (10-fold)
================================================
Accuracy            : 0.9900
Precision           : 1.0000
Recall/Sensitivity  : 0.9800
F1 Score            : 0.9889
ROC-AUC             : 0.9980
Balanced Accuracy   : 0.9900

================================================
Random Forest - Test Set Performance
================================================
Accuracy            : 1.0000 (95% CI: 0.8713-1.0000)
Precision           : 1.0000 (95% CI: 0.7719-1.0000)
Sensitivity         : 1.0000 (95% CI: 0.7719-1.0000)
Specificity         : 1.0000 (95% CI: 0.7719-1.0000)
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000
MCC                 : 1.0000

Confusion Matrix:
[[13  0]
 [ 0 13]]

TN : 13
FP : 0
FN : 0
TP : 13


################################################
Evaluating: HistGradientBoosting
################################################

HistGradientBoosting | Fold 1/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

HistGradientBoosting | Fold 2/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

HistGradientBoosting | Fold 3/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

HistGradientBoosting | Fold 4/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

HistGradientBoosting | Fold 5/10
Accuracy            : 0.9000
Precision           : 1.0000
Sensitivity         : 0.8000
F1 Score            : 0.8889
ROC-AUC             : 0.9000
Balanced Accuracy   : 0.9000

HistGradientBoosting | Fold 6/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

HistGradientBoosting | Fold 7/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

HistGradientBoosting | Fold 8/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

HistGradientBoosting | Fold 9/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

HistGradientBoosting | Fold 10/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

================================================
HistGradientBoosting - Cross-Validation (10-fold)
================================================
Accuracy            : 0.9900
Precision           : 1.0000
Recall/Sensitivity  : 0.9800
F1 Score            : 0.9889
ROC-AUC             : 0.9900
Balanced Accuracy   : 0.9900

================================================
HistGradientBoosting - Test Set Performance
================================================
Accuracy            : 1.0000 (95% CI: 0.8713-1.0000)
Precision           : 1.0000 (95% CI: 0.7719-1.0000)
Sensitivity         : 1.0000 (95% CI: 0.7719-1.0000)
Specificity         : 1.0000 (95% CI: 0.7719-1.0000)
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000
MCC                 : 1.0000

Confusion Matrix:
[[13  0]
 [ 0 13]]

TN : 13
FP : 0
FN : 0
TP : 13


################################################
Evaluating: Voting Fusion
################################################

Voting Fusion | Fold 1/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Voting Fusion | Fold 2/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Voting Fusion | Fold 3/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Voting Fusion | Fold 4/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Voting Fusion | Fold 5/10
Accuracy            : 0.9000
Precision           : 1.0000
Sensitivity         : 0.8000
F1 Score            : 0.8889
ROC-AUC             : 0.9800
Balanced Accuracy   : 0.9000

Voting Fusion | Fold 6/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Voting Fusion | Fold 7/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Voting Fusion | Fold 8/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Voting Fusion | Fold 9/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Voting Fusion | Fold 10/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

================================================
Voting Fusion - Cross-Validation (10-fold)
================================================
Accuracy            : 0.9900
Precision           : 1.0000
Recall/Sensitivity  : 0.9800
F1 Score            : 0.9889
ROC-AUC             : 0.9980
Balanced Accuracy   : 0.9900

================================================
Voting Fusion - Test Set Performance
================================================
Accuracy            : 1.0000 (95% CI: 0.8713-1.0000)
Precision           : 1.0000 (95% CI: 0.7719-1.0000)
Sensitivity         : 1.0000 (95% CI: 0.7719-1.0000)
Specificity         : 1.0000 (95% CI: 0.7719-1.0000)
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000
MCC                 : 1.0000

Confusion Matrix:
[[13  0]
 [ 0 13]]

TN : 13
FP : 0
FN : 0
TP : 13


################################################
Evaluating: Stacking Fusion
################################################

Stacking Fusion | Fold 1/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Stacking Fusion | Fold 2/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Stacking Fusion | Fold 3/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Stacking Fusion | Fold 4/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Stacking Fusion | Fold 5/10
Accuracy            : 0.9000
Precision           : 1.0000
Sensitivity         : 0.8000
F1 Score            : 0.8889
ROC-AUC             : 0.9800
Balanced Accuracy   : 0.9000

Stacking Fusion | Fold 6/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Stacking Fusion | Fold 7/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Stacking Fusion | Fold 8/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Stacking Fusion | Fold 9/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Stacking Fusion | Fold 10/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

================================================
Stacking Fusion - Cross-Validation (10-fold)
================================================
Accuracy            : 0.9900
Precision           : 1.0000
Recall/Sensitivity  : 0.9800
F1 Score            : 0.9889
ROC-AUC             : 0.9980
Balanced Accuracy   : 0.9900

================================================
Stacking Fusion - Test Set Performance
================================================
Accuracy            : 1.0000 (95% CI: 0.8713-1.0000)
Precision           : 1.0000 (95% CI: 0.7719-1.0000)
Sensitivity         : 1.0000 (95% CI: 0.7719-1.0000)
Specificity         : 1.0000 (95% CI: 0.7719-1.0000)
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000
MCC                 : 1.0000

Confusion Matrix:
[[13  0]
 [ 0 13]]

TN : 13
FP : 0
FN : 0
TP : 13

================================================
FINAL MODEL COMPARISON
================================================

,CV Accuracy,CV Precision,CV Sensitivity,CV F1,CV ROC-AUC,CV Balanced Accuracy,Accuracy,Accuracy CI Low,Accuracy CI High,Precision,...,Specificity CI Low,Specificity CI High,F1,ROC-AUC,Balanced Accuracy,MCC,TN,FP,FN,TP
XGBoost,0.99,1.0,0.98,0.988889,0.998,0.99,1.0,0.871271,1.0,1.0,...,0.771905,1.0,1.0,1.0,1.0,1.0,13.0,0.0,0.0,13.0
Random Forest,0.99,1.0,0.98,0.988889,0.998,0.99,1.0,0.871271,1.0,1.0,...,0.771905,1.0,1.0,1.0,1.0,1.0,13.0,0.0,0.0,13.0
HistGradientBoosting,0.99,1.0,0.98,0.988889,0.990,0.99,1.0,0.871271,1.0,1.0,...,0.771905,1.0,1.0,1.0,1.0,1.0,13.0,0.0,0.0,13.0
Voting Fusion,0.99,1.0,0.98,0.988889,0.998,0.99,1.0,0.871271,1.0,1.0,...,0.771905,1.0,1.0,1.0,1.0,1.0,13.0,0.0,0.0,13.0
Stacking Fusion,0.99,1.0,0.98,0.988889,0.998,0.99,1.0,0.871271,1.0,1.0,...,0.771905,1.0,1.0,1.0,1.0,1.0,13.0,0.0,0.0,13.0

Without MIRA-Net

In [1]:
# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

final_meg_df = pd.read_csv('/content/drive/MyDrive/final_meg_passive_21_par-lev_final.csv')

print("Loaded data shape:", final_meg_df.shape)
print(final_meg_df.head())

Loaded data shape: (127, 106)
   burst_rate_L_mean  burst_rate_L_std  burst_rate_R_mean  burst_rate_R_std  \
0           4.307989          0.204442           4.411462          0.166274
1           3.640013          0.519092           3.661284          0.572175
2           4.518955          0.174000           4.563599          0.153873
3           4.057439          0.259270           4.177064          0.215284
4           4.025205          0.324785           4.047333          0.306122

   burst_rate_asym  mean_burst_duration_L_mean  mean_burst_duration_L_std  \
0        -0.011867                    0.058159                   0.002800
1        -0.002913                    0.070172                   0.010659
2        -0.004915                    0.055402                   0.002179
3        -0.014527                    0.061874                   0.004100
4        -0.002741                    0.062525                   0.005235

   mean_burst_duration_R_mean  mean_burst_duration_R_std  \
0                    0.056750                   0.002180
1                    0.070130                   0.012065
2                    0.054841                   0.001874
3                    0.060008                   0.003089
4                    0.062123                   0.004726

   mean_burst_duration_asym  ...  spectral_flatness_L_std  \
0                  0.012260  ...                 0.067009
1                  0.000296  ...                 0.054090
2                  0.005089  ...                 0.019396
3                  0.015307  ...                 0.059372
4                  0.003232  ...                 0.035967

   spectral_flatness_R_mean  spectral_flatness_R_std  spectral_flatness_asym  \
0                  0.924763                 0.056414               -0.005716
1                  0.904192                 0.054053               -0.001599
2                  0.970397                 0.019833               -0.000493
3                  0.856283                 0.048577               -0.004424
4                  0.916349                 0.027035               -0.003870

   spectral_slope_L_mean  spectral_slope_L_std  spectral_slope_R_mean  \
0          -3.355146e-13          4.743884e-13          -1.831488e-13
1          -7.294939e-13          8.859464e-13          -6.976051e-13
2          -8.533174e-14          1.089821e-13          -8.562178e-14
3          -8.767126e-13          1.197989e-12          -3.583790e-13
4          -5.900980e-13          7.427183e-13          -2.455170e-13

   spectral_slope_R_std  spectral_slope_asym  Pd_indicator_meg
0          2.524731e-13        -1.523737e-05                 0
1          8.500454e-13        -3.189341e-06                 0
2          1.041308e-13         2.900524e-08                 0
3          4.214089e-13        -5.183976e-05                 1
4          2.848580e-13        -3.446098e-05                 1

[5 rows x 106 columns]

In [3]:
fused_df_named_int = final_meg_df.rename(columns={"Pd_indicator_meg": "PD_Label_Combined"})
fused_df_named_int.head()
fused_df_named_int.shape

(127, 106)

In [4]:
fused_df_named_int.head()

,burst_rate_L_mean,burst_rate_L_std,burst_rate_R_mean,burst_rate_R_std,burst_rate_asym,mean_burst_duration_L_mean,mean_burst_duration_L_std,mean_burst_duration_R_mean,mean_burst_duration_R_std,mean_burst_duration_asym,...,spectral_flatness_L_std,spectral_flatness_R_mean,spectral_flatness_R_std,spectral_flatness_asym,spectral_slope_L_mean,spectral_slope_L_std,spectral_slope_R_mean,spectral_slope_R_std,spectral_slope_asym,PD_Label_Combined
0,4.307989,0.204442,4.411462,0.166274,-0.011867,0.058159,0.002800,0.056750,0.002180,0.012260,...,0.067009,0.924763,0.056414,-0.005716,-3.355146e-13,4.743884e-13,-1.831488e-13,2.524731e-13,-1.523737e-05,0
1,3.640013,0.519092,3.661284,0.572175,-0.002913,0.070172,0.010659,0.070130,0.012065,0.000296,...,0.054090,0.904192,0.054053,-0.001599,-7.294939e-13,8.859464e-13,-6.976051e-13,8.500454e-13,-3.189341e-06,0
2,4.518955,0.174000,4.563599,0.153873,-0.004915,0.055402,0.002179,0.054841,0.001874,0.005089,...,0.019396,0.970397,0.019833,-0.000493,-8.533174e-14,1.089821e-13,-8.562178e-14,1.041308e-13,2.900524e-08,0
3,4.057439,0.259270,4.177064,0.215284,-0.014527,0.061874,0.004100,0.060008,0.003089,0.015307,...,0.059372,0.856283,0.048577,-0.004424,-8.767126e-13,1.197989e-12,-3.583790e-13,4.214089e-13,-5.183976e-05,1
4,4.025205,0.324785,4.047333,0.306122,-0.002741,0.062525,0.005235,0.062123,0.004726,0.003232,...,0.035967,0.916349,0.027035,-0.003870,-5.900980e-13,7.427183e-13,-2.455170e-13,2.848580e-13,-3.446098e-05,1

In [5]:
# ============================================================
# ###8)###
#
# ENSEMBLE CLASSIFICATION WITH STRATIFIED 10-FOLD CV
# ============================================================

# ------------------ Install Required Packages ------------------

!pip install xgboost lightgbm catboost scikit-learn statsmodels matplotlib seaborn --quiet


# ------------------ Imports ------------------

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.utils.class_weight import compute_class_weight

from sklearn.model_selection import (
    train_test_split,
    StratifiedKFold
)

from sklearn.preprocessing import StandardScaler

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    balanced_accuracy_score,
    matthews_corrcoef,
    confusion_matrix
)

from sklearn.ensemble import (
    VotingClassifier,
    StackingClassifier,
    RandomForestClassifier,
    HistGradientBoostingClassifier
)

from sklearn.linear_model import LogisticRegression

from xgboost import XGBClassifier

from statsmodels.stats.proportion import proportion_confint


# ============================================================
# STEP 1: PREPARE DATA
# ============================================================

# All feature columns except the final label column
X = fused_df_named_int.iloc[:, :-1].copy()

# Target
y = fused_df_named_int["PD_Label_Combined"].copy()


# ============================================================
# CONVERT FEATURES TO NUMERIC
# ============================================================

X = X.apply(
    pd.to_numeric,
    errors="coerce"
)


# ============================================================
# CHECK RAW VALUES
# ============================================================

print("\nRaw feature statistics:")
print("Shape :", X.shape)

print(
    "NaN values before cleaning :",
    X.isna().sum().sum()
)

print(
    "Inf values before cleaning :",
    np.isinf(
        X.to_numpy(dtype=np.float64)
    ).sum()
)


# ============================================================
# HANDLE +INF / -INF
# ============================================================

X = X.replace(
    [np.inf, -np.inf],
    np.nan
)


# ============================================================
# COLUMN-WISE MEDIAN IMPUTATION
# ============================================================

col_medians = X.median(
    axis=0,
    skipna=True
)

# If an entire column is NaN,
# replace its median with 0
col_medians = col_medians.fillna(0)

X = X.fillna(
    col_medians
)


# ============================================================
# CLIP EXTREMELY LARGE VALUES
# ============================================================

# Prevent overflow when converting to float32.
#
# Values larger than this are clipped rather than allowed
# to produce inf during float32 conversion.

CLIP_VALUE = 1e10

X = X.clip(
    lower=-CLIP_VALUE,
    upper=CLIP_VALUE
)


# ============================================================
# CONVERT TO FLOAT32 AFTER CLEANING
# ============================================================

X = X.astype(
    np.float32
)


# ============================================================
# FINAL FINITE-VALUE CHECK
# ============================================================

X_array = X.to_numpy()

print("\nAfter cleaning:")

print(
    "NaN values :",
    np.isnan(X_array).sum()
)

print(
    "Inf values :",
    np.isinf(X_array).sum()
)

print(
    "Finite     :",
    np.isfinite(X_array).all()
)

print(
    "Maximum    :",
    np.max(X_array)
)

print(
    "Minimum    :",
    np.min(X_array)
)


# ============================================================
# TARGET CLEANING
# ============================================================

y = pd.to_numeric(
    y,
    errors="coerce"
)

# Make sure target contains no missing values
valid_idx = y.notna()

X = X.loc[valid_idx].reset_index(drop=True)

y = y.loc[valid_idx].astype(
    np.int64
).reset_index(drop=True)


print("\nFinal data:")
print("X shape :", X.shape)
print("y shape :", y.shape)

print("\nClass distribution:")
print(y.value_counts())


# ============================================================
# STEP 2: CLASS WEIGHTS
# ============================================================

classes = np.unique(y)

class_weights = compute_class_weight(
    class_weight="balanced",
    classes=classes,
    y=y
)

class_weights_dict = {
    int(classes[0]): float(class_weights[0]),
    int(classes[1]): float(class_weights[1])
}

print("\nClass Weights:")
print(class_weights_dict)


# ============================================================
# STEP 3: TRAIN-TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    stratify=y,
    random_state=42
)


print("\nTrain Shape :", X_train.shape)
print("Test Shape  :", X_test.shape)


print("\nTraining Class Distribution:")
print(
    y_train.value_counts()
)


print("\nTesting Class Distribution:")
print(
    y_test.value_counts()
)


# ============================================================
# STEP 4: HANDLE CLASS IMBALANCE
# ============================================================

cw = compute_class_weight(
    class_weight="balanced",
    classes=np.unique(y_train),
    y=y_train
)

cw_dict = dict(
    zip(
        np.unique(y_train),
        cw
    )
)

scale_pos_weight = (
    cw_dict[1] / cw_dict[0]
)


print("\nTraining Class Weights:")
print(cw_dict)

print(
    "\nXGBoost scale_pos_weight:",
    scale_pos_weight
)




# ============================================================
# STEP 5: BASE MODEL CREATION FUNCTION
# ============================================================

def create_models():

    # ---------------- XGBoost ----------------

    xgb = XGBClassifier(
        n_estimators=200,
        max_depth=4,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,

        scale_pos_weight=scale_pos_weight,

        eval_metric='logloss',

        random_state=42,
        n_jobs=-1
    )


    # ---------------- Random Forest ----------------

    rf = RandomForestClassifier(
        n_estimators=200,

        class_weight='balanced',

        random_state=42,
        n_jobs=-1
    )


    # ---------------- HistGradientBoosting ----------------

    hgb = HistGradientBoostingClassifier(
        max_iter=200,
        learning_rate=0.05,
        max_leaf_nodes=31,

        class_weight='balanced',

        random_state=42
    )


    return xgb, rf, hgb


# ============================================================
# STEP 6: STRATIFIED 10-FOLD CV
# ============================================================

skf = StratifiedKFold(
    n_splits=10,
    shuffle=True,
    random_state=42
)


# ============================================================
# STEP 7: EVALUATION FUNCTION
# ============================================================

def evaluate_model(model_name):

    # ========================================================
    # CV METRIC STORAGE
    # ========================================================

    cv_accuracy = []
    cv_precision = []
    cv_sensitivity = []
    cv_f1 = []
    cv_auc = []
    cv_balanced_accuracy = []


    # ========================================================
    # 10-FOLD STRATIFIED CROSS-VALIDATION
    # ========================================================

    for fold, (train_idx, val_idx) in enumerate(
        skf.split(X_train, y_train),
        start=1
    ):

        print(
            f"\n{model_name} | Fold {fold}/10"
        )


        # ----------------------------------------------------
        # Split fold
        # ----------------------------------------------------

        X_tr = X_train.iloc[
            train_idx
        ]

        X_val = X_train.iloc[
            val_idx
        ]

        y_tr = y_train.iloc[
            train_idx
        ]

        y_val = y_train.iloc[
            val_idx
        ]


        # ----------------------------------------------------
        # Scaling INSIDE EACH FOLD
        # ----------------------------------------------------

        scaler = StandardScaler()

        X_tr_scaled = scaler.fit_transform(
            X_tr
        )

        X_val_scaled = scaler.transform(
            X_val
        )


        # ----------------------------------------------------
        # Create FRESH models for every fold
        # ----------------------------------------------------

        xgb, rf, hgb = create_models()


        # ----------------------------------------------------
        # Select requested model
        # ----------------------------------------------------

        if model_name == "XGBoost":

            model = xgb


        elif model_name == "Random Forest":

            model = rf


        elif model_name == "HistGradientBoosting":

            model = hgb


        elif model_name == "Voting Fusion":

            model = VotingClassifier(
                estimators=[
                    ('xgb', xgb),
                    ('rf', rf),
                    ('hgb', hgb)
                ],
                voting='soft'
            )


        elif model_name == "Stacking Fusion":

            model = StackingClassifier(
                estimators=[
                    ('xgb', xgb),
                    ('rf', rf),
                    ('hgb', hgb)
                ],

                final_estimator=LogisticRegression(
                    max_iter=1000,
                    class_weight='balanced'
                ),

                passthrough=True,

                cv=5
            )


        else:

            raise ValueError(
                f"Unknown model: {model_name}"
            )


        # ----------------------------------------------------
        # Train fold
        # ----------------------------------------------------

        model.fit(
            X_tr_scaled,
            y_tr
        )


        # ----------------------------------------------------
        # Validation predictions
        # ----------------------------------------------------

        scaler = StandardScaler()
        X_tr = X_tr.astype(np.float64)
        X_val = X_val.astype(np.float64)
        X_tr = np.nan_to_num(
            X_tr,
            nan=0.0,
            posinf=0.0,
            neginf=0.0
        )
        X_val = np.nan_to_num(
            X_val,
            nan=0.0,
            posinf=0.0,
            neginf=0.0
        )
        X_tr_scaled = scaler.fit_transform(X_tr)
        X_val_scaled = scaler.transform(X_val)
        # ----------------------------------------------------
        # Safety check after scaling
        # ----------------------------------------------------
        X_tr_scaled = np.nan_to_num(
            X_tr,
            nan=0.0,
            posinf=0.0,
            neginf=0.0
        )
        X_val = np.nan_to_num(
            X_val,
            nan=0.0,
            posinf=0.0,
            neginf=0.0
        )
        print(
            f"Fold {fold}: "
            f"max|X_val|={np.max(np.abs(X_val_scaled)):.4f}"
        )

        val_preds = model.predict(
             X_val_scaled
        )
        val_probs = model.predict_proba(
            X_val_scaled
        )[:, 1]

        # ----------------------------------------------------
        # Fold metrics
        # ----------------------------------------------------

        fold_accuracy = accuracy_score(
            y_val,
            val_preds
        )

        fold_precision = precision_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_sensitivity = recall_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_f1 = f1_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_auc = roc_auc_score(
            y_val,
            val_probs
        )

        fold_balanced_accuracy = balanced_accuracy_score(
            y_val,
            val_preds
        )


        # ----------------------------------------------------
        # Store fold metrics
        # ----------------------------------------------------

        cv_accuracy.append(
            fold_accuracy
        )

        cv_precision.append(
            fold_precision
        )

        cv_sensitivity.append(
            fold_sensitivity
        )

        cv_f1.append(
            fold_f1
        )

        cv_auc.append(
            fold_auc
        )

        cv_balanced_accuracy.append(
            fold_balanced_accuracy
        )


        # ----------------------------------------------------
        # Print fold result
        # ----------------------------------------------------

        print(
            f"Accuracy            : {fold_accuracy:.4f}"
        )

        print(
            f"Precision           : {fold_precision:.4f}"
        )

        print(
            f"Sensitivity         : {fold_sensitivity:.4f}"
        )

        print(
            f"F1 Score            : {fold_f1:.4f}"
        )

        print(
            f"ROC-AUC             : {fold_auc:.4f}"
        )

        print(
            f"Balanced Accuracy   : "
            f"{fold_balanced_accuracy:.4f}"
        )


    # ========================================================
    # CV MEAN RESULTS
    # ========================================================

    cv_accuracy_mean = np.mean(
        cv_accuracy
    )

    cv_precision_mean = np.mean(
        cv_precision
    )

    cv_sensitivity_mean = np.mean(
        cv_sensitivity
    )

    cv_f1_mean = np.mean(
        cv_f1
    )

    cv_auc_mean = np.mean(
        cv_auc
    )

    cv_balanced_accuracy_mean = np.mean(
        cv_balanced_accuracy
    )


    # ========================================================
    # CROSS-VALIDATION RESULTS
    # ========================================================

    print(
        "\n================================================"
    )

    print(
        f"{model_name} - Cross-Validation (10-fold)"
    )

    print(
        "================================================"
    )

    print(
        f"Accuracy            : "
        f"{cv_accuracy_mean:.4f}"
    )

    print(
        f"Precision           : "
        f"{cv_precision_mean:.4f}"
    )

    print(
        f"Recall/Sensitivity  : "
        f"{cv_sensitivity_mean:.4f}"
    )

    print(
        f"F1 Score            : "
        f"{cv_f1_mean:.4f}"
    )

    print(
        f"ROC-AUC             : "
        f"{cv_auc_mean:.4f}"
    )

    print(
        f"Balanced Accuracy   : "
        f"{cv_balanced_accuracy_mean:.4f}"
    )


    # ========================================================
    # TRAIN FINAL MODEL ON COMPLETE TRAINING SET
    # ========================================================

    final_scaler = StandardScaler()

    X_train_final_scaled = final_scaler.fit_transform(
        X_train
    )

    X_test_final_scaled = final_scaler.transform(
        X_test
    )


    # --------------------------------------------------------
    # Create fresh final models
    # --------------------------------------------------------

    xgb, rf, hgb = create_models()


    if model_name == "XGBoost":

        final_model = xgb


    elif model_name == "Random Forest":

        final_model = rf


    elif model_name == "HistGradientBoosting":

        final_model = hgb


    elif model_name == "Voting Fusion":

        final_model = VotingClassifier(
            estimators=[
                ('xgb', xgb),
                ('rf', rf),
                ('hgb', hgb)
            ],
            voting='soft'
        )


    elif model_name == "Stacking Fusion":

        final_model = StackingClassifier(
            estimators=[
                ('xgb', xgb),
                ('rf', rf),
                ('hgb', hgb)
            ],

            final_estimator=LogisticRegression(
                max_iter=1000,
                class_weight='balanced'
            ),

            passthrough=True,

            cv=5
        )


    # ========================================================
    # FINAL TRAINING
    # ========================================================

    final_model.fit(
        X_train_final_scaled,
        y_train
    )


    # ========================================================
    # TEST PREDICTIONS
    # ========================================================

    test_preds = final_model.predict(
        X_test_final_scaled
    )

    test_probs = final_model.predict_proba(
        X_test_final_scaled
    )[:, 1]


    # ========================================================
    # TEST METRICS
    # ========================================================

    accuracy = accuracy_score(
        y_test,
        test_preds
    )

    precision = precision_score(
        y_test,
        test_preds,
        zero_division=0
    )

    sensitivity = recall_score(
        y_test,
        test_preds,
        zero_division=0
    )

    f1 = f1_score(
        y_test,
        test_preds,
        zero_division=0
    )

    roc_auc = roc_auc_score(
        y_test,
        test_probs
    )

    balanced_accuracy = balanced_accuracy_score(
        y_test,
        test_preds
    )

    mcc = matthews_corrcoef(
        y_test,
        test_preds
    )


    # ========================================================
    # CONFUSION MATRIX
    # ========================================================

    cm = confusion_matrix(
        y_test,
        test_preds,
        labels=[0, 1]
    )

    tn, fp, fn, tp = cm.ravel()


    # ========================================================
    # SENSITIVITY / SPECIFICITY
    # ========================================================

    sensitivity = (
        tp / (tp + fn)
        if (tp + fn) > 0
        else 0
    )

    specificity = (
        tn / (tn + fp)
        if (tn + fp) > 0
        else 0
    )


    # ========================================================
    # 95% CONFIDENCE INTERVALS
    # ========================================================

    # ---------------- Accuracy CI ----------------

    acc_low, acc_high = proportion_confint(
        count=int(round(accuracy * len(y_test))),
        nobs=len(y_test),
        alpha=0.05,
        method='wilson'
    )


    # ---------------- Precision CI ----------------

    precision_low, precision_high = proportion_confint(
        count=tp,
        nobs=(tp + fp),
        alpha=0.05,
        method='wilson'
    ) if (tp + fp) > 0 else (0.0, 0.0)


    # ---------------- Sensitivity CI ----------------

    sensitivity_low, sensitivity_high = proportion_confint(
        count=tp,
        nobs=(tp + fn),
        alpha=0.05,
        method='wilson'
    ) if (tp + fn) > 0 else (0.0, 0.0)


    # ---------------- Specificity CI ----------------

    specificity_low, specificity_high = proportion_confint(
        count=tn,
        nobs=(tn + fp),
        alpha=0.05,
        method='wilson'
    ) if (tn + fp) > 0 else (0.0, 0.0)


    # ========================================================
    # TEST SET PERFORMANCE
    # ========================================================

    print(
        "\n================================================"
    )

    print(
        f"{model_name} - Test Set Performance"
    )

    print(
        "================================================"
    )

    print(
        f"Accuracy            : {accuracy:.4f} "
        f"(95% CI: "
        f"{acc_low:.4f}-{acc_high:.4f})"
    )

    print(
        f"Precision           : {precision:.4f} "
        f"(95% CI: "
        f"{precision_low:.4f}-{precision_high:.4f})"
    )

    print(
        f"Sensitivity         : {sensitivity:.4f} "
        f"(95% CI: "
        f"{sensitivity_low:.4f}-{sensitivity_high:.4f})"
    )

    print(
        f"Specificity         : {specificity:.4f} "
        f"(95% CI: "
        f"{specificity_low:.4f}-{specificity_high:.4f})"
    )

    print(
        f"F1 Score            : {f1:.4f}"
    )

    print(
        f"ROC-AUC             : {roc_auc:.4f}"
    )

    print(
        f"Balanced Accuracy   : "
        f"{balanced_accuracy:.4f}"
    )

    print(
        f"MCC                 : {mcc:.4f}"
    )


    # ========================================================
    # CONFUSION MATRIX
    # ========================================================

    print(
        "\nConfusion Matrix:"
    )

    print(cm)

    print(
        "\nTN :", tn
    )

    print(
        "FP :", fp
    )

    print(
        "FN :", fn
    )

    print(
        "TP :", tp
    )


    # ========================================================
    # STORE RESULTS
    # ========================================================

    result = {

        # ---------------- CV ----------------

        "CV Accuracy":
            cv_accuracy_mean,

        "CV Precision":
            cv_precision_mean,

        "CV Sensitivity":
            cv_sensitivity_mean,

        "CV F1":
            cv_f1_mean,

        "CV ROC-AUC":
            cv_auc_mean,

        "CV Balanced Accuracy":
            cv_balanced_accuracy_mean,


        # ---------------- Test ----------------

        "Accuracy":
            accuracy,

        "Accuracy CI Low":
            acc_low,

        "Accuracy CI High":
            acc_high,


        "Precision":
            precision,

        "Precision CI Low":
            precision_low,

        "Precision CI High":
            precision_high,


        "Sensitivity":
            sensitivity,

        "Sensitivity CI Low":
            sensitivity_low,

        "Sensitivity CI High":
            sensitivity_high,


        "Specificity":
            specificity,

        "Specificity CI Low":
            specificity_low,

        "Specificity CI High":
            specificity_high,


        "F1":
            f1,

        "ROC-AUC":
            roc_auc,

        "Balanced Accuracy":
            balanced_accuracy,

        "MCC":
            mcc,


        # ---------------- Confusion Matrix ----------------

        "TN":
            tn,

        "FP":
            fp,

        "FN":
            fn,

        "TP":
            tp
    }


    return result


# ============================================================
# STEP 8: EVALUATE ALL MODELS
# ============================================================

model_names = [
    "XGBoost",
    "Random Forest",
    "HistGradientBoosting",
    "Voting Fusion",
    "Stacking Fusion"
]


results = {}

for name in model_names:

    print(
        "\n\n################################################"
    )

    print(
        f"Evaluating: {name}"
    )

    print(
        "################################################"
    )

    results[name] = evaluate_model(
        name
    )


# ============================================================
# STEP 9: FINAL RESULTS DATAFRAME
# ============================================================

results_df = pd.DataFrame(
    results
).T


# ============================================================
# STEP 10: ORDER RESULTS
# ============================================================

results_df = results_df[
    [

        # ---------------- CV ----------------

        "CV Accuracy",
        "CV Precision",
        "CV Sensitivity",
        "CV F1",
        "CV ROC-AUC",
        "CV Balanced Accuracy",


        # ---------------- Test ----------------

        "Accuracy",
        "Accuracy CI Low",
        "Accuracy CI High",

        "Precision",
        "Precision CI Low",
        "Precision CI High",

        "Sensitivity",
        "Sensitivity CI Low",
        "Sensitivity CI High",

        "Specificity",
        "Specificity CI Low",
        "Specificity CI High",

        "F1",
        "ROC-AUC",
        "Balanced Accuracy",
        "MCC",

        # ---------------- Confusion Matrix ----------------

        "TN",
        "FP",
        "FN",
        "TP"
    ]
]


# ============================================================
# STEP 11: DISPLAY FINAL RESULTS
# ============================================================

print(
    "\n================================================"
)

print(
    "FINAL MODEL COMPARISON"
)

print(
    "================================================\n"
)


display(
    results_df.sort_values(
        by="F1",
        ascending=False
    )
)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 6.5 MB/s eta 0:00:00

Raw feature statistics:
Shape : (127, 105)
NaN values before cleaning : 0
Inf values before cleaning : 0

After cleaning:
NaN values : 0
Inf values : 0
Finite     : True
Maximum    : 10000000000.0
Minimum    : -2.0894015

Final data:
X shape : (127, 105)
y shape : (127,)

Class distribution:
PD_Label_Combined
0    65
1    62
Name: count, dtype: int64

Class Weights:
{0: 0.9769230769230769, 1: 1.0241935483870968}

Train Shape : (101, 105)
Test Shape  : (26, 105)

Training Class Distribution:
PD_Label_Combined
0    52
1    49
Name: count, dtype: int64

Testing Class Distribution:
PD_Label_Combined
1    13
0    13
Name: count, dtype: int64

Training Class Weights:
{np.int64(0): np.float64(0.9711538461538461), np.int64(1): np.float64(1.030612244897959)}

XGBoost scale_pos_weight: 1.0612244897959182


################################################
Evaluating: XGBoost
################################################

XGBoost | Fold 1/10
Fold 1: max|X_val|=2.4440
Accuracy            : 0.5455
Precision           : 0.5000
Sensitivity         : 0.4000
F1 Score            : 0.4444
ROC-AUC             : 0.8000
Balanced Accuracy   : 0.5333

XGBoost | Fold 2/10
Fold 2: max|X_val|=8.8686
Accuracy            : 0.6000
Precision           : 0.5000
Sensitivity         : 0.7500
F1 Score            : 0.6000
ROC-AUC             : 0.5833
Balanced Accuracy   : 0.6250

XGBoost | Fold 3/10
Fold 3: max|X_val|=6.4304
Accuracy            : 0.7000
Precision           : 0.6250
Sensitivity         : 1.0000
F1 Score            : 0.7692
ROC-AUC             : 0.6400
Balanced Accuracy   : 0.7000

XGBoost | Fold 4/10
Fold 4: max|X_val|=3.8911
Accuracy            : 0.6000
Precision           : 0.6000
Sensitivity         : 0.6000
F1 Score            : 0.6000
ROC-AUC             : 0.7600
Balanced Accuracy   : 0.6000

XGBoost | Fold 5/10
Fold 5: max|X_val|=4.9827
Accuracy            : 0.5000
Precision           : 0.5000
Sensitivity         : 0.4000
F1 Score            : 0.4444
ROC-AUC             : 0.6200
Balanced Accuracy   : 0.5000

XGBoost | Fold 6/10
Fold 6: max|X_val|=2.9173
Accuracy            : 0.6000
Precision           : 0.6000
Sensitivity         : 0.6000
F1 Score            : 0.6000
ROC-AUC             : 0.6400
Balanced Accuracy   : 0.6000

XGBoost | Fold 7/10
Fold 7: max|X_val|=2.6133
Accuracy            : 0.5000
Precision           : 0.5000
Sensitivity         : 0.4000
F1 Score            : 0.4444
ROC-AUC             : 0.4400
Balanced Accuracy   : 0.5000

XGBoost | Fold 8/10
Fold 8: max|X_val|=2.3000
Accuracy            : 0.6000
Precision           : 0.6000
Sensitivity         : 0.6000
F1 Score            : 0.6000
ROC-AUC             : 0.6800
Balanced Accuracy   : 0.6000

XGBoost | Fold 9/10
Fold 9: max|X_val|=57686004411303512015228339620937728.0000
Accuracy            : 0.6000
Precision           : 1.0000
Sensitivity         : 0.2000
F1 Score            : 0.3333
ROC-AUC             : 0.5600
Balanced Accuracy   : 0.6000

XGBoost | Fold 10/10
Fold 10: max|X_val|=11.5442
Accuracy            : 0.8000
Precision           : 0.8000
Sensitivity         : 0.8000
F1 Score            : 0.8000
ROC-AUC             : 0.7600
Balanced Accuracy   : 0.8000

================================================
XGBoost - Cross-Validation (10-fold)
================================================
Accuracy            : 0.6045
Precision           : 0.6225
Recall/Sensitivity  : 0.5750
F1 Score            : 0.5636
ROC-AUC             : 0.6483
Balanced Accuracy   : 0.6058

================================================
XGBoost - Test Set Performance
================================================
Accuracy            : 0.8077 (95% CI: 0.6212-0.9149)
Precision           : 0.9000 (95% CI: 0.5958-0.9821)
Sensitivity         : 0.6923 (95% CI: 0.4237-0.8732)
Specificity         : 0.9231 (95% CI: 0.6669-0.9863)
F1 Score            : 0.7826
ROC-AUC             : 0.8639
Balanced Accuracy   : 0.8077
MCC                 : 0.6325

Confusion Matrix:
[[12  1]
 [ 4  9]]

TN : 12
FP : 1
FN : 4
TP : 9


################################################
Evaluating: Random Forest
################################################

Random Forest | Fold 1/10
Fold 1: max|X_val|=2.4440
Accuracy            : 0.7273
Precision           : 0.6667
Sensitivity         : 0.8000
F1 Score            : 0.7273
ROC-AUC             : 0.8000
Balanced Accuracy   : 0.7333

Random Forest | Fold 2/10
Fold 2: max|X_val|=8.8686
Accuracy            : 0.6000
Precision           : 0.5000
Sensitivity         : 0.7500
F1 Score            : 0.6000
ROC-AUC             : 0.5417
Balanced Accuracy   : 0.6250

Random Forest | Fold 3/10
Fold 3: max|X_val|=6.4304
Accuracy            : 0.7000
Precision           : 0.7500
Sensitivity         : 0.6000
F1 Score            : 0.6667
ROC-AUC             : 0.8400
Balanced Accuracy   : 0.7000

Random Forest | Fold 4/10
Fold 4: max|X_val|=3.8911
Accuracy            : 0.6000
Precision           : 0.6667
Sensitivity         : 0.4000
F1 Score            : 0.5000
ROC-AUC             : 0.5600
Balanced Accuracy   : 0.6000

Random Forest | Fold 5/10
Fold 5: max|X_val|=4.9827
Accuracy            : 0.8000
Precision           : 1.0000
Sensitivity         : 0.6000
F1 Score            : 0.7500
ROC-AUC             : 0.7400
Balanced Accuracy   : 0.8000

Random Forest | Fold 6/10
Fold 6: max|X_val|=2.9173
Accuracy            : 0.6000
Precision           : 0.6000
Sensitivity         : 0.6000
F1 Score            : 0.6000
ROC-AUC             : 0.7200
Balanced Accuracy   : 0.6000

Random Forest | Fold 7/10
Fold 7: max|X_val|=2.6133
Accuracy            : 0.5000
Precision           : 0.5000
Sensitivity         : 0.4000
F1 Score            : 0.4444
ROC-AUC             : 0.6800
Balanced Accuracy   : 0.5000

Random Forest | Fold 8/10
Fold 8: max|X_val|=2.3000
Accuracy            : 0.5000
Precision           : 0.5000
Sensitivity         : 0.4000
F1 Score            : 0.4444
ROC-AUC             : 0.7600
Balanced Accuracy   : 0.5000

Random Forest | Fold 9/10
Fold 9: max|X_val|=57686004411303512015228339620937728.0000
Accuracy            : 0.6000
Precision           : 1.0000
Sensitivity         : 0.2000
F1 Score            : 0.3333
ROC-AUC             : 0.5200
Balanced Accuracy   : 0.6000

Random Forest | Fold 10/10
Fold 10: max|X_val|=11.5442
Accuracy            : 0.7000
Precision           : 0.7500
Sensitivity         : 0.6000
F1 Score            : 0.6667
ROC-AUC             : 0.7200
Balanced Accuracy   : 0.7000

================================================
Random Forest - Cross-Validation (10-fold)
================================================
Accuracy            : 0.6327
Precision           : 0.6933
Recall/Sensitivity  : 0.5350
F1 Score            : 0.5733
ROC-AUC             : 0.6882
Balanced Accuracy   : 0.6358

================================================
Random Forest - Test Set Performance
================================================
Accuracy            : 0.6923 (95% CI: 0.5001-0.8350)
Precision           : 0.7273 (95% CI: 0.4344-0.9025)
Sensitivity         : 0.6154 (95% CI: 0.3552-0.8229)
Specificity         : 0.7692 (95% CI: 0.4974-0.9182)
F1 Score            : 0.6667
ROC-AUC             : 0.8905
Balanced Accuracy   : 0.6923
MCC                 : 0.3892

Confusion Matrix:
[[10  3]
 [ 5  8]]

TN : 10
FP : 3
FN : 5
TP : 8


################################################
Evaluating: HistGradientBoosting
################################################

HistGradientBoosting | Fold 1/10
Fold 1: max|X_val|=2.4440
Accuracy            : 0.5455
Precision           : 0.5000
Sensitivity         : 0.4000
F1 Score            : 0.4444
ROC-AUC             : 0.7000
Balanced Accuracy   : 0.5333

HistGradientBoosting | Fold 2/10
Fold 2: max|X_val|=8.8686
Accuracy            : 0.6000
Precision           : 0.5000
Sensitivity         : 0.7500
F1 Score            : 0.6000
ROC-AUC             : 0.5833
Balanced Accuracy   : 0.6250

HistGradientBoosting | Fold 3/10
Fold 3: max|X_val|=6.4304
Accuracy            : 0.4000
Precision           : 0.4286
Sensitivity         : 0.6000
F1 Score            : 0.5000
ROC-AUC             : 0.4800
Balanced Accuracy   : 0.4000

HistGradientBoosting | Fold 4/10
Fold 4: max|X_val|=3.8911
Accuracy            : 0.5000
Precision           : 0.5000
Sensitivity         : 0.4000
F1 Score            : 0.4444
ROC-AUC             : 0.6800
Balanced Accuracy   : 0.5000

HistGradientBoosting | Fold 5/10
Fold 5: max|X_val|=4.9827
Accuracy            : 0.4000
Precision           : 0.4000
Sensitivity         : 0.4000
F1 Score            : 0.4000
ROC-AUC             : 0.5800
Balanced Accuracy   : 0.4000

HistGradientBoosting | Fold 6/10
Fold 6: max|X_val|=2.9173
Accuracy            : 0.7000
Precision           : 0.7500
Sensitivity         : 0.6000
F1 Score            : 0.6667
ROC-AUC             : 0.5600
Balanced Accuracy   : 0.7000

HistGradientBoosting | Fold 7/10
Fold 7: max|X_val|=2.6133
Accuracy            : 0.5000
Precision           : 0.5000
Sensitivity         : 0.4000
F1 Score            : 0.4444
ROC-AUC             : 0.4800
Balanced Accuracy   : 0.5000

HistGradientBoosting | Fold 8/10
Fold 8: max|X_val|=2.3000
Accuracy            : 0.7000
Precision           : 0.6667
Sensitivity         : 0.8000
F1 Score            : 0.7273
ROC-AUC             : 0.6400
Balanced Accuracy   : 0.7000

HistGradientBoosting | Fold 9/10
Fold 9: max|X_val|=57686004411303512015228339620937728.0000
Accuracy            : 0.6000
Precision           : 1.0000
Sensitivity         : 0.2000
F1 Score            : 0.3333
ROC-AUC             : 0.5200
Balanced Accuracy   : 0.6000

HistGradientBoosting | Fold 10/10
Fold 10: max|X_val|=11.5442
Accuracy            : 0.7000
Precision           : 0.6667
Sensitivity         : 0.8000
F1 Score            : 0.7273
ROC-AUC             : 0.8400
Balanced Accuracy   : 0.7000

================================================
HistGradientBoosting - Cross-Validation (10-fold)
================================================
Accuracy            : 0.5645
Precision           : 0.5912
Recall/Sensitivity  : 0.5350
F1 Score            : 0.5288
ROC-AUC             : 0.6063
Balanced Accuracy   : 0.5658

================================================
HistGradientBoosting - Test Set Performance
================================================
Accuracy            : 0.6923 (95% CI: 0.5001-0.8350)
Precision           : 0.8571 (95% CI: 0.4869-0.9743)
Sensitivity         : 0.4615 (95% CI: 0.2321-0.7086)
Specificity         : 0.9231 (95% CI: 0.6669-0.9863)
F1 Score            : 0.6000
ROC-AUC             : 0.7515
Balanced Accuracy   : 0.6923
MCC                 : 0.4336

Confusion Matrix:
[[12  1]
 [ 7  6]]

TN : 12
FP : 1
FN : 7
TP : 6


################################################
Evaluating: Voting Fusion
################################################

Voting Fusion | Fold 1/10
Fold 1: max|X_val|=2.4440
Accuracy            : 0.5455
Precision           : 0.5000
Sensitivity         : 0.4000
F1 Score            : 0.4444
ROC-AUC             : 0.7667
Balanced Accuracy   : 0.5333

Voting Fusion | Fold 2/10
Fold 2: max|X_val|=8.8686
Accuracy            : 0.6000
Precision           : 0.5000
Sensitivity         : 0.7500
F1 Score            : 0.6000
ROC-AUC             : 0.5833
Balanced Accuracy   : 0.6250

Voting Fusion | Fold 3/10
Fold 3: max|X_val|=6.4304
Accuracy            : 0.6000
Precision           : 0.6000
Sensitivity         : 0.6000
F1 Score            : 0.6000
ROC-AUC             : 0.6800
Balanced Accuracy   : 0.6000

Voting Fusion | Fold 4/10
Fold 4: max|X_val|=3.8911
Accuracy            : 0.6000
Precision           : 0.6000
Sensitivity         : 0.6000
F1 Score            : 0.6000
ROC-AUC             : 0.6800
Balanced Accuracy   : 0.6000

Voting Fusion | Fold 5/10
Fold 5: max|X_val|=4.9827
Accuracy            : 0.5000
Precision           : 0.5000
Sensitivity         : 0.4000
F1 Score            : 0.4444
ROC-AUC             : 0.5800
Balanced Accuracy   : 0.5000

Voting Fusion | Fold 6/10
Fold 6: max|X_val|=2.9173
Accuracy            : 0.7000
Precision           : 0.7500
Sensitivity         : 0.6000
F1 Score            : 0.6667
ROC-AUC             : 0.6800
Balanced Accuracy   : 0.7000

Voting Fusion | Fold 7/10
Fold 7: max|X_val|=2.6133
Accuracy            : 0.5000
Precision           : 0.5000
Sensitivity         : 0.4000
F1 Score            : 0.4444
ROC-AUC             : 0.6000
Balanced Accuracy   : 0.5000

Voting Fusion | Fold 8/10
Fold 8: max|X_val|=2.3000
Accuracy            : 0.6000
Precision           : 0.6000
Sensitivity         : 0.6000
F1 Score            : 0.6000
ROC-AUC             : 0.7200
Balanced Accuracy   : 0.6000

Voting Fusion | Fold 9/10
Fold 9: max|X_val|=57686004411303512015228339620937728.0000
Accuracy            : 0.6000
Precision           : 1.0000
Sensitivity         : 0.2000
F1 Score            : 0.3333
ROC-AUC             : 0.4800
Balanced Accuracy   : 0.6000

Voting Fusion | Fold 10/10
Fold 10: max|X_val|=11.5442
Accuracy            : 0.8000
Precision           : 0.8000
Sensitivity         : 0.8000
F1 Score            : 0.8000
ROC-AUC             : 0.8000
Balanced Accuracy   : 0.8000

================================================
Voting Fusion - Cross-Validation (10-fold)
================================================
Accuracy            : 0.6045
Precision           : 0.6350
Recall/Sensitivity  : 0.5350
F1 Score            : 0.5533
ROC-AUC             : 0.6570
Balanced Accuracy   : 0.6058

================================================
Voting Fusion - Test Set Performance
================================================
Accuracy            : 0.7692 (95% CI: 0.5795-0.8897)
Precision           : 0.8889 (95% CI: 0.5650-0.9801)
Sensitivity         : 0.6154 (95% CI: 0.3552-0.8229)
Specificity         : 0.9231 (95% CI: 0.6669-0.9863)
F1 Score            : 0.7273
ROC-AUC             : 0.8639
Balanced Accuracy   : 0.7692
MCC                 : 0.5659

Confusion Matrix:
[[12  1]
 [ 5  8]]

TN : 12
FP : 1
FN : 5
TP : 8


################################################
Evaluating: Stacking Fusion
################################################

Stacking Fusion | Fold 1/10
Fold 1: max|X_val|=2.4440
Accuracy            : 0.6364
Precision           : 0.5714
Sensitivity         : 0.8000
F1 Score            : 0.6667
ROC-AUC             : 0.9000
Balanced Accuracy   : 0.6500

Stacking Fusion | Fold 2/10
Fold 2: max|X_val|=8.8686
Accuracy            : 0.5000
Precision           : 0.4286
Sensitivity         : 0.7500
F1 Score            : 0.5455
ROC-AUC             : 0.5417
Balanced Accuracy   : 0.5417

Stacking Fusion | Fold 3/10
Fold 3: max|X_val|=6.4304
Accuracy            : 0.2000
Precision           : 0.0000
Sensitivity         : 0.0000
F1 Score            : 0.0000
ROC-AUC             : 0.0000
Balanced Accuracy   : 0.2000

Stacking Fusion | Fold 4/10
Fold 4: max|X_val|=3.8911
Accuracy            : 0.6000
Precision           : 0.6667
Sensitivity         : 0.4000
F1 Score            : 0.5000
ROC-AUC             : 0.5200
Balanced Accuracy   : 0.6000

Stacking Fusion | Fold 5/10
Fold 5: max|X_val|=4.9827
Accuracy            : 0.4000
Precision           : 0.4000
Sensitivity         : 0.4000
F1 Score            : 0.4000
ROC-AUC             : 0.5000
Balanced Accuracy   : 0.4000

Stacking Fusion | Fold 6/10
Fold 6: max|X_val|=2.9173
Accuracy            : 0.5000
Precision           : 0.5000
Sensitivity         : 0.4000
F1 Score            : 0.4444
ROC-AUC             : 0.6400
Balanced Accuracy   : 0.5000

Stacking Fusion | Fold 7/10
Fold 7: max|X_val|=2.6133
Accuracy            : 0.6000
Precision           : 0.6000
Sensitivity         : 0.6000
F1 Score            : 0.6000
ROC-AUC             : 0.7200
Balanced Accuracy   : 0.6000

Stacking Fusion | Fold 8/10
Fold 8: max|X_val|=2.3000
Accuracy            : 0.5000
Precision           : 0.5000
Sensitivity         : 0.6000
F1 Score            : 0.5455
ROC-AUC             : 0.4400
Balanced Accuracy   : 0.5000

Stacking Fusion | Fold 9/10
Fold 9: max|X_val|=57686004411303512015228339620937728.0000
Accuracy            : 0.7000
Precision           : 1.0000
Sensitivity         : 0.4000
F1 Score            : 0.5714
ROC-AUC             : 0.6800
Balanced Accuracy   : 0.7000

Stacking Fusion | Fold 10/10
Fold 10: max|X_val|=11.5442
Accuracy            : 0.6000
Precision           : 0.5714
Sensitivity         : 0.8000
F1 Score            : 0.6667
ROC-AUC             : 0.7200
Balanced Accuracy   : 0.6000

================================================
Stacking Fusion - Cross-Validation (10-fold)
================================================
Accuracy            : 0.5236
Precision           : 0.5238
Recall/Sensitivity  : 0.5150
F1 Score            : 0.4940
ROC-AUC             : 0.5662
Balanced Accuracy   : 0.5292

================================================
Stacking Fusion - Test Set Performance
================================================
Accuracy            : 0.6154 (95% CI: 0.4253-0.7757)
Precision           : 0.6000 (95% CI: 0.3575-0.8018)
Sensitivity         : 0.6923 (95% CI: 0.4237-0.8732)
Specificity         : 0.5385 (95% CI: 0.2914-0.7679)
F1 Score            : 0.6429
ROC-AUC             : 0.6864
Balanced Accuracy   : 0.6154
MCC                 : 0.2335

Confusion Matrix:
[[7 6]
 [4 9]]

TN : 7
FP : 6
FN : 4
TP : 9

================================================
FINAL MODEL COMPARISON
================================================

,CV Accuracy,CV Precision,CV Sensitivity,CV F1,CV ROC-AUC,CV Balanced Accuracy,Accuracy,Accuracy CI Low,Accuracy CI High,Precision,...,Specificity CI Low,Specificity CI High,F1,ROC-AUC,Balanced Accuracy,MCC,TN,FP,FN,TP
XGBoost,0.604545,0.622500,0.575,0.563590,0.648333,0.605833,0.807692,0.621237,0.914929,0.900000,...,0.666860,0.986290,0.782609,0.863905,0.807692,0.632456,12.0,1.0,4.0,9.0
Voting Fusion,0.604545,0.635000,0.535,0.553333,0.657000,0.605833,0.769231,0.579484,0.889662,0.888889,...,0.666860,0.986290,0.727273,0.863905,0.769231,0.565916,12.0,1.0,5.0,8.0
Random Forest,0.632727,0.693333,0.535,0.573283,0.688167,0.635833,0.692308,0.500117,0.834987,0.727273,...,0.497436,0.918205,0.666667,0.890533,0.692308,0.389249,10.0,3.0,5.0,8.0
Stacking Fusion,0.523636,0.523810,0.515,0.494012,0.566167,0.529167,0.615385,0.425349,0.775714,0.600000,...,0.291438,0.767939,0.642857,0.686391,0.615385,0.233550,7.0,6.0,4.0,9.0
HistGradientBoosting,0.564545,0.591190,0.535,0.528788,0.606333,0.565833,0.692308,0.500117,0.834987,0.857143,...,0.666860,0.986290,0.600000,0.751479,0.692308,0.433555,12.0,1.0,7.0,6.0

***Meg Rest task***

With MIRA-Net

In [1]:
# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

final_meg_df = pd.read_csv('/content/drive/MyDrive/final_meg_rest_21_par-lev_final.csv')

print("Loaded data shape:", final_meg_df.shape)
print(final_meg_df.head())

Loaded data shape: (127, 106)
   burst_rate_L_mean  burst_rate_L_std  burst_rate_R_mean  burst_rate_R_std  \
0           4.412365          0.242544           4.486517          0.188241
1           3.828010          0.316999           3.783657          0.297773
2           4.645359          0.130894           4.713304          0.111269
3           4.142208          0.243497           4.183916          0.217601
4           3.923527          0.336133           4.035406          0.306960

   burst_rate_asym  mean_burst_duration_L_mean  mean_burst_duration_L_std  \
0        -0.008333                    0.056832                   0.003237
1         0.005827                    0.065725                   0.005382
2        -0.007260                    0.053844                   0.001551
3        -0.005009                    0.060555                   0.003554
4        -0.014057                    0.064178                   0.005454

   mean_burst_duration_R_mean  mean_burst_duration_R_std  \
0                    0.055801                   0.002407
1                    0.066463                   0.005160
2                    0.053060                   0.001270
3                    0.059908                   0.003106
4                    0.062294                   0.004734

   mean_burst_duration_asym  ...  spectral_flatness_L_std  \
0                  0.009156  ...                 0.091817
1                 -0.005581  ...                 0.068904
2                  0.007325  ...                 0.016316
3                  0.005372  ...                 0.067243
4                  0.014897  ...                 0.033405

   spectral_flatness_R_mean  spectral_flatness_R_std  spectral_flatness_asym  \
0                  0.876225                 0.073953               -0.008900
1                  0.824798                 0.064574                0.010677
2                  0.957087                 0.012624                0.000672
3                  0.822173                 0.054189               -0.005699
4                  0.882392                 0.027770               -0.003794

   spectral_slope_L_mean  spectral_slope_L_std  spectral_slope_R_mean  \
0          -4.309604e-13          6.744059e-13          -2.233093e-13
1          -9.134283e-13          1.131478e-12          -9.278616e-13
2          -6.902417e-14          1.028420e-13          -5.045241e-14
3          -8.858549e-13          1.217447e-12          -3.559801e-13
4          -6.622744e-13          8.793728e-13          -2.369554e-13

   spectral_slope_R_std  spectral_slope_asym  Pd_indicator_meg
0          3.432532e-13            -0.000021                 0
1          1.090616e-12             0.000001                 0
2          6.137480e-14            -0.000002                 0
3          4.306339e-13            -0.000053                 1
4          2.665908e-13            -0.000043                 1

[5 rows x 106 columns]

In [4]:
# ============================================================
#     SIMPLE + STABLE DANN + SCL + MLP CLASSIFIER
#     CROSS-MODAL + CROSS-PARTICIPANT ANALYSIS
# ============================================================

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from torch.autograd import Function
import torch.nn.functional as F

import numpy as np

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# ============================================================
# LOAD DATA
# ============================================================

# First 7 columns -> Features
# Last column     -> PD / HC labels


# ============================================================
# MEG FEATURES AND LABELS
# ============================================================

# All columns except the last one are MEG features
X_meg = final_meg_df.iloc[:, :-1].copy()

# Convert features to numeric
X_meg = X_meg.apply(
    pd.to_numeric,
    errors="coerce"
)

# Replace +inf and -inf with NaN
X_meg = X_meg.replace(
    [np.inf, -np.inf],
    np.nan
)

# ------------------------------------------------------------
# Check invalid values
# ------------------------------------------------------------

print(
    "NaN values before cleaning:",
    X_meg.isna().sum().sum()
)

print(
    "Infinite values before cleaning:",
    np.isinf(
        X_meg.select_dtypes(include=np.number)
    ).sum().sum()
)

# ------------------------------------------------------------
# Replace NaN with column median
# ------------------------------------------------------------

X_meg = X_meg.fillna(
    X_meg.median(numeric_only=True)
)

# Any remaining NaN -> 0
X_meg = X_meg.fillna(0)

# Convert to float64 to avoid float32 overflow
X_meg = X_meg.values.astype(np.float64)

# Labels
y_meg = final_meg_df.iloc[:, -1].values.astype(np.int64)

# ============================================================
# FINAL CHECK BEFORE STANDARDIZATION
# ============================================================

print(
    "All MEG values finite:",
    np.isfinite(X_meg).all()
)

print(
    "Maximum absolute MEG value:",
    np.max(np.abs(X_meg))
)

# ============================================================
# STANDARDIZATION
# ============================================================

scaler_meg = StandardScaler()

X_meg = scaler_meg.fit_transform(
    X_meg
)

# ============================================================
# FINAL CHECK AFTER STANDARDIZATION
# ============================================================

print(
    "All standardized values finite:",
    np.isfinite(X_meg).all()
)

print(
    "Standardized MEG shape:",
    X_meg.shape
)

# ============================================================
# DOMAIN LABELS
# ============================================================

# 0 -> Acoustic
# 1 -> MEG

domain_meg = np.ones(
    len(X_meg)
)

# ============================================================
# COMBINE
# ============================================================

X_all = np.vstack([

    X_meg
]).astype(np.float32)

task_labels = np.hstack([

    y_meg
]).astype(np.int64)

domain_labels = np.hstack([

    domain_meg
]).astype(np.int64)

# ============================================================
# TENSORS
# ============================================================

X_all_tensor = torch.tensor(
    X_all
).float().to(device)

task_labels_tensor = torch.tensor(
    task_labels
).long().to(device)

domain_labels_tensor = torch.tensor(
    domain_labels
).long().to(device)

# ============================================================
# GRADIENT REVERSAL
# ============================================================

class GradReverse(Function):

    @staticmethod
    def forward(ctx, x, lambd):

        ctx.lambd = lambd

        return x.view_as(x)

    @staticmethod
    def backward(ctx, grad_output):

        return -ctx.lambd * grad_output, None

def grad_reverse(x, lambd):

    return GradReverse.apply(x, lambd)

# ============================================================
# SIMPLE RESIDUAL BLOCK
# ============================================================

class ResidualBlock(nn.Module):

    def __init__(self, dim):

        super().__init__()

        self.block = nn.Sequential(

            nn.Linear(dim, dim),
            nn.ReLU(),

            nn.Linear(dim, dim)
        )

    def forward(self, x):

        return F.relu(
            self.block(x) + x
        )

# ============================================================
# DANN + SCL MODEL
# ============================================================

class DANNContrastive(nn.Module):

    def __init__(self, input_dim, latent_dim=32):

        super().__init__()

        # ====================================================
        # SIMPLE ENCODER
        # ====================================================

        self.encoder = nn.Sequential(

            nn.Linear(input_dim, 128),
            nn.ReLU(),

            ResidualBlock(128),

            nn.Linear(128, 64),
            nn.ReLU(),

            nn.Dropout(0.1),

            nn.Linear(64, latent_dim)
        )

        # ====================================================
        # TASK HEAD
        # ====================================================

        self.task_head = nn.Sequential(

            nn.Linear(latent_dim, 32),
            nn.ReLU(),

            nn.Dropout(0.2),

            nn.Linear(32, 2)
        )

        # ====================================================
        # DOMAIN HEAD
        # ====================================================

        self.domain_head = nn.Sequential(

            nn.Linear(latent_dim, 16),
            nn.ReLU(),

            nn.Linear(16, 2)
        )

    def forward(self, x, lambd=1.0):

        z = self.encoder(x)

        # L2 NORMALIZATION

        z_norm = F.normalize(
            z,
            p=2,
            dim=1
        )

        # DANN

        rev_z = grad_reverse(
            z_norm,
            lambd
        )

        task_out = self.task_head(z_norm)

        domain_out = self.domain_head(rev_z)

        return task_out, domain_out, z_norm

# ============================================================
# SUPERVISED CONTRASTIVE LOSS
# ============================================================

class SupConLoss(nn.Module):

    def __init__(self, temperature=0.07):

        super().__init__()

        self.temperature = temperature

    def forward(self, features, labels):

        device = features.device

        labels = labels.contiguous().view(-1, 1)

        mask = torch.eq(
            labels,
            labels.T
        ).float().to(device)

        similarity = torch.matmul(
            features,
            features.T
        ) / self.temperature

        logits_max, _ = torch.max(
            similarity,
            dim=1,
            keepdim=True
        )

        logits = similarity - logits_max.detach()

        logits_mask = torch.ones_like(mask) - torch.eye(
            mask.shape[0]
        ).to(device)

        mask = mask * logits_mask

        exp_logits = torch.exp(logits) * logits_mask

        log_prob = logits - torch.log(
            exp_logits.sum(1, keepdim=True) + 1e-8
        )

        mean_log_prob_pos = (
            mask * log_prob
        ).sum(1) / (mask.sum(1) + 1e-8)

        loss = -mean_log_prob_pos.mean()

        return loss

# ============================================================
# DATA LOADER
# ============================================================

dataset = TensorDataset(
    X_all_tensor,
    task_labels_tensor,
    domain_labels_tensor
)

loader = DataLoader(
    dataset,
    batch_size=128,
    shuffle=True
)

# ============================================================
# MODEL
# ============================================================

model = DANNContrastive(
    input_dim=X_all.shape[1],
    latent_dim=32
).to(device)

# ============================================================
# OPTIMIZER
# ============================================================

optimizer = optim.Adam(
    model.parameters(),
    lr=1e-3,
    weight_decay=1e-4
)

# ============================================================
# LOSSES
# ============================================================

task_loss_fn = nn.CrossEntropyLoss()

domain_loss_fn = nn.CrossEntropyLoss()

contrastive_loss_fn = SupConLoss(
    temperature=0.07
)

epochs = 120

print("\nTraining Started...\n")

# ============================================================
# TRAINING
# ============================================================

for epoch in range(epochs):

    model.train()

    total_correct = 0
    total_samples = 0

    # ========================================================
    # WEAKER DANN
    # ========================================================

    p = min(epoch / 50.0, 1.0)

    lambd = 0.25 * (
        2 / (1 + np.exp(-10 * p)) - 1
    )

    for xb, y_task, y_dom in loader:

        optimizer.zero_grad()

        task_out, dom_out, z = model(
            xb,
            lambd
        )

        # ====================================================
        # LOSSES
        # ====================================================

        loss_task = task_loss_fn(
            task_out,
            y_task
        )

        loss_domain = domain_loss_fn(
            dom_out,
            y_dom
        )

        loss_contrastive = contrastive_loss_fn(
            z,
            y_task
        )

        # ====================================================
        # FINAL LOSS
        # ====================================================

        loss = (
            3.0 * loss_task +
            0.25 * loss_domain +
            0.55 * loss_contrastive
        )

        loss.backward()

        optimizer.step()

        preds = task_out.argmax(1)

        total_correct += (
            preds == y_task
        ).sum().item()

        total_samples += len(y_task)

    acc = total_correct / total_samples

    print(
        f"Epoch {epoch+1}/{epochs} "
        f"| λ={lambd:.3f} "
        f"| Acc={acc:.4f}"
    )

# ============================================================
# EXTRACT LATENT FEATURES
# ============================================================

model.eval()

with torch.no_grad():

    fused_meg_32D = model(
        torch.tensor(X_meg).float().to(device),
        0
    )[2].cpu().numpy()

# ============================================================
# COMBINE LATENTS
# ============================================================

X_fused = np.vstack([

    fused_meg_32D
])

y_fused = np.hstack([

    y_meg
])

# ============================================================
# SIMPLE MLP CLASSIFIER
# ============================================================

class FinalMLP(nn.Module):

    def __init__(self, input_dim=32):

        super().__init__()

        self.net = nn.Sequential(

            nn.Linear(input_dim, 64),
            nn.ReLU(),

            nn.Dropout(0.2),

            nn.Linear(64, 32),
            nn.ReLU(),

            nn.Linear(32, 2)
        )

    def forward(self, x):

        return self.net(x)

# ============================================================
# CROSS PARTICIPANT EVALUATION
# ============================================================

print("\n======================================")
print(" CROSS PARTICIPANT ANALYSIS")
print("======================================\n")

skf = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

accs = []
precs = []
recs = []
f1s = []
aucs = []

fold = 1

for train_idx, test_idx in skf.split(X_fused, y_fused):

    X_train = torch.tensor(
        X_fused[train_idx]
    ).float().to(device)

    X_test = torch.tensor(
        X_fused[test_idx]
    ).float().to(device)

    y_train = torch.tensor(
        y_fused[train_idx]
    ).long().to(device)

    y_test = y_fused[test_idx]

    clf = FinalMLP().to(device)

    optimizer_clf = optim.Adam(
        clf.parameters(),
        lr=1e-3
    )

    criterion = nn.CrossEntropyLoss()

    # ========================================================
    # TRAIN MLP
    # ========================================================

    clf.train()

    for epoch in range(80):

        optimizer_clf.zero_grad()

        outputs = clf(X_train)

        loss = criterion(
            outputs,
            y_train
        )

        loss.backward()

        optimizer_clf.step()

    # ========================================================
    # TEST
    # ========================================================

    clf.eval()

    with torch.no_grad():

        outputs = clf(X_test)

        probs = F.softmax(
            outputs,
            dim=1
        )[:, 1].cpu().numpy()

        preds = outputs.argmax(1).cpu().numpy()

    acc = accuracy_score(y_test, preds)

    prec = precision_score(y_test, preds)

    rec = recall_score(y_test, preds)

    f1 = f1_score(y_test, preds)

    auc = roc_auc_score(y_test, probs)

    accs.append(acc)
    precs.append(prec)
    recs.append(rec)
    f1s.append(f1)
    aucs.append(auc)

    print(f"Fold {fold}")

    print(f"Accuracy  : {acc:.4f}")
    print(f"Precision : {prec:.4f}")
    print(f"Recall    : {rec:.4f}")
    print(f"F1-Score  : {f1:.4f}")
    print(f"AUC       : {auc:.4f}")

    print()

    fold += 1

# ============================================================
# FINAL RESULTS
# ============================================================

print("\n======================================")
print(" FINAL RESULTS")
print("======================================\n")

print(f"Mean Accuracy  : {np.mean(accs)*100:.2f}%")
print(f"Mean Precision : {np.mean(precs)*100:.2f}%")
print(f"Mean Recall    : {np.mean(recs)*100:.2f}%")
print(f"Mean F1-Score  : {np.mean(f1s)*100:.2f}%")
print(f"Mean AUC       : {np.mean(aucs)*100:.2f}%")

print("\n======================================")
print(" LATENT SHAPES")
print("======================================\n")


print("MEG      :", fused_meg_32D.shape)

NaN values before cleaning: 0
Infinite values before cleaning: 0
All MEG values finite: True
Maximum absolute MEG value: 3.31844403349297e+54
All standardized values finite: True
Standardized MEG shape: (127, 105)

Training Started...

Epoch 1/120 | λ=0.000 | Acc=0.4882
Epoch 2/120 | λ=0.025 | Acc=0.5276
Epoch 3/120 | λ=0.049 | Acc=0.5118
Epoch 4/120 | λ=0.073 | Acc=0.5276
Epoch 5/120 | λ=0.095 | Acc=0.4882
Epoch 6/120 | λ=0.116 | Acc=0.5039
Epoch 7/120 | λ=0.134 | Acc=0.5354
Epoch 8/120 | λ=0.151 | Acc=0.5354
Epoch 9/120 | λ=0.166 | Acc=0.5748
Epoch 10/120 | λ=0.179 | Acc=0.5906
Epoch 11/120 | λ=0.190 | Acc=0.5827
Epoch 12/120 | λ=0.200 | Acc=0.5276
Epoch 13/120 | λ=0.208 | Acc=0.5748
Epoch 14/120 | λ=0.215 | Acc=0.5197
Epoch 15/120 | λ=0.221 | Acc=0.5906
Epoch 16/120 | λ=0.226 | Acc=0.6142
Epoch 17/120 | λ=0.230 | Acc=0.5591
Epoch 18/120 | λ=0.234 | Acc=0.5748
Epoch 19/120 | λ=0.237 | Acc=0.6142
Epoch 20/120 | λ=0.239 | Acc=0.6535
Epoch 21/120 | λ=0.241 | Acc=0.6457
Epoch 22/120 | λ=0.243 | Acc=0.7165
Epoch 23/120 | λ=0.244 | Acc=0.6535
Epoch 24/120 | λ=0.245 | Acc=0.7008
Epoch 25/120 | λ=0.246 | Acc=0.7087
Epoch 26/120 | λ=0.247 | Acc=0.7323
Epoch 27/120 | λ=0.247 | Acc=0.7638
Epoch 28/120 | λ=0.248 | Acc=0.8110
Epoch 29/120 | λ=0.248 | Acc=0.8189
Epoch 30/120 | λ=0.248 | Acc=0.8189
Epoch 31/120 | λ=0.249 | Acc=0.8583
Epoch 32/120 | λ=0.249 | Acc=0.8504
Epoch 33/120 | λ=0.249 | Acc=0.8976
Epoch 34/120 | λ=0.249 | Acc=0.9134
Epoch 35/120 | λ=0.249 | Acc=0.9449
Epoch 36/120 | λ=0.250 | Acc=0.9370
Epoch 37/120 | λ=0.250 | Acc=0.9528
Epoch 38/120 | λ=0.250 | Acc=0.9606
Epoch 39/120 | λ=0.250 | Acc=0.9764
Epoch 40/120 | λ=0.250 | Acc=0.9764
Epoch 41/120 | λ=0.250 | Acc=0.9921
Epoch 42/120 | λ=0.250 | Acc=0.9921
Epoch 43/120 | λ=0.250 | Acc=0.9921
Epoch 44/120 | λ=0.250 | Acc=0.9843
Epoch 45/120 | λ=0.250 | Acc=0.9921
Epoch 46/120 | λ=0.250 | Acc=0.9921
Epoch 47/120 | λ=0.250 | Acc=0.9921
Epoch 48/120 | λ=0.250 | Acc=0.9921
Epoch 49/120 | λ=0.250 | Acc=0.9921
Epoch 50/120 | λ=0.250 | Acc=0.9921
Epoch 51/120 | λ=0.250 | Acc=0.9921
Epoch 52/120 | λ=0.250 | Acc=0.9921
Epoch 53/120 | λ=0.250 | Acc=0.9921
Epoch 54/120 | λ=0.250 | Acc=0.9921
Epoch 55/120 | λ=0.250 | Acc=0.9921
Epoch 56/120 | λ=0.250 | Acc=0.9921
Epoch 57/120 | λ=0.250 | Acc=0.9921
Epoch 58/120 | λ=0.250 | Acc=0.9921
Epoch 59/120 | λ=0.250 | Acc=0.9921
Epoch 60/120 | λ=0.250 | Acc=0.9921
Epoch 61/120 | λ=0.250 | Acc=0.9921
Epoch 62/120 | λ=0.250 | Acc=0.9921
Epoch 63/120 | λ=0.250 | Acc=0.9921
Epoch 64/120 | λ=0.250 | Acc=0.9921
Epoch 65/120 | λ=0.250 | Acc=0.9921
Epoch 66/120 | λ=0.250 | Acc=0.9921
Epoch 67/120 | λ=0.250 | Acc=0.9921
Epoch 68/120 | λ=0.250 | Acc=0.9921
Epoch 69/120 | λ=0.250 | Acc=0.9921
Epoch 70/120 | λ=0.250 | Acc=0.9921
Epoch 71/120 | λ=0.250 | Acc=0.9921
Epoch 72/120 | λ=0.250 | Acc=0.9921
Epoch 73/120 | λ=0.250 | Acc=0.9921
Epoch 74/120 | λ=0.250 | Acc=0.9921
Epoch 75/120 | λ=0.250 | Acc=0.9921
Epoch 76/120 | λ=0.250 | Acc=0.9921
Epoch 77/120 | λ=0.250 | Acc=0.9921
Epoch 78/120 | λ=0.250 | Acc=0.9921
Epoch 79/120 | λ=0.250 | Acc=0.9921
Epoch 80/120 | λ=0.250 | Acc=0.9921
Epoch 81/120 | λ=0.250 | Acc=0.9921
Epoch 82/120 | λ=0.250 | Acc=0.9921
Epoch 83/120 | λ=0.250 | Acc=0.9921
Epoch 84/120 | λ=0.250 | Acc=0.9921
Epoch 85/120 | λ=0.250 | Acc=0.9921
Epoch 86/120 | λ=0.250 | Acc=0.9921
Epoch 87/120 | λ=0.250 | Acc=0.9921
Epoch 88/120 | λ=0.250 | Acc=0.9921
Epoch 89/120 | λ=0.250 | Acc=0.9921
Epoch 90/120 | λ=0.250 | Acc=0.9921
Epoch 91/120 | λ=0.250 | Acc=0.9921
Epoch 92/120 | λ=0.250 | Acc=0.9921
Epoch 93/120 | λ=0.250 | Acc=0.9921
Epoch 94/120 | λ=0.250 | Acc=0.9921
Epoch 95/120 | λ=0.250 | Acc=0.9921
Epoch 96/120 | λ=0.250 | Acc=0.9921
Epoch 97/120 | λ=0.250 | Acc=0.9921
Epoch 98/120 | λ=0.250 | Acc=0.9921
Epoch 99/120 | λ=0.250 | Acc=0.9843
Epoch 100/120 | λ=0.250 | Acc=0.9921
Epoch 101/120 | λ=0.250 | Acc=0.9921
Epoch 102/120 | λ=0.250 | Acc=0.9921
Epoch 103/120 | λ=0.250 | Acc=0.9921
Epoch 104/120 | λ=0.250 | Acc=0.9921
Epoch 105/120 | λ=0.250 | Acc=0.9921
Epoch 106/120 | λ=0.250 | Acc=0.9921
Epoch 107/120 | λ=0.250 | Acc=0.9921
Epoch 108/120 | λ=0.250 | Acc=0.9921
Epoch 109/120 | λ=0.250 | Acc=0.9921
Epoch 110/120 | λ=0.250 | Acc=0.9921
Epoch 111/120 | λ=0.250 | Acc=0.9921
Epoch 112/120 | λ=0.250 | Acc=0.9921
Epoch 113/120 | λ=0.250 | Acc=0.9921
Epoch 114/120 | λ=0.250 | Acc=0.9921
Epoch 115/120 | λ=0.250 | Acc=0.9921
Epoch 116/120 | λ=0.250 | Acc=0.9921
Epoch 117/120 | λ=0.250 | Acc=0.9921
Epoch 118/120 | λ=0.250 | Acc=0.9921
Epoch 119/120 | λ=0.250 | Acc=0.9921
Epoch 120/120 | λ=0.250 | Acc=0.9921

======================================
 CROSS PARTICIPANT ANALYSIS
======================================

Fold 1
Accuracy  : 1.0000
Precision : 1.0000
Recall    : 1.0000
F1-Score  : 1.0000
AUC       : 1.0000

Fold 2
Accuracy  : 1.0000
Precision : 1.0000
Recall    : 1.0000
F1-Score  : 1.0000
AUC       : 1.0000

Fold 3
Accuracy  : 1.0000
Precision : 1.0000
Recall    : 1.0000
F1-Score  : 1.0000
AUC       : 1.0000

Fold 4
Accuracy  : 1.0000
Precision : 1.0000
Recall    : 1.0000
F1-Score  : 1.0000
AUC       : 1.0000

Fold 5
Accuracy  : 0.9600
Precision : 1.0000
Recall    : 0.9167
F1-Score  : 0.9565
AUC       : 1.0000


======================================
 FINAL RESULTS
======================================

Mean Accuracy  : 99.20%
Mean Precision : 100.00%
Mean Recall    : 98.33%
Mean F1-Score  : 99.13%
Mean AUC       : 100.00%

======================================
 LATENT SHAPES
======================================

MEG      : (127, 32)

In [5]:
import torch

# Assuming fused_acoustic_32D and fused_meg_32D are numpy arrays of shape (7350, 32)

# Step 1: Convert numpy arrays to torch tensors (float32)

fused_meg_tensor = torch.from_numpy(fused_meg_32D).float()

# Step 2: Concatenate row-wise (along dim=0)
fused_output_tensor = torch.cat([fused_meg_tensor], dim=0)  # Shape: (14700, 32)

# Step 3: Print shape and dtype
print(fused_output_tensor.shape)  # torch.Size([14700, 32])
print(fused_output_tensor.dtype)  # torch.float32

torch.Size([127, 32])
torch.float32

In [6]:
import torch
import numpy as np

# ------------------------
# Step 1: Extract targets correctly
# ------------------------

# Acoustic target from df_acoustic_top7 (last column)


# MEG target from final_meg_df (last column)
y_meg = final_meg_df.iloc[:, -1].values.astype(np.int32)           # (7350,)

# Convert to tensors (reshape to column)
 # (7350, 1)
meg_target_tensor      = torch.tensor(y_meg).long().reshape(-1, 1)        # (7350, 1)

# ------------------------
# Step 2: Convert 32D latent features to tensors
# ------------------------

# (7350, 32)
fused_meg_tensor      = torch.from_numpy(fused_meg_32D).float()       # (7350, 32)

# ------------------------
# Step 3: Attach target columns
# ------------------------

# Concatenate latent features with target

meg_full      = torch.cat([fused_meg_tensor,      meg_target_tensor.float()],      dim=1)  # (7350, 65)

# ------------------------
# Step 4: Concatenate both datasets
# ------------------------

fused_df = torch.cat([meg_full], dim=0)  # (14700, 65)

# ------------------------
# Step 5: Separate features and labels for PyTorch
# ------------------------

X = fused_df[:, :-1].float()   # Features (32D) -> float32
y = fused_df[:, -1].long()     # Target -> int32

# ------------------------
# Step 6: Print shapes and dtypes
# ------------------------

print(f"Features shape: {X.shape}, dtype: {X.dtype}")  # (14700, 32), float32
print(f"Labels shape: {y.shape}, dtype: {y.dtype}")    # (14700,), int32

Features shape: torch.Size([127, 32]), dtype: torch.float32
Labels shape: torch.Size([127]), dtype: torch.int64

In [7]:
import torch
import pandas as pd

# fused_df shape = (14700, 33)

# Step 6: Convert fused tensor to numpy
fused_df_np = fused_df.numpy()

# Step 7: Create correct column names for 32 latent features + 1 label
feature_names = [f"feat_{i}" for i in range(32)]
feature_names.append("PD_Label_Combined")

# Step 8: Convert to DataFrame
fused_df_named = pd.DataFrame(fused_df_np, columns=feature_names)

# Step 9: Verify
print(fused_df_named.shape)
print(fused_df_named.head())
print(fused_df_named.tail())

(127, 33)
     feat_0    feat_1    feat_2    feat_3    feat_4    feat_5    feat_6  \
0  0.127717  0.179660  0.263688  0.151719  0.219084  0.125436  0.025157
1  0.096788  0.201059  0.275873  0.157291  0.214269  0.133495  0.004797
2  0.101601  0.187792  0.258715  0.144729  0.236691  0.128639  0.018097
3 -0.214877  0.267193 -0.074181 -0.160961  0.060650 -0.186432 -0.298644
4 -0.199068  0.263451 -0.074142 -0.149610  0.073712 -0.188132 -0.306001

     feat_7    feat_8    feat_9  ...   feat_23   feat_24   feat_25   feat_26  \
0 -0.202092  0.106707 -0.043072  ... -0.178620  0.205491  0.033113  0.209716
1 -0.201422  0.102947 -0.036616  ... -0.188519  0.217027  0.045991  0.214624
2 -0.195032  0.066789 -0.042611  ... -0.155815  0.229582  0.030754  0.184425
3 -0.339814 -0.102450 -0.138319  ... -0.248103 -0.052360 -0.202328 -0.099042
4 -0.342676 -0.099565 -0.134739  ... -0.263244 -0.038188 -0.193859 -0.091420

    feat_27   feat_28   feat_29   feat_30   feat_31  PD_Label_Combined
0 -0.123894 -0.292267 -0.270605 -0.151716  0.280475                0.0
1 -0.090419 -0.284295 -0.258292 -0.150794  0.298372                0.0
2 -0.104199 -0.296371 -0.266898 -0.130868  0.321311                0.0
3  0.145333 -0.188573  0.115622  0.122745  0.147212                1.0
4  0.142412 -0.205968  0.098411  0.122434  0.140329                1.0

[5 rows x 33 columns]
       feat_0    feat_1    feat_2    feat_3    feat_4    feat_5    feat_6  \
122  0.107411  0.203943  0.283775  0.145250  0.222133  0.132399  0.005102
123 -0.207759  0.291145 -0.060603 -0.177667  0.053579 -0.182765 -0.284350
124  0.124861  0.163668  0.263958  0.156140  0.229061  0.138163  0.028406
125  0.109226  0.185170  0.265566  0.148422  0.234955  0.132626  0.003541
126 -0.200639  0.264900 -0.073270 -0.160980  0.076284 -0.175290 -0.300658

       feat_7    feat_8    feat_9  ...   feat_23   feat_24   feat_25  \
122 -0.199996  0.107430 -0.044798  ... -0.181005  0.214904  0.038931
123 -0.343864 -0.108813 -0.152519  ... -0.249772 -0.051174 -0.213151
124 -0.194408  0.087591 -0.040285  ... -0.147118  0.213015  0.047529
125 -0.204126  0.117761 -0.048626  ... -0.189080  0.235212  0.030477
126 -0.346638 -0.085104 -0.151646  ... -0.243596 -0.055423 -0.217973

      feat_26   feat_27   feat_28   feat_29   feat_30   feat_31  \
122  0.199264 -0.070705 -0.297702 -0.252042 -0.152763  0.302154
123 -0.101208  0.141073 -0.203116  0.100269  0.115215  0.144722
124  0.195490 -0.130240 -0.282920 -0.277870 -0.140912  0.301207
125  0.196924 -0.069665 -0.287792 -0.232291 -0.123150  0.302321
126 -0.107943  0.158576 -0.193680  0.110903  0.134205  0.147582

     PD_Label_Combined
122                0.0
123                1.0
124                0.0
125                0.0
126                1.0

[5 rows x 33 columns]

In [8]:
# Make a copy to be safe (optional)
fused_df_named_int = fused_df_named.copy()

# Convert only the last column to int
fused_df_named_int['PD_Label_Combined'] = fused_df_named_int['PD_Label_Combined'].astype(int)

# Verify
print(fused_df_named_int.dtypes)
print(fused_df_named_int.head())

feat_0               float32
feat_1               float32
feat_2               float32
feat_3               float32
feat_4               float32
feat_5               float32
feat_6               float32
feat_7               float32
feat_8               float32
feat_9               float32
feat_10              float32
feat_11              float32
feat_12              float32
feat_13              float32
feat_14              float32
feat_15              float32
feat_16              float32
feat_17              float32
feat_18              float32
feat_19              float32
feat_20              float32
feat_21              float32
feat_22              float32
feat_23              float32
feat_24              float32
feat_25              float32
feat_26              float32
feat_27              float32
feat_28              float32
feat_29              float32
feat_30              float32
feat_31              float32
PD_Label_Combined      int64
dtype: object
     feat_0    feat_1    feat_2    feat_3    feat_4    feat_5    feat_6  \
0  0.127717  0.179660  0.263688  0.151719  0.219084  0.125436  0.025157
1  0.096788  0.201059  0.275873  0.157291  0.214269  0.133495  0.004797
2  0.101601  0.187792  0.258715  0.144729  0.236691  0.128639  0.018097
3 -0.214877  0.267193 -0.074181 -0.160961  0.060650 -0.186432 -0.298644
4 -0.199068  0.263451 -0.074142 -0.149610  0.073712 -0.188132 -0.306001

     feat_7    feat_8    feat_9  ...   feat_23   feat_24   feat_25   feat_26  \
0 -0.202092  0.106707 -0.043072  ... -0.178620  0.205491  0.033113  0.209716
1 -0.201422  0.102947 -0.036616  ... -0.188519  0.217027  0.045991  0.214624
2 -0.195032  0.066789 -0.042611  ... -0.155815  0.229582  0.030754  0.184425
3 -0.339814 -0.102450 -0.138319  ... -0.248103 -0.052360 -0.202328 -0.099042
4 -0.342676 -0.099565 -0.134739  ... -0.263244 -0.038188 -0.193859 -0.091420

    feat_27   feat_28   feat_29   feat_30   feat_31  PD_Label_Combined
0 -0.123894 -0.292267 -0.270605 -0.151716  0.280475                  0
1 -0.090419 -0.284295 -0.258292 -0.150794  0.298372                  0
2 -0.104199 -0.296371 -0.266898 -0.130868  0.321311                  0
3  0.145333 -0.188573  0.115622  0.122745  0.147212                  1
4  0.142412 -0.205968  0.098411  0.122434  0.140329                  1

[5 rows x 33 columns]

In [9]:
# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [10]:
import pandas as pd

fused_df_named_int.to_csv('/content/drive//MyDrive/Modality-meg(rest)_par_MIRA-Net_data.csv', index=False)

In [11]:
# ============================================================
# ###8)###
# ENSEMBLE CLASSIFICATION WITH STRATIFIED 10-FOLD CV
# ============================================================

# ------------------ Install Required Packages ------------------

!pip install xgboost lightgbm catboost scikit-learn statsmodels matplotlib seaborn --quiet


# ------------------ Imports ------------------

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.utils.class_weight import compute_class_weight

from sklearn.model_selection import (
    train_test_split,
    StratifiedKFold
)

from sklearn.preprocessing import StandardScaler

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    balanced_accuracy_score,
    matthews_corrcoef,
    confusion_matrix
)

from sklearn.ensemble import (
    VotingClassifier,
    StackingClassifier,
    RandomForestClassifier,
    HistGradientBoostingClassifier
)

from sklearn.linear_model import LogisticRegression

from xgboost import XGBClassifier

from statsmodels.stats.proportion import proportion_confint


# ============================================================
# STEP 1: PREPARE DATA
# ============================================================

X = fused_df_named_int[
    [f'feat_{i}' for i in range(32)]
].copy()

y = fused_df_named_int[
    "PD_Label_Combined"
].copy()


# ------------------ Convert X to numeric ------------------

X = X.apply(
    pd.to_numeric,
    errors='coerce'
)

X.fillna(
    0,
    inplace=True
)


# ============================================================
# STEP 2: CLASS WEIGHTS
# ============================================================

classes = np.unique(y)

class_weights = compute_class_weight(
    class_weight='balanced',
    classes=classes,
    y=y
)

class_weights_dict = {
    int(classes[0]): float(class_weights[0]),
    int(classes[1]): float(class_weights[1])
}

print("\nClass Weights:")
print(class_weights_dict)


# ============================================================
# STEP 3: TRAIN-TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=42
)


print("\nTrain Shape :", X_train.shape)
print("Test Shape  :", X_test.shape)

print("\nTraining Class Distribution:")
print(y_train.value_counts())

print("\nTesting Class Distribution:")
print(y_test.value_counts())


# ============================================================
# STEP 4: HANDLE CLASS IMBALANCE
# ============================================================

cw = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_train),
    y=y_train
)

cw_dict = dict(
    zip(
        np.unique(y_train),
        cw
    )
)

scale_pos_weight = (
    cw[1] / cw[0]
)

print("\nTraining Class Weights:")
print(cw_dict)

print(
    "\nXGBoost scale_pos_weight:",
    scale_pos_weight
)


# ============================================================
# STEP 5: BASE MODEL CREATION FUNCTION
# ============================================================

def create_models():

    # ---------------- XGBoost ----------------

    xgb = XGBClassifier(
        n_estimators=200,
        max_depth=4,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,

        scale_pos_weight=scale_pos_weight,

        eval_metric='logloss',

        random_state=42,
        n_jobs=-1
    )


    # ---------------- Random Forest ----------------

    rf = RandomForestClassifier(
        n_estimators=200,

        class_weight='balanced',

        random_state=42,
        n_jobs=-1
    )


    # ---------------- HistGradientBoosting ----------------

    hgb = HistGradientBoostingClassifier(
        max_iter=200,
        learning_rate=0.05,
        max_leaf_nodes=31,

        class_weight='balanced',

        random_state=42
    )


    return xgb, rf, hgb


# ============================================================
# STEP 6: STRATIFIED 10-FOLD CV
# ============================================================

skf = StratifiedKFold(
    n_splits=10,
    shuffle=True,
    random_state=42
)


# ============================================================
# STEP 7: EVALUATION FUNCTION
# ============================================================

def evaluate_model(model_name):

    # ========================================================
    # CV METRIC STORAGE
    # ========================================================

    cv_accuracy = []
    cv_precision = []
    cv_sensitivity = []
    cv_f1 = []
    cv_auc = []
    cv_balanced_accuracy = []


    # ========================================================
    # 10-FOLD STRATIFIED CROSS-VALIDATION
    # ========================================================

    for fold, (train_idx, val_idx) in enumerate(
        skf.split(X_train, y_train),
        start=1
    ):

        print(
            f"\n{model_name} | Fold {fold}/10"
        )


        # ----------------------------------------------------
        # Split fold
        # ----------------------------------------------------

        X_tr = X_train.iloc[
            train_idx
        ]

        X_val = X_train.iloc[
            val_idx
        ]

        y_tr = y_train.iloc[
            train_idx
        ]

        y_val = y_train.iloc[
            val_idx
        ]


        # ----------------------------------------------------
        # Scaling INSIDE EACH FOLD
        # ----------------------------------------------------

        scaler = StandardScaler()

        X_tr_scaled = scaler.fit_transform(
            X_tr
        )

        X_val_scaled = scaler.transform(
            X_val
        )


        # ----------------------------------------------------
        # Create FRESH models for every fold
        # ----------------------------------------------------

        xgb, rf, hgb = create_models()


        # ----------------------------------------------------
        # Select requested model
        # ----------------------------------------------------

        if model_name == "XGBoost":

            model = xgb


        elif model_name == "Random Forest":

            model = rf


        elif model_name == "HistGradientBoosting":

            model = hgb


        elif model_name == "Voting Fusion":

            model = VotingClassifier(
                estimators=[
                    ('xgb', xgb),
                    ('rf', rf),
                    ('hgb', hgb)
                ],
                voting='soft'
            )


        elif model_name == "Stacking Fusion":

            model = StackingClassifier(
                estimators=[
                    ('xgb', xgb),
                    ('rf', rf),
                    ('hgb', hgb)
                ],

                final_estimator=LogisticRegression(
                    max_iter=1000,
                    class_weight='balanced'
                ),

                passthrough=True,

                cv=5
            )


        else:

            raise ValueError(
                f"Unknown model: {model_name}"
            )


        # ----------------------------------------------------
        # Train fold
        # ----------------------------------------------------

        model.fit(
            X_tr_scaled,
            y_tr
        )


        # ----------------------------------------------------
        # Validation predictions
        # ----------------------------------------------------

        val_preds = model.predict(
            X_val_scaled
        )

        val_probs = model.predict_proba(
            X_val_scaled
        )[:, 1]


        # ----------------------------------------------------
        # Fold metrics
        # ----------------------------------------------------

        fold_accuracy = accuracy_score(
            y_val,
            val_preds
        )

        fold_precision = precision_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_sensitivity = recall_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_f1 = f1_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_auc = roc_auc_score(
            y_val,
            val_probs
        )

        fold_balanced_accuracy = balanced_accuracy_score(
            y_val,
            val_preds
        )


        # ----------------------------------------------------
        # Store fold metrics
        # ----------------------------------------------------

        cv_accuracy.append(
            fold_accuracy
        )

        cv_precision.append(
            fold_precision
        )

        cv_sensitivity.append(
            fold_sensitivity
        )

        cv_f1.append(
            fold_f1
        )

        cv_auc.append(
            fold_auc
        )

        cv_balanced_accuracy.append(
            fold_balanced_accuracy
        )


        # ----------------------------------------------------
        # Print fold result
        # ----------------------------------------------------

        print(
            f"Accuracy            : {fold_accuracy:.4f}"
        )

        print(
            f"Precision           : {fold_precision:.4f}"
        )

        print(
            f"Sensitivity         : {fold_sensitivity:.4f}"
        )

        print(
            f"F1 Score            : {fold_f1:.4f}"
        )

        print(
            f"ROC-AUC             : {fold_auc:.4f}"
        )

        print(
            f"Balanced Accuracy   : "
            f"{fold_balanced_accuracy:.4f}"
        )


    # ========================================================
    # CV MEAN RESULTS
    # ========================================================

    cv_accuracy_mean = np.mean(
        cv_accuracy
    )

    cv_precision_mean = np.mean(
        cv_precision
    )

    cv_sensitivity_mean = np.mean(
        cv_sensitivity
    )

    cv_f1_mean = np.mean(
        cv_f1
    )

    cv_auc_mean = np.mean(
        cv_auc
    )

    cv_balanced_accuracy_mean = np.mean(
        cv_balanced_accuracy
    )


    # ========================================================
    # CROSS-VALIDATION RESULTS
    # ========================================================

    print(
        "\n================================================"
    )

    print(
        f"{model_name} - Cross-Validation (10-fold)"
    )

    print(
        "================================================"
    )

    print(
        f"Accuracy            : "
        f"{cv_accuracy_mean:.4f}"
    )

    print(
        f"Precision           : "
        f"{cv_precision_mean:.4f}"
    )

    print(
        f"Recall/Sensitivity  : "
        f"{cv_sensitivity_mean:.4f}"
    )

    print(
        f"F1 Score            : "
        f"{cv_f1_mean:.4f}"
    )

    print(
        f"ROC-AUC             : "
        f"{cv_auc_mean:.4f}"
    )

    print(
        f"Balanced Accuracy   : "
        f"{cv_balanced_accuracy_mean:.4f}"
    )


    # ========================================================
    # TRAIN FINAL MODEL ON COMPLETE TRAINING SET
    # ========================================================

    final_scaler = StandardScaler()

    X_train_final_scaled = final_scaler.fit_transform(
        X_train
    )

    X_test_final_scaled = final_scaler.transform(
        X_test
    )


    # --------------------------------------------------------
    # Create fresh final models
    # --------------------------------------------------------

    xgb, rf, hgb = create_models()


    if model_name == "XGBoost":

        final_model = xgb


    elif model_name == "Random Forest":

        final_model = rf


    elif model_name == "HistGradientBoosting":

        final_model = hgb


    elif model_name == "Voting Fusion":

        final_model = VotingClassifier(
            estimators=[
                ('xgb', xgb),
                ('rf', rf),
                ('hgb', hgb)
            ],
            voting='soft'
        )


    elif model_name == "Stacking Fusion":

        final_model = StackingClassifier(
            estimators=[
                ('xgb', xgb),
                ('rf', rf),
                ('hgb', hgb)
            ],

            final_estimator=LogisticRegression(
                max_iter=1000,
                class_weight='balanced'
            ),

            passthrough=True,

            cv=5
        )


    # ========================================================
    # FINAL TRAINING
    # ========================================================

    final_model.fit(
        X_train_final_scaled,
        y_train
    )


    # ========================================================
    # TEST PREDICTIONS
    # ========================================================

    test_preds = final_model.predict(
        X_test_final_scaled
    )

    test_probs = final_model.predict_proba(
        X_test_final_scaled
    )[:, 1]


    # ========================================================
    # TEST METRICS
    # ========================================================

    accuracy = accuracy_score(
        y_test,
        test_preds
    )

    precision = precision_score(
        y_test,
        test_preds,
        zero_division=0
    )

    sensitivity = recall_score(
        y_test,
        test_preds,
        zero_division=0
    )

    f1 = f1_score(
        y_test,
        test_preds,
        zero_division=0
    )

    roc_auc = roc_auc_score(
        y_test,
        test_probs
    )

    balanced_accuracy = balanced_accuracy_score(
        y_test,
        test_preds
    )

    mcc = matthews_corrcoef(
        y_test,
        test_preds
    )


    # ========================================================
    # CONFUSION MATRIX
    # ========================================================

    cm = confusion_matrix(
        y_test,
        test_preds,
        labels=[0, 1]
    )

    tn, fp, fn, tp = cm.ravel()


    # ========================================================
    # SENSITIVITY / SPECIFICITY
    # ========================================================

    sensitivity = (
        tp / (tp + fn)
        if (tp + fn) > 0
        else 0
    )

    specificity = (
        tn / (tn + fp)
        if (tn + fp) > 0
        else 0
    )


    # ========================================================
    # 95% CONFIDENCE INTERVALS
    # ========================================================

    # ---------------- Accuracy CI ----------------

    acc_low, acc_high = proportion_confint(
        count=int(round(accuracy * len(y_test))),
        nobs=len(y_test),
        alpha=0.05,
        method='wilson'
    )


    # ---------------- Precision CI ----------------

    precision_low, precision_high = proportion_confint(
        count=tp,
        nobs=(tp + fp),
        alpha=0.05,
        method='wilson'
    ) if (tp + fp) > 0 else (0.0, 0.0)


    # ---------------- Sensitivity CI ----------------

    sensitivity_low, sensitivity_high = proportion_confint(
        count=tp,
        nobs=(tp + fn),
        alpha=0.05,
        method='wilson'
    ) if (tp + fn) > 0 else (0.0, 0.0)


    # ---------------- Specificity CI ----------------

    specificity_low, specificity_high = proportion_confint(
        count=tn,
        nobs=(tn + fp),
        alpha=0.05,
        method='wilson'
    ) if (tn + fp) > 0 else (0.0, 0.0)


    # ========================================================
    # TEST SET PERFORMANCE
    # ========================================================

    print(
        "\n================================================"
    )

    print(
        f"{model_name} - Test Set Performance"
    )

    print(
        "================================================"
    )

    print(
        f"Accuracy            : {accuracy:.4f} "
        f"(95% CI: "
        f"{acc_low:.4f}-{acc_high:.4f})"
    )

    print(
        f"Precision           : {precision:.4f} "
        f"(95% CI: "
        f"{precision_low:.4f}-{precision_high:.4f})"
    )

    print(
        f"Sensitivity         : {sensitivity:.4f} "
        f"(95% CI: "
        f"{sensitivity_low:.4f}-{sensitivity_high:.4f})"
    )

    print(
        f"Specificity         : {specificity:.4f} "
        f"(95% CI: "
        f"{specificity_low:.4f}-{specificity_high:.4f})"
    )

    print(
        f"F1 Score            : {f1:.4f}"
    )

    print(
        f"ROC-AUC             : {roc_auc:.4f}"
    )

    print(
        f"Balanced Accuracy   : "
        f"{balanced_accuracy:.4f}"
    )

    print(
        f"MCC                 : {mcc:.4f}"
    )


    # ========================================================
    # CONFUSION MATRIX
    # ========================================================

    print(
        "\nConfusion Matrix:"
    )

    print(cm)

    print(
        "\nTN :", tn
    )

    print(
        "FP :", fp
    )

    print(
        "FN :", fn
    )

    print(
        "TP :", tp
    )


    # ========================================================
    # STORE RESULTS
    # ========================================================

    result = {

        # ---------------- CV ----------------

        "CV Accuracy":
            cv_accuracy_mean,

        "CV Precision":
            cv_precision_mean,

        "CV Sensitivity":
            cv_sensitivity_mean,

        "CV F1":
            cv_f1_mean,

        "CV ROC-AUC":
            cv_auc_mean,

        "CV Balanced Accuracy":
            cv_balanced_accuracy_mean,


        # ---------------- Test ----------------

        "Accuracy":
            accuracy,

        "Accuracy CI Low":
            acc_low,

        "Accuracy CI High":
            acc_high,


        "Precision":
            precision,

        "Precision CI Low":
            precision_low,

        "Precision CI High":
            precision_high,


        "Sensitivity":
            sensitivity,

        "Sensitivity CI Low":
            sensitivity_low,

        "Sensitivity CI High":
            sensitivity_high,


        "Specificity":
            specificity,

        "Specificity CI Low":
            specificity_low,

        "Specificity CI High":
            specificity_high,


        "F1":
            f1,

        "ROC-AUC":
            roc_auc,

        "Balanced Accuracy":
            balanced_accuracy,

        "MCC":
            mcc,


        # ---------------- Confusion Matrix ----------------

        "TN":
            tn,

        "FP":
            fp,

        "FN":
            fn,

        "TP":
            tp
    }


    return result


# ============================================================
# STEP 8: EVALUATE ALL MODELS
# ============================================================

model_names = [
    "XGBoost",
    "Random Forest",
    "HistGradientBoosting",
    "Voting Fusion",
    "Stacking Fusion"
]


results = {}

for name in model_names:

    print(
        "\n\n################################################"
    )

    print(
        f"Evaluating: {name}"
    )

    print(
        "################################################"
    )

    results[name] = evaluate_model(
        name
    )


# ============================================================
# STEP 9: FINAL RESULTS DATAFRAME
# ============================================================

results_df = pd.DataFrame(
    results
).T


# ============================================================
# STEP 10: ORDER RESULTS
# ============================================================

results_df = results_df[
    [

        # ---------------- CV ----------------

        "CV Accuracy",
        "CV Precision",
        "CV Sensitivity",
        "CV F1",
        "CV ROC-AUC",
        "CV Balanced Accuracy",


        # ---------------- Test ----------------

        "Accuracy",
        "Accuracy CI Low",
        "Accuracy CI High",

        "Precision",
        "Precision CI Low",
        "Precision CI High",

        "Sensitivity",
        "Sensitivity CI Low",
        "Sensitivity CI High",

        "Specificity",
        "Specificity CI Low",
        "Specificity CI High",

        "F1",
        "ROC-AUC",
        "Balanced Accuracy",
        "MCC",

        # ---------------- Confusion Matrix ----------------

        "TN",
        "FP",
        "FN",
        "TP"
    ]
]


# ============================================================
# STEP 11: DISPLAY FINAL RESULTS
# ============================================================

print(
    "\n================================================"
)

print(
    "FINAL MODEL COMPARISON"
)

print(
    "================================================\n"
)


display(
    results_df.sort_values(
        by="F1",
        ascending=False
    )
)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 9.0 MB/s eta 0:00:00

Class Weights:
{0: 0.9769230769230769, 1: 1.0241935483870968}

Train Shape : (101, 32)
Test Shape  : (26, 32)

Training Class Distribution:
PD_Label_Combined
0    52
1    49
Name: count, dtype: int64

Testing Class Distribution:
PD_Label_Combined
1    13
0    13
Name: count, dtype: int64

Training Class Weights:
{np.int64(0): np.float64(0.9711538461538461), np.int64(1): np.float64(1.030612244897959)}

XGBoost scale_pos_weight: 1.0612244897959182


################################################
Evaluating: XGBoost
################################################

XGBoost | Fold 1/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

XGBoost | Fold 2/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

XGBoost | Fold 3/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

XGBoost | Fold 4/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

XGBoost | Fold 5/10
Accuracy            : 0.9000
Precision           : 1.0000
Sensitivity         : 0.8000
F1 Score            : 0.8889
ROC-AUC             : 0.9800
Balanced Accuracy   : 0.9000

XGBoost | Fold 6/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

XGBoost | Fold 7/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

XGBoost | Fold 8/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

XGBoost | Fold 9/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

XGBoost | Fold 10/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

================================================
XGBoost - Cross-Validation (10-fold)
================================================
Accuracy            : 0.9900
Precision           : 1.0000
Recall/Sensitivity  : 0.9800
F1 Score            : 0.9889
ROC-AUC             : 0.9980
Balanced Accuracy   : 0.9900

================================================
XGBoost - Test Set Performance
================================================
Accuracy            : 1.0000 (95% CI: 0.8713-1.0000)
Precision           : 1.0000 (95% CI: 0.7719-1.0000)
Sensitivity         : 1.0000 (95% CI: 0.7719-1.0000)
Specificity         : 1.0000 (95% CI: 0.7719-1.0000)
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000
MCC                 : 1.0000

Confusion Matrix:
[[13  0]
 [ 0 13]]

TN : 13
FP : 0
FN : 0
TP : 13


################################################
Evaluating: Random Forest
################################################

Random Forest | Fold 1/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Random Forest | Fold 2/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Random Forest | Fold 3/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Random Forest | Fold 4/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Random Forest | Fold 5/10
Accuracy            : 0.9000
Precision           : 1.0000
Sensitivity         : 0.8000
F1 Score            : 0.8889
ROC-AUC             : 0.9800
Balanced Accuracy   : 0.9000

Random Forest | Fold 6/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Random Forest | Fold 7/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Random Forest | Fold 8/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Random Forest | Fold 9/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Random Forest | Fold 10/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

================================================
Random Forest - Cross-Validation (10-fold)
================================================
Accuracy            : 0.9900
Precision           : 1.0000
Recall/Sensitivity  : 0.9800
F1 Score            : 0.9889
ROC-AUC             : 0.9980
Balanced Accuracy   : 0.9900

================================================
Random Forest - Test Set Performance
================================================
Accuracy            : 1.0000 (95% CI: 0.8713-1.0000)
Precision           : 1.0000 (95% CI: 0.7719-1.0000)
Sensitivity         : 1.0000 (95% CI: 0.7719-1.0000)
Specificity         : 1.0000 (95% CI: 0.7719-1.0000)
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000
MCC                 : 1.0000

Confusion Matrix:
[[13  0]
 [ 0 13]]

TN : 13
FP : 0
FN : 0
TP : 13


################################################
Evaluating: HistGradientBoosting
################################################

HistGradientBoosting | Fold 1/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

HistGradientBoosting | Fold 2/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

HistGradientBoosting | Fold 3/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

HistGradientBoosting | Fold 4/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

HistGradientBoosting | Fold 5/10
Accuracy            : 0.9000
Precision           : 1.0000
Sensitivity         : 0.8000
F1 Score            : 0.8889
ROC-AUC             : 0.9000
Balanced Accuracy   : 0.9000

HistGradientBoosting | Fold 6/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

HistGradientBoosting | Fold 7/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

HistGradientBoosting | Fold 8/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

HistGradientBoosting | Fold 9/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

HistGradientBoosting | Fold 10/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

================================================
HistGradientBoosting - Cross-Validation (10-fold)
================================================
Accuracy            : 0.9900
Precision           : 1.0000
Recall/Sensitivity  : 0.9800
F1 Score            : 0.9889
ROC-AUC             : 0.9900
Balanced Accuracy   : 0.9900

================================================
HistGradientBoosting - Test Set Performance
================================================
Accuracy            : 1.0000 (95% CI: 0.8713-1.0000)
Precision           : 1.0000 (95% CI: 0.7719-1.0000)
Sensitivity         : 1.0000 (95% CI: 0.7719-1.0000)
Specificity         : 1.0000 (95% CI: 0.7719-1.0000)
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000
MCC                 : 1.0000

Confusion Matrix:
[[13  0]
 [ 0 13]]

TN : 13
FP : 0
FN : 0
TP : 13


################################################
Evaluating: Voting Fusion
################################################

Voting Fusion | Fold 1/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Voting Fusion | Fold 2/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Voting Fusion | Fold 3/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Voting Fusion | Fold 4/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Voting Fusion | Fold 5/10
Accuracy            : 0.9000
Precision           : 1.0000
Sensitivity         : 0.8000
F1 Score            : 0.8889
ROC-AUC             : 0.9800
Balanced Accuracy   : 0.9000

Voting Fusion | Fold 6/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Voting Fusion | Fold 7/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Voting Fusion | Fold 8/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Voting Fusion | Fold 9/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Voting Fusion | Fold 10/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

================================================
Voting Fusion - Cross-Validation (10-fold)
================================================
Accuracy            : 0.9900
Precision           : 1.0000
Recall/Sensitivity  : 0.9800
F1 Score            : 0.9889
ROC-AUC             : 0.9980
Balanced Accuracy   : 0.9900

================================================
Voting Fusion - Test Set Performance
================================================
Accuracy            : 1.0000 (95% CI: 0.8713-1.0000)
Precision           : 1.0000 (95% CI: 0.7719-1.0000)
Sensitivity         : 1.0000 (95% CI: 0.7719-1.0000)
Specificity         : 1.0000 (95% CI: 0.7719-1.0000)
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000
MCC                 : 1.0000

Confusion Matrix:
[[13  0]
 [ 0 13]]

TN : 13
FP : 0
FN : 0
TP : 13


################################################
Evaluating: Stacking Fusion
################################################

Stacking Fusion | Fold 1/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Stacking Fusion | Fold 2/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Stacking Fusion | Fold 3/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Stacking Fusion | Fold 4/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Stacking Fusion | Fold 5/10
Accuracy            : 0.9000
Precision           : 1.0000
Sensitivity         : 0.8000
F1 Score            : 0.8889
ROC-AUC             : 0.9800
Balanced Accuracy   : 0.9000

Stacking Fusion | Fold 6/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Stacking Fusion | Fold 7/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Stacking Fusion | Fold 8/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Stacking Fusion | Fold 9/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

Stacking Fusion | Fold 10/10
Accuracy            : 1.0000
Precision           : 1.0000
Sensitivity         : 1.0000
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000

================================================
Stacking Fusion - Cross-Validation (10-fold)
================================================
Accuracy            : 0.9900
Precision           : 1.0000
Recall/Sensitivity  : 0.9800
F1 Score            : 0.9889
ROC-AUC             : 0.9980
Balanced Accuracy   : 0.9900

================================================
Stacking Fusion - Test Set Performance
================================================
Accuracy            : 1.0000 (95% CI: 0.8713-1.0000)
Precision           : 1.0000 (95% CI: 0.7719-1.0000)
Sensitivity         : 1.0000 (95% CI: 0.7719-1.0000)
Specificity         : 1.0000 (95% CI: 0.7719-1.0000)
F1 Score            : 1.0000
ROC-AUC             : 1.0000
Balanced Accuracy   : 1.0000
MCC                 : 1.0000

Confusion Matrix:
[[13  0]
 [ 0 13]]

TN : 13
FP : 0
FN : 0
TP : 13

================================================
FINAL MODEL COMPARISON
================================================

,CV Accuracy,CV Precision,CV Sensitivity,CV F1,CV ROC-AUC,CV Balanced Accuracy,Accuracy,Accuracy CI Low,Accuracy CI High,Precision,...,Specificity CI Low,Specificity CI High,F1,ROC-AUC,Balanced Accuracy,MCC,TN,FP,FN,TP
XGBoost,0.99,1.0,0.98,0.988889,0.998,0.99,1.0,0.871271,1.0,1.0,...,0.771905,1.0,1.0,1.0,1.0,1.0,13.0,0.0,0.0,13.0
Random Forest,0.99,1.0,0.98,0.988889,0.998,0.99,1.0,0.871271,1.0,1.0,...,0.771905,1.0,1.0,1.0,1.0,1.0,13.0,0.0,0.0,13.0
HistGradientBoosting,0.99,1.0,0.98,0.988889,0.990,0.99,1.0,0.871271,1.0,1.0,...,0.771905,1.0,1.0,1.0,1.0,1.0,13.0,0.0,0.0,13.0
Voting Fusion,0.99,1.0,0.98,0.988889,0.998,0.99,1.0,0.871271,1.0,1.0,...,0.771905,1.0,1.0,1.0,1.0,1.0,13.0,0.0,0.0,13.0
Stacking Fusion,0.99,1.0,0.98,0.988889,0.998,0.99,1.0,0.871271,1.0,1.0,...,0.771905,1.0,1.0,1.0,1.0,1.0,13.0,0.0,0.0,13.0

Without MIRA-Net

In [1]:
# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

final_meg_df = pd.read_csv('/content/drive/MyDrive/final_meg_rest_21_par-lev_final.csv')

print("Loaded data shape:", final_meg_df.shape)
print(final_meg_df.head())

Loaded data shape: (127, 106)
   burst_rate_L_mean  burst_rate_L_std  burst_rate_R_mean  burst_rate_R_std  \
0           4.412365          0.242544           4.486517          0.188241
1           3.828010          0.316999           3.783657          0.297773
2           4.645359          0.130894           4.713304          0.111269
3           4.142208          0.243497           4.183916          0.217601
4           3.923527          0.336133           4.035406          0.306960

   burst_rate_asym  mean_burst_duration_L_mean  mean_burst_duration_L_std  \
0        -0.008333                    0.056832                   0.003237
1         0.005827                    0.065725                   0.005382
2        -0.007260                    0.053844                   0.001551
3        -0.005009                    0.060555                   0.003554
4        -0.014057                    0.064178                   0.005454

   mean_burst_duration_R_mean  mean_burst_duration_R_std  \
0                    0.055801                   0.002407
1                    0.066463                   0.005160
2                    0.053060                   0.001270
3                    0.059908                   0.003106
4                    0.062294                   0.004734

   mean_burst_duration_asym  ...  spectral_flatness_L_std  \
0                  0.009156  ...                 0.091817
1                 -0.005581  ...                 0.068904
2                  0.007325  ...                 0.016316
3                  0.005372  ...                 0.067243
4                  0.014897  ...                 0.033405

   spectral_flatness_R_mean  spectral_flatness_R_std  spectral_flatness_asym  \
0                  0.876225                 0.073953               -0.008900
1                  0.824798                 0.064574                0.010677
2                  0.957087                 0.012624                0.000672
3                  0.822173                 0.054189               -0.005699
4                  0.882392                 0.027770               -0.003794

   spectral_slope_L_mean  spectral_slope_L_std  spectral_slope_R_mean  \
0          -4.309604e-13          6.744059e-13          -2.233093e-13
1          -9.134283e-13          1.131478e-12          -9.278616e-13
2          -6.902417e-14          1.028420e-13          -5.045241e-14
3          -8.858549e-13          1.217447e-12          -3.559801e-13
4          -6.622744e-13          8.793728e-13          -2.369554e-13

   spectral_slope_R_std  spectral_slope_asym  Pd_indicator_meg
0          3.432532e-13            -0.000021                 0
1          1.090616e-12             0.000001                 0
2          6.137480e-14            -0.000002                 0
3          4.306339e-13            -0.000053                 1
4          2.665908e-13            -0.000043                 1

[5 rows x 106 columns]

In [3]:
fused_df_named_int = final_meg_df.rename(columns={"Pd_indicator_meg": "PD_Label_Combined"})
fused_df_named_int.head()
fused_df_named_int.shape

(127, 106)

In [4]:
fused_df_named_int.head()

,burst_rate_L_mean,burst_rate_L_std,burst_rate_R_mean,burst_rate_R_std,burst_rate_asym,mean_burst_duration_L_mean,mean_burst_duration_L_std,mean_burst_duration_R_mean,mean_burst_duration_R_std,mean_burst_duration_asym,...,spectral_flatness_L_std,spectral_flatness_R_mean,spectral_flatness_R_std,spectral_flatness_asym,spectral_slope_L_mean,spectral_slope_L_std,spectral_slope_R_mean,spectral_slope_R_std,spectral_slope_asym,PD_Label_Combined
0,4.412365,0.242544,4.486517,0.188241,-0.008333,0.056832,0.003237,0.055801,0.002407,0.009156,...,0.091817,0.876225,0.073953,-0.008900,-4.309604e-13,6.744059e-13,-2.233093e-13,3.432532e-13,-0.000021,0
1,3.828010,0.316999,3.783657,0.297773,0.005827,0.065725,0.005382,0.066463,0.005160,-0.005581,...,0.068904,0.824798,0.064574,0.010677,-9.134283e-13,1.131478e-12,-9.278616e-13,1.090616e-12,0.000001,0
2,4.645359,0.130894,4.713304,0.111269,-0.007260,0.053844,0.001551,0.053060,0.001270,0.007325,...,0.016316,0.957087,0.012624,0.000672,-6.902417e-14,1.028420e-13,-5.045241e-14,6.137480e-14,-0.000002,0
3,4.142208,0.243497,4.183916,0.217601,-0.005009,0.060555,0.003554,0.059908,0.003106,0.005372,...,0.067243,0.822173,0.054189,-0.005699,-8.858549e-13,1.217447e-12,-3.559801e-13,4.306339e-13,-0.000053,1
4,3.923527,0.336133,4.035406,0.306960,-0.014057,0.064178,0.005454,0.062294,0.004734,0.014897,...,0.033405,0.882392,0.027770,-0.003794,-6.622744e-13,8.793728e-13,-2.369554e-13,2.665908e-13,-0.000043,1

In [5]:
# ============================================================
# ###8)###
#
# ENSEMBLE CLASSIFICATION WITH STRATIFIED 10-FOLD CV
# ============================================================

# ------------------ Install Required Packages ------------------

!pip install xgboost lightgbm catboost scikit-learn statsmodels matplotlib seaborn --quiet


# ------------------ Imports ------------------

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.utils.class_weight import compute_class_weight

from sklearn.model_selection import (
    train_test_split,
    StratifiedKFold
)

from sklearn.preprocessing import StandardScaler

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    balanced_accuracy_score,
    matthews_corrcoef,
    confusion_matrix
)

from sklearn.ensemble import (
    VotingClassifier,
    StackingClassifier,
    RandomForestClassifier,
    HistGradientBoostingClassifier
)

from sklearn.linear_model import LogisticRegression

from xgboost import XGBClassifier

from statsmodels.stats.proportion import proportion_confint


# ============================================================
# STEP 1: PREPARE DATA
# ============================================================

# All feature columns except the final label column
X = fused_df_named_int.iloc[:, :-1].copy()

# Target
y = fused_df_named_int["PD_Label_Combined"].copy()


# ============================================================
# CONVERT FEATURES TO NUMERIC
# ============================================================

X = X.apply(
    pd.to_numeric,
    errors="coerce"
)


# ============================================================
# CHECK RAW VALUES
# ============================================================

print("\nRaw feature statistics:")
print("Shape :", X.shape)

print(
    "NaN values before cleaning :",
    X.isna().sum().sum()
)

print(
    "Inf values before cleaning :",
    np.isinf(
        X.to_numpy(dtype=np.float64)
    ).sum()
)


# ============================================================
# HANDLE +INF / -INF
# ============================================================

X = X.replace(
    [np.inf, -np.inf],
    np.nan
)


# ============================================================
# COLUMN-WISE MEDIAN IMPUTATION
# ============================================================

col_medians = X.median(
    axis=0,
    skipna=True
)

# If an entire column is NaN,
# replace its median with 0
col_medians = col_medians.fillna(0)

X = X.fillna(
    col_medians
)


# ============================================================
# CLIP EXTREMELY LARGE VALUES
# ============================================================

# Prevent overflow when converting to float32.
#
# Values larger than this are clipped rather than allowed
# to produce inf during float32 conversion.

CLIP_VALUE = 1e10

X = X.clip(
    lower=-CLIP_VALUE,
    upper=CLIP_VALUE
)


# ============================================================
# CONVERT TO FLOAT32 AFTER CLEANING
# ============================================================

X = X.astype(
    np.float32
)


# ============================================================
# FINAL FINITE-VALUE CHECK
# ============================================================

X_array = X.to_numpy()

print("\nAfter cleaning:")

print(
    "NaN values :",
    np.isnan(X_array).sum()
)

print(
    "Inf values :",
    np.isinf(X_array).sum()
)

print(
    "Finite     :",
    np.isfinite(X_array).all()
)

print(
    "Maximum    :",
    np.max(X_array)
)

print(
    "Minimum    :",
    np.min(X_array)
)


# ============================================================
# TARGET CLEANING
# ============================================================

y = pd.to_numeric(
    y,
    errors="coerce"
)

# Make sure target contains no missing values
valid_idx = y.notna()

X = X.loc[valid_idx].reset_index(drop=True)

y = y.loc[valid_idx].astype(
    np.int64
).reset_index(drop=True)


print("\nFinal data:")
print("X shape :", X.shape)
print("y shape :", y.shape)

print("\nClass distribution:")
print(y.value_counts())


# ============================================================
# STEP 2: CLASS WEIGHTS
# ============================================================

classes = np.unique(y)

class_weights = compute_class_weight(
    class_weight="balanced",
    classes=classes,
    y=y
)

class_weights_dict = {
    int(classes[0]): float(class_weights[0]),
    int(classes[1]): float(class_weights[1])
}

print("\nClass Weights:")
print(class_weights_dict)


# ============================================================
# STEP 3: TRAIN-TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    stratify=y,
    random_state=42
)


print("\nTrain Shape :", X_train.shape)
print("Test Shape  :", X_test.shape)


print("\nTraining Class Distribution:")
print(
    y_train.value_counts()
)


print("\nTesting Class Distribution:")
print(
    y_test.value_counts()
)


# ============================================================
# STEP 4: HANDLE CLASS IMBALANCE
# ============================================================

cw = compute_class_weight(
    class_weight="balanced",
    classes=np.unique(y_train),
    y=y_train
)

cw_dict = dict(
    zip(
        np.unique(y_train),
        cw
    )
)

scale_pos_weight = (
    cw_dict[1] / cw_dict[0]
)


print("\nTraining Class Weights:")
print(cw_dict)

print(
    "\nXGBoost scale_pos_weight:",
    scale_pos_weight
)




# ============================================================
# STEP 5: BASE MODEL CREATION FUNCTION
# ============================================================

def create_models():

    # ---------------- XGBoost ----------------

    xgb = XGBClassifier(
        n_estimators=200,
        max_depth=4,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,

        scale_pos_weight=scale_pos_weight,

        eval_metric='logloss',

        random_state=42,
        n_jobs=-1
    )


    # ---------------- Random Forest ----------------

    rf = RandomForestClassifier(
        n_estimators=200,

        class_weight='balanced',

        random_state=42,
        n_jobs=-1
    )


    # ---------------- HistGradientBoosting ----------------

    hgb = HistGradientBoostingClassifier(
        max_iter=200,
        learning_rate=0.05,
        max_leaf_nodes=31,

        class_weight='balanced',

        random_state=42
    )


    return xgb, rf, hgb


# ============================================================
# STEP 6: STRATIFIED 10-FOLD CV
# ============================================================

skf = StratifiedKFold(
    n_splits=10,
    shuffle=True,
    random_state=42
)


# ============================================================
# STEP 7: EVALUATION FUNCTION
# ============================================================

def evaluate_model(model_name):

    # ========================================================
    # CV METRIC STORAGE
    # ========================================================

    cv_accuracy = []
    cv_precision = []
    cv_sensitivity = []
    cv_f1 = []
    cv_auc = []
    cv_balanced_accuracy = []


    # ========================================================
    # 10-FOLD STRATIFIED CROSS-VALIDATION
    # ========================================================

    for fold, (train_idx, val_idx) in enumerate(
        skf.split(X_train, y_train),
        start=1
    ):

        print(
            f"\n{model_name} | Fold {fold}/10"
        )


        # ----------------------------------------------------
        # Split fold
        # ----------------------------------------------------

        X_tr = X_train.iloc[
            train_idx
        ]

        X_val = X_train.iloc[
            val_idx
        ]

        y_tr = y_train.iloc[
            train_idx
        ]

        y_val = y_train.iloc[
            val_idx
        ]


        # ----------------------------------------------------
        # Scaling INSIDE EACH FOLD
        # ----------------------------------------------------

        scaler = StandardScaler()

        X_tr_scaled = scaler.fit_transform(
            X_tr
        )

        X_val_scaled = scaler.transform(
            X_val
        )


        # ----------------------------------------------------
        # Create FRESH models for every fold
        # ----------------------------------------------------

        xgb, rf, hgb = create_models()


        # ----------------------------------------------------
        # Select requested model
        # ----------------------------------------------------

        if model_name == "XGBoost":

            model = xgb


        elif model_name == "Random Forest":

            model = rf


        elif model_name == "HistGradientBoosting":

            model = hgb


        elif model_name == "Voting Fusion":

            model = VotingClassifier(
                estimators=[
                    ('xgb', xgb),
                    ('rf', rf),
                    ('hgb', hgb)
                ],
                voting='soft'
            )


        elif model_name == "Stacking Fusion":

            model = StackingClassifier(
                estimators=[
                    ('xgb', xgb),
                    ('rf', rf),
                    ('hgb', hgb)
                ],

                final_estimator=LogisticRegression(
                    max_iter=1000,
                    class_weight='balanced'
                ),

                passthrough=True,

                cv=5
            )


        else:

            raise ValueError(
                f"Unknown model: {model_name}"
            )


        # ----------------------------------------------------
        # Train fold
        # ----------------------------------------------------

        model.fit(
            X_tr_scaled,
            y_tr
        )


        # ----------------------------------------------------
        # Validation predictions
        # ----------------------------------------------------

        scaler = StandardScaler()
        X_tr = X_tr.astype(np.float64)
        X_val = X_val.astype(np.float64)
        X_tr = np.nan_to_num(
            X_tr,
            nan=0.0,
            posinf=0.0,
            neginf=0.0
        )
        X_val = np.nan_to_num(
            X_val,
            nan=0.0,
            posinf=0.0,
            neginf=0.0
        )
        X_tr_scaled = scaler.fit_transform(X_tr)
        X_val_scaled = scaler.transform(X_val)
        # ----------------------------------------------------
        # Safety check after scaling
        # ----------------------------------------------------
        X_tr_scaled = np.nan_to_num(
            X_tr,
            nan=0.0,
            posinf=0.0,
            neginf=0.0
        )
        X_val = np.nan_to_num(
            X_val,
            nan=0.0,
            posinf=0.0,
            neginf=0.0
        )
        print(
            f"Fold {fold}: "
            f"max|X_val|={np.max(np.abs(X_val_scaled)):.4f}"
        )

        val_preds = model.predict(
             X_val_scaled
        )
        val_probs = model.predict_proba(
            X_val_scaled
        )[:, 1]

        # ----------------------------------------------------
        # Fold metrics
        # ----------------------------------------------------

        fold_accuracy = accuracy_score(
            y_val,
            val_preds
        )

        fold_precision = precision_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_sensitivity = recall_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_f1 = f1_score(
            y_val,
            val_preds,
            zero_division=0
        )

        fold_auc = roc_auc_score(
            y_val,
            val_probs
        )

        fold_balanced_accuracy = balanced_accuracy_score(
            y_val,
            val_preds
        )


        # ----------------------------------------------------
        # Store fold metrics
        # ----------------------------------------------------

        cv_accuracy.append(
            fold_accuracy
        )

        cv_precision.append(
            fold_precision
        )

        cv_sensitivity.append(
            fold_sensitivity
        )

        cv_f1.append(
            fold_f1
        )

        cv_auc.append(
            fold_auc
        )

        cv_balanced_accuracy.append(
            fold_balanced_accuracy
        )


        # ----------------------------------------------------
        # Print fold result
        # ----------------------------------------------------

        print(
            f"Accuracy            : {fold_accuracy:.4f}"
        )

        print(
            f"Precision           : {fold_precision:.4f}"
        )

        print(
            f"Sensitivity         : {fold_sensitivity:.4f}"
        )

        print(
            f"F1 Score            : {fold_f1:.4f}"
        )

        print(
            f"ROC-AUC             : {fold_auc:.4f}"
        )

        print(
            f"Balanced Accuracy   : "
            f"{fold_balanced_accuracy:.4f}"
        )


    # ========================================================
    # CV MEAN RESULTS
    # ========================================================

    cv_accuracy_mean = np.mean(
        cv_accuracy
    )

    cv_precision_mean = np.mean(
        cv_precision
    )

    cv_sensitivity_mean = np.mean(
        cv_sensitivity
    )

    cv_f1_mean = np.mean(
        cv_f1
    )

    cv_auc_mean = np.mean(
        cv_auc
    )

    cv_balanced_accuracy_mean = np.mean(
        cv_balanced_accuracy
    )


    # ========================================================
    # CROSS-VALIDATION RESULTS
    # ========================================================

    print(
        "\n================================================"
    )

    print(
        f"{model_name} - Cross-Validation (10-fold)"
    )

    print(
        "================================================"
    )

    print(
        f"Accuracy            : "
        f"{cv_accuracy_mean:.4f}"
    )

    print(
        f"Precision           : "
        f"{cv_precision_mean:.4f}"
    )

    print(
        f"Recall/Sensitivity  : "
        f"{cv_sensitivity_mean:.4f}"
    )

    print(
        f"F1 Score            : "
        f"{cv_f1_mean:.4f}"
    )

    print(
        f"ROC-AUC             : "
        f"{cv_auc_mean:.4f}"
    )

    print(
        f"Balanced Accuracy   : "
        f"{cv_balanced_accuracy_mean:.4f}"
    )


    # ========================================================
    # TRAIN FINAL MODEL ON COMPLETE TRAINING SET
    # ========================================================

    final_scaler = StandardScaler()

    X_train_final_scaled = final_scaler.fit_transform(
        X_train
    )

    X_test_final_scaled = final_scaler.transform(
        X_test
    )


    # --------------------------------------------------------
    # Create fresh final models
    # --------------------------------------------------------

    xgb, rf, hgb = create_models()


    if model_name == "XGBoost":

        final_model = xgb


    elif model_name == "Random Forest":

        final_model = rf


    elif model_name == "HistGradientBoosting":

        final_model = hgb


    elif model_name == "Voting Fusion":

        final_model = VotingClassifier(
            estimators=[
                ('xgb', xgb),
                ('rf', rf),
                ('hgb', hgb)
            ],
            voting='soft'
        )


    elif model_name == "Stacking Fusion":

        final_model = StackingClassifier(
            estimators=[
                ('xgb', xgb),
                ('rf', rf),
                ('hgb', hgb)
            ],

            final_estimator=LogisticRegression(
                max_iter=1000,
                class_weight='balanced'
            ),

            passthrough=True,

            cv=5
        )


    # ========================================================
    # FINAL TRAINING
    # ========================================================

    final_model.fit(
        X_train_final_scaled,
        y_train
    )


    # ========================================================
    # TEST PREDICTIONS
    # ========================================================

    test_preds = final_model.predict(
        X_test_final_scaled
    )

    test_probs = final_model.predict_proba(
        X_test_final_scaled
    )[:, 1]


    # ========================================================
    # TEST METRICS
    # ========================================================

    accuracy = accuracy_score(
        y_test,
        test_preds
    )

    precision = precision_score(
        y_test,
        test_preds,
        zero_division=0
    )

    sensitivity = recall_score(
        y_test,
        test_preds,
        zero_division=0
    )

    f1 = f1_score(
        y_test,
        test_preds,
        zero_division=0
    )

    roc_auc = roc_auc_score(
        y_test,
        test_probs
    )

    balanced_accuracy = balanced_accuracy_score(
        y_test,
        test_preds
    )

    mcc = matthews_corrcoef(
        y_test,
        test_preds
    )


    # ========================================================
    # CONFUSION MATRIX
    # ========================================================

    cm = confusion_matrix(
        y_test,
        test_preds,
        labels=[0, 1]
    )

    tn, fp, fn, tp = cm.ravel()


    # ========================================================
    # SENSITIVITY / SPECIFICITY
    # ========================================================

    sensitivity = (
        tp / (tp + fn)
        if (tp + fn) > 0
        else 0
    )

    specificity = (
        tn / (tn + fp)
        if (tn + fp) > 0
        else 0
    )


    # ========================================================
    # 95% CONFIDENCE INTERVALS
    # ========================================================

    # ---------------- Accuracy CI ----------------

    acc_low, acc_high = proportion_confint(
        count=int(round(accuracy * len(y_test))),
        nobs=len(y_test),
        alpha=0.05,
        method='wilson'
    )


    # ---------------- Precision CI ----------------

    precision_low, precision_high = proportion_confint(
        count=tp,
        nobs=(tp + fp),
        alpha=0.05,
        method='wilson'
    ) if (tp + fp) > 0 else (0.0, 0.0)


    # ---------------- Sensitivity CI ----------------

    sensitivity_low, sensitivity_high = proportion_confint(
        count=tp,
        nobs=(tp + fn),
        alpha=0.05,
        method='wilson'
    ) if (tp + fn) > 0 else (0.0, 0.0)


    # ---------------- Specificity CI ----------------

    specificity_low, specificity_high = proportion_confint(
        count=tn,
        nobs=(tn + fp),
        alpha=0.05,
        method='wilson'
    ) if (tn + fp) > 0 else (0.0, 0.0)


    # ========================================================
    # TEST SET PERFORMANCE
    # ========================================================

    print(
        "\n================================================"
    )

    print(
        f"{model_name} - Test Set Performance"
    )

    print(
        "================================================"
    )

    print(
        f"Accuracy            : {accuracy:.4f} "
        f"(95% CI: "
        f"{acc_low:.4f}-{acc_high:.4f})"
    )

    print(
        f"Precision           : {precision:.4f} "
        f"(95% CI: "
        f"{precision_low:.4f}-{precision_high:.4f})"
    )

    print(
        f"Sensitivity         : {sensitivity:.4f} "
        f"(95% CI: "
        f"{sensitivity_low:.4f}-{sensitivity_high:.4f})"
    )

    print(
        f"Specificity         : {specificity:.4f} "
        f"(95% CI: "
        f"{specificity_low:.4f}-{specificity_high:.4f})"
    )

    print(
        f"F1 Score            : {f1:.4f}"
    )

    print(
        f"ROC-AUC             : {roc_auc:.4f}"
    )

    print(
        f"Balanced Accuracy   : "
        f"{balanced_accuracy:.4f}"
    )

    print(
        f"MCC                 : {mcc:.4f}"
    )


    # ========================================================
    # CONFUSION MATRIX
    # ========================================================

    print(
        "\nConfusion Matrix:"
    )

    print(cm)

    print(
        "\nTN :", tn
    )

    print(
        "FP :", fp
    )

    print(
        "FN :", fn
    )

    print(
        "TP :", tp
    )


    # ========================================================
    # STORE RESULTS
    # ========================================================

    result = {

        # ---------------- CV ----------------

        "CV Accuracy":
            cv_accuracy_mean,

        "CV Precision":
            cv_precision_mean,

        "CV Sensitivity":
            cv_sensitivity_mean,

        "CV F1":
            cv_f1_mean,

        "CV ROC-AUC":
            cv_auc_mean,

        "CV Balanced Accuracy":
            cv_balanced_accuracy_mean,


        # ---------------- Test ----------------

        "Accuracy":
            accuracy,

        "Accuracy CI Low":
            acc_low,

        "Accuracy CI High":
            acc_high,


        "Precision":
            precision,

        "Precision CI Low":
            precision_low,

        "Precision CI High":
            precision_high,


        "Sensitivity":
            sensitivity,

        "Sensitivity CI Low":
            sensitivity_low,

        "Sensitivity CI High":
            sensitivity_high,


        "Specificity":
            specificity,

        "Specificity CI Low":
            specificity_low,

        "Specificity CI High":
            specificity_high,


        "F1":
            f1,

        "ROC-AUC":
            roc_auc,

        "Balanced Accuracy":
            balanced_accuracy,

        "MCC":
            mcc,


        # ---------------- Confusion Matrix ----------------

        "TN":
            tn,

        "FP":
            fp,

        "FN":
            fn,

        "TP":
            tp
    }


    return result


# ============================================================
# STEP 8: EVALUATE ALL MODELS
# ============================================================

model_names = [
    "XGBoost",
    "Random Forest",
    "HistGradientBoosting",
    "Voting Fusion",
    "Stacking Fusion"
]


results = {}

for name in model_names:

    print(
        "\n\n################################################"
    )

    print(
        f"Evaluating: {name}"
    )

    print(
        "################################################"
    )

    results[name] = evaluate_model(
        name
    )


# ============================================================
# STEP 9: FINAL RESULTS DATAFRAME
# ============================================================

results_df = pd.DataFrame(
    results
).T


# ============================================================
# STEP 10: ORDER RESULTS
# ============================================================

results_df = results_df[
    [

        # ---------------- CV ----------------

        "CV Accuracy",
        "CV Precision",
        "CV Sensitivity",
        "CV F1",
        "CV ROC-AUC",
        "CV Balanced Accuracy",


        # ---------------- Test ----------------

        "Accuracy",
        "Accuracy CI Low",
        "Accuracy CI High",

        "Precision",
        "Precision CI Low",
        "Precision CI High",

        "Sensitivity",
        "Sensitivity CI Low",
        "Sensitivity CI High",

        "Specificity",
        "Specificity CI Low",
        "Specificity CI High",

        "F1",
        "ROC-AUC",
        "Balanced Accuracy",
        "MCC",

        # ---------------- Confusion Matrix ----------------

        "TN",
        "FP",
        "FN",
        "TP"
    ]
]


# ============================================================
# STEP 11: DISPLAY FINAL RESULTS
# ============================================================

print(
    "\n================================================"
)

print(
    "FINAL MODEL COMPARISON"
)

print(
    "================================================\n"
)


display(
    results_df.sort_values(
        by="F1",
        ascending=False
    )
)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 7.8 MB/s eta 0:00:00

Raw feature statistics:
Shape : (127, 105)
NaN values before cleaning : 0
Inf values before cleaning : 0

After cleaning:
NaN values : 0
Inf values : 0
Finite     : True
Maximum    : 10000000000.0
Minimum    : -0.5821899

Final data:
X shape : (127, 105)
y shape : (127,)

Class distribution:
PD_Label_Combined
0    65
1    62
Name: count, dtype: int64

Class Weights:
{0: 0.9769230769230769, 1: 1.0241935483870968}

Train Shape : (101, 105)
Test Shape  : (26, 105)

Training Class Distribution:
PD_Label_Combined
0    52
1    49
Name: count, dtype: int64

Testing Class Distribution:
PD_Label_Combined
1    13
0    13
Name: count, dtype: int64

Training Class Weights:
{np.int64(0): np.float64(0.9711538461538461), np.int64(1): np.float64(1.030612244897959)}

XGBoost scale_pos_weight: 1.0612244897959182


################################################
Evaluating: XGBoost
################################################

XGBoost | Fold 1/10
Fold 1: max|X_val|=4.3633
Accuracy            : 0.7273
Precision           : 0.7500
Sensitivity         : 0.6000
F1 Score            : 0.6667
ROC-AUC             : 0.8667
Balanced Accuracy   : 0.7167

XGBoost | Fold 2/10
Fold 2: max|X_val|=6.5714
Accuracy            : 0.4000
Precision           : 0.3333
Sensitivity         : 0.5000
F1 Score            : 0.4000
ROC-AUC             : 0.4583
Balanced Accuracy   : 0.4167

XGBoost | Fold 3/10
Fold 3: max|X_val|=3.6450
Accuracy            : 0.6000
Precision           : 0.6000
Sensitivity         : 0.6000
F1 Score            : 0.6000
ROC-AUC             : 0.7200
Balanced Accuracy   : 0.6000

XGBoost | Fold 4/10
Fold 4: max|X_val|=4.4133
Accuracy            : 0.4000
Precision           : 0.0000
Sensitivity         : 0.0000
F1 Score            : 0.0000
ROC-AUC             : 0.4400
Balanced Accuracy   : 0.4000

XGBoost | Fold 5/10
Fold 5: max|X_val|=6.5140
Accuracy            : 0.5000
Precision           : 0.5000
Sensitivity         : 0.4000
F1 Score            : 0.4444
ROC-AUC             : 0.5400
Balanced Accuracy   : 0.5000

XGBoost | Fold 6/10
Fold 6: max|X_val|=60405414087478247205054536250032128.0000
Accuracy            : 0.8000
Precision           : 1.0000
Sensitivity         : 0.6000
F1 Score            : 0.7500
ROC-AUC             : 0.6000
Balanced Accuracy   : 0.8000

XGBoost | Fold 7/10
Fold 7: max|X_val|=3.9118
Accuracy            : 0.4000
Precision           : 0.4286
Sensitivity         : 0.6000
F1 Score            : 0.5000
ROC-AUC             : 0.6000
Balanced Accuracy   : 0.4000

XGBoost | Fold 8/10
Fold 8: max|X_val|=2.9619
Accuracy            : 0.5000
Precision           : 0.5000
Sensitivity         : 0.4000
F1 Score            : 0.4444
ROC-AUC             : 0.6000
Balanced Accuracy   : 0.5000

XGBoost | Fold 9/10
Fold 9: max|X_val|=2.8661
Accuracy            : 0.6000
Precision           : 0.6667
Sensitivity         : 0.4000
F1 Score            : 0.5000
ROC-AUC             : 0.4800
Balanced Accuracy   : 0.6000

XGBoost | Fold 10/10
Fold 10: max|X_val|=4.4014
Accuracy            : 0.7000
Precision           : 0.6250
Sensitivity         : 1.0000
F1 Score            : 0.7692
ROC-AUC             : 0.8800
Balanced Accuracy   : 0.7000

================================================
XGBoost - Cross-Validation (10-fold)
================================================
Accuracy            : 0.5627
Precision           : 0.5404
Recall/Sensitivity  : 0.5100
F1 Score            : 0.5075
ROC-AUC             : 0.6185
Balanced Accuracy   : 0.5633

================================================
XGBoost - Test Set Performance
================================================
Accuracy            : 0.6538 (95% CI: 0.4622-0.8059)
Precision           : 0.6429 (95% CI: 0.3876-0.8366)
Sensitivity         : 0.6923 (95% CI: 0.4237-0.8732)
Specificity         : 0.6154 (95% CI: 0.3552-0.8229)
F1 Score            : 0.6667
ROC-AUC             : 0.7574
Balanced Accuracy   : 0.6538
MCC                 : 0.3086

Confusion Matrix:
[[8 5]
 [4 9]]

TN : 8
FP : 5
FN : 4
TP : 9


################################################
Evaluating: Random Forest
################################################

Random Forest | Fold 1/10
Fold 1: max|X_val|=4.3633
Accuracy            : 0.7273
Precision           : 0.6250
Sensitivity         : 1.0000
F1 Score            : 0.7692
ROC-AUC             : 0.9000
Balanced Accuracy   : 0.7500

Random Forest | Fold 2/10
Fold 2: max|X_val|=6.5714
Accuracy            : 0.4000
Precision           : 0.3333
Sensitivity         : 0.5000
F1 Score            : 0.4000
ROC-AUC             : 0.5417
Balanced Accuracy   : 0.4167

Random Forest | Fold 3/10
Fold 3: max|X_val|=3.6450
Accuracy            : 0.7000
Precision           : 0.6667
Sensitivity         : 0.8000
F1 Score            : 0.7273
ROC-AUC             : 0.8400
Balanced Accuracy   : 0.7000

Random Forest | Fold 4/10
Fold 4: max|X_val|=4.4133
Accuracy            : 0.5000
Precision           : 0.5000
Sensitivity         : 0.2000
F1 Score            : 0.2857
ROC-AUC             : 0.2600
Balanced Accuracy   : 0.5000

Random Forest | Fold 5/10
Fold 5: max|X_val|=6.5140
Accuracy            : 0.7000
Precision           : 0.7500
Sensitivity         : 0.6000
F1 Score            : 0.6667
ROC-AUC             : 0.6600
Balanced Accuracy   : 0.7000

Random Forest | Fold 6/10
Fold 6: max|X_val|=60405414087478247205054536250032128.0000
Accuracy            : 0.6000
Precision           : 0.6667
Sensitivity         : 0.4000
F1 Score            : 0.5000
ROC-AUC             : 0.5200
Balanced Accuracy   : 0.6000

Random Forest | Fold 7/10
Fold 7: max|X_val|=3.9118
Accuracy            : 0.6000
Precision           : 0.6000
Sensitivity         : 0.6000
F1 Score            : 0.6000
ROC-AUC             : 0.7600
Balanced Accuracy   : 0.6000

Random Forest | Fold 8/10
Fold 8: max|X_val|=2.9619
Accuracy            : 0.5000
Precision           : 0.5000
Sensitivity         : 0.6000
F1 Score            : 0.5455
ROC-AUC             : 0.4000
Balanced Accuracy   : 0.5000

Random Forest | Fold 9/10
Fold 9: max|X_val|=2.8661
Accuracy            : 0.6000
Precision           : 0.6667
Sensitivity         : 0.4000
F1 Score            : 0.5000
ROC-AUC             : 0.5600
Balanced Accuracy   : 0.6000

Random Forest | Fold 10/10
Fold 10: max|X_val|=4.4014
Accuracy            : 0.8000
Precision           : 0.8000
Sensitivity         : 0.8000
F1 Score            : 0.8000
ROC-AUC             : 0.8400
Balanced Accuracy   : 0.8000

================================================
Random Forest - Cross-Validation (10-fold)
================================================
Accuracy            : 0.6127
Precision           : 0.6108
Recall/Sensitivity  : 0.5900
F1 Score            : 0.5794
ROC-AUC             : 0.6282
Balanced Accuracy   : 0.6167

================================================
Random Forest - Test Set Performance
================================================
Accuracy            : 0.7308 (95% CI: 0.5392-0.8630)
Precision           : 0.7500 (95% CI: 0.4677-0.9111)
Sensitivity         : 0.6923 (95% CI: 0.4237-0.8732)
Specificity         : 0.7692 (95% CI: 0.4974-0.9182)
F1 Score            : 0.7200
ROC-AUC             : 0.7929
Balanced Accuracy   : 0.7308
MCC                 : 0.4629

Confusion Matrix:
[[10  3]
 [ 4  9]]

TN : 10
FP : 3
FN : 4
TP : 9


################################################
Evaluating: HistGradientBoosting
################################################

HistGradientBoosting | Fold 1/10
Fold 1: max|X_val|=4.3633
Accuracy            : 0.6364
Precision           : 0.6000
Sensitivity         : 0.6000
F1 Score            : 0.6000
ROC-AUC             : 0.8000
Balanced Accuracy   : 0.6333

HistGradientBoosting | Fold 2/10
Fold 2: max|X_val|=6.5714
Accuracy            : 0.5000
Precision           : 0.4286
Sensitivity         : 0.7500
F1 Score            : 0.5455
ROC-AUC             : 0.4167
Balanced Accuracy   : 0.5417

HistGradientBoosting | Fold 3/10
Fold 3: max|X_val|=3.6450
Accuracy            : 0.4000
Precision           : 0.4000
Sensitivity         : 0.4000
F1 Score            : 0.4000
ROC-AUC             : 0.4400
Balanced Accuracy   : 0.4000

HistGradientBoosting | Fold 4/10
Fold 4: max|X_val|=4.4133
Accuracy            : 0.5000
Precision           : 0.5000
Sensitivity         : 0.2000
F1 Score            : 0.2857
ROC-AUC             : 0.3200
Balanced Accuracy   : 0.5000

HistGradientBoosting | Fold 5/10
Fold 5: max|X_val|=6.5140
Accuracy            : 0.6000
Precision           : 0.6667
Sensitivity         : 0.4000
F1 Score            : 0.5000
ROC-AUC             : 0.6600
Balanced Accuracy   : 0.6000

HistGradientBoosting | Fold 6/10
Fold 6: max|X_val|=60405414087478247205054536250032128.0000
Accuracy            : 0.6000
Precision           : 0.6667
Sensitivity         : 0.4000
F1 Score            : 0.5000
ROC-AUC             : 0.6000
Balanced Accuracy   : 0.6000

HistGradientBoosting | Fold 7/10
Fold 7: max|X_val|=3.9118
Accuracy            : 0.5000
Precision           : 0.5000
Sensitivity         : 0.6000
F1 Score            : 0.5455
ROC-AUC             : 0.5200
Balanced Accuracy   : 0.5000

HistGradientBoosting | Fold 8/10
Fold 8: max|X_val|=2.9619
Accuracy            : 0.5000
Precision           : 0.5000
Sensitivity         : 0.4000
F1 Score            : 0.4444
ROC-AUC             : 0.4800
Balanced Accuracy   : 0.5000

HistGradientBoosting | Fold 9/10
Fold 9: max|X_val|=2.8661
Accuracy            : 0.6000
Precision           : 0.6667
Sensitivity         : 0.4000
F1 Score            : 0.5000
ROC-AUC             : 0.6400
Balanced Accuracy   : 0.6000

HistGradientBoosting | Fold 10/10
Fold 10: max|X_val|=4.4014
Accuracy            : 0.7000
Precision           : 0.6250
Sensitivity         : 1.0000
F1 Score            : 0.7692
ROC-AUC             : 0.8800
Balanced Accuracy   : 0.7000

================================================
HistGradientBoosting - Cross-Validation (10-fold)
================================================
Accuracy            : 0.5536
Precision           : 0.5554
Recall/Sensitivity  : 0.5150
F1 Score            : 0.5090
ROC-AUC             : 0.5757
Balanced Accuracy   : 0.5575

================================================
HistGradientBoosting - Test Set Performance
================================================
Accuracy            : 0.6154 (95% CI: 0.4253-0.7757)
Precision           : 0.6154 (95% CI: 0.3552-0.8229)
Sensitivity         : 0.6154 (95% CI: 0.3552-0.8229)
Specificity         : 0.6154 (95% CI: 0.3552-0.8229)
F1 Score            : 0.6154
ROC-AUC             : 0.7396
Balanced Accuracy   : 0.6154
MCC                 : 0.2308

Confusion Matrix:
[[8 5]
 [5 8]]

TN : 8
FP : 5
FN : 5
TP : 8


################################################
Evaluating: Voting Fusion
################################################

Voting Fusion | Fold 1/10
Fold 1: max|X_val|=4.3633
Accuracy            : 0.7273
Precision           : 0.7500
Sensitivity         : 0.6000
F1 Score            : 0.6667
ROC-AUC             : 0.8333
Balanced Accuracy   : 0.7167

Voting Fusion | Fold 2/10
Fold 2: max|X_val|=6.5714
Accuracy            : 0.4000
Precision           : 0.3333
Sensitivity         : 0.5000
F1 Score            : 0.4000
ROC-AUC             : 0.4583
Balanced Accuracy   : 0.4167

Voting Fusion | Fold 3/10
Fold 3: max|X_val|=3.6450
Accuracy            : 0.5000
Precision           : 0.5000
Sensitivity         : 0.4000
F1 Score            : 0.4444
ROC-AUC             : 0.5200
Balanced Accuracy   : 0.5000

Voting Fusion | Fold 4/10
Fold 4: max|X_val|=4.4133
Accuracy            : 0.4000
Precision           : 0.0000
Sensitivity         : 0.0000
F1 Score            : 0.0000
ROC-AUC             : 0.3200
Balanced Accuracy   : 0.4000

Voting Fusion | Fold 5/10
Fold 5: max|X_val|=6.5140
Accuracy            : 0.7000
Precision           : 0.7500
Sensitivity         : 0.6000
F1 Score            : 0.6667
ROC-AUC             : 0.6200
Balanced Accuracy   : 0.7000

Voting Fusion | Fold 6/10
Fold 6: max|X_val|=60405414087478247205054536250032128.0000
Accuracy            : 0.7000
Precision           : 0.7500
Sensitivity         : 0.6000
F1 Score            : 0.6667
ROC-AUC             : 0.6000
Balanced Accuracy   : 0.7000

Voting Fusion | Fold 7/10
Fold 7: max|X_val|=3.9118
Accuracy            : 0.5000
Precision           : 0.5000
Sensitivity         : 0.6000
F1 Score            : 0.5455
ROC-AUC             : 0.6400
Balanced Accuracy   : 0.5000

Voting Fusion | Fold 8/10
Fold 8: max|X_val|=2.9619
Accuracy            : 0.5000
Precision           : 0.5000
Sensitivity         : 0.4000
F1 Score            : 0.4444
ROC-AUC             : 0.5200
Balanced Accuracy   : 0.5000

Voting Fusion | Fold 9/10
Fold 9: max|X_val|=2.8661
Accuracy            : 0.6000
Precision           : 0.6667
Sensitivity         : 0.4000
F1 Score            : 0.5000
ROC-AUC             : 0.5200
Balanced Accuracy   : 0.6000

Voting Fusion | Fold 10/10
Fold 10: max|X_val|=4.4014
Accuracy            : 0.7000
Precision           : 0.6250
Sensitivity         : 1.0000
F1 Score            : 0.7692
ROC-AUC             : 0.8400
Balanced Accuracy   : 0.7000

================================================
Voting Fusion - Cross-Validation (10-fold)
================================================
Accuracy            : 0.5727
Precision           : 0.5375
Recall/Sensitivity  : 0.5100
F1 Score            : 0.5104
ROC-AUC             : 0.5872
Balanced Accuracy   : 0.5733

================================================
Voting Fusion - Test Set Performance
================================================
Accuracy            : 0.6538 (95% CI: 0.4622-0.8059)
Precision           : 0.6429 (95% CI: 0.3876-0.8366)
Sensitivity         : 0.6923 (95% CI: 0.4237-0.8732)
Specificity         : 0.6154 (95% CI: 0.3552-0.8229)
F1 Score            : 0.6667
ROC-AUC             : 0.7574
Balanced Accuracy   : 0.6538
MCC                 : 0.3086

Confusion Matrix:
[[8 5]
 [4 9]]

TN : 8
FP : 5
FN : 4
TP : 9


################################################
Evaluating: Stacking Fusion
################################################

Stacking Fusion | Fold 1/10
Fold 1: max|X_val|=4.3633
Accuracy            : 0.3636
Precision           : 0.2500
Sensitivity         : 0.2000
F1 Score            : 0.2222
ROC-AUC             : 0.5333
Balanced Accuracy   : 0.3500

Stacking Fusion | Fold 2/10
Fold 2: max|X_val|=6.5714
Accuracy            : 0.6000
Precision           : 0.5000
Sensitivity         : 0.5000
F1 Score            : 0.5000
ROC-AUC             : 0.5000
Balanced Accuracy   : 0.5833

Stacking Fusion | Fold 3/10
Fold 3: max|X_val|=3.6450
Accuracy            : 0.4000
Precision           : 0.4286
Sensitivity         : 0.6000
F1 Score            : 0.5000
ROC-AUC             : 0.4000
Balanced Accuracy   : 0.4000

Stacking Fusion | Fold 4/10
Fold 4: max|X_val|=4.4133
Accuracy            : 0.4000
Precision           : 0.3333
Sensitivity         : 0.2000
F1 Score            : 0.2500
ROC-AUC             : 0.4800
Balanced Accuracy   : 0.4000

Stacking Fusion | Fold 5/10
Fold 5: max|X_val|=6.5140
Accuracy            : 0.6000
Precision           : 0.6667
Sensitivity         : 0.4000
F1 Score            : 0.5000
ROC-AUC             : 0.6200
Balanced Accuracy   : 0.6000

Stacking Fusion | Fold 6/10
Fold 6: max|X_val|=60405414087478247205054536250032128.0000
Accuracy            : 0.6000
Precision           : 0.5714
Sensitivity         : 0.8000
F1 Score            : 0.6667
ROC-AUC             : 0.5600
Balanced Accuracy   : 0.6000

Stacking Fusion | Fold 7/10
Fold 7: max|X_val|=3.9118
Accuracy            : 0.7000
Precision           : 0.7500
Sensitivity         : 0.6000
F1 Score            : 0.6667
ROC-AUC             : 0.6800
Balanced Accuracy   : 0.7000

Stacking Fusion | Fold 8/10
Fold 8: max|X_val|=2.9619
Accuracy            : 0.3000
Precision           : 0.3333
Sensitivity         : 0.4000
F1 Score            : 0.3636
ROC-AUC             : 0.2400
Balanced Accuracy   : 0.3000

Stacking Fusion | Fold 9/10
Fold 9: max|X_val|=2.8661
Accuracy            : 0.7000
Precision           : 1.0000
Sensitivity         : 0.4000
F1 Score            : 0.5714
ROC-AUC             : 0.7200
Balanced Accuracy   : 0.7000

Stacking Fusion | Fold 10/10
Fold 10: max|X_val|=4.4014
Accuracy            : 0.7000
Precision           : 0.7500
Sensitivity         : 0.6000
F1 Score            : 0.6667
ROC-AUC             : 0.6400
Balanced Accuracy   : 0.7000

================================================
Stacking Fusion - Cross-Validation (10-fold)
================================================
Accuracy            : 0.5364
Precision           : 0.5583
Recall/Sensitivity  : 0.4700
F1 Score            : 0.4907
ROC-AUC             : 0.5373
Balanced Accuracy   : 0.5333

================================================
Stacking Fusion - Test Set Performance
================================================
Accuracy            : 0.6154 (95% CI: 0.4253-0.7757)
Precision           : 0.6364 (95% CI: 0.3538-0.8483)
Sensitivity         : 0.5385 (95% CI: 0.2914-0.7679)
Specificity         : 0.6923 (95% CI: 0.4237-0.8732)
F1 Score            : 0.5833
ROC-AUC             : 0.6213
Balanced Accuracy   : 0.6154
MCC                 : 0.2335

Confusion Matrix:
[[9 4]
 [6 7]]

TN : 9
FP : 4
FN : 6
TP : 7

================================================
FINAL MODEL COMPARISON
================================================

,CV Accuracy,CV Precision,CV Sensitivity,CV F1,CV ROC-AUC,CV Balanced Accuracy,Accuracy,Accuracy CI Low,Accuracy CI High,Precision,...,Specificity CI Low,Specificity CI High,F1,ROC-AUC,Balanced Accuracy,MCC,TN,FP,FN,TP
Random Forest,0.612727,0.610833,0.590,0.579434,0.628167,0.616667,0.730769,0.539170,0.862956,0.750000,...,0.497436,0.918205,0.720000,0.792899,0.730769,0.462910,10.0,3.0,4.0,9.0
XGBoost,0.562727,0.540357,0.510,0.507479,0.618500,0.563333,0.653846,0.462206,0.805878,0.642857,...,0.355229,0.822903,0.666667,0.757396,0.653846,0.308607,8.0,5.0,4.0,9.0
Voting Fusion,0.572727,0.537500,0.510,0.510357,0.587167,0.573333,0.653846,0.462206,0.805878,0.642857,...,0.355229,0.822903,0.666667,0.757396,0.653846,0.308607,8.0,5.0,4.0,9.0
HistGradientBoosting,0.553636,0.555357,0.515,0.509030,0.575667,0.557500,0.615385,0.425349,0.775714,0.615385,...,0.355229,0.822903,0.615385,0.739645,0.615385,0.230769,8.0,5.0,5.0,8.0
Stacking Fusion,0.536364,0.558333,0.470,0.490729,0.537333,0.533333,0.615385,0.425349,0.775714,0.636364,...,0.423693,0.873193,0.583333,0.621302,0.615385,0.233550,9.0,4.0,6.0,7.0